<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="it" xml:lang="it"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.24">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>2&nbsp; Assiomi e coerenza delle credenze – Probabilità per la psicologia</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>

<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../chapters/probability/03_equiprobability_combinatorics_bayesian.html" rel="next">
<link href="../../chapters/probability/01_intro_prob_bayesian.html" rel="prev">
<link href="../../style/gauss.png" rel="icon" type="image/png">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dc55a5b9e770e841cd82e46aadbfb9b0.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-af5d064118ae80f4bafc3d843c3c3870.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Nessun risultato",
    "search-matching-documents-text": "documenti trovati",
    "search-copy-link-title": "Copiare il link nella ricerca",
    "search-hide-matches-text": "Nascondere i risultati aggiuntivi",
    "search-more-match-text": "ci sono altri risultati in questo documento",
    "search-more-matches-text": "ulteriori risultati in questo documento",
    "search-clear-button-title": "Pulire",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancellare",
    "search-submit-button-title": "Inviare",
    "search-label": "Ricerca"
  }
}</script><script async="" src="https://www.googletagmanager.com/gtag/js?id=G-QT5S3P9D31"></script><script type="text/javascript">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-QT5S3P9D31', { 'anonymize_ip': true});
</script><style>html{ scroll-behavior: smooth; }</style>
<script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script><script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>
</head>
<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Attiva/disattiva la barra laterale" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../chapters/probability/introduction_probability.html">Elementi di teoria della probabilità</a></li><li class="breadcrumb-item"><a href="../../chapters/probability/02_axioms_coherence_bayesian.html"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Assiomi e coerenza delle credenze</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Attiva/disattiva la barra laterale" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Ricerca" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header sidebar-header-stacked">
      <a href="../../index.html" class="sidebar-logo-link">
      </a>
    <div class="sidebar-title mb-0 py-0">
      <a href="../../">Probabilità per la psicologia</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/ccaudek/utet-prob/" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Attiva/disattiva la modalità lettore">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Ricerca"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Percorso e obiettivi</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../prefazione.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Prefazione</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../chapters/probability/introduction_probability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Elementi di teoria della probabilità</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/probability/01_intro_prob_bayesian.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Interpretazione bayesiana della probabilità</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/probability/02_axioms_coherence_bayesian.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Assiomi e coerenza delle credenze</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/probability/03_equiprobability_combinatorics_bayesian.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Equiprobabilità e calcolo combinatorio come caso limite</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/probability/04_conditional_prob_bayesian.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Probabilità condizionata come aggiornamento</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/probability/05_bayes_theorem.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Il teorema di Bayes</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/probability/06_random_var.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Variabili casuali</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/probability/07_prob_distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Distribuzioni di massa e di densità</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/probability/08_expval_var.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Proprietà delle variabili casuali</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/probability/09_sampling_distr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Stime, stimatori e parametri</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/probability/10_joint_prob.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Probabilità congiunta</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/probability/11_cov_cor.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Covarianza e correlazione</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/probability/12_intro_distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Introduzione alle distribuzioni di probabilità</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/probability/13_discr_rv_distr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Distribuzioni di v.c. discrete</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/probability/14_cont_rv_distr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Distribuzioni di v.c. continue</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/probability/15_gauss.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Assunzione di gaussianità e trasformazioni dei dati</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/probability/16_likelihood.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">La verosimiglianza</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a02_math_symbols.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Simbologia di base</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a11_numbers.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Numeri e intervalli</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a12_sum_notation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Sommatorie</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a13_sets.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">D</span>&nbsp; <span class="chapter-title">Insiemi</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a14_combinatorics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">E</span>&nbsp; <span class="chapter-title">Calcolo combinatorio</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a15_calculus.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">F</span>&nbsp; <span class="chapter-title">Per liberarvi dai terrori preliminari</span></span></a>
  </div>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Sommario</h2>
   
  <ul class="collapse">
<li><a href="#spazio-campionario-come-possibilit%C3%A0-epistemiche" id="toc-spazio-campionario-come-possibilità-epistemiche" class="nav-link active" data-scroll-target="#spazio-campionario-come-possibilit%C3%A0-epistemiche"><span class="header-section-number">2.1</span> Spazio campionario come possibilità epistemiche</a></li>
  <li><a href="#eventi-come-proposizioni-sul-mondo" id="toc-eventi-come-proposizioni-sul-mondo" class="nav-link" data-scroll-target="#eventi-come-proposizioni-sul-mondo"><span class="header-section-number">2.2</span> Eventi come proposizioni sul mondo</a></li>
  <li><a href="#gli-assiomi-di-kolmogorov-come-vincoli-di-coerenza" id="toc-gli-assiomi-di-kolmogorov-come-vincoli-di-coerenza" class="nav-link" data-scroll-target="#gli-assiomi-di-kolmogorov-come-vincoli-di-coerenza"><span class="header-section-number">2.3</span> Gli assiomi di Kolmogorov come vincoli di coerenza</a></li>
  <li><a href="#diagnosi-di-incoerenze-casi-tipici" id="toc-diagnosi-di-incoerenze-casi-tipici" class="nav-link" data-scroll-target="#diagnosi-di-incoerenze-casi-tipici"><span class="header-section-number">2.4</span> Diagnosi di incoerenze: casi tipici</a></li>
  <li><a href="#vincoli-di-fr%C3%A9chet-per-congiunzioni-di-eventi" id="toc-vincoli-di-fréchet-per-congiunzioni-di-eventi" class="nav-link" data-scroll-target="#vincoli-di-fr%C3%A9chet-per-congiunzioni-di-eventi"><span class="header-section-number">2.5</span> Vincoli di Fréchet per congiunzioni di eventi</a></li>
  <li><a href="#tabelle-di-probabilit%C3%A0-congiunta" id="toc-tabelle-di-probabilità-congiunta" class="nav-link" data-scroll-target="#tabelle-di-probabilit%C3%A0-congiunta"><span class="header-section-number">2.6</span> Tabelle di probabilità congiunta</a></li>
  <li><a href="#calcolo-di-probabilit%C3%A0-marginali-e-condizionate" id="toc-calcolo-di-probabilità-marginali-e-condizionate" class="nav-link" data-scroll-target="#calcolo-di-probabilit%C3%A0-marginali-e-condizionate"><span class="header-section-number">2.7</span> Calcolo di probabilità marginali e condizionate</a></li>
  <li><a href="#esercizio-guidato-costruire-e-analizzare-una-tabella-22" id="toc-esercizio-guidato-costruire-e-analizzare-una-tabella-22" class="nav-link" data-scroll-target="#esercizio-guidato-costruire-e-analizzare-una-tabella-22"><span class="header-section-number">2.8</span> Esercizio guidato: costruire e analizzare una tabella 2×2</a></li>
  <li><a href="#estensione-a-tabelle-multidimensionali" id="toc-estensione-a-tabelle-multidimensionali" class="nav-link" data-scroll-target="#estensione-a-tabelle-multidimensionali"><span class="header-section-number">2.9</span> Estensione a tabelle multidimensionali</a></li>
  </ul><div class="toc-actions"><ul class="collapse"><li><a href="https://github.com/ccaudek/utet-prob/blob/main/chapters/probability/02_axioms_coherence_bayesian.qmd" class="toc-action"><i class="bi bi-github"></i>Mostra il codice</a></li><li><a href="https://github.com/ccaudek/utet-prob/issues/new" class="toc-action"><i class="bi empty"></i>Segnala un problema</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../chapters/probability/introduction_probability.html">Elementi di teoria della probabilità</a></li><li class="breadcrumb-item"><a href="../../chapters/probability/02_axioms_coherence_bayesian.html"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Assiomi e coerenza delle credenze</span></a></li></ol></nav><div class="quarto-title">
<h1 class="title"><span id="sec-prob-models" class="quarto-section-identifier"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Assiomi e coerenza delle credenze</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header><section id="introduzione" class="level2 unnumbered unlisted"><h2 class="unnumbered unlisted anchored" data-anchor-id="introduzione">Introduzione</h2>
<p>Dopo aver introdotto la probabilità come <em>grado di credenza razionale</em> nel <a href="01_intro_prob_bayesian.html" class="quarto-xref"><span>Capitolo 1</span></a>, questo capitolo sviluppa il framework matematico per operare in modo coerente con le credenze. Esploreremo come lo <em>spazio campionario</em> e gli <em>eventi</em> rappresentino possibilità epistemiche, e come gli <em>assiomi di Kolmogorov</em> fungano da vincoli di coerenza logica.</p>
<p>Un aspetto cruciale che affronteremo è la costruzione e manipolazione di <em>tabelle di probabilità congiunta</em>, che costituiscono lo strumento operativo fondamentale per rappresentare credenze su sistemi complessi. Queste tabelle, in particolare nel caso semplice 2×2, rendono esplicita la relazione tra probabilità <em>congiunte</em>, <em>marginali</em> e <em>condizionate</em>, mostrando che tutte le probabilità di interesse derivano da un’unica struttura coerente.</p>
<p>Attraverso esempi psicologici concreti e simulazioni in R, vedremo come diagnosticare e correggere le incoerenze nelle assegnazioni probabilistiche e come verificare empiricamente che le credenze coerenti producano i dati attesi.</p>
<section id="panoramica-del-capitolo" class="level3 unnumbered unlisted"><h3 class="unnumbered unlisted anchored" data-anchor-id="panoramica-del-capitolo">Panoramica del capitolo</h3>
<ul>
<li>Spazio campionario ed eventi come possibilità epistemiche.</li>
<li>Assiomi di Kolmogorov come vincoli di coerenza.</li>
<li>Diagnosi di incoerenze: additività e vincoli di Fréchet.</li>
<li>Tabelle di probabilità congiunta (2×2 e oltre).</li>
<li>Derivazione di marginali e condizionate da congiunte.</li>
<li>Verifica empirica della coerenza con simulazioni.</li>
</ul>
<div class="callout callout-style-simple callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Consiglio</span>Prerequisiti
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li>Aver letto il <a href="01_intro_prob_bayesian.html" class="quarto-xref"><span>Capitolo 1</span></a>.</li>
<li>Leggere l’<a href="../appendix/a13_sets.html" class="quarto-xref"><span>Appendice D</span></a> (teoria degli insiemi).</li>
<li>Familiarità base con R e ggplot2.</li>
</ul>
</div>
</div>
</div>
<div class="callout callout-style-simple callout-caution no-icon callout-titled" title="Preparazione del Notebook">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Attenzione</span>Preparazione del Notebook
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">here</span><span class="fu">::</span><span class="fu"><a href="https://here.r-lib.org/reference/here.html">here</a></span><span class="op">(</span><span class="st">"code"</span>, <span class="st">"_common.R"</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="kw"><a href="https://rdrr.io/r/base/source.html">source</a></span><span class="op">(</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Load packages</span></span>
<span><span class="kw">if</span> <span class="op">(</span><span class="op">!</span><span class="fu"><a href="https://rdrr.io/r/base/ns-load.html">requireNamespace</a></span><span class="op">(</span><span class="st">"pacman"</span><span class="op">)</span><span class="op">)</span> <span class="fu"><a href="https://rdrr.io/r/utils/install.packages.html">install.packages</a></span><span class="op">(</span><span class="st">"pacman"</span><span class="op">)</span></span>
<span><span class="fu">pacman</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/pacman/man/p_load.html">p_load</a></span><span class="op">(</span><span class="va">ggplot2</span>, <span class="va">dplyr</span>, <span class="va">tidyr</span>, <span class="va">viridis</span><span class="op">)</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
</div>
</div>
</section></section><section id="spazio-campionario-come-possibilità-epistemiche" class="level2" data-number="2.1"><h2 data-number="2.1" class="anchored" data-anchor-id="spazio-campionario-come-possibilità-epistemiche">
<span class="header-section-number">2.1</span> Spazio campionario come possibilità epistemiche</h2>
<p>Nel linguaggio classico, lo spazio campionario <span class="math inline">\(\Omega\)</span> (o <span class="math inline">\(S\)</span>) viene definito come “l’insieme di tutti gli esiti possibili di un esperimento casuale”. Nell’approccio bayesiano, tale definizione va reinterpretata in chiave epistemica.</p>
<div id="def-sample-space-bayesian" class="theorem definition">
<p><span class="theorem-title"><strong>Definizione 2.1 (Spazio campionario (visione bayesiana))</strong></span> Lo <em>spazio campionario</em> <span class="math inline">\(\Omega\)</span> rappresenta l’insieme delle <em>possibilità epistemiche</em> compatibili con le informazioni disponibili. Esso non rappresenta ciò che può accadere fisicamente, ma ciò che, dati gli attuali limiti della nostra conoscenza, consideriamo possibile.</p>
</div>
<section id="caratteristiche-dello-spazio-campionario-epistemico" class="level3" data-number="2.1.1"><h3 data-number="2.1.1" class="anchored" data-anchor-id="caratteristiche-dello-spazio-campionario-epistemico">
<span class="header-section-number">2.1.1</span> Caratteristiche dello spazio campionario epistemico</h3>
<ol type="1">
<li><p><strong>Dipendente dall’informazione</strong>: lo spazio campionario può cambiare si acquisiscono nuove informazioni. Prima di osservare i risultati di un test diagnostico, lo spazio include i i valori {positivo, negativo}. Dopo aver osservato “positivo”, lo spazio si riduce.</p></li>
<li><p><strong>Non univoco</strong>: ricercatori diversi, con informazioni diverse, possono definire spazi campionari diversi per lo stesso fenomeno.</p></li>
<li><p><strong>Costruzione</strong>: definire <span class="math inline">\(\Omega\)</span> richiede di specificare il <em>livello di dettaglio rilevante</em> per la domanda di interesse.</p></li>
</ol>
<div class="callout callout-style-simple callout-note no-icon callout-titled" title="Esempio psicologico">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Esempio psicologico
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<section id="spazio-campionario-per-una-valutazione-clinica" class="level3 unnumbered unlisted callout-body-container callout-body"><h3 class="unnumbered unlisted anchored" data-anchor-id="spazio-campionario-per-una-valutazione-clinica">Spazio campionario per una valutazione clinica</h3>
<p>Consideriamo la valutazione di un paziente per possibile depressione. Lo spazio campionario può essere definito in modi diversi a seconda delle informazioni e degli obiettivi:</p>
<p><strong>Livello 1 (binario):</strong> <span class="math display">\[\Omega_1 = \{\text{Depresso}, \text{Non depresso}\}.\]</span></p>
<p><strong>Livello 2 (severità):</strong> <span class="math display">\[\Omega_2 = \{\text{Nessuna}, \text{Lieve}, \text{Moderata}, \text{Severa}\}.\]</span></p>
<p><strong>Livello 3 (combinazioni):</strong> <span class="math display">\[\Omega_3 = \{\text{Depressione}, \text{Ansia}, \text{Comorbidità}, \text{Nessuna}\}.\]</span></p>
<p>La scelta dipende da:</p>
<ul>
<li>informazioni disponibili (screening, test, colloquio);</li>
<li>obiettivo clinico (screening vs diagnosi differenziale);</li>
<li>decisioni da prendere (trattamento, monitoraggio).</li>
</ul>
<p>Ogni spazio è legittimo nel proprio contesto. La probabilità assegnata riflette la credenza in quello specifico spazio.</p>
</section>
</div>
</div>
</section></section><section id="eventi-come-proposizioni-sul-mondo" class="level2" data-number="2.2"><h2 data-number="2.2" class="anchored" data-anchor-id="eventi-come-proposizioni-sul-mondo">
<span class="header-section-number">2.2</span> Eventi come proposizioni sul mondo</h2>
<p>Un <em>evento</em> è un sottoinsieme di <span class="math inline">\(\Omega\)</span> che rappresenta una <em>proposizione</em> sul mondo che può essere vera o falsa.</p>
<div id="def-event-bayesian" class="theorem definition">
<p><span class="theorem-title"><strong>Definizione 2.2 (Evento)</strong></span> Un <em>evento</em> <span class="math inline">\(A \subseteq \Omega\)</span> è una <em>proposizione</em> sul mondo a cui possiamo assegnare un grado di credenza <span class="math inline">\(P(A)\)</span>, dato lo stato di informazione corrente.</p>
</div>
<section id="operazioni-su-eventi" class="level3" data-number="2.2.1"><h3 data-number="2.2.1" class="anchored" data-anchor-id="operazioni-su-eventi">
<span class="header-section-number">2.2.1</span> Operazioni su eventi</h3>
<p>Le operazioni insiemistiche classiche hanno interpretazioni epistemiche naturali:</p>
<ul>
<li>
<strong>Unione</strong> <span class="math inline">\(A \cup B\)</span>: “La proposizione <span class="math inline">\(A\)</span> <em>oppure</em> la proposizione <span class="math inline">\(B\)</span> è vera”.</li>
<li>
<strong>Intersezione</strong> <span class="math inline">\(A \cap B\)</span>: “Entrambe le proposizioni <span class="math inline">\(A\)</span> <em>e</em> <span class="math inline">\(B\)</span> sono vere”.</li>
<li>
<strong>Complemento</strong> <span class="math inline">\(A^c\)</span>: “La proposizione <span class="math inline">\(A\)</span> <em>non</em> è vera”.</li>
<li>
<strong>Insieme vuoto</strong> <span class="math inline">\(\varnothing\)</span>: “Proposizione logicamente contraddittoria (sempre falsa per necessità logica)”.</li>
<li>
<strong>Spazio campionario</strong> <span class="math inline">\(\Omega\)</span>: “Proposizione logicamente vera: qualcosa accade nell’insieme”.</li>
</ul>
<div class="callout callout-style-simple callout-note no-icon callout-titled" title="Esempio: Eventi in un test psicometrico">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Esempio: Eventi in un test psicometrico
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<section id="proposizioni-nella-satisfaction-with-life-scale-swls" class="level3 callout-body-container callout-body" data-number="2.2.2"><h3 data-number="2.2.2" class="anchored" data-anchor-id="proposizioni-nella-satisfaction-with-life-scale-swls">
<span class="header-section-number">2.2.2</span> Proposizioni nella Satisfaction with Life Scale (SWLS)</h3>
<p>La SWLS ha punteggi che vanno da 5 a 35. Definiamo:</p>
<ul>
<li>
<span class="math inline">\(\Omega = \{5, 6, 7, \ldots, 35\}\)</span> (possibili punteggi).</li>
<li>
<span class="math inline">\(A =\)</span> “Punteggio ≥ 25” (alta soddisfazione) <span class="math inline">\(= \{25, 26, \ldots, 35\}\)</span>.</li>
<li>
<span class="math inline">\(B =\)</span> “Punteggio ≤ 15” (bassa soddisfazione) <span class="math inline">\(= \{5, 6, \ldots, 15\}\)</span>.</li>
<li>
<span class="math inline">\(C =\)</span> “Punteggio tra 16 e 24” (soddisfazione moderata) <span class="math inline">\(= \{16, 17, \ldots, 24\}\)</span>.</li>
</ul>
<p>Operazioni:</p>
<ul>
<li>
<span class="math inline">\(A \cup B\)</span>: “Soddisfazione alta <em>o</em> bassa” (non moderata).</li>
<li>
<span class="math inline">\(A \cap B = \varnothing\)</span>: proposizioni mutualmente esclusive (impossibile avere entrambi).</li>
<li>
<span class="math inline">\(A^c = B \cup C\)</span>: “Non alta soddisfazione”.</li>
<li>
<span class="math inline">\(A \cup B \cup C = \Omega\)</span>: proposizioni esaustive.</li>
</ul>
<p>La credenza <span class="math inline">\(P(A)\)</span> quantifica quanto riteniamo plausibile, in base a ciò che sappiamo (popolazione, contesto), che un individuo scelto abbia un’alta soddisfazione.</p>
</section>
</div>
</div>
</section></section><section id="gli-assiomi-di-kolmogorov-come-vincoli-di-coerenza" class="level2" data-number="2.3"><h2 data-number="2.3" class="anchored" data-anchor-id="gli-assiomi-di-kolmogorov-come-vincoli-di-coerenza">
<span class="header-section-number">2.3</span> Gli assiomi di Kolmogorov come vincoli di coerenza</h2>
<p>Nel <a href="01_intro_prob_bayesian.html" class="quarto-xref"><span>Capitolo 1</span></a> abbiamo visto che gli assiomi di Kolmogorov non sono leggi naturali ma vincoli per evitare incoerenze (il cosiddetto <em>Dutch Book</em>). Qui li formalizziamo e approfondiamo le loro implicazioni.</p>
<div id="def-probability-measure" class="theorem definition">
<p><span class="theorem-title"><strong>Definizione 2.3 (Funzione di probabilità (definizione bayesiana))</strong></span> Una <em>funzione di probabilità</em> <span class="math inline">\(P: \mathcal{F} \to [0,1]\)</span> assegna a ogni evento <span class="math inline">\(A\)</span> in una famiglia di eventi <span class="math inline">\(\mathcal{F}\)</span> un numero <span class="math inline">\(P(A)\)</span> che rappresenta il grado di credenza nell’affermazione <span class="math inline">\(A\)</span>. Per essere coerente, <span class="math inline">\(P\)</span> deve soddisfare i seguenti <em>assiomi di coerenza</em>:</p>
<ol type="1">
<li><p><strong>Non-negatività</strong>: <span class="math inline">\(P(A) \geq 0\)</span> per ogni evento <span class="math inline">\(A\)</span>.</p></li>
<li><p><strong>Normalizzazione</strong>: <span class="math inline">\(P(\Omega) = 1\)</span>.</p></li>
<li><p><strong>Additività finita</strong>: se <span class="math inline">\(A\)</span> e <span class="math inline">\(B\)</span> sono eventi disgiunti (<span class="math inline">\(A \cap B = \varnothing\)</span>), allora <span class="math display">\[P(A \cup B) = P(A) + P(B).\]</span></p></li>
<li><p><strong>Additività numerabile</strong> (per spazi infiniti): se <span class="math inline">\(A_1, A_2, \ldots\)</span> è una sequenza di eventi mutuamente disgiunti, allora <span class="math display">\[P\left(\bigcup_{i=1}^{\infty} A_i\right) = \sum_{i=1}^{\infty} P(A_i).\]</span></p></li>
</ol>
</div>
<section id="interpretazione-epistemica-degli-assiomi" class="level3" data-number="2.3.1"><h3 data-number="2.3.1" class="anchored" data-anchor-id="interpretazione-epistemica-degli-assiomi">
<span class="header-section-number">2.3.1</span> Interpretazione epistemica degli assiomi</h3>
<ol type="1">
<li><p><strong>Non-negatività</strong>: un grado di credenza negativo non ha senso; zero significa “impossibile dato ciò che so”, uno significa “certo dato ciò che so”.</p></li>
<li><p><strong>Normalizzazione</strong>: sono certo che <em>qualcosa</em> nello spazio delle possibilità si verificherà. Se <span class="math inline">\(P(\Omega) &lt; 1\)</span>, sto ammettendo la possibilità che nulla di ciò che ho preso in considerazione accada, il che è incoerente.</p></li>
<li><p><strong>Additività</strong>: se due affermazioni sono mutualmente esclusive, la credenza nella loro disgiunzione è la somma delle credenze separate; violare questo principio porta al cosiddetto <em>Dutch Book</em>.</p></li>
</ol></section><section id="conseguenze-immediate-degli-assiomi" class="level3" data-number="2.3.2"><h3 data-number="2.3.2" class="anchored" data-anchor-id="conseguenze-immediate-degli-assiomi">
<span class="header-section-number">2.3.2</span> Conseguenze immediate degli assiomi</h3>
<p>Dagli assiomi derivano diverse proprietà utili:</p>
<div id="thm-probability-properties" class="theorem">
<p><span class="theorem-title"><strong>Teorema 2.1 (Proprietà derivate della probabilità)</strong></span> &nbsp;</p>
<ol type="1">
<li>
<strong>Probabilità del complemento</strong>: <span class="math inline">\(P(A^c) = 1 - P(A)\)</span>.</li>
<li>
<strong>Probabilità dell’insieme vuoto</strong>: <span class="math inline">\(P(\varnothing) = 0\)</span>.</li>
<li>
<strong>Monotonia</strong>: se <span class="math inline">\(A \subseteq B\)</span>, allora <span class="math inline">\(P(A) \leq P(B)\)</span>.</li>
<li>
<strong>Regola dell’unione</strong> (eventi non disgiunti): <span class="math display">\[P(A \cup B) = P(A) + P(B) - P(A \cap B).\]</span>
</li>
<li>
<strong>Principio di inclusione-esclusione</strong> (generalizzazione): <span class="math display">\[P(A_1 \cup A_2 \cup A_3) = \sum P(A_i) - \sum P(A_i \cap A_j) + P(A_1 \cap A_2 \cap A_3).\]</span>
</li>
</ol>
</div>
<p>Queste proprietà non sono assiomi aggiuntivi, ma conseguenze logiche dei tre assiomi di base. Una volta accettati i vincoli di coerenza, tutto il resto ne consegue necessariamente.</p>
</section></section><section id="diagnosi-di-incoerenze-casi-tipici" class="level2" data-number="2.4"><h2 data-number="2.4" class="anchored" data-anchor-id="diagnosi-di-incoerenze-casi-tipici">
<span class="header-section-number">2.4</span> Diagnosi di incoerenze: casi tipici</h2>
<p>Vediamo come identificare e correggere incoerenze comuni nelle assegnazioni probabilistiche.</p>
<section id="incoerenza-1-violazione-delladditività" class="level3" data-number="2.4.1"><h3 data-number="2.4.1" class="anchored" data-anchor-id="incoerenza-1-violazione-delladditività">
<span class="header-section-number">2.4.1</span> Incoerenza 1: Violazione dell’additività</h3>
<p>L’errore più frequente è violare l’additività per eventi disgiunti, assegnando una probabilità maggiore di quella logicamente possibile.</p>
<div class="callout callout-style-simple callout-warning no-icon callout-titled" title="Esempio di incoerenza clinica">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Avviso</span>Esempio di incoerenza clinica
</div>
</div>
<section id="sovrastima-delle-probabilità" class="level4 unlisted unnumbered callout-body-container callout-body"><h4 class="unlisted unnumbered anchored" data-anchor-id="sovrastima-delle-probabilità">Sovrastima delle probabilità</h4>
<p>Un clinico assegna le seguenti credenze per tre diagnosi mutualmente esclusive:</p>
<ul>
<li>
<span class="math inline">\(P(\text{Depressione}) = 0.6\)</span>;</li>
<li>
<span class="math inline">\(P(\text{Ansia}) = 0.5\)</span>;<br>
</li>
<li>
<span class="math inline">\(P(\text{Nessuna condizione}) = 0.2\)</span>.</li>
</ul>
<p>Il problema è che <span class="math inline">\(0.6 + 0.5 + 0.2 = 1.3 &gt; 1\)</span>.</p>
<p>Questa assegnazione è incoerente perché i tre eventi sono:</p>
<ul>
<li>
<em>mutualmente esclusivi</em>: il paziente può avere solo una delle tre condizioni;</li>
<li>
<em>collettivamente esaustivi</em>: coprono tutti i casi possibili.</li>
</ul>
<p>Il clinico ha quindi “speso” più credenza (1.3) di quanta ne disponesse (1.0), come se avesse il 130% di certezza invece del 100%.</p>
</section>
</div>
<div class="cell" data-layout-align="center">
<pre><code>#&gt; Probabilità assegnate:
#&gt; Depressione       Ansia     Nessuna 
#&gt;         0.6         0.5         0.2
#&gt; 
#&gt; Somma totale: 1.3
#&gt; ⚠️ INCOERENZA RILEVATA: Per eventi mutuamente esclusivi ed esaustivi,
#&gt;    la somma delle probabilità deve essere esattamente 1.
#&gt;    Eccesso di credenza: 0.3</code></pre>
</div>
<p><strong>Strategie di correzione</strong>:</p>
<ol type="1">
<li>
<strong>Normalizzazione proporzionale</strong> (se le proporzioni relative sono giudicate corrette):</li>
</ol>
<div class="cell" data-layout-align="center">
<pre><code>#&gt; Probabilità normalizzate (mantenendo le proporzioni):
#&gt; Depressione       Ansia     Nessuna 
#&gt;       0.462       0.385       0.154
#&gt; Nuova somma: 1</code></pre>
</div>
<ol start="2" type="1">
<li>
<p><strong>Revisione critica</strong> (approccio preferibile): rivalutare ciascuna assegnazione alla luce dell’incoerenza scoperta, considerando:</p>
<ul>
<li>prevalenze nella popolazione di riferimento;</li>
<li>evidenze cliniche specifiche del caso;</li>
<li>possibile sovrastima di condizioni ritenute più salienti.</li>
</ul>
</li>
</ol></section><section id="visualizzazione-dellincoerenza" class="level3" data-number="2.4.2"><h3 data-number="2.4.2" class="anchored" data-anchor-id="visualizzazione-dellincoerenza">
<span class="header-section-number">2.4.2</span> Visualizzazione dell’incoerenza</h3>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="02_axioms_coherence_bayesian_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:85.0%"></p>
</figure>
</div>
</div>
</div>
</section></section><section id="vincoli-di-fréchet-per-congiunzioni-di-eventi" class="level2" data-number="2.5"><h2 data-number="2.5" class="anchored" data-anchor-id="vincoli-di-fréchet-per-congiunzioni-di-eventi">
<span class="header-section-number">2.5</span> Vincoli di Fréchet per congiunzioni di eventi</h2>
<p>Quando consideriamo due eventi che <em>possono verificarsi insieme</em>, la probabilità della loro intersezione <span class="math inline">\(P(A \cap B)\)</span> non può essere scelta liberamente, ma deve rispettare precisi vincoli matematici.</p>
<div id="thm-frechet-bounds" class="theorem">
<p><span class="theorem-title"><strong>Teorema 2.2 (Vincoli di Fréchet)</strong></span> Per qualsiasi coppia di eventi <span class="math inline">\(A\)</span> e <span class="math inline">\(B\)</span> vale:</p>
<p><span class="math display">\[
\max\{0,\, P(A) + P(B) - 1\} \;\leq\; P(A \cap B) \;\leq\; \min\{P(A), P(B)\}.
\]</span></p>
<p><strong>Interpretazione intuitiva:</strong></p>
<ul>
<li>
<strong>Limite superiore</strong>: l’evento “<span class="math inline">\(A\)</span> e <span class="math inline">\(B\)</span> insieme” non può essere più probabile dell’evento singolo meno probabile tra <span class="math inline">\(A\)</span> e <span class="math inline">\(B\)</span>.</li>
<li>
<strong>Limite inferiore</strong>: se la somma delle probabilità individuali supera 1, allora <span class="math inline">\(A\)</span> e <span class="math inline">\(B\)</span> <em>devono</em> sovrapporsi almeno in parte.</li>
</ul>
</div>
<div class="callout callout-style-simple callout-note no-icon callout-titled" title="Esempio clinico: Depressione e Ansia">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Esempio clinico: Depressione e Ansia
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<section id="applicazione-alla-comorbidità-psicologica" class="level4 unnumbered unlisted callout-body-container callout-body"><h4 class="unnumbered unlisted anchored" data-anchor-id="applicazione-alla-comorbidità-psicologica">Applicazione alla comorbidità psicologica</h4>
<p>Consideriamo uno studio su una popolazione clinica in cui:</p>
<ul>
<li>
<span class="math inline">\(P(\text{Depressione}) = 0.6\)</span> (60% è depresso);</li>
<li>
<span class="math inline">\(P(\text{Ansia}) = 0.5\)</span> (50% è ansioso).</li>
</ul>
<p>Quali valori sono logicamente possibili per la comorbidità <span class="math inline">\(P(\text{Depressione} \cap \text{Ansia})\)</span>?</p>
<p><strong>Calcolo dei limiti:</strong></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb4"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">P_Depressione</span> <span class="op">&lt;-</span> <span class="fl">0.6</span></span>
<span><span class="va">P_Ansia</span> <span class="op">&lt;-</span> <span class="fl">0.5</span></span>
<span></span>
<span><span class="va">limite_inferiore</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/Extremes.html">max</a></span><span class="op">(</span><span class="fl">0</span>, <span class="va">P_Depressione</span> <span class="op">+</span> <span class="va">P_Ansia</span> <span class="op">-</span> <span class="fl">1</span><span class="op">)</span></span>
<span><span class="va">limite_superiore</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/Extremes.html">min</a></span><span class="op">(</span><span class="va">P_Depressione</span>, <span class="va">P_Ansia</span><span class="op">)</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell" data-layout-align="center">
<pre><code>#&gt; VINCOLI DI FRÉCHET - Depressione e Ansia
#&gt; =========================================
#&gt; P(Depressione) = 0.6
#&gt; P(Ansia) = 0.5
#&gt; ---
#&gt; Limite inferiore: max(0, 0.6 + 0.5 - 1) = 0.1
#&gt; Limite superiore: min(0.6, 0.5) = 0.5
#&gt; ---
#&gt; INTERVALLO AMMISSIBILE:
#&gt; 0.1 ≤ P(Depressione ∩ Ansia) ≤ 0.5</code></pre>
</div>
<p><strong>Risultato:</strong> <span class="math inline">\(0.1 \leq P(\text{Comorbidità}) \leq 0.5\)</span>.</p>
<p><strong>Cosa significa nella pratica:</strong></p>
<ul>
<li>❌ <strong>Incoerente</strong>: dire che solo il 5% ha comorbidità (<span class="math inline">\(&lt; 0.1\)</span>) è impossibile;</li>
<li>❌ <strong>Incoerente</strong>: dire che il 60% ha comorbidità (<span class="math inline">\(&gt; 0.5\)</span>) è impossibile;</li>
<li>✅ <strong>Coerente</strong>: qualsiasi valore tra 10% e 50% è logicamente possibile.</li>
</ul></section>
</div>
</div>
<section id="mappa-dei-valori-ammissibili" class="level3" data-number="2.5.1"><h3 data-number="2.5.1" class="anchored" data-anchor-id="mappa-dei-valori-ammissibili">
<span class="header-section-number">2.5.1</span> Mappa dei valori ammissibili</h3>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb6"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Creare griglia di valori</span></span>
<span><span class="va">grid</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/expand.grid.html">expand.grid</a></span><span class="op">(</span></span>
<span>  P_A <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq</a></span><span class="op">(</span><span class="fl">0</span>, <span class="fl">1</span>, by <span class="op">=</span> <span class="fl">0.02</span><span class="op">)</span>,</span>
<span>  P_B <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq</a></span><span class="op">(</span><span class="fl">0</span>, <span class="fl">1</span>, by <span class="op">=</span> <span class="fl">0.02</span><span class="op">)</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Calcolare vincoli per ogni coppia</span></span>
<span><span class="va">grid</span><span class="op">$</span><span class="va">limite_inferiore</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/Extremes.html">pmax</a></span><span class="op">(</span><span class="fl">0</span>, <span class="va">grid</span><span class="op">$</span><span class="va">P_A</span> <span class="op">+</span> <span class="va">grid</span><span class="op">$</span><span class="va">P_B</span> <span class="op">-</span> <span class="fl">1</span><span class="op">)</span></span>
<span><span class="va">grid</span><span class="op">$</span><span class="va">limite_superiore</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/Extremes.html">pmin</a></span><span class="op">(</span><span class="va">grid</span><span class="op">$</span><span class="va">P_A</span>, <span class="va">grid</span><span class="op">$</span><span class="va">P_B</span><span class="op">)</span></span>
<span><span class="va">grid</span><span class="op">$</span><span class="va">ampiezza_lecita</span> <span class="op">&lt;-</span> <span class="va">grid</span><span class="op">$</span><span class="va">limite_superiore</span> <span class="op">-</span> <span class="va">grid</span><span class="op">$</span><span class="va">limite_inferiore</span></span>
<span></span>
<span><span class="co"># Visualizzazione</span></span>
<span><span class="fu">ggplot</span><span class="op">(</span><span class="va">grid</span>, <span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">P_A</span>, y <span class="op">=</span> <span class="va">P_B</span>, fill <span class="op">=</span> <span class="va">ampiezza_lecita</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_tile</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">scale_fill_viridis_c</span><span class="op">(</span></span>
<span>    name <span class="op">=</span> <span class="st">"Ampiezza dell'intervallo\nammissibile"</span>,</span>
<span>    option <span class="op">=</span> <span class="st">"plasma"</span>,</span>
<span>    limits <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0</span>, <span class="fl">1</span><span class="op">)</span></span>
<span>  <span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">labs</span><span class="op">(</span></span>
<span>    title <span class="op">=</span> <span class="st">"Vincoli di Fréchet: intervalli ammissibili per P(A ∩ B)"</span>,</span>
<span>    subtitle <span class="op">=</span> <span class="st">"Per ogni coppia (P(A), P(B)), l'area colorata mostra quanti valori di P(A ∩ B) \nsono logicamente possibili"</span>,</span>
<span>    x <span class="op">=</span> <span class="st">"P(A)"</span>,</span>
<span>    y <span class="op">=</span> <span class="st">"P(B)"</span>,</span>
<span>    caption <span class="op">=</span> <span class="st">"Colori più chiari = maggiore libertà nella scelta di P(A ∩ B)"</span></span>
<span>  <span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">theme_minimal</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">theme</span><span class="op">(</span>legend.position <span class="op">=</span> <span class="st">"right"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">coord_fixed</span><span class="op">(</span><span class="op">)</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="02_axioms_coherence_bayesian_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption>Regione dei valori ammissibili per P(A ∩ B) in funzione di P(A) e P(B)</figcaption></figure>
</div>
</div>
</div>
<p><strong>Come leggere questa mappa:</strong></p>
<ul>
<li>
<strong>🔵 Blu scuro</strong> (angoli): vincoli molto stringenti - pochi valori di <span class="math inline">\(P(A \cap B)\)</span> sono possibili;</li>
<li>
<strong>🟡 Giallo</strong> (centro): massima libertà - molti valori di <span class="math inline">\(P(A \cap B)\)</span> sono ammissibili;</li>
<li>
<strong>Regione in alto a destra</strong>: quando <span class="math inline">\(P(A) + P(B) &gt; 1\)</span>, è necessaria una sovrapposizione minima obbligatoria;</li>
<li>
<strong>Regione in basso a sinistra</strong>: quando <span class="math inline">\(P(A) + P(B) \leq 1\)</span>, la sovrapposizione può essere anche nulla.</li>
</ul>
<blockquote class="blockquote">
<p><strong>Importante per la pratica clinica</strong>: questi vincoli ci proteggono dall’assegnare probabilità logicamente impossibili a sintomi che si presentano insieme o a condizioni che co-occorrono.</p>
</blockquote>
</section></section><section id="tabelle-di-probabilità-congiunta" class="level2" data-number="2.6"><h2 data-number="2.6" class="anchored" data-anchor-id="tabelle-di-probabilità-congiunta">
<span class="header-section-number">2.6</span> Tabelle di probabilità congiunta</h2>
<p>Le <strong>tabelle di probabilità congiunta</strong> sono lo strumento fondamentale per rappresentare le credenze su sistemi con più variabili. Rendono esplicite tutte le relazioni tra gli eventi.</p>
<section id="struttura-di-una-tabella-22" class="level3" data-number="2.6.1"><h3 data-number="2.6.1" class="anchored" data-anchor-id="struttura-di-una-tabella-22">
<span class="header-section-number">2.6.1</span> Struttura di una tabella 2×2</h3>
<p>Consideriamo due eventi binari <span class="math inline">\(A\)</span> e <span class="math inline">\(B\)</span>. La tabella congiunta ha questa struttura:</p>
<table class="caption-top table">
<thead><tr class="header">
<th></th>
<th><span class="math inline">\(B\)</span></th>
<th><span class="math inline">\(B^c\)</span></th>
<th>Marginale</th>
</tr></thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(A\)</span></td>
<td><span class="math inline">\(P(A \cap B)\)</span></td>
<td><span class="math inline">\(P(A \cap B^c)\)</span></td>
<td><span class="math inline">\(P(A)\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(A^c\)</span></td>
<td><span class="math inline">\(P(A^c \cap B)\)</span></td>
<td><span class="math inline">\(P(A^c \cap B^c)\)</span></td>
<td><span class="math inline">\(P(A^c)\)</span></td>
</tr>
<tr class="odd">
<td><strong>Marginale</strong></td>
<td><span class="math inline">\(P(B)\)</span></td>
<td><span class="math inline">\(P(B^c)\)</span></td>
<td><span class="math inline">\(1\)</span></td>
</tr>
</tbody>
</table>
<p><strong>Proprietà chiave:</strong></p>
<ol type="1">
<li>
<strong>Celle interne</strong>: probabilità congiunte (4 valori)</li>
<li>
<strong>Marginali di riga</strong>: <span class="math inline">\(P(A) = P(A \cap B) + P(A \cap B^c)\)</span>
</li>
<li>
<strong>Marginali di colonna</strong>: <span class="math inline">\(P(B) = P(A \cap B) + P(A^c \cap B)\)</span>
</li>
<li>
<strong>Normalizzazione</strong>: la somma di tutte le celle è uguale a 1.</li>
</ol>
<p>Una volta specificata in modo coerente la tabella congiunta, tutte le altre probabilità ne derivano automaticamente.</p>
<div class="callout callout-style-simple callout-important no-icon callout-titled" title="Principio fondamentale">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Importante</span>Principio fondamentale
</div>
</div>
<section id="dalla-distribuzione-congiunta-derivano-tutte-le-probabilità" class="level3 callout-body-container callout-body" data-number="2.6.2"><h3 data-number="2.6.2" class="anchored" data-anchor-id="dalla-distribuzione-congiunta-derivano-tutte-le-probabilità">
<span class="header-section-number">2.6.2</span> Dalla distribuzione congiunta derivano tutte le probabilità</h3>
<p>Specificare una distribuzione di probabilità congiunta coerente su uno spazio finito richiede di:</p>
<ul>
<li>assegnare probabilità a ogni combinazione possibile degli eventi;</li>
<li>da questa specificazione completa discendono automaticamente, tramite operazioni di somma e condizionamento:
<ul>
<li>le probabilità marginali dei singoli eventi;</li>
<li>le probabilità condizionate tra eventi;</li>
<li>la verifica di eventuali relazioni di indipendenza.</li>
</ul>
</li>
</ul>
<p>La distribuzione congiunta rappresenta quindi lo <em>stato di conoscenza completo</em> sul sistema in esame.</p>
</section>
</div>
</section><section id="costruzione-di-una-tabella-di-probabilità-congiunta-22" class="level3" data-number="2.6.3"><h3 data-number="2.6.3" class="anchored" data-anchor-id="costruzione-di-una-tabella-di-probabilità-congiunta-22">
<span class="header-section-number">2.6.3</span> Costruzione di una tabella di probabilità congiunta 2×2</h3>
<div class="callout callout-style-simple callout-note no-icon callout-titled" title="Esempio: Test diagnostico per la depressione">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-8-contents" aria-controls="callout-8" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Esempio: Test diagnostico per la depressione
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-8" class="callout-8-contents callout-collapse collapse">
<section id="definizione-dello-scenario" class="level4 unnumbered unlisted callout-body-container callout-body"><h4 class="unnumbered unlisted anchored" data-anchor-id="definizione-dello-scenario">Definizione dello scenario</h4>
<p>Consideriamo un test diagnostico per la depressione con:</p>
<ul>
<li>
<strong><span class="math inline">\(D\)</span></strong>: il paziente è effettivamente depresso</li>
<li>
<strong><span class="math inline">\(T^+\)</span></strong>: il test risulta positivo</li>
</ul>
<p>Dati ricavati dalla letteratura clinica:</p>
<ul>
<li>
<strong>Prevalenza</strong>: <span class="math inline">\(P(D) = 0.15\)</span> (15% dei pazienti sono depressi)</li>
<li>
<strong>Sensibilità</strong>: <span class="math inline">\(P(T^+ \mid D) = 0.85\)</span> (l’85% dei depressi risulta positivo)</li>
<li>
<strong>Falsi positivi</strong>: <span class="math inline">\(P(T^+ \mid D^c) = 0.20\)</span> (il 20% dei non depressi risulta positivo)</li>
</ul>
<p><strong>Costruzione passo-passo della tabella:</strong></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb7"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Parametri di base</span></span>
<span><span class="va">prevalenza</span> <span class="op">&lt;-</span> <span class="fl">0.15</span></span>
<span><span class="va">sensibilita</span> <span class="op">&lt;-</span> <span class="fl">0.85</span></span>
<span><span class="va">tasso_falsi_positivi</span> <span class="op">&lt;-</span> <span class="fl">0.20</span></span>
<span></span>
<span><span class="co"># Calcolo delle probabilità congiunte</span></span>
<span><span class="va">p_depresso_positivo</span> <span class="op">&lt;-</span> <span class="va">sensibilita</span> <span class="op">*</span> <span class="va">prevalenza</span></span>
<span><span class="va">p_depresso_negativo</span> <span class="op">&lt;-</span> <span class="op">(</span><span class="fl">1</span> <span class="op">-</span> <span class="va">sensibilita</span><span class="op">)</span> <span class="op">*</span> <span class="va">prevalenza</span></span>
<span><span class="va">p_non_depresso_positivo</span> <span class="op">&lt;-</span> <span class="va">tasso_falsi_positivi</span> <span class="op">*</span> <span class="op">(</span><span class="fl">1</span> <span class="op">-</span> <span class="va">prevalenza</span><span class="op">)</span></span>
<span><span class="va">p_non_depresso_negativo</span> <span class="op">&lt;-</span> <span class="op">(</span><span class="fl">1</span> <span class="op">-</span> <span class="va">tasso_falsi_positivi</span><span class="op">)</span> <span class="op">*</span> <span class="op">(</span><span class="fl">1</span> <span class="op">-</span> <span class="va">prevalenza</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Creazione della tabella</span></span>
<span><span class="va">tabella_congiunta</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/matrix.html">matrix</a></span><span class="op">(</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">p_depresso_positivo</span>, <span class="va">p_depresso_negativo</span>,</span>
<span>    <span class="va">p_non_depresso_positivo</span>, <span class="va">p_non_depresso_negativo</span><span class="op">)</span>,</span>
<span>  nrow <span class="op">=</span> <span class="fl">2</span>,</span>
<span>  byrow <span class="op">=</span> <span class="cn">TRUE</span>,</span>
<span>  dimnames <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span></span>
<span>    <span class="st">"Stato reale"</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Depresso"</span>, <span class="st">"Non depresso"</span><span class="op">)</span>,</span>
<span>    <span class="st">"Risultato test"</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Positivo"</span>, <span class="st">"Negativo"</span><span class="op">)</span></span>
<span>  <span class="op">)</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/cat.html">cat</a></span><span class="op">(</span><span class="st">"TABELLA DI PROBABILITÀ CONGIUNTA\n"</span><span class="op">)</span></span>
<span><span class="co">#&gt; TABELLA DI PROBABILITÀ CONGIUNTA</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/cat.html">cat</a></span><span class="op">(</span><span class="st">"===============================\n"</span><span class="op">)</span></span>
<span><span class="co">#&gt; ===============================</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="va">tabella_congiunta</span>, <span class="fl">4</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="co">#&gt;               Risultato test</span></span>
<span><span class="co">#&gt; Stato reale    Positivo Negativo</span></span>
<span><span class="co">#&gt;   Depresso        0.128   0.0225</span></span>
<span><span class="co">#&gt;   Non depresso    0.170   0.6800</span></span>
<span></span>
<span><span class="co"># Verifica della coerenza</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/cat.html">cat</a></span><span class="op">(</span><span class="st">"\nVERIFICA DELLA COERENZA:\n"</span><span class="op">)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; VERIFICA DELLA COERENZA:</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/cat.html">cat</a></span><span class="op">(</span><span class="st">"Marginali per stato reale:"</span>, <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/colSums.html">rowSums</a></span><span class="op">(</span><span class="va">tabella_congiunta</span><span class="op">)</span>, <span class="fl">4</span><span class="op">)</span>, <span class="st">"\n"</span><span class="op">)</span></span>
<span><span class="co">#&gt; Marginali per stato reale: 0.15 0.85</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/cat.html">cat</a></span><span class="op">(</span><span class="st">"Marginali per risultato test:"</span>, <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/colSums.html">colSums</a></span><span class="op">(</span><span class="va">tabella_congiunta</span><span class="op">)</span>, <span class="fl">4</span><span class="op">)</span>, <span class="st">"\n"</span><span class="op">)</span></span>
<span><span class="co">#&gt; Marginali per risultato test: 0.297 0.703</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/cat.html">cat</a></span><span class="op">(</span><span class="st">"Somma totale (deve essere 1):"</span>, <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">tabella_congiunta</span><span class="op">)</span>, <span class="fl">4</span><span class="op">)</span>, <span class="st">"\n"</span><span class="op">)</span></span>
<span><span class="co">#&gt; Somma totale (deve essere 1): 1</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><strong>Interpretazione dei risultati:</strong></p>
<ul>
<li>
<strong>12.75%</strong>: probabilità che un paziente sia depresso e risulti positivo al test</li>
<li>
<strong>2.25%</strong>: probabilità che un paziente sia depresso ma risulti negativo (falsi negativi)</li>
<li>
<strong>17.00%</strong>: probabilità che un paziente non sia depresso ma risulti positivo (falsi positivi)</li>
<li>
<strong>68.00%</strong>: probabilità che un paziente non sia depresso e risulti negativo</li>
</ul>
<p>La tabella è <strong>coerente</strong>: tutte le probabilità sono non negative e la somma totale è 1, come richiesto dagli assiomi della probabilità.</p>
</section>
</div>
</div>
</section><section id="visualizzazione-della-tabella-congiunta" class="level3" data-number="2.6.4"><h3 data-number="2.6.4" class="anchored" data-anchor-id="visualizzazione-della-tabella-congiunta">
<span class="header-section-number">2.6.4</span> Visualizzazione della tabella congiunta</h3>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="02_axioms_coherence_bayesian_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:85.0%"></p>
</figure>
</div>
</div>
</div>
</section><section id="verifica-empirica-con-simulazione" class="level3" data-number="2.6.5"><h3 data-number="2.6.5" class="anchored" data-anchor-id="verifica-empirica-con-simulazione">
<span class="header-section-number">2.6.5</span> Verifica empirica con simulazione</h3>
<p>Possiamo verificare che la tabella congiunta sia coerente simulando dati e confrontando frequenze empiriche con probabilità teoriche.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb8"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">123</span><span class="op">)</span></span>
<span><span class="va">N</span> <span class="op">&lt;-</span> <span class="fl">100000</span></span>
<span></span>
<span><span class="co"># Simulare secondo la distribuzione congiunta</span></span>
<span><span class="co"># Esiti possibili: (D,T+), (D,T-), (D^c,T+), (D^c,T-)</span></span>
<span><span class="va">probs_vector</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">p_depresso_positivo</span>, <span class="va">p_depresso_negativo</span>, </span>
<span>                  <span class="va">p_non_depresso_positivo</span>, <span class="va">p_non_depresso_negativo</span><span class="op">)</span></span>
<span></span>
<span><span class="va">outcomes</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/sample.html">sample</a></span><span class="op">(</span><span class="fl">1</span><span class="op">:</span><span class="fl">4</span>, size <span class="op">=</span> <span class="va">N</span>, replace <span class="op">=</span> <span class="cn">TRUE</span>, prob <span class="op">=</span> <span class="va">probs_vector</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Contare frequenze empiriche</span></span>
<span><span class="va">freq_empiriche</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/table.html">table</a></span><span class="op">(</span><span class="va">outcomes</span><span class="op">)</span> <span class="op">/</span> <span class="va">N</span></span>
<span></span>
<span><span class="co"># Confronto</span></span>
<span><span class="va">df_verifica</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span></span>
<span>  Configurazione <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"D∩T+"</span>, <span class="st">"D∩T-"</span>, <span class="st">"D^c∩T+"</span>, <span class="st">"D^c∩T-"</span><span class="op">)</span>,</span>
<span>  Teorica <span class="op">=</span> <span class="va">probs_vector</span>,</span>
<span>  Empirica <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/numeric.html">as.numeric</a></span><span class="op">(</span><span class="va">freq_empiriche</span><span class="op">)</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/cat.html">cat</a></span><span class="op">(</span><span class="st">"Confronto teorico vs empirico:\n"</span><span class="op">)</span></span>
<span><span class="co">#&gt; Confronto teorico vs empirico:</span></span>
<span><span class="co"># Correzione: applica round solo alle colonne numeriche</span></span>
<span><span class="va">df_verifica_numeric</span> <span class="op">&lt;-</span> <span class="va">df_verifica</span></span>
<span><span class="va">df_verifica_numeric</span><span class="op">$</span><span class="va">Teorica</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="va">df_verifica_numeric</span><span class="op">$</span><span class="va">Teorica</span>, <span class="fl">4</span><span class="op">)</span></span>
<span><span class="va">df_verifica_numeric</span><span class="op">$</span><span class="va">Empirica</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="va">df_verifica_numeric</span><span class="op">$</span><span class="va">Empirica</span>, <span class="fl">4</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="va">df_verifica_numeric</span><span class="op">)</span></span>
<span><span class="co">#&gt;   Configurazione Teorica Empirica</span></span>
<span><span class="co">#&gt; 1           D∩T+  0.1275   0.1266</span></span>
<span><span class="co">#&gt; 2           D∩T-  0.0225   0.0226</span></span>
<span><span class="co">#&gt; 3         D^c∩T+  0.1700   0.1699</span></span>
<span><span class="co">#&gt; 4         D^c∩T-  0.6800   0.6809</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="02_axioms_coherence_bayesian_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:85.0%"></p>
</figure>
</div>
</div>
</div>
<p><strong>Interpretazione</strong>: le frequenze empiriche convergono verso le probabilità teoriche, confermando che la tabella rappresenta credenze coerenti che producono dati attesi.</p>
</section></section><section id="calcolo-di-probabilità-marginali-e-condizionate" class="level2" data-number="2.7"><h2 data-number="2.7" class="anchored" data-anchor-id="calcolo-di-probabilità-marginali-e-condizionate">
<span class="header-section-number">2.7</span> Calcolo di probabilità marginali e condizionate</h2>
<p>Una volta costruita una tabella congiunta coerente, possiamo ricavare qualsiasi altra quantità probabilistica di interesse.</p>
<section id="probabilità-marginali" class="level3" data-number="2.7.1"><h3 data-number="2.7.1" class="anchored" data-anchor-id="probabilità-marginali">
<span class="header-section-number">2.7.1</span> Probabilità marginali</h3>
<p>Le probabilità <em>marginali</em> si ottengono sommando (marginalizzando) lungo una dimensione:</p>
<p><span class="math display">\[
P(A) = \sum_{B} P(A \cap B) = P(A \cap B) + P(A \cap B^c),
\]</span></p>
<p><span class="math display">\[
P(B) = \sum_{A} P(A \cap B) = P(A \cap B) + P(A^c \cap B).
\]</span></p>
<div class="cell" data-layout-align="center">
<pre><code>#&gt; Probabilità marginali derivate:
#&gt; P(D) = 0.15
#&gt; P(D^c) = 0.85
#&gt; P(T+) = 0.297
#&gt; P(T-) = 0.703</code></pre>
</div>
</section><section id="probabilità-condizionate" class="level3" data-number="2.7.2"><h3 data-number="2.7.2" class="anchored" data-anchor-id="probabilità-condizionate">
<span class="header-section-number">2.7.2</span> Probabilità condizionate</h3>
<p>Le probabilità <em>condizionate</em> si ottengono come rapporti:</p>
<p><span class="math display">\[
P(A \mid B) = \frac{P(A \cap B)}{P(B)}.
\]</span></p>
<p><strong>Interpretazione epistemica</strong>: dopo aver appreso che <span class="math inline">\(B\)</span> è vero, “riduciamo” lo spazio delle possibilità a quelle compatibili con <span class="math inline">\(B\)</span>, e rinormalizziamo.</p>
<div class="cell" data-layout-align="center">
<pre><code>#&gt; Probabilità condizionate derivate:
#&gt; P(D | T+) = 0.429 (Valore predittivo positivo)
#&gt; P(D | T-) = 0.032 (Probabilità residua dopo test negativo)</code></pre>
</div>
<div class="callout callout-style-simple callout-important no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Importante</span>Messaggio chiave: la coerenza delle probabilità condizionate
</div>
</div>
<div class="callout-body-container callout-body">
<p>Le probabilità condizionate non sono assegnazioni arbitrarie, ma <em>relazioni strutturate</em> che derivano necessariamente dalla distribuzione congiunta.</p>
<p>Questa dipendenza matematica garantisce che tutte le probabilità siano <em>coerenti tra loro</em>: una volta specificata la distribuzione congiunta, le probabilità condizionate sono determinate univocamente attraverso la relazione:</p>
<p><span class="math display">\[
P(A \mid B) = \frac{P(A \cap B)}{P(B)}
\]</span></p>
<p>Se invece assegnassimo le probabilità condizionate in modo indipendente dalla congiunta, rischieremmo di creare <strong>incoerenze logiche</strong>, come ad esempio:</p>
<ul>
<li>
<span class="math inline">\(P(A \mid B) \cdot P(B) \neq P(A \cap B)\)</span>;</li>
<li>Probabilità che violano gli assiomi fondamentali;</li>
<li>Assegnazioni che porterebbero al <em>Dutch book</em>.</li>
</ul>
<p>La struttura congiunta funge quindi da <em>fondamento coerente</em> da cui tutte le altre probabilità derivano naturalmente.</p>
</div>
</div>
</section><section id="visualizzazione-dalla-distribuzione-congiunta-alle-probabilità-condizionate" class="level3" data-number="2.7.3"><h3 data-number="2.7.3" class="anchored" data-anchor-id="visualizzazione-dalla-distribuzione-congiunta-alle-probabilità-condizionate">
<span class="header-section-number">2.7.3</span> Visualizzazione: dalla distribuzione congiunta alle probabilità condizionate</h3>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="02_axioms_coherence_bayesian_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:85.0%"></p>
</figure>
</div>
</div>
</div>
</section></section><section id="esercizio-guidato-costruire-e-analizzare-una-tabella-22" class="level2" data-number="2.8"><h2 data-number="2.8" class="anchored" data-anchor-id="esercizio-guidato-costruire-e-analizzare-una-tabella-22">
<span class="header-section-number">2.8</span> Esercizio guidato: costruire e analizzare una tabella 2×2</h2>
<p>Lavoriamo passo-passo sulla costruzione di una tabella congiunta da informazioni psicologiche.</p>
<div class="callout callout-style-simple callout-tip no-icon callout-titled" title="Scenario clinico">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Consiglio</span>Scenario clinico
</div>
</div>
<section id="comorbidità-depressione-ansia-in-terapia" class="level3 callout-body-container callout-body" data-number="2.8.1"><h3 data-number="2.8.1" class="anchored" data-anchor-id="comorbidità-depressione-ansia-in-terapia">
<span class="header-section-number">2.8.1</span> Comorbidità Depressione-Ansia in terapia</h3>
<p>Uno psicoterapeuta vuole modellare la probabilità di comorbidità nel proprio ambulatorio. Dalla letteratura e dall’esperienza clinica, stabilisce:</p>
<ul>
<li>
<span class="math inline">\(P(\text{Depressione}) = 0.50\)</span> (prevalenza nell’ambulatorio);</li>
<li>
<span class="math inline">\(P(\text{Ansia}) = 0.40\)</span>;</li>
<li>
<span class="math inline">\(P(\text{Ansia} \mid \text{Depressione}) = 0.60\)</span> (comorbidità).</li>
</ul>
<p><strong>Obiettivo</strong>: Costruire la tabella congiunta completa e rispondere a domande cliniche.</p>
</section>
</div>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb11"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Parametri</span></span>
<span><span class="va">P_D</span> <span class="op">&lt;-</span> <span class="fl">0.50</span></span>
<span><span class="va">P_A</span> <span class="op">&lt;-</span> <span class="fl">0.40</span></span>
<span><span class="va">P_A_given_D</span> <span class="op">&lt;-</span> <span class="fl">0.60</span></span>
<span></span>
<span><span class="co"># Passo 1: Calcolare congiunta P(D ∩ A)</span></span>
<span><span class="va">P_D_and_A</span> <span class="op">&lt;-</span> <span class="va">P_A_given_D</span> <span class="op">*</span> <span class="va">P_D</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/cat.html">cat</a></span><span class="op">(</span><span class="st">"=== COSTRUZIONE TABELLA CONGIUNTA ===\n\n"</span><span class="op">)</span></span>
<span><span class="co">#&gt; === COSTRUZIONE TABELLA CONGIUNTA ===</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/cat.html">cat</a></span><span class="op">(</span><span class="st">"Passo 1: P(D ∩ A) = P(A|D) × P(D) ="</span>, <span class="va">P_A_given_D</span>, <span class="st">"×"</span>, <span class="va">P_D</span>, <span class="st">"="</span>, <span class="va">P_D_and_A</span>, <span class="st">"\n\n"</span><span class="op">)</span></span>
<span><span class="co">#&gt; Passo 1: P(D ∩ A) = P(A|D) × P(D) = 0.6 × 0.5 = 0.3</span></span>
<span></span>
<span><span class="co"># Passo 2: Altre celle usando additività</span></span>
<span><span class="va">P_D_and_notA</span> <span class="op">&lt;-</span> <span class="va">P_D</span> <span class="op">-</span> <span class="va">P_D_and_A</span></span>
<span><span class="va">P_notD_and_A</span> <span class="op">&lt;-</span> <span class="va">P_A</span> <span class="op">-</span> <span class="va">P_D_and_A</span></span>
<span><span class="va">P_notD_and_notA</span> <span class="op">&lt;-</span> <span class="fl">1</span> <span class="op">-</span> <span class="op">(</span><span class="va">P_D_and_A</span> <span class="op">+</span> <span class="va">P_D_and_notA</span> <span class="op">+</span> <span class="va">P_notD_and_A</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/cat.html">cat</a></span><span class="op">(</span><span class="st">"Passo 2: Altre celle\n"</span><span class="op">)</span></span>
<span><span class="co">#&gt; Passo 2: Altre celle</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/cat.html">cat</a></span><span class="op">(</span><span class="st">"  P(D ∩ A^c) ="</span>, <span class="va">P_D_and_notA</span>, <span class="st">"\n"</span><span class="op">)</span></span>
<span><span class="co">#&gt;   P(D ∩ A^c) = 0.2</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/cat.html">cat</a></span><span class="op">(</span><span class="st">"  P(D^c ∩ A) ="</span>, <span class="va">P_notD_and_A</span>, <span class="st">"\n"</span><span class="op">)</span></span>
<span><span class="co">#&gt;   P(D^c ∩ A) = 0.1</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/cat.html">cat</a></span><span class="op">(</span><span class="st">"  P(D^c ∩ A^c) ="</span>, <span class="va">P_notD_and_notA</span>, <span class="st">"\n\n"</span><span class="op">)</span></span>
<span><span class="co">#&gt;   P(D^c ∩ A^c) = 0.4</span></span>
<span></span>
<span><span class="co"># Passo 3: Verificare coerenza</span></span>
<span><span class="va">somma_celle</span> <span class="op">&lt;-</span> <span class="va">P_D_and_A</span> <span class="op">+</span> <span class="va">P_D_and_notA</span> <span class="op">+</span> <span class="va">P_notD_and_A</span> <span class="op">+</span> <span class="va">P_notD_and_notA</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/cat.html">cat</a></span><span class="op">(</span><span class="st">"Passo 3: Verifica coerenza\n"</span><span class="op">)</span></span>
<span><span class="co">#&gt; Passo 3: Verifica coerenza</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/cat.html">cat</a></span><span class="op">(</span><span class="st">"  Somma celle ="</span>, <span class="va">somma_celle</span>, <span class="st">"(deve essere 1) ✓\n\n"</span><span class="op">)</span></span>
<span><span class="co">#&gt;   Somma celle = 1 (deve essere 1) ✓</span></span>
<span></span>
<span><span class="co"># Creare tabella</span></span>
<span><span class="va">tab_comorbid</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/matrix.html">matrix</a></span><span class="op">(</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">P_D_and_A</span>, <span class="va">P_D_and_notA</span>,</span>
<span>    <span class="va">P_notD_and_A</span>, <span class="va">P_notD_and_notA</span><span class="op">)</span>,</span>
<span>  nrow <span class="op">=</span> <span class="fl">2</span>, byrow <span class="op">=</span> <span class="cn">TRUE</span>,</span>
<span>  dimnames <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span></span>
<span>    Depressione <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"D"</span>, <span class="st">"D^c"</span><span class="op">)</span>,</span>
<span>    Ansia <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"A"</span>, <span class="st">"A^c"</span><span class="op">)</span></span>
<span>  <span class="op">)</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/cat.html">cat</a></span><span class="op">(</span><span class="st">"TABELLA CONGIUNTA FINALE:\n"</span><span class="op">)</span></span>
<span><span class="co">#&gt; TABELLA CONGIUNTA FINALE:</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="va">tab_comorbid</span>, <span class="fl">3</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="co">#&gt;            Ansia</span></span>
<span><span class="co">#&gt; Depressione   A A^c</span></span>
<span><span class="co">#&gt;         D   0.3 0.2</span></span>
<span><span class="co">#&gt;         D^c 0.1 0.4</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/cat.html">cat</a></span><span class="op">(</span><span class="st">"\nMARGINALI:\n"</span><span class="op">)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; MARGINALI:</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/cat.html">cat</a></span><span class="op">(</span><span class="st">"Riga (Depressione):"</span>, <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/colSums.html">rowSums</a></span><span class="op">(</span><span class="va">tab_comorbid</span><span class="op">)</span>, <span class="fl">3</span><span class="op">)</span>, <span class="st">"\n"</span><span class="op">)</span></span>
<span><span class="co">#&gt; Riga (Depressione): 0.5 0.5</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/cat.html">cat</a></span><span class="op">(</span><span class="st">"Colonna (Ansia):"</span>, <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/colSums.html">colSums</a></span><span class="op">(</span><span class="va">tab_comorbid</span><span class="op">)</span>, <span class="fl">3</span><span class="op">)</span>, <span class="st">"\n"</span><span class="op">)</span></span>
<span><span class="co">#&gt; Colonna (Ansia): 0.4 0.6</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<section id="rispondere-a-domande-cliniche" class="level3" data-number="2.8.2"><h3 data-number="2.8.2" class="anchored" data-anchor-id="rispondere-a-domande-cliniche">
<span class="header-section-number">2.8.2</span> Rispondere a domande cliniche</h3>
<div class="cell" data-layout-align="center">
<pre><code>#&gt; 
#&gt; === DOMANDE CLINICHE ===
#&gt; Q1: P(D ∪ A) = P(almeno una condizione) = 0.6
#&gt; Q2: P(D^c ∩ A^c) = P(nessuna condizione) = 0.4
#&gt; Q3: P(D ∩ A) = P(entrambe le condizioni) = 0.3
#&gt; Q4: P(D | A) = P(Depressione dato Ansia) = 0.75
#&gt; 
#&gt; Q5: Test di indipendenza
#&gt;   P(D) × P(A) = 0.2
#&gt;   P(D ∩ A) = 0.3
#&gt;   → Eventi DIPENDENTI (correlati)
#&gt;   Differenza: 0.1</code></pre>
</div>
</section><section id="visualizzazione-della-tabella-congiunta-1" class="level3" data-number="2.8.3"><h3 data-number="2.8.3" class="anchored" data-anchor-id="visualizzazione-della-tabella-congiunta-1">
<span class="header-section-number">2.8.3</span> Visualizzazione della tabella congiunta</h3>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb13"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Heatmap</span></span>
<span><span class="va">df_comorbid</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/as.data.frame.html">as.data.frame</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/table.html">as.table</a></span><span class="op">(</span><span class="va">tab_comorbid</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/colnames.html">colnames</a></span><span class="op">(</span><span class="va">df_comorbid</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Depressione"</span>, <span class="st">"Ansia"</span>, <span class="st">"Probabilita"</span><span class="op">)</span></span>
<span></span>
<span><span class="fu">ggplot</span><span class="op">(</span><span class="va">df_comorbid</span>, <span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">Ansia</span>, y <span class="op">=</span> <span class="va">Depressione</span>, fill <span class="op">=</span> <span class="va">Probabilita</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_tile</span><span class="op">(</span>color <span class="op">=</span> <span class="st">"white"</span>, size <span class="op">=</span> <span class="fl">2</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_text</span><span class="op">(</span><span class="fu">aes</span><span class="op">(</span>label <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="va">Probabilita</span>, <span class="fl">3</span><span class="op">)</span><span class="op">)</span>, </span>
<span>            color <span class="op">=</span> <span class="st">"white"</span>, size <span class="op">=</span> <span class="fl">8</span>, fontface <span class="op">=</span> <span class="st">"bold"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">scale_fill_viridis_c</span><span class="op">(</span>option <span class="op">=</span> <span class="st">"plasma"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">labs</span><span class="op">(</span></span>
<span>    title <span class="op">=</span> <span class="st">"Tabella congiunta: Depressione × Ansia"</span>,</span>
<span>    subtitle <span class="op">=</span> <span class="st">"Comorbidità P(D ∩ A) = 0.30 (cella in basso a sinistra)"</span></span>
<span>  <span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">theme_minimal</span><span class="op">(</span>base_size <span class="op">=</span> <span class="fl">14</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">coord_fixed</span><span class="op">(</span><span class="op">)</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="02_axioms_coherence_bayesian_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:85.0%"></p>
</figure>
</div>
</div>
</div>
</section></section><section id="estensione-a-tabelle-multidimensionali" class="level2" data-number="2.9"><h2 data-number="2.9" class="anchored" data-anchor-id="estensione-a-tabelle-multidimensionali">
<span class="header-section-number">2.9</span> Estensione a tabelle multidimensionali</h2>
<p>Il principio della distribuzione congiunta si generalizza naturalmente a sistemi con più variabili e categorie, permettendo di modellare situazioni cliniche più complesse.</p>
<section id="esempio-depressione-e-livelli-di-ansia" class="level3" data-number="2.9.1"><h3 data-number="2.9.1" class="anchored" data-anchor-id="esempio-depressione-e-livelli-di-ansia">
<span class="header-section-number">2.9.1</span> Esempio: depressione e livelli di ansia</h3>
<p>Consideriamo uno scenario clinico con due dimensioni:</p>
<ul>
<li>Depressione: presenza/assenza (variabile binaria);</li>
<li>Severità dell’ansia: nessuna/lieve/grave (variabile ternaria).</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb14"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Scenario: Depressione × Severità Ansia (Nessuna/Lieve/Grave)</span></span>
<span><span class="va">tab_2x3</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/matrix.html">matrix</a></span><span class="op">(</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0.15</span>, <span class="fl">0.20</span>, <span class="fl">0.15</span>,  <span class="co"># D: Ansia Nessuna/Lieve/Grave</span></span>
<span>    <span class="fl">0.35</span>, <span class="fl">0.10</span>, <span class="fl">0.05</span><span class="op">)</span>, <span class="co"># D^c: Ansia Nessuna/Lieve/Grave</span></span>
<span>  nrow <span class="op">=</span> <span class="fl">2</span>, byrow <span class="op">=</span> <span class="cn">TRUE</span>,</span>
<span>  dimnames <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span></span>
<span>    Depressione <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"D"</span>, <span class="st">"D^c"</span><span class="op">)</span>,</span>
<span>    Ansia <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Nessuna"</span>, <span class="st">"Lieve"</span>, <span class="st">"Grave"</span><span class="op">)</span></span>
<span>  <span class="op">)</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/cat.html">cat</a></span><span class="op">(</span><span class="st">"Tabella 2×3:\n"</span><span class="op">)</span></span>
<span><span class="co">#&gt; Tabella 2×3:</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="va">tab_2x3</span><span class="op">)</span></span>
<span><span class="co">#&gt;            Ansia</span></span>
<span><span class="co">#&gt; Depressione Nessuna Lieve Grave</span></span>
<span><span class="co">#&gt;         D      0.15   0.2  0.15</span></span>
<span><span class="co">#&gt;         D^c    0.35   0.1  0.05</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/cat.html">cat</a></span><span class="op">(</span><span class="st">"\nMarginali:\n"</span><span class="op">)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Marginali:</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/cat.html">cat</a></span><span class="op">(</span><span class="st">"Depressione:"</span>, <span class="fu"><a href="https://rdrr.io/r/base/colSums.html">rowSums</a></span><span class="op">(</span><span class="va">tab_2x3</span><span class="op">)</span>, <span class="st">"\n"</span><span class="op">)</span></span>
<span><span class="co">#&gt; Depressione: 0.5 0.5</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/cat.html">cat</a></span><span class="op">(</span><span class="st">"Ansia:"</span>, <span class="fu"><a href="https://rdrr.io/r/base/colSums.html">colSums</a></span><span class="op">(</span><span class="va">tab_2x3</span><span class="op">)</span>, <span class="st">"\n"</span><span class="op">)</span></span>
<span><span class="co">#&gt; Ansia: 0.5 0.3 0.2</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/cat.html">cat</a></span><span class="op">(</span><span class="st">"Totale:"</span>, <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">tab_2x3</span><span class="op">)</span>, <span class="st">"\n"</span><span class="op">)</span></span>
<span><span class="co">#&gt; Totale: 1</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section><section id="visualizzazione-della-distribuzione-congiunta" class="level3" data-number="2.9.2"><h3 data-number="2.9.2" class="anchored" data-anchor-id="visualizzazione-della-distribuzione-congiunta">
<span class="header-section-number">2.9.2</span> Visualizzazione della distribuzione congiunta</h3>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb15"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">df_2x3</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/as.data.frame.html">as.data.frame</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/table.html">as.table</a></span><span class="op">(</span><span class="va">tab_2x3</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/colnames.html">colnames</a></span><span class="op">(</span><span class="va">df_2x3</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Depressione"</span>, <span class="st">"SeveritaAnsia"</span>, <span class="st">"Probabilita"</span><span class="op">)</span></span>
<span></span>
<span><span class="fu">ggplot</span><span class="op">(</span><span class="va">df_2x3</span>, <span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">SeveritaAnsia</span>, y <span class="op">=</span> <span class="va">Depressione</span>, fill <span class="op">=</span> <span class="va">Probabilita</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_tile</span><span class="op">(</span>color <span class="op">=</span> <span class="st">"white"</span>, size <span class="op">=</span> <span class="fl">1</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_text</span><span class="op">(</span><span class="fu">aes</span><span class="op">(</span>label <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="va">Probabilita</span>, <span class="fl">2</span><span class="op">)</span><span class="op">)</span>, </span>
<span>            color <span class="op">=</span> <span class="st">"white"</span>, size <span class="op">=</span> <span class="fl">6</span>, fontface <span class="op">=</span> <span class="st">"bold"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">scale_fill_viridis_c</span><span class="op">(</span>option <span class="op">=</span> <span class="st">"plasma"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">labs</span><span class="op">(</span></span>
<span>    title <span class="op">=</span> <span class="st">"Tabella congiunta 2×3: Depressione × Severità Ansia"</span>,</span>
<span>    subtitle <span class="op">=</span> <span class="st">"Ogni cella = credenza nella configurazione specifica"</span></span>
<span>  <span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">theme_minimal</span><span class="op">(</span>base_size <span class="op">=</span> <span class="fl">12</span><span class="op">)</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="02_axioms_coherence_bayesian_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:85.0%"></p>
</figure>
</div>
</div>
</div>
<p><strong>Interpretazione clinica:</strong></p>
<ul>
<li>15%: pazienti depressi con ansia grave;</li>
<li>20%: pazienti depressi con ansia lieve;<br>
</li>
<li>35%: pazienti non depressi senza ansia;</li>
<li>le probabilità marginali mostrano la prevalenza complessiva di ciascuna condizione.</li>
</ul></section></section><section id="riflessioni-conclusive" class="level2 unnumbered unlisted"><h2 class="unnumbered unlisted anchored" data-anchor-id="riflessioni-conclusive">Riflessioni conclusive</h2>
<p>In questo capitolo abbiamo gettato le basi matematiche per esprimere e manipolare le nostre credenze in modo rigorosamente coerente.</p>
<ol type="1">
<li><p><strong>Spazio campionario epistemico</strong>: abbiamo ridefinito lo spazio campionario non come “tutto ciò che può fisicamente accadere”, ma come “tutto ciò che riteniamo possibile”, in base al nostro attuale stato di conoscenza.</p></li>
<li><p><strong>Assiomi come garanzia di coerenza</strong>: gli assiomi della probabilità non sono leggi della natura, ma come condizioni necessarie per evitare contraddizioni logiche e situazioni di svantaggio certo (Dutch Book).</p></li>
<li><p><strong>Vincoli strutturali</strong>: i vincoli di Fréchet ci mostrano che le probabilità congiunte non possono essere assegnate arbitrariamente, ma devono rispettare relazioni matematiche precise con le probabilità marginali.</p></li>
<li>
<p><strong>La potenza delle tabelle congiunte</strong>: la distribuzione congiunta si rivela come la rappresentazione più completa e operativa del nostro stato di credenza. Da questa matrice fondamentale derivano in modo sistematico:</p>
<ul>
<li>
<strong>probabilità marginali</strong> (per somma lungo righe o colonne);</li>
<li>
<strong>probabilità condizionate</strong> (come rapporti tra celle);</li>
<li>
<strong>verifiche di indipendenza</strong> (confrontando prodotti con congiunte);</li>
<li>
<strong>qualsiasi altra quantità probabilistica</strong> di interesse.</li>
</ul>
</li>
<li><p><strong>Validazione attraverso la simulazione</strong>: le verifiche empiriche confermano che le credenze coerenti generano pattern di dati attesi, ma è fondamentale ricordare che i dati non definiscono le credenze, bensì le credenze esprimono il nostro stato di incertezza prima di osservare i dati.</p></li>
</ol>
<section id="vantaggi-per-la-ricerca-e-la-pratica-psicologica" class="level3" data-number="2.9.3"><h3 data-number="2.9.3" class="anchored" data-anchor-id="vantaggi-per-la-ricerca-e-la-pratica-psicologica">
<span class="header-section-number">2.9.3</span> Vantaggi per la ricerca e la pratica psicologica</h3>
<p>Questo approccio basato su distribuzioni congiunte offre vantaggi concreti:</p>
<ul>
<li>
<strong>trasparenza</strong>: tutte le assunzioni probabilistiche sono esplicite e verificabili;</li>
<li>
<strong>potere diagnostico</strong>: le incoerenze logiche diventano immediatamente visibili e correggibili;</li>
<li>
<strong>flessibilità operativa</strong>: è semplice incorporare nuove informazioni aggiornando la distribuzione;</li>
<li>
<strong>chiarezza comunicativa</strong>: le tabelle sono intuitive e accessibili anche per chi non è esperto di statistica.</li>
</ul></section><section id="prossime-direzioni" class="level3" data-number="2.9.4"><h3 data-number="2.9.4" class="anchored" data-anchor-id="prossime-direzioni">
<span class="header-section-number">2.9.4</span> Prossime direzioni</h3>
<p>Nei prossimi capitoli utilizzeremo questo solido framework per:</p>
<ul>
<li>esplorare l’<em>equiprobabilità</em> come caso speciale di simmetria epistemica;</li>
<li>approfondire l’<em>aggiornamento bayesiano</em> attraverso il calcolo delle probabilità condizionate;</li>
<li>applicare questi strumenti a scenari psicologici sempre più complessi.</li>
</ul>
<p>Questo capitolo ha stabilito non solo <em>come</em> calcolare probabilità, ma <em>perché</em> certe regole sono necessarie per pensare in modo razionale in situazioni di incertezza.</p>
</section></section><section id="esercizi" class="level2 unnumbered unlisted"><h2 class="unnumbered unlisted anchored" data-anchor-id="esercizi">Esercizi</h2>
<div class="callout callout-style-simple callout-important no-icon callout-titled" title="Problemi">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-11-contents" aria-controls="callout-11" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Importante</span>Problemi
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-11" class="callout-11-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<section id="esercizi-sulla-coerenza" class="level3" data-number="2.9.5"><h3 data-number="2.9.5" class="anchored" data-anchor-id="esercizi-sulla-coerenza">
<span class="header-section-number">2.9.5</span> Esercizi sulla coerenza</h3>
<ol type="1">
<li>
<p>Verifica se le seguenti assegnazioni per eventi mutuamente esclusivi sono coerenti:</p>
<ol type="a">
<li><span class="math inline">\(P(A) = 0.3, P(B) = 0.4, P(C) = 0.3\)</span></li>
<li><span class="math inline">\(P(A) = 0.5, P(B) = 0.4, P(C) = 0.2\)</span></li>
<li><span class="math inline">\(P(A) = 0.25, P(B) = 0.25, P(C) = 0.25, P(D) = 0.25\)</span></li>
</ol>
</li>
<li><p>Un ricercatore assegna <span class="math inline">\(P(A) = 0.7\)</span> e <span class="math inline">\(P(A^c) = 0.4\)</span>. Identifica l’incoerenza e spiega perché viola gli assiomi.</p></li>
<li><p>Per eventi disgiunti <span class="math inline">\(A\)</span> e <span class="math inline">\(B\)</span> con <span class="math inline">\(P(A) = 0.6\)</span> e <span class="math inline">\(P(B) = 0.3\)</span>, qualcuno afferma <span class="math inline">\(P(A \cup B) = 0.8\)</span>. È coerente? Se no, qual è il valore corretto?</p></li>
</ol></section><section id="esercizi-sui-vincoli-di-fréchet" class="level3" data-number="2.9.6"><h3 data-number="2.9.6" class="anchored" data-anchor-id="esercizi-sui-vincoli-di-fréchet">
<span class="header-section-number">2.9.6</span> Esercizi sui vincoli di Fréchet</h3>
<ol start="4" type="1">
<li>
<p>Dati <span class="math inline">\(P(A) = 0.4\)</span> e <span class="math inline">\(P(B) = 0.7\)</span>:</p>
<ol type="a">
<li>Calcola i vincoli di Fréchet per <span class="math inline">\(P(A \cap B)\)</span>
</li>
<li>Quali dei seguenti valori sono coerenti: 0.05, 0.1, 0.3, 0.5?</li>
<li>Visualizza graficamente la regione ammissibile</li>
</ol>
</li>
<li>
<p>In uno studio su depressione e insonnia:</p>
<ul>
<li><span class="math inline">\(P(\text{Depressione}) = 0.30\)</span></li>
<li><span class="math inline">\(P(\text{Insonnia}) = 0.45\)</span></li>
</ul>
<p>Determina l’intervallo di valori plausibili per <span class="math inline">\(P(\text{Depressione} \cap \text{Insonnia})\)</span>.</p>
</li>
<li><p>Scrivi una funzione R che, dati <span class="math inline">\(P(A)\)</span> e <span class="math inline">\(P(B)\)</span>, verifichi se un proposto <span class="math inline">\(P(A \cap B)\)</span> rispetta i vincoli di Fréchet.</p></li>
</ol></section><section id="esercizi-su-tabelle-congiunte" class="level3" data-number="2.9.7"><h3 data-number="2.9.7" class="anchored" data-anchor-id="esercizi-su-tabelle-congiunte">
<span class="header-section-number">2.9.7</span> Esercizi su tabelle congiunte</h3>
<ol start="7" type="1">
<li>
<p>Completa la seguente tabella congiunta (alcune celle sono mancanti):</p>
<table class="caption-top table">
<thead><tr class="header">
<th></th>
<th><span class="math inline">\(B\)</span></th>
<th><span class="math inline">\(B^c\)</span></th>
<th>Marg.</th>
</tr></thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(A\)</span></td>
<td>0.25</td>
<td>?</td>
<td>0.40</td>
</tr>
<tr class="even">
<td><span class="math inline">\(A^c\)</span></td>
<td>?</td>
<td>0.45</td>
<td>?</td>
</tr>
<tr class="odd">
<td>Marg.</td>
<td>?</td>
<td>?</td>
<td>1</td>
</tr>
</tbody>
</table>
</li>
<li>
<p>Costruisci una tabella congiunta 2×2 per:</p>
<ul>
<li>Test COVID: <span class="math inline">\(P(+) = 0.08\)</span>
</li>
<li>Malattia: <span class="math inline">\(P(\text{COVID}) = 0.05\)</span>
</li>
<li>Sensibilità: <span class="math inline">\(P(+ \mid \text{COVID}) = 0.90\)</span>
</li>
</ul>
<p>Calcola poi:</p>
<ol type="a">
<li>
<span class="math inline">\(P(\text{COVID} \mid +)\)</span> (valore predittivo positivo)</li>
<li>
<span class="math inline">\(P(\text{COVID} \mid -)\)</span> (probabilità dopo test negativo)</li>
<li>Specificità del test</li>
</ol>
</li>
<li><p>Verifica con simulazione Monte Carlo (N=100,000) che la tabella dell’esercizio 8 è coerente confrontando frequenze empiriche con probabilità teoriche.</p></li>
</ol></section><section id="esercizi-applicati-psicologia" class="level3" data-number="2.9.8"><h3 data-number="2.9.8" class="anchored" data-anchor-id="esercizi-applicati-psicologia">
<span class="header-section-number">2.9.8</span> Esercizi applicati (psicologia)</h3>
<ol start="10" type="1">
<li>
<p><strong>Comorbidità</strong>: In un campione clinico:</p>
<ul>
<li><span class="math inline">\(P(\text{Depressione}) = 0.55\)</span></li>
<li><span class="math inline">\(P(\text{PTSD}) = 0.30\)</span></li>
<li><span class="math inline">\(P(\text{PTSD} \mid \text{Depressione}) = 0.45\)</span></li>
</ul>
<ol type="a">
<li>Costruisci la tabella congiunta completa</li>
<li>Calcola <span class="math inline">\(P(\text{Depressione} \mid \text{PTSD})\)</span>
</li>
<li>Le due condizioni sono indipendenti?</li>
<li>Qual è la probabilità di avere almeno una delle due condizioni?</li>
</ol>
</li>
<li>
<p><strong>Test psicometrico</strong>: Un test di ansia ha:</p>
<ul>
<li>Sensibilità: 0.80</li>
<li>Specificità: 0.85</li>
<li>Prevalenza nell’ambulatorio: 0.25</li>
</ul>
<ol type="a">
<li>Costruisci la tabella 2×2 per (Ansia × Test)</li>
<li>Un paziente ha test positivo. Quanto è probabile che sia ansioso?</li>
<li>Se il test è negativo, quanto è probabile l’assenza di ansia?</li>
</ol>
</li>
<li>
<p><strong>Tre diagnosi</strong>: Un paziente può avere Depressione (D), Ansia (A), o Nessuna condizione (N). Assegnazioni:</p>
<ul>
<li><span class="math inline">\(P(D) = 0.40\)</span></li>
<li><span class="math inline">\(P(A) = 0.35\)</span></li>
<li><span class="math inline">\(P(N) = 0.30\)</span></li>
</ul>
<p>Identifica e correggi l’incoerenza.</p>
</li>
</ol></section><section id="esercizi-di-pensiero-critico" class="level3" data-number="2.9.9"><h3 data-number="2.9.9" class="anchored" data-anchor-id="esercizi-di-pensiero-critico">
<span class="header-section-number">2.9.9</span> Esercizi di pensiero critico</h3>
<ol start="13" type="1">
<li><p>Spiega perché, nell’approccio bayesiano, specificare una tabella congiunta coerente è “più fondamentale” che specificare separatamente marginali e condizionate.</p></li>
<li><p>Un frequentista obietta: “Le tabelle congiunte funzionano solo per spazi finiti. Come gestite il caso continuo?” Rispondi dall’ottica bayesiana.</p></li>
<li><p>Due clinici costruiscono tabelle congiunte diverse per Depressione × Test, partendo da prior diversi ma usando la stessa sensibilità/specificità. È un problema? Cosa succederebbe con molti dati?</p></li>
</ol></section><section id="esercizi-computazionali" class="level3" data-number="2.9.10"><h3 data-number="2.9.10" class="anchored" data-anchor-id="esercizi-computazionali">
<span class="header-section-number">2.9.10</span> Esercizi computazionali</h3>
<ol start="16" type="1">
<li>
<p>Scrivi una funzione R che:</p>
<ul>
<li>Input: vettore di probabilità per eventi mutuamente esclusivi</li>
<li>Output: TRUE se coerente, FALSE con messaggio di errore se incoerente</li>
<li>Bonus: Se incoerente, proponi correzione per normalizzazione</li>
</ul>
</li>
<li><p>Crea una visualizzazione interattiva (Shiny app o plot animato) che mostri come variano i vincoli di Fréchet al variare di <span class="math inline">\(P(A)\)</span> e <span class="math inline">\(P(B)\)</span>.</p></li>
<li>
<p>Simula 10,000 pazienti secondo la tabella dell’esercizio 10, poi:</p>
<ol type="a">
<li>Calcola frequenze empiriche delle 4 configurazioni</li>
<li>Confronta con probabilità teoriche</li>
<li>Visualizza convergenza all’aumentare di N</li>
</ol>
</li>
</ol></section>
</div>
</div>
</div>
<div class="callout callout-style-simple callout-tip no-icon callout-titled" title="Soluzioni">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-12-contents" aria-controls="callout-12" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Consiglio</span>Soluzioni
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-12" class="callout-12-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<section id="soluzioni-esercizi-sulla-coerenza" class="level3" data-number="2.9.11"><h3 data-number="2.9.11" class="anchored" data-anchor-id="soluzioni-esercizi-sulla-coerenza">
<span class="header-section-number">2.9.11</span> Soluzioni esercizi sulla coerenza</h3>
<ol type="1">
<li><ol type="a">
<li>
<span class="math inline">\(0.3 + 0.4 + 0.3 = 1.0\)</span> ✓ Coerente<br>
</li>
<li>
<span class="math inline">\(0.5 + 0.4 + 0.2 = 1.1\)</span> ✗ Incoerente (somma &gt; 1)<br>
</li>
<li>
<span class="math inline">\(4 \times 0.25 = 1.0\)</span> ✓ Coerente</li>
</ol></li>
<li><p>Per l’assioma del complemento: <span class="math inline">\(P(A) + P(A^c) = 1\)</span>. Ma <span class="math inline">\(0.7 + 0.4 = 1.1 \neq 1\)</span>. Incoerente. Correzione: deve essere <span class="math inline">\(P(A^c) = 0.3\)</span>.</p></li>
<li><p>Per eventi disgiunti: <span class="math inline">\(P(A \cup B) = P(A) + P(B) = 0.6 + 0.3 = 0.9\)</span>. Il valore 0.8 è incoerente (troppo basso).</p></li>
</ol></section><section id="soluzioni-vincoli-di-fréchet" class="level3" data-number="2.9.12"><h3 data-number="2.9.12" class="anchored" data-anchor-id="soluzioni-vincoli-di-fréchet">
<span class="header-section-number">2.9.12</span> Soluzioni vincoli di Fréchet</h3>
<ol start="4" type="1">
<li><ol type="a">
<li><p>Lower: <span class="math inline">\(\max(0, 0.4 + 0.7 - 1) = 0.1\)</span>; Upper: <span class="math inline">\(\min(0.4, 0.7) = 0.4\)</span><br>
Intervallo: <span class="math inline">\([0.1, 0.4]\)</span></p></li>
<li><p>Coerenti: 0.1 (al limite), 0.3 (interno), 0.5 (FUORI, troppo alto)<br>
Non coerente: 0.05 (troppo basso)</p></li>
</ol></li>
<li><p>Lower: <span class="math inline">\(\max(0, 0.30 + 0.45 - 1) = 0\)</span>; Upper: <span class="math inline">\(\min(0.30, 0.45) = 0.30\)</span><br>
Intervallo plausibile: <span class="math inline">\([0, 0.30]\)</span></p></li>
<li><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb16"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">check_frechet</span> <span class="op">&lt;-</span> <span class="kw">function</span><span class="op">(</span><span class="va">P_A</span>, <span class="va">P_B</span>, <span class="va">P_AB</span><span class="op">)</span> <span class="op">{</span></span>
<span>  <span class="va">lower</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/Extremes.html">max</a></span><span class="op">(</span><span class="fl">0</span>, <span class="va">P_A</span> <span class="op">+</span> <span class="va">P_B</span> <span class="op">-</span> <span class="fl">1</span><span class="op">)</span></span>
<span>  <span class="va">upper</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/Extremes.html">min</a></span><span class="op">(</span><span class="va">P_A</span>, <span class="va">P_B</span><span class="op">)</span></span>
<span></span>
<span>  <span class="kw">if</span> <span class="op">(</span><span class="va">P_AB</span> <span class="op">&gt;=</span> <span class="va">lower</span> <span class="op">&amp;&amp;</span> <span class="va">P_AB</span> <span class="op">&lt;=</span> <span class="va">upper</span><span class="op">)</span> <span class="op">{</span></span>
<span>    <span class="fu"><a href="https://rdrr.io/r/base/cat.html">cat</a></span><span class="op">(</span><span class="st">"✓ Coerente: P(A∩B) ∈ ["</span>, <span class="va">lower</span>, <span class="st">","</span>, <span class="va">upper</span>, <span class="st">"]\n"</span><span class="op">)</span></span>
<span>    <span class="kw"><a href="https://rdrr.io/r/base/function.html">return</a></span><span class="op">(</span><span class="cn">TRUE</span><span class="op">)</span></span>
<span>  <span class="op">}</span> <span class="kw">else</span> <span class="op">{</span></span>
<span>    <span class="fu"><a href="https://rdrr.io/r/base/cat.html">cat</a></span><span class="op">(</span><span class="st">"✗ Incoerente: P(A∩B) ="</span>, <span class="va">P_AB</span>, </span>
<span>        <span class="st">"ma deve essere in ["</span>, <span class="va">lower</span>, <span class="st">","</span>, <span class="va">upper</span>, <span class="st">"]\n"</span><span class="op">)</span></span>
<span>    <span class="kw"><a href="https://rdrr.io/r/base/function.html">return</a></span><span class="op">(</span><span class="cn">FALSE</span><span class="op">)</span></span>
<span>  <span class="op">}</span></span>
<span><span class="op">}</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div></li>
</ol></section><section id="soluzioni-tabelle-congiunte" class="level3" data-number="2.9.13"><h3 data-number="2.9.13" class="anchored" data-anchor-id="soluzioni-tabelle-congiunte">
<span class="header-section-number">2.9.13</span> Soluzioni tabelle congiunte</h3>
<ol start="7" type="1">
<li>Tabella completata:
<ul>
<li><span class="math inline">\(P(A \cap B^c) = 0.40 - 0.25 = 0.15\)</span></li>
<li>
<span class="math inline">\(P(A^c \cap B) = P(B) - 0.25\)</span> (serve calcolare <span class="math inline">\(P(B)\)</span> da altre info)</li>
<li><span class="math inline">\(P(A^c) = 1 - 0.40 = 0.60\)</span></li>
<li><span class="math inline">\(P(A^c \cap B) = 0.60 - 0.45 = 0.15\)</span></li>
<li><span class="math inline">\(P(B) = 0.25 + 0.15 = 0.40\)</span></li>
<li><span class="math inline">\(P(B^c) = 0.15 + 0.45 = 0.60\)</span></li>
</ul>
<table class="caption-top table">
<thead><tr class="header">
<th></th>
<th><span class="math inline">\(B\)</span></th>
<th><span class="math inline">\(B^c\)</span></th>
<th>Marg.</th>
</tr></thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(A\)</span></td>
<td>0.25</td>
<td>0.15</td>
<td>0.40</td>
</tr>
<tr class="even">
<td><span class="math inline">\(A^c\)</span></td>
<td>0.15</td>
<td>0.45</td>
<td>0.60</td>
</tr>
<tr class="odd">
<td>Marg.</td>
<td>0.40</td>
<td>0.60</td>
<td>1.00</td>
</tr>
</tbody>
</table>
</li>
<li><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb17"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">P_C</span> <span class="op">&lt;-</span> <span class="fl">0.05</span></span>
<span><span class="va">P_pos</span> <span class="op">&lt;-</span> <span class="fl">0.08</span></span>
<span><span class="va">sens</span> <span class="op">&lt;-</span> <span class="fl">0.90</span></span>
<span></span>
<span><span class="co"># Congiunta</span></span>
<span><span class="va">P_C_and_pos</span> <span class="op">&lt;-</span> <span class="va">sens</span> <span class="op">*</span> <span class="va">P_C</span>  <span class="co"># = 0.045</span></span>
<span><span class="va">P_C_and_neg</span> <span class="op">&lt;-</span> <span class="va">P_C</span> <span class="op">-</span> <span class="va">P_C_and_pos</span>  <span class="co"># = 0.005</span></span>
<span><span class="va">P_notC_and_pos</span> <span class="op">&lt;-</span> <span class="va">P_pos</span> <span class="op">-</span> <span class="va">P_C_and_pos</span>  <span class="co"># = 0.035</span></span>
<span><span class="va">P_notC_and_neg</span> <span class="op">&lt;-</span> <span class="fl">1</span> <span class="op">-</span> <span class="op">(</span><span class="va">P_C_and_pos</span> <span class="op">+</span> <span class="va">P_C_and_neg</span> <span class="op">+</span> <span class="va">P_notC_and_pos</span><span class="op">)</span>  <span class="co"># = 0.915</span></span>
<span></span>
<span><span class="co"># a) P(C | +) = 0.045 / 0.08 = 0.5625</span></span>
<span><span class="co"># b) P(C | -) = 0.005 / 0.92 ≈ 0.0054</span></span>
<span><span class="co"># c) Specificità = P(- | C^c) = 0.915 / 0.95 ≈ 0.963</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div></li>
</ol></section><section id="soluzioni-esercizi-applicati" class="level3" data-number="2.9.14"><h3 data-number="2.9.14" class="anchored" data-anchor-id="soluzioni-esercizi-applicati">
<span class="header-section-number">2.9.14</span> Soluzioni esercizi applicati</h3>
<ol start="10" type="1">
<li><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb18"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">P_D</span> <span class="op">&lt;-</span> <span class="fl">0.55</span></span>
<span><span class="va">P_P</span> <span class="op">&lt;-</span> <span class="fl">0.30</span></span>
<span><span class="va">P_P_given_D</span> <span class="op">&lt;-</span> <span class="fl">0.45</span></span>
<span></span>
<span><span class="co"># a) Tabella</span></span>
<span><span class="va">P_D_and_P</span> <span class="op">&lt;-</span> <span class="va">P_P_given_D</span> <span class="op">*</span> <span class="va">P_D</span>  <span class="co"># = 0.2475</span></span>
<span><span class="va">P_D_and_notP</span> <span class="op">&lt;-</span> <span class="va">P_D</span> <span class="op">-</span> <span class="va">P_D_and_P</span>  <span class="co"># = 0.3025</span></span>
<span><span class="va">P_notD_and_P</span> <span class="op">&lt;-</span> <span class="va">P_P</span> <span class="op">-</span> <span class="va">P_D_and_P</span>  <span class="co"># = 0.0525</span></span>
<span><span class="va">P_notD_and_notP</span> <span class="op">&lt;-</span> <span class="fl">1</span> <span class="op">-</span> <span class="op">(</span><span class="va">P_D_and_P</span> <span class="op">+</span> <span class="va">P_D_and_notP</span> <span class="op">+</span> <span class="va">P_notD_and_P</span><span class="op">)</span>  <span class="co"># = 0.3975</span></span>
<span></span>
<span><span class="co"># b) P(D | P) = 0.2475 / 0.30 = 0.825</span></span>
<span></span>
<span><span class="co"># c) Test indipendenza: P(D) × P(P) = 0.55 × 0.30 = 0.165</span></span>
<span><span class="co">#    P(D ∩ P) = 0.2475 ≠ 0.165 → DIPENDENTI</span></span>
<span></span>
<span><span class="co"># d) P(D ∪ P) = 0.55 + 0.30 - 0.2475 = 0.6025</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div></li>
<li><p><code>r     # Vedi soluzione 8, adattata con prevalenza 0.25     # a) Tabella costruita con sens=0.80, spec=0.85, prev=0.25     # b) P(A | +) = [0.80 × 0.25] / [0.80 × 0.25 + 0.15 × 0.75] ≈ 0.640     # c) P(A^c | -) = [0.85 × 0.75] / [0.20 × 0.25 + 0.85 × 0.75] ≈ 0.927</code></p></li>
<li>
<p>Somma = 1.05 &gt; 1. Incoerente. Correzione (normalizzazione):</p>
<ul>
<li><span class="math inline">\(P(D) = 0.40 / 1.05 ≈ 0.381\)</span></li>
<li><span class="math inline">\(P(A) = 0.35 / 1.05 ≈ 0.333\)</span></li>
<li><span class="math inline">\(P(N) = 0.30 / 1.05 ≈ 0.286\)</span></li>
</ul>
</li>
</ol></section><section id="soluzioni-pensiero-critico" class="level3" data-number="2.9.15"><h3 data-number="2.9.15" class="anchored" data-anchor-id="soluzioni-pensiero-critico">
<span class="header-section-number">2.9.15</span> Soluzioni pensiero critico</h3>
<ol start="13" type="1">
<li><p>La tabella congiunta è più fondamentale perché rappresenta lo stato di credenza <strong>completo</strong> sul sistema. Da essa derivano automaticamente (e coerentemente) tutte le marginali e condizionate. Specificare marginali e condizionate separatamente rischia incoerenze (es. <span class="math inline">\(P(A \mid B) P(B) \neq P(B \mid A) P(A)\)</span>).</p></li>
<li><p>Nel continuo si usano <strong>densità di probabilità congiunta</strong> <span class="math inline">\(f(x, y)\)</span>. Il principio è identico: la densità congiunta determina tutto (marginali tramite integrazione, condizionate tramite rapporti di densità). La struttura di coerenza è preservata.</p></li>
<li><p>Non è un problema—riflette informazioni diverse. Con molti dati, la verosimiglianza dominerà e i posterior convergeranno, riducendo l’influenza dei prior diversi. È una caratteristica, non un bug: la soggettività è nelle assunzioni iniziali esplicite.</p></li>
</ol></section>
</div>
</div>
</div>
</section><section id="bibliografia" class="level2 unnumbered unlisted"><h2 class="unnumbered unlisted anchored" data-anchor-id="bibliografia">Bibliografia</h2>


</section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiato!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiato!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/ccaudek\.github\.io\/utet-prob\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
            // default icon
            link.classList.add("external");
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="../../chapters/probability/01_intro_prob_bayesian.html" class="pagination-link" aria-label="Interpretazione bayesiana della probabilità">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Interpretazione bayesiana della probabilità</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../../chapters/probability/03_equiprobability_combinatorics_bayesian.html" class="pagination-link" aria-label="Equiprobabilità e calcolo combinatorio come caso limite">
        <span class="nav-page-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Equiprobabilità e calcolo combinatorio come caso limite</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
    <div class="nav-footer-left">
<p><strong>Probabilità per la psicologia</strong> — Modulo di richiamo del progetto UTET a supporto del manuale <em>Metodi bayesiani in psicologia</em>.</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/ccaudek/utet-prob/blob/main/chapters/probability/02_axioms_coherence_bayesian.qmd" class="toc-action"><i class="bi bi-github"></i>Mostra il codice</a></li><li><a href="https://github.com/ccaudek/utet-prob/issues/new" class="toc-action"><i class="bi empty"></i>Segnala un problema</a></li></ul></div></div>
    <div class="nav-footer-right">
<p>Realizzato con <a href="https://quarto.org/">Quarto</a>.</p>
</div>
  </div>
</footer>


<script src="../../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>