<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="it" xml:lang="it"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.34">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>9&nbsp; Proprietà delle variabili casuali – Probabilità per la psicologia — Modulo di richiamo</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>

<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../chapters/probability/09_sampling_distr.html" rel="next">
<link href="../../chapters/probability/07_prob_distributions.html" rel="prev">
<link href="../../style/gauss.png" rel="icon" type="image/png">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-0a72236910a44089af39cd28873f322e.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-9908c7b05874059c2106d454ac00f1d0.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Nessun risultato",
    "search-matching-documents-text": "documenti trovati",
    "search-copy-link-title": "Copiare il link nella ricerca",
    "search-hide-matches-text": "Nascondere i risultati aggiuntivi",
    "search-more-match-text": "ci sono altri risultati in questo documento",
    "search-more-matches-text": "ulteriori risultati in questo documento",
    "search-clear-button-title": "Pulire",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancellare",
    "search-submit-button-title": "Inviare",
    "search-label": "Ricerca"
  }
}</script><script async="" src="https://www.googletagmanager.com/gtag/js?id=G-QT5S3P9D31"></script><script type="text/javascript">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-QT5S3P9D31', { 'anonymize_ip': true});
</script><style>html{ scroll-behavior: smooth; }</style>
<script>
window.MathJax = {
  tex: { inlineMath: [['$', '$'], ['\\(', '\\)']] },
  svg: { scale: 1, mtextInheritFont: true, fontCache: 'none', minScale: 1 },
  options: { renderActions: { addMenu: [0, '', ''] } },
  loader: { load: ['input/tex','output/svg'] }
};
</script><script>
window.MathJax = {
  tex: { inlineMath: [['$', '$'], ['\\(', '\\)']] },
  svg: { scale: 1, mtextInheritFont: true, fontCache: 'none', minScale: 1 },
  options: { renderActions: { addMenu: [0, '', ''] } },
  loader: { load: ['input/tex','output/svg'] }
};
// Suggerimento CSS: vedi sezione 3 per gli spazi attorno a display math
</script><script>
window.MathJax = {
  tex: {
    packages: {'[+]': ['boldsymbol']},
    inlineMath: [['$', '$'], ['\\(', '\\)']]
  },
  svg: { fontCache: 'global' }
};
</script><script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script><script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script><link rel="stylesheet" href="../../style/_typography-extras.css">
<link rel="stylesheet" href="../../style/_code-extras.css">
<link rel="stylesheet" href="../../style/_math-extras.css">
<link rel="stylesheet" href="../../style/styles.css">
</head>
<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Attiva/disattiva la barra laterale" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../chapters/probability/introduction_probability.html">Probabilità</a></li><li class="breadcrumb-item"><a href="../../chapters/probability/08_expval_var.html"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Proprietà delle variabili casuali</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Attiva/disattiva la barra laterale" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Ricerca" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../../">Probabilità per la psicologia — Modulo di richiamo</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/ccaudek/utet-prob/" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Attiva/disattiva la modalità lettore">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Ricerca"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Percorso e obiettivi</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../prefazione.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Prefazione</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../chapters/probability/introduction_probability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Probabilità</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/probability/01_intro_prob.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Interpretazione della probabilità</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/probability/02_probability_models.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Modelli probabilistici</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/probability/03_sigma-algebra.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Dal Discreto al Continuo: la <span class="math inline">\(\sigma\)</span>-algebra</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/probability/04_conditional_prob.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Probabilità condizionata</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/probability/05_bayes_theorem.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Il teorema di Bayes</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/probability/06_random_var.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Variabili casuali</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/probability/07_prob_distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Distribuzioni di massa e di densità</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/probability/08_expval_var.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Proprietà delle variabili casuali</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/probability/09_sampling_distr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Stime, stimatori e parametri</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/probability/10_joint_prob.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Probabilità congiunta</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/probability/11_cov_cor.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Covarianza e correlazione</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/probability/12_intro_distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Introduzione alle distribuzioni di probabilità</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/probability/13_discr_rv_distr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Distribuzioni di v.c. discrete</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/probability/14_cont_rv_distr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Distribuzioni di v.c. continue</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/probability/15_gauss.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Assunzione di gaussianità e trasformazioni dei dati</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/probability/16_likelihood.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">La verosimiglianza</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a02_math_symbols.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Simbologia di base</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a11_numbers.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Numeri e intervalli</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a12_sum_notation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Sommatorie</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a13_sets.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">D</span>&nbsp; <span class="chapter-title">Insiemi</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a14_combinatorics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">E</span>&nbsp; <span class="chapter-title">Calcolo combinatorio</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a15_calculus.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">F</span>&nbsp; <span class="chapter-title">Per liberarvi dai terrori preliminari</span></span></a>
  </div>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Sommario</h2>
   
  <ul class="collapse">
<li><a href="#tendenza-centrale" id="toc-tendenza-centrale" class="nav-link active" data-scroll-target="#tendenza-centrale"><span class="header-section-number">9.1</span> Tendenza centrale</a></li>
  <li><a href="#valore-atteso" id="toc-valore-atteso" class="nav-link" data-scroll-target="#valore-atteso"><span class="header-section-number">9.2</span> Valore atteso</a></li>
  <li><a href="#varianza" id="toc-varianza" class="nav-link" data-scroll-target="#varianza"><span class="header-section-number">9.3</span> Varianza</a></li>
  <li><a href="#standardizzazione" id="toc-standardizzazione" class="nav-link" data-scroll-target="#standardizzazione"><span class="header-section-number">9.4</span> Standardizzazione</a></li>
  <li><a href="#il-teorema-di-chebyshev" id="toc-il-teorema-di-chebyshev" class="nav-link" data-scroll-target="#il-teorema-di-chebyshev"><span class="header-section-number">9.5</span> Il teorema di Chebyshev</a></li>
  <li><a href="#momenti-di-variabili-casuali" id="toc-momenti-di-variabili-casuali" class="nav-link" data-scroll-target="#momenti-di-variabili-casuali"><span class="header-section-number">9.6</span> Momenti di variabili casuali</a></li>
  </ul><div class="toc-actions"><ul class="collapse"><li><a href="https://github.com/ccaudek/utet-prob/blob/main/chapters/probability/08_expval_var.qmd" class="toc-action"><i class="bi bi-github"></i>Mostra il codice</a></li><li><a href="https://github.com/ccaudek/utet-prob/issues/new" class="toc-action"><i class="bi empty"></i>Segnala un problema</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../chapters/probability/introduction_probability.html">Probabilità</a></li><li class="breadcrumb-item"><a href="../../chapters/probability/08_expval_var.html"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Proprietà delle variabili casuali</span></a></li></ol></nav><div class="quarto-title">
<h1 class="title"><span id="sec-prob-random-var-properties" class="quarto-section-identifier"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Proprietà delle variabili casuali</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header><div class="epigraph">
<blockquote class="blockquote">
<p>“If I expect <em>a</em> or <em>b</em>, and have an equal chance of gaining either of them, my Expectation is worth <span class="math inline">\((a+b)/2\)</span>.”</p>
<p>— <strong>Christiaan Huygens</strong>, <em>De ratiociniis in ludo aleae</em> (1657).</p>
</blockquote>
</div>
<section id="introduzione" class="level2 unnumbered unlisted"><h2 class="unnumbered unlisted anchored" data-anchor-id="introduzione">Introduzione</h2>
<p>Spesso è molto utile sintetizzare la distribuzione di una variabile casuale attraverso indicatori caratteristici. Questi indicatori consentono di cogliere le principali proprietà della distribuzione, come la posizione centrale (ovvero il “baricentro”) e la variabilità (ossia la dispersione attorno al centro). In questo modo, è possibile ottenere una descrizione sintetica e significativa della distribuzione di probabilità della variabile casuale.</p>
<p>In questo capitolo, introdurremo i concetti fondamentali di valore atteso e varianza di una variabile casuale, che sono strumenti essenziali per comprendere e riassumere le proprietà di una distribuzione probabilistica.</p>
<section id="panoramica-del-capitolo" class="level3 unnumbered unlisted"><h3 class="unnumbered unlisted anchored" data-anchor-id="panoramica-del-capitolo">Panoramica del capitolo</h3>
<ul>
<li>Concetti di valore atteso e varianza per variabili casuali discrete.</li>
<li>Proprietà del valore atteso e della varianza.</li>
<li>Valore atteso e varianza per variabili casuali continue.</li>
<li>Utilizzare R per calcolare valore atteso e varianza.</li>
</ul>
<div class="callout callout-style-simple callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Prerequisiti
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Per affrontare al meglio questo capitolo, assicurati di avere familiarità con i seguenti argomenti:</p>
<ul>
<li>È fondamentale aver letto la sezione <a href="../appendix/a15_calculus.html" class="quarto-xref"><span>Appendice F</span></a>.</li>
<li>Si consiglia la lettura del capitolo <em>Expectation</em> in <span class="citation" data-cites="schervish2014probability">Schervish &amp; DeGroot (<a href="#ref-schervish2014probability" role="doc-biblioref">2014</a>)</span>.</li>
</ul>
</div>
</div>
</div>
<div class="callout callout-style-simple callout-caution no-icon callout-titled" title="Preparazione del Notebook">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Preparazione del Notebook
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">here</span><span class="fu">::</span><span class="fu"><a href="https://here.r-lib.org/reference/here.html">here</a></span><span class="op">(</span><span class="st">"code"</span>, <span class="st">"_common.R"</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="kw"><a href="https://rdrr.io/r/base/source.html">source</a></span><span class="op">(</span><span class="op">)</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</div>
</section></section><section id="tendenza-centrale" class="level2" data-number="9.1"><h2 data-number="9.1" class="anchored" data-anchor-id="tendenza-centrale">
<span class="header-section-number">9.1</span> Tendenza centrale</h2>
<p>Quando vogliamo comprendere il comportamento tipico di una variabile casuale, ci interessa spesso determinare il suo “valore tipico”. Tuttavia, questa nozione può essere interpretata in diversi modi:</p>
<ul>
<li>
<em>Media</em>: La somma dei valori divisa per il numero dei valori.</li>
<li>
<em>Mediana</em>: Il valore centrale della distribuzione, quando i dati sono ordinati in senso crescente o decrescente.</li>
<li>
<em>Moda</em>: Il valore che si verifica con maggiore frequenza.</li>
</ul>
<p>Ad esempio, per il set di valori <span class="math inline">\(\{3, 1, 4, 1, 5\}\)</span>, la media è <span class="math inline">\(\frac{3+1+4+1+5}{5} = 2.8\)</span>, la mediana è 3, e la moda è 1. Tuttavia, quando ci occupiamo di variabili casuali, anziché di semplici sequenze di numeri, diventa necessario chiarire cosa intendiamo per “valore tipico” in questo contesto. Questo ci porta alla definizione formale del valore atteso.</p>
</section><section id="valore-atteso" class="level2" data-number="9.2"><h2 data-number="9.2" class="anchored" data-anchor-id="valore-atteso">
<span class="header-section-number">9.2</span> Valore atteso</h2>
<div id="def-" class="theorem definition">
<p><span class="theorem-title"><strong>Definizione 9.1</strong></span> Sia <span class="math inline">\(X\)</span> una variabile casuale discreta che assume i valori <span class="math inline">\(x_1, \dots, x_n\)</span> con probabilità <span class="math inline">\(P(X = x_i) = p(x_i)\)</span>. Il <em>valore atteso</em> di <span class="math inline">\(X\)</span>, denotato con <span class="math inline">\(\mathbb{E}(X)\)</span>, è definito come:</p>
<p><span class="math display">\[
\mathbb{E}(X) = \sum_{i=1}^n x_i \cdot p(x_i).
\]</span></p>
</div>
<p>In altre parole, il valore atteso (noto anche come speranza matematica o aspettazione) di una variabile casuale è la somma di tutti i valori che la variabile può assumere, ciascuno ponderato dalla probabilità con cui esso si verifica.</p>
<div class="callout callout-style-simple callout-note no-icon callout-titled" title="Esercizio">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Esercizio
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Calcoliamo il valore atteso della variabile casuale <span class="math inline">\(X\)</span> corrispondente al lancio di una moneta equilibrata, dove <em>testa</em> corrisponde a <span class="math inline">\(X = 1\)</span> e <em>croce</em> corrisponde a <span class="math inline">\(X = 0\)</span>:</p>
<p><span class="math display">\[
\mathbb{E}(X) = \sum_{i=1}^{2} x_i \cdot P(x_i) = 0 \cdot \frac{1}{2} + 1 \cdot \frac{1}{2} = 0.5.
\]</span></p>
</div>
</div>
</div>
<div class="callout callout-style-simple callout-note no-icon callout-titled" title="Esercizio">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Esercizio
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Calcoliamo il valore atteso della variabile casuale <span class="math inline">\(X\)</span> che rappresenta la somma dei punti ottenuti dal lancio di due dadi equilibrati a sei facce.</p>
<p>La variabile casuale <span class="math inline">\(X\)</span> può assumere i seguenti valori:</p>
<p><span class="math display">\[
\{2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12\}.
\]</span></p>
<p>La probabilità associata a ciascun valore è data dalla distribuzione di massa di probabilità. Ad esempio, il valore <span class="math inline">\(X = 2\)</span> si ottiene solo se entrambi i dadi mostrano 1, quindi ha probabilità:</p>
<p><span class="math display">\[
P(X = 2) = \frac{1}{36}.
\]</span></p>
<p>Analogamente, <span class="math inline">\(X = 7\)</span> può essere ottenuto con sei combinazioni diverse: (1,6), (2,5), (3,4), (4,3), (5,2), (6,1), quindi:</p>
<p><span class="math display">\[
P(X = 7) = \frac{6}{36}.
\]</span></p>
<p>La distribuzione di massa di probabilità completa è:</p>
<p><span class="math display">\[
P(X) = \left\{\frac{1}{36}, \frac{2}{36}, \frac{3}{36}, \frac{4}{36}, \frac{5}{36}, \frac{6}{36}, \frac{5}{36}, \frac{4}{36}, \frac{3}{36}, \frac{2}{36}, \frac{1}{36}\right\}.
\]</span></p>
<p>Il valore atteso <span class="math inline">\(\mathbb{E}[X]\)</span> è definito come:</p>
<p><span class="math display">\[
\mathbb{E}[X] = \sum_{x} x \cdot P(X = x).
\]</span></p>
<p>Applicando questa formula:</p>
<p><span class="math display">\[
\mathbb{E}[X] = 2 \cdot \frac{1}{36} + 3 \cdot \frac{2}{36} + 4 \cdot \frac{3}{36} + \cdots + 12 \cdot \frac{1}{36} = 7.
\]</span></p>
<p>Ecco come calcolarlo utilizzando R:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Valori di X e le loro probabilità</span></span>
<span><span class="va">valori</span> <span class="op">&lt;-</span> <span class="fl">2</span><span class="op">:</span><span class="fl">12</span></span>
<span><span class="va">prob</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>, <span class="fl">2</span>, <span class="fl">3</span>, <span class="fl">4</span>, <span class="fl">5</span>, <span class="fl">6</span>, <span class="fl">5</span>, <span class="fl">4</span>, <span class="fl">3</span>, <span class="fl">2</span>, <span class="fl">1</span><span class="op">)</span> <span class="op">/</span> <span class="fl">36</span></span>
<span></span>
<span><span class="co"># Calcolo del valore atteso</span></span>
<span><span class="va">valore_atteso</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">valori</span> <span class="op">*</span> <span class="va">prob</span><span class="op">)</span></span>
<span><span class="va">valore_atteso</span></span>
<span><span class="co">#&gt; [1] 7</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Il risultato sarà: <span class="math display">\[
\mathbb{E}[X] = 7.
\]</span></p>
<p>Per rappresentare graficamente la distribuzione di massa di probabilità:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb3"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Creazione di un data frame</span></span>
<span><span class="va">dati</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span>Valore <span class="op">=</span> <span class="va">valori</span>, Probabilità <span class="op">=</span> <span class="va">prob</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Plot</span></span>
<span><span class="fu">ggplot</span><span class="op">(</span><span class="va">dati</span>, <span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">Valore</span>, y <span class="op">=</span> <span class="va">Probabilità</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_col</span><span class="op">(</span>fill <span class="op">=</span> <span class="st">"lightblue"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">labs</span><span class="op">(</span></span>
<span>    title <span class="op">=</span> <span class="st">"Distribuzione di Massa di Probabilità per X"</span>,</span>
<span>    x <span class="op">=</span> <span class="st">"Valore della Somma (X)"</span>,</span>
<span>    y <span class="op">=</span> <span class="st">"Probabilità"</span></span>
<span>  <span class="op">)</span> </span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="08_expval_var_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:85.0%"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
<p>Nel suo <a href="https://en.wikipedia.org/wiki/Ars_Conjectandi">Ars conjectandi</a>, Bernoulli introduce la nozione di valore atteso con le seguenti parole:</p>
<blockquote class="blockquote">
<p>il termine “aspettativa” non deve essere inteso nel suo significato comune […], bensì come la speranza di ottenere il meglio diminuita dalla paura di ottenere il peggio. Pertanto, il valore della nostra aspettativa rappresenta sempre qualcosa di intermedio tra il meglio che possiamo sperare e il peggio che possiamo temere <span class="citation" data-cites="hacking2006emergence">(<a href="#ref-hacking2006emergence" role="doc-biblioref">Hacking, 2006</a>)</span>.</p>
</blockquote>
<p>In termini moderni, questa intuizione può essere rappresentata in modo più chiaro attraverso una simulazione. Possiamo affermare, infatti, che il valore atteso di una variabile casuale corrisponde alla media aritmetica di un gran numero di realizzazioni indipendenti della variabile stessa.</p>
<div class="callout callout-style-simple callout-note no-icon callout-titled" title="Esercizio">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Esercizio
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Per fare un esempio concreto, consideriamo nuovamente il caso del lancio di due dadi bilanciati a sei facce, dove la variabile casuale <span class="math inline">\(X\)</span> rappresenta la “somma dei due dadi”. Simuliamo un numero elevato di realizzazioni indipendenti di <span class="math inline">\(X\)</span>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb4"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">123</span><span class="op">)</span>  </span>
<span><span class="va">x_samples</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/sample.html">sample</a></span><span class="op">(</span><span class="va">valori</span>, size <span class="op">=</span> <span class="fl">1e6</span>, replace <span class="op">=</span> <span class="cn">TRUE</span>, prob <span class="op">=</span> <span class="va">prob</span><span class="op">)</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>L’istruzione <code>sample(x, size = 1e6, replace = TRUE, prob = px))</code> utilizza R per generare un array di 1.000.000 di elementi (specificato dal parametro <code>size</code>), selezionati casualmente dall’array <code>x</code> secondo le probabilità specificate nell’array <code>px</code>.</p>
<p>Quando il numero di realizzazioni indipendenti è sufficientemente grande, la media aritmetica dei campioni generati si avvicina al valore atteso della variabile casuale:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb5"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">x_samples</span><span class="op">)</span></span>
<span><span class="co">#&gt; [1] 7</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Questo risultato conferma che il valore atteso <span class="math inline">\(\mathbb{E}[X] = 7\)</span> rappresenta la somma media dei punti ottenuti nel lancio di due dadi equilibrati su un numero elevato di prove. Anche se ogni singola somma può variare tra 2 e 12, in media ci aspettiamo una somma di 7.</p>
<p>L’aspettativa può anche essere interpretata come un <strong>centro di massa</strong>. Immagina che delle masse puntiformi con pesi <span class="math inline">\(p_1, p_2, \dots, p_n\)</span> siano posizionate alle posizioni <span class="math inline">\(x_1, x_2, \dots, x_n\)</span> sulla retta reale. Il centro di massa—il punto in cui i pesi sono bilanciati—è dato da:</p>
<p><span class="math display">\[
\text{centro di massa} = x_1 p_1 + x_2 p_2 + \dots + x_n p_n,
\]</span></p>
<p>che corrisponde esattamente all’aspettativa della variabile discreta <span class="math inline">\(X\)</span>, che assume valori <span class="math inline">\(x_1, \dots, x_n\)</span> con probabilità <span class="math inline">\(p_1, \dots, p_n\)</span>. Una conseguenza ovvia di questa interpretazione è che, per una funzione di densità di probabilità (pdf) simmetrica, l’aspettativa coincide con il punto di simmetria (a patto che l’aspettativa esista).</p>
<div id="fig-exp-val" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-exp-val-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../../figures/expected_value.png" class="img-fluid figure-img" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-exp-val-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;9.1: L’aspettativa come centro di massa <span class="citation" data-cites="kroese2025statistical">(figura tratta da <a href="#ref-kroese2025statistical" role="doc-biblioref">Chan &amp; Kroese, 2025</a>)</span>.
</figcaption></figure>
</div>
</div>
</div>
</div>
<section id="proprietà-del-valore-atteso" class="level3" data-number="9.2.1"><h3 data-number="9.2.1" class="anchored" data-anchor-id="proprietà-del-valore-atteso">
<span class="header-section-number">9.2.1</span> Proprietà del valore atteso</h3>
<p>Una delle proprietà più importanti del valore atteso è la sua <strong>linearità</strong>: il valore atteso della somma di due variabili casuali è uguale alla somma dei loro rispettivi valori attesi:</p>
<p><span id="eq-prop-expval-linearity"><span class="math display">\[
\mathbb{E}(X + Y) = \mathbb{E}(X) + \mathbb{E}(Y).
\tag{9.1}\]</span></span></p>
<p>Questa proprietà, espressa dalla formula sopra, è intuitiva quando <span class="math inline">\(X\)</span> e <span class="math inline">\(Y\)</span> sono variabili casuali indipendenti, ma è valida anche nel caso in cui <span class="math inline">\(X\)</span> e <span class="math inline">\(Y\)</span> siano correlate.</p>
<p>Inoltre, se moltiplichiamo una variabile casuale per una costante <span class="math inline">\(c\)</span>, il valore atteso del prodotto è uguale alla costante moltiplicata per il valore atteso della variabile casuale:</p>
<p><span id="eq-prop-expval-const"><span class="math display">\[
\mathbb{E}(cY) = c \mathbb{E}(Y).
\tag{9.2}\]</span></span></p>
<p>Questa proprietà ci dice che una costante può essere “estratta” dall’operatore di valore atteso, e si applica a qualunque numero di variabili casuali.</p>
<p>Un’altra proprietà significativa riguarda il prodotto di variabili casuali indipendenti. Se <span class="math inline">\(X\)</span> e <span class="math inline">\(Y\)</span> sono indipendenti, allora il valore atteso del loro prodotto è uguale al prodotto dei loro valori attesi:</p>
<p><span id="eq-expval-prod-ind-rv"><span class="math display">\[
\mathbb{E}(XY) = \mathbb{E}(X) \mathbb{E}(Y).
\tag{9.3}\]</span></span></p>
<p>Infine, consideriamo la media aritmetica <span class="math inline">\(\bar{X} = \frac{X_1 + \ldots + X_n}{n}\)</span> di <span class="math inline">\(n\)</span> variabili casuali indipendenti con la stessa distribuzione e con valore atteso <span class="math inline">\(\mu\)</span>. Il valore atteso della media aritmetica è:</p>
<p><span class="math display">\[
\mathbb{E}(\bar{X}) = \frac{1}{n} \left(\mathbb{E}(X_1) + \dots + \mathbb{E}(X_n)\right) = \frac{1}{n} \cdot n \cdot \mathbb{E}(X) = \mu.
\]</span></p>
<p>Questo risultato conferma che la media aritmetica di un campione di variabili casuali indipendenti ha lo stesso valore atteso della distribuzione originaria, rendendo il valore atteso uno strumento cruciale per l’analisi statistica e probabilistica.</p>
<div class="callout callout-style-simple callout-note no-icon callout-titled" title="Esercizio">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Esercizio
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Consideriamo il seguente esperimento casuale. Sia <span class="math inline">\(Y\)</span> il numero che si ottiene dal lancio di un dado equilibrato a sei facce e <span class="math inline">\(Y\)</span> il numero di teste prodotto dal lancio di una moneta equilibrata (0 oppure 1). Troviamo il valore atteso di <span class="math inline">\(X+Y\)</span>.</p>
<p>Per risolvere il problema iniziamo a costruire lo spazio campione dell’esperimento casuale.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 31%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
</colgroup>
<thead><tr class="header">
<th style="text-align: center;"><span class="math inline">\(x /\ y\)</span></th>
<th style="text-align: center;">1</th>
<th style="text-align: center;">2</th>
<th style="text-align: center;">3</th>
<th style="text-align: center;">4</th>
<th style="text-align: center;">5</th>
<th style="text-align: center;">6</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">0</td>
<td style="text-align: center;">(0, 1)</td>
<td style="text-align: center;">(0, 2)</td>
<td style="text-align: center;">(0, 3)</td>
<td style="text-align: center;">(0, 4)</td>
<td style="text-align: center;">(0, 5)</td>
<td style="text-align: center;">(0, 6)</td>
</tr>
<tr class="even">
<td style="text-align: center;">1</td>
<td style="text-align: center;">(1, 1)</td>
<td style="text-align: center;">(1, 2)</td>
<td style="text-align: center;">(1, 3)</td>
<td style="text-align: center;">(1, 4)</td>
<td style="text-align: center;">(1, 5)</td>
<td style="text-align: center;">(1, 6)</td>
</tr>
</tbody>
</table>
<p>ovvero</p>
<table class="caption-top table">
<thead><tr class="header">
<th style="text-align: center;"><span class="math inline">\(x /\ y\)</span></th>
<th style="text-align: center;">1</th>
<th style="text-align: center;">2</th>
<th style="text-align: center;">3</th>
<th style="text-align: center;">4</th>
<th style="text-align: center;">5</th>
<th style="text-align: center;">6</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">0</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">6</td>
</tr>
<tr class="even">
<td style="text-align: center;">1</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">6</td>
<td style="text-align: center;">7</td>
</tr>
</tbody>
</table>
<p>Il risultato del lancio del dado è indipendente dal risultato del lancio della moneta. Pertanto, ciascun evento elementare dello spazio campione avrà la stessa probabilità di verificarsi, ovvero <span class="math inline">\(P(\omega) = \frac{1}{12}\)</span>. Il valore atteso di <span class="math inline">\(X+Y\)</span> è dunque uguale a:</p>
<p><span class="math display">\[
\mathbb{E}(X+Y) = 1 \cdot \frac{1}{12} + 2 \cdot \frac{1}{12} + \dots + 7 \cdot \frac{1}{12} = 4.0.
\]</span></p>
<p>Si ottiene lo stesso risultato usando l’<a href="#eq-prop-expval-linearity" class="quarto-xref">Equazione&nbsp;<span>9.1</span></a>:</p>
<p><span class="math display">\[
\mathbb{E}(X+Y) = \mathbb{E}(X) + E(Y) = 3.5 + 0.5 = 4.0.
\]</span></p>
</div>
</div>
</div>
<div class="callout callout-style-simple callout-note no-icon callout-titled" title="Esercizio">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Esercizio
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Svolgiamo ora l’esercizio in R</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb6"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">coin</span> <span class="op">&lt;-</span> <span class="fl">0</span><span class="op">:</span><span class="fl">1</span>  <span class="co"># Valori della moneta: testa (0) e croce (1)</span></span>
<span><span class="va">die</span> <span class="op">&lt;-</span> <span class="fl">1</span><span class="op">:</span><span class="fl">6</span>   <span class="co"># Valori del dado: da 1 a 6</span></span>
<span></span>
<span><span class="co"># Creazione del campione come combinazione di valori (moneta, dado)</span></span>
<span><span class="va">sample</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/expand.grid.html">expand.grid</a></span><span class="op">(</span>coin <span class="op">=</span> <span class="va">coin</span>, die <span class="op">=</span> <span class="va">die</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="va">sample</span><span class="op">)</span></span>
<span><span class="co">#&gt;    coin die</span></span>
<span><span class="co">#&gt; 1     0   1</span></span>
<span><span class="co">#&gt; 2     1   1</span></span>
<span><span class="co">#&gt; 3     0   2</span></span>
<span><span class="co">#&gt; 4     1   2</span></span>
<span><span class="co">#&gt; 5     0   3</span></span>
<span><span class="co">#&gt; 6     1   3</span></span>
<span><span class="co">#&gt; 7     0   4</span></span>
<span><span class="co">#&gt; 8     1   4</span></span>
<span><span class="co">#&gt; 9     0   5</span></span>
<span><span class="co">#&gt; 10    1   5</span></span>
<span><span class="co">#&gt; 11    0   6</span></span>
<span><span class="co">#&gt; 12    1   6</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb7"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">px</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/numeric.html">numeric</a></span><span class="op">(</span><span class="op">)</span>  <span class="co"># Vettore per memorizzare le probabilità</span></span>
<span></span>
<span><span class="kw">for</span> <span class="op">(</span><span class="va">i</span> <span class="kw">in</span> <span class="fl">1</span><span class="op">:</span><span class="fl">7</span><span class="op">)</span> <span class="op">{</span></span>
<span>  <span class="co"># Filtrare le combinazioni in cui la somma è uguale a 'i'</span></span>
<span>  <span class="va">event</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/subset.html">subset</a></span><span class="op">(</span><span class="va">sample</span>, <span class="va">coin</span> <span class="op">+</span> <span class="va">die</span> <span class="op">==</span> <span class="va">i</span><span class="op">)</span></span>
<span>  <span class="co"># Calcolare la probabilità</span></span>
<span>  <span class="va">prob</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/nrow.html">nrow</a></span><span class="op">(</span><span class="va">event</span><span class="op">)</span> <span class="op">/</span> <span class="fu"><a href="https://rdrr.io/r/base/nrow.html">nrow</a></span><span class="op">(</span><span class="va">sample</span><span class="op">)</span></span>
<span>  <span class="va">px</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">px</span>, <span class="va">prob</span><span class="op">)</span></span>
<span>  </span>
<span>  <span class="co"># Stampare la probabilità</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/base/cat.html">cat</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/sprintf.html">sprintf</a></span><span class="op">(</span><span class="st">"P(X + Y = %d) = %d / %d\n"</span>, <span class="va">i</span>, <span class="fu"><a href="https://rdrr.io/r/base/nrow.html">nrow</a></span><span class="op">(</span><span class="va">event</span><span class="op">)</span>, <span class="fu"><a href="https://rdrr.io/r/base/nrow.html">nrow</a></span><span class="op">(</span><span class="va">sample</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="op">}</span></span>
<span><span class="co">#&gt; P(X + Y = 1) = 1 / 12</span></span>
<span><span class="co">#&gt; P(X + Y = 2) = 2 / 12</span></span>
<span><span class="co">#&gt; P(X + Y = 3) = 2 / 12</span></span>
<span><span class="co">#&gt; P(X + Y = 4) = 2 / 12</span></span>
<span><span class="co">#&gt; P(X + Y = 5) = 2 / 12</span></span>
<span><span class="co">#&gt; P(X + Y = 6) = 2 / 12</span></span>
<span><span class="co">#&gt; P(X + Y = 7) = 1 / 12</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb8"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">x</span> <span class="op">&lt;-</span> <span class="fl">1</span><span class="op">:</span><span class="fl">7</span>  <span class="co"># Valori della variabile casuale (somma di moneta e dado)</span></span>
<span><span class="va">expected_value</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">x</span> <span class="op">*</span> <span class="va">px</span><span class="op">)</span></span>
<span><span class="va">expected_value</span></span>
<span><span class="co">#&gt; [1] 4</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</div>
<div class="callout callout-style-simple callout-note no-icon callout-titled" title="Esercizio">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-8-contents" aria-controls="callout-8" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Esercizio
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-8" class="callout-8-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Consideriamo le variabili casuali <span class="math inline">\(X\)</span> e <span class="math inline">\(Y\)</span> definite nel caso del lancio di tre monete equilibrate, dove <span class="math inline">\(X\)</span> conta il numero delle teste nei tre lanci e <span class="math inline">\(Y\)</span> conta il numero delle teste al primo lancio. Si calcoli il valore atteso di <span class="math inline">\(Z = X \cdot Y\)</span>.</p>
<p>La distribuzione di probabilità congiunta <span class="math inline">\(P(X, Y)\)</span> è fornita nella tabella seguente.</p>
<table class="caption-top table">
<thead><tr class="header">
<th style="text-align: center;"><span class="math inline">\(x /\ y\)</span></th>
<th style="text-align: center;">0</th>
<th style="text-align: center;">1</th>
<th style="text-align: center;"><span class="math inline">\(p(Y)\)</span></th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">0</td>
<td style="text-align: center;">1/8</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">1/8</td>
</tr>
<tr class="even">
<td style="text-align: center;">1</td>
<td style="text-align: center;">2/8</td>
<td style="text-align: center;">1/8</td>
<td style="text-align: center;">3/8</td>
</tr>
<tr class="odd">
<td style="text-align: center;">2</td>
<td style="text-align: center;">1/8</td>
<td style="text-align: center;">2/8</td>
<td style="text-align: center;">3/8</td>
</tr>
<tr class="even">
<td style="text-align: center;">3</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">1/8</td>
<td style="text-align: center;">1/8</td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="math inline">\(p(y)\)</span></td>
<td style="text-align: center;">4/8</td>
<td style="text-align: center;">4/8</td>
<td style="text-align: center;">1.0</td>
</tr>
</tbody>
</table>
<p>Il calcolo del valore atteso di <span class="math inline">\(XY\)</span> si riduce a</p>
<p><span class="math display">\[
\mathbb{E}(Z) = 1 \cdot \frac{1}{8} + 2 \cdot \frac{2}{8} + 3 \cdot \frac{1}{8} = 1.0.
\]</span></p>
<p>Si noti che le variabili casuali <span class="math inline">\(Y\)</span> e <span class="math inline">\(Y\)</span> non sono indipendenti. Dunque non possiamo usare l’<a href="#eq-expval-prod-ind-rv" class="quarto-xref">Equazione&nbsp;<span>9.3</span></a>. Infatti, il valore atteso di <span class="math inline">\(X\)</span> è</p>
<p><span class="math display">\[
\mathbb{E}(X) = 1 \cdot \frac{3}{8} + 2 \cdot \frac{3}{8} + 3 \cdot \frac{1}{8} = 1.5
\]</span></p>
<p>e il valore atteso di <span class="math inline">\(Y\)</span> è</p>
<p><span class="math display">\[
\mathbb{E}(Y) = 0 \cdot \frac{4}{8} + 1 \cdot \frac{4}{8} = 0.5.
\]</span></p>
<p>Perciò</p>
<p><span class="math display">\[
1.5 \cdot 0.5 \neq 1.0.
\]</span></p>
</div>
</div>
</div>
</section><section id="valore-atteso-di-una-variabile-casuale-continua" class="level3" data-number="9.2.2"><h3 data-number="9.2.2" class="anchored" data-anchor-id="valore-atteso-di-una-variabile-casuale-continua">
<span class="header-section-number">9.2.2</span> Valore atteso di una variabile casuale continua</h3>
<p>Nel caso di una variabile casuale continua <span class="math inline">\(X\)</span>, il valore atteso è definito come:</p>
<p><span class="math display">\[
\mathbb{E}(X) = \int_{-\infty}^{+\infty} x \cdot p(x) \, \mathrm{d}x.
\]</span></p>
<p>Anche in questo contesto, il valore atteso rappresenta una media ponderata dei valori di <span class="math inline">\(x\)</span>, dove ogni possibile valore di <span class="math inline">\(x\)</span> è ponderato in base alla densità di probabilità <span class="math inline">\(p(x)\)</span>.</p>
<p>L’integrale può essere interpretato analogamente a una somma continua, in cui <span class="math inline">\(x\)</span> rappresenta la posizione delle barre infinitamente strette di un istogramma, e <span class="math inline">\(p(x)\)</span> rappresenta l’altezza di tali barre. La notazione <span class="math inline">\(\int_{-\infty}^{+\infty}\)</span> indica che si sta sommando il contributo di ogni valore possibile di <span class="math inline">\(x\)</span> lungo l’intero asse reale.</p>
<p>Questa interpretazione rende chiaro come l’integrale calcoli una somma ponderata che si estende su tutti i possibili valori di <span class="math inline">\(x\)</span>, fornendo una misura centrale della distribuzione della variabile casuale continua. Per ulteriori dettagli sulla notazione dell’integrale, si veda l’<span class="quarto-unresolved-ref">?sec-calculus</span>.</p>
<section id="moda" class="level4" data-number="9.2.2.1"><h4 data-number="9.2.2.1" class="anchored" data-anchor-id="moda">
<span class="header-section-number">9.2.2.1</span> Moda</h4>
<p>Un’altra misura di tendenza centrale delle variabili casuali continue è la moda. La moda di <span class="math inline">\(Y\)</span> individua il valore <span class="math inline">\(y\)</span> più plausibile, ovvero il valore <span class="math inline">\(y\)</span> che massimizza la funzione di densità <span class="math inline">\(p(y)\)</span>:</p>
<p><span id="eq-def-mode"><span class="math display">\[
Mo(Y) = \text{argmax}_y p(y).
\tag{9.4}\]</span></span></p>
<div class="callout callout-style-simple callout-note no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p>La notazione <span class="math inline">\(\text{argmax}_y p(y)\)</span> significa: il valore <span class="math inline">\(y\)</span> tale per cui la funzione <span class="math inline">\(p(y)\)</span> assume il suo valore massimo.</p>
</div>
</div>
</div>
</section></section></section><section id="varianza" class="level2" data-number="9.3"><h2 data-number="9.3" class="anchored" data-anchor-id="varianza">
<span class="header-section-number">9.3</span> Varianza</h2>
<p>Dopo il valore atteso, la seconda proprietà più importante di una variabile casuale è la <em>varianza</em>.</p>
<div id="def-" class="theorem definition">
<p><span class="theorem-title"><strong>Definizione 9.2</strong></span> Se <span class="math inline">\(X\)</span> è una variabile casuale discreta con distribuzione <span class="math inline">\(p(x)\)</span>, la varianza di <span class="math inline">\(X\)</span>, denotata con <span class="math inline">\(\mathbb{V}(X)\)</span>, è definita come:</p>
<p><span id="eq-def-var-rv"><span class="math display">\[
\mathbb{V}(X) = \mathbb{E}\Big[\big(X - \mathbb{E}(X)\big)^2\Big].
\tag{9.5}\]</span></span></p>
</div>
<p>In altre parole, la varianza misura la deviazione media quadratica dei valori della variabile rispetto alla sua media. Se denotiamo il valore atteso di <span class="math inline">\(X\)</span> con <span class="math inline">\(\mu = \mathbb{E}(X)\)</span>, la varianza <span class="math inline">\(\mathbb{V}(X)\)</span> diventa il valore atteso di <span class="math inline">\((X - \mu)^2\)</span>.</p>
<p>La varianza rappresenta una misura della “dispersione” dei valori di <span class="math inline">\(X\)</span> intorno al suo valore atteso. Quando calcoliamo la varianza, stiamo effettivamente misurando quanto i valori di <span class="math inline">\(X\)</span> tendono a differire dalla media <span class="math inline">\(\mu\)</span>.</p>
<p>Per capire meglio, consideriamo la variabile casuale <span class="math inline">\(X - \mathbb{E}(X)\)</span>, detta <em>scarto</em> o <em>deviazione</em> dalla media. Questa variabile rappresenta le “distanze” tra i valori di <span class="math inline">\(X\)</span> e il valore atteso <span class="math inline">\(\mathbb{E}(X)\)</span>. Tuttavia, poiché lo scarto può essere positivo o negativo, la media dello scarto è sempre zero, il che lo rende inadatto a quantificare la dispersione.</p>
<p>Per risolvere questo problema, eleviamo al quadrato gli scarti, ottenendo <span class="math inline">\((X - \mathbb{E}(X))^2\)</span>, che rende tutte le deviazioni positive. La varianza è quindi la media di questi scarti al quadrato, fornendo una misura efficace della dispersione complessiva dei valori di <span class="math inline">\(X\)</span> rispetto alla sua media.</p>
<p>Questo concetto è fondamentale per comprendere la variabilità di una distribuzione e per applicare strumenti statistici che richiedono una conoscenza approfondita della distribuzione dei dati.</p>
<div class="callout callout-style-simple callout-note no-icon callout-titled" title="Esercizio">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-9-contents" aria-controls="callout-9" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Esercizio
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-9" class="callout-9-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Posta <span class="math inline">\(S\)</span> uguale alla somma dei punti ottenuti nel lancio di due dadi equilibrati, si calcoli la varianza di <span class="math inline">\(S\)</span>.</p>
<p>La variabile casuale <span class="math inline">\(S\)</span> ha la seguente distribuzione di probabilità:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 6%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
</colgroup>
<thead><tr class="header">
<th style="text-align: center;"><span class="math inline">\(s\)</span></th>
<th style="text-align: center;">2</th>
<th style="text-align: center;">3</th>
<th style="text-align: center;">4</th>
<th style="text-align: center;">5</th>
<th style="text-align: center;">6</th>
<th style="text-align: center;">7</th>
<th style="text-align: center;">8</th>
<th style="text-align: center;">9</th>
<th style="text-align: center;">10</th>
<th style="text-align: center;">11</th>
<th style="text-align: center;">12</th>
</tr></thead>
<tbody><tr class="odd">
<td style="text-align: center;"><span class="math inline">\(P(S = s)\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\frac{1}{36}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\frac{2}{36}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\frac{3}{36}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\frac{4}{36}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\frac{5}{36}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\frac{6}{36}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\frac{5}{36}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\frac{4}{36}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\frac{3}{36}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\frac{2}{36}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\frac{1}{36}\)</span></td>
</tr></tbody>
</table>
<p>Essendo <span class="math inline">\(\mathbb{E}(S) = 7\)</span>, la varianza diventa</p>
<p><span class="math display">\[
\begin{aligned}
\mathbb{V}(S) &amp;= \sum \left(s - \mathbb{E}(S)\right)^2 \cdot P(s) \notag\\
&amp;= (2 - 7)^2 \cdot \frac{1}{36} + (3-7)^2 \cdot \frac{3}{36} + \dots + (12 - 7)^2 \cdot \frac{1}{36} \notag\\
&amp;= 5.8333.\notag
\end{aligned}
\]</span></p>
</div>
</div>
</div>
<div class="callout callout-style-simple callout-note no-icon callout-titled" title="Esercizio">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-10-contents" aria-controls="callout-10" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Esercizio
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-10" class="callout-10-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Svolgiamo l’esercizio in R</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb9"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Definire i valori di x e le loro probabilità px</span></span>
<span><span class="va">x</span> <span class="op">&lt;-</span> <span class="fl">2</span><span class="op">:</span><span class="fl">12</span></span>
<span><span class="va">px</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span></span>
<span>  <span class="fl">1</span> <span class="op">/</span> <span class="fl">36</span>, <span class="fl">2</span> <span class="op">/</span> <span class="fl">36</span>, <span class="fl">3</span> <span class="op">/</span> <span class="fl">36</span>, <span class="fl">4</span> <span class="op">/</span> <span class="fl">36</span>, <span class="fl">5</span> <span class="op">/</span> <span class="fl">36</span>, <span class="fl">6</span> <span class="op">/</span> <span class="fl">36</span>,</span>
<span>  <span class="fl">5</span> <span class="op">/</span> <span class="fl">36</span>, <span class="fl">4</span> <span class="op">/</span> <span class="fl">36</span>, <span class="fl">3</span> <span class="op">/</span> <span class="fl">36</span>, <span class="fl">2</span> <span class="op">/</span> <span class="fl">36</span>, <span class="fl">1</span> <span class="op">/</span> <span class="fl">36</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Calcolare il valore atteso</span></span>
<span><span class="va">ex</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">x</span> <span class="op">*</span> <span class="va">px</span><span class="op">)</span></span>
<span><span class="va">ex</span></span>
<span><span class="co">#&gt; [1] 7</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Applichiamo l’<a href="#eq-def-var-rv" class="quarto-xref">Equazione&nbsp;<span>9.5</span></a>:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb10"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Calcolo della varianza utilizzando la definizione</span></span>
<span><span class="va">variance</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="op">(</span><span class="va">x</span> <span class="op">-</span> <span class="va">ex</span><span class="op">)</span><span class="op">^</span><span class="fl">2</span> <span class="op">*</span> <span class="va">px</span><span class="op">)</span></span>
<span><span class="va">variance</span></span>
<span><span class="co">#&gt; [1] 5.83</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Usiamo la funzione <code><a href="https://rdrr.io/r/stats/cor.html">var()</a></code> di <code>rv_discrete</code>:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb11"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Calcolo della varianza con pesi</span></span>
<span><span class="va">variance_check</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/weighted.mean.html">weighted.mean</a></span><span class="op">(</span><span class="op">(</span><span class="va">x</span> <span class="op">-</span> <span class="va">ex</span><span class="op">)</span><span class="op">^</span><span class="fl">2</span>, w <span class="op">=</span> <span class="va">px</span><span class="op">)</span></span>
<span><span class="va">variance_check</span></span>
<span><span class="co">#&gt; [1] 5.83</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</div>
<section id="formula-alternativa-per-la-varianza" class="level3" data-number="9.3.1"><h3 data-number="9.3.1" class="anchored" data-anchor-id="formula-alternativa-per-la-varianza">
<span class="header-section-number">9.3.1</span> Formula alternativa per la varianza</h3>
<p>La varianza di una variabile casuale <span class="math inline">\(X\)</span>, indicata come <span class="math inline">\(\mathbb{V}(X)\)</span>, misura la dispersione dei valori attorno alla media. La definizione classica è:</p>
<p><span class="math display">\[
\mathbb{V}(X) = \mathbb{E}\Big[\big(X - \mathbb{E}(X)\big)^2\Big].
\]</span></p>
<p>Esiste però una formula alternativa che semplifica il calcolo.</p>
<div class="proof">
<p><span class="proof-title"><em>Dimostrazione</em>. </span></p>
<ol type="1">
<li><p><strong>Espansione del quadrato</strong><br>
Consideriamo la varianza, definita come <span class="math inline">\(\mathbb{V}(X) = \mathbb{E}\big[(X - \mathbb{E}(X))^2\big]\)</span>.<br>
Espandiamo il quadrato <span class="math inline">\((X - \mathbb{E}(X))^2\)</span> utilizzando la regola <span class="math inline">\((a - b)^2 = a^2 - 2ab + b^2\)</span>: <span class="math display">\[
(X - \mathbb{E}(X))^2 = X^2 - 2\,X\,\mathbb{E}(X) + \big(\mathbb{E}(X)\big)^2.
\]</span></p></li>
<li><p><strong>Applicazione dell’aspettativa</strong><br>
Applichiamo <span class="math inline">\(\mathbb{E}[\cdot]\)</span> a ciascun termine, ricordando che l’aspettativa è un operatore lineare: <span class="math display">\[
\mathbb{E}\big[(X - \mathbb{E}(X))^2\big]
= \mathbb{E}\big[X^2\big]
  \;-\; 2 \,\mathbb{E}\big[X\,\mathbb{E}(X)\big]
  \;+\; \mathbb{E}\big[\big(\mathbb{E}(X)\big)^2\big].
\]</span></p></li>
<li>
<p><strong>Gestione dei termini costanti</strong><br>
L’aspettativa <span class="math inline">\(\mathbb{E}(X)\)</span> è una costante (indipendente da <span class="math inline">\(X\)</span>). Indichiamola con <span class="math inline">\(\mu\)</span>. Quindi:</p>
<ul>
<li>
<span class="math inline">\(\mathbb{E}(X^2)\)</span> resta com’è.</li>
<li>
<span class="math inline">\(\mathbb{E}[X \cdot \mu] = \mu \, \mathbb{E}[X] = \mu \cdot \mu = \mu^2\)</span>.</li>
<li>
<span class="math inline">\(\mathbb{E}\big(\mu^2\big) = \mu^2\)</span>.</li>
</ul>
</li>
<li>
<p><strong>Sostituzione e semplificazione</strong><br>
Rimpiazzando i risultati nel secondo passaggio si ottiene: <span class="math display">\[
\mathbb{E}(X^2) \;-\; 2\,\mu^2 \;+\; \mu^2
\;=\; \mathbb{E}(X^2) - \mu^2.
\]</span><br>
Poiché <span class="math inline">\(\mu = \mathbb{E}(X)\)</span>, la varianza può quindi essere scritta come:</p>
<p><span id="eq-variance-alt-formula"><span class="math display">\[
\boxed{
\mathbb{V}(X) = \mathbb{E}(X^2) \;-\; \bigl(\mathbb{E}(X)\bigr)^2.
}
\tag{9.6}\]</span></span></p>
</li>
</ol>
</div>
<p>Questa forma risulta molto utile per ragioni di efficienza computazionale: invece di calcolare gli scarti <span class="math inline">\((X - \mu)\)</span> per ogni osservazione, è sufficiente trovare <span class="math inline">\(\mathbb{E}(X^2)\)</span> e poi sottrarre <span class="math inline">\(\mu^2\)</span>. In tal modo si riducono i passaggi intermedi e, di conseguenza, si minimizzano gli errori pratici. Inoltre, nelle dimostrazioni che richiedono manipolazioni algebriche – come quelle tipiche della Teoria Classica dei Test – questa espressione semplifica notevolmente le trasformazioni.</p>
<div class="callout callout-style-simple callout-note no-icon callout-titled" title="Esercizio">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-11-contents" aria-controls="callout-11" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Esercizio
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-11" class="callout-11-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Consideriamo la variabile casuale <span class="math inline">\(X\)</span> che corrisponde al numero di teste che si osservano nel lancio di una moneta truccata con probabilità di testa uguale a 0.8. Si trovi la varianza di <span class="math inline">\(Y\)</span>.</p>
<p>Il valore atteso di <span class="math inline">\(X\)</span> è</p>
<p><span class="math display">\[
\mathbb{E}(X) = 0 \cdot 0.2 + 1 \cdot 0.8 = 0.8.
\]</span></p>
<p>Usando la formula tradizionale della varianza otteniamo:</p>
<p><span class="math display">\[
\mathbb{V}(X) = (0 - 0.8)^2 \cdot 0.2 + (1 - 0.8)^2 \cdot 0.8 = 0.16.
\]</span></p>
<p>Lo stesso risultato si trova con la formula alternativa della varianza. Il valore atteso di <span class="math inline">\(X^2\)</span> è</p>
<p><span class="math display">\[
\mathbb{E}(X^2) = 0^2 \cdot 0.2 + 1^2 \cdot 0.8 = 0.8.
\]</span></p>
<p>e la varianza diventa</p>
<p><span class="math display">\[
\mathbb{V}(X) = \mathbb{E}(X^2) - \big(\mathbb{E}(Y) \big)^2 = 0.8 - 0.8^2 = 0.16.
\]</span></p>
</div>
</div>
</div>
<div class="callout callout-style-simple callout-note no-icon callout-titled" title="Esercizio">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-12-contents" aria-controls="callout-12" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Esercizio
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-12" class="callout-12-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Svolgiamo l’esercizio in R:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb12"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Definire i valori di x e le probabilità px</span></span>
<span><span class="va">x</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0</span>, <span class="fl">1</span><span class="op">)</span></span>
<span><span class="va">px</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0.2</span>, <span class="fl">0.8</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Calcolare il risultato</span></span>
<span><span class="va">result</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">x</span><span class="op">^</span><span class="fl">2</span> <span class="op">*</span> <span class="va">px</span><span class="op">)</span> <span class="op">-</span> <span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">x</span> <span class="op">*</span> <span class="va">px</span><span class="op">)</span><span class="op">)</span><span class="op">^</span><span class="fl">2</span></span>
<span><span class="va">result</span></span>
<span><span class="co">#&gt; [1] 0.16</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</div>
</section><section id="proprietà" class="level3" data-number="9.3.2"><h3 data-number="9.3.2" class="anchored" data-anchor-id="proprietà">
<span class="header-section-number">9.3.2</span> Proprietà</h3>
<p><strong>Segno della varianza.</strong> La varianza di una variabile aleatoria non è mai negativa, ed è zero solamente quando la variabile assume un solo valore.</p>
<p><strong>Invarianza per traslazione.</strong> La varianza è invariante per traslazione, che lascia fisse le distanze dalla media, e cambia quadraticamente per riscalamento:</p>
<p><span class="math display">\[
\mathbb{V}(a + bX) = b^2\mathbb{V}(X).
\]</span></p>
<p><em>Dimostrazione.</em> Iniziamo a scrivere</p>
<p><span class="math display">\[
(aX+b)-{\mathbb{E}}[aX+b]=aX+b-a{\mathbb{E}}[X]-b=a(X-{\mathbb  {E}}[X]).
\]</span></p>
<p>Quindi</p>
<p><span class="math display">\[
\sigma _{{aX+b}}^{2}={\mathbb{E}}[a^{2}(X-{\mathbb  {E}}[X])^{2}]=a^{2}\sigma _{X}^{2}.
\]</span></p>
<p>Esaminiamo una dimostrazione numerica.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb13"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Definire i valori di x</span></span>
<span><span class="va">x</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">2</span>, <span class="fl">1</span>, <span class="fl">4</span>, <span class="fl">7</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Calcolare y</span></span>
<span><span class="va">y</span> <span class="op">&lt;-</span> <span class="fl">100</span> <span class="op">+</span> <span class="fl">2</span> <span class="op">*</span> <span class="va">x</span></span>
<span></span>
<span><span class="co"># Verificare la relazione tra le varianze</span></span>
<span><span class="va">result</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/cor.html">var</a></span><span class="op">(</span><span class="va">y</span><span class="op">)</span> <span class="op">==</span> <span class="fl">2</span><span class="op">^</span><span class="fl">2</span> <span class="op">*</span> <span class="fu"><a href="https://rdrr.io/r/stats/cor.html">var</a></span><span class="op">(</span><span class="va">x</span><span class="op">)</span></span>
<span><span class="va">result</span></span>
<span><span class="co">#&gt; [1] TRUE</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Varianza della somma di due variabili indipendenti.</strong> La varianza della somma di due variabili indipendenti o anche solo incorrelate è pari alla somma delle loro varianze:</p>
<p><span class="math display">\[
\mathbb{V}(X+Y) = \mathbb{V}(X) + \mathbb{V}(Y).
\]</span></p>
<p><em>Dimostrazione.</em> Se <span class="math inline">\(\mathbb{E}(X) = \mathbb{E}(Y) = 0\)</span>, allora <span class="math inline">\(\mathbb{E}(X+Y) = 0\)</span> e</p>
<p><span class="math display">\[\mathbb{V}(X+Y) = \mathbb{E}((X+Y)^2) = \mathbb{E}(X^2) + 2 \mathbb{E}(XY) + \mathbb{E}(Y^2).\]</span></p>
<p>Siccome le variabili sono indipendenti risulta <span class="math inline">\(\mathbb{E}(XY) = \mathbb{E}(X)\mathbb{E}(Y) = 0\)</span>.</p>
<p><strong>Varianza della differenza di due variabili indipendenti.</strong> La varianza della differenza di due variabili indipendenti è pari alla somma delle loro varianze:</p>
<p><span class="math display">\[
\mathbb{V}(X-Y) = \mathbb{V}(X) + \mathbb{V}(Y).
\]</span></p>
<p><em>Dimostrazione.</em></p>
<p><span class="math display">\[
\mathbb{V}(X-Y) = \mathbb{V}(X +(-Y)) = \mathbb{V}(X) + \mathbb{V}(-Y) = \mathbb{V}(X) + \mathbb{V}(Y).
\]</span></p>
<p><strong>Varianza della somma di due variabili non indipendenti.</strong> Se <span class="math inline">\(X\)</span> e <span class="math inline">\(Y\)</span> non sono indipendenti, la formula viene corretta dalla loro covarianza:</p>
<p><span class="math display">\[
\mathbb{V}(X+Y) = \mathbb{V}(X) + \mathbb{V}(Y) + 2 Cov(X,Y),
\]</span></p>
<p>dove <span class="math inline">\(Cov(X,Y) = \mathbb{E}(XY) - \mathbb{E}(X)\mathbb{E}(Y)\)</span>.</p>
<p>Una dimostrazione numerica di questo principio è fornita sotto.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb14"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Definire i valori di x e y</span></span>
<span><span class="va">x</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">2</span>, <span class="fl">1</span>, <span class="fl">4</span>, <span class="fl">7</span><span class="op">)</span></span>
<span><span class="va">y</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>, <span class="fl">3</span>, <span class="fl">5</span>, <span class="fl">11</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Calcolare la varianza di x + y con ddof = 0</span></span>
<span><span class="va">var_x_y</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="op">(</span><span class="va">x</span> <span class="op">+</span> <span class="va">y</span> <span class="op">-</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">x</span> <span class="op">+</span> <span class="va">y</span><span class="op">)</span><span class="op">)</span><span class="op">^</span><span class="fl">2</span><span class="op">)</span></span>
<span><span class="va">var_x_y</span></span>
<span><span class="co">#&gt; [1] 35.2</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb15"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Definire i valori di x e y</span></span>
<span><span class="va">x</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">2</span>, <span class="fl">1</span>, <span class="fl">4</span>, <span class="fl">7</span><span class="op">)</span></span>
<span><span class="va">y</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>, <span class="fl">3</span>, <span class="fl">5</span>, <span class="fl">11</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Calcolo della varianza combinata</span></span>
<span><span class="va">result</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="op">(</span><span class="va">x</span> <span class="op">-</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">x</span><span class="op">)</span><span class="op">)</span><span class="op">^</span><span class="fl">2</span><span class="op">)</span> <span class="op">+</span> </span>
<span>          <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="op">(</span><span class="va">y</span> <span class="op">-</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">y</span><span class="op">)</span><span class="op">)</span><span class="op">^</span><span class="fl">2</span><span class="op">)</span> <span class="op">+</span> </span>
<span>          <span class="fl">2</span> <span class="op">*</span> <span class="fu"><a href="https://rdrr.io/r/stats/cor.html">cov</a></span><span class="op">(</span><span class="va">x</span>, <span class="va">y</span><span class="op">)</span> <span class="op">*</span> <span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/length.html">length</a></span><span class="op">(</span><span class="va">x</span><span class="op">)</span> <span class="op">-</span> <span class="fl">1</span><span class="op">)</span> <span class="op">/</span> <span class="fu"><a href="https://rdrr.io/r/base/length.html">length</a></span><span class="op">(</span><span class="va">x</span><span class="op">)</span></span>
<span><span class="va">result</span></span>
<span><span class="co">#&gt; [1] 35.2</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Varianza della media di variabili indipendenti.</strong> La media aritmetica <span class="math inline">\(\textstyle {\bar  {X}}={\frac  {X_{1}+\ldots +X_{n}}{n}}\)</span> di <span class="math inline">\(n\)</span> variabili casuali indipendenti aventi la medesima distribuzione, ha varianza</p>
<p><span class="math display">\[
\mathbb{V}(\bar{X}) = \frac{1}{n^2} \mathbb{V}(X_1)+ \dots \mathbb{V}(X_n) = \frac{1}{n^2} n \mathbb{V}(X) = \frac{1}{n} \mathbb{V}(X).
\]</span></p>
<div class="callout callout-style-simple callout-note no-icon callout-titled" title="Esercizio">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-13-contents" aria-controls="callout-13" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Esercizio
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-13" class="callout-13-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Il principio precedente è illustrato dalla seguente simulazione.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb16"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Creare la popolazione</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">123</span><span class="op">)</span>  <span class="co"># Per riproducibilità</span></span>
<span><span class="va">population</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span><span class="fl">10000</span>, mean <span class="op">=</span> <span class="fl">50</span>, sd <span class="op">=</span> <span class="fl">10</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Definire dimensione del campione e numero di campioni</span></span>
<span><span class="va">sample_size</span> <span class="op">&lt;-</span> <span class="fl">30</span></span>
<span><span class="va">num_samples</span> <span class="op">&lt;-</span> <span class="fl">100000</span></span>
<span></span>
<span><span class="co"># Creare un vettore per memorizzare le medie campionarie</span></span>
<span><span class="va">sample_means</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/numeric.html">numeric</a></span><span class="op">(</span><span class="va">num_samples</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Generare i campioni e calcolare le medie</span></span>
<span><span class="kw">for</span> <span class="op">(</span><span class="va">i</span> <span class="kw">in</span> <span class="fl">1</span><span class="op">:</span><span class="va">num_samples</span><span class="op">)</span> <span class="op">{</span></span>
<span>  <span class="va">sample</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/sample.html">sample</a></span><span class="op">(</span><span class="va">population</span>, size <span class="op">=</span> <span class="va">sample_size</span>, replace <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span>
<span>  <span class="va">sample_means</span><span class="op">[</span><span class="va">i</span><span class="op">]</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">sample</span><span class="op">)</span></span>
<span><span class="op">}</span></span>
<span></span>
<span><span class="co"># Calcolare la varianza delle medie campionarie</span></span>
<span><span class="va">sampling_dist_mean_var</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/cor.html">var</a></span><span class="op">(</span><span class="va">sample_means</span><span class="op">)</span> <span class="op">*</span> <span class="op">(</span><span class="op">(</span><span class="va">num_samples</span> <span class="op">-</span> <span class="fl">1</span><span class="op">)</span> <span class="op">/</span> <span class="va">num_samples</span><span class="op">)</span>  <span class="co"># ddof = 0</span></span>
<span><span class="va">sampling_dist_mean_var</span></span>
<span><span class="co">#&gt; [1] 3.33</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Il valore teorico della varianza della distribuzione campionaria della media è</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb17"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fl">10</span><span class="op">^</span><span class="fl">2</span> <span class="op">/</span> <span class="fl">30</span></span>
<span><span class="co">#&gt; [1] 3.33</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</div>
</section><section id="varianza-di-una-variabile-casuale-continua" class="level3" data-number="9.3.3"><h3 data-number="9.3.3" class="anchored" data-anchor-id="varianza-di-una-variabile-casuale-continua">
<span class="header-section-number">9.3.3</span> Varianza di una variabile casuale continua</h3>
<p>Per una variabile casuale continua <span class="math inline">\(X\)</span>, la varianza è definita come:</p>
<p><span id="eq-def-var-rv-cont"><span class="math display">\[
\mathbb{V}(X) = \int_{-\infty}^{+\infty} \large[x - \mathbb{E}(X)\large]^2 p(x) \,\operatorname {d}\!x.
\tag{9.7}\]</span></span></p>
<p>Analogamente al caso discreto, la varianza di una variabile casuale continua <span class="math inline">\(X\)</span> una misura della dispersione, ovvero la “distanza” media quadratica attesa dei valori <span class="math inline">\(x\)</span> rispetto alla loro media <span class="math inline">\(\mathbb{E}(X)\)</span>. In altre parole, la varianza quantifica quanto i valori della variabile casuale si discostano tipicamente dal loro valore medio.</p>
</section><section id="deviazione-standard" class="level3" data-number="9.3.4"><h3 data-number="9.3.4" class="anchored" data-anchor-id="deviazione-standard">
<span class="header-section-number">9.3.4</span> Deviazione standard</h3>
<p>Quando si lavora con le varianze, i valori sono elevati al quadrato, il che può rendere i numeri significativamente più grandi (o più piccoli) rispetto ai dati originali. Per riportare questi valori all’unità di misura della scala originale, si prende la radice quadrata della varianza. Il risultato ottenuto è chiamato <em>deviazione standard</em> ed è comunemente indicato con la lettera greca <span class="math inline">\(\sigma\)</span>.</p>
<div id="def-" class="theorem definition">
<p><span class="theorem-title"><strong>Definizione 9.3</strong></span> La deviazione standard, o scarto quadratico medio, è definita come la radice quadrata della varianza:</p>
<p><span id="eq-standard-deviation-def"><span class="math display">\[
\sigma_X = \sqrt{\mathbb{V}(X)}.
\tag{9.8}\]</span></span></p>
</div>
<p>Come nella statistica descrittiva, la deviazione standard di una variabile casuale fornisce una misura della dispersione, ossia la “distanza” tipica o prevista dei valori <span class="math inline">\(x\)</span> rispetto alla loro media.</p>
<div class="callout callout-style-simple callout-note no-icon callout-titled" title="Esercizio">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-14-contents" aria-controls="callout-14" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Esercizio
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-14" class="callout-14-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Per i dadi equilibrati dell’esempio precedente, la deviazione standard della variabile casuale <span class="math inline">\(S\)</span> è pari a <span class="math inline">\(\sqrt{5.833} = 2.415\)</span>. Questo valore indica quanto i risultati della somma dei due dadi tendono a variare attorno alla loro media.</p>
</div>
</div>
</div>
</section></section><section id="standardizzazione" class="level2" data-number="9.4"><h2 data-number="9.4" class="anchored" data-anchor-id="standardizzazione">
<span class="header-section-number">9.4</span> Standardizzazione</h2>
<div id="def-" class="theorem definition">
<p><span class="theorem-title"><strong>Definizione 9.4</strong></span> Data una variabile casuale <span class="math inline">\(X\)</span>, si dice <em>variabile standardizzata</em> di <span class="math inline">\(X\)</span> l’espressione</p>
<p><span id="eq-standardization"><span class="math display">\[
Z = \frac{X - \mathbb{E}(X)}{\sigma_X}.
\tag{9.9}\]</span></span></p>
</div>
<p>Solitamente, una variabile standardizzata viene denotata con la lettera <span class="math inline">\(Z\)</span>.</p>
</section><section id="il-teorema-di-chebyshev" class="level2" data-number="9.5"><h2 data-number="9.5" class="anchored" data-anchor-id="il-teorema-di-chebyshev">
<span class="header-section-number">9.5</span> Il teorema di Chebyshev</h2>
<p>Il <em>Teorema di Chebyshev</em> ci permette di stimare la probabilità che una variabile aleatoria si discosti dal suo valore atteso (media) di una certa quantità. In altre parole, ci fornisce un limite superiore alla probabilità che una variabile aleatoria assuma valori “estremi”.</p>
<p>Il teorema di Chebyshev afferma che, per qualsiasi variabile aleatoria X con media E(X) e varianza Var(X), e per qualsiasi numero reale k &gt; 0, si ha:</p>
<p><span id="eq-chebyshev-def"><span class="math display">\[
P(\mid X - E(X)\mid \geq k \sigma) \leq 1/k^2,
\tag{9.10}\]</span></span></p>
<p>dove:</p>
<ul>
<li>
<span class="math inline">\(P(\mid X - E(X)\mid \geq k \sigma)\)</span> è la probabilità che lo scarto assoluto tra X e la sua media sia maggiore o uguale a k volte la deviazione standard (σ).</li>
<li>σ è la radice quadrata della varianza, ovvero la deviazione standard.</li>
</ul>
<p>Cosa ci dice questo teorema?</p>
<ul>
<li>
<strong>Limite superiore:</strong> Il teorema ci fornisce un limite superiore alla probabilità che una variabile aleatoria si discosti dalla sua media di più di k deviazioni standard.</li>
<li>
<strong>Qualsiasi distribuzione:</strong> La bellezza di questo teorema è che vale per qualsiasi distribuzione di probabilità, a patto che la media e la varianza esistano.</li>
<li>
<strong>Utilizzo:</strong> Il teorema di Chebyshev è molto utile quando non conosciamo la distribuzione esatta di una variabile aleatoria, ma conosciamo la sua media e la sua varianza.</li>
</ul>
<p>In sintesi, il teorema di Chebyshev ci fornisce un limite superiore alla probabilità che una variabile aleatoria si discosti dalla sua media di una certa quantità, in base alla sua varianza. Il teorema di Chebyshev ci permette quindi di fare inferenze sulla distribuzione di una variabile aleatoria anche quando abbiamo informazioni limitate.</p>
<div class="callout callout-style-simple callout-note no-icon callout-titled" title="Esercizio">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-15-contents" aria-controls="callout-15" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Esercizio
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-15" class="callout-15-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Supponiamo di avere una variabile aleatoria <span class="math inline">\(X\)</span> con media 100 e varianza 25. Vogliamo stimare la probabilità che <span class="math inline">\(X\)</span> assuma valori al di fuori dell’intervallo [90, 110].</p>
<p>In questo caso, <span class="math inline">\(k\)</span> = 2 (poiché 10 è uguale a 2 volte la deviazione standard, che è 5). Applicando il teorema di Chebyshev, otteniamo:</p>
<p><span class="math display">\[
P(\mid X - 100 \mid \geq 10) \leq \left( \frac{1}{2} \right)^2 = 0.25
\]</span></p>
<p>Quindi, possiamo affermare con certezza che al massimo il 25% dei valori di X saranno al di fuori dell’intervallo [90, 110].</p>
</div>
</div>
</div>
</section><section id="momenti-di-variabili-casuali" class="level2" data-number="9.6"><h2 data-number="9.6" class="anchored" data-anchor-id="momenti-di-variabili-casuali">
<span class="header-section-number">9.6</span> Momenti di variabili casuali</h2>
<div id="def-" class="theorem definition">
<p><span class="theorem-title"><strong>Definizione 9.5</strong></span> Si chiama <em>momento</em> di ordine <span class="math inline">\(q\)</span> di una v.c. <span class="math inline">\(X\)</span>, dotata di densità <span class="math inline">\(p(x)\)</span>, la quantità</p>
<p><span id="eq-moments-cont"><span class="math display">\[
\mathbb{E}(X^q) = \int_{-\infty}^{+\infty} x^q p(x) \; dx.
\tag{9.11}\]</span></span></p>
<p>Se <span class="math inline">\(X\)</span> è una v.c. discreta, i suoi momenti valgono:</p>
<p><span id="eq-moments-discr"><span class="math display">\[
\mathbb{E}(X^q) = \sum_i x_i^q P(x_i),
\tag{9.12}\]</span></span></p>
<p>dove:</p>
<ul>
<li>
<span class="math inline">\(E(X^q)\)</span> rappresenta il valore atteso di <span class="math inline">\(X\)</span> elevato alla <span class="math inline">\(q\)</span>-esima potenza.</li>
<li>
<span class="math inline">\(x_i\)</span> sono i possibili valori della variabile discreta.</li>
<li>
<span class="math inline">\(P(x_i)\)</span> è la probabilità associata a ciascun valore discreto.</li>
</ul>
</div>
<p>I momenti sono parametri statistici che forniscono informazioni importanti sulle caratteristiche di una variabile casuale. Tra questi, i più noti e utilizzati sono:</p>
<ol type="1">
<li>Il momento del primo ordine (<span class="math inline">\(q\)</span> = 1): corrisponde al valore atteso (o media) della variabile casuale <span class="math inline">\(X\)</span>.</li>
<li>Il momento del secondo ordine (<span class="math inline">\(q\)</span> = 2): quando calcolato rispetto alla media, corrisponde alla varianza.</li>
</ol>
<p>Per i momenti di ordine superiore al primo, è comune calcolarli rispetto al valore medio di <span class="math inline">\(X\)</span>. Questo si ottiene applicando una traslazione: <span class="math inline">\(x_0 = x − \mathbb{E}(X)\)</span>, dove <span class="math inline">\(x_0\)</span> rappresenta lo scarto dalla media. In particolare, il momento centrale del secondo ordine, calcolato con questa traslazione, corrisponde alla definizione di varianza.</p>
<div class="callout callout-style-simple callout-note no-icon callout-titled" title="Esercizio">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-16-contents" aria-controls="callout-16" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Esercizio
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-16" class="callout-16-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>In R, possiamo calcolare il valore atteso e la varianza di variabili casuali discrete utilizzando vettori di valori e probabilità.</p>
<p>Consideriamo una variabile casuale <span class="math inline">\(X\)</span> che rappresenta i valori ottenuti dal lancio di un dado non equilibrato, con valori possibili da 0 a 6, e con la seguente distribuzione di massa di probabilità: 0.1, 0.2, 0.3, 0.1, 0.1, 0.0, 0.2.</p>
<p>Iniziamo a definire un vettore che contiene i valori della v.c.:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb18"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">x</span> <span class="op">&lt;-</span> <span class="fl">0</span><span class="op">:</span><span class="fl">6</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="va">x</span><span class="op">)</span></span>
<span><span class="co">#&gt; [1] 0 1 2 3 4 5 6</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Il vettore <code>px</code> conterrà le probabilità associate ai valori <code>x</code>:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb19"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">px</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0.1</span>, <span class="fl">0.2</span>, <span class="fl">0.3</span>, <span class="fl">0.1</span>, <span class="fl">0.1</span>, <span class="fl">0.0</span>, <span class="fl">0.2</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="va">px</span><span class="op">)</span></span>
<span><span class="co">#&gt; [1] 0.1 0.2 0.3 0.1 0.1 0.0 0.2</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Controlliamo che la somma sia 1:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb20"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">px</span><span class="op">)</span></span>
<span><span class="co">#&gt; [1] 1</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Calcoliamo il valore atteso di <span class="math inline">\(X\)</span> implementando la formula del valore atteso utilizzando i vettori <code>x</code> e <code>px</code>:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb21"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">x_ev</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">x</span> <span class="op">*</span> <span class="va">px</span><span class="op">)</span></span>
<span><span class="va">x_ev</span></span>
<span><span class="co">#&gt; [1] 2.7</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Calcoliamo la varianza di <span class="math inline">\(X\)</span> usando i vettori <code>x</code> e <code>px</code>:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb22"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">x_var</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="op">(</span><span class="va">x</span> <span class="op">-</span> <span class="va">x_ev</span><span class="op">)</span><span class="op">^</span><span class="fl">2</span> <span class="op">*</span> <span class="va">px</span><span class="op">)</span></span>
<span><span class="va">x_var</span></span>
<span><span class="co">#&gt; [1] 3.81</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Calcoliamo la deviazione standard di <span class="math inline">\(X\)</span> prendendo la radice quadrata della varianza:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb23"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">x_sd</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">sqrt</a></span><span class="op">(</span><span class="va">x_var</span><span class="op">)</span></span>
<span><span class="va">x_sd</span></span>
<span><span class="co">#&gt; [1] 1.95</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Per rappresentare graficamente la distribuzione di massa, possiamo usare <code>ggplot2</code>:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb24"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">df</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">x</span>, pmf <span class="op">=</span> <span class="va">px</span><span class="op">)</span></span>
<span><span class="fu">ggplot</span><span class="op">(</span><span class="va">df</span>, <span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">x</span>, y <span class="op">=</span> <span class="va">pmf</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_point</span><span class="op">(</span>color <span class="op">=</span> <span class="st">"#832F2B"</span>, size <span class="op">=</span> <span class="fl">3</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_segment</span><span class="op">(</span><span class="fu">aes</span><span class="op">(</span>xend <span class="op">=</span> <span class="va">x</span>, yend <span class="op">=</span> <span class="fl">0</span><span class="op">)</span>, linewidth <span class="op">=</span> <span class="fl">1</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">labs</span><span class="op">(</span>title <span class="op">=</span> <span class="st">"Distribuzione di massa di probabilità"</span>, </span>
<span>       x <span class="op">=</span> <span class="st">"Valori"</span>, y <span class="op">=</span> <span class="st">"Probabilità"</span><span class="op">)</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="08_expval_var_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:85.0%"></p>
</figure>
</div>
</div>
</div>
<p>Questo codice calcola il valore atteso, la varianza e la deviazione standard di una variabile casuale discreta e rappresenta graficamente la distribuzione di massa, tutto in R.</p>
</div>
</div>
</div>
<div class="callout callout-style-simple callout-note no-icon callout-titled" title="Esercizio">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-17-contents" aria-controls="callout-17" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Esercizio
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-17" class="callout-17-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Un esempio pratico dell’uso del <strong>valore atteso</strong> e della <strong>varianza</strong> in psicologia è rappresentato dagli studi sulla memoria episodica, in particolare attraverso il paradigma sperimentale delle risposte “Remember-Know”. Questo paradigma permette di esplorare come le persone riconoscano eventi passati, distinguendo tra ricordi dettagliati e semplici sensazioni di familiarità.</p>
<p><strong>Il Paradigma “Remember-Know”</strong></p>
<p>In un tipico esperimento di memoria episodica:</p>
<ol type="1">
<li>Ai partecipanti viene presentata una lista di stimoli (es. parole o immagini).</li>
<li>Dopo un intervallo di tempo, viene mostrata una nuova lista contenente elementi precedentemente visti (<em>old</em>) e elementi nuovi (<em>new</em>).<br>
</li>
<li>Per ogni stimolo <em>old</em> riconosciuto, i soggetti devono specificare se:
<ul>
<li>
<strong>Remember (R)</strong>: Ricordano consapevolmente dettagli contestuali dell’episodio di encoding (es. “Ricordo che questa parola era scritta in rosso”).</li>
<li>
<strong>Know (K)</strong>: Avvertono familiarità con lo stimolo, ma senza accesso a dettagli specifici (es. “Sembra conosciuto, ma non so perché”).<br>
</li>
<li>
<strong>Miss</strong>: Non riconoscono lo stimolo.</li>
</ul>
</li>
</ol>
<p>La variabile in gioco è quindi <strong>categorica e discreta</strong>, con tre possibili esiti per gli stimoli <em>old</em>: {R, K, Miss}.</p>
<p><strong>Modelli Teorici e Previsioni Statistiche</strong></p>
<p>Due importanti teorie cercano di spiegare come avviene questo riconoscimento:</p>
<p><strong>Teoria del Processo Unico (Strength Theory)</strong> <span class="citation" data-cites="wixted2010continuous">(e.g., <a href="#ref-wixted2010continuous" role="doc-biblioref">Wixted &amp; Mickes, 2010</a>)</span></p>
<ul>
<li>
<strong>Ipotesi centrale</strong>:<br>
C’è una sola dimensione continua (la “forza mnemonica”) che determina il tipo di risposta.
<ul>
<li>Le risposte Remember derivano da tracce molto forti, quelle Know da tracce di forza intermedia, e i Miss da tracce troppo deboli.</li>
</ul>
</li>
<li>
<strong>Implicazioni statistiche</strong>: molte risposte Know, meno risposte Remember, bassa varianza.</li>
</ul>
<p><strong>Teoria del Doppio Processo (Dual-Process)</strong> <span class="citation" data-cites="yonelinas2002nature">(e.g., <a href="#ref-yonelinas2002nature" role="doc-biblioref">Yonelinas, 2002</a>)</span></p>
<ul>
<li>
<strong>Ipotesi centrale</strong>:<br>
Ci sono due processi indipendenti:
<ol type="1">
<li>
<strong>Recollection (R)</strong>: Processo <em>qualitativo e binario</em> (presente/assente), legato al ricordo consapevole di dettagli contestuali.<br>
</li>
<li>
<strong>Familiarità (K)</strong>: Processo <em>continuo</em>, basato su una sensazione generica di familiarità.</li>
</ol>
</li>
<li>
<strong>Implicazioni statistiche</strong>: numero simile di risposte Remember e Know, alta varianza.</li>
</ul>
<p>Qui entrano in gioco i concetti statistici: ogni teoria formula previsioni diverse sul <strong>valore atteso</strong> (es. proporzione attesa di risposte R o K) e sulla <strong>varianza</strong> (dispersione dei dati attorno a questi valori). Confrontando le osservazioni sperimentali con le aspettative teoriche, è possibile testare quale modello sia più coerente con i dati empirici, illustrando come strumenti probabilistici possano chiarire meccanismi cognitivi complessi.</p>
<p><strong>Confronto Statistico: Previsioni Teoriche</strong></p>
<p>Per confrontare quantitativamente le previsioni dei due modelli, consideriamo un esperimento ipotetico con 100 stimoli <em>old</em>. Assegniamo punteggi numerici alle categorie di risposta per trasformarle in una variabile discreta, facilitando il calcolo di valore atteso e varianza:</p>
<ul>
<li>
<strong>Remember (R) = 2</strong><br>
</li>
<li>
<strong>Know (K) = 1</strong><br>
</li>
<li><strong>Miss = 0</strong></li>
</ul>
<p>Questa codifica riflette l’intensità mnemonica associata a ciascuna risposta, permettendo di quantificare le differenze teoriche tra i modelli.</p>
<p><strong>1. Modello Single-Process (Forza continua)</strong></p>
<p>Secondo questa teoria, la distribuzione attesa delle risposte è:</p>
<table class="caption-top table">
<thead><tr class="header">
<th>Categoria</th>
<th>R</th>
<th>K</th>
<th>Miss</th>
</tr></thead>
<tbody><tr class="odd">
<td>% Prevista</td>
<td>25%</td>
<td>60%</td>
<td>15%</td>
</tr></tbody>
</table>
<p><strong>Calcoli statistici</strong>:<br>
- <strong>Valore atteso</strong> (media ponderata):<br><span class="math display">\[
  E(X) = (2 \cdot 0.25) + (1 \cdot 0.60) + (0 \cdot 0.15) = 1.10
  \]</span><br>
- <strong>Varianza</strong> (dispersione attorno alla media):<br><span class="math display">\[
  \begin{aligned}
  Var(X) &amp;= (2-1.10)^2 \cdot 0.25 + (1-1.10)^2 \cdot 0.60 + (0-1.10)^2 \cdot 0.15 \\
  &amp;= 0.2025 + 0.006 + 0.1815 = 0.39
  \end{aligned}
  \]</span></p>
<p><strong>2. Modello Dual-Process (Recollection e Familiarità)</strong></p>
<p>La teoria prevede una distribuzione basata su due meccanismi indipendenti:</p>
<table class="caption-top table">
<thead><tr class="header">
<th>Categoria</th>
<th>R</th>
<th>K</th>
<th>Miss</th>
</tr></thead>
<tbody><tr class="odd">
<td>% Prevista</td>
<td>40%</td>
<td>40%</td>
<td>20%</td>
</tr></tbody>
</table>
<p><strong>Calcoli statistici</strong>:<br>
- <strong>Valore atteso</strong>:<br><span class="math display">\[
  E(X) = (2 \cdot 0.40) + (1 \cdot 0.40) + (0 \cdot 0.20) = 1.20
  \]</span><br>
- <strong>Varianza</strong>:<br><span class="math display">\[
  \begin{aligned}
  Var(X) &amp;= (2-1.20)^2 \cdot 0.40 + (1-1.20)^2 \cdot 0.40 + (0-1.20)^2 \cdot 0.20 \\
  &amp;= 0.256 + 0.016 + 0.288 = 0.56
  \end{aligned}
  \]</span></p>
<p><strong>Sintesi del Confronto</strong></p>
<p>I due modelli generano previsioni distinte, riassunte nella tabella seguente:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 22%">
<col style="width: 18%">
<col style="width: 12%">
<col style="width: 46%">
</colgroup>
<thead><tr class="header">
<th>Modello</th>
<th>Valore Atteso</th>
<th>Varianza</th>
<th>Interpretazione</th>
</tr></thead>
<tbody>
<tr class="odd">
<td><strong>Single-Process</strong></td>
<td>1.10</td>
<td>0.39</td>
<td>Media più bassa, varianza ridotta (distribuzione concentrata attorno a K).</td>
</tr>
<tr class="even">
<td><strong>Dual-Process</strong></td>
<td>1.20</td>
<td>0.56</td>
<td>Media più alta, varianza elevata (effetto della miscela tra due processi).</td>
</tr>
</tbody>
</table>
<ul>
<li>
<strong>Valore atteso</strong>: Il modello dual-process predice una media superiore, coerente con la maggiore proporzione attesa di risposte <em>Remember</em>.<br>
</li>
<li>
<strong>Varianza</strong>: La differenza nella dispersione (0.39 vs.&nbsp;0.56) riflette l’eterogeneità introdotta dalla separazione tra <em>recollection</em> e <em>familiarità</em> nel modello duale.</li>
</ul>
<p><strong>Applicazione a Dati Empirici</strong></p>
<p>Supponiamo ora di aver raccolto dati reali da 100 soggetti che hanno prodotto questa distribuzione:</p>
<table class="caption-top table">
<thead><tr class="header">
<th>R</th>
<th>K</th>
<th>Miss</th>
</tr></thead>
<tbody><tr class="odd">
<td>38%</td>
<td>42%</td>
<td>20%</td>
</tr></tbody>
</table>
<p>Calcoliamo il valore atteso e la varianza empiriche:</p>
<p><span class="math display">\[
  E(X) = 2 \cdot 0.38 + 1 \cdot 0.42 + 0 \cdot 0.20 = 1.18
  \]</span></p>
<p><span class="math display">\[
  Var(X) = (2-1.18)^2 \cdot 0.38 + (1-1.18)^2 \cdot 0.42 + (0-1.18)^2 \cdot 0.20 = 0.55
  \]</span></p>
<p><strong>Risultati</strong>:</p>
<table class="caption-top table">
<thead><tr class="header">
<th>Dati</th>
<th>Valore Atteso</th>
<th>Varianza</th>
</tr></thead>
<tbody><tr class="odd">
<td>Empirici</td>
<td>1.18</td>
<td>0.55</td>
</tr></tbody>
</table>
<p>Confrontando questi risultati con le previsioni teoriche, notiamo che i dati empirici si avvicinano molto più al modello <strong>dual-process</strong> (valore atteso: 1.20 vs.&nbsp;1.18; varianza: 0.56 vs.&nbsp;0.55).</p>
<p><strong>Implicazioni Psicologiche e Cliniche</strong></p>
<ul>
<li><p><strong>Teoriche</strong>: Il confronto tra distribuzioni osservate e teoriche, usando valore atteso e varianza, consente di identificare quale teoria cognitiva spieghi meglio i dati.</p></li>
<li><p><strong>Cliniche</strong>: In contesti clinici (es. valutazione di deficit cognitivi), questo approccio consente di identificare se un paziente mostra un profilo riconducibile a un danno selettivo della <em>recollection</em> (R ↓) o della <em>familiarità</em> (K ↓).</p></li>
</ul>
<p>Questo framework illustra come strumenti probabilistici di base possano tradurre ipotesi psicologiche complesse in predizioni quantitative verificabili, avanzando la comprensione dei meccanismi cognitivi.</p>
</div>
</div>
</div>
</section><section id="riflessioni-conclusive" class="level2 unnumbered unlisted"><h2 class="unnumbered unlisted anchored" data-anchor-id="riflessioni-conclusive">Riflessioni conclusive</h2>
<p>In conclusione, i concetti di valore atteso e varianza sono fondamentali per comprendere il comportamento delle variabili casuali. Il valore atteso fornisce una misura centrale, rappresentando il “valore tipico” che ci si aspetta di osservare, mentre la varianza quantifica la dispersione dei valori attorno a questa media, offrendo una visione più completa della distribuzione. Questi strumenti sono essenziali per l’analisi e la modellizzazione statistica, fornendo le basi per valutare e interpretare la variabilità nei fenomeni aleatori.</p>
<div class="callout callout-style-simple callout-important no-icon callout-titled" title="Problemi 1">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-18-contents" aria-controls="callout-18" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Problemi 1
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-18" class="callout-18-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Esercizio 1: Calcolo del Valore Atteso per Variabili Discrete</strong></p>
<p>Utilizzando i dati raccolti dagli studenti sulla SWLS, calcola il valore atteso della soddisfazione con la vita (<span class="math inline">\(X\)</span>). Organizza i dati come nell’esempio seguente e interpretalo come se fosse la distribuzione di probabilità <strong>nella popolazione</strong>:</p>
<table class="caption-top table">
<thead><tr class="header">
<th>SWLS Score</th>
<th>Probabilità <span class="math inline">\(P(X)\)</span>
</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>5</td>
<td>0.05</td>
</tr>
<tr class="even">
<td>10</td>
<td>0.10</td>
</tr>
<tr class="odd">
<td>15</td>
<td>0.20</td>
</tr>
<tr class="even">
<td>20</td>
<td>0.30</td>
</tr>
<tr class="odd">
<td>25</td>
<td>0.20</td>
</tr>
<tr class="even">
<td>30</td>
<td>0.10</td>
</tr>
<tr class="odd">
<td>35</td>
<td>0.05</td>
</tr>
</tbody>
</table>
<ol type="1">
<li>Calcola il valore atteso di <span class="math inline">\(X\)</span>, <span class="math inline">\(\mathbb{E}(X)\)</span>.</li>
<li>Interpreta il risultato ottenuto.</li>
</ol>
<p><strong>Esercizio 2: Varianza e Deviazione Standard</strong></p>
<p>Data la stessa distribuzione della SWLS utilizzata nell’esercizio precedente:</p>
<ol type="1">
<li>Calcola la varianza <span class="math inline">\(\mathbb{V}(X)\)</span>.</li>
<li>Calcola la deviazione standard <span class="math inline">\(\sigma_X\)</span>.</li>
<li>Commenta il significato della dispersione dei valori rispetto alla media.</li>
</ol>
<p><strong>Esercizio 3: Proprietà del Valore Atteso</strong></p>
<p>Utilizzando la distribuzione della LSNS-6:</p>
<ol type="1">
<li>Definisci una nuova variabile casuale <span class="math inline">\(Y = 2X + 3\)</span>.</li>
<li>Calcola il valore atteso di <span class="math inline">\(Y\)</span>, <span class="math inline">\(\mathbb{E}(Y)\)</span>, utilizzando la linearità dell’operatore di aspettazione.</li>
<li>Verifica il risultato calcolando direttamente <span class="math inline">\(\mathbb{E}(Y)\)</span> dalla distribuzione di probabilità di <span class="math inline">\(Y\)</span>.</li>
</ol>
<p>Utilizza una distribuzione della LSNS-6 organizzata come segue (sostituisci i valori presenti con quelli del campione):</p>
<table class="caption-top table">
<thead><tr class="header">
<th>LSNS-6 Score</th>
<th>Probabilità <span class="math inline">\(P(Y)\)</span>
</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>5</td>
<td>0.10</td>
</tr>
<tr class="even">
<td>10</td>
<td>0.15</td>
</tr>
<tr class="odd">
<td>15</td>
<td>0.25</td>
</tr>
<tr class="even">
<td>20</td>
<td>0.25</td>
</tr>
<tr class="odd">
<td>25</td>
<td>0.15</td>
</tr>
<tr class="even">
<td>30</td>
<td>0.10</td>
</tr>
</tbody>
</table>
<p><strong>Esercizio 4: Applicazione del Teorema di Chebyshev</strong></p>
<p>Sia la soddisfazione con la vita (SWLS) distribuita con media <span class="math inline">\(\mu = 3.2\)</span> e deviazione standard <span class="math inline">\(\sigma = 0.8\)</span>.</p>
<ol type="1">
<li>Usa il teorema di Chebyshev per trovare un limite superiore alla probabilità che un valore di SWLS sia oltre due deviazioni standard dalla media.</li>
<li>Confronta questo risultato con la probabilità empirica calcolata utilizzando i dati raccolti.</li>
</ol>
<p><strong>Esercizio 5: Standardizzazione e Distribuzione Normale</strong></p>
<div class="sourceCode" id="cb25"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Definizione dei dati osservati della LSNS-6 (sostituisci con i dati reali se disponibili)</span></span>
<span><span class="va">lsns6_scores</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">5</span>, <span class="fl">8</span>, <span class="fl">10</span>, <span class="fl">12</span>, <span class="fl">15</span>, <span class="fl">18</span>, <span class="fl">20</span>, <span class="fl">22</span>, <span class="fl">25</span>, <span class="fl">28</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Parametri della distribuzione</span></span>
<span><span class="va">mu</span> <span class="op">&lt;-</span> <span class="fl">12</span>   <span class="co"># Media della LSNS-6</span></span>
<span><span class="va">sigma</span> <span class="op">&lt;-</span> <span class="fl">4</span>  <span class="co"># Deviazione standard della LSNS-6</span></span>
<span></span>
<span><span class="co"># Standardizzazione dei valori osservati</span></span>
<span><span class="va">z_scores</span> <span class="op">&lt;-</span> <span class="op">(</span><span class="va">lsns6_scores</span> <span class="op">-</span> <span class="va">mu</span><span class="op">)</span> <span class="op">/</span> <span class="va">sigma</span></span>
<span></span>
<span><span class="co"># Creazione dell'istogramma della distribuzione standardizzata</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/hist.html">hist</a></span><span class="op">(</span><span class="va">z_scores</span>, </span>
<span>     breaks <span class="op">=</span> <span class="fl">10</span>, </span>
<span>     col <span class="op">=</span> <span class="st">"lightblue"</span>, </span>
<span>     main <span class="op">=</span> <span class="st">"Istogramma della distribuzione standardizzata di LSNS-6"</span>, </span>
<span>     xlab <span class="op">=</span> <span class="st">"Z-score"</span>, </span>
<span>     ylab <span class="op">=</span> <span class="st">"Frequenza"</span>,</span>
<span>     probability <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Sovrapposizione della curva normale standard</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/curve.html">curve</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">dnorm</a></span><span class="op">(</span><span class="va">x</span>, mean <span class="op">=</span> <span class="fl">0</span>, sd <span class="op">=</span> <span class="fl">1</span><span class="op">)</span>, col <span class="op">=</span> <span class="st">"red"</span>, lwd <span class="op">=</span> <span class="fl">2</span>, add <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<ol type="1">
<li><p><strong>Standardizzazione</strong>: La trasformazione dei punteggi della LSNS-6 in Z-score permette di esprimere ogni valore in termini di deviazioni standard rispetto alla media. Un valore <span class="math inline">\(Z = 1\)</span> significa che il punteggio di LSNS-6 è una deviazione standard sopra la media, mentre <span class="math inline">\(Z = -1\)</span> significa che è una deviazione standard sotto la media.</p></li>
<li><p><strong>Istogramma della distribuzione standardizzata</strong>: Il grafico mostra la distribuzione dei punteggi standardizzati. Se la distribuzione originale è simile a una normale, l’istogramma dei punteggi standardizzati dovrebbe assomigliare a una distribuzione normale standard.</p></li>
<li><p><strong>Confronto con la distribuzione normale standard</strong>: La curva rossa rappresenta la densità di una normale standard (<span class="math inline">\(\mathcal{N}(0,1)\)</span>). Se i dati sono approssimativamente normali, l’istogramma dei punteggi standardizzati dovrebbe seguire la forma della curva normale standard. Differenze marcate potrebbero indicare asimmetria o curtosi anomale nella distribuzione dei punteggi LSNS-6.</p></li>
</ol>
</div>
</div>
</div>
<div class="callout callout-style-simple callout-tip no-icon callout-titled" title="Soluzioni 1">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-19-contents" aria-controls="callout-19" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Soluzioni 1
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-19" class="callout-19-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Esercizio 1: Calcolo del Valore Atteso della SWLS</strong></p>
<p>La <strong>Satisfaction With Life Scale (SWLS)</strong> è composta da 5 item, ciascuno valutato su una scala Likert da 1 a 7. Supponiamo di avere la seguente distribuzione di probabilità per il punteggio totale della SWLS basata su un campione di studenti:</p>
<table class="caption-top table">
<thead><tr class="header">
<th>SWLS Score</th>
<th>Probabilità <span class="math inline">\(P(X)\)</span>
</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>5</td>
<td>0.05</td>
</tr>
<tr class="even">
<td>10</td>
<td>0.10</td>
</tr>
<tr class="odd">
<td>15</td>
<td>0.20</td>
</tr>
<tr class="even">
<td>20</td>
<td>0.30</td>
</tr>
<tr class="odd">
<td>25</td>
<td>0.20</td>
</tr>
<tr class="even">
<td>30</td>
<td>0.10</td>
</tr>
<tr class="odd">
<td>35</td>
<td>0.05</td>
</tr>
</tbody>
</table>
<p><strong>Domanda:</strong><br>
Calcola il valore atteso <span class="math inline">\(\mathbb{E}[X]\)</span> del punteggio SWLS.</p>
<p><strong>Soluzione:</strong> Il valore atteso si calcola come:</p>
<p><span class="math display">\[
\mathbb{E}[X] = \sum x_i P(x_i)
\]</span></p>
<p>Calcoliamo in R:</p>
<div class="sourceCode" id="cb26"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Definizione dei valori SWLS e delle probabilità</span></span>
<span><span class="va">swls_scores</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">5</span>, <span class="fl">10</span>, <span class="fl">15</span>, <span class="fl">20</span>, <span class="fl">25</span>, <span class="fl">30</span>, <span class="fl">35</span><span class="op">)</span></span>
<span><span class="va">prob_swls</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0.05</span>, <span class="fl">0.10</span>, <span class="fl">0.20</span>, <span class="fl">0.30</span>, <span class="fl">0.20</span>, <span class="fl">0.10</span>, <span class="fl">0.05</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Calcolo del valore atteso</span></span>
<span><span class="va">expected_swls</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">swls_scores</span> <span class="op">*</span> <span class="va">prob_swls</span><span class="op">)</span></span>
<span><span class="va">expected_swls</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><strong>Risultato:</strong><br><span class="math display">\[
\mathbb{E}[X] = 20
\]</span></p>
<p>Il valore atteso rappresenta la media teorica della soddisfazione con la vita nella popolazione, assumendo che la distribuzione dei punteggi SWLS segua esattamente le probabilità fornite. In altre parole, se prendessimo un numero molto grande di individui con questa distribuzione di probabilità, il punteggio medio atteso sarebbe 20. Questo suggerisce che, nella popolazione considerata, il livello medio di soddisfazione con la vita si colloca al centro della scala SWLS.</p>
<p><strong>Esercizio 2: Calcolo della Varianza e Deviazione Standard della SWLS</strong></p>
<div class="sourceCode" id="cb27"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Definizione dei dati</span></span>
<span><span class="va">swls_scores</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">5</span>, <span class="fl">10</span>, <span class="fl">15</span>, <span class="fl">20</span>, <span class="fl">25</span>, <span class="fl">30</span>, <span class="fl">35</span><span class="op">)</span></span>
<span><span class="va">probabilities</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0.05</span>, <span class="fl">0.10</span>, <span class="fl">0.20</span>, <span class="fl">0.30</span>, <span class="fl">0.20</span>, <span class="fl">0.10</span>, <span class="fl">0.05</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Calcolo del valore atteso (media attesa)</span></span>
<span><span class="va">expected_value</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">swls_scores</span> <span class="op">*</span> <span class="va">probabilities</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Calcolo della varianza</span></span>
<span><span class="va">variance</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="op">(</span><span class="va">swls_scores</span> <span class="op">-</span> <span class="va">expected_value</span><span class="op">)</span><span class="op">^</span><span class="fl">2</span> <span class="op">*</span> <span class="va">probabilities</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Calcolo della deviazione standard</span></span>
<span><span class="va">std_deviation</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">sqrt</a></span><span class="op">(</span><span class="va">variance</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Stampa dei risultati</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/cat.html">cat</a></span><span class="op">(</span><span class="st">"Valore atteso (E[X]):"</span>, <span class="va">expected_value</span>, <span class="st">"\n"</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/cat.html">cat</a></span><span class="op">(</span><span class="st">"Varianza (Var[X]):"</span>, <span class="va">variance</span>, <span class="st">"\n"</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/cat.html">cat</a></span><span class="op">(</span><span class="st">"Deviazione standard (σ_X):"</span>, <span class="va">std_deviation</span>, <span class="st">"\n"</span><span class="op">)</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<ul>
<li>
<strong>Varianza</strong>: Misura la dispersione dei punteggi SWLS rispetto alla media attesa. Se la varianza è alta, significa che i punteggi sono molto variabili; se è bassa, significa che i punteggi sono più concentrati attorno al valore atteso.</li>
<li>
<strong>Deviazione standard</strong>: È la radice quadrata della varianza e ha la stessa unità di misura dei dati originali. Fornisce un’indicazione della dispersione media dei punteggi rispetto alla media.</li>
</ul>
<p>Se la deviazione standard è elevata, significa che nella popolazione ci sono sia individui con livelli di soddisfazione molto bassi sia individui con livelli molto alti. Se è bassa, i punteggi sono più omogenei intorno alla media.</p>
<p><strong>Esercizio 3: Calcolo del Valore Atteso della Scala della Rete Sociale di Lubben (LSNS-6)</strong></p>
<div class="sourceCode" id="cb28"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Definizione dei dati della LSNS-6</span></span>
<span><span class="va">lsns_scores</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">5</span>, <span class="fl">10</span>, <span class="fl">15</span>, <span class="fl">20</span>, <span class="fl">25</span>, <span class="fl">30</span><span class="op">)</span></span>
<span><span class="va">probabilities</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0.10</span>, <span class="fl">0.15</span>, <span class="fl">0.25</span>, <span class="fl">0.25</span>, <span class="fl">0.15</span>, <span class="fl">0.10</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Definizione della trasformazione della variabile casuale Y = 2X + 3</span></span>
<span><span class="va">y_values</span> <span class="op">&lt;-</span> <span class="fl">2</span> <span class="op">*</span> <span class="va">lsns_scores</span> <span class="op">+</span> <span class="fl">3</span></span>
<span></span>
<span><span class="co"># Calcolo del valore atteso di X</span></span>
<span><span class="va">expected_x</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">lsns_scores</span> <span class="op">*</span> <span class="va">probabilities</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Utilizzo della linearità dell'operatore di aspettazione: E[Y] = 2E[X] + 3</span></span>
<span><span class="va">expected_y_from_x</span> <span class="op">&lt;-</span> <span class="fl">2</span> <span class="op">*</span> <span class="va">expected_x</span> <span class="op">+</span> <span class="fl">3</span></span>
<span></span>
<span><span class="co"># Calcolo diretto del valore atteso di Y</span></span>
<span><span class="va">expected_y_direct</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">y_values</span> <span class="op">*</span> <span class="va">probabilities</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Stampa dei risultati</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/cat.html">cat</a></span><span class="op">(</span><span class="st">"Valore atteso di X (E[X]):"</span>, <span class="va">expected_x</span>, <span class="st">"\n"</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/cat.html">cat</a></span><span class="op">(</span><span class="st">"Valore atteso di Y calcolato con la linearità (E[Y] = 2E[X] + 3):"</span>, <span class="va">expected_y_from_x</span>, <span class="st">"\n"</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/cat.html">cat</a></span><span class="op">(</span><span class="st">"Valore atteso di Y calcolato direttamente dalla distribuzione di probabilità di Y:"</span>, <span class="va">expected_y_direct</span>, <span class="st">"\n"</span><span class="op">)</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<ol type="1">
<li>
<p><strong>Linearità dell’operatore di aspettazione</strong>: Questo principio afferma che se una variabile casuale <span class="math inline">\(X\)</span> viene trasformata linearmente in <span class="math inline">\(Y = aX + b\)</span>, allora il valore atteso di <span class="math inline">\(Y\)</span> è dato da:</p>
<p><span class="math display">\[
\mathbb{E}(Y) = a \mathbb{E}(X) + b
\]</span></p>
<p>Questo semplifica il calcolo senza dover ridefinire una nuova distribuzione di probabilità.</p>
</li>
<li><p><strong>Verifica del risultato</strong>: Dopo aver calcolato <span class="math inline">\(\mathbb{E}(Y)\)</span> con la proprietà di linearità, lo confrontiamo con il calcolo diretto utilizzando la distribuzione trasformata. Se i due valori coincidono, confermiamo che la proprietà di linearità è rispettata.</p></li>
<li><p><strong>Significato pratico</strong>: La trasformazione lineare di una variabile casuale può rappresentare un’operazione reale come la conversione di punteggi da una scala all’altra. Il valore atteso si comporta linearmente, il che è utile per interpretare trasformazioni senza dover ricalcolare completamente la distribuzione.</p></li>
</ol>
<p><strong>Esercizio 4: Probabilità secondo il Teorema di Chebyshev</strong></p>
<p>Il Teorema di Chebyshev afferma che per qualsiasi distribuzione, la probabilità che un valore sia oltre <span class="math inline">\(k\)</span> deviazioni standard dalla media è al massimo:</p>
<p><span class="math display">\[
P(|X - \mu| \geq k\sigma) \leq \frac{1}{k^2}
\]</span></p>
<p>Sostituendo <span class="math inline">\(k = 2\)</span>:</p>
<p><span class="math display">\[
P(|X - 3.2| \geq 2 \cdot 0.8) \leq \frac{1}{2^2} = \frac{1}{4} = 0.25
\]</span></p>
<p>Quindi, il Teorema di Chebyshev fornisce un limite superiore del 25% alla probabilità che un valore di SWLS sia oltre due deviazioni standard dalla media.</p>
<p>Per confrontare questo risultato con la probabilità empirica, è necessaro usare i dati raccolti sulla SWLS.</p>
<p><strong>Esercizio 5: Standardizzazione del Punteggio LSNS-6</strong></p>
<p><strong>Domanda:</strong><br>
Standardizza il punteggio <strong>LSNS-6</strong> trasformandolo nella variabile standardizzata <span class="math inline">\(Z\)</span>.</p>
<p><span class="math display">\[
Z = \frac{Y - \mathbb{E}(Y)}{\sigma_Y}
\]</span></p>
<p><strong>Soluzione:</strong> Calcoliamo in R:</p>
<div class="sourceCode" id="cb29"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Standardizzazione dei punteggi LSNS-6</span></span>
<span><span class="va">z_lsns</span> <span class="op">&lt;-</span> <span class="op">(</span><span class="va">lsns_scores</span> <span class="op">-</span> <span class="va">expected_lsns</span><span class="op">)</span> <span class="op">/</span> <span class="va">sd_lsns</span></span>
<span><span class="va">z_lsns</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><strong>Risultato:</strong></p>
<table class="caption-top table">
<thead><tr class="header">
<th>LSNS-6 Score</th>
<th>Z-Score</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>5</td>
<td>-2.23</td>
</tr>
<tr class="even">
<td>10</td>
<td>-1.34</td>
</tr>
<tr class="odd">
<td>15</td>
<td>-0.45</td>
</tr>
<tr class="even">
<td>20</td>
<td>0.45</td>
</tr>
<tr class="odd">
<td>25</td>
<td>1.34</td>
</tr>
<tr class="even">
<td>30</td>
<td>2.23</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<div class="callout callout-style-simple callout-important no-icon callout-titled" title="Problemi 2">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-20-contents" aria-controls="callout-20" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Problemi 2
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-20" class="callout-20-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Esercizio 6: Personalizzazione degli Interventi Basati sulla Probabilità Condizionata</strong></p>
<p>Uno psicologo scolastico vuole identificare quali studenti potrebbero trarre maggiore beneficio da un programma di supporto psicologico. Dalla letteratura, si sa che la probabilità di avere livelli bassi di soddisfazione con la vita (SWLS ≤ 15) è più alta tra gli studenti che riportano elevati livelli di stress accademico.</p>
<p>Dai dati raccolti su un campione di studenti:</p>
<ul>
<li><span class="math inline">\(P(\text{SWLS} \leq 15) = 0.35\)</span></li>
<li><span class="math inline">\(P(\text{Stress Alto}) = 0.40\)</span></li>
<li><span class="math inline">\(P(\text{SWLS} \leq 15 \mid \text{Stress Alto}) = 0.60\)</span></li>
</ul>
<p><strong>Domanda</strong> Se uno studente è scelto a caso, qual è la probabilità che abbia un alto livello di stress dato che il suo punteggio SWLS è ≤ 15?</p>
<p><strong>Esercizio 7: Prevedere il Successo di un Intervento Psicologico</strong> Uno psicologo clinico sta valutando l’efficacia di un intervento sulla riduzione dell’ansia. Ha raccolto i dati di 100 pazienti e ha osservato che il miglioramento medio nei punteggi di ansia (misurati con DASS-21) è di 5 punti con una deviazione standard di 2.5.</p>
<p>Supponiamo che il miglioramento sia una variabile aleatoria normale con media 5 e deviazione standard 2.5.</p>
<p><strong>Domanda</strong> Qual è la probabilità che un paziente scelto a caso migliori di almeno 7 punti?</p>
<p><strong>Esercizio 8: Allocazione Ottimale delle Risorse in un Programma di Prevenzione</strong> Uno psicologo organizza un programma di sensibilizzazione sulla salute mentale in diverse scuole. Ha raccolto dati sulla frequenza con cui gli studenti si rivolgono allo sportello di ascolto, con la seguente distribuzione:</p>
<table class="caption-top table">
<thead><tr class="header">
<th>Numero di Visite</th>
<th>Probabilità</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>0</td>
<td>0.40</td>
</tr>
<tr class="even">
<td>1</td>
<td>0.30</td>
</tr>
<tr class="odd">
<td>2</td>
<td>0.15</td>
</tr>
<tr class="even">
<td>3+</td>
<td>0.15</td>
</tr>
</tbody>
</table>
<p><strong>Domanda</strong> Se lo psicologo ha risorse per organizzare colloqui individuali solo per il 30% degli studenti, quale soglia può usare per selezionare gli studenti più bisognosi in base alla distribuzione delle visite?</p>
<p><strong>Esercizio 9: Misurare la Variabilità della Risposta a un Trattamento</strong> Uno psicologo somministra un trattamento per la depressione e misura la variazione nei punteggi di depressione su un campione di pazienti prima e dopo l’intervento.</p>
<p>Le variazioni seguono questa distribuzione:</p>
<table class="caption-top table">
<thead><tr class="header">
<th>Δ Punteggio DASS-21</th>
<th>Probabilità</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>-10</td>
<td>0.10</td>
</tr>
<tr class="even">
<td>-5</td>
<td>0.20</td>
</tr>
<tr class="odd">
<td>0</td>
<td>0.40</td>
</tr>
<tr class="even">
<td>+5</td>
<td>0.20</td>
</tr>
<tr class="odd">
<td>+10</td>
<td>0.10</td>
</tr>
</tbody>
</table>
<p><strong>Domanda</strong> Qual è la deviazione standard della variazione nei punteggi di depressione?</p>
<p><strong>Esercizio 10: Probabilità di un Fallimento in un Programma di Sensibilizzazione</strong> Uno psicologo organizza un programma per ridurre il pregiudizio sulla salute mentale. Dai dati precedenti, la probabilità di successo di ogni evento di sensibilizzazione è del 70%. Se organizza 5 eventi indipendenti, qual è la probabilità che almeno 1 fallisca?</p>
</div>
</div>
</div>
<div class="callout callout-style-simple callout-tip no-icon callout-titled" title="Soluzioni 2">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-21-contents" aria-controls="callout-21" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Soluzioni 2
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-21" class="callout-21-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Esercizio 6: Personalizzazione degli Interventi Basati sulla Probabilità Condizionata</strong></p>
<p>Utilizziamo la formula della probabilità condizionata:</p>
<p><span class="math display">\[
P(\text{Stress Alto} \mid \text{SWLS} \leq 15) = \frac{P(\text{SWLS} \leq 15 \mid \text{Stress Alto}) P(\text{Stress Alto})}{P(\text{SWLS} \leq 15)}
\]</span></p>
<p>Calcoliamo in R:</p>
<div class="sourceCode" id="cb30"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">p_swls_low</span> <span class="op">&lt;-</span> <span class="fl">0.35</span></span>
<span><span class="va">p_stress_high</span> <span class="op">&lt;-</span> <span class="fl">0.40</span></span>
<span><span class="va">p_swls_given_stress</span> <span class="op">&lt;-</span> <span class="fl">0.60</span></span>
<span></span>
<span><span class="va">p_stress_given_swls</span> <span class="op">&lt;-</span> <span class="op">(</span><span class="va">p_swls_given_stress</span> <span class="op">*</span> <span class="va">p_stress_high</span><span class="op">)</span> <span class="op">/</span> <span class="va">p_swls_low</span></span>
<span><span class="va">p_stress_given_swls</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><strong>Risultato</strong> Lo psicologo può usare questa informazione per identificare studenti con alta probabilità di avere stress elevato, anche se non hanno segnalato direttamente il problema, e offrire supporto mirato.</p>
<p><strong>Esercizio 7: Prevedere il Successo di un Intervento Psicologico</strong></p>
<p>Usiamo la normalizzazione:</p>
<p><span class="math display">\[
Z = \frac{X - \mu}{\sigma}
\]</span></p>
<p>e calcoliamo la probabilità corrispondente:</p>
<div class="sourceCode" id="cb31"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">mean_improvement</span> <span class="op">&lt;-</span> <span class="fl">5</span></span>
<span><span class="va">sd_improvement</span> <span class="op">&lt;-</span> <span class="fl">2.5</span></span>
<span><span class="va">threshold</span> <span class="op">&lt;-</span> <span class="fl">7</span></span>
<span></span>
<span><span class="va">p_improve_7</span> <span class="op">&lt;-</span> <span class="fl">1</span> <span class="op">-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">pnorm</a></span><span class="op">(</span><span class="va">threshold</span>, mean <span class="op">=</span> <span class="va">mean_improvement</span>, sd <span class="op">=</span> <span class="va">sd_improvement</span><span class="op">)</span></span>
<span><span class="va">p_improve_7</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><strong>Risultato</strong> Questo aiuta lo psicologo a comunicare ai pazienti la probabilità di ottenere miglioramenti significativi e ad adattare le aspettative dell’intervento.</p>
<p><strong>Esercizio 8: Allocazione Ottimale delle Risorse in un Programma di Prevenzione</strong></p>
<p><strong>Soluzione</strong> Calcoliamo la probabilità cumulativa:</p>
<div class="sourceCode" id="cb32"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">visits</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0</span>, <span class="fl">1</span>, <span class="fl">2</span>, <span class="fl">3</span><span class="op">)</span></span>
<span><span class="va">probabilities</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0.40</span>, <span class="fl">0.30</span>, <span class="fl">0.15</span>, <span class="fl">0.15</span><span class="op">)</span></span>
<span><span class="va">cumulative_prob</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/cumsum.html">cumsum</a></span><span class="op">(</span><span class="va">probabilities</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Determinare la soglia per il 30% più bisognoso</span></span>
<span><span class="va">threshold</span> <span class="op">&lt;-</span> <span class="va">visits</span><span class="op">[</span><span class="fu"><a href="https://rdrr.io/r/base/Extremes.html">min</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/which.html">which</a></span><span class="op">(</span><span class="va">cumulative_prob</span> <span class="op">&gt;=</span> <span class="fl">0.70</span><span class="op">)</span><span class="op">)</span><span class="op">]</span></span>
<span><span class="va">threshold</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><strong>Risultato</strong> Lo psicologo può decidere di offrire supporto prioritario a studenti con almeno 2 visite, massimizzando l’impatto con risorse limitate.</p>
<p><strong>Esercizio 9: Misurare la Variabilità della Risposta a un Trattamento</strong></p>
<p><strong>Soluzione</strong> Calcoliamo la varianza e la deviazione standard:</p>
<div class="sourceCode" id="cb33"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">score_changes</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="op">-</span><span class="fl">10</span>, <span class="op">-</span><span class="fl">5</span>, <span class="fl">0</span>, <span class="fl">5</span>, <span class="fl">10</span><span class="op">)</span></span>
<span><span class="va">probabilities</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0.10</span>, <span class="fl">0.20</span>, <span class="fl">0.40</span>, <span class="fl">0.20</span>, <span class="fl">0.10</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Media attesa</span></span>
<span><span class="va">expected_change</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">score_changes</span> <span class="op">*</span> <span class="va">probabilities</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Varianza</span></span>
<span><span class="va">variance_change</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="op">(</span><span class="va">score_changes</span> <span class="op">-</span> <span class="va">expected_change</span><span class="op">)</span><span class="op">^</span><span class="fl">2</span> <span class="op">*</span> <span class="va">probabilities</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Deviazione standard</span></span>
<span><span class="va">sd_change</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">sqrt</a></span><span class="op">(</span><span class="va">variance_change</span><span class="op">)</span></span>
<span><span class="va">sd_change</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><strong>Risultato</strong> Se la deviazione standard è grande, significa che l’effetto del trattamento è molto variabile e potrebbero essere necessarie strategie personalizzate.</p>
<p><strong>Esercizio 10: Probabilità di un Fallimento in un Programma di Sensibilizzazione</strong></p>
<p>Usiamo la distribuzione binomiale:</p>
<div class="sourceCode" id="cb34"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">p_success</span> <span class="op">&lt;-</span> <span class="fl">0.70</span></span>
<span><span class="va">n_events</span> <span class="op">&lt;-</span> <span class="fl">5</span></span>
<span></span>
<span><span class="va">p_failure_at_least_one</span> <span class="op">&lt;-</span> <span class="fl">1</span> <span class="op">-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Binomial.html">dbinom</a></span><span class="op">(</span><span class="fl">5</span>, <span class="va">n_events</span>, <span class="va">p_success</span><span class="op">)</span></span>
<span><span class="va">p_failure_at_least_one</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><strong>Risultato</strong> Lo psicologo può pianificare strategie di miglioramento sapendo la probabilità di un fallimento.</p>
</div>
</div>
</div>
<div class="callout callout-style-simple callout-important no-icon callout-titled" title="Problemi 3">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-22-contents" aria-controls="callout-22" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Problemi 3
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-22" class="callout-22-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Esercizio 3</strong></p>
<p>Consiglio gli esercizi di base disponibili nella seguente <a href="https://stats.libretexts.org/Bookshelves/Introductory_Statistics/Introductory_Statistics_(Shafer_and_Zhang)/04%3A_Discrete_Random_Variables/4.E%3A_Discrete_Random_Variables_(Exercises)">pagina web</a>.</p>
</div>
</div>
</div>
<div class="callout callout-style-simple callout-note no-icon callout-titled" title="Informazioni sull'ambiente di sviluppo">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-23-contents" aria-controls="callout-23" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Informazioni sull’ambiente di sviluppo
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-23" class="callout-23-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb35"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/utils/sessionInfo.html">sessionInfo</a></span><span class="op">(</span><span class="op">)</span></span>
<span><span class="co">#&gt; R version 4.5.1 (2025-06-13)</span></span>
<span><span class="co">#&gt; Platform: aarch64-apple-darwin20</span></span>
<span><span class="co">#&gt; Running under: macOS Sequoia 15.6.1</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Matrix products: default</span></span>
<span><span class="co">#&gt; BLAS:   /Library/Frameworks/R.framework/Versions/4.5-arm64/Resources/lib/libRblas.0.dylib </span></span>
<span><span class="co">#&gt; LAPACK: /Library/Frameworks/R.framework/Versions/4.5-arm64/Resources/lib/libRlapack.dylib;  LAPACK version 3.12.1</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; locale:</span></span>
<span><span class="co">#&gt; [1] C/UTF-8/C/C/C/C</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; time zone: Europe/Rome</span></span>
<span><span class="co">#&gt; tzcode source: internal</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; attached base packages:</span></span>
<span><span class="co">#&gt; [1] stats     graphics  grDevices utils     datasets  methods   base     </span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; other attached packages:</span></span>
<span><span class="co">#&gt;  [1] pillar_1.11.0         tinytable_0.13.0      patchwork_1.3.2      </span></span>
<span><span class="co">#&gt;  [4] ggdist_3.3.3          tidybayes_3.0.7       bayesplot_1.14.0     </span></span>
<span><span class="co">#&gt;  [7] ggplot2_3.5.2         reliabilitydiag_0.2.1 priorsense_1.1.1     </span></span>
<span><span class="co">#&gt; [10] posterior_1.6.1       loo_2.8.0             rstan_2.32.7         </span></span>
<span><span class="co">#&gt; [13] StanHeaders_2.32.10   brms_2.22.0           Rcpp_1.1.0           </span></span>
<span><span class="co">#&gt; [16] sessioninfo_1.2.3     conflicted_1.2.0      janitor_2.2.1        </span></span>
<span><span class="co">#&gt; [19] matrixStats_1.5.0     modelr_0.1.11         tibble_3.3.0         </span></span>
<span><span class="co">#&gt; [22] dplyr_1.1.4           tidyr_1.3.1           rio_1.2.3            </span></span>
<span><span class="co">#&gt; [25] here_1.0.1           </span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; loaded via a namespace (and not attached):</span></span>
<span><span class="co">#&gt;  [1] svUnit_1.0.8          tidyselect_1.2.1      farver_2.1.2         </span></span>
<span><span class="co">#&gt;  [4] fastmap_1.2.0         TH.data_1.1-4         tensorA_0.36.2.1     </span></span>
<span><span class="co">#&gt;  [7] digest_0.6.37         timechange_0.3.0      estimability_1.5.1   </span></span>
<span><span class="co">#&gt; [10] lifecycle_1.0.4       survival_3.8-3        magrittr_2.0.3       </span></span>
<span><span class="co">#&gt; [13] compiler_4.5.1        rlang_1.1.6           tools_4.5.1          </span></span>
<span><span class="co">#&gt; [16] knitr_1.50            labeling_0.4.3        bridgesampling_1.1-2 </span></span>
<span><span class="co">#&gt; [19] htmlwidgets_1.6.4     curl_7.0.0            pkgbuild_1.4.8       </span></span>
<span><span class="co">#&gt; [22] RColorBrewer_1.1-3    abind_1.4-8           multcomp_1.4-28      </span></span>
<span><span class="co">#&gt; [25] withr_3.0.2           purrr_1.1.0           grid_4.5.1           </span></span>
<span><span class="co">#&gt; [28] stats4_4.5.1          colorspace_2.1-1      xtable_1.8-4         </span></span>
<span><span class="co">#&gt; [31] inline_0.3.21         emmeans_1.11.2-8      scales_1.4.0         </span></span>
<span><span class="co">#&gt; [34] MASS_7.3-65           cli_3.6.5             mvtnorm_1.3-3        </span></span>
<span><span class="co">#&gt; [37] rmarkdown_2.29        ragg_1.5.0            generics_0.1.4       </span></span>
<span><span class="co">#&gt; [40] RcppParallel_5.1.11-1 cachem_1.1.0          stringr_1.5.1        </span></span>
<span><span class="co">#&gt; [43] splines_4.5.1         parallel_4.5.1        vctrs_0.6.5          </span></span>
<span><span class="co">#&gt; [46] V8_7.0.0              Matrix_1.7-4          sandwich_3.1-1       </span></span>
<span><span class="co">#&gt; [49] jsonlite_2.0.0        arrayhelpers_1.1-0    systemfonts_1.2.3    </span></span>
<span><span class="co">#&gt; [52] glue_1.8.0            codetools_0.2-20      distributional_0.5.0 </span></span>
<span><span class="co">#&gt; [55] lubridate_1.9.4       stringi_1.8.7         gtable_0.3.6         </span></span>
<span><span class="co">#&gt; [58] QuickJSR_1.8.0        htmltools_0.5.8.1     Brobdingnag_1.2-9    </span></span>
<span><span class="co">#&gt; [61] R6_2.6.1              textshaping_1.0.3     rprojroot_2.1.1      </span></span>
<span><span class="co">#&gt; [64] evaluate_1.0.5        lattice_0.22-7        backports_1.5.0      </span></span>
<span><span class="co">#&gt; [67] memoise_2.0.1         broom_1.0.9           snakecase_0.11.1     </span></span>
<span><span class="co">#&gt; [70] rstantools_2.5.0      coda_0.19-4.1         gridExtra_2.3        </span></span>
<span><span class="co">#&gt; [73] nlme_3.1-168          checkmate_2.3.3       xfun_0.53            </span></span>
<span><span class="co">#&gt; [76] zoo_1.8-14            pkgconfig_2.0.3</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</div>
</section><section id="bibliografia" class="level2 unnumbered unlisted"><h2 class="unnumbered unlisted anchored" data-anchor-id="bibliografia">Bibliografia</h2>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" data-line-spacing="2" role="list">
<div id="ref-kroese2025statistical" class="csl-entry" role="listitem">
Chan, J. C. C., &amp; Kroese, D. P. (2025). <em>Statistical Modeling and Computation</em> (2ª ed.). Springer.
</div>
<div id="ref-hacking2006emergence" class="csl-entry" role="listitem">
Hacking, I. (2006). <em>The emergence of probability: A philosophical study of early ideas about probability, induction and statistical inference</em>. Cambridge University Press.
</div>
<div id="ref-schervish2014probability" class="csl-entry" role="listitem">
Schervish, M. J., &amp; DeGroot, M. H. (2014). <em>Probability and statistics</em> (Vol. 563). Pearson Education London, UK:
</div>
<div id="ref-wixted2010continuous" class="csl-entry" role="listitem">
Wixted, J. T., &amp; Mickes, L. (2010). A continuous dual-process model of remember/know judgments. <em>Psychological Review</em>, <em>117</em>(4), 1025–1054.
</div>
<div id="ref-yonelinas2002nature" class="csl-entry" role="listitem">
Yonelinas, A. P. (2002). The nature of recollection and familiarity: A review of 30 years of research. <em>Journal of Memory and Language</em>, <em>46</em>(3), 441–517.
</div>
</div>
</section></main><!-- /main --><script>
document.body.classList.add('classic-book');
document.addEventListener('DOMContentLoaded', function() {
  const paragraphs = document.querySelectorAll('p');
  paragraphs.forEach(p => {
    if (p.textContent.length > 200) {
      p.style.hyphens = 'auto';
      p.style.hyphenateCharacter = '-';
    }
  });
  const headings = document.querySelectorAll('h1, h2, h3, h4, h5, h6');
  headings.forEach(h => {
    h.style.fontFeatureSettings = '"liga" 1, "dlig" 1, "smcp" 1';
  });
});
</script><script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiato!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiato!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/ccaudek\.github\.io\/utet-prob\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
            // default icon
            link.classList.add("external");
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="../../chapters/probability/07_prob_distributions.html" class="pagination-link" aria-label="Distribuzioni di massa e di densità">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Distribuzioni di massa e di densità</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../../chapters/probability/09_sampling_distr.html" class="pagination-link" aria-label="Stime, stimatori e parametri">
        <span class="nav-page-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Stime, stimatori e parametri</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
    <div class="nav-footer-left">
<p><strong>Probabilità per la psicologia</strong> — Modulo di richiamo del progetto UTET a supporto del manuale <em>Metodi bayesiani in psicologia</em>.</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/ccaudek/utet-prob/blob/main/chapters/probability/08_expval_var.qmd" class="toc-action"><i class="bi bi-github"></i>Mostra il codice</a></li><li><a href="https://github.com/ccaudek/utet-prob/issues/new" class="toc-action"><i class="bi empty"></i>Segnala un problema</a></li></ul></div></div>
    <div class="nav-footer-right">
<p>Realizzato con <a href="https://quarto.org/">Quarto</a>.</p>
</div>
  </div>
</footer>


<script src="../../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>