<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="it" xml:lang="it"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<meta name="description" content="Modulo di richiamo sulla probabilità per la psicologia, parte del progetto UTET a supporto del manuale Inferenza bayesiana in psicologia: Ragionare con l’incertezza.">
<title>11&nbsp; Distribuzioni di variabili casuali discrete – Probabilità per la psicologia</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>

<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../chapters/probability/12_cont_rv_distr.html" rel="next">
<link href="../../chapters/probability/10_intro_distributions.html" rel="prev">
<script src="../../site_libs/cookie-consent/cookie-consent.js"></script>
<link href="../../site_libs/cookie-consent/cookie-consent.css" rel="stylesheet">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-852af3d06ec72eeb83abe568abde0a2c.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark-ad70a6f0db1617724bec401cc1948888.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-852af3d06ec72eeb83abe568abde0a2c.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-118e8738f0f8160cafa1a1cf8d5a5e55.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/bootstrap/bootstrap-dark-77af5ebc2982ad6e9138913f7b62f5c8.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/bootstrap/bootstrap-118e8738f0f8160cafa1a1cf8d5a5e55.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script src="../../site_libs/quarto-contrib/glightbox/glightbox.min.js"></script>
<link href="../../site_libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="../../site_libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": true,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": true,
  "language": {
    "search-no-results-text": "Nessun risultato",
    "search-matching-documents-text": "documenti trovati",
    "search-copy-link-title": "Copiare il link nella ricerca",
    "search-hide-matches-text": "Nascondere i risultati aggiuntivi",
    "search-more-match-text": "ci sono altri risultati in questo documento",
    "search-more-matches-text": "ulteriori risultati in questo documento",
    "search-clear-button-title": "Pulire",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancellare",
    "search-submit-button-title": "Inviare",
    "search-label": "Ricerca"
  }
}</script><script async="" src="https://www.googletagmanager.com/gtag/js?id=G-QT5S3P9D31"></script><script type="text/plain" cookie-consent="tracking">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-QT5S3P9D31', { 'anonymize_ip': true});
</script><script type="text/javascript" charset="UTF-8">
document.addEventListener('DOMContentLoaded', function () {
cookieconsent.run({
  "notice_banner_type":"headline",
  "consent_type":"express",
  "palette":"light",
  "language":"en",
  "page_load_consent_levels":["strictly-necessary"],
  "notice_banner_reject_button_hide":false,
  "preferences_center_close_button_hide":false,
  "website_name":""
  ,
"language":"it"
  });
});
</script><style>html{ scroll-behavior: smooth; }</style>
<link href="../../site_libs/pagedtable-1.1/css/pagedtable.css" rel="stylesheet">
<script src="../../site_libs/pagedtable-1.1/js/pagedtable.js"></script><script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script><script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script><script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>
<meta property="og:title" content="11&nbsp; Distribuzioni di variabili casuali discrete – Probabilità per la psicologia">
<meta property="og:description" content="Modulo di richiamo sulla probabilità per la psicologia, parte del progetto UTET a supporto del manuale Inferenza bayesiana in psicologia: Ragionare con l’incertezza.">
<meta property="og:image" content="https://ccaudek.github.io/utet-prob/chapters/probability/11_discr_rv_distr_files/figure-html/fig-uniforme-discreta-1.png">
<meta property="og:site_name" content="Probabilità per la psicologia">
<meta property="og:image:height" content="1297">
<meta property="og:image:width" content="2100">
<meta name="twitter:title" content="11&nbsp; Distribuzioni di variabili casuali discrete – Probabilità per la psicologia">
<meta name="twitter:description" content="Modulo di richiamo sulla probabilità per la psicologia, parte del progetto UTET a supporto del manuale Inferenza bayesiana in psicologia: Ragionare con l’incertezza.">
<meta name="twitter:image" content="https://ccaudek.github.io/utet-prob/chapters/probability/11_discr_rv_distr_files/figure-html/fig-uniforme-discreta-1.png">
<meta name="twitter:image-height" content="1297">
<meta name="twitter:image-width" content="2100">
<meta name="twitter:card" content="summary_large_image">
<link rel="canonical" href="https://ccaudek.github.io/utet-prob/chapters/probability/11_discr_rv_distr.html">
</head>
<body class="nav-sidebar floating quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const queryPrefersDark = window.matchMedia('(prefers-color-scheme: dark)');
    const darkModeDefault = queryPrefersDark.matches;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    queryPrefersDark.addEventListener("change", e => {
      if(window.localStorage.getItem("quarto-color-scheme") !== null)
        return;
      const alternate = e.matches
      toggleColorMode(alternate);
      localAlternateSentinel = e.matches ? 'alternate' : 'default'; // this is used alongside local storage!
      toggleGiscusIfUsed(alternate, darkModeDefault);
    });
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Attiva/disattiva la barra laterale" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../chapters/probability/10_intro_distributions.html">PARTE 3: Distribuzioni specifiche</a></li><li class="breadcrumb-item"><a href="../../chapters/probability/11_discr_rv_distr.html"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Distribuzioni di variabili casuali discrete</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Attiva/disattiva la barra laterale" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Ricerca" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../../">Probabilità per la psicologia</a> 
        <div class="sidebar-tools-main tools-wide">
    <a href="https://ccaudek.github.io/utet-companion/" title="Manuale e companion" class="quarto-navigation-tool px-1" aria-label="Manuale e companion"><i class="bi bi-book"></i></a>
    <a href="https://github.com/ccaudek/utet-prob/" title="Eseguire il codice" class="quarto-navigation-tool px-1" aria-label="Eseguire il codice"><i class="bi bi-github"></i></a>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Attiva/disattiva la modalità oscura"><i class="bi"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Attiva/disattiva la modalità lettore">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
    <div id="quarto-search" class="quarto-navigation-tool px-1" title="Ricerca"></div>
</div>
    </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Come usare il modulo</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false">
 <span class="menu-text">PARTE 1: Fondamenti della probabilità</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/probability/01_intro_prob_bayesian.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Interpretazione bayesiana della probabilità</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/probability/02_axioms_coherence_bayesian.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Assiomi e coerenza delle credenze</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/probability/03_equiprobability_combinatorics_bayesian.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Equiprobabilità e calcolo combinatorio</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/probability/04_conditional_prob_bayesian.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Probabilità condizionata come aggiornamento</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/probability/05_bayes_theorem.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Il teorema di Bayes</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false">
 <span class="menu-text">PARTE 2: Variabili casuali e distribuzioni</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/probability/06_random_var.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Variabili casuali</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/probability/07_prob_distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Distribuzioni di massa e di densità</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/probability/08_expval_var.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Proprietà delle variabili casuali</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/probability/09_cov_cor.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Covarianza e correlazione</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">PARTE 3: Distribuzioni specifiche</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/probability/10_intro_distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Introduzione alle distribuzioni di probabilità</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/probability/11_discr_rv_distr.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Distribuzioni di variabili casuali discrete</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/probability/12_cont_rv_distr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Distribuzioni di variabili casuali continue</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false">
 <span class="menu-text">PARTE 4: Verso l’inferenza</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/probability/13_from_sample_to_evidence.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Dal campione all’evidenza: informazione, precisione e incertezza</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/probability/14_likelihood.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">La verosimiglianza</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/probability/15_aggiornamento_bayesiano.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Dalla verosimiglianza alla posterior: una prima idea dell’aggiornamento bayesiano</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/probability/16_conclusioni.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Conclusioni: dalla probabilità all’inferenza bayesiana</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false">
 <span class="menu-text">Appendici</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a01_math_symbols.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Simbologia di base</span></span></a>
  </div>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active" data-toc-expanded="2"><h2 id="toc-title">Sommario</h2>
   
  <ul class="collapse">
<li><a href="#perch%C3%A9-le-distribuzioni-discrete-sono-importanti-in-psicologia" id="toc-perché-le-distribuzioni-discrete-sono-importanti-in-psicologia" class="nav-link active" data-scroll-target="#perch%C3%A9-le-distribuzioni-discrete-sono-importanti-in-psicologia"><span class="header-section-number">11.1</span> Perché le distribuzioni discrete sono importanti in psicologia?</a></li>
  <li><a href="#sec-discrete-distribution-meaning" id="toc-sec-discrete-distribution-meaning" class="nav-link" data-scroll-target="#sec-discrete-distribution-meaning"><span class="header-section-number">11.2</span> Che cosa descrive una distribuzione discreta?</a></li>
  <li><a href="#sec-r-discrete-functions" id="toc-sec-r-discrete-functions" class="nav-link" data-scroll-target="#sec-r-discrete-functions"><span class="header-section-number">11.3</span> Le funzioni R per le distribuzioni</a></li>
  <li><a href="#sec-discrete-uniform" id="toc-sec-discrete-uniform" class="nav-link" data-scroll-target="#sec-discrete-uniform"><span class="header-section-number">11.4</span> Distribuzione uniforme discreta</a></li>
  <li><a href="#sec-bernoulli-distribution" id="toc-sec-bernoulli-distribution" class="nav-link" data-scroll-target="#sec-bernoulli-distribution"><span class="header-section-number">11.5</span> Distribuzione di Bernoulli</a></li>
  <li><a href="#sec-binomial-distribution" id="toc-sec-binomial-distribution" class="nav-link" data-scroll-target="#sec-binomial-distribution"><span class="header-section-number">11.6</span> Distribuzione binomiale</a></li>
  <li><a href="#sec-beta-binomial-distribution" id="toc-sec-beta-binomial-distribution" class="nav-link" data-scroll-target="#sec-beta-binomial-distribution"><span class="header-section-number">11.7</span> Distribuzione beta-binomiale</a></li>
  <li><a href="#sec-poisson-distribution" id="toc-sec-poisson-distribution" class="nav-link" data-scroll-target="#sec-poisson-distribution"><span class="header-section-number">11.8</span> Distribuzione di Poisson</a></li>
  <li><a href="#sec-discrete-model-checks" id="toc-sec-discrete-model-checks" class="nav-link" data-scroll-target="#sec-discrete-model-checks"><span class="header-section-number">11.9</span> Quando i modelli discreti semplici non bastano</a></li>
  </ul><div class="toc-actions"><ul class="collapse"><li><a href="https://github.com/ccaudek/utet-prob/issues/new" class="toc-action"><i class="bi bi-github"></i>Segnala un problema</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../chapters/probability/10_intro_distributions.html">PARTE 3: Distribuzioni specifiche</a></li><li class="breadcrumb-item"><a href="../../chapters/probability/11_discr_rv_distr.html"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Distribuzioni di variabili casuali discrete</span></a></li></ol></nav><div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title"><span id="sec-prob-discr-distr" class="quarto-section-identifier"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Distribuzioni di variabili casuali discrete</span></span></h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Codice</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Mostra il codice</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Nascondere il codice</a></li></ul></div></div>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header><div class="callout callout-style-default callout-note callout-titled" title="In sintesi">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>In sintesi
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Da sapere</strong> Comprendere come una funzione di massa assegna probabilità ai valori di una variabile discreta; distinguere uniforme discreta, Bernoulli, binomiale, beta-binomiale e Poisson; riconoscere le assunzioni che collegano ciascuna famiglia al processo generativo.</p>
<p><strong>Da saper fare</strong> Scegliere una famiglia discreta coerente con il tipo di dato e il disegno; interpretare supporto, parametri, media e varianza; spiegare che cosa indicano le funzioni <code>d</code>, <code>p</code>, <code>q</code> e <code>r</code> di R; riconoscere quando indipendenza, probabilità costante o equidispersione sono poco plausibili; spiegare perché differenze tra unità nella probabilità di successo producono sovradispersione.</p>
</div>
</div>
<section id="introduzione" class="level2 unnumbered unlisted"><h2 class="unnumbered unlisted anchored" data-anchor-id="introduzione">Introduzione</h2>
<p>Nel capitolo precedente abbiamo introdotto l’idea generale di <strong>distribuzione di probabilità</strong>: un modo formale per assegnare probabilità ai valori possibili di una variabile casuale. In questo capitolo ci concentriamo sulle <strong>distribuzioni discrete</strong>, che descrivono variabili con un insieme finito o numerabile di valori, come una risposta corretta o errata, il numero di successi o il numero di eventi osservati in un intervallo.</p>
<p>La prospettiva adottata è bayesiana, ma lo scopo non è ancora svolgere un’inferenza completa. L’obiettivo è imparare a riconoscere alcune importanti <strong>famiglie di modelli generativi discreti</strong> e le assunzioni che esse incorporano. Nel <a href="13_from_sample_to_evidence.html" class="quarto-xref"><span>Capitolo 13</span></a> useremo questi modelli per comprendere quanta informazione può contenere un campione; nel capitolo sulla verosimiglianza vedremo come, dopo avere osservato i dati, gli stessi modelli possano essere letti come funzioni dei parametri.</p>
</section><section id="perché-le-distribuzioni-discrete-sono-importanti-in-psicologia" class="level2" data-number="11.1"><h2 data-number="11.1" class="anchored" data-anchor-id="perché-le-distribuzioni-discrete-sono-importanti-in-psicologia">
<span class="header-section-number">11.1</span> Perché le distribuzioni discrete sono importanti in psicologia?</h2>
<p>Molti dati psicologici nascono in forma discreta: un item può essere corretto o errato, un sintomo può essere presente o assente, un partecipante può scegliere una tra più alternative e un comportamento può verificarsi un certo numero di volte. Riconoscere questa struttura permette di usare modelli che rispettano i valori realmente possibili e che rendono esplicite le ipotesi sul processo di osservazione.</p>
<p>Una distribuzione discreta risponde anzitutto a una domanda generativa:</p>
<blockquote class="blockquote">
<p>Se questo modello e questi valori dei parametri fossero appropriati, quali dati potremmo osservare e con quali probabilità?</p>
</blockquote>
<div class="callout callout-style-default callout-note callout-titled" title="Ruolo bayesiano delle distribuzioni discrete">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Ruolo bayesiano delle distribuzioni discrete
</div>
</div>
<div class="callout-body-container callout-body">
<p>Nel percorso bayesiano, le distribuzioni discrete possono svolgere tre ruoli distinti:</p>
<ol type="1">
<li>
<strong>Modelli per i dati osservabili</strong>: ad esempio, una risposta corretta o errata può essere modellata con una Bernoulli.</li>
<li>
<strong>Componenti della verosimiglianza</strong>: dopo avere osservato i dati, la stessa espressione viene considerata come funzione dei parametri.</li>
<li>
<strong>Distribuzioni predittive</strong>: integrando l’incertezza sui parametri, si ottengono probabilità per dati futuri. Un primo esempio è la distribuzione beta-binomiale (<a href="#sec-beta-binomial-distribution" class="quarto-xref"><span>Sezione 11.7</span></a>).</li>
</ol>
<p>In questo capitolo ci concentriamo soprattutto sul primo ruolo, introducendo gli altri due soltanto quando aiutano a comprendere il significato del modello.</p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Prerequisiti">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Consiglio</span>Prerequisiti
</div>
</div>
<div class="callout-body-container callout-body">
<p>Per seguire il capitolo è utile avere letto <a href="06_random_var.html" class="quarto-xref"><span>Capitolo 6</span></a>, <a href="07_prob_distributions.html" class="quarto-xref"><span>Capitolo 7</span></a>, <a href="08_expval_var.html" class="quarto-xref"><span>Capitolo 8</span></a> e <a href="10_intro_distributions.html" class="quarto-xref"><span>Capitolo 10</span></a>. Il coefficiente binomiale è stato introdotto in <a href="03_equiprobability_combinatorics_bayesian.html" class="quarto-xref"><span>Capitolo 3</span></a>. Per la notazione matematica, consulta <a href="../appendix/a01_math_symbols.html" class="quarto-xref"><span>Appendice A</span></a>.</p>
</div>
</div>
</section><section id="panoramica-del-capitolo" class="level2 unnumbered unlisted"><h2 class="unnumbered unlisted anchored" data-anchor-id="panoramica-del-capitolo">Panoramica del capitolo</h2>
<p>Il capitolo procede in sette passaggi:</p>
<ol type="1">
<li>distingue supporto e funzione di massa di una variabile discreta;</li>
<li>introduce le funzioni standard di R per probabilità, probabilità cumulate, quantili e simulazioni;</li>
<li>presenta la distribuzione uniforme discreta;</li>
<li>collega Bernoulli e binomiale ai dati binari e ai conteggi di successi;</li>
<li>mostra come la distribuzione beta-binomiale descriva i conteggi di successi quando la probabilità di successo varia tra unità o è incerta;</li>
<li>presenta la distribuzione di Poisson per alcuni processi di conteggio;</li>
<li>mostra perché sovradispersione, eterogeneità e dipendenza possono richiedere modelli più flessibili.</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled" title="Preparazione del notebook">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Preparazione del notebook
</div>
</div>
<div class="callout-body-container callout-body">
<div class="cell">
<details open="" class="code-fold"><summary>Mostra/Nascondi codice</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">here</span><span class="fu">::</span><span class="fu"><a href="https://here.r-lib.org/reference/here.html">here</a></span><span class="op">(</span><span class="st">"code"</span>, <span class="st">"_common.R"</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="kw"><a href="https://rdrr.io/r/base/source.html">source</a></span><span class="op">(</span><span class="op">)</span></span>
<span><span class="fu">apply_visual_theme</span><span class="op">(</span><span class="op">)</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</div>
</div>
</section><section id="sec-discrete-distribution-meaning" class="level2" data-number="11.2"><h2 data-number="11.2" class="anchored" data-anchor-id="sec-discrete-distribution-meaning">
<span class="header-section-number">11.2</span> Che cosa descrive una distribuzione discreta?</h2>
<p>Una distribuzione discreta associa probabilità a valori separati e numerabili. Se <span class="math inline">\(X\)</span> è una variabile casuale discreta, la sua distribuzione è descritta dalla <strong>funzione di massa di probabilità</strong>:</p>
<p><span class="math display">\[
p_X(x) = P(X = x).
\]</span></p>
<p>Le probabilità assegnate ai valori possibili devono soddisfare due condizioni:</p>
<p><span class="math display">\[
p_X(x) \geq 0, \qquad \sum_x p_X(x) = 1.
\]</span></p>
<p>Il <strong>supporto</strong> della distribuzione è l’insieme dei valori che la variabile può assumere. Ad esempio:</p>
<ul>
<li>una variabile Bernoulli ha supporto <span class="math inline">\(\{0,1\}\)</span>;</li>
<li>una variabile binomiale con <span class="math inline">\(n\)</span> prove ha supporto <span class="math inline">\(\{0,1,\ldots,n\}\)</span>;</li>
<li>una variabile di Poisson ha supporto <span class="math inline">\(\{0,1,2,\ldots\}\)</span>.</li>
</ul>
<div class="callout callout-style-default callout-important callout-titled" title="Modello condizionale, non certezza sul parametro">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Importante</span>Modello condizionale, non certezza sul parametro
</div>
</div>
<div class="callout-body-container callout-body">
<p>Quando scriviamo</p>
<p><span class="math display">\[
Y \mid \theta \sim p(\cdot \mid \theta),
\]</span> non stiamo dicendo che <span class="math inline">\(\theta\)</span> sia noto con certezza. Stiamo dicendo: <strong>Se il parametro assumesse un certo valore, quale distribuzione avrebbero i dati?</strong></p>
<p>Questa distinzione è cruciale nella prospettiva bayesiana. Il modello dei dati è condizionato al parametro e l’incertezza sul parametro è rappresentata separatamente da una distribuzione a priori e, dopo avere osservato i dati, da una distribuzione a posteriori.</p>
</div>
</div>
</section><section id="sec-r-discrete-functions" class="level2" data-number="11.3"><h2 data-number="11.3" class="anchored" data-anchor-id="sec-r-discrete-functions">
<span class="header-section-number">11.3</span> Le funzioni R per le distribuzioni</h2>
<p>R utilizza una convenzione molto comoda per lavorare con le distribuzioni di probabilità. Ogni distribuzione ha quattro funzioni principali, identificate da una lettera iniziale:</p>
<table class="caption-top table">
<thead><tr class="header">
<th>Prefisso</th>
<th>Significato</th>
<th>Esempio con la binomiale</th>
</tr></thead>
<tbody>
<tr class="odd">
<td><code>d</code></td>
<td>funzione di massa o densità</td>
<td><code>dbinom(k, size, prob)</code></td>
</tr>
<tr class="even">
<td><code>p</code></td>
<td>funzione di ripartizione</td>
<td><code>pbinom(k, size, prob)</code></td>
</tr>
<tr class="odd">
<td><code>q</code></td>
<td>quantile</td>
<td><code>qbinom(p, size, prob)</code></td>
</tr>
<tr class="even">
<td><code>r</code></td>
<td>generazione casuale</td>
<td><code>rbinom(n, size, prob)</code></td>
</tr>
</tbody>
</table>
<p>Esempio: consideriamo <span class="math inline">\(Y \sim \mathrm{Binomiale}(10, 0.60)\)</span>.</p>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold"><summary>Mostra/Nascondi codice</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Probabilità di osservare esattamente 7 successi</span></span>
<span><span class="va">p_esatto</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Binomial.html">dbinom</a></span><span class="op">(</span><span class="fl">7</span>, size <span class="op">=</span> <span class="fl">10</span>, prob <span class="op">=</span> <span class="fl">0.60</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Probabilità di osservare al massimo 7 successi</span></span>
<span><span class="va">p_cumulato</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Binomial.html">pbinom</a></span><span class="op">(</span><span class="fl">7</span>, size <span class="op">=</span> <span class="fl">10</span>, prob <span class="op">=</span> <span class="fl">0.60</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Più piccolo valore che porta la probabilità cumulata almeno al 95%</span></span>
<span><span class="va">q_95</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Binomial.html">qbinom</a></span><span class="op">(</span><span class="fl">0.95</span>, size <span class="op">=</span> <span class="fl">10</span>, prob <span class="op">=</span> <span class="fl">0.60</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Cinque campioni simulati dalla distribuzione</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">1</span><span class="op">)</span></span>
<span><span class="va">simulazioni</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Binomial.html">rbinom</a></span><span class="op">(</span><span class="fl">5</span>, size <span class="op">=</span> <span class="fl">10</span>, prob <span class="op">=</span> <span class="fl">0.60</span><span class="op">)</span></span>
<span></span>
<span><span class="va">p_esatto</span></span>
<span><span class="co">#&gt; [1] 0.215</span></span>
<span><span class="va">p_cumulato</span></span>
<span><span class="co">#&gt; [1] 0.833</span></span>
<span><span class="va">q_95</span></span>
<span><span class="co">#&gt; [1] 8</span></span>
<span><span class="va">simulazioni</span></span>
<span><span class="co">#&gt; [1] 7 7 6 4 7</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>Per una distribuzione discreta, le funzioni <code>d</code> restituiscono la massa di probabilità associata a un valore; per una distribuzione continua restituiscono invece una densità. Quando i dati sono stati osservati e l’espressione viene considerata come funzione dei parametri, questi valori contribuiscono alla verosimiglianza. Le funzioni <code>r</code> generano simulazioni dal modello e permettono di esaminare quali osservazioni il modello tende a produrre; da sole, però, non dimostrano che il modello sia adeguato ai dati reali.</p>
</section><section id="sec-discrete-uniform" class="level2" data-number="11.4"><h2 data-number="11.4" class="anchored" data-anchor-id="sec-discrete-uniform">
<span class="header-section-number">11.4</span> Distribuzione uniforme discreta</h2>
<section id="definizione" class="level3" data-number="11.4.1"><h3 data-number="11.4.1" class="anchored" data-anchor-id="definizione">
<span class="header-section-number">11.4.1</span> Definizione</h3>
<div id="def-uniform-discrete" class="theorem definition">
<p><span class="theorem-title"><strong>Definizione 11.1</strong></span> Una variabile casuale <span class="math inline">\(X\)</span> segue una distribuzione uniforme discreta su <span class="math inline">\(\{1,\ldots,N\}\)</span> se assegna la stessa probabilità a ciascuno dei valori possibili:</p>
<p><span class="math display">\[
X \sim \mathrm{Uniforme\ discreta}(1,N),
\qquad
P(X=x) = \frac{1}{N}, \quad x = 1,\ldots,N.
\]</span></p>
<p>I suoi momenti principali sono:</p>
<p><span class="math display">\[
\mathbb{E}(X) = \frac{N+1}{2},
\qquad
\mathbb{V}(X) = \frac{N^2 - 1}{12}.
\]</span></p>
</div>
<p>La distribuzione uniforme discreta rappresenta una scelta di <strong>simmetria</strong>: all’interno del modello, gli esiti vengono trattati nello stesso modo. Questa assegnazione deve essere giustificata dal meccanismo di selezione o dalle assunzioni informative; non deriva dal solo fatto che gli esiti possano essere elencati.</p>
</section><section id="esempio-assegnazione-casuale-a-condizioni-sperimentali" class="level3" data-number="11.4.2"><h3 data-number="11.4.2" class="anchored" data-anchor-id="esempio-assegnazione-casuale-a-condizioni-sperimentali">
<span class="header-section-number">11.4.2</span> Esempio: assegnazione casuale a condizioni sperimentali</h3>
<p>Supponiamo di assegnare partecipanti a quattro condizioni sperimentali con uguale probabilità. Il gruppo assegnato a un partecipante può essere modellato come:</p>
<p><span class="math display">\[
G \sim \mathrm{Uniforme\ discreta}(1,4).
\]</span></p>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold"><summary>Mostra/Nascondi codice</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb3"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">42</span><span class="op">)</span></span>
<span><span class="va">N</span> <span class="op">&lt;-</span> <span class="fl">4</span></span>
<span><span class="va">n_partecipanti</span> <span class="op">&lt;-</span> <span class="fl">400</span></span>
<span><span class="va">condizione</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/sample.html">sample</a></span><span class="op">(</span><span class="fl">1</span><span class="op">:</span><span class="va">N</span>, size <span class="op">=</span> <span class="va">n_partecipanti</span>, replace <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span>
<span></span>
<span><span class="va">df_uniforme</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span>condizione <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="va">condizione</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="fu">ggplot</span><span class="op">(</span><span class="va">df_uniforme</span>, <span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">condizione</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_bar</span><span class="op">(</span><span class="fu">aes</span><span class="op">(</span>y <span class="op">=</span> <span class="fu">after_stat</span><span class="op">(</span><span class="va">prop</span><span class="op">)</span>, group <span class="op">=</span> <span class="fl">1</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_hline</span><span class="op">(</span>yintercept <span class="op">=</span> <span class="fl">1</span> <span class="op">/</span> <span class="va">N</span>, linetype <span class="op">=</span> <span class="st">"dashed"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">scale_y_continuous</span><span class="op">(</span>labels <span class="op">=</span> <span class="fu">scales</span><span class="fu">::</span><span class="fu"><a href="https://scales.r-lib.org/reference/percent_format.html">percent_format</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">labs</span><span class="op">(</span></span>
<span>    title <span class="op">=</span> <span class="st">"Assegnazione casuale a quattro condizioni"</span>,</span>
<span>    subtitle <span class="op">=</span> <span class="st">"La linea tratteggiata indica la probabilità teorica 1/4"</span>,</span>
<span>    x <span class="op">=</span> <span class="st">"Condizione sperimentale"</span>,</span>
<span>    y <span class="op">=</span> <span class="st">"Frequenza relativa"</span></span>
<span>  <span class="op">)</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
</details><div class="cell-output-display">
<div id="fig-uniforme-discreta" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-uniforme-discreta-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="11_discr_rv_distr_files/figure-html/fig-uniforme-discreta-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-1" title="Figura&nbsp;11.1: Frequenze relative simulate in 400 assegnazioni indipendenti a quattro condizioni equiprobabili."><img src="11_discr_rv_distr_files/figure-html/fig-uniforme-discreta-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:85.0%"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-uniforme-discreta-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;11.1: Frequenze relative simulate in 400 assegnazioni indipendenti a quattro condizioni equiprobabili.
</figcaption></figure>
</div>
</div>
</div>
<p>La <a href="#fig-uniforme-discreta" class="quarto-xref">Figura&nbsp;<span>11.1</span></a> mostra che le frequenze osservate oscillano intorno a <span class="math inline">\(1/4\)</span>: l’equiprobabilità riguarda il modello, non l’uguaglianza esatta delle frequenze in un campione finito. Inoltre, questa simulazione usa assegnazioni indipendenti; un disegno a gruppi perfettamente bilanciati richiederebbe un diverso meccanismo di randomizzazione.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Interpretazione bayesiana">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Interpretazione bayesiana
</div>
</div>
<div class="callout-body-container callout-body">
<p>Una distribuzione uniforme su un insieme finito può anche rappresentare una prior simmetrica su ipotesi o modelli alternativi:</p>
<p><span class="math display">\[
P(M_1)=P(M_2)=\cdots=P(M_K)=\frac{1}{K}.
\]</span></p>
<p>Questa scelta non dimostra che i modelli siano ugualmente validi. Esprime soltanto pesi iniziali uguali, adottati perché la modellizzazione non distingue le alternative prima dei dati.</p>
</div>
</div>
</section></section><section id="sec-bernoulli-distribution" class="level2" data-number="11.5"><h2 data-number="11.5" class="anchored" data-anchor-id="sec-bernoulli-distribution">
<span class="header-section-number">11.5</span> Distribuzione di Bernoulli</h2>
<section id="definizione-1" class="level3" data-number="11.5.1"><h3 data-number="11.5.1" class="anchored" data-anchor-id="definizione-1">
<span class="header-section-number">11.5.1</span> Definizione</h3>
<div id="def-bernoulli" class="theorem definition">
<p><span class="theorem-title"><strong>Definizione 11.2</strong></span> Una variabile casuale <span class="math inline">\(X\)</span> segue una distribuzione di Bernoulli se può assumere solo due valori, convenzionalmente codificati come 1 e 0:</p>
<p><span class="math display">\[
X \sim \mathrm{Bernoulli}(p),
\qquad
P(X=x) = p^x(1-p)^{1-x},
\quad x \in \{0,1\}.
\]</span></p>
<p>I suoi momenti principali sono:</p>
<p><span class="math display">\[
\mathbb{E}(X) = p,
\qquad
\mathbb{V}(X) = p(1-p).
\]</span></p>
</div>
<p>Il modello di Bernoulli è il più semplice per un dato binario. Il valore 1 non deve essere interpretato come un successo in senso stretto: è solo l’esito che abbiamo scelto di codificare come tale. In psicologia può indicare una risposta corretta, la presenza di un sintomo, l’adesione a un trattamento o una scelta tra due alternative.</p>
</section><section id="esempio-risposta-corretta-a-un-item" class="level3" data-number="11.5.2"><h3 data-number="11.5.2" class="anchored" data-anchor-id="esempio-risposta-corretta-a-un-item">
<span class="header-section-number">11.5.2</span> Esempio: risposta corretta a un item</h3>
<p>Un partecipante risponde a un item di memoria. Se la probabilità di risposta corretta è <span class="math inline">\(p = 0.70\)</span>, la risposta <span class="math inline">\(X\)</span> può essere modellata come:</p>
<p><span class="math display">\[
X \mid p = 0.70 \sim \mathrm{Bernoulli}(0.70).
\]</span></p>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold"><summary>Mostra/Nascondi codice</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb4"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">p</span> <span class="op">&lt;-</span> <span class="fl">0.70</span></span>
<span><span class="va">bern_df</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span></span>
<span>  esito <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0</span>, <span class="fl">1</span><span class="op">)</span>, labels <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Errata"</span>, <span class="st">"Corretta"</span><span class="op">)</span><span class="op">)</span>,</span>
<span>  probabilita <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span> <span class="op">-</span> <span class="va">p</span>, <span class="va">p</span><span class="op">)</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="fu">ggplot</span><span class="op">(</span><span class="va">bern_df</span>, <span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">esito</span>, y <span class="op">=</span> <span class="va">probabilita</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_col</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">scale_y_continuous</span><span class="op">(</span>labels <span class="op">=</span> <span class="fu">scales</span><span class="fu">::</span><span class="fu"><a href="https://scales.r-lib.org/reference/percent_format.html">percent_format</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">labs</span><span class="op">(</span></span>
<span>    title <span class="op">=</span> <span class="st">"Distribuzione di Bernoulli"</span>,</span>
<span>    subtitle <span class="op">=</span> <span class="st">"Probabilità di risposta corretta p = 0.70"</span>,</span>
<span>    x <span class="op">=</span> <span class="st">"Esito"</span>,</span>
<span>    y <span class="op">=</span> <span class="st">"Probabilità"</span></span>
<span>  <span class="op">)</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
</details><div class="cell-output-display">
<div id="fig-bernoulli" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-bernoulli-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="11_discr_rv_distr_files/figure-html/fig-bernoulli-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-2" title="Figura&nbsp;11.2: Funzione di massa di una Bernoulli con probabilità dell’esito 1 pari a 0,70."><img src="11_discr_rv_distr_files/figure-html/fig-bernoulli-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:85.0%"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-bernoulli-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;11.2: Funzione di massa di una Bernoulli con probabilità dell’esito 1 pari a 0,70.
</figcaption></figure>
</div>
</div>
</div>
<p>La <a href="#fig-bernoulli" class="quarto-xref">Figura&nbsp;<span>11.2</span></a> rappresenta le due sole probabilità ammesse dal modello: <span class="math inline">\(P(X=1)=p\)</span> e <span class="math inline">\(P(X=0)=1-p\)</span>.</p>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold"><summary>Mostra/Nascondi codice</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb5"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">123</span><span class="op">)</span></span>
<span><span class="va">risposte</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Binomial.html">rbinom</a></span><span class="op">(</span><span class="fl">20</span>, size <span class="op">=</span> <span class="fl">1</span>, prob <span class="op">=</span> <span class="va">p</span><span class="op">)</span></span>
<span><span class="va">risposte</span></span>
<span><span class="co">#&gt;  [1] 1 0 1 0 0 1 1 0 1 1 0 1 1 1 1 0 1 1 1 0</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">risposte</span><span class="op">)</span></span>
<span><span class="co">#&gt; [1] 0.65</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>Anche se il parametro usato nella simulazione è <span class="math inline">\(p = 0.70\)</span>, in un campione piccolo la proporzione osservata può discostarsi sensibilmente da 0.70. Questo aspetto verrà ripreso nel <a href="13_from_sample_to_evidence.html" class="quarto-xref"><span>Capitolo 13</span></a>: i dati osservati sono informativi, ma sono anche soggetti a variabilità campionaria.</p>
</section><section id="bernoulli-come-modello-generativo" class="level3" data-number="11.5.3"><h3 data-number="11.5.3" class="anchored" data-anchor-id="bernoulli-come-modello-generativo">
<span class="header-section-number">11.5.3</span> Bernoulli come modello generativo</h3>
<p>Per una sequenza di risposte binarie <span class="math inline">\(X_1,\ldots,X_n\)</span>, il modello più semplice assume:</p>
<p><span class="math display">\[
X_i \mid p \overset{\mathrm{iid}}{\sim} \mathrm{Bernoulli}(p),
\qquad i=1,\ldots,n.
\]</span></p>
<p>La sigla <em>iid</em> indica che, condizionatamente a <span class="math inline">\(p\)</span>, le osservazioni sono indipendenti e condividono la stessa distribuzione. L’assunzione è semplice ma forte: la probabilità dell’esito codificato come 1 deve essere la stessa per tutte le osservazioni e una risposta non deve modificare direttamente le altre.</p>
<div class="callout callout-style-default callout-warning callout-titled" title="Quando la Bernoulli è troppo semplice">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Avviso</span>Quando la Bernoulli è troppo semplice
</div>
</div>
<div class="callout-body-container callout-body">
<p>Nei dati psicologici reali, l’assunzione di un unico valore di <span class="math inline">\(p\)</span> può essere irrealistica. Ad esempio, gli item diversi possono avere difficoltà diverse, i partecipanti possono avere abilità diverse, e le risposte successive possono non essere indipendenti.</p>
<p>La distribuzione di Bernoulli rimane comunque il punto di partenza: i modelli più ricchi spesso nascono proprio dal rilassamento di una o più delle sue assunzioni. Un primo esempio è la distribuzione beta-binomiale (<a href="#sec-beta-binomial-distribution" class="quarto-xref"><span>Sezione 11.7</span></a>), che consente alla probabilità di successo di variare tra partecipanti.</p>
</div>
</div>
</section></section><section id="sec-binomial-distribution" class="level2" data-number="11.6"><h2 data-number="11.6" class="anchored" data-anchor-id="sec-binomial-distribution">
<span class="header-section-number">11.6</span> Distribuzione binomiale</h2>
<section id="dalla-bernoulli-alla-binomiale" class="level3" data-number="11.6.1"><h3 data-number="11.6.1" class="anchored" data-anchor-id="dalla-bernoulli-alla-binomiale">
<span class="header-section-number">11.6.1</span> Dalla Bernoulli alla binomiale</h3>
<p>La distribuzione binomiale descrive il numero di successi in <span class="math inline">\(n\)</span> prove di Bernoulli indipendenti, tutte con la stessa probabilità di successo <span class="math inline">\(p\)</span>.</p>
<p>Se</p>
<p><span class="math display">\[
X_1,\ldots,X_n \mid p \sim \mathrm{Bernoulli}(p),
\]</span> e definiamo</p>
<p><span class="math display">\[
Y = \sum_{i=1}^n X_i,
\]</span> allora <span class="math inline">\(Y\)</span> rappresenta il numero totale di successi. In questo caso:</p>
<p><span class="math display">\[
Y \mid p \sim \mathrm{Binomiale}(n,p).
\]</span></p>
</section><section id="perché-compare-il-coefficiente-binomiale" class="level3" data-number="11.6.2"><h3 data-number="11.6.2" class="anchored" data-anchor-id="perché-compare-il-coefficiente-binomiale">
<span class="header-section-number">11.6.2</span> Perché compare il coefficiente binomiale?</h3>
<p>Se osserviamo esattamente <span class="math inline">\(k\)</span> successi e <span class="math inline">\(n-k\)</span> insuccessi, la probabilità di una sequenza specifica è:</p>
<p><span class="math display">\[
p^k(1-p)^{n-k}.
\]</span></p>
<p>Tuttavia, lo stesso numero di successi può comparire in molti ordini diversi. Il numero di sequenze con <span class="math inline">\(k\)</span> successi in <span class="math inline">\(n\)</span> prove è:</p>
<p><span class="math display">\[
\binom{n}{k}.
\]</span> Quindi, la probabilità complessiva di osservare <span class="math inline">\(k\)</span> successi è:</p>
<p><span class="math display">\[
P(Y=k \mid p,n) = \binom{n}{k}p^k(1-p)^{n-k}.
\]</span></p>
</section><section id="definizione-2" class="level3" data-number="11.6.3"><h3 data-number="11.6.3" class="anchored" data-anchor-id="definizione-2">
<span class="header-section-number">11.6.3</span> Definizione</h3>
<div id="def-binomial" class="theorem definition">
<p><span class="theorem-title"><strong>Definizione 11.3</strong></span> Una variabile casuale <span class="math inline">\(Y\)</span> segue una distribuzione binomiale con parametri <span class="math inline">\(n\)</span> e <span class="math inline">\(p\)</span> se:</p>
<p><span class="math display">\[
Y \sim \mathrm{Binomiale}(n,p),
\qquad
P(Y=k)=\binom{n}{k}p^k(1-p)^{n-k},
\quad k=0,1,\ldots,n.
\]</span></p>
<p>I suoi momenti principali sono:</p>
<p><span class="math display">\[
\mathbb{E}(Y)=np,
\qquad
\mathbb{V}(Y)=np(1-p).
\]</span></p>
</div>
</section><section id="esempio-punteggio-a-un-test" class="level3" data-number="11.6.4"><h3 data-number="11.6.4" class="anchored" data-anchor-id="esempio-punteggio-a-un-test">
<span class="header-section-number">11.6.4</span> Esempio: punteggio a un test</h3>
<p>Un test contiene 20 item dicotomici. Se la probabilità di risposta corretta a ciascun item è <span class="math inline">\(p=0.75\)</span>, il numero totale di risposte corrette può essere modellato come:</p>
<p><span class="math display">\[
Y \mid p=0.75 \sim \mathrm{Binomiale}(20,0.75).
\]</span></p>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold"><summary>Mostra/Nascondi codice</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb6"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">n_item</span> <span class="op">&lt;-</span> <span class="fl">20</span></span>
<span><span class="va">p_corretto</span> <span class="op">&lt;-</span> <span class="fl">0.75</span></span>
<span><span class="va">k</span> <span class="op">&lt;-</span> <span class="fl">0</span><span class="op">:</span><span class="va">n_item</span></span>
<span></span>
<span><span class="va">binom_df</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span></span>
<span>  k <span class="op">=</span> <span class="va">k</span>,</span>
<span>  probabilita <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/Binomial.html">dbinom</a></span><span class="op">(</span><span class="va">k</span>, size <span class="op">=</span> <span class="va">n_item</span>, prob <span class="op">=</span> <span class="va">p_corretto</span><span class="op">)</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="fu">ggplot</span><span class="op">(</span><span class="va">binom_df</span>, <span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">k</span>, y <span class="op">=</span> <span class="va">probabilita</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_col</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">scale_x_continuous</span><span class="op">(</span>breaks <span class="op">=</span> <span class="fl">0</span><span class="op">:</span><span class="va">n_item</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">labs</span><span class="op">(</span></span>
<span>    title <span class="op">=</span> <span class="st">"Distribuzione binomiale"</span>,</span>
<span>    subtitle <span class="op">=</span> <span class="st">"Numero di risposte corrette su 20 item, p = 0.75"</span>,</span>
<span>    x <span class="op">=</span> <span class="st">"Risposte corrette"</span>,</span>
<span>    y <span class="op">=</span> <span class="st">"Probabilità"</span></span>
<span>  <span class="op">)</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
</details><div class="cell-output-display">
<div id="fig-binomiale-test" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-binomiale-test-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="11_discr_rv_distr_files/figure-html/fig-binomiale-test-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-3" title="Figura&nbsp;11.3: Distribuzione binomiale del numero di risposte corrette su 20 prove con probabilità costante pari a 0,75."><img src="11_discr_rv_distr_files/figure-html/fig-binomiale-test-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:85.0%"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-binomiale-test-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;11.3: Distribuzione binomiale del numero di risposte corrette su 20 prove con probabilità costante pari a 0,75.
</figcaption></figure>
</div>
</div>
</div>
<p>La <a href="#fig-binomiale-test" class="quarto-xref">Figura&nbsp;<span>11.3</span></a> assegna probabilità al numero totale di risposte corrette, non all’ordine in cui esse compaiono.</p>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold"><summary>Mostra/Nascondi codice</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb7"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">media_teorica</span> <span class="op">&lt;-</span> <span class="va">n_item</span> <span class="op">*</span> <span class="va">p_corretto</span></span>
<span><span class="va">var_teorica</span> <span class="op">&lt;-</span> <span class="va">n_item</span> <span class="op">*</span> <span class="va">p_corretto</span> <span class="op">*</span> <span class="op">(</span><span class="fl">1</span> <span class="op">-</span> <span class="va">p_corretto</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/cat.html">cat</a></span><span class="op">(</span><span class="st">"Media teorica:"</span>, <span class="va">media_teorica</span>, <span class="st">"\n"</span><span class="op">)</span></span>
<span><span class="co">#&gt; Media teorica: 15</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/cat.html">cat</a></span><span class="op">(</span><span class="st">"Varianza teorica:"</span>, <span class="va">var_teorica</span>, <span class="st">"\n"</span><span class="op">)</span></span>
<span><span class="co">#&gt; Varianza teorica: 3.75</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</section><section id="la-proporzione-campionaria" class="level3" data-number="11.6.5"><h3 data-number="11.6.5" class="anchored" data-anchor-id="la-proporzione-campionaria">
<span class="header-section-number">11.6.5</span> La proporzione campionaria</h3>
<p>Spesso non ci interessa solo il numero totale di successi <span class="math inline">\(Y\)</span>, ma anche la proporzione:</p>
<p><span class="math display">\[
\hat p = \frac{Y}{n}.
\]</span></p>
<p>Poiché <span class="math inline">\(Y \sim \mathrm{Binomiale}(n,p)\)</span>, otteniamo:</p>
<p><span class="math display">\[
\mathbb{E}(\hat p)=p,
\qquad
\mathbb{V}(\hat p)=\frac{p(1-p)}{n}.
\]</span></p>
<p>Questa relazione sarà centrale nel <a href="13_from_sample_to_evidence.html" class="quarto-xref"><span>Capitolo 13</span></a>: mostra perché campioni più grandi producono proporzioni più stabili.</p>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold"><summary>Mostra/Nascondi codice</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb8"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">42</span><span class="op">)</span></span>
<span><span class="va">n_values</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">10</span>, <span class="fl">50</span>, <span class="fl">200</span><span class="op">)</span></span>
<span><span class="va">p_vero</span> <span class="op">&lt;-</span> <span class="fl">0.40</span></span>
<span><span class="va">n_rep</span> <span class="op">&lt;-</span> <span class="fl">5000</span></span>
<span></span>
<span><span class="va">sim_list</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/lapply.html">lapply</a></span><span class="op">(</span><span class="va">n_values</span>, <span class="kw">function</span><span class="op">(</span><span class="va">n</span><span class="op">)</span> <span class="op">{</span></span>
<span>  <span class="va">phat</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Binomial.html">rbinom</a></span><span class="op">(</span><span class="va">n_rep</span>, size <span class="op">=</span> <span class="va">n</span>, prob <span class="op">=</span> <span class="va">p_vero</span><span class="op">)</span> <span class="op">/</span> <span class="va">n</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span>n <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="va">n</span><span class="op">)</span>, phat <span class="op">=</span> <span class="va">phat</span><span class="op">)</span></span>
<span><span class="op">}</span><span class="op">)</span></span>
<span></span>
<span><span class="va">sim_df</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/do.call.html">do.call</a></span><span class="op">(</span><span class="va">rbind</span>, <span class="va">sim_list</span><span class="op">)</span></span>
<span></span>
<span><span class="fu">ggplot</span><span class="op">(</span><span class="va">sim_df</span>, <span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">phat</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_histogram</span><span class="op">(</span>bins <span class="op">=</span> <span class="fl">30</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">facet_wrap</span><span class="op">(</span><span class="op">~</span> <span class="va">n</span>, ncol <span class="op">=</span> <span class="fl">1</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">labs</span><span class="op">(</span></span>
<span>    title <span class="op">=</span> <span class="st">"Distribuzione simulata della proporzione campionaria"</span>,</span>
<span>    subtitle <span class="op">=</span> <span class="st">"La variabilità diminuisce al crescere di n"</span>,</span>
<span>    x <span class="op">=</span> <span class="st">"Proporzione osservata"</span>,</span>
<span>    y <span class="op">=</span> <span class="st">"Frequenza"</span></span>
<span>  <span class="op">)</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
</details><div class="cell-output-display">
<div id="fig-proporzione-campionaria" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-proporzione-campionaria-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="11_discr_rv_distr_files/figure-html/fig-proporzione-campionaria-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-4" title="Figura&nbsp;11.4: Distribuzioni simulate della proporzione campionaria per diverse numerosità, con probabilità generatrice pari a 0,40."><img src="11_discr_rv_distr_files/figure-html/fig-proporzione-campionaria-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:85.0%"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-proporzione-campionaria-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;11.4: Distribuzioni simulate della proporzione campionaria per diverse numerosità, con probabilità generatrice pari a 0,40.
</figcaption></figure>
</div>
</div>
</div>
<p>La <a href="#fig-proporzione-campionaria" class="quarto-xref">Figura&nbsp;<span>11.4</span></a> illustra il significato di <span class="math inline">\(\mathbb{V}(\hat p)=p(1-p)/n\)</span>: aumentando <span class="math inline">\(n\)</span>, le proporzioni simulate si concentrano maggiormente intorno a <span class="math inline">\(p\)</span>.</p>
</section><section id="ruolo-bayesiano-la-binomiale-come-verosimiglianza" class="level3" data-number="11.6.6"><h3 data-number="11.6.6" class="anchored" data-anchor-id="ruolo-bayesiano-la-binomiale-come-verosimiglianza">
<span class="header-section-number">11.6.6</span> Ruolo bayesiano: la binomiale come verosimiglianza</h3>
<p>Se osserviamo <span class="math inline">\(y\)</span> successi su <span class="math inline">\(n\)</span> prove, la massa binomiale può essere riletta come funzione di <span class="math inline">\(p\)</span>:</p>
<p><span class="math display">\[
L(p \mid y,n) \propto p^y(1-p)^{n-y}.
\]</span></p>
<p>Il coefficiente <span class="math inline">\(\binom{n}{y}\)</span> è omesso nella proporzionalità perché non dipende da <span class="math inline">\(p\)</span>. Questa espressione non è ancora una distribuzione a posteriori: è la <strong>verosimiglianza</strong>, che confronta quanto valori diversi di <span class="math inline">\(p\)</span> rendano compatibile il risultato osservato, mantenendo fissi <span class="math inline">\(y\)</span> e <span class="math inline">\(n\)</span>.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Anticipazione: prior Beta e aggiornamento">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Anticipazione: prior Beta e aggiornamento
</div>
</div>
<div class="callout-body-container callout-body">
<p>La distribuzione Beta, presentata in <a href="12_cont_rv_distr.html#sec-cont-beta" class="quarto-xref"><span>Sezione 12.8</span></a>, è una distribuzione continua su <span class="math inline">\((0,1)\)</span> molto utile per rappresentare l’incertezza su una probabilità <span class="math inline">\(p\)</span>. In <a href="#sec-beta-binomial-distribution" class="quarto-xref"><span>Sezione 11.7</span></a> ne useremo due proprietà.</p>
<p>Se</p>
<p><span class="math display">\[
p \sim \mathrm{Beta}(\alpha,\beta)
\]</span> e osserviamo <span class="math inline">\(y\)</span> successi su <span class="math inline">\(n\)</span> prove, allora la distribuzione a posteriori è:</p>
<p><span class="math display">\[
p \mid y,n \sim \mathrm{Beta}(\alpha+y,\beta+n-y).
\]</span></p>
<p>Per ora non è necessario padroneggiare questa formula. È sufficiente riconoscere che i dati binomiali aggiornano le credenze su una probabilità.</p>
</div>
</div>
</section></section><section id="sec-beta-binomial-distribution" class="level2" data-number="11.7"><h2 data-number="11.7" class="anchored" data-anchor-id="sec-beta-binomial-distribution">
<span class="header-section-number">11.7</span> Distribuzione beta-binomiale</h2>
<section id="quando-la-probabilità-di-successo-non-è-la-stessa-per-tutti" class="level3" data-number="11.7.1"><h3 data-number="11.7.1" class="anchored" data-anchor-id="quando-la-probabilità-di-successo-non-è-la-stessa-per-tutti">
<span class="header-section-number">11.7.1</span> Quando la probabilità di successo non è la stessa per tutti</h3>
<p>La distribuzione binomiale assume che tutte le prove condividano la stessa probabilità di successo <span class="math inline">\(p\)</span>. Quando le prove provengono da persone diverse, questa assunzione è spesso poco plausibile: in un compito di memoria, ad esempio, alcuni partecipanti ricordano più facilmente di altri.</p>
<p>Consideriamo dieci studenti che studiano 10 parole ciascuno. Il numero di parole ricordate da ciascuno è:</p>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold"><summary>Mostra/Nascondi codice</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb9"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">ricordati</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">2</span>, <span class="fl">3</span>, <span class="fl">3</span>, <span class="fl">4</span>, <span class="fl">4</span>, <span class="fl">8</span>, <span class="fl">8</span>, <span class="fl">9</span>, <span class="fl">9</span>, <span class="fl">10</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span>media <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">ricordati</span><span class="op">)</span>, deviazione_standard <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/sd.html">sd</a></span><span class="op">(</span><span class="va">ricordati</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="co">#&gt;               media deviazione_standard </span></span>
<span><span class="co">#&gt;                6.00                3.06</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>La proporzione complessiva di parole ricordate è 0.60. Se tutti gli studenti avessero la stessa probabilità <span class="math inline">\(p = 0.60\)</span>, il numero di parole ricordate da ciascuno seguirebbe una distribuzione <span class="math inline">\(\mathrm{Binomiale}(10, 0.60)\)</span>, con deviazione standard</p>
<p><span class="math display">\[
\sqrt{10 \times 0.60 \times 0.40} \approx 1.55.
\]</span></p>
<p>La deviazione standard osservata è circa il doppio. La discrepanza compare anche nelle code della distribuzione:</p>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold"><summary>Mostra/Nascondi codice</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb10"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span></span>
<span>  binomiale_al_massimo_2 <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/Binomial.html">pbinom</a></span><span class="op">(</span><span class="fl">2</span>, size <span class="op">=</span> <span class="fl">10</span>, prob <span class="op">=</span> <span class="fl">0.60</span><span class="op">)</span>,</span>
<span>  osservata_al_massimo_2 <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">ricordati</span> <span class="op">&lt;=</span> <span class="fl">2</span><span class="op">)</span>,</span>
<span>  binomiale_almeno_9 <span class="op">=</span> <span class="fl">1</span> <span class="op">-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Binomial.html">pbinom</a></span><span class="op">(</span><span class="fl">8</span>, size <span class="op">=</span> <span class="fl">10</span>, prob <span class="op">=</span> <span class="fl">0.60</span><span class="op">)</span>,</span>
<span>  osservata_almeno_9 <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">ricordati</span> <span class="op">&gt;=</span> <span class="fl">9</span><span class="op">)</span></span>
<span><span class="op">)</span></span>
<span><span class="co">#&gt; binomiale_al_massimo_2 osservata_al_massimo_2 </span></span>
<span><span class="co">#&gt;                 0.0123                 0.1000 </span></span>
<span><span class="co">#&gt;     binomiale_almeno_9     osservata_almeno_9 </span></span>
<span><span class="co">#&gt;                 0.0464                 0.3000</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>Sotto il modello binomiale, ricordare al massimo 2 parole ha probabilità di circa l’1% e ricordarne almeno 9 di circa il 5%. Nel campione, queste prestazioni riguardano rispettivamente 1 e 3 studenti su 10. Con soli dieci studenti le frequenze osservate sono molto instabili, ma tutte le indicazioni vanno nella stessa direzione: i dati sono più dispersi di quanto il modello binomiale possa produrre. Questo fenomeno si chiama <strong>sovradispersione</strong>.</p>
</section><section id="un-modello-a-due-stadi" class="level3" data-number="11.7.2"><h3 data-number="11.7.2" class="anchored" data-anchor-id="un-modello-a-due-stadi">
<span class="header-section-number">11.7.2</span> Un modello a due stadi</h3>
<p>Per rappresentare le differenze tra studenti possiamo attribuire a ciascuno una propria probabilità di ricordo <span class="math inline">\(p_i\)</span>. Il processo generativo si articola allora in due stadi:</p>
<ol type="1">
<li>per ogni studente si estrae una probabilità <span class="math inline">\(p_i\)</span> da una distribuzione che descrive la popolazione degli studenti;</li>
<li>condizionatamente a <span class="math inline">\(p_i\)</span>, il numero di parole ricordate segue una binomiale:</li>
</ol>
<p><span class="math display">\[
Y_i \mid p_i \sim \mathrm{Binomiale}(n, p_i).
\]</span></p>
<p>La distribuzione di <span class="math inline">\(Y_i\)</span> che si ottiene considerando entrambi gli stadi, cioè senza conoscere il valore di <span class="math inline">\(p_i\)</span>, si chiama distribuzione <strong>marginale</strong> di <span class="math inline">\(Y_i\)</span>. Poiché combina più distribuzioni condizionate, pesandole secondo la distribuzione del parametro, viene anche detta <strong>mistura</strong>.</p>
</section><section id="un-caso-semplice-due-tipi-di-studenti" class="level3" data-number="11.7.3"><h3 data-number="11.7.3" class="anchored" data-anchor-id="un-caso-semplice-due-tipi-di-studenti">
<span class="header-section-number">11.7.3</span> Un caso semplice: due tipi di studenti</h3>
<p>Iniziamo da un caso che si può calcolare con i soli strumenti di questo capitolo. Supponiamo che la popolazione comprenda due tipi di studenti, ugualmente frequenti: per il primo tipo la probabilità di ricordo è 0.3, per il secondo è 0.8.</p>
<p><span class="math display">\[
P(p_i = 0.3) = P(p_i = 0.8) = 0.5.
\]</span></p>
<p>Per la legge della probabilità totale, la probabilità di osservare <span class="math inline">\(k\)</span> parole ricordate è la media delle due distribuzioni binomiali, pesata dalla frequenza dei due tipi:</p>
<p><span class="math display">\[
P(Y = k) = 0.5 \binom{n}{k} 0.3^k\, 0.7^{\,n-k} + 0.5 \binom{n}{k} 0.8^k\, 0.2^{\,n-k}.
\]</span></p>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold"><summary>Mostra/Nascondi codice</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb11"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">k</span> <span class="op">&lt;-</span> <span class="fl">0</span><span class="op">:</span><span class="fl">10</span></span>
<span><span class="va">mistura</span> <span class="op">&lt;-</span> <span class="fl">0.5</span> <span class="op">*</span> <span class="fu"><a href="https://rdrr.io/r/stats/Binomial.html">dbinom</a></span><span class="op">(</span><span class="va">k</span>, size <span class="op">=</span> <span class="fl">10</span>, prob <span class="op">=</span> <span class="fl">0.3</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fl">0.5</span> <span class="op">*</span> <span class="fu"><a href="https://rdrr.io/r/stats/Binomial.html">dbinom</a></span><span class="op">(</span><span class="va">k</span>, size <span class="op">=</span> <span class="fl">10</span>, prob <span class="op">=</span> <span class="fl">0.8</span><span class="op">)</span></span>
<span></span>
<span><span class="va">df_mistura</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/cbind.html">rbind</a></span><span class="op">(</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span>k <span class="op">=</span> <span class="va">k</span>, probabilita <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/Binomial.html">dbinom</a></span><span class="op">(</span><span class="va">k</span>, <span class="fl">10</span>, <span class="fl">0.3</span><span class="op">)</span>, modello <span class="op">=</span> <span class="st">"p = 0.3"</span><span class="op">)</span>,</span>
<span>  <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span>k <span class="op">=</span> <span class="va">k</span>, probabilita <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/Binomial.html">dbinom</a></span><span class="op">(</span><span class="va">k</span>, <span class="fl">10</span>, <span class="fl">0.8</span><span class="op">)</span>, modello <span class="op">=</span> <span class="st">"p = 0.8"</span><span class="op">)</span>,</span>
<span>  <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span>k <span class="op">=</span> <span class="va">k</span>, probabilita <span class="op">=</span> <span class="va">mistura</span>, modello <span class="op">=</span> <span class="st">"mistura (0.5 e 0.5)"</span><span class="op">)</span></span>
<span><span class="op">)</span></span>
<span><span class="va">df_mistura</span><span class="op">$</span><span class="va">modello</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="va">df_mistura</span><span class="op">$</span><span class="va">modello</span>, levels <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/unique.html">unique</a></span><span class="op">(</span><span class="va">df_mistura</span><span class="op">$</span><span class="va">modello</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="fu">ggplot</span><span class="op">(</span><span class="va">df_mistura</span>, <span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">k</span>, y <span class="op">=</span> <span class="va">probabilita</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_col</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">facet_wrap</span><span class="op">(</span><span class="op">~</span> <span class="va">modello</span>, nrow <span class="op">=</span> <span class="fl">1</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">scale_x_continuous</span><span class="op">(</span>breaks <span class="op">=</span> <span class="va">k</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">labs</span><span class="op">(</span></span>
<span>    title <span class="op">=</span> <span class="st">"Una mistura di due binomiali"</span>,</span>
<span>    x <span class="op">=</span> <span class="st">"Parole ricordate"</span>,</span>
<span>    y <span class="op">=</span> <span class="st">"Probabilità"</span></span>
<span>  <span class="op">)</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
</details><div class="cell-output-display">
<div id="fig-mistura-binomiali" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-mistura-binomiali-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="11_discr_rv_distr_files/figure-html/fig-mistura-binomiali-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-5" title="Figura&nbsp;11.5: Numero di parole ricordate su 10 per studenti con probabilità di ricordo 0,3, per studenti con probabilità 0,8 e per una popolazione che contiene i due tipi in parti uguali."><img src="11_discr_rv_distr_files/figure-html/fig-mistura-binomiali-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:85.0%"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mistura-binomiali-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;11.5: Numero di parole ricordate su 10 per studenti con probabilità di ricordo 0,3, per studenti con probabilità 0,8 e per una popolazione che contiene i due tipi in parti uguali.
</figcaption></figure>
</div>
</div>
</div>
<p>La <a href="#fig-mistura-binomiali" class="quarto-xref">Figura&nbsp;<span>11.5</span></a> mostra che la mistura conserva i due massimi, attorno a 3 e a 8 parole. La probabilità media di ricordo nella popolazione è <span class="math inline">\(0.5 \times 0.3 + 0.5 \times 0.8 = 0.55\)</span>, ma i valori 5 e 6, vicini a <span class="math inline">\(10 \times 0.55\)</span>, sono fra i meno probabili della zona centrale. Una binomiale con <span class="math inline">\(p = 0.55\)</span> avrebbe invece un solo massimo, proprio in quella zona.</p>
</section><section id="da-dove-viene-la-variabilità-aggiuntiva" class="level3" data-number="11.7.4"><h3 data-number="11.7.4" class="anchored" data-anchor-id="da-dove-viene-la-variabilità-aggiuntiva">
<span class="header-section-number">11.7.4</span> Da dove viene la variabilità aggiuntiva</h3>
<p>La media della mistura è la stessa di una binomiale con <span class="math inline">\(p\)</span> uguale alla probabilità media:</p>
<p><span class="math display">\[
\mathbb{E}(Y) = n\,\mathbb{E}(p_i) = 10 \times 0.55 = 5.5.
\]</span></p>
<p>La varianza, invece, è molto più grande. Per capire perché, la si può scomporre in due parti:</p>
<p><span class="math display">\[
\mathbb{V}(Y)
=
\underbrace{\mathbb{E}\big[\mathbb{V}(Y \mid p_i)\big]}_{\text{variabilità binomiale media}}
+
\underbrace{\mathbb{V}\big[\mathbb{E}(Y \mid p_i)\big]}_{\text{variabilità dovuta alle differenze in } p_i}.
\]</span></p>
<p>Questa scomposizione è nota come <strong>legge della varianza totale</strong>. Nel nostro esempio:</p>
<ul>
<li>il primo termine è la media delle varianze binomiali dei due tipi: <span class="math inline">\(10 \times (0.5 \times 0.3 \times 0.7 + 0.5 \times 0.8 \times 0.2) = 1.85\)</span>;</li>
<li>il secondo termine è la varianza dei numeri medi di parole ricordate dai due tipi, 3 e 8: <span class="math inline">\(10^2 \times \mathbb{V}(p_i) = 100 \times 0.0625 = 6.25\)</span>.</li>
</ul>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold"><summary>Mostra/Nascondi codice</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb12"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">media_mistura</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">k</span> <span class="op">*</span> <span class="va">mistura</span><span class="op">)</span></span>
<span><span class="va">varianza_mistura</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">k</span><span class="op">^</span><span class="fl">2</span> <span class="op">*</span> <span class="va">mistura</span><span class="op">)</span> <span class="op">-</span> <span class="va">media_mistura</span><span class="op">^</span><span class="fl">2</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span></span>
<span>  varianza_mistura <span class="op">=</span> <span class="va">varianza_mistura</span>,</span>
<span>  somma_dei_due_termini <span class="op">=</span> <span class="fl">1.85</span> <span class="op">+</span> <span class="fl">6.25</span>,</span>
<span>  varianza_binomiale_stessa_media <span class="op">=</span> <span class="fl">10</span> <span class="op">*</span> <span class="fl">0.55</span> <span class="op">*</span> <span class="fl">0.45</span></span>
<span><span class="op">)</span></span>
<span><span class="co">#&gt;                varianza_mistura           somma_dei_due_termini </span></span>
<span><span class="co">#&gt;                            8.10                            8.10 </span></span>
<span><span class="co">#&gt; varianza_binomiale_stessa_media </span></span>
<span><span class="co">#&gt;                            2.48</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>La varianza della mistura è 8.1, più del triplo di quella di una binomiale con la stessa media (2.475). La differenza è interamente dovuta al secondo termine: se tutti gli studenti avessero la stessa probabilità, <span class="math inline">\(\mathbb{V}(p_i)\)</span> sarebbe zero e si ritornerebbe alla binomiale.</p>
<div class="callout callout-style-default callout-important callout-titled" title="L'origine della sovradispersione">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Importante</span>L’origine della sovradispersione
</div>
</div>
<div class="callout-body-container callout-body">
<p>La sovradispersione non richiede che il singolo studente si comporti in modo diverso da una binomiale. Nasce dal fatto che studenti diversi hanno probabilità diverse: alla variabilità di ciascuno attorno alla propria media si aggiunge la variabilità delle medie fra studenti.</p>
</div>
</div>
</section><section id="dal-caso-discreto-al-caso-continuo" class="level3" data-number="11.7.5"><h3 data-number="11.7.5" class="anchored" data-anchor-id="dal-caso-discreto-al-caso-continuo">
<span class="header-section-number">11.7.5</span> Dal caso discreto al caso continuo</h3>
<p>Due soli tipi di studenti sono una semplificazione. Più realisticamente, la probabilità di ricordo può assumere qualunque valore tra 0 e 1 e variare con continuità da uno studente all’altro. Per descriverla serve una distribuzione continua definita sull’intervallo <span class="math inline">\((0,1)\)</span>: la <strong>distribuzione Beta</strong>, presentata in <a href="12_cont_rv_distr.html#sec-cont-beta" class="quarto-xref"><span>Sezione 12.8</span></a>.</p>
<p>In questa sezione ne servono soltanto due proprietà. Una distribuzione <span class="math inline">\(\mathrm{Beta}(\alpha, \beta)\)</span> si può descrivere con due quantità:</p>
<p><span class="math display">\[
m = \frac{\alpha}{\alpha+\beta},
\qquad
\kappa = \alpha+\beta.
\]</span></p>
<ul>
<li>
<span class="math inline">\(m\)</span> è la probabilità media di successo nella popolazione;</li>
<li>
<span class="math inline">\(\kappa\)</span> indica quanto le probabilità individuali sono <strong>concentrate</strong> attorno a <span class="math inline">\(m\)</span>: con <span class="math inline">\(\kappa\)</span> grande sono simili fra loro, con <span class="math inline">\(\kappa\)</span> piccolo sono molto diverse.</li>
</ul>
<p>I parametri originali si ricavano da <span class="math inline">\(m\)</span> e <span class="math inline">\(\kappa\)</span> come <span class="math inline">\(\alpha = m\kappa\)</span> e <span class="math inline">\(\beta = (1-m)\kappa\)</span>.</p>
<p>Se la probabilità di ciascuna unità segue una distribuzione Beta e, condizionatamente a essa, il numero di successi segue una binomiale,</p>
<p><span class="math display">\[
p_i \sim \mathrm{Beta}(\alpha, \beta),
\qquad
Y_i \mid p_i \sim \mathrm{Binomiale}(n, p_i),
\]</span></p>
<p>allora la distribuzione marginale di <span class="math inline">\(Y_i\)</span> è una <strong>beta-binomiale</strong>.</p>
</section><section id="definizione-3" class="level3" data-number="11.7.6"><h3 data-number="11.7.6" class="anchored" data-anchor-id="definizione-3">
<span class="header-section-number">11.7.6</span> Definizione</h3>
<div id="def-beta-binomial" class="theorem definition">
<p><span class="theorem-title"><strong>Definizione 11.4</strong></span> Una variabile casuale <span class="math inline">\(Y\)</span> segue una distribuzione beta-binomiale con parametri <span class="math inline">\(n\)</span>, <span class="math inline">\(\alpha &gt; 0\)</span> e <span class="math inline">\(\beta &gt; 0\)</span> se:</p>
<p><span class="math display">\[
Y \sim \mathrm{BetaBinomiale}(n, \alpha, \beta),
\qquad
P(Y=k)=\binom{n}{k}\frac{B(k+\alpha,\; n-k+\beta)}{B(\alpha,\beta)},
\quad k=0,1,\ldots,n,
\]</span></p>
<p>dove <span class="math inline">\(B(\cdot,\cdot)\)</span> è la funzione beta, la costante di normalizzazione della distribuzione Beta (<a href="12_cont_rv_distr.html#sec-cont-beta" class="quarto-xref"><span>Sezione 12.8</span></a>).</p>
<p>Con <span class="math inline">\(m = \alpha/(\alpha+\beta)\)</span> e <span class="math inline">\(\kappa = \alpha+\beta\)</span>, i suoi momenti principali sono:</p>
<p><span class="math display">\[
\mathbb{E}(Y)=nm,
\qquad
\mathbb{V}(Y)=nm(1-m)\,\frac{\kappa+n}{\kappa+1}.
\]</span></p>
</div>
<p>La media coincide con quella di una binomiale con <span class="math inline">\(p = m\)</span>. La varianza è la varianza binomiale <span class="math inline">\(nm(1-m)\)</span> moltiplicata per il fattore</p>
<p><span class="math display">\[
\frac{\kappa+n}{\kappa+1} = 1 + \frac{n-1}{\kappa+1},
\]</span></p>
<p>che è maggiore di 1 non appena <span class="math inline">\(n &gt; 1\)</span>. Il fattore cresce con il numero di prove per unità e diminuisce con la concentrazione <span class="math inline">\(\kappa\)</span>.</p>
<p>Il caso <span class="math inline">\(n = 1\)</span> merita un’osservazione. Con una sola prova per unità il fattore vale 1 e la beta-binomiale coincide con una Bernoulli di parametro <span class="math inline">\(m\)</span>: con una sola risposta binaria per persona, le differenze tra persone non lasciano alcuna traccia nella distribuzione dei dati. Per rilevare l’eterogeneità servono più prove per ciascuna unità.</p>
</section><section id="due-casi-limite" class="level3" data-number="11.7.7"><h3 data-number="11.7.7" class="anchored" data-anchor-id="due-casi-limite">
<span class="header-section-number">11.7.7</span> Due casi limite</h3>
<p>La beta-binomiale contiene come casi particolari due distribuzioni già incontrate in questo capitolo.</p>
<p><strong>Concentrazione molto grande.</strong> Quando <span class="math inline">\(\kappa\)</span> cresce, le probabilità individuali si concentrano attorno a <span class="math inline">\(m\)</span>, il fattore <span class="math inline">\((\kappa+n)/(\kappa+1)\)</span> tende a 1 e la beta-binomiale tende alla <span class="math inline">\(\mathrm{Binomiale}(n, m)\)</span>. La binomiale è quindi il caso in cui tutte le unità condividono la stessa probabilità.</p>
<p><strong>Prior uniforme sulla probabilità.</strong> Con <span class="math inline">\(\alpha = \beta = 1\)</span> la distribuzione Beta è uniforme su <span class="math inline">\((0,1)\)</span> e la beta-binomiale assegna la stessa probabilità a tutti i conteggi possibili:</p>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold"><summary>Mostra/Nascondi codice</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb13"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">dbetabinom_base</span> <span class="op">&lt;-</span> <span class="kw">function</span><span class="op">(</span><span class="va">k</span>, <span class="va">size</span>, <span class="va">shape1</span>, <span class="va">shape2</span><span class="op">)</span> <span class="op">{</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/base/Log.html">exp</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/Special.html">lchoose</a></span><span class="op">(</span><span class="va">size</span>, <span class="va">k</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://rdrr.io/r/base/Special.html">lbeta</a></span><span class="op">(</span><span class="va">k</span> <span class="op">+</span> <span class="va">shape1</span>, <span class="va">size</span> <span class="op">-</span> <span class="va">k</span> <span class="op">+</span> <span class="va">shape2</span><span class="op">)</span> <span class="op">-</span> <span class="fu"><a href="https://rdrr.io/r/base/Special.html">lbeta</a></span><span class="op">(</span><span class="va">shape1</span>, <span class="va">shape2</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="op">}</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="fu">dbetabinom_base</span><span class="op">(</span><span class="fl">0</span><span class="op">:</span><span class="fl">10</span>, size <span class="op">=</span> <span class="fl">10</span>, shape1 <span class="op">=</span> <span class="fl">1</span>, shape2 <span class="op">=</span> <span class="fl">1</span><span class="op">)</span>, <span class="fl">4</span><span class="op">)</span></span>
<span><span class="co">#&gt;  [1] 0.0909 0.0909 0.0909 0.0909 0.0909 0.0909 0.0909 0.0909 0.0909</span></span>
<span><span class="co">#&gt; [10] 0.0909 0.0909</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>Ciascun valore ha probabilità <span class="math inline">\(1/11\)</span>: è la distribuzione uniforme discreta su <span class="math inline">\(\{0, 1, \ldots, 10\}\)</span> (<a href="#sec-discrete-uniform" class="quarto-xref"><span>Sezione 11.4</span></a>). Una probabilità incerta distribuita uniformemente produce conteggi distribuiti uniformemente, e non conteggi concentrati attorno a <span class="math inline">\(n/2\)</span>.</p>
</section><section id="perché-le-prove-non-sono-più-indipendenti" class="level3" data-number="11.7.8"><h3 data-number="11.7.8" class="anchored" data-anchor-id="perché-le-prove-non-sono-più-indipendenti">
<span class="header-section-number">11.7.8</span> Perché le prove non sono più indipendenti</h3>
<p>Nel modello a due stadi, le prove di uno stesso studente sono indipendenti <strong>condizionatamente</strong> a <span class="math inline">\(p_i\)</span>. Se però <span class="math inline">\(p_i\)</span> non è noto, due prove dello stesso studente non sono più indipendenti: un successo nella prima prova rende più plausibile che lo studente abbia una probabilità alta, e quindi aumenta la probabilità di successo nella seconda.</p>
<p>La correlazione tra due prove della stessa unità è</p>
<p><span class="math display">\[
\rho = \frac{1}{\kappa+1},
\]</span></p>
<p>e la varianza della beta-binomiale può essere riscritta come</p>
<p><span class="math display">\[
\mathbb{V}(Y) = nm(1-m)\,\big[1 + (n-1)\rho\big].
\]</span></p>
<p>In <a href="12_cont_rv_distr.html#sec-cont-beta" class="quarto-xref"><span>Sezione 12.8</span></a> vedremo che <span class="math inline">\(1/(\kappa+1)\)</span> ammette anche un’altra lettura: è la quota della varianza di una singola prova dovuta alle differenze tra unità.</p>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold"><summary>Mostra/Nascondi codice</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb14"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">11</span><span class="op">)</span></span>
<span><span class="va">n_sim</span> <span class="op">&lt;-</span> <span class="fl">100000</span></span>
<span><span class="va">p_studente</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Beta.html">rbeta</a></span><span class="op">(</span><span class="va">n_sim</span>, shape1 <span class="op">=</span> <span class="fl">0.60</span> <span class="op">*</span> <span class="fl">3</span>, shape2 <span class="op">=</span> <span class="fl">0.40</span> <span class="op">*</span> <span class="fl">3</span><span class="op">)</span></span>
<span><span class="va">prova_1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Binomial.html">rbinom</a></span><span class="op">(</span><span class="va">n_sim</span>, size <span class="op">=</span> <span class="fl">1</span>, prob <span class="op">=</span> <span class="va">p_studente</span><span class="op">)</span></span>
<span><span class="va">prova_2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Binomial.html">rbinom</a></span><span class="op">(</span><span class="va">n_sim</span>, size <span class="op">=</span> <span class="fl">1</span>, prob <span class="op">=</span> <span class="va">p_studente</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span>correlazione_simulata <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/cor.html">cor</a></span><span class="op">(</span><span class="va">prova_1</span>, <span class="va">prova_2</span><span class="op">)</span>, correlazione_teorica <span class="op">=</span> <span class="fl">1</span> <span class="op">/</span> <span class="op">(</span><span class="fl">3</span> <span class="op">+</span> <span class="fl">1</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="co">#&gt; correlazione_simulata  correlazione_teorica </span></span>
<span><span class="co">#&gt;                 0.253                 0.250</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Eterogeneità e dipendenza">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Eterogeneità e dipendenza
</div>
</div>
<div class="callout-body-container callout-body">
<p>Differenze tra unità e dipendenza tra le prove di una stessa unità sono due aspetti dello stesso fenomeno. Per questo, in <a href="#sec-discrete-model-checks" class="quarto-xref"><span>Sezione 11.9</span></a>, «partecipanti molto diversi tra loro» e «dati provenienti da gruppi differenti» compaiono tra le ragioni per cui l’assunzione di indipendenza della binomiale può non essere soddisfatta.</p>
</div>
</div>
</section><section id="esempio-le-prestazioni-di-dieci-studenti" class="level3" data-number="11.7.9"><h3 data-number="11.7.9" class="anchored" data-anchor-id="esempio-le-prestazioni-di-dieci-studenti">
<span class="header-section-number">11.7.9</span> Esempio: le prestazioni di dieci studenti</h3>
<p>Torniamo ai dieci studenti. Confrontiamo la binomiale con <span class="math inline">\(p = 0.60\)</span> e una beta-binomiale con la stessa media, <span class="math inline">\(m = 0.60\)</span>, e concentrazione <span class="math inline">\(\kappa = 3\)</span>, cioè con <span class="math inline">\(\alpha = 1.8\)</span> e <span class="math inline">\(\beta = 1.2\)</span>.</p>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold"><summary>Mostra/Nascondi codice</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb15"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">k</span> <span class="op">&lt;-</span> <span class="fl">0</span><span class="op">:</span><span class="fl">10</span></span>
<span><span class="va">df_confronto</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/cbind.html">rbind</a></span><span class="op">(</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span>k <span class="op">=</span> <span class="va">k</span>, probabilita <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/Binomial.html">dbinom</a></span><span class="op">(</span><span class="va">k</span>, <span class="fl">10</span>, <span class="fl">0.60</span><span class="op">)</span>,</span>
<span>             modello <span class="op">=</span> <span class="st">"Binomiale: p = 0.60 per tutti"</span><span class="op">)</span>,</span>
<span>  <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span>k <span class="op">=</span> <span class="va">k</span>, probabilita <span class="op">=</span> <span class="fu">dbetabinom_base</span><span class="op">(</span><span class="va">k</span>, <span class="fl">10</span>, <span class="fl">0.60</span> <span class="op">*</span> <span class="fl">3</span>, <span class="fl">0.40</span> <span class="op">*</span> <span class="fl">3</span><span class="op">)</span>,</span>
<span>             modello <span class="op">=</span> <span class="st">"Beta-binomiale: m = 0.60, κ = 3"</span><span class="op">)</span></span>
<span><span class="op">)</span></span>
<span><span class="va">df_confronto</span><span class="op">$</span><span class="va">modello</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="va">df_confronto</span><span class="op">$</span><span class="va">modello</span>, levels <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/unique.html">unique</a></span><span class="op">(</span><span class="va">df_confronto</span><span class="op">$</span><span class="va">modello</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">df_osservati</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span>k <span class="op">=</span> <span class="va">k</span>, frequenza <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/numeric.html">as.numeric</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/table.html">table</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="va">ricordati</span>, levels <span class="op">=</span> <span class="va">k</span><span class="op">)</span><span class="op">)</span><span class="op">)</span> <span class="op">/</span> <span class="fl">10</span><span class="op">)</span></span>
<span></span>
<span><span class="fu">ggplot</span><span class="op">(</span><span class="va">df_confronto</span>, <span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">k</span>, y <span class="op">=</span> <span class="va">probabilita</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_col</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_point</span><span class="op">(</span>data <span class="op">=</span> <span class="va">df_osservati</span>, <span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">k</span>, y <span class="op">=</span> <span class="va">frequenza</span><span class="op">)</span>, size <span class="op">=</span> <span class="fl">2.5</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">facet_wrap</span><span class="op">(</span><span class="op">~</span> <span class="va">modello</span>, nrow <span class="op">=</span> <span class="fl">1</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">scale_x_continuous</span><span class="op">(</span>breaks <span class="op">=</span> <span class="va">k</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">labs</span><span class="op">(</span></span>
<span>    title <span class="op">=</span> <span class="st">"Binomiale e beta-binomiale"</span>,</span>
<span>    x <span class="op">=</span> <span class="st">"Parole ricordate"</span>,</span>
<span>    y <span class="op">=</span> <span class="st">"Probabilità"</span></span>
<span>  <span class="op">)</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
</details><div class="cell-output-display">
<div id="fig-beta-binomiale" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-beta-binomiale-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="11_discr_rv_distr_files/figure-html/fig-beta-binomiale-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-6" title="Figura&nbsp;11.6: Numero di parole ricordate su 10 secondo una binomiale con probabilità fissata a 0,60 e secondo una beta-binomiale con la stessa media e concentrazione pari a 3. I punti indicano le frequenze relative osservate nei dieci studenti."><img src="11_discr_rv_distr_files/figure-html/fig-beta-binomiale-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:85.0%"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-beta-binomiale-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;11.6: Numero di parole ricordate su 10 secondo una binomiale con probabilità fissata a 0,60 e secondo una beta-binomiale con la stessa media e concentrazione pari a 3. I punti indicano le frequenze relative osservate nei dieci studenti.
</figcaption></figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold"><summary>Mostra/Nascondi codice</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb16"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">p_bb</span> <span class="op">&lt;-</span> <span class="fu">dbetabinom_base</span><span class="op">(</span><span class="va">k</span>, <span class="fl">10</span>, <span class="fl">0.60</span> <span class="op">*</span> <span class="fl">3</span>, <span class="fl">0.40</span> <span class="op">*</span> <span class="fl">3</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/cbind.html">rbind</a></span><span class="op">(</span></span>
<span>  binomiale <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span>deviazione_standard <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">sqrt</a></span><span class="op">(</span><span class="fl">10</span> <span class="op">*</span> <span class="fl">0.60</span> <span class="op">*</span> <span class="fl">0.40</span><span class="op">)</span>,</span>
<span>                al_massimo_2 <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/Binomial.html">pbinom</a></span><span class="op">(</span><span class="fl">2</span>, <span class="fl">10</span>, <span class="fl">0.60</span><span class="op">)</span>,</span>
<span>                almeno_9 <span class="op">=</span> <span class="fl">1</span> <span class="op">-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Binomial.html">pbinom</a></span><span class="op">(</span><span class="fl">8</span>, <span class="fl">10</span>, <span class="fl">0.60</span><span class="op">)</span><span class="op">)</span>,</span>
<span>  beta_binomiale <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">sqrt</a></span><span class="op">(</span><span class="fl">10</span> <span class="op">*</span> <span class="fl">0.60</span> <span class="op">*</span> <span class="fl">0.40</span> <span class="op">*</span> <span class="op">(</span><span class="fl">3</span> <span class="op">+</span> <span class="fl">10</span><span class="op">)</span> <span class="op">/</span> <span class="op">(</span><span class="fl">3</span> <span class="op">+</span> <span class="fl">1</span><span class="op">)</span><span class="op">)</span>,</span>
<span>                     <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">p_bb</span><span class="op">[</span><span class="va">k</span> <span class="op">&lt;=</span> <span class="fl">2</span><span class="op">]</span><span class="op">)</span>,</span>
<span>                     <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">p_bb</span><span class="op">[</span><span class="va">k</span> <span class="op">&gt;=</span> <span class="fl">9</span><span class="op">]</span><span class="op">)</span><span class="op">)</span>,</span>
<span>  osservato <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/sd.html">sd</a></span><span class="op">(</span><span class="va">ricordati</span><span class="op">)</span>, <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">ricordati</span> <span class="op">&lt;=</span> <span class="fl">2</span><span class="op">)</span>, <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">ricordati</span> <span class="op">&gt;=</span> <span class="fl">9</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="op">)</span>, <span class="fl">3</span><span class="op">)</span></span>
<span><span class="co">#&gt;                deviazione_standard al_massimo_2 almeno_9</span></span>
<span><span class="co">#&gt; binomiale                     1.55        0.012    0.046</span></span>
<span><span class="co">#&gt; beta_binomiale                2.79        0.137    0.232</span></span>
<span><span class="co">#&gt; osservato                     3.06        0.100    0.300</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>La beta-binomiale riproduce molto meglio la dispersione dei dati: la sua deviazione standard è circa 2.8, contro 1.55 della binomiale e 3.06 osservata, e assegna alle prestazioni molto basse e molto alte probabilità paragonabili alle frequenze osservate. Il fattore di inflazione della varianza vale <span class="math inline">\((3 + 10)/(3 + 1) = 3.25\)</span>.</p>
<p>Il valore <span class="math inline">\(\kappa = 3\)</span> è stato scelto qui a scopo illustrativo. Stimare <span class="math inline">\(m\)</span> e <span class="math inline">\(\kappa\)</span> a partire dai dati è un problema di inferenza, che affronteremo nei capitoli successivi.</p>
</section><section id="le-funzioni-r" class="level3" data-number="11.7.10"><h3 data-number="11.7.10" class="anchored" data-anchor-id="le-funzioni-r">
<span class="header-section-number">11.7.10</span> Le funzioni R</h3>
<p>R di base non include funzioni per la beta-binomiale, ma è semplice costruirle. La funzione di massa è <code>dbetabinom_base()</code>, definita sopra. Le simulazioni si ottengono seguendo direttamente i due stadi del modello:</p>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold"><summary>Mostra/Nascondi codice</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb17"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">rbetabinom_base</span> <span class="op">&lt;-</span> <span class="kw">function</span><span class="op">(</span><span class="va">n_sim</span>, <span class="va">size</span>, <span class="va">shape1</span>, <span class="va">shape2</span><span class="op">)</span> <span class="op">{</span></span>
<span>  <span class="va">p</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Beta.html">rbeta</a></span><span class="op">(</span><span class="va">n_sim</span>, <span class="va">shape1</span>, <span class="va">shape2</span><span class="op">)</span>   <span class="co"># stadio 1: una probabilità per ciascuna unità</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/stats/Binomial.html">rbinom</a></span><span class="op">(</span><span class="va">n_sim</span>, size <span class="op">=</span> <span class="va">size</span>, prob <span class="op">=</span> <span class="va">p</span><span class="op">)</span> <span class="co"># stadio 2: i successi, data quella probabilità</span></span>
<span><span class="op">}</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">11</span><span class="op">)</span></span>
<span><span class="va">y_sim</span> <span class="op">&lt;-</span> <span class="fu">rbetabinom_base</span><span class="op">(</span><span class="fl">100000</span>, size <span class="op">=</span> <span class="fl">10</span>, shape1 <span class="op">=</span> <span class="fl">1.8</span>, shape2 <span class="op">=</span> <span class="fl">1.2</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/cbind.html">rbind</a></span><span class="op">(</span></span>
<span>  simulata <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/numeric.html">as.numeric</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/table.html">table</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="va">y_sim</span>, levels <span class="op">=</span> <span class="fl">0</span><span class="op">:</span><span class="fl">10</span><span class="op">)</span><span class="op">)</span><span class="op">)</span> <span class="op">/</span> <span class="fl">100000</span>,</span>
<span>  esatta <span class="op">=</span> <span class="fu">dbetabinom_base</span><span class="op">(</span><span class="fl">0</span><span class="op">:</span><span class="fl">10</span>, <span class="fl">10</span>, <span class="fl">1.8</span>, <span class="fl">1.2</span><span class="op">)</span></span>
<span><span class="op">)</span>, <span class="fl">3</span><span class="op">)</span></span>
<span><span class="co">#&gt;           [,1]  [,2]  [,3]  [,4]  [,5]  [,6]  [,7]  [,8]  [,9]</span></span>
<span><span class="co">#&gt; simulata 0.025 0.046 0.065 0.080 0.094 0.103 0.112 0.119 0.124</span></span>
<span><span class="co">#&gt; esatta   0.026 0.047 0.064 0.079 0.092 0.104 0.113 0.120 0.123</span></span>
<span><span class="co">#&gt;          [,10] [,11]</span></span>
<span><span class="co">#&gt; simulata 0.122 0.109</span></span>
<span><span class="co">#&gt; esatta   0.122 0.110</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>Le frequenze simulate coincidono con le probabilità esatte entro l’errore di simulazione. La funzione di ripartizione si ottiene sommando le masse, ad esempio con <code>cumsum(dbetabinom_base(0:10, 10, 1.8, 1.2))</code>. Il pacchetto <strong>extraDistr</strong> fornisce funzioni già pronte per la beta-binomiale, come <code>dbbinom()</code>, <code>pbbinom()</code> e <code>rbbinom()</code>.</p>
</section><section id="ruolo-bayesiano-eterogeneità-e-incertezza" class="level3" data-number="11.7.11"><h3 data-number="11.7.11" class="anchored" data-anchor-id="ruolo-bayesiano-eterogeneità-e-incertezza">
<span class="header-section-number">11.7.11</span> Ruolo bayesiano: eterogeneità e incertezza</h3>
<p>La stessa distribuzione ammette due letture, che corrispondono a due significati diversi della distribuzione Beta.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead><tr class="header">
<th>Lettura</th>
<th>Che cosa descrive la Beta</th>
<th>Esempio</th>
</tr></thead>
<tbody>
<tr class="odd">
<td><strong>Eterogeneità</strong></td>
<td>differenze reali tra unità: ciascuna ha la propria probabilità</td>
<td>la distribuzione dei punteggi in una popolazione di studenti con capacità diverse</td>
</tr>
<tr class="even">
<td><strong>Incertezza epistemica</strong></td>
<td>un’unica probabilità, non nota: la Beta descrive ciò che crediamo su di essa</td>
<td>la previsione di quanti successi si osserveranno in nuove prove</td>
</tr>
</tbody>
</table>
<p>Nella seconda lettura, la beta-binomiale è una <strong>distribuzione predittiva</strong>. Se l’incertezza su <span class="math inline">\(p\)</span> prima dei dati è descritta da <span class="math inline">\(p \sim \mathrm{Beta}(\alpha, \beta)\)</span>, il numero di successi in <span class="math inline">\(n\)</span> prove future segue una <span class="math inline">\(\mathrm{BetaBinomiale}(n, \alpha, \beta)\)</span>: è la distribuzione <strong>predittiva a priori</strong>. Dopo avere osservato <span class="math inline">\(y\)</span> successi su <span class="math inline">\(n\)</span> prove, la distribuzione a posteriori è <span class="math inline">\(\mathrm{Beta}(\alpha+y, \beta+n-y)\)</span>, come anticipato in <a href="#sec-binomial-distribution" class="quarto-xref"><span>Sezione 11.6</span></a>, e il numero di successi in <span class="math inline">\(n'\)</span> nuove prove segue</p>
<p><span class="math display">\[
\tilde Y \mid y \sim \mathrm{BetaBinomiale}(n',\; \alpha+y,\; \beta+n-y),
\]</span></p>
<p>la distribuzione <strong>predittiva a posteriori</strong>.</p>
<p>Ad esempio, con prior <span class="math inline">\(\mathrm{Beta}(2, 2)\)</span> e 7 successi su 10 prove, la posterior è <span class="math inline">\(\mathrm{Beta}(9, 5)\)</span>. Per 10 nuove prove, la deviazione standard della predittiva a posteriori è circa 1.92; quella di una binomiale che fissa <span class="math inline">\(p\)</span> alla media a posteriori, <span class="math inline">\(9/14\)</span>, è circa 1.52. La previsione che tratta <span class="math inline">\(p\)</span> come noto sottostima l’incertezza, perché ignora l’incertezza residua sul parametro.</p>
<div class="callout callout-style-default callout-important callout-titled" title="Stessa formula, conseguenze diverse">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Importante</span>Stessa formula, conseguenze diverse
</div>
</div>
<div class="callout-body-container callout-body">
<p>Nella lettura come eterogeneità, la variabilità aggiuntiva è una proprietà della popolazione: osservare più studenti permette di descriverla meglio, ma non la elimina. Nella lettura come incertezza epistemica, la variabilità aggiuntiva dipende da ciò che non sappiamo: con più dati la posterior si concentra, <span class="math inline">\(\kappa\)</span> cresce e la predittiva si avvicina a una binomiale.</p>
</div>
</div>
</section></section><section id="sec-poisson-distribution" class="level2" data-number="11.8"><h2 data-number="11.8" class="anchored" data-anchor-id="sec-poisson-distribution">
<span class="header-section-number">11.8</span> Distribuzione di Poisson</h2>
<section id="quando-usarla" class="level3" data-number="11.8.1"><h3 data-number="11.8.1" class="anchored" data-anchor-id="quando-usarla">
<span class="header-section-number">11.8.1</span> Quando usarla</h3>
<p>La distribuzione di Poisson è un possibile modello per il numero di eventi osservati in un intervallo di tempo, spazio o esposizione. La sua giustificazione richiede assunzioni idealizzate, tra cui:</p>
<ul>
<li>gli eventi sono conteggiabili e l’intervallo di osservazione è ben definito;</li>
<li>il tasso medio è stabile nell’intervallo considerato;</li>
<li>gli eventi in intervalli disgiunti sono approssimativamente indipendenti;</li>
<li>in intervalli molto brevi, la probabilità di più eventi contemporanei è trascurabile rispetto a quella di un singolo evento.</li>
</ul>
<p>In psicologia, esempi comuni sono:</p>
<ul>
<li>attacchi di panico in un mese;</li>
<li>errori di omissione in un compito attentivo;</li>
<li>risvegli notturni;</li>
<li>comportamenti target osservati in una sessione.</li>
</ul></section><section id="definizione-4" class="level3" data-number="11.8.2"><h3 data-number="11.8.2" class="anchored" data-anchor-id="definizione-4">
<span class="header-section-number">11.8.2</span> Definizione</h3>
<div id="def-poisson" class="theorem definition">
<p><span class="theorem-title"><strong>Definizione 11.5</strong></span> Una variabile casuale <span class="math inline">\(Y\)</span> segue una distribuzione di Poisson con parametro <span class="math inline">\(\lambda &gt; 0\)</span> se:</p>
<p><span class="math display">\[
Y \sim \mathrm{Poisson}(\lambda),
\qquad
P(Y=y)=\frac{\lambda^y e^{-\lambda}}{y!},
\quad y=0,1,2,\ldots.
\]</span></p>
<p>La sua proprietà caratteristica è:</p>
<p><span class="math display">\[
\mathbb{E}(Y)=\mathbb{V}(Y)=\lambda.
\]</span></p>
</div>
<p>Il parametro <span class="math inline">\(\lambda\)</span> rappresenta il numero medio atteso di eventi nell’intervallo considerato. Se <span class="math inline">\(\lambda=2.5\)</span>, ci aspettiamo in media 2.5 eventi per intervallo, ma il numero osservato potrà essere 0, 1, 2, 3, e così via.</p>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold"><summary>Mostra/Nascondi codice</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb18"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">lambda</span> <span class="op">&lt;-</span> <span class="fl">2.5</span></span>
<span><span class="va">y</span> <span class="op">&lt;-</span> <span class="fl">0</span><span class="op">:</span><span class="fl">12</span></span>
<span><span class="va">pois_df</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span></span>
<span>  y <span class="op">=</span> <span class="va">y</span>,</span>
<span>  probabilita <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/Poisson.html">dpois</a></span><span class="op">(</span><span class="va">y</span>, lambda <span class="op">=</span> <span class="va">lambda</span><span class="op">)</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="fu">ggplot</span><span class="op">(</span><span class="va">pois_df</span>, <span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">y</span>, y <span class="op">=</span> <span class="va">probabilita</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_col</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">scale_x_continuous</span><span class="op">(</span>breaks <span class="op">=</span> <span class="va">y</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">labs</span><span class="op">(</span></span>
<span>    title <span class="op">=</span> <span class="st">"Distribuzione di Poisson"</span>,</span>
<span>    subtitle <span class="op">=</span> <span class="st">"Conteggi attesi con lambda = 2.5"</span>,</span>
<span>    x <span class="op">=</span> <span class="st">"Numero di eventi"</span>,</span>
<span>    y <span class="op">=</span> <span class="st">"Probabilità"</span></span>
<span>  <span class="op">)</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
</details><div class="cell-output-display">
<div id="fig-poisson" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-poisson-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="11_discr_rv_distr_files/figure-html/fig-poisson-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-7" title="Figura&nbsp;11.7: Funzione di massa di una distribuzione di Poisson con tasso medio pari a 2,5 eventi per intervallo."><img src="11_discr_rv_distr_files/figure-html/fig-poisson-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:85.0%"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-poisson-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;11.7: Funzione di massa di una distribuzione di Poisson con tasso medio pari a 2,5 eventi per intervallo.
</figcaption></figure>
</div>
</div>
</div>
<p>La <a href="#fig-poisson" class="quarto-xref">Figura&nbsp;<span>11.7</span></a> mostra una distribuzione asimmetrica su conteggi interi non negativi; il parametro <span class="math inline">\(\lambda\)</span> ne determina sia la media sia la varianza.</p>
</section><section id="esempio-clinico" class="level3" data-number="11.8.3"><h3 data-number="11.8.3" class="anchored" data-anchor-id="esempio-clinico">
<span class="header-section-number">11.8.3</span> Esempio clinico</h3>
<p>Un clinico sta monitorando il numero di attacchi di panico riportati da un paziente in un mese. Se il tasso medio atteso è <span class="math inline">\(\lambda = 2.5\)</span> attacchi al mese, allora:</p>
<p><span class="math display">\[
Y \mid \lambda = 2.5 \sim \mathrm{Poisson}(2.5).
\]</span></p>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold"><summary>Mostra/Nascondi codice</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb19"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">123</span><span class="op">)</span></span>
<span><span class="va">mesi</span> <span class="op">&lt;-</span> <span class="fl">24</span></span>
<span><span class="va">attacchi</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Poisson.html">rpois</a></span><span class="op">(</span><span class="va">mesi</span>, lambda <span class="op">=</span> <span class="fl">2.5</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span></span>
<span>  mese <span class="op">=</span> <span class="fl">1</span><span class="op">:</span><span class="va">mesi</span>,</span>
<span>  attacchi <span class="op">=</span> <span class="va">attacchi</span></span>
<span><span class="op">)</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
</details><div class="cell-output-display">
<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["mese"],"name":[1],"type":["int"],"align":["right"]},{"label":["attacchi"],"name":[2],"type":["int"],"align":["right"]}],"data":[{"1":"1","2":"2"},{"1":"2","2":"4"},{"1":"3","2":"2"},{"1":"4","2":"4"},{"1":"5","2":"5"},{"1":"6","2":"0"},{"1":"7","2":"2"},{"1":"8","2":"5"},{"1":"9","2":"3"},{"1":"10","2":"2"},{"1":"11","2":"5"},{"1":"12","2":"2"},{"1":"13","2":"3"},{"1":"14","2":"3"},{"1":"15","2":"1"},{"1":"16","2":"5"},{"1":"17","2":"1"},{"1":"18","2":"0"},{"1":"19","2":"2"},{"1":"20","2":"5"},{"1":"21","2":"4"},{"1":"22","2":"3"},{"1":"23","2":"3"},{"1":"24","2":"7"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold"><summary>Mostra/Nascondi codice</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb20"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/cat.html">cat</a></span><span class="op">(</span><span class="st">"Media osservata:"</span>, <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">attacchi</span><span class="op">)</span>, <span class="fl">2</span><span class="op">)</span>, <span class="st">"\n"</span><span class="op">)</span></span>
<span><span class="co">#&gt; Media osservata: 3.04</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/cat.html">cat</a></span><span class="op">(</span><span class="st">"Varianza osservata:"</span>, <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/cor.html">var</a></span><span class="op">(</span><span class="va">attacchi</span><span class="op">)</span>, <span class="fl">2</span><span class="op">)</span>, <span class="st">"\n"</span><span class="op">)</span></span>
<span><span class="co">#&gt; Varianza osservata: 3.09</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>Con pochi mesi di osservazione, media e varianza empiriche possono differire sensibilmente. Con molte osservazioni indipendenti generate da una Poisson, entrambe tendono verso <span class="math inline">\(\lambda\)</span>. La somiglianza tra media e varianza è però soltanto una conseguenza necessaria del modello, non una prova sufficiente della sua adeguatezza.</p>
</section><section id="tassi-ed-esposizione" class="level3" data-number="11.8.4"><h3 data-number="11.8.4" class="anchored" data-anchor-id="tassi-ed-esposizione">
<span class="header-section-number">11.8.4</span> Tassi ed esposizione</h3>
<p>Spesso gli intervalli di osservazione non hanno la stessa durata. In questo caso non è sufficiente confrontare i conteggi grezzi: bisogna tenere conto dell’<strong>esposizione</strong>.</p>
<p>Se <span class="math inline">\(t_i\)</span> è la durata dell’osservazione per l’unità <span class="math inline">\(i\)</span>, possiamo scrivere:</p>
<p><span class="math display">\[
Y_i \mid \lambda,t_i \sim \mathrm{Poisson}(\lambda t_i),
\]</span> dove <span class="math inline">\(\lambda\)</span> è il tasso per unità di esposizione.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Esempio">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Esempio
</div>
</div>
<div class="callout-body-container callout-body">
<p>Osservare 4 comportamenti problema in 2 ore non ha lo stesso significato di osservarli in 20 minuti. Il conteggio è lo stesso, ma il tasso è diverso.</p>
</div>
</div>
</section><section id="ruolo-bayesiano-prior-gamma-per-un-tasso" class="level3" data-number="11.8.5"><h3 data-number="11.8.5" class="anchored" data-anchor-id="ruolo-bayesiano-prior-gamma-per-un-tasso">
<span class="header-section-number">11.8.5</span> Ruolo bayesiano: prior Gamma per un tasso</h3>
<p>Nel framework bayesiano, <span class="math inline">\(\lambda\)</span> è una quantità incerta. Una scelta frequente per rappresentare l’incertezza su un tasso positivo è la distribuzione Gamma, presentata in <a href="12_cont_rv_distr.html#sec-cont-gamma" class="quarto-xref"><span>Sezione 12.7</span></a>.</p>
<p>Se</p>
<p><span class="math display">\[
\lambda \sim \mathrm{Gamma}(\alpha,\beta),
\]</span> e osserviamo conteggi indipendenti <span class="math inline">\(y_1,\ldots,y_n\)</span> su intervalli di uguale esposizione, allora:</p>
<p><span class="math display">\[
\lambda \mid \mathbf{y}
\sim
\mathrm{Gamma}\left(\alpha + \sum_{i=1}^n y_i,\; \beta+n\right),
\]</span></p>
<p>nella parametrizzazione in cui <span class="math inline">\(\beta\)</span> è il parametro di tasso della Gamma.</p>
<p>Per ora, il punto fondamentale è il seguente: la distribuzione di Poisson fornisce il modello dei conteggi, mentre la distribuzione Gamma rappresenta l’incertezza sul tasso che genera tali conteggi.</p>
</section></section><section id="sec-discrete-model-checks" class="level2" data-number="11.9"><h2 data-number="11.9" class="anchored" data-anchor-id="sec-discrete-model-checks">
<span class="header-section-number">11.9</span> Quando i modelli discreti semplici non bastano</h2>
<p>Le distribuzioni introdotte finora sono utili perché semplici e interpretabili. Proprio per questo, però, incorporano assunzioni forti.</p>
<section id="binomiale-indipendenza-e-probabilità-costante" class="level3" data-number="11.9.1"><h3 data-number="11.9.1" class="anchored" data-anchor-id="binomiale-indipendenza-e-probabilità-costante">
<span class="header-section-number">11.9.1</span> Binomiale: indipendenza e probabilità costante</h3>
<p>La distribuzione binomiale presuppone che tutte le prove abbiano la stessa probabilità <span class="math inline">\(p\)</span> e siano indipendenti. Questa assunzione può essere problematica quando:</p>
<ul>
<li>gli item hanno difficoltà diverse;</li>
<li>i partecipanti sono molto diversi tra loro;</li>
<li>le prove successive sono influenzate dall’apprendimento, dalla fatica o dalla memoria;</li>
<li>i dati provengono da gruppi o contesti differenti.</li>
</ul>
<p>In questi casi la variabilità osservata può essere maggiore di quella prevista dalla distribuzione binomiale: si parla di <strong>sovradispersione</strong>. La distribuzione beta-binomiale (<a href="#sec-beta-binomial-distribution" class="quarto-xref"><span>Sezione 11.7</span></a>) è il modello più semplice che la rappresenta.</p>
</section><section id="poisson-equidispersione" class="level3" data-number="11.9.2"><h3 data-number="11.9.2" class="anchored" data-anchor-id="poisson-equidispersione">
<span class="header-section-number">11.9.2</span> Poisson: equidispersione</h3>
<p>La distribuzione di Poisson assume che media e varianza coincidano:</p>
<p><span class="math display">\[
\mathbb{E}(Y)=\mathbb{V}(Y)=\lambda.
\]</span></p>
<p>Nei dati psicologici, questa proprietà è spesso violata. Se la varianza è molto maggiore della media, una Poisson semplice può sottostimare la dispersione. Anche quando media e varianza sono simili, tuttavia, restano da controllare altre caratteristiche, come eccesso di zeri, dipendenza temporale ed eterogeneità tra individui.</p>
<p>Il modello analogo alla beta-binomiale per i conteggi di eventi è la <strong>binomiale negativa</strong>: si ottiene lasciando variare il tasso <span class="math inline">\(\lambda\)</span> tra unità secondo una distribuzione Gamma (<a href="12_cont_rv_distr.html#sec-cont-gamma" class="quarto-xref"><span>Sezione 12.7</span></a>). Come nella beta-binomiale, l’eterogeneità dei tassi produce una varianza maggiore della media.</p>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold"><summary>Mostra/Nascondi codice</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb21"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Piccolo controllo descrittivo per dati di conteggio</span></span>
<span><span class="va">media_attacchi</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">attacchi</span><span class="op">)</span></span>
<span><span class="va">var_attacchi</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/cor.html">var</a></span><span class="op">(</span><span class="va">attacchi</span><span class="op">)</span></span>
<span><span class="va">rapporto_dispersione</span> <span class="op">&lt;-</span> <span class="va">var_attacchi</span> <span class="op">/</span> <span class="va">media_attacchi</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/cat.html">cat</a></span><span class="op">(</span><span class="st">"Media:"</span>, <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="va">media_attacchi</span>, <span class="fl">2</span><span class="op">)</span>, <span class="st">"\n"</span><span class="op">)</span></span>
<span><span class="co">#&gt; Media: 3.04</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/cat.html">cat</a></span><span class="op">(</span><span class="st">"Varianza:"</span>, <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="va">var_attacchi</span>, <span class="fl">2</span><span class="op">)</span>, <span class="st">"\n"</span><span class="op">)</span></span>
<span><span class="co">#&gt; Varianza: 3.09</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/cat.html">cat</a></span><span class="op">(</span><span class="st">"Varianza / media:"</span>, <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="va">rapporto_dispersione</span>, <span class="fl">2</span><span class="op">)</span>, <span class="st">"\n"</span><span class="op">)</span></span>
<span><span class="co">#&gt; Varianza / media: 1.01</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div class="callout callout-style-default callout-warning callout-titled" title="Il modello non è il fenomeno">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Avviso</span>Il modello non è il fenomeno
</div>
</div>
<div class="callout-body-container callout-body">
<p>Una distribuzione discreta è una rappresentazione semplificata del processo che potrebbe aver generato i dati. Non basta scegliere una distribuzione perché il dominio sembra corretto: bisogna chiedersi se le assunzioni del modello siano plausibili per il disegno di ricerca e per il fenomeno psicologico studiato.</p>
</div>
</div>
</section></section><section id="riflessioni-conclusive" class="level2 unnumbered unlisted"><h2 class="unnumbered unlisted anchored" data-anchor-id="riflessioni-conclusive">Riflessioni conclusive</h2>
<p>Le distribuzioni discrete introdotte in questo capitolo costituiscono un primo vocabolario per la modellazione dei dati psicologici. La distribuzione uniforme discreta rappresenta una simmetria tra alternative finite, la distribuzione di Bernoulli descrive un singolo esito binario, la distribuzione binomiale descrive il numero di successi in un numero fisso di prove, la distribuzione beta-binomiale descrive lo stesso conteggio quando la probabilità di successo varia tra unità o è incerta, e la distribuzione di Poisson è un modello possibile per il conteggio di eventi prodotti da un tasso stabile.</p>
<p>In prospettiva bayesiana, queste distribuzioni non sono soltanto formule per calcolare le probabilità. Esplicitano le assunzioni sul processo generativo. Dopo l’osservazione dei dati, le stesse espressioni possono essere considerate come verosimiglianze e, integrando l’incertezza sui parametri, contribuiscono alle distribuzioni predittive.</p>
<p>La scelta di una famiglia di distribuzioni non dipende quindi soltanto dal supporto. Bisogna chiedersi se l’indipendenza, la probabilità costante, il tasso stabile e l’equidispersione siano plausibili. Quando queste condizioni non sono soddisfatte, la soluzione non consiste nel forzare i dati nel modello più semplice, ma nel costruire una rappresentazione più adeguata dell’eterogeneità e della dipendenza.</p>
<section id="guida-rapida-quale-distribuzione-usare" class="level3" data-number="11.9.3"><h3 data-number="11.9.3" class="anchored" data-anchor-id="guida-rapida-quale-distribuzione-usare">
<span class="header-section-number">11.9.3</span> Guida rapida: quale distribuzione usare?</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead><tr class="header">
<th>Distribuzione</th>
<th>Supporto</th>
<th>Domanda modellata</th>
<th>Esempio psicologico</th>
<th>Parametro principale</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>Uniforme discreta</td>
<td><span class="math inline">\(\{1,\ldots,N\}\)</span></td>
<td>Quale alternativa viene selezionata se il modello le tratta simmetricamente?</td>
<td>Assegnazione casuale indipendente a condizioni</td>
<td><span class="math inline">\(N\)</span></td>
</tr>
<tr class="even">
<td>Bernoulli</td>
<td><span class="math inline">\(\{0,1\}\)</span></td>
<td>L’evento si verifica oppure no?</td>
<td>Risposta corretta a un item</td>
<td><span class="math inline">\(p\)</span></td>
</tr>
<tr class="odd">
<td>Binomiale</td>
<td><span class="math inline">\(\{0,\ldots,n\}\)</span></td>
<td>Quanti successi si osservano in <span class="math inline">\(n\)</span> prove <em>iid</em>?</td>
<td>Numero di item corretti sotto probabilità costante</td>
<td><span class="math inline">\(n,p\)</span></td>
</tr>
<tr class="even">
<td>Beta-binomiale</td>
<td><span class="math inline">\(\{0,\ldots,n\}\)</span></td>
<td>Quanti successi si osservano in <span class="math inline">\(n\)</span> prove, se la probabilità di successo varia tra unità o è incerta?</td>
<td>Numero di parole ricordate da studenti con capacità diverse</td>
<td>
<span class="math inline">\(n,\alpha,\beta\)</span> oppure <span class="math inline">\(n,m,\kappa\)</span>
</td>
</tr>
<tr class="odd">
<td>Poisson</td>
<td><span class="math inline">\(\{0,1,2,\ldots\}\)</span></td>
<td>Quanti eventi si osservano in un intervallo con tasso stabile?</td>
<td>Numero di episodi riportati in un periodo</td>
<td><span class="math inline">\(\lambda\)</span></td>
</tr>
</tbody>
</table></section></section><section id="esercizi" class="level2 unnumbered unlisted"><h2 class="unnumbered unlisted anchored" data-anchor-id="esercizi">Esercizi</h2>
<ol type="1">
<li><p>Una variabile registra la presenza o l’assenza di un comportamento. Qual è il suo supporto e quale famiglia semplice può descrivere una singola osservazione?</p></li>
<li><p>Qual è la differenza tra modellare ogni risposta a un test con una Bernoulli e modellare il numero totale di risposte corrette con una binomiale?</p></li>
<li><p>Per una binomiale, che cosa restituiscono rispettivamente <code>dbinom(7, ...)</code> e <code>pbinom(7, ...)</code>?</p></li>
<li><p>In una distribuzione uniforme discreta su quattro condizioni, ciascuna condizione ha probabilità <span class="math inline">\(1/4\)</span>. Perché in 40 assegnazioni non è necessario osservare esattamente 10 persone per condizione?</p></li>
<li><p>Un test contiene item con difficoltà molto diverse. Quale assunzione del modello binomiale diventa poco plausibile?</p></li>
<li><p>In un modello di Poisson, che cosa significa affermare che <span class="math inline">\(\lambda=2{,}5\)</span> eventi al mese? Come cambia il numero atteso di eventi se l’osservazione dura due mesi?</p></li>
<li><p>Un insieme di conteggi ha media e varianza molto simili. Questo dimostra che una Poisson è il modello corretto? Spiega.</p></li>
<li><p>Una beta-binomiale è più dispersa di una binomiale con la stessa probabilità media. Quale fonte aggiuntiva di variabilità rappresenta?</p></li>
<li><p>Che cosa accade a una <span class="math inline">\(\mathrm{BetaBinomiale}(n,\alpha,\beta)\)</span> quando la concentrazione <span class="math inline">\(\kappa=\alpha+\beta\)</span> diventa molto grande? E quando <span class="math inline">\(\alpha=\beta=1\)</span>?</p></li>
<li><p>Un test ha 10 item. La probabilità di risposta corretta varia tra partecipanti secondo una distribuzione Beta con media <span class="math inline">\(m=0{,}6\)</span> e concentrazione <span class="math inline">\(\kappa=3\)</span>. Calcola la varianza del punteggio totale e confrontala con quella di una binomiale con <span class="math inline">\(p=0{,}6\)</span>.</p></li>
<li><p>In quale dei due scenari seguenti la beta-binomiale rappresenta eterogeneità e in quale incertezza epistemica? (a) La distribuzione dei punteggi in una classe di studenti con capacità diverse. (b) La previsione del numero di successi di una singola persona in 10 nuove prove, dopo averne osservate 10.</p></li>
<li><p>Perché, con una sola prova binaria per partecipante, non è possibile rilevare differenze tra partecipanti nella probabilità di successo?</p></li>
</ol>
<div class="callout callout-style-default callout-tip callout-titled" title="Soluzioni">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-14-contents" aria-controls="callout-14" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Consiglio</span>Soluzioni
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-14" class="callout-14-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li><p>Il supporto è <span class="math inline">\(\{0,1\}\)</span>, dopo avere scelto una codifica per assenza e presenza. Una singola osservazione può essere descritta da una Bernoulli con parametro <span class="math inline">\(p\)</span>, probabilità dell’esito codificato come 1.</p></li>
<li><p>La Bernoulli descrive una singola risposta binaria. La binomiale descrive il numero totale di successi in <span class="math inline">\(n\)</span> prove, assumendo che le prove siano condizionatamente indipendenti e condividano la stessa probabilità <span class="math inline">\(p\)</span>.</p></li>
<li><p><code>dbinom(7, ...)</code> restituisce la probabilità di osservare esattamente 7 successi. <code>pbinom(7, ...)</code> restituisce la probabilità cumulata di osservarne al massimo 7.</p></li>
<li><p>L’equiprobabilità riguarda il meccanismo generativo, non le frequenze esatte in un campione finito. Le frequenze osservate oscillano casualmente intorno ai valori attesi. Un’assegnazione perfettamente bilanciata richiederebbe un vincolo aggiuntivo nel disegno.</p></li>
<li><p>Diventa poco plausibile l’ipotesi di una probabilità di successo costante per tutte le prove. Item di diversa difficoltà possono richiedere probabilità differenti o un modello che rappresenti esplicitamente tali differenze.</p></li>
<li><p>Il numero medio atteso è 2,5 eventi per mese. Se il tasso resta stabile e l’esposizione raddoppia, il numero atteso in due mesi è <span class="math inline">\(2{,}5\times2=5\)</span>.</p></li>
<li><p>No.&nbsp;L’equidispersione è una conseguenza necessaria della Poisson, ma non è sufficiente a identificarla. Occorre controllare anche forma della distribuzione, zeri, dipendenza, stabilità del tasso ed eterogeneità.</p></li>
<li><p>Rappresenta l’incertezza o l’eterogeneità nella probabilità <span class="math inline">\(p\)</span>. La predizione integra più valori possibili di <span class="math inline">\(p\)</span>, invece di assumere un unico valore fissato per tutte le unità.</p></li>
<li><p>Quando <span class="math inline">\(\kappa\)</span> è molto grande, le probabilità individuali si concentrano attorno a <span class="math inline">\(m\)</span>, il fattore <span class="math inline">\((\kappa+n)/(\kappa+1)\)</span> tende a 1 e la beta-binomiale tende alla <span class="math inline">\(\mathrm{Binomiale}(n,m)\)</span>. Con <span class="math inline">\(\alpha=\beta=1\)</span> la Beta è uniforme e la beta-binomiale assegna probabilità <span class="math inline">\(1/(n+1)\)</span> a ciascun conteggio: è l’uniforme discreta su <span class="math inline">\(\{0,\ldots,n\}\)</span>.</p></li>
<li><p>La varianza binomiale è <span class="math inline">\(10\times0{,}6\times0{,}4=2{,}4\)</span>. Il fattore di inflazione è <span class="math inline">\((3+10)/(3+1)=3{,}25\)</span>, quindi la varianza beta-binomiale è <span class="math inline">\(2{,}4\times3{,}25=7{,}8\)</span>, con deviazione standard di circa 2,79 contro 1,55.</p></li>
<li><ol type="a">
<li>Eterogeneità: la Beta descrive differenze reali tra studenti, che non si riducono osservando più studenti. (b) Incertezza epistemica: la persona ha un’unica probabilità, non nota; la Beta è la distribuzione a posteriori e la beta-binomiale è la distribuzione predittiva a posteriori, che si avvicina a una binomiale al crescere dei dati.</li>
</ol></li>
<li><p>Con <span class="math inline">\(n=1\)</span> il fattore di inflazione vale 1 e la beta-binomiale coincide con una Bernoulli di parametro <span class="math inline">\(m\)</span>. La distribuzione dei dati dipende soltanto dalla probabilità media, e qualunque distribuzione delle probabilità individuali con la stessa media produce gli stessi dati. Per rilevare l’eterogeneità servono più prove per ciascuna unità.</p></li>
</ol>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Punti chiave">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-15-contents" aria-controls="callout-15" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Punti chiave
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-15" class="callout-15-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li>Una distribuzione discreta assegna probabilità a valori finiti o numerabili; la somma delle masse è uguale a 1.</li>
<li>Il supporto descrive i valori ammessi, ma non basta da solo a scegliere una famiglia.</li>
<li>Le funzioni <code>d</code>, <code>p</code>, <code>q</code> e <code>r</code> di R restituiscono rispettivamente massa o densità, probabilità cumulata, quantile e simulazioni.</li>
<li>L’uniforme discreta tratta simmetricamente le alternative; questa simmetria è un’assunzione da giustificare.</li>
<li>La Bernoulli descrive un singolo esito binario con probabilità <span class="math inline">\(p\)</span>.</li>
<li>La binomiale descrive un conteggio di successi quando le prove sono <em>iid</em> Bernoulli condizionatamente a <span class="math inline">\(p\)</span>.</li>
<li>La varianza della proporzione campionaria è <span class="math inline">\(p(1-p)/n\)</span>: campioni più grandi producono proporzioni più concentrate.</li>
<li>La Poisson è un possibile modello per conteggi con tasso stabile ed equidispersione; media e varianza simili non ne dimostrano da sole l’adeguatezza.</li>
<li>Esposizioni diverse richiedono di modellare il numero atteso come tasso per esposizione.</li>
<li>La beta-binomiale descrive un conteggio di successi quando la probabilità varia tra unità secondo una Beta; ha la stessa media della binomiale con <span class="math inline">\(p=m\)</span> e varianza moltiplicata per <span class="math inline">\((\kappa+n)/(\kappa+1)\)</span>.</li>
<li>La sovradispersione deriva dalla varianza delle probabilità individuali; eterogeneità tra unità e dipendenza tra le prove di una stessa unità sono due aspetti dello stesso fenomeno.</li>
<li>La stessa beta-binomiale descrive eterogeneità tra unità oppure, come distribuzione predittiva, incertezza su un’unica probabilità.</li>
<li>Sovradispersione, eccesso di zeri, eterogeneità o dipendenza possono richiedere modelli più flessibili.</li>
<li>Nel quadro bayesiano, la stessa famiglia può contribuire al modello dei dati, alla verosimiglianza o alla distribuzione predittiva.</li>
</ul>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Ambiente di sviluppo">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-16-contents" aria-controls="callout-16" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Ambiente di sviluppo
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-16" class="callout-16-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell" data-layout-align="center">
<details open="" class="code-fold"><summary>Mostra/Nascondi codice</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb22"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/utils/sessionInfo.html">sessionInfo</a></span><span class="op">(</span><span class="op">)</span></span>
<span><span class="co">#&gt; R version 4.6.1 (2026-06-24)</span></span>
<span><span class="co">#&gt; Platform: aarch64-apple-darwin23</span></span>
<span><span class="co">#&gt; Running under: macOS Golden Gate 27.0</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Matrix products: default</span></span>
<span><span class="co">#&gt; BLAS:   /Library/Frameworks/R.framework/Versions/4.6/Resources/lib/libRblas.0.dylib </span></span>
<span><span class="co">#&gt; LAPACK: /Library/Frameworks/R.framework/Versions/4.6/Resources/lib/libRlapack.dylib;  LAPACK version 3.12.1</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; locale:</span></span>
<span><span class="co">#&gt; [1] C.UTF-8/UTF-8/C.UTF-8/C/C.UTF-8/C.UTF-8</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; time zone: Europe/Rome</span></span>
<span><span class="co">#&gt; tzcode source: internal</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; attached base packages:</span></span>
<span><span class="co">#&gt; [1] stats     graphics  grDevices utils     datasets  methods  </span></span>
<span><span class="co">#&gt; [7] base     </span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; other attached packages:</span></span>
<span><span class="co">#&gt;  [1] ragg_1.5.2            tinytable_0.18.0     </span></span>
<span><span class="co">#&gt;  [3] withr_3.0.3           systemfonts_1.3.2    </span></span>
<span><span class="co">#&gt;  [5] patchwork_1.3.2       ggdist_3.3.3         </span></span>
<span><span class="co">#&gt;  [7] tidybayes_3.0.7       bayesplot_1.16.0     </span></span>
<span><span class="co">#&gt;  [9] ggplot2_4.0.3         reliabilitydiag_0.2.1</span></span>
<span><span class="co">#&gt; [11] priorsense_1.2.0      posterior_1.7.0      </span></span>
<span><span class="co">#&gt; [13] loo_2.10.1            rstan_2.32.7         </span></span>
<span><span class="co">#&gt; [15] StanHeaders_2.39.1    brms_2.23.1          </span></span>
<span><span class="co">#&gt; [17] Rcpp_1.1.2            sessioninfo_1.2.4    </span></span>
<span><span class="co">#&gt; [19] conflicted_1.2.0      janitor_2.2.1        </span></span>
<span><span class="co">#&gt; [21] matrixStats_1.5.0     modelr_0.1.11        </span></span>
<span><span class="co">#&gt; [23] tibble_3.3.1          dplyr_1.2.1          </span></span>
<span><span class="co">#&gt; [25] tidyr_1.3.2           rio_1.3.0            </span></span>
<span><span class="co">#&gt; [27] here_1.0.2           </span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; loaded via a namespace (and not attached):</span></span>
<span><span class="co">#&gt;  [1] svUnit_1.0.8         tidyselect_1.2.1     farver_2.1.2        </span></span>
<span><span class="co">#&gt;  [4] S7_0.2.2             fastmap_1.2.0        tensorA_0.36.2.1    </span></span>
<span><span class="co">#&gt;  [7] digest_0.6.39        timechange_0.4.0     estimability_2.0.0  </span></span>
<span><span class="co">#&gt; [10] lifecycle_1.0.5      magrittr_2.0.5       compiler_4.6.1      </span></span>
<span><span class="co">#&gt; [13] rlang_1.3.0          tools_4.6.1          yaml_2.3.12         </span></span>
<span><span class="co">#&gt; [16] knitr_1.51           labeling_0.4.3       bridgesampling_1.2-1</span></span>
<span><span class="co">#&gt; [19] htmlwidgets_1.6.4    pkgbuild_1.4.8       curl_8.0.0          </span></span>
<span><span class="co">#&gt; [22] RColorBrewer_1.1-3   abind_1.4-8          purrr_1.2.2         </span></span>
<span><span class="co">#&gt; [25] grid_4.6.1           stats4_4.6.1         xtable_1.8-8        </span></span>
<span><span class="co">#&gt; [28] inline_0.3.21        emmeans_2.0.4        scales_1.4.0        </span></span>
<span><span class="co">#&gt; [31] cli_3.6.6            mvtnorm_1.4-2        rmarkdown_2.32      </span></span>
<span><span class="co">#&gt; [34] generics_0.1.4       otel_0.2.0           RcppParallel_6.2.1  </span></span>
<span><span class="co">#&gt; [37] cachem_1.1.0         stringr_1.6.0        parallel_4.6.1      </span></span>
<span><span class="co">#&gt; [40] vctrs_0.7.3          V8_8.2.0             Matrix_1.7-6        </span></span>
<span><span class="co">#&gt; [43] jsonlite_2.0.0       arrayhelpers_1.1-2   glue_1.8.1          </span></span>
<span><span class="co">#&gt; [46] codetools_0.2-20     distributional_0.8.1 lubridate_1.9.5     </span></span>
<span><span class="co">#&gt; [49] stringi_1.8.9        gtable_0.3.6         QuickJSR_1.11.0     </span></span>
<span><span class="co">#&gt; [52] pillar_1.11.1        htmltools_0.5.9      Brobdingnag_1.2-9   </span></span>
<span><span class="co">#&gt; [55] R6_2.6.1             textshaping_1.0.5    rprojroot_2.1.1     </span></span>
<span><span class="co">#&gt; [58] evaluate_1.0.5       lattice_0.23-1       backports_1.5.1     </span></span>
<span><span class="co">#&gt; [61] memoise_2.0.1        broom_1.0.13         snakecase_0.11.1    </span></span>
<span><span class="co">#&gt; [64] rstantools_2.7.1     coda_0.19-4.1        gridExtra_2.3.1     </span></span>
<span><span class="co">#&gt; [67] nlme_3.1-171         checkmate_2.3.4      xfun_0.60           </span></span>
<span><span class="co">#&gt; [70] pkgconfig_2.0.3</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</div>
</div>
</div>


</section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiato!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiato!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const cellDetails = window.document.querySelectorAll(".cell details.code-fold");
        for (let i=0; i<cellDetails.length; i++) {
          const details = cellDetails[i];
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell div.sourceCode.cell-code");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("^(?:https?:)?//ccaudek\.github\.io/utet-prob/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
            // default icon
            link.classList.add("external");
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="../../chapters/probability/10_intro_distributions.html" class="pagination-link" aria-label="Introduzione alle distribuzioni di probabilità">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Introduzione alle distribuzioni di probabilità</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../../chapters/probability/12_cont_rv_distr.html" class="pagination-link" aria-label="Distribuzioni di variabili casuali continue">
        <span class="nav-page-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Distribuzioni di variabili casuali continue</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
    <div class="nav-footer-left">
<p><strong>Probabilità per la psicologia</strong><br>
Materiali digitali del progetto UTET a supporto del manuale <em>Inferenza bayesiana in psicologia: Ragionare con l’incertezza</em>.</p>
</div>   
    <div class="nav-footer-center">

<div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/ccaudek/utet-prob/issues/new" class="toc-action"><i class="bi bi-github"></i>Segnala un problema</a></li></ul></div><div class="cookie-consent-footer"><a href="#" id="open_preferences_center">Preferenze cookie</a></div></div>
    <div class="nav-footer-right">
<p><a href="https://ccaudek.github.io/utet-companion/">Companion principale</a> · <a href="https://github.com/ccaudek/utet-prob/">Repository</a> · <a href="https://creativecommons.org/licenses/by-nc-nd/4.0/deed.it">Licenza</a></p>
</div>
  </div>
</footer><script>var lightboxQuarto = GLightbox({"closeEffect":"zoom","descPosition":"bottom","loop":false,"openEffect":"zoom","selector":".lightbox"});
(function() {
  let previousOnload = window.onload;
  window.onload = () => {
    if (previousOnload) {
      previousOnload();
    }
    lightboxQuarto.on('slide_before_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      const href = trigger.getAttribute('href');
      if (href !== null) {
        const imgEl = window.document.querySelector(`a[href="${href}"] img`);
        if (imgEl !== null) {
          const srcAttr = imgEl.getAttribute("src");
          if (srcAttr && srcAttr.startsWith("data:")) {
            slideConfig.href = srcAttr;
          }
        }
      } 
    });
  
    lightboxQuarto.on('slide_after_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(slideNode);
      }
    });
  
  };
  
})();
          </script>


<script src="../../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>