{
  "hash": "38ac2d6889f9ae96b8395b078710e48d",
  "result": {
    "engine": "knitr",
    "markdown": "# Dal dato all'ipotesi: l'evidenza e l'aggiornamento delle credenze {#sec-prob-inference-uncertainty}\n\n## Introduzione {.unnumbered .unlisted}\n\nNella ricerca psicologica ci si trova costantemente di fronte all'incertezza. Desideriamo comprendere fenomeni complessi, come la prevalenza di un disturbo d'ansia, l'efficacia di un trattamento terapeutico o la relazione tra stress e prestazione cognitiva, ma non abbiamo mai accesso a informazioni complete. I dati che raccogliamo sono limitati: osserviamo un numero finito di partecipanti in contesti specifici utilizzando strumenti di misurazione imperfetti.\n\nCome possiamo quantificare l'incertezza sulle quantità di interesse a partire da queste osservazioni parziali? Come possiamo esprimere, in termini probabilistici, la nostra sicurezza che la prevalenza di un disturbo rientri in un certo intervallo o che un trattamento sia efficace?\n\nQuesto capitolo affronta le domande fondamentali dell'inferenza statistica. L'approccio che adotteremo considera i parametri, come proporzioni, medie e varianze, come oggetti rispetto ai quali abbiamo *incertezza epistemica*, quantificabile attraverso distribuzioni di probabilità. Prima di raccogliere i dati, esprimiamo le nostre conoscenze preliminari attraverso una distribuzione *a priori*. Dopo aver osservato i dati, aggiorniamo tale distribuzione ottenendo una distribuzione *a posteriori*. Questo processo di aggiornamento razionale delle credenze alla luce dell'evidenza è alla base dell'inferenza bayesiana.\n\n## Due tipi di incertezza\n\nÈ utile distinguere due forme di incertezza che incontriamo nell'analisi dei dati:\n\n1. **Incertezza epistemica** (dal greco *episteme*, conoscenza): riguarda la nostra limitata conoscenza dei parametri del fenomeno studiato. Non conosciamo con esattezza la proporzione di persone affette da un certo disturbo o il valore medio di un punteggio in una popolazione. Questa incertezza può essere ridotta raccogliendo più dati.\n\n2. **Incertezza aleatoria**: riguarda la variabilità intrinseca dei fenomeni osservati. Anche conoscendo perfettamente tutti i parametri di una distribuzione, le singole osservazioni future rimarrebbero imprevedibili. Ad esempio, anche conoscendo il QI medio (100) e la deviazione standard (15), non è possibile prevedere con esattezza il QI della prossima persona sottoposta al test.\n\nIn questo capitolo ci concentreremo principalmente sull'*incertezza epistemica*, ovvero quella relativa ai parametri, e su come essa venga ridotta dalle osservazioni empiriche.\n\n### Un esempio concreto: stima della prevalenza di sintomi depressivi\n\nSupponiamo di voler determinare la prevalenza di sintomi depressivi clinicamente significativi nella popolazione studentesca universitaria. Poiché non è possibile valutare l'intera popolazione, adottiamo la seguente procedura:\n\n1. reclutiamo un campione di 200 studenti tramite campionamento probabilistico;\n2. rileviamo che 72 partecipanti presentano sintomi depressivi clinicamente significativi;\n3. ci proponiamo di quantificare l'incertezza relativa al parametro $\\theta$, che rappresenta la prevalenza nella popolazione di riferimento.\n\nCome procedere? Prima della raccolta dei dati, possiamo esprimere le nostre conoscenze preliminari su $\\theta$ attraverso una distribuzione a priori. Dopo aver osservato i dati (72 casi su 200), aggiorniamo tale distribuzione mediante il teorema di Bayes, ottenendo una distribuzione a posteriori. Da questa distribuzione ricaviamo un intervallo di credibilità al 95% (ad esempio [0.29; 0.43]), la cui interpretazione è immediata: \"sulla base dei risultati osservati, riteniamo che esista una probabilità del 95% che il vero valore del parametro $\\theta$ si collochi tra 0.29 e 0.43\".\n\nQuesta interpretazione probabilistica diretta è perfettamente in linea con il modo in cui i ricercatori concepiscono l'incertezza nei processi inferenziali e fornisce una risposta alla domanda di ricerca che ha motivato lo studio.\n\n### Panoramica del capitolo {.unnumbered .unlisted}\n\nIn questo capitolo esploreremo:\n\n- le proprietà matematiche fondamentali che governano come i dati riducono l'incertezza;\n- come quantificare l'incertezza sui parametri usando distribuzioni di probabilità;\n- il ruolo della quantità di dati nel determinare la precisione delle nostre inferenze;\n- la convergenza della nostra conoscenza verso la \"realtà\" al crescere delle osservazioni;\n- i limiti dell'inferenza statistica.\n\n::: {.callout-tip collapse=true}\n## Prerequisiti\n\n- Leggere il capitolo *Sampling Distributions of Estimators* [@schervish2014probability].\n:::\n\n::: {.callout-caution collapse=true title=\"Preparazione del Notebook\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhere::here(\"code\", \"_common.R\") |> \n  source()\n```\n:::\n\n:::\n\n\n## Dati, parametri e incertezza\n\n### Dati osservati e parametro di interesse\n\nSupponiamo di voler indagare la prevalenza di un sintomo d'ansia specifico all'interno della popolazione studentesca universitaria. L'obiettivo ideale sarebbe determinare con esattezza la proporzione $\\theta$ di studenti che manifestano il sintomo. Tuttavia, l'osservazione completa della popolazione è impraticabile, costringendoci a una strategia indiretta:\n\n1. selezioniamo un campione rappresentativo di $n$ studenti;\n2. per ciascun partecipante, registriamo la presenza o l'assenza del sintomo attraverso una codifica binaria;\n3. sfruttiamo queste osservazioni campionarie per costruire un'inferenza probabilistica su $\\theta$.\n\nFormalizziamo le osservazioni mediante le variabili aleatorie $X_1, X_2, \\ldots, X_n$, dove ciascuna $X_i$ assume il valore:\n\n$$\nX_i = \n\\begin{cases}\n1 & \\text{se lo studente } i \\text{ presenta il sintomo} \\\\\n0 & \\text{in caso contrario}\n\\end{cases}\n$$\n\nQuesta rappresentazione ci permette di modellare matematicamente il processo di raccolta dei dati e di quantificare rigorosamente l'incertezza associata alla stima del parametro di interesse.\n\n### Dalla statistica descrittiva all'inferenza probabilistica\n\nLa proporzione campionaria fornisce una sintesi descrittiva dei dati osservati:\n\n$$\n\\bar{X} = \\frac{1}{n}\\sum_{i=1}^n X_i = \\frac{\\text{numero di studenti con sintomo}}{n}.\n$$\n\nTuttavia, l'obiettivo scientifico va oltre la mera descrizione campionaria: desideriamo utilizzare $\\bar{X}$ per fare inferenza sul parametro $\\theta$, che rappresenta la proporzione vera nella popolazione di riferimento.\n\nLa questione fondamentale è: in che modo il valore osservato di $\\bar{X}$ dovrebbe modificare la nostra incertezza riguardo a $\\theta$?\n\n### Il modello probabilistico di riferimento\n\nPer rispondere a questa domanda, costruiamo un modello probabilistico che metta in relazione:\n\n1. le osservazioni empiriche $X_1, \\ldots, X_n$;\n2. il parametro di interesse $\\theta$, soggetto a incertezza epistemica;\n3. la conoscenza pregressa disponibile prima della raccolta dei dati.\n\nAssumiamo che, condizionatamente al parametro $\\theta$, ciascuna osservazione segua una distribuzione di Bernoulli:\n\n$$\nX_i \\mid \\theta \\sim \\text{Bernoulli}(\\theta)\n$$\n\nQuesta assunzione implica che, se il valore di $\\theta$ fosse noto, la probabilità di osservare il sintomo in uno studente qualsiasi sarebbe esattamente $\\theta$.\n\n::: {.callout-note}\n### Notazione condizionale e sua interpretazione\n\nLa notazione $X_i \\mid \\theta$ indica che stiamo considerando la distribuzione della variabile $X_i$ nell'ipotesi che il parametro $\\theta$ sia fissato a un valore specifico. Questa formulazione non presuppone la conoscenza effettiva del valore di $\\theta$, ma piuttosto struttura il nostro ragionamento ipotetico: \"se il valore di $\\theta$ fosse questo, allora le nostre osservazioni si comporterebbero in questo modo\".\n:::\n\n## Proprietà fondamentali della media campionaria\n\nPrima di procedere con l'inferenza bayesiana, è utile comprendere alcune proprietà matematiche della media campionaria $\\bar{X}$ che valgono indipendentemente dal framework inferenziale adottato. Queste proprietà ci dicono come $\\bar{X}$ si comporta in relazione al parametro $\\theta$ e spiegano *perché* i dati sono informativi.\n\n### Valore atteso della media campionaria\n\nSupponiamo di avere osservazioni $X_1, X_2, \\ldots, X_n$ **indipendenti e identicamente distribuite** (i.i.d.), ciascuna con valore atteso $\\mathbb{E}[X_i \\mid \\theta] = \\theta$.\n\n::: {#thm-expval-sample-mean}\nIl valore atteso della media campionaria è:\n\n$$\n\\mathbb{E}[\\bar{X} \\mid \\theta] = \\theta.\n$$\n:::\n\n::: {.proof}\nPartendo dalla definizione di media campionaria:\n\n$$\n\\bar{X} = \\frac{1}{n}\\sum_{i=1}^n X_i,\n$$\n\ncalcoliamo il valore atteso:\n\n$$\n\\mathbb{E}[\\bar{X} \\mid \\theta] = \\mathbb{E}\\left[\\frac{1}{n}\\sum_{i=1}^n X_i \\bigg| \\theta\\right].\n$$\n\nPer la linearità del valore atteso:\n\n$$\n= \\frac{1}{n}\\sum_{i=1}^n \\mathbb{E}[X_i \\mid \\theta].\n$$\n\nPoiché tutte le $X_i$ sono identicamente distribuite con $\\mathbb{E}[X_i \\mid \\theta] = \\theta$:\n\n$$\n= \\frac{1}{n} \\cdot n\\theta = \\theta.\n$$\n:::\n\n**Interpretazione**: questo risultato ci dice che la media campionaria è *centrata* sul valore del parametro. Non presenta un bias sistematico né verso l'alto né verso il basso. Questa proprietà è fondamentale per giustificare l'uso di $\\bar{X}$ come base per fare inferenza su $\\theta$: nel framework bayesiano, implica che la distribuzione predittiva della media campionaria sarà centrata sul valore atteso a priori di $\\theta$.\n\n### Varianza della media campionaria\n\nLa seconda proprietà fondamentale riguarda la *variabilità* di $\\bar{X}$.\n\n::: {#thm-var-sample-mean}\nSe le osservazioni sono indipendenti con varianza $\\text{Var}(X_i \\mid \\theta) = \\sigma^2$, allora:\n\n$$\n\\text{Var}(\\bar{X} \\mid \\theta) = \\frac{\\sigma^2}{n}.\n$$\n:::\n\n::: {.proof}\nPartiamo dalla varianza della media campionaria:\n\n$$\n\\text{Var}(\\bar{X} \\mid \\theta) = \\text{Var}\\left(\\frac{1}{n}\\sum_{i=1}^n X_i \\bigg| \\theta\\right).\n$$\n\nUsando la proprietà $\\text{Var}(aY) = a^2\\text{Var}(Y)$:\n\n$$\n= \\frac{1}{n^2}\\text{Var}\\left(\\sum_{i=1}^n X_i \\bigg| \\theta\\right).\n$$\n\nPer l'indipendenza, la varianza della somma è la somma delle varianze:\n\n$$\n= \\frac{1}{n^2}\\sum_{i=1}^n \\text{Var}(X_i \\mid \\theta) = \\frac{1}{n^2} \\cdot n\\sigma^2 = \\frac{\\sigma^2}{n}.\n$$\n:::\n\n**Interpretazione**: questo risultato mostra che la variabilità di $\\bar{X}$ diminuisce con $n$. Più dati vengono raccolti, più $\\bar{X}$ diventa \"stabile\" e informativo su $\\theta$. La varianza diminuisce proporzionalmente a $1/n$, quindi:\n\n- con $n=100$ dati, la varianza di $\\bar{X}$ è 1/100 della varianza delle singole osservazioni;\n- per dimezzare la deviazione standard di $\\bar{X}$, è necessario quadruplicare $n$.\n\nQuesta proprietà spiega *perché* la distribuzione a posteriori diventa più concentrata con l'aumentare dei dati: i dati forniscono informazioni sempre più precise su $\\theta$.\n\n### Il caso delle variabili Bernoulliane\n\nConsideriamo un esperimento o un'osservazione binaria, codificata da una variabile aleatoria $X_i$ che assume valore 1 in caso di \"successo\" (es., presenza di un sintomo) e 0 in caso di \"insuccesso\". La distribuzione di ciascuna $X_i$ è modellata da una distribuzione di **Bernoulli** con parametro $\\theta$, che rappresenta la probabilità di successo.\n\n**1. Variabilità di una singola osservazione.**\n\nLa variabilità intrinseca di una singola osservazione $X_i$ è data dalla sua varianza:\n$$\n\\text{Var}(X_i \\mid \\theta) = \\theta(1-\\theta).\n$$\nQuesta funzione, una parabola, è massima quando $\\theta = 0.5$ (massima incertezza) e si annulla quando $\\theta = 0$ o $\\theta = 1$ (nessuna variabilità).\n\n**2. Variabilità della media campionaria.**\n\nDato un campione di $n$ osservazioni indipendenti $X_1, \\dots, X_n$, la media campionaria $\\bar{X} = \\frac{1}{n} \\sum_{i=1}^n X_i$ rappresenta la proporzione di successi osservata.\n\nLa varianza di $\\bar{X}$, nota come **varianza campionaria**, è:\n$$\n\\text{Var}(\\bar{X} \\mid \\theta) = \\frac{\\text{Var}(X_i \\mid \\theta)}{n} = \\frac{\\theta(1-\\theta)}{n}.\n$$\nQuesto risultato mostra come la variabilità della media diminuisca all'aumentare della dimensione del campione $n$, secondo il fattore $1/n$.\n\n**3. L'errore standard e la sua interpretazione.**\n\nLa radice quadrata della varianza campionaria è detta **errore standard (SE)** di $\\bar{X}$:\n$$\n\\text{SE}(\\bar{X}) = \\sqrt{\\text{Var}(\\bar{X} \\mid \\theta)} = \\sqrt{\\frac{\\theta(1-\\theta)}{n}}.\n$$\n\nL'errore standard quantifica l'incertezza associata a $\\bar{X}$ come stimatore di $\\theta$. In altre parole, indica quanto ci si aspetta che la proporzione osservata $\\bar{X}$ vari da campione a campione a causa della casualità del campionamento.\n\nIn un'ottica bayesiana, l'errore standard assume un ruolo cruciale nel quantificare il contenuto informativo del dato. Un errore standard di grandezza ridotta, tipicamente associato a campioni di ampiezza elevata, segnala che le osservazioni sono in grado di fornire una stima precisa del parametro, conducendo a una distribuzione a posteriori fortemente concentrata. Al contrario, un errore standard ampio indica un'elevata incertezza campionaria, suggerendo che i dati, da soli, forniscono un'informazione meno definitiva sul parametro di interesse. Pertanto, questa statistica funge da ponte tra la variabilità del fenomeno e l'affidabilità inferenziale che è lecito attendersi dal campione osservato.\n\n## Comprendere la variabilità dei dati\n\n### Il concetto di distribuzione campionaria\n\nImmaginiamo di poter osservare molti campioni diversi provenienti dalla stessa popolazione, ciascuno di dimensione $n$. Per ognuno di essi calcoleremmo $\\bar{X}$, ottenendo valori diversi. La *distribuzione campionaria* di $\\bar{X}$ descrive come questi valori si distribuiscono.\n\nQuesto concetto teorico è molto utile per comprendere come i dati influenzino la distribuzione a posteriori. La distribuzione campionaria contribuisce alla funzione di verosimiglianza, che è il meccanismo formale attraverso cui i dati \"parlano\" nell'inferenza bayesiana: la verosimiglianza quantifica quanto bene ciascun possibile valore di $\\theta$ spiega i dati osservati.\n\n### Esempio concreto: una popolazione finita\n\nPer rendere tutto più concreto, consideriamo un caso semplice: una popolazione di soli 4 valori.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nx <- c(2, 4.5, 5, 5.5)\nx\n#> [1] 2.0 4.5 5.0 5.5\n```\n:::\n\n\nCalcoliamo media e varianza di questa popolazione:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmean_x <- mean(x)  # Media\nvar_x <- var(x) * ((length(x) - 1) / length(x))  # Varianza\ncat(\"Media:\", mean_x, \"\\n\")\n#> Media: 4.25\ncat(\"Varianza:\", var_x, \"\\n\")\n#> Varianza: 1.81\n```\n:::\n\n\nConsideriamo ora tutti i possibili campioni di dimensione $n$ = 2, estratti con reinserimento. Da una popolazione di 4 elementi, questo procedimento genera $4^2 = 16$ campioni possibili.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Generiamo tutte le coppie possibili\nsamples <- expand.grid(x, x)\nhead(samples, 10)\n#>    Var1 Var2\n#> 1   2.0  2.0\n#> 2   4.5  2.0\n#> 3   5.0  2.0\n#> 4   5.5  2.0\n#> 5   2.0  4.5\n#> 6   4.5  4.5\n#> 7   5.0  4.5\n#> 8   5.5  4.5\n#> 9   2.0  5.0\n#> 10  4.5  5.0\n```\n:::\n\n\nPer ogni coppia, calcoliamo la media:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsample_means <- rowMeans(samples)\nsample_means\n#>  [1] 2.00 3.25 3.50 3.75 3.25 4.50 4.75 5.00 3.50 4.75 5.00 5.25 3.75 5.00 5.25\n#> [16] 5.50\n```\n:::\n\n\nAl fine di una migliore organizzazione dei risultati, costruiamo un apposito data frame:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndf <- data.frame(\n  Campione = apply(samples, 1, paste, collapse = \", \"),\n  Media = sample_means\n)\nhead(df, 10)\n#>    Campione Media\n#> 1      2, 2  2.00\n#> 2    4.5, 2  3.25\n#> 3      5, 2  3.50\n#> 4    5.5, 2  3.75\n#> 5    2, 4.5  3.25\n#> 6  4.5, 4.5  4.50\n#> 7    5, 4.5  4.75\n#> 8  5.5, 4.5  5.00\n#> 9      2, 5  3.50\n#> 10   4.5, 5  4.75\n```\n:::\n\n\nLa distribuzione delle medie campionarie può essere visualizzata mediante il seguente istogramma:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot(data.frame(sample_means), aes(x = sample_means)) +\n  geom_histogram(\n    bins = 7,\n    aes(y = after_stat(density)),\n    fill = \"lightblue\",\n    color = \"black\"\n  ) +\n  labs(\n    title = \"Distribuzione campionaria della media (n=2)\",\n    x = \"Media campionaria\",\n    y = \"Densità\"\n  )\n```\n\n::: {.cell-output-display}\n![](09_dal_dato_ipotesi_files/figure-html/unnamed-chunk-7-1.png){fig-align='center' width=85%}\n:::\n:::\n\n\nVerifichiamo le proprietà teoriche:\n\n\n::: {.cell layout-align=\"center\"}\n\n```\n#> Media delle medie campionarie: 4.25\n#> Media della popolazione: 4.25\n#> Varianza delle medie campionarie: 0.906\n#> Varianza teorica (σ²/n): 0.906\n```\n:::\n\n\nI risultati empirici confermano le proprietà teoriche della distribuzione campionaria:\n\n- la media delle medie campionarie coincide esattamente con la media della popolazione;\n- la varianza delle medie campionarie corrisponde alla quantità teorica attesa di $\\sigma^2/n$.\n\n::: {.callout-note}\n### Interpretazione per l'inferenza\n\nQuesta simulazione mostra concretamente perché, se osserviamo $\\bar{X} = 4.75$, possiamo essere ragionevolmente sicuri che il parametro sottostante sia vicino a quel valore. I valori di $\\bar{X}$ tendono a concentrarsi intorno al valore del parametro vero, e tale concentrazione aumenta con $n$.\n\nCiò spiega perché la distribuzione a posteriori di $\\theta$ sarà centrata sul valore osservato di $\\bar{X}$, con una dispersione che dipende da $n$.\n:::\n\n## Legge dei Grandi Numeri {#sec-lln}\n\nLa *Legge dei Grandi Numeri* (LGN) è uno dei pilastri della teoria della probabilità e ha profonde implicazioni per l'inferenza statistica.\n\n### Enunciato intuitivo\n\nLa LGN afferma che, all'aumentare del numero di osservazioni $n$, la media campionaria $\\bar{X}_n$ converge al valore atteso $\\theta$:\n\n$$\n\\bar{X}_n \\xrightarrow{n \\to \\infty} \\theta.\n$$\n\nIn termini più precisi, esistono due forme:\n\n1. **Legge Debole**: $\\bar{X}_n$ converge a $\\theta$ *in probabilità*, cioè per ogni $\\varepsilon > 0$:\n   \n   $$\n   \\Pr\\bigl(|\\bar{X}_n - \\theta| > \\varepsilon \\mid \\theta\\bigr) \\to 0 \\quad \\text{quando } n \\to \\infty.\n   $$\n\n2. **Legge Forte**: $\\bar{X}_n$ converge a $\\theta$ *quasi certamente*, cioè:\n   \n   $$\n   \\Pr\\left(\\lim_{n \\to \\infty} \\bar{X}_n = \\theta \\; \\bigg| \\;\\theta\\right) = 1.\n   $$\n\n### Implicazioni per l'inferenza bayesiana\n\nLa LGN ha un'interpretazione diretta nel framework bayesiano: all'aumentare di $n$, la distribuzione a posteriori di $\\theta$ diventa sempre più concentrata attorno al valore vero, *indipendentemente dalla prior iniziale*, a condizione che questa assegni una massa positiva al valore vero.\n\nIn altre parole: **con sufficienti dati, anche credenze iniziali molto diverse convergono alla stessa conclusione**. Questo risultato è rassicurante e mostra la robustezza dell'inferenza bayesiana — l'evidenza empirica finisce sempre per prevalere sulle credenze a priori.\n\n### Simulazione della convergenza campionaria\n\nEsaminiamo un scenario in cui il parametro vero è $\\theta = 0.45$. Simuliamo campioni di dimensione crescente per osservare empiricamente il comportamento della media campionaria:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(42)\ntheta_true <- 0.45\nn_max <- 1000\n\n# Generazione delle osservazioni bernoulliane\nobservations <- rbinom(n_max, size = 1, prob = theta_true)\n\n# Calcolo delle medie cumulative\ncumulative_means <- cumsum(observations) / seq_along(observations)\n\n# Preparazione dei dati per la visualizzazione\ndata_plot <- data.frame(\n  n = 1:n_max,\n  mean = cumulative_means\n)\n\nggplot(data_plot, aes(x = n, y = mean)) +\n  geom_line(color = \"#4E79A7\", linewidth = 0.8, alpha = 0.8) +\n  geom_hline(yintercept = theta_true, \n             linetype = \"dashed\", \n             color = \"#E15759\",\n             linewidth = 1.2) +\n  geom_ribbon(aes(ymin = mean - 1.96 * sqrt(mean * (1 - mean) / n),\n                  ymax = mean + 1.96 * sqrt(mean * (1 - mean) / n)),\n              alpha = 0.2, fill = \"#4E79A7\") +\n  labs(\n    title = \"Convergenza della media campionaria verso il parametro vero\",\n    subtitle = \"Legge dei Grandi Numeri: stabilizzazione con l'aumentare delle osservazioni\",\n    x = \"Dimensione campionaria (n)\",\n    y = \"Media campionaria cumulativa\"\n  ) +\n  ylim(0.2, 0.7) +\n  theme_minimal() +\n  annotate(\"text\", x = 800, y = theta_true + 0.03, \n           label = paste(\"θ =\", theta_true), \n           color = \"#E15759\", size = 4.5)\n```\n\n::: {.cell-output-display}\n![](09_dal_dato_ipotesi_files/figure-html/unnamed-chunk-9-1.png){fig-align='center' width=85%}\n:::\n:::\n\n\n**Osservazioni empiriche**:\nnelle fasi iniziali del campionamento, la media campionaria $\\bar{X}_n$ presenta ampie e imprevedibili fluttuazioni, riflettendo l'elevata variabilità associata alle piccole dimensioni del campione. Man mano che le osservazioni si accumulano, l'ampiezza delle oscillazioni diminuisce in modo sistematico. Una volta raggiunti campioni sufficientemente ampi, la media campionaria si stabilizza in prossimità del valore parametrico vero.\n\n::: {.callout-important}\n### Il carattere auto-correttivo dell'inferenza bayesiana\n\nLa legge dei grandi numeri rivela una proprietà fondamentale: con un numero sufficiente di dati, l'evidenza empirica finisce per prevalere su qualsiasi credenza a priori ragionevole.\n\nQuando due ricercatori partono da convinzioni iniziali diverse, ma nessuna delle due esclude completamente il valore vero del parametro, e osservano la stessa serie di dati empirici, le loro distribuzioni a posteriori convergeranno progressivamente verso conclusioni sostanzialmente identiche.\n\nQuesto risultato ha un'importanza epistemologica notevole: dimostra che la metodologia bayesiana possiede un carattere intrinsecamente autocorrettivo. Gli eventuali errori contenuti nelle credenze iniziali vengono progressivamente attenuati e infine sovrascritti dall'accumularsi dell'evidenza sperimentale.\n:::\n\n### Applicazioni in psicologia\n\nLa Legge dei Grandi Numeri ha importanti implicazioni per la ricerca psicologica.\n\nGli *studi pilota*, caratterizzati da dimensioni campionarie ridotte, producono stime soggette a notevole variabilità. Ciò spiega perché le replicazioni con campioni più ampi tendono a generare risultati più stabili e affidabili.\n\nLe *meta-analisi* sfruttano implicitamente questo principio combinando le evidenze di molti studi, aumentando virtualmente la dimensione del campione complessivo e riducendo l'incertezza associata alla stima degli effetti.\n\nNei *disegni longitudinali*, l'osservazione ripetuta nel tempo degli stessi fenomeni permette di ridurre progressivamente l'incertezza riguardante le caratteristiche stabili dei costrutti indagati.\n\n## Teorema del Limite Centrale\n\nIl Teorema del Limite Centrale (TLC) costituisce uno dei pilastri concettuali più profondi della teoria della probabilità, con conseguenze metodologiche di ampia portata per l'inferenza statistica.\n\n### Enunciato formale\n\n::: {#thm-clt}\nSiano $X_1, X_2, \\ldots, X_n$ variabili aleatorie indipendenti e identicamente distribuite con valore atteso $\\mu$ e varianza $\\sigma^2$ finite. Allora, al crescere di $n$, la distribuzione della media campionaria $\\bar{X}_n$ converge verso una distribuzione normale:\n\n$$\n\\bar{X}_n \\;\\dot\\sim\\; \\mathcal{N}\\left(\\mu, \\frac{\\sigma^2}{n}\\right).\n$$\n\ndove la notazione $\\dot\\sim$ indica \"approssimativamente distribuito come\" per $n$ sufficientemente grande.\n:::\n\n### Portata concettuale\n\nLa proprietà notevole del TLC risiede nel fatto che la media di un numero elevato di variabili aleatorie indipendenti converge verso una distribuzione normale, *indipendentemente dalla forma della distribuzione sottostante delle variabili originarie*. Questo principio si manifesta in un'ampia gamma di situazioni probabilistiche, incluse variabili distribuite uniformemente, variabili governate da leggi esponenziali, variabili binarie dicotomiche e distribuzioni marcatamente asimmetriche. In tutti questi casi, la distribuzione della media campionaria tende sistematicamente verso la distribuzione normale.\n\n### Visualizzazione del TLC\n\nConsideriamo una popolazione con distribuzione uniforme (chiaramente non normale):\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(42)\npopulation <- runif(5000, min = 0, max = 1)\n\n# Istogramma della popolazione\nggplot(data.frame(population), aes(x = population)) +\n  geom_histogram(\n    aes(y = after_stat(density)),\n    bins = 30,\n    fill = \"lightblue\",\n    color = \"black\"\n  ) +\n  labs(\n    title = \"Distribuzione della popolazione (uniforme)\",\n    x = \"Valore\",\n    y = \"Densità\"\n  )\n```\n\n::: {.cell-output-display}\n![](09_dal_dato_ipotesi_files/figure-html/unnamed-chunk-10-1.png){fig-align='center' width=85%}\n:::\n:::\n\n\nOra estraiamo 300 campioni, ciascuno di dimensione $n=30$, e calcoliamo le medie:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsample_size <- 30\nnum_samples <- 300\n\nsample_means <- replicate(num_samples, {\n  sample_data <- sample(population, size = sample_size, replace = TRUE)\n  mean(sample_data)\n})\n\n# Media e deviazione standard delle medie campionarie\nx_bar <- mean(sample_means)\nstd <- sd(sample_means)\n\ncat(\"Media delle medie campionarie:\", x_bar, \"\\n\")\n#> Media delle medie campionarie: 0.501\ncat(\"Dev. standard delle medie:\", std, \"\\n\")\n#> Dev. standard delle medie: 0.0524\n```\n:::\n\n\nConfrontiamo con i valori teorici:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmu <- mean(population)\nsigma <- sd(population)\n\ncat(\"\\nValori teorici della popolazione:\\n\")\n#> \n#> Valori teorici della popolazione:\ncat(\"Media:\", mu, \"\\n\")\n#> Media: 0.503\ncat(\"Dev. standard delle medie (σ/√n):\", sigma / sqrt(sample_size), \"\\n\")\n#> Dev. standard delle medie (σ/√n): 0.0531\n```\n:::\n\n\nVisualizziamo la distribuzione delle medie campionarie con la curva normale teorica sovrapposta:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot(data.frame(sample_means), aes(x = sample_means)) +\n  geom_histogram(\n    aes(y = after_stat(density)),\n    bins = 30,\n    fill = \"lightblue\",\n    color = \"black\",\n    alpha = 0.7\n  ) +\n  stat_function(\n    fun = dnorm, \n    args = list(mean = x_bar, sd = std),\n    color = \"red\",\n    linewidth = 1.2\n  ) +\n  labs(\n    title = \"Distribuzione delle medie campionarie\",\n    subtitle = \"La curva rossa è la distribuzione normale teorica\",\n    x = \"Media campionaria\",\n    y = \"Densità\"\n  )\n```\n\n::: {.cell-output-display}\n![](09_dal_dato_ipotesi_files/figure-html/unnamed-chunk-13-1.png){fig-align='center' width=85%}\n:::\n:::\n\n\n**Osservazione**: nonostante la popolazione sia uniforme (non normale), la distribuzione delle medie è approssimativamente normale.\n\n### Implicazioni per l'inferenza bayesiana\n\nIl Teorema del Limite Centrale ha un'influenza profonda sulla pratica dell'inferenza bayesiana.\n\nIn contesti con ampi campioni, la distribuzione a posteriori tende a convergere verso una forma gaussiana, a prescindere dalla configurazione della distribuzione a priori, a condizione che quest'ultima sia sufficientemente regolare. Questa proprietà di regolarità asintotica conferisce robustezza al metodo bayesiano, attenuando l'impatto delle specifiche scelte dei *prior* quando si dispone di abbondante evidenza empirica.\n\nQuesto risultato giustifica l'uso di approssimazioni gaussiane per la distribuzione a posteriori in molte applicazioni pratiche, semplificando notevolmente i calcoli in situazioni in cui forme analitiche esatte risulterebbero complesse o intrattabili.\n\n### Esempio: approssimazione della distribuzione a posteriori\n\nConsideriamo un contesto di ricerca in psicologia clinica in cui si studia la prevalenza di un particolare sintomo. Supponiamo di adottare un prior uniforme per il parametro $\\theta$ e di osservare un campione di 100 soggetti, tra i quali 45 manifestano il sintomo.\n\nPer la dimensione del campione considerata, la distribuzione a posteriori può essere approssimata mediante una distribuzione normale:\n\n$$\n\\theta \\mid y \\;\\dot\\sim\\; \\mathcal{N}\\left(\\frac{45}{100}, \\frac{0.45 \\times 0.55}{100}\\right).\n$$\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Parametri osservati\nn <- 100\ny <- 45\np_hat <- y / n\n\n# Approssimazione normale della posteriore\nposterior_mean <- p_hat\nposterior_sd <- sqrt(p_hat * (1 - p_hat) / n)\n\ncat(\"Media a posteriori (approssimata):\", posterior_mean, \"\\n\")\n#> Media a posteriori (approssimata): 0.45\ncat(\"Deviazione standard a posteriori:\", round(posterior_sd, 4), \"\\n\")\n#> Deviazione standard a posteriori: 0.0497\n\n# Intervallo di credibilità al 95%\nlower <- qnorm(0.025, mean = posterior_mean, sd = posterior_sd)\nupper <- qnorm(0.975, mean = posterior_mean, sd = posterior_sd)\n\ncat(\"\\nIntervallo di credibilità 95%: [\", round(lower, 3), \",\", round(upper, 3), \"]\\n\")\n#> \n#> Intervallo di credibilità 95%: [ 0.352 , 0.548 ]\n```\n:::\n\n\nLa visualizzazione della distribuzione a posteriori approssimata:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ntheta_grid <- seq(0.25, 0.65, length.out = 1000)\nposterior_density <- dnorm(theta_grid, mean = posterior_mean, sd = posterior_sd)\n\nggplot(data.frame(theta = theta_grid, density = posterior_density), \n       aes(x = theta, y = density)) +\n  geom_line(linewidth = 1.2, color = \"#2E86AB\") +\n  geom_area(aes(x = theta, y = density), \n            data = subset(data.frame(theta = theta_grid, density = posterior_density),\n                         theta >= lower & theta <= upper),\n            fill = \"#A23B72\", alpha = 0.3) +\n  geom_vline(xintercept = c(lower, upper), \n             linetype = \"dashed\", \n             color = \"#F18F01\", size = 0.8) +\n  labs(\n    title = \"Distribuzione a posteriori (approssimazione normale)\",\n    subtitle = \"Intervallo di credibilità al 95% per la proporzione del sintomo\",\n    x = \"θ (proporzione nella popolazione)\",\n    y = \"Densità a posteriori\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](09_dal_dato_ipotesi_files/figure-html/unnamed-chunk-15-1.png){fig-align='center' width=85%}\n:::\n:::\n\n\n**Interpretazione dell'intervallo di credibilità.**\n\nL'intervallo [0.352, 0.548] può essere interpretato in modo probabilistico diretto: *alla luce dei dati osservati, c'è una probabilità del 95% che la vera proporzione nella popolazione si collochi tra il 35.2% e il 54.8%*. Questa interpretazione è intuitiva e coerente con il modo in cui i ricercatori concepiscono l'incertezza parametrica.\n\n## Precisione, informazione ed errore standard\n\n### L'errore standard come misura di informatività\n\nL'*errore standard* di una statistica rappresenta la deviazione standard della sua distribuzione campionaria. Nel caso della media campionaria:\n\n$$\n\\text{SE}(\\bar{X}) = \\sqrt{\\frac{\\sigma^2}{n}}.\n$$\n\nQuesta misura quantifica il grado di informazione contenuto nei dati riguardo al parametro di interesse. Un errore standard ridotto segnala che i dati forniscono un'evidenza precisa su $\\theta$, il che si traduce in una distribuzione a posteriori concentrata attorno alla stima. Al contrario, un errore standard ampio indica dati scarsamente informativi che si traducono in una distribuzione a posteriori più dispersa.\n\n### Precisione come inverso della varianza\n\nNell'ambito della statistica bayesiana, risulta particolarmente utile concettualizzare l'incertezza attraverso la nozione di *precisione*, definita come il reciproco della varianza:\n\n$$\n\\text{Precisione} = \\frac{1}{\\text{Varianza}}.\n$$\n\nApplicando questo concetto alla media campionaria:\n\n$$\n\\text{Precisione}(\\bar{X} \\mid \\theta) = \\frac{n}{\\sigma^2}.\n$$\n\nQuesta formulazione rivela una proprietà notevole: **la precisione cresce in proporzione diretta con la dimensione campionaria $n$**. Questa relazione lineare è più intuitiva dell'andamento corrispondente della varianza, che decresce secondo il fattore $1/n$.\n\nMolti modelli bayesiani adottano esplicitamente la precisione come parametro fondamentale. La distribuzione normale, per esempio, viene spesso parametrizzata nella forma $X \\sim \\mathcal{N}(\\mu, \\tau)$, dove $\\tau = 1/\\sigma^2$ rappresenta la precisione. Questa scelta parametrica evidenzia due principi fondamentali:\n\n- un valore di precisione elevato corrisponde a un grado di incertezza ridotto;\n- la combinazione di informazioni provenienti da fonti indipendenti si realizza attraverso la semplice **somma** delle rispettive precisioni.\n\n### Combinazione di informazioni: prior e dati\n\nUn aspetto particolarmente elegante del paradigma bayesiano risiede nella sua capacità di integrare in modo coerente e formale diverse fonti di informazione. In questo contesto, la conoscenza pregressa sul parametro di interesse è codificata nella distribuzione a priori, la cui incertezza è quantificata da una precisione $\\tau_0$. Parallelamente, l'informazione contenuta nei dati osservati è sintetizzata dalla verosimiglianza, la cui precisione, espressa come $n/\\sigma^2$, misura quantitativamente l'informatività dell'evidenza empirica.\n\nLa sintesi di queste due componenti avviene nella distribuzione a posteriori, la cui precisione $\\tau_{\\text{post}}$ è data dalla semplice somma:\n\n$$\n\\tau_{\\text{post}} = \\tau_0 + \\frac{n}{\\sigma^2}.\n$$\n\nQuesta relazione formalizza in modo trasparente il processo di accumulo della conoscenza: ogni nuova osservazione contribuisce ad aumentare la precisione complessiva della nostra inferenza, perfezionando progressivamente la nostra comprensione del fenomeno in esame. L'approccio bayesiano fornisce quindi un meccanismo matematicamente rigoroso per aggiornare le credenze, in cui il peso relativo attribuito alla conoscenza pregressa e ai nuovi dati è determinato esplicitamente dalle rispettive precisioni.\n\n#### Esempio: sintesi di evidenze da studi multipli\n\nSi consideri uno scenario comune nella ricerca psicologica, in cui due studi indipendenti investigano lo stesso costrutto teorico, denotato da $\\theta$, ma presentano dimensioni campionarie e livelli di precisione differenti.\n\n**Studio A**: $n_A = 50$, $\\bar{X}_A = 0.42$, $\\text{SE}_A = 0.07$.\n**Studio B**: $n_B = 200$, $\\bar{X}_B = 0.38$, $\\text{SE}_B = 0.035$.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Parametri degli studi\nn_A <- 50; x_bar_A <- 0.42; se_A <- 0.07\nn_B <- 200; x_bar_B <- 0.38; se_B <- 0.035\n\n# Calcolo delle precisioni\nprecision_A <- 1 / se_A^2\nprecision_B <- 1 / se_B^2\n\ncat(\"Precisione Studio A:\", round(precision_A, 2), \"\\n\")\n#> Precisione Studio A: 204\ncat(\"Precisione Studio B:\", round(precision_B, 2), \"\\n\")\n#> Precisione Studio B: 816\ncat(\"Rapporto di precisione B/A:\", round(precision_B / precision_A, 2), \"\\n\")\n#> Rapporto di precisione B/A: 4\n```\n:::\n\n\nL'analisi delle precisioni rivela che lo Studio B presenta un'incertezza approssimativamente quattro volte inferiore rispetto allo Studio A, risultato coerente con la sua dimensione campionaria quadruplicata.\n\nProcedendo con una sintesi bayesiana delle evidenze:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Combinazione delle informazioni\nprecision_combined <- precision_A + precision_B\nmean_combined <- (precision_A * x_bar_A + precision_B * x_bar_B) / precision_combined\nse_combined <- sqrt(1 / precision_combined)\n\ncat(\"Stima combinata:\", round(mean_combined, 3), \"\\n\")\n#> Stima combinata: 0.388\ncat(\"Errore standard combinato:\", round(se_combined, 4), \"\\n\")\n#> Errore standard combinato: 0.0313\ncat(\"\\nIntervallo di credibilità 95% per la sintesi:\\n\")\n#> \n#> Intervallo di credibilità 95% per la sintesi:\ncat(\"[\", round(mean_combined - 1.96*se_combined, 3), \",\",\n    round(mean_combined + 1.96*se_combined, 3), \"]\\n\")\n#> [ 0.327 , 0.449 ]\n```\n:::\n\n\nLa stima combinata risulta più prossima al valore osservato nello Studio B, riflettendo il maggiore contributo informativo di questo studio dovuto alla sua superiore precisione. L'approccio bayesiano attribuisce automaticamente un peso maggiore alle evidenze più affidabili, producendo una sintesi ottimale che integra coerentemente tutte le informazioni disponibili. \n\n## Convergenza bayesiana: da credenze diverse a conclusioni condivise\n\n### Il teorema di convergenza bayesiana\n\nUn risultato teorico fondamentale riguarda il comportamento asintotico della distribuzione a posteriori con l'aumentare della dimensione del campione.\n\n::: {#thm-bayesian-consistency}\n## Consistenza bayesiana\n\nSotto opportune condizioni di regolarità, se la distribuzione a priori assegna una densità positiva al valore vero del parametro $\\theta_0$, allora:\n\n1. la distribuzione a posteriori converge verso una distribuzione degenere concentrata in $\\theta_0$:\n   \n   $$\n   p(\\theta \\mid \\mathbf{X}_n) \\xrightarrow{n \\to \\infty} \\delta(\\theta - \\theta_0).\n   $$\n\n2. la media a posteriori converge al valore vero del parametro:\n   \n   $$\n   \\mathbb{E}[\\theta \\mid \\mathbf{X}_n] \\xrightarrow{n \\to \\infty} \\theta_0.\n   $$\n\n3. la varianza a posteriori tende asintoticamente a zero:\n   \n   $$\n   \\text{Var}(\\theta \\mid \\mathbf{X}_n) \\xrightarrow{n \\to \\infty} 0.\n   $$\n:::\n\n### Interpretazione sostantiva\n\nQuesto teorema rivela proprietà essenziali dell'inferenza bayesiana:\n\n1. **Robustezza asintotica alle specificazioni a priori**: in presenza di dati sufficienti, la scelta della distribuzione a priori perde progressivamente influenza, a condizione che non escluda completamente il valore vero del parametro.\n\n2. **Capacità auto-correttiva**: qualora le credenze iniziali si rivelino inadeguate, l'evidenza empirica opera una correzione progressiva della distribuzione a posteriori.\n\n3. **Velocità di convergenza**: la varianza a posteriori decresce proporzionalmente a $1/n$.\n\n### Illustrazione: convergenza con prior differenti\n\nConsideriamo tre ricercatori con concezioni iniziali differenti riguardo al parametro $\\theta$:\n\n- **ricercatore A**: prior $\\text{Beta}(2, 8)$ — propenso a credere in valori bassi di $\\theta$ (attorno a 0.2);\n- **ricercatore B**: prior $\\text{Beta}(8, 2)$ — incline a valori elevati di $\\theta$ (attorno a 0.8);\n- **ricercatore C**: prior $\\text{Beta}(1, 1)$ — uniforme, massima incertezza iniziale.\n\nIl valore del parametro vero è $\\theta_0 = 0.45$. Osserviamo l'evoluzione delle distribuzioni a posteriori:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Parametri della simulazione\ntheta_true <- 0.45\nn_observations <- c(10, 50, 200, 1000)\n\n# Specificazioni a priori\nprior_A <- c(2, 8)\nprior_B <- c(8, 2)\nprior_C <- c(1, 1)\n\n# Funzione per il calcolo delle distribuzioni a posteriori\ncompute_posterior <- function(prior, n, theta) {\n  y <- rbinom(1, n, theta)  # numero di successi osservati\n  c(prior[1] + y, prior[2] + n - y)\n}\n\n# Simulazione\nset.seed(42)\nposteriors <- list()\n\nfor (n in n_observations) {\n  theta_grid <- seq(0.1, 0.9, length.out = 200)\n  \n  post_A <- compute_posterior(prior_A, n, theta_true)\n  post_B <- compute_posterior(prior_B, n, theta_true)\n  post_C <- compute_posterior(prior_C, n, theta_true)\n  \n  posteriors[[as.character(n)]] <- data.frame(\n    theta = rep(theta_grid, 3),\n    density = c(\n      dbeta(theta_grid, post_A[1], post_A[2]),\n      dbeta(theta_grid, post_B[1], post_B[2]),\n      dbeta(theta_grid, post_C[1], post_C[2])\n    ),\n    researcher = rep(c(\"A (prior conservativo)\", \n                       \"B (prior ottimista)\", \n                       \"C (prior non informativo)\"), \n                     each = length(theta_grid)),\n    n = n\n  )\n}\n\nall_posteriors <- do.call(rbind, posteriors)\nall_posteriors$n <- factor(all_posteriors$n, \n                           levels = n_observations,\n                           labels = paste(\"n =\", n_observations))\n\nggplot(all_posteriors, aes(x = theta, y = density, color = researcher, linetype = researcher)) +\n  geom_line(linewidth = 1.2) +\n  geom_vline(xintercept = theta_true, linetype = \"dashed\", \n             color = \"#E15759\", linewidth = 1.2, alpha = 0.8) +\n  facet_wrap(~ n, ncol = 2, scales = \"free_y\") +\n  labs(\n    title = \"Convergenza bayesiana con prior differenti\",\n    subtitle = \"La linea verticale indica il valore parametrico vero θ = 0.45\",\n    x = \"Parametro θ\",\n    y = \"Densità a posteriori\",\n    color = \"Ricercatore\",\n    linetype = \"Ricercatore\"\n  ) +\n  scale_color_manual(values = c(\"#4E79A7\", \"#59A14F\", \"#EDC948\")) +\n  theme_minimal() +\n  theme(legend.position = \"bottom\",\n        plot.title = element_text(face = \"bold\"))\n```\n\n::: {.cell-output-display}\n![](09_dal_dato_ipotesi_files/figure-html/unnamed-chunk-18-1.png){fig-align='center' width=85%}\n:::\n:::\n\n\n**Osservazioni empiriche**:\n\n1. con $n=10$ osservazioni, le distribuzioni a posteriori riflettono marcatamente le diverse concezioni a priori;\n2. con $n=50$ osservazioni, inizia a manifestarsi un processo di convergenza;\n3. con $n=200$ osservazioni, le distribuzioni a posteriori risultano sostanzialmente sovrapposte;\n4. con $n=1000$ osservazioni, le distribuzioni sono praticamente indistinguibili.\n\n**Implicazioni per la ricerca scientifica.**\n\n1. **Soggettività controllata**: sebbene i ricercatori possano iniziare con concezioni a priori diverse, l'evidenza empirica conduce progressivamente a conclusioni condivise.\n\n2. **Criticità della dimensione campionaria**: con campioni di modesta entità, le specificazioni a priori mantengono una forte influenza; con campioni ampi, l'evidenza domina l'inferenza.\n\n3. **Base per la replicabilità**: studi condotti con prior ragionevoli e dimensioni campionarie adeguate convergono verso conclusioni simili.\n\n## Incertezza, distorsione sistematica e limiti dell'inferenza\n\n### L'errore standard quantifica solo l'incertezza campionaria\n\nÈ fondamentale comprendere che l'errore standard, così come la dispersione della distribuzione a posteriori, misura esclusivamente l'incertezza epistemica derivante dalla finitezza del campione. Tale misura non coglie né mitiga gli errori sistematici che possono compromettere la validità del processo di ricerca.\n\n### Fonti di distorsione che persistono\n\n**Distorsione da selezione**: se si intende stimare la prevalenza dei disturbi d'ansia attraverso un campione di volontari, gli individui con sintomi più gravi potrebbero avere una minore o maggiore propensione a partecipare. Anche con campioni di grandi dimensioni, la stima risulterebbe sistematicamente distorta.\n\n**Distorsione da risposta**: se si indaga la frequenza di pensieri negativi auto-riferiti, la desiderabilità sociale può indurre i partecipanti a sottostimare la frequenza effettiva. Si ottiene una stima di elevata precisione statistica, ma riferita a un costrutto distorto.\n\n**Errori di misurazione**: se lo strumento di valutazione non coglie adeguatamente il costrutto teorico o presenta bassa affidabilità, le inferenze statistiche risulteranno compromesse. L'incremento della dimensione del campione non risolve problemi di validità e affidabilità.\n\n### Rappresentazione visiva: precisione versus accuratezza\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](09_dal_dato_ipotesi_files/figure-html/unnamed-chunk-19-1.png){fig-align='center' width=85%}\n:::\n:::\n\n\n**Principio fondamentale**: la condizione più critica nell'inferenza statistica si verifica quando si combina un'elevata precisione con una scarsa accuratezza. In questo scenario, i metodi statistici generano una falsa certezza riguardo a conclusioni sistematicamente distorte. I campioni di grandi dimensioni, quando affetti da bias sistematici, generano stime sostanzialmente errate, ma che appaiono tuttavia accompagnate da livelli di confidenza ingiustificatamente elevati. Questo paradosso rappresenta uno dei rischi più insidiosi nell'interpretazione dei risultati quantitativi, in quanto l'apparente robustezza statistica può mascherare errori sistematici nel disegno della ricerca o nel processo di misurazione.\n\n::: {.callout-warning title=\"Il pericolo della falsa precisione\"}\n\nUn intervallo di credibilità particolarmente ristretto può creare l'illusione di una conoscenza estremamente precisa. È fondamentale riconoscere che tale intervallo quantifica esclusivamente l'incertezza campionaria, senza catturare l'affidabilità complessiva del risultato scientifico.\n\nSe nel disegno sperimentale, negli strumenti di misurazione o nei processi di campionamento sono presenti distorsioni sistematiche, il vero valore del parametro oggetto di studio potrebbe trovarsi ben al di fuori dei limiti dell'intervallo calcolato. L'inferenza bayesiana, sebbene potente nel quantificare l'incertezza attribuibile alla variabilità campionaria, non dispone degli strumenti per identificare o correggere gli errori metodologici di fondo.\n\n**La precisione statistica non deve mai essere confusa con la validità scientifica.**\n:::\n\n### Strategie di mitigazione\n\nPer contrastare il rischio della falsa precisione, è possibile adottare diverse strategie metodologiche. Una progettazione della ricerca metodologicamente rigorosa, che includa strategie di campionamento probabilistico, protocolli standardizzati e strumenti dotati di adeguate proprietà psicometriche, rappresenta il primo baluardo contro le distorsioni sistematiche. L'approccio bayesiano offre inoltre strumenti analitici specifici, come le analisi di sensibilità, che permettono di incorporare esplicitamente l'incertezza relativa alla qualità dei dati mediante distribuzioni a priori progettate per modellare possibili errori di misurazione.\n\nUn ulteriore sviluppo è rappresentato dalla modellazione gerarchica che, grazie alla sua specificazione, permette di catturare le molteplici fonti di variabilità e distorsione presenti nei dati, isolando le diverse componenti di incertezza. Infine, la trasparenza epistemica, che include il riconoscimento esplicito dei limiti metodologici, rimane fondamentale: gli intervalli di credibilità mantengono la loro validità interpretativa solo nel contesto delle assunzioni del modello statistico adottato e la loro violazione può compromettere le conclusioni inferenziali.\n\n## Verso la verosimiglianza: come i dati informano le credenze\n\nIn questo capitolo abbiamo esplorato le proprietà matematiche fondamentali che governano il comportamento della media campionaria e, più in generale, la relazione tra dati e parametri. L'analisi ha rivelato che la media campionaria è centrata sul parametro, come espresso dalla relazione $\\mathbb{E}[\\bar{X}] = \\theta$, e che la sua variabilità diminuisce proporzionalmente all'aumentare della dimensione campionaria secondo la legge $\\text{Var}(\\bar{X}) = \\sigma^2/n$. Abbiamo inoltre osservato come essa converga al valore vero con l'accumularsi dei dati, in accordo con la Legge dei Grandi Numeri, e come la sua distribuzione tenda asintoticamente verso la normale per effetto del Teorema del Limite Centrale.\n\nMa come si traducono concretamente queste proprietà nell'aggiornamento delle credenze bayesiane? La risposta risiede nella **funzione di verosimiglianza**, che costituirà l'oggetto di uno dei prossimi capitoli. La verosimiglianza formalizza il meccanismo attraverso cui i dati \"parlano\": per ogni possibile valore del parametro $\\theta$, essa quantifica quanto bene quel valore spiega le osservazioni raccolte. È proprio la verosimiglianza che, combinata con la distribuzione a priori mediante il teorema di Bayes, genera la distribuzione a posteriori.\n\nLe proprietà matematiche esaminate in questo capitolo, come la centratura, la precisione crescente e la convergenza, trovano la loro espressione formale nella verosimiglianza. Comprendere a fondo queste proprietà risulta quindi essenziale per apprezzare il funzionamento dell'inferenza bayesiana e per interpretare correttamente i risultati che da essa scaturiscono.\n\n## Riflessioni conclusive {.unnumbered .unlisted}\n\nQuesto capitolo ha esplorato le modalità attraverso cui quantificare sistematicamente l'incertezza quando si traggono conclusioni da evidenze limitate. Le proprietà matematiche fondamentali della media campionaria rivelano che essa è centrata sul parametro della popolazione, giustificando così l'uso dei dati per trarre inferenze affidabili. La precisione delle nostre stime aumenta sistematicamente con l'aumentare del numero di osservazioni, poiché la variabilità diminuisce secondo il fattore $1/n$. La Legge dei Grandi Numeri, inoltre, garantisce la convergenza delle nostre inferenze verso i valori veri. Il Teorema del Limite Centrale fornisce inoltre il fondamento teorico per le approssimazioni distribuzionali, cruciali nella pratica statistica.\n\nL'inferenza bayesiana emerge come un framework coerente per quantificare e aggiornare l'incertezza in modo formalmente rigoroso. In questo approccio, le credenze iniziali, espresse come distribuzioni a priori, vengono aggiornate sistematicamente alla luce dei dati osservati. La distribuzione a posteriori rappresenta lo stato di conoscenza più aggiornato dopo l'osservazione dei dati, mentre gli intervalli di credibilità forniscono un'interpretazione probabilistica diretta e intuitiva. Un aspetto particolarmente rilevante è che, in presenza di un numero sufficiente di dati, credenze iniziali anche molto diverse tendono a convergere verso conclusioni sostanzialmente condivise.\n\nTuttavia, è necessario riconoscere e considerare i limiti metodologici. L'inferenza statistica quantifica esclusivamente l'incertezza campionaria senza poter correggere le distorsioni sistematiche eventualmente presenti nel disegno della ricerca. I campioni di grandi dimensioni, se affetti da bias, producono stime precise ma imprecise, creando il rischio di false certezze. La qualità del disegno di ricerca rimane dunque un presupposto irrinunciabile che non può essere sostituito dalla sofisticazione statistica.\n\nIn un capitolo successivo vedremo come la verosimiglianza formalizzi compiutamente il ruolo dei dati nell'inferenza, completando così il quadro concettuale necessario per comprendere il meccanismo di aggiornamento bayesiano e le sue implicazioni per la ricerca empirica.\n\n::: {.callout-important title=\"Problemi\" collapse=\"true\"}\nEsercizi sulla distribuzione campionaria e sull'inferenza sono disponibili sulla seguente [pagina web](https://stats.libretexts.org/Bookshelves/Introductory_Statistics/Introductory_Statistics_(Shafer_and_Zhang)/06%3A_Sampling_Distributions/6.E%3A_Sampling_Distributions_(Exercises)).\n:::\n\n::: {.callout-note collapse=true title=\"Informazioni sull'ambiente di sviluppo\"}\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsessionInfo()\n#> R version 4.5.2 (2025-10-31)\n#> Platform: aarch64-apple-darwin20\n#> Running under: macOS Tahoe 26.1\n#> \n#> Matrix products: default\n#> BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib \n#> LAPACK: /Library/Frameworks/R.framework/Versions/4.5-arm64/Resources/lib/libRlapack.dylib;  LAPACK version 3.12.1\n#> \n#> locale:\n#> [1] C.UTF-8/UTF-8/C.UTF-8/C/C.UTF-8/C.UTF-8\n#> \n#> time zone: Europe/Rome\n#> tzcode source: internal\n#> \n#> attached base packages:\n#> [1] stats     graphics  grDevices utils     datasets  methods   base     \n#> \n#> other attached packages:\n#>  [1] pillar_1.11.1         tinytable_0.15.1      patchwork_1.3.2      \n#>  [4] ggdist_3.3.3          tidybayes_3.0.7       bayesplot_1.14.0     \n#>  [7] ggplot2_4.0.1         reliabilitydiag_0.2.1 priorsense_1.2.0     \n#> [10] posterior_1.6.1       loo_2.8.0             rstan_2.32.7         \n#> [13] StanHeaders_2.32.10   brms_2.23.0           Rcpp_1.1.0           \n#> [16] sessioninfo_1.2.3     conflicted_1.2.0      janitor_2.2.1        \n#> [19] matrixStats_1.5.0     modelr_0.1.11         tibble_3.3.0         \n#> [22] dplyr_1.1.4           tidyr_1.3.1           rio_1.2.4            \n#> [25] here_1.0.2           \n#> \n#> loaded via a namespace (and not attached):\n#>  [1] svUnit_1.0.8          tidyselect_1.2.1      farver_2.1.2         \n#>  [4] S7_0.2.1              fastmap_1.2.0         TH.data_1.1-5        \n#>  [7] tensorA_0.36.2.1      digest_0.6.39         timechange_0.3.0     \n#> [10] estimability_1.5.1    lifecycle_1.0.4       survival_3.8-3       \n#> [13] magrittr_2.0.4        compiler_4.5.2        rlang_1.1.6          \n#> [16] tools_4.5.2           yaml_2.3.10           knitr_1.50           \n#> [19] labeling_0.4.3        bridgesampling_1.2-1  htmlwidgets_1.6.4    \n#> [22] curl_7.0.0            pkgbuild_1.4.8        RColorBrewer_1.1-3   \n#> [25] abind_1.4-8           multcomp_1.4-29       withr_3.0.2          \n#> [28] purrr_1.2.0           grid_4.5.2            stats4_4.5.2         \n#> [31] colorspace_2.1-2      xtable_1.8-4          inline_0.3.21        \n#> [34] emmeans_2.0.0         scales_1.4.0          MASS_7.3-65          \n#> [37] cli_3.6.5             mvtnorm_1.3-3         rmarkdown_2.30       \n#> [40] ragg_1.5.0            generics_0.1.4        RcppParallel_5.1.11-1\n#> [43] cachem_1.1.0          stringr_1.6.0         splines_4.5.2        \n#> [46] parallel_4.5.2        vctrs_0.6.5           V8_8.0.1             \n#> [49] Matrix_1.7-4          sandwich_3.1-1        jsonlite_2.0.0       \n#> [52] arrayhelpers_1.1-0    systemfonts_1.3.1     glue_1.8.0           \n#> [55] codetools_0.2-20      distributional_0.5.0  lubridate_1.9.4      \n#> [58] stringi_1.8.7         gtable_0.3.6          QuickJSR_1.8.1       \n#> [61] htmltools_0.5.8.1     Brobdingnag_1.2-9     R6_2.6.1             \n#> [64] textshaping_1.0.4     rprojroot_2.1.1       evaluate_1.0.5       \n#> [67] lattice_0.22-7        backports_1.5.0       memoise_2.0.1        \n#> [70] broom_1.0.10          snakecase_0.11.1      rstantools_2.5.0     \n#> [73] gridExtra_2.3         coda_0.19-4.1         nlme_3.1-168         \n#> [76] checkmate_2.3.3       xfun_0.54             zoo_1.8-14           \n#> [79] pkgconfig_2.0.3\n```\n:::\n\n:::\n\n## Bibliografia {.unnumbered .unlisted}\n",
    "supporting": [
      "09_dal_dato_ipotesi_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}