project:
  type: book
  output-dir: docs

book:
  title: "Probabilità per la psicologia"
  subtitle: "Modulo di richiamo"
  license: "Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International (CC BY-NC-ND 4.0)"
  reader-mode: true
  google-analytics: G-QT5S3P9D31

  author: 
    - name: "Corrado Caudek"
      orcid: "0000-0002-1404-0420"
  date: "last-modified"
  search: true
  repo-url: https://github.com/ccaudek/utet-prob/
  repo-actions: [source, issue]
  back-to-top-navigation: true
  site-url: https://ccaudek.github.io/utet-prob/
  page-footer:
    left: |
      **Probabilità per la psicologia** — Modulo di richiamo del progetto UTET a supporto del manuale *Metodi bayesiani in psicologia*.
    right: |
      Realizzato con <a href="https://quarto.org/">Quarto</a>.
  favicon: style/gauss.png
  sidebar:
    collapse-level: 1

  chapters:
    - index.qmd
    - prefazione.qmd

    - part: chapters/probability/introduction_probability.qmd
      chapters:
        - chapters/probability/01_intro_prob.qmd
        - chapters/probability/02_probability_models.qmd
        - chapters/probability/03_sigma-algebra.qmd
        - chapters/probability/04_conditional_prob.qmd
        - chapters/probability/05_bayes_theorem.qmd
        - chapters/probability/06_random_var.qmd
        - chapters/probability/07_prob_distributions.qmd
        - chapters/probability/08_expval_var.qmd
        - chapters/probability/09_sampling_distr.qmd
        - chapters/probability/10_joint_prob.qmd
        - chapters/probability/11_cov_cor.qmd
        - chapters/probability/12_intro_distributions.qmd
        - chapters/probability/13_discr_rv_distr.qmd
        - chapters/probability/14_cont_rv_distr.qmd
        - chapters/probability/15_gauss.qmd
        - chapters/probability/16_likelihood.qmd

  appendices:
    - chapters/appendix/a02_math_symbols.qmd
    - chapters/appendix/a11_numbers.qmd
    - chapters/appendix/a12_sum_notation.qmd
    - chapters/appendix/a13_sets.qmd
    - chapters/appendix/a14_combinatorics.qmd
    - chapters/appendix/a15_calculus.qmd

crossref:
  appendix-title: "Appendice"

toc: true
toc-depth: 2

bibliography: ./references.bib
biblio-style: apalike
csl: apa.csl
link-citations: true

format:
  html:
    include-in-header:
      - style/_mathjax-config.html
    include-after-body:
      - style/_after-body.html
    theme: style/mystyle.scss
    css:
      - style/_typography-extras.css
      - style/_code-extras.css
      - style/_math-extras.css
      - style/styles.css
    fig-format: png
    dpi: 192
    fig-responsive: true
    smooth-scroll: true
    page-layout: article
    max-width: 72ch
    number-sections: true
    link-external-icon: true
    link-external-newwindow: true
    footnotes-hover: true
    reader-mode: true
    callout-appearance: minimal
    lang: it
    title-block-banner: false
    toc-title: "Sommario"
    date-format: "D MMMM YYYY"
    code-copy: hover
    code-link: true
    code-overflow: scroll
    code-line-numbers: false
    code-block-bg: false
    code-block-border-left: false

execute:
  freeze: auto
  echo: true
  warning: false
  message: false
  fig.width: 6
  fig.asp: 0.618
  fig.retina: 2
  fig.align: "center"
  fig.show: "hold"
  options:
    width: 120
    pillar.width: Inf
    tibble.width: Inf

website:
  cookie-consent:
    type: express
    style: headline
    anonymize-ip: true
