{
  "hash": "f2bfa5c418d66fc94c99da13d68940e2",
  "result": {
    "engine": "knitr",
    "markdown": "# Probabilità condizionata {#sec-prob-conditional-prob}\n\n::: {.epigraph}\n> “Probability is always conditional.”\n>\n> -- **Dennis V. Lindley**, *The Philosophy of Statistics* (2000). \n:::\n\n\n## Introduzione {.unnumbered .unlisted}\n\nLa probabilità condizionata esprime la probabilità di un evento in relazione al verificarsi di un altro evento. Questo concetto è fondamentale, in quanto riflette il modo in cui *aggiorniamo* le nostre credenze alla luce di nuove informazioni. Ad esempio, la probabilità che piova domani può variare in base alle condizioni atmosferiche odierne: osservare un cielo nuvoloso può influenzare la nostra valutazione della probabilità di pioggia. In questo senso, ogni nuova informazione può confermare, rafforzare o mettere in discussione le credenze preesistenti.\n\nLa probabilità condizionata riveste un ruolo centrale non solo nella teoria della probabilità, ma anche nelle applicazioni quotidiane e scientifiche. In molti contesti, le probabilità sono implicitamente condizionate da informazioni preesistenti, anche se non le esplicitiamo formalmente. Comprendere e quantificare questo processo di aggiornamento delle credenze ci permette di gestire l'incertezza in modo più efficace, trasformando la probabilità in uno strumento dinamico per la presa di decisioni e l'inferenza.\n\n### Panoramica del capitolo {.unnumbered .unlisted}\n\n- Concetti di probabilità congiunta, marginale e condizionata.\n- Applicazione dei principi di indipendenza e probabilità condizionata.\n- Il paradosso di Simpson;\n- Il teorema del prodotto e della probabilità totale.\n\n::: {.callout-tip collapse=true}\n## Prerequisiti\n\n- Leggere il capitolo *Conditional probability* di *Introduction to Probability* [@blitzstein2019introduction]. \n- Leggere il capitolo *Conditional Probability* [@schervish2014probability].\n:::\n\n::: {.callout-caution collapse=true title=\"Preparazione del Notebook\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhere::here(\"code\", \"_common.R\") |> \n  source()\n```\n:::\n\n:::\n\n## Indipendenza stocastica\n\nIn alcuni casi, l’aggiornamento delle probabilità diventa particolarmente semplice. Ciò si verifica quando due eventi non si influenzano a vicenda. In tali situazioni, la probabilità che essi si verifichino insieme può essere calcolata direttamente, grazie alla proprietà di *indipendenza*.\n\n### Indipendenza di due eventi\n\n::: {#def-}\nDue eventi $A$ e $B$ si dicono *indipendenti* se la probabilità che si verifichino entrambi è pari al prodotto delle loro probabilità individuali:\n\n$$\nP(A \\cap B) = P(A) \\, P(B).\n$$ {#eq-join-prob-independence}\n:::\n\nCiò significa che conoscere l’esito di uno dei due eventi non fornisce alcuna informazione utile sull’altro. In simboli, si scrive $A \\perp B$ per indicare che $A$ e $B$ sono eventi indipendenti.  \n\n::: {.callout-note collapse=\"true\" title=\"Esempio\"}\nSupponiamo di lanciare *due monete distinte* e di considerare i seguenti eventi:\n\n- $A$ = “La *prima* moneta mostra Testa”  \n- $B$ = “La *seconda* moneta mostra Testa”\n\nPoiché il risultato della prima moneta non influisce in alcun modo su quello della seconda, i due eventi sono *indipendenti*. In particolare, la probabilità di ottenere “Testa” su una moneta è:\n\n$$\nP(A) \\;=\\; P(B) \\;=\\; \\frac{1}{2}.\n$$\n\nLa probabilità che entrambe le monete mostrino Testa (cioè che si verifichino contemporaneamente gli eventi $A$ e $B$) è data dal *prodotto* delle loro probabilità:\n\n$$\nP(A \\cap B) \\;=\\; P(A)\\,P(B)\n\\;=\\; \\frac{1}{2} \\times \\frac{1}{2}\n\\;=\\; \\frac{1}{4}.\n$$\n\nPoiché questa relazione è soddisfatta, possiamo concludere che *$A$ e $B$ sono eventi indipendenti*.  \n:::\n\n## Indipendenza di un insieme di eventi\n\nIl concetto di *indipendenza* non riguarda soltanto due eventi, ma può estendersi anche a un insieme più ampio. In generale, diciamo che ${A_i : i \\in I}$ è un insieme di eventi *indipendente* se, per ogni sottoinsieme finito $J \\subseteq I$, la probabilità che si verifichino contemporaneamente tutti gli eventi di $J$ è uguale al prodotto delle loro probabilità individuali:\n\n$$\nP \\Bigl(\\bigcap_{i \\in J} A_i\\Bigr) \\;=\\; \\prod_{i \\in J} P(A_i).\n$$ {#eq-join-prob-independence-set}\nIn altre parole, nessun evento della collezione fornisce informazioni utili sugli altri: il verificarsi di uno non modifica la probabilità degli altri.  \n\nNella pratica, questa condizione è molto forte. Per questo motivo, l’indipendenza di più eventi può avere due significati distinti:  \n\n- può essere un’*ipotesi semplificante* in un modello (per esempio, assumere che le risposte a diverse domande di un questionario siano indipendenti, cioè non influenzate tra loro);  \n- può essere una *proprietà empirica* dei dati, che deve però essere verificata con analisi specifiche.  \n\n::: {.callout-note collapse=\"true\" title=\"Esempio\"}\nConsideriamo una sequenza di *tre lanci* di una moneta equilibrata e definiamo gli eventi:\n\n- $A_1$ = “Il primo lancio mostra *Testa*”.\n- $A_2$ = “Il secondo lancio mostra *Testa*”.\n- $A_3$ = “Il terzo lancio mostra *Testa*”.\n\nCiascuno di questi eventi ha probabilità $1/2$. Poiché ogni lancio *non* influenza gli altri, l’insieme $\\{A_1, A_2, A_3\\}$ è *indipendente* nel senso più ampio: non solo $P(A_1 \\cap A_2) = P(A_1)P(A_2)$ e simili per coppie, ma vale anche\n\n$$\nP(A_1 \\cap A_2 \\cap A_3)\n\\;=\\;\nP(A_1)\\,P(A_2)\\,P(A_3)\n\\;=\\;\n\\left(\\tfrac12\\right)\\left(\\tfrac12\\right)\\left(\\tfrac12\\right)\n\\;=\\;\n\\tfrac18.\n$$\n\nIn effetti, per *qualunque* combinazione di Testa e Croce (ad esempio, “Testa al primo e terzo lancio, Croce al secondo”), la probabilità risulta sempre il prodotto delle probabilità dei singoli esiti, confermando l’indipendenza.\n:::\n\n### Quando gli eventi non sono indipendenti\n\nSe per due eventi $A$ e $B$ vale la disuguaglianza  \n$$\nP(A \\cap B) \\neq P(A) \\cdot P(B),\n$$ \nallora essi *non sono indipendenti*. In tal caso, la conoscenza dell’esito di uno dei due eventi fornisce *informazioni rilevanti* sulla probabilità del verificarsi dell’altro. Questa dipendenza deve essere esplicitamente considerata nei calcoli probabilistici, ad esempio ricorrendo al concetto di *probabilità condizionata*.\n\n::: {.callout-note collapse=\"true\" title=\"Indipendenza stocastica e mutua esclusività: concetti distinti\"}\n\nUn errore concettuale comune consiste nel confondere il concetto di \"indipendenza\" con quello di \"disgiunzione\" (o mutua esclusività). Due eventi sono *disgiunti* quando non possono verificarsi simultaneamente, ossia quando:\n\n$$\nP(A \\cap B) = 0.\n$$\n\nSe $P(A) > 0$ e $P(B) > 0$, e gli eventi sono disgiunti, allora *non possono essere indipendenti*. Infatti, l’indipendenza richiederebbe:\n\n$$\nP(A \\cap B) = P(A) \\cdot P(B) > 0,\n$$\nma per definizione di disgiunzione si ha $P(A \\cap B) = 0$, il che contraddice la precedente uguaglianza. Pertanto, la disgiunzione implica un’esclusione reciproca, mentre l’indipendenza indica l’assenza di qualsiasi influenza tra i due eventi.\n\nPer esempio, nel lancio di un dado a sei facce:\n\n- $C$ = “Esce un numero pari” $\\{\\;2,4,6\\}$.\n- $D$ = “Esce un numero dispari” $\\{\\;1,3,5\\}$.\n\nI due eventi sono *disgiunti*, poiché un numero non può essere contemporaneamente pari e dispari; dunque $P(C \\cap D)=0$.\n\nTuttavia, *non* sono indipendenti: se lo fossero, si dovrebbe avere $P(C \\cap D) = P(C)P(D)$. Invece,\n\n$$\n0 \\;\\neq\\; \\tfrac12 \\,\\times\\, \\tfrac12 \\;=\\; \\tfrac14,\n$$\nda cui segue che $C$ e $D$ non sono eventi indipendenti.  \n\nIn sintesi, gli eventi *disgiunti* (o mutualmente esclusivi) non possono verificarsi simultaneamente, mentre gli eventi *indipendenti* non esercitano alcuna influenza reciproca sulle rispettive probabilità. Sebbene entrambe le proprietà rivestano un'importanza fondamentale nella teoria della probabilità, esse descrivono relazioni concettualmente distinte tra gli eventi.\n:::\n\n## Probabilità condizionata\n\nLa *probabilità condizionata* quantifica la probabilità che si verifichi un evento $A$, dato che si è verificato un altro evento $B$.\n\n::: {#def-}\nSe $P(B) > 0$, la probabilità condizionata di $A$ dato $B$ è definita come:\n\n$$\nP(A \\mid B) = \\frac{P(A \\cap B)}{P(B)}. \n$$ {#eq-prob-cond-def}\n:::\n\nQuesta espressione può essere interpretata come un'operazione di *confinamento probabilistico* agli esiti in cui $B$ si verifica, ricalibrando così la misura di probabilità sull'evento condizionante.\n\n### Interpretazione della probabilità condizionata\n\nLa probabilità condizionata rappresenta un *meccanismo di aggiornamento* delle nostre conoscenze. Inizialmente, si dispone di una probabilità $P(A)$; dopo aver osservato il verificarsi di un evento correlato $B$, si restringe lo spazio degli esiti possibili a quelli compatibili con $B$, ricalibrando di conseguenza la probabilità di $A$.\n\n- **Esempio intuitivo**: Se una persona ha la febbre ($B$), la probabilità che abbia l’influenza ($A$) aumenta rispetto alla probabilità basata sulla sola popolazione generale.\n\nQuesta capacità di “aggiornare probabilisticamente\" le credenze rende la probabilità condizionata uno strumento essenziale in:\n\n- *diagnosi medica:* per valutare la probabilità di una malattia ($A$) dato il risultato di un test ($B$);  \n- *previsioni meteorologiche*, per stimare la probabilità di pioggia $A$) dato l'arrivo di un fronte nuvoloso ($B$); \n- *modellizzazione delle dipendenze stocastiche*, dove il verificarsi di un evento influisce sulla probabilità di un altro.\n\nLa formula $P(A \\mid B) = \\frac{P(A \\cap B)}{P(B)}$ quantifica proprio questo processo di revisione della probabilità alla luce di nuove informazioni.\n\n::: {.callout-note collapse=\"true\" title=\"Esempio\"}\nLanciamo due dadi equilibrati consecutivamente. Dato che la somma dei dadi è 10, qual è la probabilità che uno dei due dadi mostri un 6?  \n\nDefiniamo:  \n\n- *B* come l'evento che la somma sia 10:  \n  $$ B = \\{(4, 6), (5, 5), (6, 4)\\}. $$  \n- *A* come l'evento che uno dei due dadi mostri un 6:  \n  $$ A = \\{(1, 6), \\dots, (5, 6), (6, 1), \\dots, (6, 5)\\}. $$  \n\nL'intersezione tra *A* e *B* è:  \n$$ A \\cap B = \\{(4, 6), (6, 4)\\}. $$  \n\nPoiché in questo esperimento tutti gli eventi elementari sono equiprobabili, la probabilità condizionata $P(A | B)$ è data da:  \n$$\nP(A | B) = \\frac{P(A \\cap B)}{P(B)} = \\frac{\\frac{2}{36}}{\\frac{3}{36}} = \\frac{2}{3}.\n$$  \n\nQuindi, la probabilità che uno dei due dadi mostri un 6, sapendo che la somma è 10, è $\\frac{2}{3}$.\n:::\n\n::: {.callout-note collapse=\"true\" title=\"Esempio\"}\n**Somma di due dadi**\n\nConsideriamo il lancio di *due dadi equilibrati* e calcoliamo la probabilità che la somma dei punteggi risulti *minore di 8*.\n\n1. **Senza informazioni aggiuntive**  \n\n   - Ogni dado può assumere valori da 1 a 6, per un totale di 36 possibili combinazioni $(6 \\times 6)$.  \n   - Tra queste 36, esistono 21 combinazioni in cui la somma è minore di 8.  \n   - Dunque la probabilità iniziale è:\n     $$\n     P(\\text{Somma} < 8)\n     \\;=\\;\n     \\frac{21}{36}\n     \\;\\approx\\; 0{.}58.\n     $$\n\n2. **Con informazione aggiuntiva**  \n   Supponiamo di *sapere* che la somma uscita è *dispari*. Questa nuova informazione *restringe* lo spazio degli esiti possibili:\n   \n   - Solo 18 combinazioni su 36 producono un risultato dispari.  \n   - Tra queste 18, 12 combinazioni hanno somma minore di 8.  \n   - Pertanto, la probabilità condizionata diventa:\n     $$\n     P(\\text{Somma} < 8 \\,\\mid\\, \\text{Somma dispari})\n     \\;=\\;\n     \\frac{12}{18}\n     \\;=\\;\n     0{.}67.\n     $$\n\nConfrontando i due risultati ($0{,}58$ senza informazioni contro $0{,}67$ con l’informazione “somma dispari”), osserviamo come la *probabilità di un evento possa cambiare* una volta ottenuta un’informazione aggiuntiva.\n\n**Codice in R.**\n\nNel codice R che segue, utilizziamo l’insieme di tutte le combinazioni di lanci per verificare numericamente i risultati:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# 1. Definiamo i possibili valori di un dado\nr <- 1:6  \n\n# 2. Costruiamo tutte le combinazioni possibili (i, j)\n#    in cui i e j vanno da 1 a 6.\n#    In totale ci aspettiamo 36 combinazioni (6 x 6).\nsample <- expand.grid(i = r, j = r)  \nnrow(sample)  # Contiamo quante sono: dovrebbero essere 36\n#> [1] 36\n\n# 3. Selezioniamo solo le coppie (i, j) in cui la somma è minore di 8.\n#    Verifichiamo quante sono e le confrontiamo con il totale.\nevent <- subset(sample, i + j < 8)\ncat(nrow(event), \"/\", nrow(sample), \"\\n\")  # Dovrebbe stampare 21 / 36\n#> 21 / 36\n\n# 4. Selezioniamo ora solo le coppie con somma dispari.\n#    %% è l’operatore \"modulo\": (i + j) %% 2 != 0 verifica se la somma è dispari.\nsample_odd <- subset(sample, (i + j) %% 2 != 0)\nnrow(sample_odd)  # Dovrebbe essere 18\n#> [1] 18\n\n# 5. Calcoliamo quante coppie hanno somma minore di 8 tra quelle con somma dispari.\nevent_odd <- subset(sample_odd, i + j < 8)\ncat(nrow(event_odd), \"/\", nrow(sample_odd), \"\\n\")  # Dovrebbe stampare 12 / 18\n#> 12 / 18\n```\n:::\n\n\nSecondo la @eq-prob-cond-definition, se definiamo  \n\n- $A$ = “Somma < 8”  \n- $B$ = “Somma dispari”,  \n\nallora $P(A \\cap B) = 12/36$ e $P(B) = 18/36$. Di conseguenza,\n\n$$\nP(A \\mid B)\n\\;=\\;\n\\frac{P(A \\cap B)}{P(B)}\n\\;=\\;\n\\frac{12/36}{18/36}\n\\;=\\;\n\\frac{12}{18}\n\\;=\\;\n0{.}67.\n$$\n\nQuesto esempio dimostra come la *probabilità condizionata* consenta di aggiornare la stima di un evento alla luce di nuove informazioni.\n:::\n\n::: {.callout-tip title=\"Screening per la diagnosi precoce del tumore mammario\" collapse=\"true\"}\n\nSupponiamo di utilizzare un test diagnostico con le seguenti caratteristiche:\n\n- **Sensibilità** (probabilità di test positivo fra le donne **malate**): 90%.  \n- **Specificità** (probabilità di test negativo fra le donne **sane**): 90%.  \n- **Prevalenza** (percentuale di donne effettivamente malate nella popolazione): 1%.\n\n**1. Esempio con 1000 donne.**\n\nPer semplificare i calcoli, immaginiamo di sottoporre a screening 1000 donne a caso:\n\n1. *Donne malate* (1%): 10 su 1000.  \n   - Con una *sensibilità del 90%*, circa 9 di queste 10 donne avranno un esito positivo al test (vere positive).  \n   - Circa 1 donna avrà invece un risultato negativo (falso negativo).\n\n2. *Donne sane* (99%): 990 su 1000.  \n   - Con una *specificità del 90%*, circa 891 di queste 990 risulteranno negative al test (vere negative).  \n   - Le restanti 99 donne avranno un esito positivo (false positive).\n\nQuesto ci permette di costruire uno schema riassuntivo (spesso rappresentato sotto forma di tabella o diagramma a blocchi):\n\n- *positive*: $9$ (vere positive) + $99$ (false positive) = *108*,  \n- *negative*: $1$ (falso negativo) + $891$ (vero negativo) = *892*.  \n\n\n**2. Probabilità *non condizionata* di un test positivo.**\n\nLa probabilità che una donna, scelta a caso, *risulti positiva* allo screening (indipendentemente dal fatto che sia malata o sana) si ottiene rapportando il numero di test positivi al totale:\n\n$$\nP(\\text{Test positivo})\n\\;=\\;\n\\frac{108}{1000}\n\\;=\\;\n0{.}108\n\\;\\; (10{.}8\\%).\n$$\n\nQuesta è una *probabilità non condizionata*, in quanto considera l’intera popolazione delle 1000 donne, senza ulteriori informazioni.\n\n\n**3. Probabilità *condizionata* di essere malate dato un test positivo.**\n\nCi interessa ora sapere: *Se una donna ha appena ricevuto un risultato positivo, qual è la probabilità che abbia davvero il cancro al seno?*\n\nMatematicamente, riformuliamo la domanda come:  \n$$\nP(\\text{Cancro} \\mid \\text{Test positivo}).\n$$\n\nOsservando il nostro esempio di 1000 donne:\n\n- Abbiamo *108 test positivi* in tutto.  \n- Solo *9* di questi test positivi provengono effettivamente da donne malate.\n\nPertanto,\n\n$$\nP(\\text{Cancro} \\mid \\text{Test positivo})\n\\;=\\;\n\\frac{9}{108}\n\\;=\\;\n0{.}083\n\\;\\; (8{.}3\\%).\n$$\n\nQuesta è una *probabilità condizionata*, poiché riguarda soltanto quelle donne già selezionate in base all’esito positivo del test.\n\n**4. Confronto fra probabilità non condizionata e condizionata.**\n\n- *Probabilità non condizionata* (esito positivo): $0{.}108$ (10.8%).  \n- *Probabilità condizionata* (avere un tumore, sapendo che il test è positivo): $0{.}083$ (8.3%).\n\nNotiamo come *l’informazione aggiuntiva* (“il test è risultato positivo”) riduca il numero di casi osservati, focalizzando l’attenzione su un sottoinsieme della popolazione. In altre parole, la conoscenza di un test positivo *aggiorna* la nostra stima della probabilità di avere la malattia, mostrandoci che, nonostante l’alta sensibilità e specificità, la maggior parte dei test positivi riguarda donne sane (false positive), a causa della bassa prevalenza (1%).\n\nQuesto esempio illustra in modo tangibile la distinzione fra:\n\n1. *probabilità non condizionata*: la probabilità di un evento considerando l’intera popolazione,  \n2. *probabilità condizionata*: la probabilità di un evento una volta appresa un’informazione aggiuntiva (qui, l’esito positivo del test).\n\nQuesta differenza è fondamentale nell’interpretazione dei test diagnostici, specialmente quando la malattia è relativamente rara.\n:::\n\n::: {.callout-tip title=\"Il Problema di Monty Hall\" collapse=\"true\"}\nIl *problema di Monty Hall* è un famoso quesito di teoria della probabilità che illustra in modo efficace il concetto di probabilità condizionata. Questo problema è diventato celebre grazie a una rubrica tenuta da Marilyn vos Savant nella rivista *Parade*, in cui rispose a una lettera pubblicata il 9 settembre 1990:\n\n> \"Supponiamo di partecipare a un quiz televisivo e di dover scegliere tra tre porte. Dietro una di esse c'è un'auto, mentre dietro le altre due ci sono delle capre. Scegli una porta, ad esempio la numero 1, e il conduttore, che sa cosa c'è dietro ogni porta, ne apre un'altra, diciamo la numero 3, rivelando una capra. A questo punto, ti chiede se vuoi cambiare la tua scelta e passare alla porta numero 2. È vantaggioso cambiare porta?\"\n> Craig. F. Whitaker, Columbia, MD\n\nLa situazione descritta ricorda quella del popolare quiz televisivo degli anni '70 *Let's Make a Deal*, condotto da Monty Hall e Carol Merrill. Marilyn vos Savant rispose che il concorrente dovrebbe cambiare porta, poiché la probabilità di vincere l'auto raddoppia passando da 1/3 a 2/3. Tuttavia, la sua risposta suscitò un acceso dibattito, con molte persone, inclusi alcuni matematici, che sostenevano che cambiare porta non avrebbe offerto alcun vantaggio. Questo episodio ha reso il problema di Monty Hall uno dei più famosi esempi di come l'intuizione possa portare a conclusioni errate in ambito probabilistico.\n\n**Chiarire il Problema.**\n\nLa lettera originale di Craig Whitaker è piuttosto vaga, quindi per analizzare il problema in modo rigoroso è necessario fare alcune ipotesi:\n\n1. *Posizione dell'auto*: L'auto è nascosta in modo casuale ed equiprobabile dietro una delle tre porte.\n2. *Scelta iniziale del giocatore*: Il giocatore sceglie una porta in modo casuale, indipendentemente dalla posizione dell'auto.\n3. *Azione del conduttore*: Dopo la scelta del giocatore, il conduttore apre una delle due porte rimanenti, rivelando una capra, e offre al giocatore la possibilità di cambiare porta.\n4. *Scelta del conduttore*: Se il conduttore ha la possibilità di scegliere tra due porte (entrambe con capre), ne apre una in modo casuale.\n\nCon queste assunzioni, possiamo rispondere alla domanda: *Qual è la probabilità che il giocatore vinca l'auto se decide di cambiare porta?*\n\nDi seguito, esploreremo tre metodi per risolvere il problema di Monty Hall: il diagramma ad albero, l'analisi delle probabilità e una simulazione.\n\n**Metodo 1: diagramma ad albero.**\n\nIl diagramma ad albero è uno strumento utile per visualizzare tutti i possibili esiti di un esperimento probabilistico. Nel caso del problema di Monty Hall, possiamo suddividere il processo in tre fasi:\n\n1. *Posizione dell'auto*: L'auto può trovarsi dietro una delle tre porte (A, B o C), ciascuna con probabilità 1/3.\n2. *Scelta del giocatore*: Il giocatore sceglie una porta in modo casuale, indipendentemente dalla posizione dell'auto.\n3. *Azione del conduttore*: Il conduttore apre una delle due porte rimanenti, rivelando una capra.\n\nIl diagramma ad albero mostra tutte le possibili combinazioni di questi eventi. Ad esempio, se l'auto è dietro la porta A e il giocatore sceglie la porta B, il conduttore aprirà la porta C (l'unica porta rimanente con una capra).\n\n**Passo 1: Identificare lo spazio campionario**  \nLo spazio campionario è composto da 12 esiti possibili, rappresentati dalle combinazioni di:\n\n- Posizione dell'auto (A, B, C).\n- Scelta iniziale del giocatore (A, B, C).\n- Porta aperta dal conduttore (una delle due rimanenti con una capra).\n\nEcco un diagramma ad albero che rappresenta questa situazione:\n\n::: {#fig-monthy-hall-tree}\n![](../../figures/monthy-hall-tree.png){width=\"75%\"}\n\nIl diagramma ad albero per il Problema di Monty Hall mostra le probabilità associate a ogni possibile esito. I pesi sugli archi rappresentano la probabilità di seguire quel particolare percorso, dato che ci troviamo nel nodo padre. Ad esempio, se l'auto si trova dietro la porta A, la probabilità che il giocatore scelga inizialmente la porta B è pari a 1/3. La colonna più a destra del diagramma mostra la probabilità di ciascun esito finale. Ogni probabilità di esito è calcolata moltiplicando le probabilità lungo il percorso che parte dalla radice (auto dietro una certa porta) e termina alla foglia (esito finale) (Figura tratta da Lehman, Leighton e Meyer, 2018).\n:::\n\n**Passo 2: Definire l'evento di interesse**  \nL'evento di interesse è \"il giocatore vince cambiando porta\". Questo si verifica quando la porta inizialmente scelta dal giocatore non nasconde l'auto, e il giocatore decide di cambiare porta.\n\nGli esiti che soddisfano questa condizione sono:\n\n- `(Auto A, Scelta B, Apertura C)`\n- `(Auto A, Scelta C, Apertura B)`\n- `(Auto B, Scelta A, Apertura C)`\n- `(Auto B, Scelta C, Apertura A)`\n- `(Auto C, Scelta A, Apertura B)`\n- `(Auto C, Scelta B, Apertura A)`\n\nQuesti esiti sono in totale 6.\n\n**Passo 3: Calcolare le probabilità degli esiti**  \nOgni esito ha una probabilità specifica, calcolata moltiplicando le probabilità lungo il percorso nel diagramma ad albero. \n\nEsempio di calcolo per l'esito `(Auto A, Scelta B, Apertura C)`:\n\n- La probabilità che l'auto sia dietro la porta A è $\\frac{1}{3}$.\n- La probabilità che il giocatore scelga la porta B è $\\frac{1}{3}$.\n- La probabilità che il conduttore apra la porta C (che contiene una capra) è $1$ (poiché il conduttore deve aprire una porta con una capra, e la porta C è l'unica possibile).\n\nLa probabilità totale per questo esito è:\n\n$$\nP(\\text{Auto A, Scelta B, Apertura C}) = \\frac{1}{3} \\times \\frac{1}{3} \\times 1 = \\frac{1}{9}.\n$$\n\nProcedendo in modo simile per tutti gli altri esiti, otteniamo le probabilità per tutti i 12 esiti.\n\n**Passo 4: Calcolare la probabilità dell'evento**  \nLa probabilità di vincere cambiando porta è la somma delle probabilità degli esiti favorevoli. \n\n$$\n\\begin{aligned}\nP&(\\text{vincere cambiando porta}) = \\notag \\\\\n&\\quad P(\\text{Auto A, Scelta B, Apertura C}) + P(\\text{Auto A, Scelta C, Apertura B}) + \\notag\\\\  \n&\\quad P(\\text{Auto B, Scelta A, Apertura C}) + \\dots \\notag\n\\end{aligned}\n$$\n\n$$\n= \\frac{1}{9} + \\frac{1}{9} + \\frac{1}{9} + \\frac{1}{9} + \\frac{1}{9} + \\frac{1}{9} = \\frac{6}{9} = \\frac{2}{3}.\n$$\n\nLa probabilità di vincere mantenendo la scelta originale è il complemento:\n\n$$\nP(\\text{vincere mantenendo la scelta}) = 1 - P(\\text{vincere cambiando porta}) = 1 - \\frac{2}{3} = \\frac{1}{3}.\n$$\n\nLa conclusione è che il giocatore ha una probabilità di vincere pari a $\\frac{2}{3}$ se cambia porta, contro una probabilità di $\\frac{1}{3}$ se mantiene la sua scelta iniziale. Cambiare porta è quindi la strategia vincente. \n\n**Metodo 2: analisi delle probabilità.**\n\nIl problema di Monty Hall può essere chiarito analizzando i tre scenari possibili, immaginando di essere osservatori esterni che sanno cosa si nasconde dietro ogni porta:\n\n1. **Primo scenario**:  \n\n   - Il giocatore sceglie inizialmente la porta con una capra (chiamiamola \"capra 1\").  \n   - Il conduttore apre l'altra porta con la \"capra 2\".  \n   - Se il giocatore cambia porta, vince l'automobile.  \n\n2. **Secondo scenario**:  \n\n   - Il giocatore sceglie inizialmente la porta con l'altra capra (\"capra 2\").  \n   - Il conduttore apre la porta con la \"capra 1\".  \n   - Se il giocatore cambia porta, vince l'automobile.  \n\n3. **Terzo scenario**:  \n\n   - Il giocatore sceglie inizialmente la porta con l'automobile.  \n   - Il conduttore apre una delle due porte con una capra (non importa quale).  \n   - Se il giocatore cambia porta, perde l'automobile.  \n\nAll'inizio del gioco, il giocatore ha:  \n\n- *1/3 di probabilità* di scegliere l'automobile.  \n- *2/3 di probabilità* di scegliere una capra.  \n\nDopo la scelta iniziale, il conduttore apre una porta con una capra, ma questa azione non altera le probabilità iniziali. Il giocatore si trova quindi con due porte chiuse: quella scelta inizialmente e una rimanente.  \n\n- Se il giocatore ha scelto l'automobile inizialmente (1/3 di probabilità), cambiando porta perde.  \n- Se il giocatore ha scelto una capra inizialmente (2/3 di probabilità), cambiando porta vince l'automobile.  \n\nIn sintesi, cambiando porta, il giocatore ha *2/3 di probabilità* di vincere l'automobile, mentre mantenendo la scelta iniziale ha solo *1/3 di probabilità*. Pertanto, la strategia migliore è cambiare porta per massimizzare le possibilità di vittoria.\n\n**Metodo 3: simulazione.**\n\nPer confermare il risultato, possiamo eseguire una simulazione. Ripetendo il gioco migliaia di volte, possiamo confrontare la frequenza con cui il giocatore vince cambiando porta rispetto a quando mantiene la scelta iniziale.\n\nEcco un esempio di codice in R per la simulazione:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Numero di simulazioni da effettuare.\n# Più è grande B, più precisa sarà la stima.\nB <- 10000  \n\n# Definiamo una funzione \"monty_hall\" che\n# a) simula un gioco\n# b) restituisce TRUE/FALSE a seconda che il giocatore vinca l'auto o no.\nmonty_hall <- function(strategy){\n  \n  # 1. Dichiariamo le porte possibili, in forma di stringhe.\n  doors <- c(\"1\", \"2\", \"3\")\n  \n  # 2. Stabiliamo dove si trova il premio (auto) e le capre.\n  #    \"prize\" sarà un vettore con dentro \"car\" per la porta con l’auto \n  #    e \"goat\" per quelle con la capra.\n  #    La funzione sample() crea una distribuzione casuale di \"car\" e \"goat\".\n  prize <- sample(c(\"car\", \"goat\", \"goat\"))\n  \n  # 3. Troviamo qual è la porta che ha la macchina.\n  prize_door <- doors[ prize == \"car\" ]\n  \n  # 4. Il giocatore fa la sua prima scelta, pescando a caso fra le 3 porte.\n  my_pick <- sample(doors, 1)\n  \n  # 5. Il conduttore deve aprire una porta che:\n  #    - non sia la mia (my_pick)\n  #    - non abbia la macchina (prize_door)\n  #    Così facendo, rivela una porta con la capra.\n  #    Se ci sono due porte con capra, ne sceglie una a caso.\n  show <- sample(doors[!doors %in% c(my_pick, prize_door)], 1)\n  \n  # 6. La strategia \"stick\" significa: RESTARE sulla scelta iniziale (my_pick).\n  #    La strategia \"switch\" significa: CAMBIARE porta, passando a quella\n  #    rimasta tra le due che NON sono state aperte.\n  stick <- my_pick\n  switch <- doors[!doors %in% c(my_pick, show)]\n  \n  # 7. Se la strategia scelta (in input) è \"stick\", la mia scelta finale è \"stick\".\n  #    Altrimenti, è \"switch\".\n  final_choice <- ifelse(strategy == \"stick\", stick, switch)\n  \n  # 8. La funzione restituisce TRUE se la scelta finale coincide con la porta premiata,\n  #    altrimenti FALSE.\n  return(final_choice == prize_door)\n}\n```\n:::\n\n\nNel codice qui sopra:\n\n- `my_pick` è la porta che il giocatore sceglie subito.\n- `show` è la porta che il conduttore mostra, rivelando la capra.\n- `stick` rimane la scelta iniziale (quindi è my_pick).\n- `switch` è la porta che rimane fra le non aperte e non scelte inizialmente.\n\nAl termine, la funzione `monty_hall()` stabilisce se, con la strategia considerata, si vince (TRUE) o si perde (FALSE).\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Simuliamo B volte la strategia \"stick\" (non cambiare mai la scelta iniziale).\nstick_results <- replicate(B, monty_hall(\"stick\"))\n\n# stick_results è un vettore di TRUE/FALSE lungo B.\n# Per scoprire la percentuale di vittorie, calcoliamo la media dei TRUE.\nmean(stick_results)\n#> [1] 0.335\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Simuliamo B volte la strategia \"switch\" (cambiare sempre la scelta iniziale).\nswitch_results <- replicate(B, monty_hall(\"switch\"))\n\n# Anche qui, calcoliamo la media per sapere quante volte abbiamo vinto l’auto.\nmean(switch_results)\n#> [1] 0.666\n```\n:::\n\n\n- La media di un vettore di `TRUE/FALSE` in R è pari alla frazione di `TRUE`.\n- In questo modo, `mean(stick_results)` ci dice la probabilità di vincere restando sulla scelta iniziale.\n- `mean(switch_results)` ci dice la probabilità di vincere se si cambia sempre porta dopo l’intervento del conduttore.\n\nRisultati attesi:\n\n- *Mantenere la Scelta Iniziale*: La frequenza di vittoria dovrebbe essere circa 1/3 (33.3%).\n- *Cambiare Porta*: La frequenza di vittoria dovrebbe essere circa 2/3 (66.6%).\n\nLa simulazione conferma che cambiare porta aumenta la probabilità di vincere da 1/3 a 2/3, dimostrando che la strategia ottimale nel problema di Monty Hall è quella di cambiare porta dopo che il conduttore ha rivelato una capra.\n\nIn sintesi, il problema di Monty Hall mette in luce come l'intuizione possa trarci in inganno quando ci confrontiamo con scenari probabilistici. Attraverso l'uso del diagramma ad albero, un'analisi delle probabilità e l'esecuzione di simulazioni, abbiamo dimostrato che cambiare porta raddoppia le possibilità di vincita, facendole passare da 1/3 a 2/3. Questo risultato, in apparente contrasto con ciò che potrebbe sembrare intuitivo, costituisce un esempio emblematico dell'importanza di adottare un approccio formale nella valutazione delle probabilità, anziché affidarsi esclusivamente a impressioni iniziali che spesso si rivelano fuorvianti.\n:::\n\n::: {.callout-tip title=\"Il paradosso di Simpson\" collapse=\"true\"}\nNel contesto della *probabilità condizionata*, un fenomeno particolarmente interessante e, al tempo stesso, controintuitivo è il *paradosso di Simpson*. Questo paradosso si verifica quando una tendenza osservata in diversi gruppi di dati separati scompare o addirittura si inverte una volta che i gruppi vengono combinati.  \n\nIl paradosso di Simpson evidenzia l'importanza di considerare le *variabili confondenti* e di analizzare i dati con grande attenzione per evitare di trarre conclusioni errate o fuorvianti. È un esempio emblematico di come l'interpretazione dei dati statistici richieda non solo strumenti matematici, ma anche una profonda comprensione del contesto e delle relazioni tra le variabili coinvolte.  \n\nUn caso storico di paradosso di Simpson riguarda l’applicazione della *pena di morte* negli Stati Uniti [@RadeletPierce1991]. Questo studio analizza 674 processi per omicidio in Florida tra il 1976 e il 1987, esaminando l'influenza della razza dell'imputato e della vittima sulla probabilità di ricevere la pena di morte. I dati riportano il numero di condannati alla pena di morte in base alla razza dell'imputato e della vittima:  \n\n| Razza dell'imputato | Razza della vittima | Pena di morte | No pena di morte | Tasso di condanna |\n|---------------------|--------------------|--------------|-----------------|----------------|\n| Bianco             | Bianco             | 19           | 132             | 19 / 151 ≈ 12.6% |\n| Bianco             | Nero               | 11           | 52              | 11 / 63 ≈ 17.5% |\n| Nero               | Bianco             | 6            | 37              | 6 / 43 ≈ 14.0% |\n| Nero               | Nero               | 1            | 9               | 1 / 10 = 10.0% |\n\nSe analizziamo i dati separatamente per la razza della vittima, emerge che la probabilità di ricevere la pena di morte è più alta per gli imputati *bianchi* rispetto agli imputati *neri*, sia nei casi in cui la vittima era bianca (12.6% vs 14.0%) sia nei casi in cui la vittima era nera (17.5% vs 10.0%).  \n\nTuttavia, quando i dati vengono aggregati senza tenere conto della razza della vittima, si osserva una tendenza opposta:  \n\n| Razza dell'imputato | Pena di morte | No pena di morte | Tasso di condanna |\n|---------------------|--------------|-----------------|----------------|\n| Bianco             | 30           | 184             | 30 / 214 ≈ 14.0% |\n| Nero               | 7            | 46              | 7 / 53 ≈ 13.2% |\n\nAggregando i dati, sembra che gli *imputati neri abbiano meno probabilità di ricevere la pena di morte rispetto agli imputati bianchi* (13.2% vs 14.0%).  \n\nQuesta apparente contraddizione è il risultato del paradosso di Simpson. La variabile confondente in questo caso è la *razza della vittima*: gli omicidi con vittime bianche avevano una probabilità molto più alta di portare alla pena di morte rispetto agli omicidi con vittime nere. Poiché gli imputati bianchi erano più spesso accusati di aver ucciso vittime bianche (per cui la probabilità di pena di morte era maggiore), il loro tasso di condanna complessivo risultava più alto. Viceversa, gli imputati neri erano più spesso accusati di aver ucciso vittime nere (per cui la probabilità di pena di morte era inferiore), abbassando il loro tasso di condanna complessivo.  \n\nQuesto caso dimostra come l'aggregazione dei dati senza considerare una variabile confondente (in questo caso, la razza della vittima) possa portare a una conclusione errata e fuorviante. È essenziale analizzare i dati in modo stratificato per evitare interpretazioni distorte e per comprendere i reali meccanismi sottostanti un fenomeno.\n:::\n\n## Indipendenza e probabilità condizionata\n\nIl concetto di indipendenza tra due eventi $A$ e $B$ può essere caratterizzato in modo intuitivo attraverso la lente della probabilità condizionata. Due eventi sono indipendenti se il verificarsi di uno *non altera* la probabilità del verificarsi dell’altro. In altre parole, la conoscenza dell’esito di $B$ non fornisce alcuna informazione utile su $A$, e viceversa.\n\nFormalmente, questa condizione si esprime attraverso le relazioni:\n\n$$\nP(A \\mid B) = \\frac{P(A \\cap B)}{P(B)} = P(A),\n$$\n$$\nP(B \\mid A) = \\frac{P(A \\cap B)}{P(A)} = P(B).\n$$\nDi conseguenza, $A$ e $B$ sono indipendenti *se e solo se* vale una delle seguenti condizioni equivalenti:\n\n- $P(A \\mid B) = P(A)$,\n- $P(B \\mid A) = P(B)$,\n- $P(A \\cap B) = P(A) \\cdot P(B)$.\nQuesto implica che la probabilità di $A$ rimane invariata sia che $B$ si sia verificato o meno, e analogamente per $B$. L’indipendenza stocastica rappresenta dunque l’assenza completa di influenza reciproca tra i due eventi.\n\n### Indipendenza di tre eventi\n\nLa definizione di indipendenza si generalizza a tre eventi $A$, $B$ e $C$ richiedendo condizioni più stringenti rispetto al caso bivariato. Tre eventi si definiscono *completamente indipendenti* se:\n\n1. **Indipendenza a coppie**:\n   $$\n   \\begin{aligned}\n   P(A \\cap B) &= P(A) P(B), \\\\\n   P(A \\cap C) &= P(A) P(C), \\\\\n   P(B \\cap C) &= P(B) P(C).\n   \\end{aligned}\n   $$\n\n2. **Indipendenza dell'intersezione tripla**:\n   $$\n   P(A \\cap B \\cap C) = P(A) P(B) P(C).\n   $$\n\nLe prime tre condizioni garantiscono l'indipendenza tra ogni coppia di eventi, mentre la quarta condizione assicura che l'indipendenza sia valida anche per l'interazione simultanea dei tre eventi. È cruciale osservare che l'indipendenza a coppie *non implica* l'indipendenza completa: possono esistere esempi in cui le coppie sono indipendenti ma l'intersezione tripla non factorizza nel prodotto delle probabilità marginali.\n\nIn sintesi, l'indipendenza completa richiede che il verificarsi di qualsiasi sottoinsieme degli eventi non influenzi la probabilità degli altri. Questa proprietà semplifica notevolmente il calcolo delle probabilità congiunte ed è alla base di molti modelli probabilistici e statistici.\n\n::: {.callout-note collapse=\"true\" title=\"Esempio\"}\n**Indipendenza tra Eventi in un Mazzo di Carte**\n\n**Scenario 1: Mazzo Completo (52 Carte)**\n\nConsideriamo un mazzo standard di 52 carte. Ogni seme (picche, cuori, quadri, fiori) contiene 13 carte, e nel mazzo ci sono 4 Regine in totale. Definiamo i seguenti eventi:\n\n- $A$ = “Pescare una carta *di picche*”,  \n- $B$ = “Pescare una carta *Regina*”.\n\n1. **Probabilità di $A$**.  Poiché ci sono 13 picche in un mazzo di 52 carte, \n   $$\n   P(A) = \\frac{13}{52} = \\frac{1}{4}.\n   $$\n\n2. **Probabilità di $B$**.  Ci sono 4 Regine su 52 carte, quindi \n   $$\n   P(B) = \\frac{4}{52} = \\frac{1}{13}.\n   $$\n\n3. **Probabilità congiunta $P(A \\cap B)$**.  L’unica carta che è contemporaneamente “picche” e “Regina” è la Regina di picche, perciò:\n   $$\n   P(A \\cap B) = \\frac{1}{52}.\n   $$\n\nPer verificare l’indipendenza di $A$ e $B$, confrontiamo $P(A \\cap B)$ con $P(A)\\,P(B)$:\n\n$$\nP(A)\\,P(B) \n= \\frac{1}{4} \\times \\frac{1}{13} \n= \\frac{1}{52},\n$$\n$$\nP(A \\cap B) \n= \\frac{1}{52}.\n$$\n\nPoiché $P(A \\cap B) = P(A)\\,P(B)$, i due eventi *sono indipendenti* quando il mazzo è completo.\n\n**Scenario 2: Mazzo Ridotto (51 Carte)**\n\nOra rimuoviamo una carta qualunque dal mazzo — ad esempio il “2 di quadri” — portando il totale a 51 carte. Notiamo che la Regina di picche *non* è stata rimossa, ma il cambio di composizione potrebbe comunque influire sulle probabilità.\n\n1. **Probabilità di $A \\cap B$**.  Poiché la Regina di picche è ancora presente, pescare quella carta specifica ha ora probabilità\n   $$\n   P(A \\cap B) = \\frac{1}{51}.\n   $$\n\n2. **Probabilità di $A$**.  Il seme di picche non è stato modificato (restano 13 picche), ma il denominatore è passato a 51 carte:\n   $$\n   P(A) = \\frac{13}{51}.\n   $$\n\n3. **Probabilità di $B$**.  Nel mazzo restano ancora 4 Regine (nessuna è stata rimossa), su 51 carte totali:\n   $$\n   P(B) = \\frac{4}{51}.\n   $$\n\n4. **Prodotto $P(A)\\,P(B)$**.  Calcolando:\n   $$\n   P(A)\\,P(B)\n   = \\frac{13}{51} \\times \\frac{4}{51}\n   = \\frac{52}{2601}.\n   $$\n\nConfrontando:\n\n$$\nP(A \\cap B) \n= \\frac{1}{51},\n\\quad\\text{mentre}\\quad\nP(A)\\,P(B) \n= \\frac{52}{2601}.\n$$\n\nSi verifica che\n\n$$\n\\frac{1}{51} \n\\;\\neq\\; \n\\frac{52}{2601}.\n$$\n\nPertanto, *$A$ e $B$ non sono più indipendenti* nel mazzo ridotto.\n\n*In sintesi*, questo esempio mostra come l’indipendenza tra due eventi *dipenda dal contesto*:  \n\n- con un mazzo completo (52 carte), “pescare picche” e “pescare una Regina” sono eventi indipendenti; \n- basta rimuovere una carta qualunque (anche non correlata direttamente a “picche” o “Regine”) perché le probabilità cambino e gli stessi eventi *cessino di essere indipendenti*.  \n\nIn altre parole, *ogni modifica* alla composizione del mazzo può influire sulle probabilità dei singoli eventi e, di conseguenza, sulle loro relazioni di dipendenza o indipendenza.\n:::\n\n## Teorema del prodotto\n\nA partire dalla definizione di probabilità condizionata, si deriva il *Teorema del Prodotto* (noto anche come *regola della catena* o *regola moltiplicativa*). Questo teorema consente di esprimere la probabilità congiunta di due o più eventi come prodotto di probabilità condizionate.\n\n### Caso di due eventi\n\nPer due eventi $A$ e $B$, il Teorema del Prodotto afferma che:\n\n$$\nP(A \\cap B) = P(B) \\cdot P(A \\mid B) = P(A) \\cdot P(B \\mid A).\n$$ {#eq-probcondinv}\nIn altre parole, la probabilità che $A$ e $B$ si verifichino simultaneamente può essere calcolata in due modi equivalenti:\n\n- moltiplicando la probabilità di $B$ per la probabilità di $A$ dato $B$;\n- moltiplicando la probabilità di $A$ per la probabilità di $B$ dato $A$.\n\nLa scelta dell'ordine dipende dalla disponibilità delle probabilità condizionate o dalla struttura del problema.\n\n### Generalizzazione a $n$ eventi\n\nIl teorema si estende a $n$ eventi $A_1, A_2, \\dots, A_n$, assumendo che $P(A_1 \\cap A_2 \\cap \\cdots \\cap A_{n-1}) > 0$. In tal caso:\n\n$$\n\\begin{aligned}\nP(A_1 \\cap A_2 \\cap \\cdots \\cap A_n) = & \\, P(A_1) \\\\\n& \\cdot P(A_2 \\mid A_1) \\\\\n& \\cdot P(A_3 \\mid A_1 \\cap A_2) \\\\\n& \\, \\vdots \\\\\n& \\cdot P(A_n \\mid A_1 \\cap A_2 \\cap \\cdots \\cap A_{n-1}).\n\\end{aligned} \n$$ {#eq-probcomposte}\nOgni fattore rappresenta la probabilità di un evento condizionata al verificarsi di tutti gli eventi precedenti. Questa forma è particolarmente utile per modellare processi sequenziali o dipendenze condizionate.\n\n#### Procedura di applicazione\n\n1. *Inizia con la probabilità marginale* del primo evento: $P(A_1)$;\n2. *Moltiplica progressivamente* per le probabilità condizionate successive;\n3. *Includi l'ultimo termine*: $P(A_n \\mid A_1 \\cap \\cdots \\cap A_{n-1})$.\n\nIn sintesi, il Teorema del Prodotto riveste un ruolo fondamentale in molteplici contesti applicativi e teorici. In particolare, esso costituisce uno strumento essenziale nella *modellazione di processi stocastici sequenziali*, dove consente di calcolare la probabilità congiunta di eventi concatenati esprimendola come prodotto di probabilità condizionate lungo la sequenza. Inoltre, il teorema permette la *scomposizione di problemi complessi in fasi condizionate*, facilitando così l'analisi di scenari multivariati attraverso un approccio graduale e gerarchico. Infine, trova un'applicazione cruciale nella *costruzione di reti bayesiane e nell'inferenza probabilistica*, dove viene utilizzato per rappresentare e calcolare efficientemente le dipendenze condizionali tra variabili aleatorie, fornendo una base formale per l'aggiornamento delle credenze alla luce di nuove evidenze.\n\n::: {.callout-note collapse=\"true\" title=\"Esempio\"}\nDa un'urna contenente 6 palline bianche e 4 nere si estrae una pallina per volta, senza reintrodurla nell'urna. Indichiamo con $B_i$ l'evento: \"esce una pallina bianca alla $i$-esima estrazione\" e con $N_i$ l'estrazione di una pallina nera. L'evento: \"escono due palline bianche nelle prime due estrazioni\" è rappresentato dalla intersezione $\\{B_1 \\cap B_2\\}$ e, per l'@eq-probcondinv, la sua probabilità vale\n\n$$\nP(B_1 \\cap B_2) = P(B_1)P(B_2 \\mid B_1).\n$$\n\n$P(B_1)$ vale 6/10, perché nella prima estrazione $\\Omega$ è costituito da 10 elementi: 6 palline bianche e 4 nere. La probabilità condizionata $P(B_2 \\mid B_1)$ vale 5/9, perché nella seconda estrazione, se è verificato l'evento $B_1$, lo spazio campionario consiste di 5 palline bianche e 4 nere. Si ricava pertanto:\n\n$$\nP(B_1 \\cap B_2) = \\frac{6}{10} \\cdot \\frac{5}{9} = \\frac{1}{3}.\n$$\n\nIn modo analogo si ha che\n\n$$\nP(N_1 \\cap N_2) = P(N_1)P(N_2 \\mid N_1) = \\frac{4}{10} \\cdot \\frac{3}{9} = \\frac{4}{30}.\n$$\n\nSe l'esperimento consiste nell'estrazione successiva di 3 palline, la probabilità che queste siano tutte bianche, per l'@eq-probcomposte, vale\n\n$$\n\\begin{aligned}\nP(B_1 \\cap B_2 \\cap B_3) &=P(B_1)P(B_2 \\mid B_1)P(B_3 \\mid B_1 \\cap B_2) \\notag\\\\ \n&=\\frac{6}{10}\\cdot\\frac{5}{9} \\cdot\\frac{4}{8} \\notag\\\\ \n&= \\frac{1}{6}.\n\\end{aligned}\n$$\n\nLa probabilità dell'estrazione di tre palline nere è invece:\n\n$$\n\\begin{aligned}\nP(N_1 \\cap N_2 \\cap N_3) &= P(N_1)P(N_2 \\mid N_1)P(N_3 \\mid N_1 \\cap N_2)\\notag\\\\ \n&= \\frac{4}{10} \\cdot \\frac{3}{9} \\cdot \\frac{2}{8} \\notag\\\\ \n&= \\frac{1}{30}.\\notag\n\\end{aligned}\n$$\n:::\n\n## Teorema della probabilità totale\n\nIl *Teorema della Probabilità Totale* (noto anche come *legge della probabilità totale*) consente di calcolare la probabilità di un evento $A$ scomponendolo rispetto a una partizione dello spazio campionario. Questo approccio è particolarmente utile quando si considerano scenari multipli, categorie distinte o gruppi che formano una suddivisione esaustiva di $\\Omega$.\n\n### Enunciato formale\n\n::: {#def-}\nSia $\\{B_1, B_2, \\dots, B_n\\}$ una *partizione* di $\\Omega$, cioè una collezione di eventi tali che:\n\n1. *Mutua esclusività*: $B_i \\cap B_j = \\emptyset$ per ogni $i \\neq j$;\n2. *Copertura completa*: $\\bigcup_{i=1}^n B_i = \\Omega$.\n\nAllora, per qualsiasi evento $A \\subseteq \\Omega$, vale:\n\n$$\nP(A) = \\sum_{i=1}^n P(A \\cap B_i) = \\sum_{i=1}^n P(A \\mid B_i) \\cdot P(B_i). \n$$ {#eq-theorem-total-prob}\nIn pratica, $P(A)$ è una *media ponderata* delle probabilità condizionate $P(A \\mid B_i)$, con pesi dati dalle probabilità $P(B_i)$.\n:::\n\n### Caso particolare: partizione binaria\n\nQuando la partizione è composta da due eventi complementari $B$ e $B^c$, la formula assume la forma semplificata:\n\n$$\nP(A) = P(A \\mid B) \\cdot P(B) + P(A \\mid B^c) \\cdot P(B^c). \n$$ {#eq-prob-teorem-total-prob-two-part}\n\n::: {.callout-note collapse=\"true\" title=\"Esempio: accuratezza di un test medico\"}\nConsideriamo:\n\n- $B$: una persona è malata;\n- $B^c$: una persona è sana;\n- $A$: il test risulta positivo.\n\nLa probabilità di un test positivo è data da:\n\n$$\nP(A) = P(A \\mid B) \\cdot P(B) + P(A \\mid B^c) \\cdot P(B^c),\n$$\n\ndove:\n- $P(A \\mid B)$ è la sensibilità del test (probabilità di positivo se malati),\n- $P(A \\mid B^c)$ è il complemento a 1 della specificità (probabilità di falso positivo).\n:::\n\n### Applicazioni\n\n1. **Analisi stratificata**:  \n   Utile quando la popolazione è suddivisa in sottogruppi (es. fasce d’età, regioni geografiche). La probabilità di $A$ si calcola aggregando i contributi di ciascun gruppo.\n\n2. **Teorema di Bayes**:  \n   Il denominatore nella formula di Bayes è un’applicazione diretta di questo teorema, dove le ipotesi $H_1, \\dots, H_n$ formano una partizione dello spazio delle ipotesi.\n\n3. **Processi decisionali**:  \n   Consente di valutare la probabilità di un evento considerando tutti i possibili scenari o stati del mondo.\n\nIn sintesi, il teorema della probabilità totale permette di frammentare un problema complesso in componenti più gestibili, condizionate a elementi di una partizione, per poi ricombinarle in una soluzione completa.\n\n::: {.callout-note collapse=\"true\" title=\"Esempio\"}\n**Urne con Palline di Colori Diversi**  \n\nAbbiamo *3 urne*, ciascuna con 100 palline:\n\n- Urna 1: 75 rosse, 25 blu  \n- Urna 2: 60 rosse, 40 blu  \n- Urna 3: 45 rosse, 55 blu  \n\nL’urna viene scelta a caso (probabilità $1/3$ per ciascuna). Qual è la probabilità di estrarre una pallina *rossa*?\n\nDefinisco:\n\n- $R$: “Estraggo una pallina rossa”;  \n- $U_i$: “Seleziono l'Urna $i$”. \n\nLe urne $U_1, U_2, U_3$ costituiscono una partizione (disgiunte e coprenti $\\Omega$). Sappiamo:\n\n$$\nP(R \\mid U_1)=0.75,\n\\quad\nP(R \\mid U_2)=0.60,\n\\quad\nP(R \\mid U_3)=0.45.\n$$\n\nApplicando la probabilità totale:\n\n$$\n\\begin{aligned}\nP(R)\n&= P(R \\mid U_1)\\,P(U_1) + P(R \\mid U_2)\\,P(U_2) + P(R \\mid U_3)\\,P(U_3)\\\\\n&= 0.75 \\times \\tfrac13 + 0.60 \\times \\tfrac13 + 0.45 \\times \\tfrac13\n= 0.60.\n\\end{aligned}\n$$\n:::\n\n::: {.callout-note collapse=\"true\" title=\"Esempio\"}\n**Probabilità della Depressione in Diverse Fasce d’Età**  \n\nUna popolazione è suddivisa in *3 gruppi*: \n\n- giovani (30%), \n- adulti (40%),  \n- anziani (30%).\n\nLe probabilità *condizionate* di soffrire di depressione sono:\n\n$$\nP(D \\mid \\text{Giovane}) = 0.10, \\quad\nP(D \\mid \\text{Adulto}) = 0.20, \\quad\nP(D \\mid \\text{Anziano}) = 0.35.\n$$\n\nUsando la probabilità totale:\n\n$$\nP(D)\n= 0.10\\times0.30 + 0.20\\times0.40 + 0.35\\times0.30\n= 0.215.\n$$\n\nDunque, circa il 21.5% della popolazione totale soffre di depressione, combinando i tassi per ciascuna fascia.\n:::\n\n\n## Riflessioni conclusive {.unnumbered .unlisted}\n\nLa *probabilità condizionata* è uno dei concetti più importanti in statistica, poiché fornisce il quadro teorico per:\n\n- comprendere e formalizzare l’*indipendenza* tra eventi o variabili (assenza di ogni tipo di relazione); \n- espandere e generalizzare il calcolo delle probabilità (ad esempio, la *legge della probabilità totale*, che scompone in modo sistematico eventi complessi);  \n- alimentare metodi inferenziali avanzati, come il *Teorema di Bayes*.\n\nIn particolare, il *Teorema di Bayes* rappresenta uno strumento cardine dell’inferenza statistica: grazie alla probabilità condizionata, è possibile “aggiornare” in modo continuo le credenze sulle ipotesi (o sui parametri di un modello) alla luce di nuove osservazioni. Tale caratteristica di “apprendimento” graduale rende l’*inferenza bayesiana* flessibile e potente, ideale per affrontare situazioni in cui vengono resi disponibili dati aggiuntivi o in cui le condizioni iniziali possono cambiare.\n\nIn definitiva, la probabilità condizionata non solo chiarisce la nozione di indipendenza e getta le fondamenta di metodi inferenziali evoluti, ma soprattutto rappresenta il “motore” di modelli che si *adattano* dinamicamente alle nuove informazioni. Questa prospettiva “attiva” nell’aggiornamento delle probabilità è ciò che rende l’analisi statistica uno strumento versatile per descrivere e interpretare il mondo reale.\n\n\n::: {.callout-tip title=\"Esercizio\" collapse=\"true\"}\n**Esercizio 1: Soddisfazione con la Vita e Stress Accademico**\n\nUn gruppo di studenti ha compilato la **Satisfaction with Life Scale (SWLS)** e un questionario sullo stress accademico. Dai dati raccolti emerge che:\n\n- Il 40% degli studenti ha riportato un alto livello di stress accademico.\n- Il 60% degli studenti ha riportato un basso livello di stress accademico.\n- Tra gli studenti con alto stress, il 30% ha riportato una soddisfazione con la vita elevata.\n- Tra gli studenti con basso stress, il 70% ha riportato una soddisfazione con la vita elevata.\n\nCalcola la probabilità che uno studente scelto a caso abbia:\n\n1. Un alto livello di stress e una soddisfazione elevata.\n2. Una soddisfazione elevata.\n3. Un alto livello di stress, dato che ha una soddisfazione elevata.\n\n**Esercizio 2: Studio del Paradosso di Simpson**\n\nUn'università vuole valutare la relazione tra la frequenza di partecipazione alle lezioni e il successo negli esami finali. I dati raccolti mostrano che:\n\n| Gruppo | Studenti con alta frequenza | Superano l'esame | Non superano l'esame |\n|--------|---------------------------|----------------|-----------------|\n| A      | 40                        | 30             | 10              |\n| B      | 60                        | 20             | 40              |\n\n1. Calcola la probabilità di superare l'esame per ciascun gruppo separatamente.\n2. Calcola la probabilità totale di superare l'esame.\n3. Spiega se il Paradosso di Simpson si manifesta in questi dati.\n\n**Esercizio 3: Il Problema di Monty Hall**\n\nIn un quiz televisivo, un concorrente deve scegliere tra tre porte: dietro una c'è un'auto e dietro le altre due ci sono capre. Dopo la scelta iniziale, il conduttore, che sa cosa c'è dietro ogni porta, apre una delle due porte rimanenti rivelando una capra. Il concorrente ha ora la possibilità di cambiare la sua scelta.\n\n1. Qual è la probabilità di vincere l'auto se il concorrente **non cambia** la sua scelta?\n2. Qual è la probabilità di vincere l'auto se il concorrente **cambia** la sua scelta?\n3. Spiega perché cambiare porta è la strategia migliore.\n\n**Esercizio 4: Teorema della Probabilità Totale**\n\nUn'università ha tre dipartimenti: Psicologia, Economia e Ingegneria. Le proporzioni di studenti iscritti sono:\n\n- Psicologia: 40%\n- Economia: 35%\n- Ingegneria: 25%\n\nLa probabilità di laurearsi in tempo varia per ogni dipartimento:\n\n- Psicologia: 70%\n- Economia: 60%\n- Ingegneria: 80%\n\nCalcola la probabilità che uno studente scelto a caso si laurei in tempo.\n\n**Esercizio 5: Urne e Palline**\n\nUn'urna contiene 5 palline rosse e 7 blu. Si estrae una pallina, si osserva il colore e poi la pallina viene rimessa nell'urna. Quindi si estrae una seconda pallina.\n\n1. Qual è la probabilità di estrarre due palline rosse?\n2. Qual è la probabilità di estrarre almeno una pallina blu?\n3. Qual è la probabilità di estrarre una pallina rossa alla seconda estrazione, dato che la prima estratta era blu?\n:::\n\n::: {.callout-tip title=\"Soluzioni\" collapse=\"true\"}\n**Esercizio 1: Soddisfazione con la Vita e Stress Accademico**\n\n1. La probabilità che uno studente abbia **alto stress** e **soddisfazione elevata** si calcola moltiplicando la probabilità condizionata di avere soddisfazione elevata dato l'alto stress per la probabilità di avere alto stress:\n   \n   $$\n   P(S \\cap V) = P(V | S) P(S) = 0.30 \\times 0.40 = 0.12.\n   $$\n   \n2. La probabilità che uno studente abbia una **soddisfazione elevata**, indipendentemente dal livello di stress, si ottiene applicando la legge della probabilità totale:\n   \n   $$\n   P(V) = P(V | S) P(S) + P(V | \\neg S) P(\\neg S)\n   $$\n   \n   $$\n   = (0.30 \\times 0.40) + (0.70 \\times 0.60) = 0.12 + 0.42 = 0.54.\n   $$\n   \n3. La probabilità che uno studente abbia **alto stress** sapendo che ha una soddisfazione elevata si calcola utilizzando la formula della probabilità condizionata:\n   \n   $$\n   P(S | V) = \\frac{P(S \\cap V)}{P(V)} = \\frac{0.12}{0.54} \\approx 0.22.\n   $$\n\n**Esercizio 2: Studio del Paradosso di Simpson**\n\n1. $P(E | A) = \\frac{30}{40} = 0.75$, $P(E | B) = \\frac{20}{60} = 0.33$\n2. $P(E) = P(E | A) P(A) + P(E | B) P(B) = (0.75 \\times 0.40) + (0.33 \\times 0.60) = 0.30 + 0.198 = 0.498$\n3. Se i tassi di successo aggregati mostrano una relazione invertita, il Paradosso di Simpson si manifesta.\n\n**Esercizio 3: Il Problema di Monty Hall**\n\n1. $P(V | S) = \\frac{1}{3}$\n2. $P(V | C) = \\frac{2}{3}$\n3. Cambiare porta aumenta le probabilità di vincita da $1/3$ a $2/3$, quindi conviene sempre cambiare.\n\n**Esercizio 4: Teorema della Probabilità Totale**\n\n$P(L) = (0.70 \\times 0.40) + (0.60 \\times 0.35) + (0.80 \\times 0.25) = 0.28 + 0.21 + 0.20 = 0.69$\n\n**Esercizio 5: Urne e Palline**\n\n1. $P(R_1 \\cap R_2) = (5/12) \\times (5/12) = 25/144$\n2. $1 - P(R_1 \\cap R_2) = 1 - 25/144 = 119/144$\n3. $P(R_2 | B_1) = 5/12$\n:::\n\n::: {.callout-note collapse=true title=\"Informazioni sull'ambiente di sviluppo\"}\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsessionInfo()\n#> R version 4.5.1 (2025-06-13)\n#> Platform: aarch64-apple-darwin20\n#> Running under: macOS Tahoe 26.0\n#> \n#> Matrix products: default\n#> BLAS:   /Library/Frameworks/R.framework/Versions/4.5-arm64/Resources/lib/libRblas.0.dylib \n#> LAPACK: /Library/Frameworks/R.framework/Versions/4.5-arm64/Resources/lib/libRlapack.dylib;  LAPACK version 3.12.1\n#> \n#> locale:\n#> [1] C.UTF-8/UTF-8/C.UTF-8/C/C.UTF-8/C.UTF-8\n#> \n#> time zone: Europe/Rome\n#> tzcode source: internal\n#> \n#> attached base packages:\n#> [1] stats     graphics  grDevices utils     datasets  methods   base     \n#> \n#> other attached packages:\n#>  [1] pillar_1.11.1         tinytable_0.13.0      patchwork_1.3.2      \n#>  [4] ggdist_3.3.3          tidybayes_3.0.7       bayesplot_1.14.0     \n#>  [7] ggplot2_4.0.0         reliabilitydiag_0.2.1 priorsense_1.1.1     \n#> [10] posterior_1.6.1       loo_2.8.0             rstan_2.32.7         \n#> [13] StanHeaders_2.32.10   brms_2.23.0           Rcpp_1.1.0           \n#> [16] sessioninfo_1.2.3     conflicted_1.2.0      janitor_2.2.1        \n#> [19] matrixStats_1.5.0     modelr_0.1.11         tibble_3.3.0         \n#> [22] dplyr_1.1.4           tidyr_1.3.1           rio_1.2.3            \n#> [25] here_1.0.2           \n#> \n#> loaded via a namespace (and not attached):\n#>  [1] svUnit_1.0.8          tidyselect_1.2.1      farver_2.1.2         \n#>  [4] S7_0.2.0              fastmap_1.2.0         TH.data_1.1-4        \n#>  [7] tensorA_0.36.2.1      digest_0.6.37         timechange_0.3.0     \n#> [10] estimability_1.5.1    lifecycle_1.0.4       survival_3.8-3       \n#> [13] magrittr_2.0.4        compiler_4.5.1        rlang_1.1.6          \n#> [16] tools_4.5.1           knitr_1.50            bridgesampling_1.1-2 \n#> [19] htmlwidgets_1.6.4     curl_7.0.0            pkgbuild_1.4.8       \n#> [22] RColorBrewer_1.1-3    abind_1.4-8           multcomp_1.4-28      \n#> [25] withr_3.0.2           purrr_1.1.0           grid_4.5.1           \n#> [28] stats4_4.5.1          colorspace_2.1-1      xtable_1.8-4         \n#> [31] inline_0.3.21         emmeans_1.11.2-8      scales_1.4.0         \n#> [34] MASS_7.3-65           cli_3.6.5             mvtnorm_1.3-3        \n#> [37] rmarkdown_2.29        ragg_1.5.0            generics_0.1.4       \n#> [40] RcppParallel_5.1.11-1 cachem_1.1.0          stringr_1.5.2        \n#> [43] splines_4.5.1         parallel_4.5.1        vctrs_0.6.5          \n#> [46] V8_7.0.0              Matrix_1.7-4          sandwich_3.1-1       \n#> [49] jsonlite_2.0.0        arrayhelpers_1.1-0    systemfonts_1.2.3    \n#> [52] glue_1.8.0            codetools_0.2-20      distributional_0.5.0 \n#> [55] lubridate_1.9.4       stringi_1.8.7         gtable_0.3.6         \n#> [58] QuickJSR_1.8.0        htmltools_0.5.8.1     Brobdingnag_1.2-9    \n#> [61] R6_2.6.1              textshaping_1.0.3     rprojroot_2.1.1      \n#> [64] evaluate_1.0.5        lattice_0.22-7        backports_1.5.0      \n#> [67] memoise_2.0.1         broom_1.0.10          snakecase_0.11.1     \n#> [70] rstantools_2.5.0      gridExtra_2.3         coda_0.19-4.1        \n#> [73] nlme_3.1-168          checkmate_2.3.3       xfun_0.53            \n#> [76] zoo_1.8-14            pkgconfig_2.0.3\n```\n:::\n\n:::\n\n## Bibliografia {.unnumbered .unlisted}\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}