{
  "hash": "9c5da1ce2b70f7703519b47f5c047d44",
  "result": {
    "engine": "knitr",
    "markdown": "# Incertezza, dati e inferenza {#sec-prob-inference-uncertainty}\n\n## Introduzione {.unnumbered .unlisted}\n\nNella ricerca psicologica ci si trova costantemente di fronte all'incertezza. Desideriamo comprendere fenomeni complessi, come la prevalenza di un disturbo d'ansia, l'efficacia di un trattamento terapeutico o la relazione tra stress e prestazione cognitiva, ma non abbiamo mai accesso a informazioni complete. I dati che raccogliamo sono limitati: osserviamo un certo numero di partecipanti in contesti specifici utilizzando strumenti di misurazione imperfetti. \n\nCome possiamo quantificare la nostra incertezza sulle quantità di interesse a partire da queste osservazioni parziali? Come possiamo esprimere, in termini probabilistici, quanto siamo sicuri che la prevalenza di un disturbo rientri in un certo intervallo o che un trattamento sia efficace?\n\nQuesto capitolo affronta proprio queste fondamentali domande dell'inferenza statistica. L'approccio che adotteremo considera i parametri, ovvero le quantità che vogliamo conoscere, come proporzioni, medie o varianze, non come valori \"reali ma sconosciuti\" fissati da qualche entità esterna, ma come oggetti rispetto ai quali abbiamo incertezza, quantificabile attraverso distribuzioni di probabilità.\n\n## Due tipi di incertezza\n\nÈ utile ricordare qui che dobbiamo sempre distinguere due forme di incertezza che incontriamo nell'analisi dei dati:\n\n1. **Incertezza epistemica** (dal greco *episteme*, conoscenza): riguarda la nostra limitata conoscenza dei parametri del fenomeno che stiamo studiando; Non conosciamo con esattezza la proporzione di persone con un certo disturbo o la media di un punteggio in una popolazione. Questa incertezza può essere ridotta raccogliendo più dati.\n\n2. **Incertezza aleatoria**: riguarda la variabilità intrinseca dei fenomeni che osserviamo. Anche se conoscessimo perfettamente tutti i parametri di una distribuzione, le singole osservazioni future rimarrebbero comunque imprevedibili. Ad esempio, anche conoscendo il QI medio, pari a 100, con deviazione standard 15, non è possibile prevedere con esattezza il QI della prossima persona che sottoponiamo al test.\n\nIn questo capitolo ci concentreremo principalmente sull'*incertezza epistemica*, ovvero quella relativa ai parametri, e su come essa venga ridotta dalle osservazioni empiriche.\n\n### Un esempio concreto: stima della prevalenza di sintomi depressivi\n\nSupponiamo di voler determinare la prevalenza di sintomi depressivi clinicamente significativi nella popolazione studentesca universitaria. Data l'impraticabilità di valutare l'intera popolazione, adottiamo la seguente procedura:\n\n1. reclutiamo un campione di 200 studenti tramite un campionamento probabilistico;\n2. rileviamo che 72 partecipanti presentano sintomi depressivi clinicamente significativi;\n3. ci proponiamo di quantificare l'incertezza relativa al parametro $\\theta$, che rappresenta la prevalenza nella popolazione di riferimento.\n\n**L'approccio frequentista classico** concettualizza $\\theta$ come un valore fisso sebbene ignoto. Si procede calcolando una stima puntuale $\\hat{\\theta} = 72/200 = 0.36$ e costruendo un intervallo di confidenza al 95% che risulta essere [0.29, 0.43]. L'interpretazione di questo intervallo richiede una prospettiva controfattuale: se potessimo ripetere infinite volte il processo di campionamento e la costruzione dell'intervallo, il 95% di tali intervalli conterrebbe il valore del parametro vero $\\theta$.\n\n**L'approccio bayesiano**, invece, considera $\\theta$ come una quantità intrinsecamente incerta, rappresentabile attraverso una distribuzione di probabilità. Prima della raccolta dati, esprimiamo le nostre conoscenze preliminari attraverso una distribuzione a priori su $\\theta$. Dopo aver osservato i dati (72 casi su 200), aggiorniamo tale distribuzione ottenendo una distribuzione a posteriori. Da questa distribuzione a posteriori otteniamo un intervallo di credibilità al 95% [0.29; 0.43], la cui interpretazione risulta immediata: sulla base dei risultati osservati, riteniamo che esista una probabilità del 95% che il vero valore del parametro $\\theta$ nella popolazione si collochi tra 0.29 e 0.43.\n\nQuesta seconda interpretazione risulta notevolmente più intuitiva e naturalmente allineata con il modo in cui i ricercatori concepiscono l'incertezza nei processi inferenziali, fornendo una risposta diretta alla domanda di ricerca che ha motivato lo studio.\n\n### Panoramica del capitolo {.unnumbered .unlisted}\n\nIn questo capitolo esploreremo:\n\n- le proprietà matematiche fondamentali che governano come i dati riducono l'incertezza;\n- come quantificare l'incertezza sui parametri usando distribuzioni di probabilità;\n- il ruolo della quantità di dati nel determinare la precisione delle nostre inferenze;\n- la convergenza della nostra conoscenza verso la \"realtà\" al crescere delle osservazioni;\n- i limiti dell'inferenza statistica, indipendentemente dall'approccio adottato.\n\n::: {.callout-tip collapse=true}\n## Prerequisiti\n\n- Leggere il capitolo *Sampling Distributions of Estimators* [@schervish2014probability].\n:::\n\n::: {.callout-caution collapse=true title=\"Preparazione del Notebook\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhere::here(\"code\", \"_common.R\") |> \n  source()\n```\n:::\n\n:::\n\n\n## Dati, parametri e incertezza\n\n### Dati osservati e parametro di interesse\n\nSupponiamo di voler indagare la prevalenza di un sintomo d'ansia specifico all'interno della popolazione studentesca universitaria. L'obiettivo ideale sarebbe quello di determinare con esattezza la proporzione $\\theta$ di studenti che manifestano il sintomo. Tuttavia, l'osservazione completa della popolazione è impraticabile, costringendoci a una strategia indiretta:\n\n1. selezioniamo un campione rappresentativo di $n$ studenti;\n2. per ciascun partecipante, registriamo la presenza o l'assenza del sintomo attraverso una codifica binaria;\n3. sfruttiamo queste osservazioni campionarie per costruire un'inferenza probabilistica su $\\theta$.\n\nFormalizziamo le osservazioni mediante le variabili aleatorie $X_1, X_2, \\ldots, X_n$, dove ciascuna $X_i$ assume il valore:\n\n$$\nX_i = \n\\begin{cases}\n1 & \\text{se lo studente } i \\text{ presenta il sintomo} \\\\\n0 & \\text{in caso contrario}\n\\end{cases}\n$$\n\nQuesta rappresentazione ci permette di modellare matematicamente il processo di raccolta dei dati e di quantificare rigorosamente l'incertezza associata alla stima del parametro di interesse, $\\theta$.\n\n### Dalla statistica descrittiva all'inferenza probabilistica\n\nLa proporzione campionaria fornisce una sintesi descrittiva dei dati osservati:\n\n$$\n\\bar{X} = \\frac{1}{n}\\sum_{i=1}^n X_i = \\frac{\\text{numero di studenti con sintomo}}{n}.\n$$\n\nTuttavia, l'obiettivo scientifico va oltre la mera descrizione campionaria: desideriamo utilizzare $\\bar{X}$ per compiere inferenze sul parametro $\\theta$, che rappresenta la proporzione vera nella popolazione studentesca di riferimento.\n\nLa questione fondamentale diventa: in che modo il valore osservato di $\\bar{X}$ dovrebbe modificare la nostra incertezza riguardo a $\\theta$?\n\n### Il modello probabilistico di riferimento\n\nPer rispondere a questa domanda, costruiamo un modello probabilistico che metta in relazione:\n\n1. le osservazioni empiriche $X_1, \\ldots, X_n$;\n2. il parametro di interesse $\\theta$, soggetto a incertezza epistemica;\n3. la conoscenza pregressa disponibile prima della raccolta dei dati.\n\nAssumiamo che, condizionatamente al parametro $\\theta$, ciascuna osservazione segua una distribuzione di Bernoulli:\n\n$$\nX_i \\mid \\theta \\sim \\text{Bernoulli}(\\theta)\n$$\n\nQuesta assunzione implica che, se il valore di $\\theta$ fosse noto, la probabilità di osservare il sintomo in uno studente qualsiasi sarebbe esattamente $\\theta$.\n\n**Notazione condizionale e sua interpretazione**\n\nLa notazione $X_i \\mid \\theta$ indica che stiamo considerando la distribuzione della variabile $X_i$ nell'ipotesi che il parametro $\\theta$ sia fissato a un valore specifico. Questa formulazione non presuppone la conoscenza effettiva di $\\theta$, ma piuttosto struttura il nostro ragionamento ipotetico: \"se il valore di $\\theta$ fosse questo, allora le nostre osservazioni si comporterebbero in questo modo\".\n\n## Proprietà fondamentali della media campionaria\n\nPrima di affrontare l'inferenza bayesiana completa, è utile comprendere alcune proprietà matematiche che valgono indipendentemente dal framework inferenziale adottato. Queste proprietà ci dicono come la media campionaria $\\bar{X}$ si comporta in relazione al parametro $\\theta$.\n\n### Valore atteso della media campionaria\n\nSupponiamo di avere osservazioni $X_1, X_2, \\ldots, X_n$ **indipendenti e identicamente distribuite** (i.i.d.), ciascuna con valore atteso $\\mathbb{E}[X_i \\mid \\theta] = \\theta$.\n\n::: {#thm-expval-sample-mean}\nIl valore atteso della media campionaria è:\n\n$$\n\\mathbb{E}[\\bar{X} \\mid \\theta] = \\theta.\n$$\n:::\n\n::: {.proof}\nPartendo dalla definizione di media campionaria:\n\n$$\n\\bar{X} = \\frac{1}{n}\\sum_{i=1}^n X_i,\n$$\n\ncalcoliamo il valore atteso:\n\n$$\n\\mathbb{E}[\\bar{X} \\mid \\theta] = \\mathbb{E}\\left[\\frac{1}{n}\\sum_{i=1}^n X_i \\bigg| \\theta\\right].\n$$\n\nPer la linearità del valore atteso:\n\n$$\n= \\frac{1}{n}\\sum_{i=1}^n \\mathbb{E}[X_i \\mid \\theta].\n$$\n\nPoiché tutte le $X_i$ sono identicamente distribuite con $\\mathbb{E}[X_i \\mid \\theta] = \\theta$:\n\n$$\n= \\frac{1}{n} \\cdot n\\theta = \\theta.\n$$\n:::\n\n**Interpretazione**: questo risultato ci dice che la media campionaria è centrata sul valore del parametro. Non presenta un bias sistematico né verso l'alto né verso il basso. Questa proprietà è fondamentale per giustificare l'uso di $\\bar{X}$ come base per trarre inferenze su $\\theta$.\n\n::: {.callout-note}\n### Collegamento con l'inferenza bayesiana\n\nNel framework bayesiano, questo risultato implica che la distribuzione predittiva della media campionaria (prima di osservare i dati) sarà centrata sul valore atteso a priori di $\\theta$. Se la distribuzione a priori è uniforme o simmetrica, ci si aspetta che la media campionaria sia vicina al centro della distribuzione a priori.\n:::\n\n### Varianza della media campionaria\n\nLa seconda proprietà fondamentale riguarda la *variabilità* di $\\bar{X}$.\n\n::: {#thm-var-sample-mean}\nSe le osservazioni sono indipendenti con varianza $\\text{Var}(X_i \\mid \\theta) = \\sigma^2$, allora:\n\n$$\n\\text{Var}(\\bar{X} \\mid \\theta) = \\frac{\\sigma^2}{n}.\n$$\n:::\n\n::: {.proof}\nPartiamo dalla varianza della media campionaria:\n\n$$\n\\text{Var}(\\bar{X} \\mid \\theta) = \\text{Var}\\left(\\frac{1}{n}\\sum_{i=1}^n X_i \\bigg| \\theta\\right).\n$$\n\nUsando la proprietà $\\text{Var}(aY) = a^2\\text{Var}(Y)$:\n\n$$\n= \\frac{1}{n^2}\\text{Var}\\left(\\sum_{i=1}^n X_i \\bigg| \\theta\\right).\n$$\n\nPer l'indipendenza, la varianza della somma è la somma delle varianze:\n\n$$\n= \\frac{1}{n^2}\\sum_{i=1}^n \\text{Var}(X_i \\mid \\theta) = \\frac{1}{n^2} \\cdot n\\sigma^2 = \\frac{\\sigma^2}{n}.\n$$\n:::\n\n**Interpretazione cruciale**: questo risultato mostra che la variabilità di $\\bar{X}$ diminuisce con $n$. Più dati vengono raccolti, più $\\bar{X}$ diventa \"stabile\" e informativo su $\\theta$. La varianza diminuisce proporzionalmente a 1/n, quindi:\n\n- con $n=100$ dati, la varianza di $\\bar{X}$ è 1/100 della varianza delle singole osservazioni;\n- per dimezzare la deviazione standard di $\\bar{X}$, dobbiamo quadruplicare $n$.\n\n### Il caso Bernoulli\n\nPer variabili 0-1 (presenza/assenza di sintomo), abbiamo:\n\n$$\n\\text{Var}(X_i \\mid \\theta) = \\theta(1-\\theta).\n$$\n\nQuindi:\n\n$$\n\\text{Var}(\\bar{X} \\mid \\theta) = \\frac{\\theta(1-\\theta)}{n}.\n$$\n\nLa deviazione standard di $\\bar{X}$, spesso chiamata **errore standard**, è:\n\n$$\n\\text{SE}(\\bar{X}) = \\sqrt{\\frac{\\theta(1-\\theta)}{n}}.\n$$\n\nQuesta quantità misura quanto ci si aspetta che $\\bar{X}$ vari \"per caso\" se si potesse ripetere l'osservazione. Nel contesto bayesiano, contribuisce a determinare quanto i dati siano informativi: un errore standard più piccolo indica che i dati forniscono informazioni più precise su $\\theta$.\n\n::: {.callout-important}\n### Perché queste proprietà sono importanti per l'inferenza bayesiana\n\nAnche se si tratta di proprietà \"frequentiste\" (calcolate condizionatamente a $\\theta$), sono fondamentali per comprendere l'impatto dei dati sulla distribuzione a posteriori.\n\n1. **Centratura**: il fatto che $\\mathbb{E}[\\bar{X} \\mid \\theta] = \\theta$ garantisce che osservazioni ripetute non presentino un bias sistematico.\n\n2. **Precisione**: il fatto che $\\text{Var}(\\bar{X} \\mid \\theta) \\propto 1/n$ spiega perché la distribuzione a posteriori diventa più concentrata con l'aumentare dei dati.\n\n3. **Velocità di apprendimento**: la relazione $1/n$ ci dice quanto rapidamente riduciamo l'incertezza aggiungendo osservazioni.\n:::\n\n## Comprendere la variabilità dei dati\n\n### Il concetto di distribuzione campionaria\n\nImmaginiamo di poter (ipoteticamente) osservare molti campioni diversi dalla stessa popolazione, ciascuno di dimensione $n$. Per ognuno di essi calcoleremmo $\\bar{X}$, ottenendo valori diversi. La *distribuzione campionaria* di $\\bar{X}$ descrive come questi valori si distribuiscono.\n\nQuesto concetto teorico è estremamente utile per due motivi:\n\n1. *Nel paradigma frequentista* la distribuzione campionaria di $\\bar{X}$ serve per costruire intervalli di confidenza e test di ipotesi.\n\n2. *nel paradigma bayesiano* aiuta a comprendere come i dati influenzino la distribuzione a posteriori. La distribuzione campionaria contribuisce alla funzione di verosimiglianza, che è centrale nell'aggiornamento bayesiano.\n\n::: {.callout-note}\n### Reinterpretazione bayesiana\n\nNel framework bayesiano, non immaginiamo \"ripetizioni ipotetiche\" dell'esperimento. Invece, utilizziamo le proprietà della distribuzione campionaria per capire:\n\n- Quanto sono informativi i dati osservati?\n- Come dovrebbero modificare la nostra credenza su $\\theta$?\n- Quanto dovremmo essere sicuri della nostra conclusione?\n\nLa distribuzione campionaria è uno *strumento matematico* per quantificare l'informazione contenuta nei dati, non un concetto che richiede di immaginare esperimenti non condotti.\n:::\n\n### Esempio concreto: una popolazione finita\n\nPer rendere tutto più concreto, consideriamo un caso semplice: una popolazione di soli 4 valori.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nx <- c(2, 4.5, 5, 5.5)\nx\n#> [1] 2.0 4.5 5.0 5.5\n```\n:::\n\n\nCalcoliamo media e varianza di questa popolazione:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmean_x <- mean(x)  # Media\nvar_x <- var(x) * ((length(x) - 1) / length(x))  # Varianza\ncat(\"Media:\", mean_x, \"\\n\")\n#> Media: 4.25\ncat(\"Varianza:\", var_x, \"\\n\")\n#> Varianza: 1.81\n```\n:::\n\n\nOra consideriamo tutti i possibili campioni di dimensione $n=2$ (con reinserimento). Ci sono $4^2 = 16$ possibili coppie:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Generiamo tutte le coppie possibili\nsamples <- expand.grid(x, x)\nhead(samples, 10)\n#>    Var1 Var2\n#> 1   2.0  2.0\n#> 2   4.5  2.0\n#> 3   5.0  2.0\n#> 4   5.5  2.0\n#> 5   2.0  4.5\n#> 6   4.5  4.5\n#> 7   5.0  4.5\n#> 8   5.5  4.5\n#> 9   2.0  5.0\n#> 10  4.5  5.0\n```\n:::\n\n\nPer ogni coppia, calcoliamo la media:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsample_means <- rowMeans(samples)\nsample_means\n#>  [1] 2.00 3.25 3.50 3.75 3.25 4.50 4.75 5.00 3.50 4.75 5.00 5.25 3.75 5.00 5.25\n#> [16] 5.50\n```\n:::\n\n\nCreiamo un data frame per visualizzare:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndf <- data.frame(\n  Campione = apply(samples, 1, paste, collapse = \", \"),\n  Media = sample_means\n)\nhead(df, 10)\n#>    Campione Media\n#> 1      2, 2  2.00\n#> 2    4.5, 2  3.25\n#> 3      5, 2  3.50\n#> 4    5.5, 2  3.75\n#> 5    2, 4.5  3.25\n#> 6  4.5, 4.5  4.50\n#> 7    5, 4.5  4.75\n#> 8  5.5, 4.5  5.00\n#> 9      2, 5  3.50\n#> 10   4.5, 5  4.75\n```\n:::\n\n\nVisualizziamo la distribuzione di queste medie campionarie:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot(data.frame(sample_means), aes(x = sample_means)) +\n  geom_histogram(\n    bins = 7,\n    aes(y = after_stat(density)),\n    fill = \"lightblue\",\n    color = \"black\"\n  ) +\n  labs(\n    title = \"Distribuzione campionaria della media (n=2)\",\n    x = \"Media campionaria\",\n    y = \"Densità\"\n  )\n```\n\n::: {.cell-output-display}\n![](09_incertezza_inferenza_files/figure-html/unnamed-chunk-7-1.png){fig-align='center' width=85%}\n:::\n:::\n\n\nVerifichiamo le proprietà teoriche:\n\n\n::: {.cell layout-align=\"center\"}\n\n```\n#> Media delle medie campionarie: 4.25\n#> Media della popolazione: 4.25\n#> Varianza delle medie campionarie: 0.906\n#> Varianza teorica (σ²/n): 0.906\n```\n:::\n\n\nCome previsto dalla teoria:\n\n- la media delle medie campionarie coincide con la media della popolazione;\n- la varianza delle medie campionarie è $\\sigma^2/n$.\n\n::: {.callout-note}\n### Interpretazione per l'inferenza\n\nQuesta simulazione mostra concretamente perché, se osserviamo $\\bar{X} = 4.75$, possiamo essere ragionevolmente sicuri che il parametro sottostante sia vicino a quel valore. I valori di $\\bar{X}$ tendono a concentrarsi intorno al valore del parametro vero e tale concentrazione aumenta con $n$.\n\nNel contesto bayesiano, ciò giustifica il fatto che la distribuzione a posteriori di $\\theta$ sarà centrata sul valore osservato di $\\bar{X}$ con una dispersione che dipende da $n$.\n:::\n\n## Legge dei Grandi Numeri {#sec-lln}\n\nLa *Legge dei Grandi Numeri* (LGN) è uno dei pilastri della teoria della probabilità e ha profonde implicazioni per l'inferenza statistica, sia frequentista che bayesiana.\n\n### Enunciato intuitivo\n\nLa LGN afferma che, all'aumentare del numero di osservazioni $n$, la media campionaria $\\bar{X}_n$ converge al valore atteso $\\theta$:\n\n$$\n\\bar{X}_n \\xrightarrow{n \\to \\infty} \\theta.\n$$\n\nIn termini più precisi, esistono due forme:\n\n1. **Legge Debole**: $\\bar{X}_n$ converge a $\\theta$ *in probabilità*, cioè per ogni $\\varepsilon > 0$:\n   \n   $$\n   \\Pr\\bigl(|\\bar{X}_n - \\theta| > \\varepsilon \\mid \\theta\\bigr) \\to 0 \\quad \\text{quando } n \\to \\infty.\n   $$\n\n2. **Legge Forte**: $\\bar{X}_n$ converge a $\\theta$ *quasi certamente*, cioè:\n   \n   $$\n   \\Pr\\left(\\lim_{n \\to \\infty} \\bar{X}_n = \\theta \\bigg| \\theta\\right) = 1.\n   $$\n\n### Implicazioni per l'inferenza\n\n**Dal punto di vista frequentista**, la LGN garantisce che le stime basate su $\\bar{X}_n$ siano consistenti: con un numero sufficiente di dati, la stima converge al valore effettivo del parametro.\n\n**Dal punto di vista bayesiano**, la LGN ha un'interpretazione ancora più diretta: all'aumentare di $n$, la distribuzione a posteriori di $\\theta$ ddiventa sempre più concentrata attorno al valore vero, indipendentemente dalla prior iniziale, a condizione che questa assegni una massa positiva al valore vero.\n\nIn altre parole: *con sufficienti dati, anche credenze iniziali molto diverse convergono alla stessa conclusione*. Questo risultato è rassicurante e mostra la robustezza dell'inferenza bayesiana.\n\n### Simulazione della convergenza campionaria\n\nEsaminiamo un scenario in cui il parametro vero è $\\theta = 0.45$. Simuliamo campioni di dimensione crescente per osservare empiricamente il comportamento della media campionaria:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(42)\ntheta_true <- 0.45\nn_max <- 1000\n\n# Generazione delle osservazioni bernoulliane\nobservations <- rbinom(n_max, size = 1, prob = theta_true)\n\n# Calcolo delle medie cumulative\ncumulative_means <- cumsum(observations) / seq_along(observations)\n\n# Preparazione dei dati per la visualizzazione\ndata_plot <- data.frame(\n  n = 1:n_max,\n  mean = cumulative_means\n)\n\nggplot(data_plot, aes(x = n, y = mean)) +\n  geom_line(color = \"#4E79A7\", linewidth = 0.8, alpha = 0.8) +\n  geom_hline(yintercept = theta_true, \n             linetype = \"dashed\", \n             color = \"#E15759\",\n             linewidth = 1.2) +\n  geom_ribbon(aes(ymin = mean - 1.96 * sqrt(mean * (1 - mean) / n),\n                  ymax = mean + 1.96 * sqrt(mean * (1 - mean) / n)),\n              alpha = 0.2, fill = \"#4E79A7\") +\n  labs(\n    title = \"Convergenza della media campionaria verso il parametro vero\",\n    subtitle = \"Legge dei Grandi Numeri: stabilizzazione con l'aumentare delle osservazioni\",\n    x = \"Dimensione campionaria (n)\",\n    y = \"Media campionaria cumulativa\"\n  ) +\n  ylim(0.2, 0.7) +\n  theme_minimal() +\n  annotate(\"text\", x = 800, y = theta_true + 0.03, \n           label = paste(\"θ =\", theta_true), \n           color = \"#E15759\", size = 4.5)\n```\n\n::: {.cell-output-display}\n![](09_incertezza_inferenza_files/figure-html/unnamed-chunk-9-1.png){fig-align='center' width=85%}\n:::\n:::\n\n\n**Osservazioni empiriche**:\nnelle fasi iniziali del campionamento, la media campionaria $\\bar{X}_n$ presenta ampie e imprevedibili fluttuazioni, riflettendo l'elevata variabilità associata a piccole dimensioni del campione. Man mano che le osservazioni si accumulano, l'ampiezza delle oscillazioni diminuisce in modo sistematico. Una volta raggiunti campioni sufficientemente ampi, la media campionaria si stabilizza in prossimità del valore parametrico vero, dimostrando visivamente il principio di convergenza garantito dalla legge dei grandi numeri.\n\n::: {.callout-important}\n### Interpretazione bayesiana della legge dei grandi numeri\n\nNel quadro concettuale bayesiano, la legge dei grandi numeri rivela una proprietà fondamentale: con un numero sufficiente di dati, l'evidenza empirica finisce per prevalere su qualsiasi credenza a priori ragionevole.\n\nQuesto principio funziona nel modo seguente: quando due ricercatori partono da convinzioni iniziali diverse ma ragionevoli, nel senso che nessuna delle due esclude completamente il valore vero del parametro, e osservano la stessa serie di dati empirici, le loro distribuzioni a posteriori convergeranno progressivamente verso conclusioni sostanzialmente identiche man mano che il campione aumenta.\n\nQuesto risultato ha un'importanza epistemologica notevole, in quanto dimostra che la metodologia bayesiana possiede un carattere intrinsecamente auto-correttivo. Gli eventuali errori contenuti nelle credenze iniziali vengono progressivamente attenuati e infine sovrascritti dall'accumularsi sistematico dell'evidenza sperimentale, garantendo che, nel lungo periodo, il processo inferenziale converga verso conclusioni robuste e indipendenti dalle convinzioni iniziali.\n:::\n\n### Applicazioni in psicologia\n\nLa Legge dei Grandi Numeri ha rilevanti implicazioni per la ricerca psicologica.\n\nGli *studi pilota*, caratterizzati tipicamente da dimensioni campionarie ridotte, producono stime soggette a notevole variabilità. Ciò spiega perché le replicazioni con campioni più ampi tendono a generare risultati più stabili e affidabili dal punto di vista metodologico.\n\nLe *meta-analisi* sfruttano implicitamente questo principio combinando le evidenze di molti studi, aumentando virtualmente la dimensione del campione complessivo e riducendo l'incertezza associata alla stima degli effetti.\n\nNei *disegni longitudinali*, l'osservazione ripetuta nel tempo degli stessi fenomeni permette di ridurre progressivamente l'incertezza riguardante le caratteristiche relativamente stabili dei costrutti indagati.\n\nTuttavia, la legge dei grandi numeri rappresenta solo una componente del quadro teorico necessario. Il *Teorema del Limite Centrale* completa questa visione, fornendo informazioni cruciali sulla forma distributiva della media campionaria $\\bar{X}_n$ e permettendo di determinare non solo dove converge la stima, ma anche come l'incertezza si distribuisce attorno a tale valore.\n\n## Teorema del Limite Centrale\n\nIl Teorema del Limite Centrale costituisce uno dei pilastri concettuali più profondi della teoria della probabilità, con conseguenze metodologiche di ampia portata per la statistica inferenziale.\n\n### Enunciato formale\n\n::: {#thm-clt}\nSiano $X_1, X_2, \\ldots, X_n$ variabili aleatorie indipendenti e identicamente distribuite con valore atteso $\\mu$ e varianza $\\sigma^2$ finite. Allora, al crescere di $n$, la distribuzione della media campionaria $\\bar{X}_n$ converge verso una distribuzione normale:\n\n$$\n\\bar{X}_n \\;\\dot\\sim\\; \\mathcal{N}\\left(\\mu, \\frac{\\sigma^2}{n}\\right)\n$$\n\ndove la notazione $\\dot\\sim$ indica \"approssimativamente distribuito come\" per $n$ sufficientemente grande.\n:::\n\n### Portata concettuale\n\nLa proprietà sorprendente del teorema risiede nel fatto che la media di numerose variabili indipendenti tende a distribuirsi secondo una legge normale *indipendentemente dalla forma della distribuzione delle variabili originarie*. Questo principio di universalità si applica a un'ampia gamma di situazioni:\n\n- variabili uniformemente distribuite;\n- variabili con distribuzione esponenziale;\n- variabili binarie dicotomiche:\n- distribuzioni marcatamente asimmetriche.\n\nIn tutti questi casi, la distribuzione della media campionaria tende sistematicamente verso la distribuzione normale, fornendo una solida base teorica per molteplici procedure inferenziali ampiamente utilizzate nella ricerca psicologica.\n\n### Visualizzazione del TLC\n\nConsideriamo una popolazione con distribuzione uniforme (chiaramente non normale):\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(42)\npopulation <- runif(5000, min = 0, max = 1)\n\n# Istogramma della popolazione\nggplot(data.frame(population), aes(x = population)) +\n  geom_histogram(\n    aes(y = after_stat(density)),\n    bins = 30,\n    fill = \"lightblue\",\n    color = \"black\"\n  ) +\n  labs(\n    title = \"Distribuzione della popolazione (uniforme)\",\n    x = \"Valore\",\n    y = \"Densità\"\n  )\n```\n\n::: {.cell-output-display}\n![](09_incertezza_inferenza_files/figure-html/unnamed-chunk-10-1.png){fig-align='center' width=85%}\n:::\n:::\n\n\nOra estraiamo 300 campioni, ciascuno di dimensione $n=30$, e calcoliamo le medie:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsample_size <- 30\nnum_samples <- 300\n\nsample_means <- replicate(num_samples, {\n  sample_data <- sample(population, size = sample_size, replace = TRUE)\n  mean(sample_data)\n})\n\n# Media e deviazione standard delle medie campionarie\nx_bar <- mean(sample_means)\nstd <- sd(sample_means)\n\ncat(\"Media delle medie campionarie:\", x_bar, \"\\n\")\n#> Media delle medie campionarie: 0.501\ncat(\"Dev. standard delle medie:\", std, \"\\n\")\n#> Dev. standard delle medie: 0.0524\n```\n:::\n\n\nConfrontiamo con i valori teorici:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmu <- mean(population)\nsigma <- sd(population)\n\ncat(\"\\nValori teorici della popolazione:\\n\")\n#> \n#> Valori teorici della popolazione:\ncat(\"Media:\", mu, \"\\n\")\n#> Media: 0.503\ncat(\"Dev. standard delle medie (σ/√n):\", sigma / sqrt(sample_size), \"\\n\")\n#> Dev. standard delle medie (σ/√n): 0.0531\n```\n:::\n\n\nVisualizziamo la distribuzione delle medie campionarie con la curva normale teorica sovrapposta:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot(data.frame(sample_means), aes(x = sample_means)) +\n  geom_histogram(\n    aes(y = after_stat(density)),\n    bins = 30,\n    fill = \"lightblue\",\n    color = \"black\",\n    alpha = 0.7\n  ) +\n  stat_function(\n    fun = dnorm, \n    args = list(mean = x_bar, sd = std),\n    color = \"red\",\n    linewidth = 1.2\n  ) +\n  labs(\n    title = \"Distribuzione delle medie campionarie\",\n    subtitle = \"La curva rossa è la distribuzione normale teorica\",\n    x = \"Media campionaria\",\n    y = \"Densità\"\n  )\n```\n\n::: {.cell-output-display}\n![](09_incertezza_inferenza_files/figure-html/unnamed-chunk-13-1.png){fig-align='center' width=85%}\n:::\n:::\n\n\n**Osservazione**: nonostante la popolazione sia uniforme (non normale), la distribuzione delle medie è approssimativamente normale.\n\n### Implicazioni per l'inferenza bayesiana\n\nIl Teorema del Limite Centrale ha un'influenza profonda sulla pratica dell'inferenza bayesiana, con conseguenze sia teoriche che applicative di ampia portata.\n\nIn contesti con ampi campioni, la distribuzione a posteriori tende a convergere verso una forma gaussiana, a prescindere dalla configurazione della distribuzione a priori, a condizione che quest'ultima sia sufficientemente regolare da non escludere valori plausibili del parametro. Questa proprietà di regolarità asintotica conferisce robustezza al metodo bayesiano, attenuando l'impatto delle specifiche scelte prior quando si dispone di un'abbondante evidenza empirica.\n\nQuesto risultato giustifica l'uso di approssimazioni gaussiane per la distribuzione a posteriori in molte applicazioni pratiche, semplificando notevolmente i calcoli in situazioni in cui forme analitiche esatte risulterebbero complesse o intrattabili. L'approssimazione gaussiana rende accessibili una vasta gamma di strumenti analitici sviluppati per la distribuzione normale.\n\nUna conseguenza pratica di particolare rilevanza riguarda la costruzione di intervalli di credibilità. Con campioni di dimensioni consistenti, è possibile determinare gli intervalli di credibilità bayesiani utilizzando i quantili della distribuzione normale, anche quando il modello sottostante presenta una struttura complessa. Questo approccio approssimato conserva le proprietà probabilistiche desiderate, offrendo al contempo notevoli vantaggi computazionali.\n\n### Esempio bayesiano con il Teorema del Limite Centrale\n\nConsideriamo un contesto di ricerca in psicologia clinica in cui si studia la prevalenza di un particolare sintomo. Supponiamo di adottare un prior uniforme per il parametro $\\theta$ compreso tra 0 e 1, rappresentante la proporzione nella popolazione, e di osservare un campione di 100 soggetti, tra i quali 45 manifestano il sintomo.\n\nPer la dimensione del campione considerata, la distribuzione a posteriori può essere approssimata efficacemente mediante una distribuzione normale:\n\n$$\n\\theta \\mid y \\;\\dot\\sim\\; \\mathcal{N}\\left(\\frac{45}{100}, \\frac{0.45 \\times 0.55}{100}\\right)\n$$\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Parametri osservati\nn <- 100\ny <- 45\np_hat <- y / n\n\n# Approssimazione normale della posteriore\nposterior_mean <- p_hat\nposterior_sd <- sqrt(p_hat * (1 - p_hat) / n)\n\ncat(\"Media a posteriori (approssimata):\", posterior_mean, \"\\n\")\n#> Media a posteriori (approssimata): 0.45\ncat(\"Deviazione standard a posteriori:\", round(posterior_sd, 4), \"\\n\")\n#> Deviazione standard a posteriori: 0.0497\n\n# Intervallo di credibilità al 95%\nlower <- qnorm(0.025, mean = posterior_mean, sd = posterior_sd)\nupper <- qnorm(0.975, mean = posterior_mean, sd = posterior_sd)\n\ncat(\"\\nIntervallo di credibilità 95%: [\", round(lower, 3), \",\", round(upper, 3), \"]\\n\")\n#> \n#> Intervallo di credibilità 95%: [ 0.352 , 0.548 ]\n```\n:::\n\n\nLa visualizzazione della distribuzione a posteriori approssimata risulta particolarmente illuminante:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ntheta_grid <- seq(0.25, 0.65, length.out = 1000)\nposterior_density <- dnorm(theta_grid, mean = posterior_mean, sd = posterior_sd)\n\nggplot(data.frame(theta = theta_grid, density = posterior_density), \n       aes(x = theta, y = density)) +\n  geom_line(linewidth = 1.2, color = \"#2E86AB\") +\n  geom_area(aes(x = theta, y = density), \n            data = subset(data.frame(theta = theta_grid, density = posterior_density),\n                         theta >= lower & theta <= upper),\n            fill = \"#A23B72\", alpha = 0.3) +\n  geom_vline(xintercept = c(lower, upper), \n             linetype = \"dashed\", \n             color = \"#F18F01\", size = 0.8) +\n  labs(\n    title = \"Approssimazione normale della distribuzione a posteriori\",\n    subtitle = \"Intervallo di credibilità al 95% per la proporzione del sintomo\",\n    x = \"θ (proporzione nella popolazione)\",\n    y = \"Densità a posteriori\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](09_incertezza_inferenza_files/figure-html/unnamed-chunk-15-1.png){fig-align='center' width=85%}\n:::\n:::\n\n\n**Interpretazione dell'intervallo di credibilità**\n\nL'intervallo [0.352, 0.548] può essere interpretato in modo probabilistico diretto: alla luce dei dati osservati, si può affermare che c'è una probabilità del 95% che la vera proporzione nella popolazione si collochi tra il 35.2% e il 54.8%. Questa interpretazione è più intuitiva e coerente con il modo in cui i ricercatori concepiscono l'incertezza parametrica, a differenza degli intervalli di confidenza frequentisti che presuppongono una concezione basata su ripetizioni campionarie ipotetiche.\n\n## Precisione, informazione ed errore standard\n\n### L'errore standard: prospettive interpretative\n\nL'*errore standard* di una statistica rappresenta convenzionalmente la deviazione standard della sua distribuzione campionaria. Nel caso della media campionaria, questa quantità assume la forma:\n\n$$\n\\text{SE}(\\bar{X}) = \\sqrt{\\frac{\\sigma^2}{n}}\n$$\n\nTale misura ammette due letture complementari che riflettono differenti filosofie inferenziali:\n\n**Prospettiva frequentista.**  \nL'errore standard quantifica l'ampiezza della variazione che ci aspetteremmo nella media campionaria se potessimo replicare infinite volte il medesimo disegno di ricerca in condizioni identiche. Esso misura dunque la variabilità intrinseca imputabile al processo di campionamento casuale.\n\n**Prospettiva bayesiana e informazionale.**  \nIn questa visione, l'errore standard misura il grado di informazione contenuta nei dati riguardo al parametro di interesse. Un errore standard ridotto segnala che i dati forniscono evidenza precisa su $\\theta$, risultando in una distribuzione a posteriori concentrata attorno alla stima. Al contrario, un errore standard ampio indica dati scarsamente informativi, che si traducono in una distribuzione a posteriori più dispersa.\n\nLa seconda interpretazione presenta il vantaggio di non richiedere l'artificio concettuale delle ripetizioni campionarie ipotetiche, offrendo una comprensione più immediata dell'incertezza nell'inferenza che risulta particolarmente utile nella pratica della ricerca applicata.\n\n### Precisione come inverso della varianza\n\nNell'ambito della statistica bayesiana, risulta particolarmente utile concettualizzare l'incertezza attraverso la nozione di *precisione*, definita come il reciproco della varianza:\n\n$$\n\\text{Precisione} = \\frac{1}{\\text{Varianza}}.\n$$\n\nApplicando questo concetto alla media campionaria, otteniamo:\n\n$$\n\\text{Precisione}(\\bar{X} \\mid \\theta) = \\frac{n}{\\sigma^2}.\n$$\n\nQuesta formulazione rivela una proprietà notevole: la precisione cresce in proporzione diretta con la dimensione campionaria $n$. Tale relazione lineare risulta più intuitiva del corrispondente andamento della varianza, che decresce secondo il fattore $1/n$.\n\n**Precisione nella modellistica bayesiana.**\n\nMolti modelli bayesiani adottano esplicitamente la precisione come parametro fondamentale. La distribuzione normale, ad esempio, viene frequentemente parametrizzata nella forma:\n\n$$\nX \\sim \\mathcal{N}(\\mu, \\tau),\n$$\n\ndove $\\tau = 1/\\sigma^2$ rappresenta la precisione. Questa scelta parametrica illumina due principi fondamentali:\n\n- un valore di precisione elevato corrisponde a un grado di incertezza ridotto;\n- la combinazione di informazioni provenienti da fonti indipendenti si realizza attraverso la semplice somma delle rispettive precisioni, operazione che risulterebbe notevolmente più complessa se espressa in termini di varianze.\n\n### Combinazione di informazioni: integrazione tra conoscenza pregressa ed evidenza empirica\n\nUn aspetto particolarmente elegante del framework bayesiano risiede nella sua capacità di integrare in modo naturale diverse fonti di informazione. Consideriamo due componenti fondamentali:\n\n- la distribuzione a priori, che riflette il grado di conoscenza preesistente riguardo al parametro di interesse, possiede una precisione $\\tau_0$;\n- i dati osservati esibiscono una precisione $n/\\sigma^2$, che quantifica l'informatività dell'evidenza empirica raccolta.\n\nLa precisione della distribuzione a posteriori emerge allora come semplice somma delle due componenti:\n\n$$\n\\tau_{\\text{post}} = \\tau_0 + \\frac{n}{\\sigma^2}\n$$\n\nQuesta relazione formalizza in modo particolarmente chiaro il processo di accumulo della conoscenza: ogni nuova osservazione contribuisce ad aumentare la precisione complessiva della nostra inferenza, rafforzando progressivamente la nostra comprensione del fenomeno in esame.\n\n### Esempio: sintesi delle evidenze da studi multipli\n\nConsideriamo due studi psicologici che indagano lo stesso costrutto, $\\theta$, ma che presentano dimensioni campionarie e precisioni differenti:\n\n**Studio A**: $n_A = 50$, $\\bar{X}_A = 0.42$, $\\text{SE}_A = 0.07$  \n**Studio B**: $n_B = 200$, $\\bar{X}_B = 0.38$, $\\text{SE}_B = 0.035$\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Parametri degli studi\nn_A <- 50; x_bar_A <- 0.42; se_A <- 0.07\nn_B <- 200; x_bar_B <- 0.38; se_B <- 0.035\n\n# Calcolo delle precisioni\nprecision_A <- 1 / se_A^2\nprecision_B <- 1 / se_B^2\n\ncat(\"Precisione Studio A:\", round(precision_A, 2), \"\\n\")\n#> Precisione Studio A: 204\ncat(\"Precisione Studio B:\", round(precision_B, 2), \"\\n\")\n#> Precisione Studio B: 816\ncat(\"Rapporto di precisione B/A:\", round(precision_B / precision_A, 2), \"\\n\")\n#> Rapporto di precisione B/A: 4\n```\n:::\n\n\nLo studio B presenta una precisione approssimativamente quadrupla rispetto allo studio A, risultato coerente con la sua dimensione campionaria quattro volte superiore.\n\nProcedendo con una sintesi bayesiana dei due studi:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Combinazione delle informazioni\nprecision_combined <- precision_A + precision_B\nmean_combined <- (precision_A * x_bar_A + precision_B * x_bar_B) / precision_combined\nse_combined <- sqrt(1 / precision_combined)\n\ncat(\"Stima combinata:\", round(mean_combined, 3), \"\\n\")\n#> Stima combinata: 0.388\ncat(\"Errore standard combinato:\", round(se_combined, 4), \"\\n\")\n#> Errore standard combinato: 0.0313\ncat(\"\\nIntervallo di credibilità 95% per la sintesi:\\n\")\n#> \n#> Intervallo di credibilità 95% per la sintesi:\ncat(\"[\", round(mean_combined - 1.96*se_combined, 3), \",\",\n    round(mean_combined + 1.96*se_combined, 3), \"]\\n\")\n#> [ 0.327 , 0.449 ]\n```\n:::\n\n\nLa stima combinata risulta più prossima al valore osservato nello studio B, riflettendo il maggiore contributo informativo di questo studio, dovuto alla sua maggiore precisione. Questo esempio illustra come l'approccio bayesiano pesi automaticamente le prove in base alla loro affidabilità, producendo una sintesi ottimale delle informazioni disponibili.\n\n## Oltre la media: altre statistiche di interesse psicologico\n\nL'attenzione si è finora concentrata sulla media campionaria, ma la ricerca psicologica coinvolge frequentemente altre quantità di interesse. Esaminiamo due casi di particolare rilevanza.\n\n### Il massimo campionario\n\nIn diversi contesti psicologici, l'interesse si rivolge ai valori estremi piuttosto che a quelli centrali. Esempi includono:\n\n- il tempo di reazione minimo registrato in un compito cognitivo;\n- il punteggio massimo ottenuto in una prova di abilità;\n- la performance ottimale osservata in condizioni di stress acuto.\n\n::: {#def-}\nDato un campione $X_1, \\ldots, X_n$, il **massimo campionario** è definito come:\n\n$$\nM = \\max\\{X_1, \\ldots, X_n\\}\n$$\n:::\n\n**Proprietà distintive**:\n\n- la distribuzione di $M$ presenta tipicamente asimmetria positiva;\n- il valore atteso $\\mathbb{E}[M]$ eccede sistematicamente la media della popolazione $\\mu$.\n- all'aumentare della dimensione campionaria $n$, $M$ converge verso valori progressivamente più estremi.\n\n#### Simulazione esplorativa\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(123)\nmu <- 100; sigma <- 15\nn_sims <- 10000\nsample_size <- 5\n\n# Simulazione dei massimi campionari\nsample_maxes <- replicate(n_sims, max(rnorm(sample_size, mean = mu, sd = sigma)))\n\n# Preparazione per la visualizzazione\nx_grid <- seq(mu - 3*sigma, mu + 3*sigma, length.out = 200)\nnormal_density <- dnorm(x_grid, mean = mu, sd = sigma)\n\nggplot() +\n  geom_histogram(\n    data = data.frame(maxes = sample_maxes),\n    aes(x = maxes, y = after_stat(density)),\n    bins = 30,\n    fill = \"#4E79A7\",\n    color = \"white\",\n    alpha = 0.8\n  ) +\n  geom_line(\n    data = data.frame(x = x_grid, y = normal_density),\n    aes(x = x, y = y),\n    color = \"#E15759\",\n    linewidth = 1.2,\n    linetype = \"dashed\"\n  ) +\n  geom_vline(xintercept = mean(sample_maxes), \n             color = \"#2E5984\", \n             linetype = \"solid\",\n             size = 1) +\n  annotate(\"text\", x = mean(sample_maxes) + 5, y = 0.03,\n           label = paste(\"Media massimi =\", round(mean(sample_maxes), 1)),\n           color = \"#2E5984\", hjust = 0) +\n  labs(\n    title = \"Distribuzione del massimo campionario per n=5\",\n    subtitle = \"Confronto con la distribuzione normale della popolazione (linea tratteggiata)\",\n    x = \"Valore del massimo osservato\",\n    y = \"Densità\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](09_incertezza_inferenza_files/figure-html/unnamed-chunk-18-1.png){fig-align='center' width=85%}\n:::\n:::\n\n\nLa distribuzione dei massimi campionari evidenzia uno spostamento marcato verso destra rispetto alla distribuzione della popolazione, confermando la natura non normale di questa statistica nonostante l'origine gaussiana delle osservazioni.\n\n**Implicazioni inferenziali**\n\nQuando l'obiettivo della ricerca riguarda parametri legati agli estremi distributivi, come nel caso della determinazione del novantacinquesimo percentile della distribuzione dei tempi di reazione, l'applicazione diretta del Teorema del Limite Centrale risulta inappropriata. In questi contesti, è necessario ricorrere a modelli statistici specificamente sviluppati per i valori estremi, come quelli forniti dalla teoria dei valori estremi.\n\nL'approccio bayesiano mantiene comunque la sua validità anche in questi scenari complessi: è possibile specificare distribuzioni a priori per i parametri di interesse e aggiornarle sulla base dei dati osservati, ricorrendo eventualmente a metodi computazionali avanzati come le catene di Markov di Monte Carlo quando le soluzioni analitiche non sono disponibili.\n\n### La varianza campionaria\n\nUn'altra statistica di fondamentale importanza è la *varianza campionaria*, che quantifica la dispersione delle osservazioni attorno al loro valore centrale.\n\n::: {#def-}\nLa varianza campionaria è definita come:\n\n$$\nS^2 = \\frac{1}{n-1}\\sum_{i=1}^n (X_i - \\bar{X})^2.\n$$\n\nLa scelta del denominatore $n-1$ costituisce una correzione per ottenere uno stimatore non distorto della varianza della popolazione: $\\mathbb{E}[S^2] = \\sigma^2$.\n:::\n\n#### Giustificazione della correzione\n\nL'utilizzo della formula con denominatore $n$:\n\n$$\n\\tilde{S}^2 = \\frac{1}{n}\\sum_{i=1}^n (X_i - \\bar{X})^2\n$$\ncomporta una sottostima sistematica di $\\sigma^2$. Questo fenomeno si spiega considerando che la stima si basa sulla media campionaria $\\bar{X}$ (a sua volta una variabile aleatoria) anziché sul valore atteso vero $\\mu$. Tale sostituzione comporta una perdita di un grado di libertà nel calcolo.\n\nLa correzione introdotta da Bessel, che utilizza $n-1$ come denominatore, produce uno stimatore la cui aspettativa coincide esattamente con la varianza della popolazione:\n\n$$\n\\mathbb{E}[S^2] = \\sigma^2.\n$$\n\n#### Verifica mediante simulazione\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(123)\nmu <- 100; sigma <- 15\nn_sims <- 10000\nsample_size <- 5\ntrue_var <- sigma^2\n\n# Simulazione dei due stimatori\ncalc_vars <- function() {\n  sample_data <- rnorm(sample_size, mean = mu, sd = sigma)\n  var_n <- sum((sample_data - mean(sample_data))^2) / sample_size\n  var_n_minus_1 <- var(sample_data)  # Funzione var di R usa n-1\n  c(var_n, var_n_minus_1)\n}\n\nvars_matrix <- replicate(n_sims, calc_vars())\nsample_vars_n <- vars_matrix[1, ]\nsample_vars_n_minus_1 <- vars_matrix[2, ]\n\n# Confronto delle medie\ncat(\"Valore atteso stimatore con n:\", round(mean(sample_vars_n), 2), \"\\n\")\n#> Valore atteso stimatore con n: 181\ncat(\"Valore atteso stimatore con n-1:\", round(mean(sample_vars_n_minus_1), 2), \"\\n\")\n#> Valore atteso stimatore con n-1: 226\ncat(\"Varianza della popolazione:\", true_var, \"\\n\")\n#> Varianza della popolazione: 225\ncat(\"Bias relativo stimatore con n:\", round((mean(sample_vars_n) - true_var)/true_var * 100, 1), \"%\\n\")\n#> Bias relativo stimatore con n: -19.7 %\n```\n:::\n\n\nLa visualizzazione comparativa evidenzia le differenze tra i due approcci:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndata_combined <- rbind(\n  data.frame(var = sample_vars_n, type = \"Denominatore n (distorto)\"),\n  data.frame(var = sample_vars_n_minus_1, type = \"Denominatore n-1 (corretto)\")\n)\n\nggplot(data_combined, aes(x = var, color = type, fill = type)) +\n  geom_density(alpha = 0.3, linewidth = 1) +\n  geom_vline(xintercept = true_var, linetype = \"dashed\", linewidth = 1, color = \"#E15759\") +\n  annotate(\"text\", x = true_var + 20, y = 0.015, \n           label = paste(\"σ² =\", true_var), color = \"#E15759\") +\n  labs(\n    title = \"Distribuzione degli stimatori della varianza\",\n    subtitle = \"Confronto tra la versione distorta (n) e corretta (n-1)\",\n    x = \"Varianza campionaria\",\n    y = \"Densità\"\n  ) +\n  scale_color_manual(values = c(\"#79706E\", \"#4E79A7\")) +\n  scale_fill_manual(values = c(\"#79706E\", \"#4E79A7\")) +\n  theme_minimal() +\n  theme(legend.position = \"bottom\")\n```\n\n::: {.cell-output-display}\n![](09_incertezza_inferenza_files/figure-html/unnamed-chunk-20-1.png){fig-align='center' width=85%}\n:::\n:::\n\n\nLa distribuzione in blu, corrispondente allo stimatore corretto, risulta centrata esattamente sul valore vero della varianza, mentre la distribuzione in grigio mostra uno spostamento sistematico verso sinistra, confermando la natura distorta dello stimatore con denominatore $n$.\n\n**Implicazioni per l'inferenza bayesiana.**\n\nNell'ambito dell'inferenza bayesiana, la consapevolezza di questa distorsione risulta rilevante quando la varianza campionaria viene incorporata nella funzione di verosimiglianza o quando si conducono inferenze sul parametro $\\sigma^2$.\n\nNella pratica della ricerca:\n\n- con campioni di ampiezza consistente ($n > 30$), la discrepanza tra le due formulazioni diventa trascurabile;\n- in contesti con campioni di dimensione ridotta, l'utilizzo della correzione $n-1$ è essenziale per ottenere stime puntuali accurate;\n- nell'approccio bayesiano completo, la modellazione probabilistica integrata gestisce automaticamente queste problematiche attraverso la specifica appropriata delle distribuzioni a priori e delle funzioni di verosimiglianza.\n\n## Incertezza, distorsione sistematica e limiti dell'inferenza statistica\n\n### L'errore standard quantifica solo l'incertezza campionaria\n\nÈ fondamentale comprendere che l'errore standard, così come la dispersione della distribuzione a posteriori, misura esclusivamente l'incertezza epistemica derivante dalla finitezza del campione. Tale misura non coglie né mitiga gli errori sistematici che possono compromettere la validità del processo di ricerca.\n\nEsaminiamo alcune fonti di distorsione che persistono nonostante l'aumento della dimensione del campione.\n\n### Distorsione da selezione\n\n**Contesto tipico**: si intende stimare la prevalenza dei disturbi d'ansia nella popolazione studentesca universitaria attraverso un campione di volontari.\n\n**Problema fondamentale**: gli individui con sintomi d'ansia più gravi potrebbero avere una minore propensione a partecipare a causa di meccanismi di evitamento sociale, oppure potrebbero essere più disponibili spinti dalla ricerca di aiuto.\n\n**Conseguenza inferenziale**: anche con campioni di grandi dimensioni, la stima campionaria risulterebbe sistematicamente distorta. L'intervallo di credibilità risulterebbe estremamente preciso, ma centrato su un valore parametrico errato.\n\n### Distorsione da risposta\n\n**Scenario comune**: si indaga la frequenza di pensieri negativi auto-riferiti.\n\n**Problematica sottostante**: la desiderabilità sociale può indurre i partecipanti a sottostimare la frequenza effettiva di tali pensieri, mentre altri potrebbero rifiutarsi di ammetterne l'effettiva occorrenza.\n\n**Implicazione metodologica**: si ottiene una stima di elevata precisione statistica, ma riferita a un costrutto distorto.\n\n### Errori di misurazione\n\n**Caso emblematico**: si utilizza un questionario per la valutazione dell'autostima.\n\n**Criticità misurazionale**: se lo strumento non coglie adeguatamente il costrutto teorico di riferimento o presenta una bassa affidabilità, le inferenze statistiche risulteranno compromesse.\n\n**Limite fondamentale**: l'incremento della dimensione del campione non risolve i problemi di validità e affidabilità degli strumenti di misurazione.\n\n### Rappresentazione visiva: precisione versus accuratezza\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(42)\n\n# Simulazione di quattro scenari inferenziali\nn_points <- 100\n\n# Scenario 1: Condizioni ottimali\ns1 <- data.frame(\n  x = rnorm(n_points, mean = 0, sd = 0.3),\n  y = rnorm(n_points, mean = 0, sd = 0.3),\n  scenario = \"Condizioni ottimali\"\n)\n\n# Scenario 2: Precisione ingannevole\ns2 <- data.frame(\n  x = rnorm(n_points, mean = 2, sd = 0.3),\n  y = rnorm(n_points, mean = 2, sd = 0.3),\n  scenario = \"Precisione ingannevole\"\n)\n\n# Scenario 3: Accuratezza con dispersione\ns3 <- data.frame(\n  x = rnorm(n_points, mean = 0, sd = 1),\n  y = rnorm(n_points, mean = 0, sd = 1),\n  scenario = \"Accuratezza con dispersione\"\n)\n\n# Scenario 4: Condizioni deficitarie\ns4 <- data.frame(\n  x = rnorm(n_points, mean = 2, sd = 1),\n  y = rnorm(n_points, mean = 2, sd = 1),\n  scenario = \"Condizioni deficitarie\"\n)\n\nall_scenarios <- rbind(s1, s2, s3, s4)\n\nggplot(all_scenarios, aes(x = x, y = y)) +\n  geom_point(alpha = 0.6, color = \"#4E79A7\") +\n  geom_point(aes(x = 0, y = 0), \n             color = \"#E15759\", \n             size = 5, \n             shape = 4,\n             stroke = 2) +\n  facet_wrap(~ scenario, ncol = 2) +\n  coord_fixed() +\n  labs(\n    title = \"Precisione e accuratezza nell'inferenza statistica\",\n    subtitle = \"La croce rossa indica il valore parametrico vero\",\n    x = \"\",\n    y = \"\"\n  ) +\n  theme_minimal() +\n  theme(\n    axis.text = element_blank(),\n    axis.ticks = element_blank(),\n    strip.text = element_text(face = \"bold\")\n  )\n```\n\n::: {.cell-output-display}\n![](09_incertezza_inferenza_files/figure-html/unnamed-chunk-21-1.png){fig-align='center' width=85%}\n:::\n:::\n\n\n**Principio fondamentale**: lo scenario più problematico è rappresentato dalla combinazione di alta precisione e bassa accuratezza. In questa situazione, l'inferenza statistica genera una falsa certezza riguardo a conclusioni sistematicamente errate. I campioni di grandi dimensioni, se affetti da distorsioni sistematiche, producono stime errate con livelli di confidenza inappropriati.\n\n### Strategie di mitigazione\n\n1. **Progettazione metodologica rigorosa**: implementazione di strategie di campionamento probabilistico, adozione di protocolli standardizzati e utilizzo di strumenti con adeguate proprietà psicometriche.\n\n2. **Analisi di sensibilità**: l'approccio bayesiano consente di incorporare esplicitamente l'incertezza riguardante la qualità dei dati attraverso distribuzioni a priori che modellano gli errori di misurazione.\n\n3. **Modellazione gerarchica**: specificazione di modelli in grado di catturare le molteplici fonti di variabilità e distorsione presenti nei dati.\n\n4. **Trasparenza epistemica**: riconoscimento esplicito dei limiti metodologici. Gli intervalli di credibilità mantengono la loro validità solo se si rispettano le assunzioni del modello statistico adottato. Quando il modello ignora fonti rilevanti di distorsione, gli intervalli risultano fuorvianti, nonostante la loro apparente precisione.\n\n::: {.callout-warning}\n#### Il pericolo della falsa precisione {.unnumbered .unlisted}\n\nUn intervallo di credibilità estremamente ristretto - ad esempio [0.449, 0.451] - può generare un'illusione di conoscenza precisa e definitiva. Tuttavia, è cruciale comprendere che tale intervallo quantifica esclusivamente l'incertezza campionaria, non l'affidabilità complessiva del risultato.\n\nIn presenza di distorsioni sistematiche nel disegno di ricerca o negli strumenti di misura, il vero valore del parametro potrebbe collocarsi ben al di fuori dell'intervallo calcolato, nonostante la sua apparente precisione. L'inferenza bayesiana, al pari di quella frequentista, può quantificare soltanto l'incertezza imputabile alla finitezza del campione, ma non possiede la capacità di correggere errori metodologici fondamentali nella progettazione dello studio o nei processi di misurazione.\n\nLa precisione statistica non deve mai essere confusa con la validità scientifica. Un risultato numericamente preciso ma concettualmente viziato da errori sistematici rappresenta un pericolo maggiore di un risultato impreciso ma metodologicamente solido, poiché la sua apparente accuratezza può trarre in inganno sia il ricercatore che il lettore.\n:::\n\n## Convergenza e consistenza nell'inferenza bayesiana\n\n### Il teorema di convergenza bayesiana\n\nUn risultato teorico di fondamentale importanza nella statistica bayesiana riguarda il comportamento asintotico della distribuzione a posteriori con l'aumentare della dimensione del campione.\n\n::: {#thm-bayesian-consistency}\n## Consistenza bayesiana\n\nSotto opportune condizioni di regolarità, se la distribuzione a priori assegna una densità positiva al valore vero del parametro $\\theta_0$, allora:\n\n1. la distribuzione a posteriori converge verso una distribuzione degenere concentrata in $\\theta_0$:\n   \n   $$\n   p(\\theta \\mid \\mathbf{X}_n) \\xrightarrow{n \\to \\infty} \\delta(\\theta - \\theta_0),\n   $$\n   \n   dove $\\delta$ denota la funzione delta di Dirac.\n\n2. la media a posteriori converge al valore vero del parametro:\n   \n   $$\n   \\mathbb{E}[\\theta \\mid \\mathbf{X}_n] \\xrightarrow{n \\to \\infty} \\theta_0.\n   $$\n\n3. la varianza a posteriori tende asintoticamente a zero:\n   \n   $$\n   \\text{Var}(\\theta \\mid \\mathbf{X}_n) \\xrightarrow{n \\to \\infty} 0.\n   $$\n:::\n\n### Interpretazione sostantiva\n\nQuesto teorema rivela le proprietà essenziali dell'inferenza bayesiana:\n\n1. **Robustezza asintotica alle specificazioni a priori**: in presenza di dati sufficienti, la scelta della distribuzione a priori perde progressivamente influenza, a condizione che non escluda completamente il valore vero del parametro.\n\n2. **Capacità auto-correttiva**: qualora le credenze iniziali si rivelino inadeguate, l'evidenza empirica opera una correzione progressiva della distribuzione a posteriori.\n\n3. **Velocità di convergenza**: la varianza a posteriori decresce proporzionalmente a $1/n$, in accordo con i risultati classici della teoria della distribuzione campionaria.\n\n### Illustrazione empirica: convergenza con specificazioni a priori differenti\n\nConsideriamo tre ricercatori che adottano concezioni iniziali differenti riguardo al parametro $\\theta$, rappresentante una proporzione di successi:\n\n- **Ricercatore A**: distribuzione a priori $\\text{Beta}(2, 8)$ - propenso a credere in valori bassi di $\\theta$ (attorno a 0.2);\n- **Ricercatore B**: distribuzione a priori $\\text{Beta}(8, 2)$ - incline a valori elevati di $\\theta$ (attorno a 0.8);\n- **Ricercatore C**: distribuzione a priori $\\text{Beta}(1, 1)$ - uniforme, rappresentante massima incertezza iniziale.\n\nIl valore del parametro vero è $\\theta_0 = 0.45$. Osserviamo l'evoluzione delle distribuzioni a posteriori al crescere dell'informazione campionaria:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Parametri della simulazione\ntheta_true <- 0.45\nn_observations <- c(10, 50, 200, 1000)\n\n# Specificazioni a priori\nprior_A <- c(2, 8)\nprior_B <- c(8, 2)\nprior_C <- c(1, 1)\n\n# Funzione per il calcolo delle distribuzioni a posteriori\ncompute_posterior <- function(prior, n, theta) {\n  y <- rbinom(1, n, theta)  # numero di successi osservati\n  c(prior[1] + y, prior[2] + n - y)\n}\n\n# Simulazione\nset.seed(42)\nposteriors <- list()\n\nfor (n in n_observations) {\n  theta_grid <- seq(0.1, 0.9, length.out = 200)\n  \n  post_A <- compute_posterior(prior_A, n, theta_true)\n  post_B <- compute_posterior(prior_B, n, theta_true)\n  post_C <- compute_posterior(prior_C, n, theta_true)\n  \n  posteriors[[as.character(n)]] <- data.frame(\n    theta = rep(theta_grid, 3),\n    density = c(\n      dbeta(theta_grid, post_A[1], post_A[2]),\n      dbeta(theta_grid, post_B[1], post_B[2]),\n      dbeta(theta_grid, post_C[1], post_C[2])\n    ),\n    researcher = rep(c(\"Ricercatore A (prior conservativo)\", \n                       \"Ricercatore B (prior ottimista)\", \n                       \"Ricercatore C (prior non informativo)\"), \n                     each = length(theta_grid)),\n    n = n\n  )\n}\n\nall_posteriors <- do.call(rbind, posteriors)\nall_posteriors$n <- factor(all_posteriors$n, \n                           levels = n_observations,\n                           labels = paste(\"n =\", n_observations))\n\nggplot(all_posteriors, aes(x = theta, y = density, color = researcher, linetype = researcher)) +\n  geom_line(linewidth = 1.2) +\n  geom_vline(xintercept = theta_true, linetype = \"dashed\", \n             color = \"#E15759\", linewidth = 1.2, alpha = 0.8) +\n  facet_wrap(~ n, ncol = 2, scales = \"free_y\") +\n  labs(\n    title = \"Convergenza bayesiana con specificazioni a priori differenti\",\n    subtitle = \"La linea verticale indica il valore parametrico vero θ = 0.45\",\n    x = \"Parametro θ\",\n    y = \"Densità a posteriori\",\n    color = \"Ricercatore\",\n    linetype = \"Ricercatore\"\n  ) +\n  scale_color_manual(values = c(\"#4E79A7\", \"#59A14F\", \"#EDC948\")) +\n  theme_minimal() +\n  theme(legend.position = \"bottom\",\n        plot.title = element_text(face = \"bold\"))\n```\n\n::: {.cell-output-display}\n![](09_incertezza_inferenza_files/figure-html/unnamed-chunk-22-1.png){fig-align='center' width=85%}\n:::\n:::\n\n\n**Osservazioni empiriche**:\n\n1. con $n=10$ osservazioni, le distribuzioni a posteriori riflettono marcatamente le diverse concezioni a priori;\n2. con $n=50$ osservazioni, inizia a manifestarsi un processo di convergenza;\n3. con $n=200$ osservazioni, le distribuzioni a posteriori risultano sostanzialmente sovrapposte;\n4. con $n=1000$ osservazioni, le distribuzioni sono praticamente indistinguibili.\n\n**Implicazioni per la ricerca scientifica**\n\nQuesto risultato teorico offre importanti rassicurazioni metodologiche:\n\n1. **Soggettività controllata**: sebbene i ricercatori possano iniziare con concezioni a priori diverse, l'evidenza empirica conduce progressivamente a conclusioni condivise.\n\n2. **Criticità della dimensione campionaria**: con campioni di modesta entità, le specificazioni a priori mantengono una forte influenza, mentre con campioni ampi l'evidenza dati domina l'inferenza.\n\n3. **Base per la replicabilità**: Studi condotti con specificazioni a priori ragionevoli e dimensioni campionarie adeguate dovrebbero convergere verso conclusioni simili.\n\nL'inferenza bayesiana dimostra quindi di possedere una proprietà di *oggettività asintotica*, pur ammettendo una legittima variabilità nelle concezioni iniziali.\n\n## Dalla frequenza alle credenze: sintesi dei framework inferenziali\n\n### Confronto concettuale tra paradigmi\n\nÈ giunto il momento di sintetizzare sistematicamente le differenti prospettive attraverso cui i principali framework interpretano i concetti statistici fondamentali.\n\n**Parametro $\\theta$.**  \nNell'approccio frequentista, il parametro rappresenta una quantità fissa sebbene ignota. La prospettiva bayesiana, al contrario, considera il parametro come una variabile aleatoria caratterizzata da una propria distribuzione di probabilità.\n\n**Natura della probabilità.**  \nLa visione frequentista identifica la probabilità con la frequenza relativa in infinite ripetizioni ipotetiche di un esperimento. L'interpretazione bayesiana, invece, concepisce la probabilità come un grado di credenza razionale, soggettiva, ma coerente.\n\n**Processo inferenziale.**  \nL'inferenza frequentista costruisce procedure che, nel lungo periodo, garantiscono proprietà di copertura prefissate. L'inferenza bayesiana, invece, aggiorna la distribuzione di probabilità del parametro alla luce dell'evidenza empirica osservata.\n\n**Intervalli di incertezza.**  \nUn intervallo di confidenza al 95% viene interpretato come una procedura che, se ripetuta infinite volte, coprirebbe il valore vero del parametro nel 95% dei casi. Un intervallo di credibilità bayesiano può essere interpretato direttamente come la probabilità che il parametro sia contenuto in quell'intervallo specifico.\n\n**Fonte dell'incertezza.**  \nL'incertezza frequentista origina dalla variabilità campionaria in ripetizioni ipotetiche. L'incertezza bayesiana, invece, riflette l'incompletezza della nostra conoscenza epistemica riguardo al parametro.\n\n**Funzione dei dati.**  \nI dati forniscono le basi per calcolare le statistiche e costruire gli stimatori nel paradigma frequentista. Nell'approccio bayesiano, i dati aggiornano le credenze preliminari, trasformando la distribuzione a priori in una distribuzione a posteriori.\n\n**Ruolo delle informazioni preliminari.**  \nIl framework frequentista non incorpora formalmente le conoscenze preesistenti. La metodologia bayesiana, invece, assegna un ruolo fondamentale alla distribuzione a priori che codifica matematicamente la conoscenza disponibile prima della raccolta dei dati.\n\n**Convergenza asintotica.**  \nEntrambi i paradigmi riconoscono che, sotto condizioni di regolarità, le stime convergono al valore parametrico vero al crescere della dimensione del campione.\n\n**Teorema del Limite Centrale.**  \nI frequentisti osservano la normalità asintotica delle distribuzioni campionarie, mentre i bayesiani notano che le distribuzioni a posteriori tendono a diventare approssimativamente normali.\n\n### Criteri per la scelta metodologica\n\nEntrambi i framework possiedono solide basi matematiche e producono inferenze valide quando applicati correttamente. La scelta dell'approccio più adatto dipende da diverse considerazioni:\n\n**Caratteristiche del problema investigativo:**  \nper problemi che coinvolgono aggiornamenti sequenziali delle credenze o l'integrazione di evidenze multiple, il framework bayesiano offre una struttura concettuale più naturale.\n\n**Disponibilità di conoscenza pregressa:**  \nquando esistono informazioni rilevanti precedenti allo studio, la metodologia bayesiana permette di incorporarle formalmente attraverso la specificazione della distribuzione a priori.\n\n**Trasparenza interpretativa:**  \nle affermazioni probabilistiche bayesiane sono più intuitive e direttamente interpretabili, specialmente per i ricercatori non specializzati in statistica.\n\n**Tradizioni disciplinari:**  \ndifferenti comunità scientifiche hanno sviluppato preferenze consolidate per specifici approcci inferenziali.\n\n### L'orientamento metodologico di questo volume\n\nIl presente manuale adotta una prospettiva prevalentemente bayesiana, scelta motivata da diverse considerazioni fondamentali che rispondono alle esigenze della ricerca psicologica contemporanea.\n\nIl primo vantaggio significativo è la coerenza con i processi naturali di ragionamento scientifico in condizioni di incertezza. Il framework bayesiano formalizza matematicamente il modo in cui i ricercatori pensano e aggiornano le proprie convinzioni alla luce di nuove evidenze.\n\nLa capacità di integrare formalmente la conoscenza pregressa nel processo inferenziale rappresenta un ulteriore elemento distintivo. Attraverso la specificazione di distribuzioni a priori, è possibile incorporare in modo trasparente e rigoroso quanto già noto dalla letteratura esistente, dall'esperienza clinica o da considerazioni teoriche.\n\nL'immediata interpretabilità dei risultati statistici rappresenta un vantaggio pratico di notevole rilevanza. Le affermazioni probabilistiche bayesiane, come \"esiste una probabilità del 95% che l'intervento sia efficace\", sono intuitive e possono essere utilizzate direttamente nel processo decisionale clinico e nella comunicazione scientifica.\n\nLa naturale estensibilità a modelli complessi e strutturati completa il quadro dei vantaggi. L'approccio bayesiano si estende elegantemente a contesti investigativi sofisticati, come i modelli gerarchici, l'analisi multi-livello e l'integrazione di dati eterogenei.\n\nPur adottando questa prospettiva metodologica, riconosciamo appieno il valore storico e metodologico dei contributi dell'approccio frequentista. Nei casi appropriati, sottolineiamo come i due paradigmi possano integrarsi proficuamente, offrendo una visione pluralistica e integrata della metodologia statistica per la ricerca in psicologia.\n\n**Principio unificante della metodologia statistica**\n\nAl di là delle distinzioni filosofiche che caratterizzano i diversi paradigmi inferenziali, la statistica moderna si basa su un solido fondamento matematico condiviso. Tale terreno comune include la legge dei grandi numeri, che garantisce la stabilità delle stime con l'aumentare dell'informazione disponibile; il teorema del limite centrale, che giustifica l'ubiquità della distribuzione normale nei contesti inferenziali; le proprietà fondamentali delle distribuzioni di probabilità, che forniscono il linguaggio formale per quantificare l'incertezza; e, infine, i metodi computazionali avanzati che permettono di applicare tali principi a problemi di crescente complessità.\n\nLa scelta del framework appropriato si configura quindi principalmente come una questione di interpretazione epistemologica e di convenienza applicativa, piuttosto che di correttezza matematica sottostante. Un ricercatore statisticamente competente dimostra la propria maturità metodologica attraverso la comprensione approfondita dei principi che animano entrambi gli approcci e sviluppando quella saggezza applicativa che gli permette di scegliere lo strumento più adeguato alle specifiche esigenze del contesto investigativo.\n\n## Riflessioni conclusive {.unnumbered .unlisted}\n\nQuesto capitolo ha esplorato una questione fondamentale della ricerca empirica in psicologia: come quantificare sistematicamente l'incertezza quando si traggono conclusioni da evidenze limitate. \n\nL'analisi ha mostrato che l'inferenza statistica, al di là delle specifiche scelte metodologiche, si basa su proprietà matematiche universali.\n\nLa media campionaria dimostra una proprietà di centratura sul parametro della popolazione, giustificando così l'utilizzo dei dati osservati per trarre inferenze sui fenomeni sottostanti. La precisione delle nostre stime aumenta in modo sistematico con l'aumentare delle osservazioni, poiché la variabilità diminuisce secondo un fattore proporzionale a $1/n$.  La legge dei grandi numeri garantisce la convergenza delle nostre inferenze verso i valori veri, a prescindere dalle ipotesi iniziali. Il Teorema del Limite Centrale fornisce il fondamento teorico per le approssimazioni distribuzionali, cruciali nella pratica applicata.\n\n### La prospettiva bayesiana come scelta interpretativa {.unnumbered .unlisted}\n\nL'adozione di un'interpretazione prevalentemente bayesiana di questi concetti risponde a precise considerazioni metodologiche.\n\nLe affermazioni probabilistiche bayesiane offrono un'immediatezza interpretativa superiore, consentendo di esprimere conclusioni nella forma \"esiste una probabilità del 95% che...\" anziché ricorrere a costruzioni controfattuali. La formalizzazione della conoscenza pregressa mediante distribuzioni a priori permette di integrare rigorosamente quanto già noto dalla letteratura esistente e dall'esperienza accumulata. Il processo di apprendimento viene concettualizzato come un aggiornamento sequenziale delle credenze, in linea con l'evoluzione cumulativa della conoscenza scientifica. La struttura del framework bayesiano si presta naturalmente a modelli di crescente complessità e sofisticazione analitica.\n\n### Limiti metodologici intrascendibili {.unnumbered .unlisted}\n\nÈ essenziale riconoscere che nessuna sofisticazione statistica può superare determinati vincoli metodologici.\n\nLe distorsioni sistematiche intrinseche alla raccolta dei dati, come il campionamento non probabilistico, gli strumenti di misura inadeguati o gli effetti di desiderabilità sociale, rimangono irrisolvibili attraverso il solo affinamento analitico. Ogni processo inferenziale si basa su un insieme di assunzioni model-based la cui violazione può compromettere la validità delle conclusioni, indipendentemente dalla dimensione del campione. La presenza di fonti di variabilità non catturate dal modello conduce a una sottostima sistematica dell'incertezza inferenziale.\n\n### Prospettive di sviluppo metodologico {.unnumbered .unlisted}\n\nI concetti esaminati in questo capitolo, ovvero distribuzione a posteriori, convergenza, precisione e errore standard, costituiscono la base per comprendere i modelli statistici avanzati che verranno esplorati nei capitoli successivi.\n\nL'analisi di regressione bayesiana estenderà il framework inferenziale allo studio delle relazioni tra le variabili. I modelli gerarchici permetteranno di rappresentare le complesse strutture di dipendenza tipiche dei dati psicologici. Le tecniche di selezione dei modelli forniranno gli strumenti per valutare quale rappresentazione teorica sia maggiormente supportata dall'evidenza empirica. I metodi predittivi consentiranno di utilizzare le distribuzioni a posteriori per formulare previsioni su osservazioni future.\n\nIn tutti questi contesti avanzati, i principi fondamentali rimangono invariati: le distribuzioni di probabilità quantificano l'incertezza, l'evidenza empirica aggiorna le credenze e la consapevolezza critica riconosce sia le potenzialità che i limiti dell'inferenza statistica.\n\n### Considerazioni finali {.unnumbered .unlisted}\n\nL'inferenza statistica è uno strumento potente, ma non onnipotente. Permette di quantificare rigorosamente l'incertezza, apprendere sistematicamente dall'evidenza empirica, distinguere i pattern significativi dalle fluttuazioni casuali e formulare previsioni accompagnate da stime di affidabilità.\n\nTuttavia, non può correggere gli errori di progettazione della ricerca, compensare le distorsioni sistematiche, stabilire nessi causali a partire da mere correlazioni o sostituire il pensiero critico del ricercatore.\n\nUna pratica scientifica rigorosa richiede l'integrazione di competenze statistiche, una comprensione approfondita del dominio teorico, la consapevolezza dei limiti metodologici e la trasparenza nella comunicazione delle incertezze e delle assunzioni.\n\n::: {.callout-important title=\"Problemi\" collapse=\"true\"}\nEsercizi sulla distribuzione campionaria e sull'inferenza sono disponibili sulla seguente [pagina web](https://stats.libretexts.org/Bookshelves/Introductory_Statistics/Introductory_Statistics_(Shafer_and_Zhang)/06%3A_Sampling_Distributions/6.E%3A_Sampling_Distributions_(Exercises)).\n:::\n\n::: {.callout-note collapse=true title=\"Informazioni sull'ambiente di sviluppo\"}\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsessionInfo()\n#> R version 4.5.2 (2025-10-31)\n#> Platform: aarch64-apple-darwin20\n#> Running under: macOS Tahoe 26.1\n#> \n#> Matrix products: default\n#> BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib \n#> LAPACK: /Library/Frameworks/R.framework/Versions/4.5-arm64/Resources/lib/libRlapack.dylib;  LAPACK version 3.12.1\n#> \n#> locale:\n#> [1] C.UTF-8/UTF-8/C.UTF-8/C/C.UTF-8/C.UTF-8\n#> \n#> time zone: Europe/Rome\n#> tzcode source: internal\n#> \n#> attached base packages:\n#> [1] stats     graphics  grDevices utils     datasets  methods   base     \n#> \n#> other attached packages:\n#>  [1] pillar_1.11.1         tinytable_0.15.1      patchwork_1.3.2      \n#>  [4] ggdist_3.3.3          tidybayes_3.0.7       bayesplot_1.14.0     \n#>  [7] ggplot2_4.0.0         reliabilitydiag_0.2.1 priorsense_1.2.0     \n#> [10] posterior_1.6.1       loo_2.8.0             rstan_2.32.7         \n#> [13] StanHeaders_2.32.10   brms_2.23.0           Rcpp_1.1.0           \n#> [16] sessioninfo_1.2.3     conflicted_1.2.0      janitor_2.2.1        \n#> [19] matrixStats_1.5.0     modelr_0.1.11         tibble_3.3.0         \n#> [22] dplyr_1.1.4           tidyr_1.3.1           rio_1.2.4            \n#> [25] here_1.0.2           \n#> \n#> loaded via a namespace (and not attached):\n#>  [1] svUnit_1.0.8          tidyselect_1.2.1      farver_2.1.2         \n#>  [4] S7_0.2.0              fastmap_1.2.0         TH.data_1.1-4        \n#>  [7] tensorA_0.36.2.1      digest_0.6.38         timechange_0.3.0     \n#> [10] estimability_1.5.1    lifecycle_1.0.4       survival_3.8-3       \n#> [13] magrittr_2.0.4        compiler_4.5.2        rlang_1.1.6          \n#> [16] tools_4.5.2           yaml_2.3.10           knitr_1.50           \n#> [19] labeling_0.4.3        bridgesampling_1.1-2  htmlwidgets_1.6.4    \n#> [22] curl_7.0.0            pkgbuild_1.4.8        RColorBrewer_1.1-3   \n#> [25] abind_1.4-8           multcomp_1.4-29       withr_3.0.2          \n#> [28] purrr_1.2.0           grid_4.5.2            stats4_4.5.2         \n#> [31] colorspace_2.1-2      xtable_1.8-4          inline_0.3.21        \n#> [34] emmeans_2.0.0         scales_1.4.0          MASS_7.3-65          \n#> [37] cli_3.6.5             mvtnorm_1.3-3         rmarkdown_2.30       \n#> [40] ragg_1.5.0            generics_0.1.4        RcppParallel_5.1.11-1\n#> [43] cachem_1.1.0          stringr_1.6.0         splines_4.5.2        \n#> [46] parallel_4.5.2        vctrs_0.6.5           V8_8.0.1             \n#> [49] Matrix_1.7-4          sandwich_3.1-1        jsonlite_2.0.0       \n#> [52] arrayhelpers_1.1-0    systemfonts_1.3.1     glue_1.8.0           \n#> [55] codetools_0.2-20      distributional_0.5.0  lubridate_1.9.4      \n#> [58] stringi_1.8.7         gtable_0.3.6          QuickJSR_1.8.1       \n#> [61] htmltools_0.5.8.1     Brobdingnag_1.2-9     R6_2.6.1             \n#> [64] textshaping_1.0.4     rprojroot_2.1.1       evaluate_1.0.5       \n#> [67] lattice_0.22-7        backports_1.5.0       memoise_2.0.1        \n#> [70] broom_1.0.10          snakecase_0.11.1      rstantools_2.5.0     \n#> [73] gridExtra_2.3         coda_0.19-4.1         nlme_3.1-168         \n#> [76] checkmate_2.3.3       xfun_0.54             zoo_1.8-14           \n#> [79] pkgconfig_2.0.3\n```\n:::\n\n:::\n\n## Bibliografia {.unnumbered .unlisted}\n",
    "supporting": [
      "09_incertezza_inferenza_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}