{
  "hash": "16a413b94553c7c010f6682f9ac2b0d3",
  "result": {
    "engine": "knitr",
    "markdown": "# Assiomi e coerenza delle credenze {#sec-prob-axioms-coherence}\n\n## Introduzione {.unnumbered .unlisted}\n\nDopo aver introdotto la probabilità come *grado di credenza razionale* nel @sec-prob-interpretation, questo capitolo sviluppa il framework matematico per operare in modo coerente con le credenze.  Esploreremo come lo *spazio campionario* e gli *eventi* rappresentino possibilità epistemiche, e come gli *assiomi di Kolmogorov* fungano da vincoli di coerenza logica.\n\nUn aspetto cruciale che affronteremo è la costruzione e manipolazione di *tabelle di probabilità congiunta*, che costituiscono lo strumento operativo fondamentale per rappresentare credenze su sistemi complessi. Queste tabelle, in particolare nel caso semplice 2×2, rendono esplicita la relazione tra probabilità *congiunte*, *marginali* e *condizionate*, mostrando che tutte le probabilità di interesse derivano da un'unica struttura coerente.\n\nAttraverso esempi psicologici concreti e simulazioni in R, vedremo come diagnosticare e correggere le incoerenze nelle assegnazioni probabilistiche e come verificare empiricamente che le credenze coerenti producano i dati attesi.\n\n### Panoramica del capitolo {.unnumbered .unlisted}\n\n- Spazio campionario ed eventi come possibilità epistemiche.\n- Assiomi di Kolmogorov come vincoli di coerenza.\n- Diagnosi di incoerenze: additività e vincoli di Fréchet.\n- Tabelle di probabilità congiunta (2×2 e oltre).\n- Derivazione di marginali e condizionate da congiunte.\n- Verifica empirica della coerenza con simulazioni.\n\n::: {.callout-tip collapse=true}\n## Prerequisiti\n\n- Aver letto il @sec-prob-interpretation.\n- Leggere l'@sec-apx-sets (teoria degli insiemi).\n- Familiarità base con R e ggplot2.\n:::\n\n::: {.callout-caution collapse=true title=\"Preparazione del Notebook\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhere::here(\"code\", \"_common.R\") |> \n  source()\n\n# Load packages\nif (!requireNamespace(\"pacman\")) install.packages(\"pacman\")\npacman::p_load(ggplot2, dplyr, tidyr, viridis)\n```\n:::\n\n:::\n\n## Spazio campionario come possibilità epistemiche\n\nNel linguaggio classico, lo spazio campionario $\\Omega$ (o $S$) viene definito come \"l'insieme di tutti gli esiti possibili di un esperimento casuale\". Nell'approccio bayesiano, tale definizione va reinterpretata in chiave epistemica.\n\n::: {#def-sample-space-bayesian}\n### Spazio campionario (visione bayesiana)\n\nLo *spazio campionario* $\\Omega$ rappresenta l'insieme delle *possibilità epistemiche* compatibili con le informazioni disponibili. Esso non rappresenta ciò che può accadere fisicamente, ma ciò che, dati gli attuali limiti della nostra conoscenza, consideriamo possibile.\n:::\n\n### Caratteristiche dello spazio campionario epistemico\n\n1. **Dipendente dall'informazione**: lo spazio campionario può cambiare si acquisiscono nuove informazioni. Prima di osservare i risultati di un test diagnostico, lo spazio include i i valori {positivo, negativo}. Dopo aver osservato \"positivo\", lo spazio si riduce.\n\n2. **Non univoco**: ricercatori diversi, con informazioni diverse, possono definire spazi campionari diversi per lo stesso fenomeno.\n\n3. **Costruzione**: definire $\\Omega$ richiede di specificare il *livello di dettaglio rilevante* per la domanda di interesse.\n\n::: {.callout-note collapse=\"true\" title=\"Esempio psicologico\"}\n### Spazio campionario per una valutazione clinica {.unnumbered .unlisted}\n\nConsideriamo la valutazione di un paziente per possibile depressione. Lo spazio campionario può essere definito in modi diversi a seconda delle informazioni e degli obiettivi:\n\n**Livello 1 (binario):**\n$$\\Omega_1 = \\{\\text{Depresso}, \\text{Non depresso}\\}.$$\n\n**Livello 2 (severità):**\n$$\\Omega_2 = \\{\\text{Nessuna}, \\text{Lieve}, \\text{Moderata}, \\text{Severa}\\}.$$\n\n**Livello 3 (combinazioni):**\n$$\\Omega_3 = \\{\\text{Depressione}, \\text{Ansia}, \\text{Comorbidità}, \\text{Nessuna}\\}.$$\n\nLa scelta dipende da:\n\n- informazioni disponibili (screening, test, colloquio);\n- obiettivo clinico (screening vs diagnosi differenziale);\n- decisioni da prendere (trattamento, monitoraggio).\n\nOgni spazio è legittimo nel proprio contesto. La probabilità assegnata riflette la credenza in quello specifico spazio.\n:::\n\n## Eventi come proposizioni sul mondo\n\nUn *evento* è un sottoinsieme di $\\Omega$ che rappresenta una *proposizione* sul mondo che può essere vera o falsa.\n\n::: {#def-event-bayesian}\n### Evento\n\nUn *evento* $A \\subseteq \\Omega$ è una *proposizione* sul mondo a cui possiamo assegnare un grado di credenza $P(A)$, dato lo stato di informazione corrente.\n:::\n\n### Operazioni su eventi\n\nLe operazioni insiemistiche classiche hanno interpretazioni epistemiche naturali:\n\n- **Unione** $A \\cup B$: \"La proposizione $A$ *oppure* la proposizione $B$ è vera\".\n- **Intersezione** $A \\cap B$: \"Entrambe le proposizioni $A$ *e* $B$ sono vere\".\n- **Complemento** $A^c$: \"La proposizione $A$ *non* è vera\".\n- **Insieme vuoto** $\\varnothing$: \"Proposizione logicamente contraddittoria \n  (sempre falsa per necessità logica)\".\n- **Spazio campionario** $\\Omega$: \"Proposizione logicamente vera: qualcosa accade nell'insieme\".\n\n::: {.callout-note collapse=\"true\" title=\"Esempio: Eventi in un test psicometrico\"}\n### Proposizioni nella Satisfaction with Life Scale (SWLS)\n\nLa SWLS ha punteggi che vanno da 5 a 35. Definiamo:\n\n- $\\Omega = \\{5, 6, 7, \\ldots, 35\\}$ (possibili punteggi).\n- $A =$ \"Punteggio ≥ 25\" (alta soddisfazione) $= \\{25, 26, \\ldots, 35\\}$.\n- $B =$ \"Punteggio ≤ 15\" (bassa soddisfazione) $= \\{5, 6, \\ldots, 15\\}$.\n- $C =$ \"Punteggio tra 16 e 24\" (soddisfazione moderata) $= \\{16, 17, \\ldots, 24\\}$.\n\nOperazioni:\n\n- $A \\cup B$: \"Soddisfazione alta *o* bassa\" (non moderata).\n- $A \\cap B = \\varnothing$: proposizioni mutualmente esclusive (impossibile avere entrambi).\n- $A^c = B \\cup C$: \"Non alta soddisfazione\".\n- $A \\cup B \\cup C = \\Omega$: proposizioni esaustive.\n\nLa credenza $P(A)$ quantifica quanto riteniamo plausibile, in base a ciò che sappiamo (popolazione, contesto), che un individuo scelto abbia un'alta soddisfazione.\n:::\n\n## Gli assiomi di Kolmogorov come vincoli di coerenza\n\nNel @sec-prob-interpretation abbiamo visto che gli assiomi di Kolmogorov non sono leggi naturali ma vincoli per evitare incoerenze (il cosiddetto *Dutch Book*). Qui li formalizziamo e approfondiamo le loro implicazioni.\n\n::: {#def-probability-measure}\n### Funzione di probabilità (definizione bayesiana)\n\nUna *funzione di probabilità* $P: \\mathcal{F} \\to [0,1]$ assegna a ogni evento $A$ in una famiglia di eventi $\\mathcal{F}$ un numero $P(A)$ che rappresenta il grado di credenza nell'affermazione $A$. Per essere coerente, $P$ deve soddisfare i seguenti *assiomi di coerenza*:\n\n1. **Non-negatività**: $P(A) \\geq 0$ per ogni evento $A$.\n2. **Normalizzazione**: $P(\\Omega) = 1$.\n3. **Additività finita**: se $A$ e $B$ sono eventi disgiunti ($A \\cap B = \\varnothing$), allora\n   $$P(A \\cup B) = P(A) + P(B).$$\n\n4. **Additività numerabile** (per spazi infiniti): se $A_1, A_2, \\ldots$ è una sequenza di eventi mutuamente disgiunti, allora\n   $$P\\left(\\bigcup_{i=1}^{\\infty} A_i\\right) = \\sum_{i=1}^{\\infty} P(A_i).$$\n:::\n\n### Interpretazione epistemica degli assiomi\n\n1. **Non-negatività**: un grado di credenza negativo non ha senso; zero significa \"impossibile dato ciò che so\", uno significa \"certo dato ciò che so\".\n\n2. **Normalizzazione**: sono certo che *qualcosa* nello spazio delle possibilità si verificherà. Se $P(\\Omega) < 1$, sto ammettendo la possibilità che nulla di ciò che ho preso in considerazione accada, il che è incoerente.\n\n3. **Additività**: se due affermazioni sono mutualmente esclusive, la credenza nella loro disgiunzione è la somma delle credenze separate; violare questo principio porta al cosiddetto *Dutch Book*.\n\n### Conseguenze immediate degli assiomi\n\nDagli assiomi derivano diverse proprietà utili:\n\n::: {#thm-probability-properties}\n### Proprietà derivate della probabilità\n\n1. **Probabilità del complemento**: $P(A^c) = 1 - P(A)$.\n2. **Probabilità dell'insieme vuoto**: $P(\\varnothing) = 0$.\n3. **Monotonia**: se $A \\subseteq B$, allora $P(A) \\leq P(B)$.\n4. **Regola dell'unione** (eventi non disgiunti):\n   $$P(A \\cup B) = P(A) + P(B) - P(A \\cap B).$$\n5. **Principio di inclusione-esclusione** (generalizzazione):\n   $$P(A_1 \\cup A_2 \\cup A_3) = \\sum P(A_i) - \\sum P(A_i \\cap A_j) + P(A_1 \\cap A_2 \\cap A_3).$$\n:::\n\nQueste proprietà non sono assiomi aggiuntivi, ma conseguenze logiche dei tre assiomi di base. Una volta accettati i vincoli di coerenza, tutto il resto ne consegue necessariamente.\n\n## Diagnosi di incoerenze: casi tipici\n\nVediamo come identificare e correggere incoerenze comuni nelle assegnazioni probabilistiche.\n\n### Incoerenza 1: Violazione dell'additività\n\nL'errore più frequente è violare l'additività per eventi disgiunti, assegnando una probabilità maggiore di quella logicamente possibile.\n\n::: {.callout-warning title=\"Esempio di incoerenza clinica\"}\n#### Sovrastima delle probabilità {.unlisted .unnumbered}\n\nUn clinico assegna le seguenti credenze per tre diagnosi mutualmente esclusive:\n\n- $P(\\text{Depressione}) = 0.6$;\n- $P(\\text{Ansia}) = 0.5$;  \n- $P(\\text{Nessuna condizione}) = 0.2$.\n\nIl problema è che $0.6 + 0.5 + 0.2 = 1.3 > 1$.\n\nQuesta assegnazione è incoerente perché i tre eventi sono:\n\n- *mutualmente esclusivi*: il paziente può avere solo una delle tre condizioni;\n- *collettivamente esaustivi*: coprono tutti i casi possibili.\n\nIl clinico ha quindi \"speso\" più credenza (1.3) di quanta ne disponesse (1.0), come se avesse il 130% di certezza invece del 100%.\n:::\n\n\n::: {.cell layout-align=\"center\"}\n\n```\n#> Probabilità assegnate:\n#> Depressione       Ansia     Nessuna \n#>         0.6         0.5         0.2\n#> \n#> Somma totale: 1.3\n#> ⚠️ INCOERENZA RILEVATA: Per eventi mutuamente esclusivi ed esaustivi,\n#>    la somma delle probabilità deve essere esattamente 1.\n#>    Eccesso di credenza: 0.3\n```\n:::\n\n\n**Strategie di correzione**:\n\n1. **Normalizzazione proporzionale** (se le proporzioni relative sono giudicate corrette):\n\n::: {.cell layout-align=\"center\"}\n\n```\n#> Probabilità normalizzate (mantenendo le proporzioni):\n#> Depressione       Ansia     Nessuna \n#>       0.462       0.385       0.154\n#> Nuova somma: 1\n```\n:::\n\n\n2. **Revisione critica** (approccio preferibile): rivalutare ciascuna assegnazione alla luce dell'incoerenza scoperta, considerando:\n\n   - prevalenze nella popolazione di riferimento;\n   - evidenze cliniche specifiche del caso;\n   - possibile sovrastima di condizioni ritenute più salienti.\n\n### Visualizzazione dell'incoerenza\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](02_axioms_coherence_bayesian_files/figure-html/unnamed-chunk-4-1.png){fig-align='center' width=85%}\n:::\n:::\n\n\n## Vincoli di Fréchet per congiunzioni di eventi\n\nQuando consideriamo due eventi che *possono verificarsi insieme*, la probabilità della loro intersezione $P(A \\cap B)$ non può essere scelta liberamente, ma deve rispettare precisi vincoli matematici.\n\n::: {#thm-frechet-bounds}\n### Vincoli di Fréchet\n\nPer qualsiasi coppia di eventi $A$ e $B$ vale:\n\n$$\n\\max\\{0,\\, P(A) + P(B) - 1\\} \\;\\leq\\; P(A \\cap B) \\;\\leq\\; \\min\\{P(A), P(B)\\}.\n$$\n\n**Interpretazione intuitiva:**\n\n- **Limite superiore**: l'evento \"$A$ e $B$ insieme\" non può essere più probabile dell'evento singolo meno probabile tra $A$ e $B$.\n- **Limite inferiore**: se la somma delle probabilità individuali supera 1, allora $A$ e $B$ *devono* sovrapporsi almeno in parte.\n:::\n\n::: {.callout-note collapse=\"true\" title=\"Esempio clinico: Depressione e Ansia\"}\n#### Applicazione alla comorbidità psicologica {.unnumbered .unlisted}\n\nConsideriamo uno studio su una popolazione clinica in cui:\n\n- $P(\\text{Depressione}) = 0.6$ (60% è depresso);\n- $P(\\text{Ansia}) = 0.5$ (50% è ansioso).\n\nQuali valori sono logicamente possibili per la comorbidità $P(\\text{Depressione} \\cap \\text{Ansia})$?\n\n**Calcolo dei limiti:**\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nP_Depressione <- 0.6\nP_Ansia <- 0.5\n\nlimite_inferiore <- max(0, P_Depressione + P_Ansia - 1)\nlimite_superiore <- min(P_Depressione, P_Ansia)\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```\n#> VINCOLI DI FRÉCHET - Depressione e Ansia\n#> =========================================\n#> P(Depressione) = 0.6\n#> P(Ansia) = 0.5\n#> ---\n#> Limite inferiore: max(0, 0.6 + 0.5 - 1) = 0.1\n#> Limite superiore: min(0.6, 0.5) = 0.5\n#> ---\n#> INTERVALLO AMMISSIBILE:\n#> 0.1 ≤ P(Depressione ∩ Ansia) ≤ 0.5\n```\n:::\n\n\n**Risultato:** $0.1 \\leq P(\\text{Comorbidità}) \\leq 0.5$.\n\n**Cosa significa nella pratica:**\n\n- ❌ **Incoerente**: dire che solo il 5% ha comorbidità ($< 0.1$) è impossibile;\n- ❌ **Incoerente**: dire che il 60% ha comorbidità ($> 0.5$) è impossibile;\n- ✅ **Coerente**: qualsiasi valore tra 10% e 50% è logicamente possibile.\n:::\n\n### Mappa dei valori ammissibili\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Creare griglia di valori\ngrid <- expand.grid(\n  P_A = seq(0, 1, by = 0.02),\n  P_B = seq(0, 1, by = 0.02)\n)\n\n# Calcolare vincoli per ogni coppia\ngrid$limite_inferiore <- pmax(0, grid$P_A + grid$P_B - 1)\ngrid$limite_superiore <- pmin(grid$P_A, grid$P_B)\ngrid$ampiezza_lecita <- grid$limite_superiore - grid$limite_inferiore\n\n# Visualizzazione\nggplot(grid, aes(x = P_A, y = P_B, fill = ampiezza_lecita)) +\n  geom_tile() +\n  scale_fill_viridis_c(\n    name = \"Ampiezza dell'intervallo\\nammissibile\",\n    option = \"plasma\",\n    limits = c(0, 1)\n  ) +\n  labs(\n    title = \"Vincoli di Fréchet: intervalli ammissibili per P(A ∩ B)\",\n    subtitle = \"Per ogni coppia (P(A), P(B)), l'area colorata mostra quanti valori di P(A ∩ B) \\nsono logicamente possibili\",\n    x = \"P(A)\",\n    y = \"P(B)\",\n    caption = \"Colori più chiari = maggiore libertà nella scelta di P(A ∩ B)\"\n  ) +\n  theme_minimal() +\n  theme(legend.position = \"right\") +\n  coord_fixed()\n```\n\n::: {.cell-output-display}\n![Regione dei valori ammissibili per P(A ∩ B) in funzione di P(A) e P(B)](02_axioms_coherence_bayesian_files/figure-html/unnamed-chunk-7-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n**Come leggere questa mappa:**\n\n- **🔵 Blu scuro** (angoli): vincoli molto stringenti - pochi valori di $P(A \\cap B)$ sono possibili;\n- **🟡 Giallo** (centro): massima libertà - molti valori di $P(A \\cap B)$ sono ammissibili;\n- **Regione in alto a destra**: quando $P(A) + P(B) > 1$, è necessaria una sovrapposizione minima obbligatoria;\n- **Regione in basso a sinistra**: quando $P(A) + P(B) \\leq 1$, la sovrapposizione può essere anche nulla.\n\n> **Importante per la pratica clinica**: questi vincoli ci proteggono dall'assegnare probabilità logicamente impossibili a sintomi che si presentano insieme o a condizioni che co-occorrono.\n\n## Tabelle di probabilità congiunta\n\nLe **tabelle di probabilità congiunta** sono lo strumento fondamentale per rappresentare le credenze su sistemi con più variabili. Rendono esplicite tutte le relazioni tra gli eventi.\n\n### Struttura di una tabella 2×2\n\nConsideriamo due eventi binari $A$ e $B$. La tabella congiunta ha questa struttura:\n\n|       | $B$  | $B^c$ | Marginale |\n|-------|------|-------|-----------|\n| $A$   | $P(A \\cap B)$ | $P(A \\cap B^c)$ | $P(A)$ |\n| $A^c$ | $P(A^c \\cap B)$ | $P(A^c \\cap B^c)$ | $P(A^c)$ |\n| **Marginale** | $P(B)$ | $P(B^c)$ | $1$ |\n\n**Proprietà chiave:**\n\n1. **Celle interne**: probabilità congiunte (4 valori)\n2. **Marginali di riga**: $P(A) = P(A \\cap B) + P(A \\cap B^c)$\n3. **Marginali di colonna**: $P(B) = P(A \\cap B) + P(A^c \\cap B)$\n4. **Normalizzazione**: la somma di tutte le celle è uguale a 1.\n\nUna volta specificata in modo coerente la tabella congiunta, tutte le altre probabilità ne derivano automaticamente.\n\n::: {.callout-important title=\"Principio fondamentale\"}\n### Dalla distribuzione congiunta derivano tutte le probabilità\n\nSpecificare una distribuzione di probabilità congiunta coerente su uno spazio finito richiede di:\n\n- assegnare probabilità a ogni combinazione possibile degli eventi;\n- da questa specificazione completa discendono automaticamente, tramite operazioni di somma e condizionamento:\n  - le probabilità marginali dei singoli eventi;\n  - le probabilità condizionate tra eventi;\n  - la verifica di eventuali relazioni di indipendenza.\n\nLa distribuzione congiunta rappresenta quindi lo *stato di conoscenza completo* sul sistema in esame.\n:::\n\n### Costruzione di una tabella di probabilità congiunta 2×2\n\n::: {.callout-note collapse=\"true\" title=\"Esempio: Test diagnostico per la depressione\"}\n#### Definizione dello scenario {.unnumbered .unlisted}\n\nConsideriamo un test diagnostico per la depressione con:\n\n- **$D$**: il paziente è effettivamente depresso\n- **$T^+$**: il test risulta positivo\n\nDati ricavati dalla letteratura clinica:\n\n- **Prevalenza**: $P(D) = 0.15$ (15% dei pazienti sono depressi)\n- **Sensibilità**: $P(T^+ \\mid D) = 0.85$ (l'85% dei depressi risulta positivo)\n- **Falsi positivi**: $P(T^+ \\mid D^c) = 0.20$ (il 20% dei non depressi risulta positivo)\n\n**Costruzione passo-passo della tabella:**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Parametri di base\nprevalenza <- 0.15\nsensibilita <- 0.85\ntasso_falsi_positivi <- 0.20\n\n# Calcolo delle probabilità congiunte\np_depresso_positivo <- sensibilita * prevalenza\np_depresso_negativo <- (1 - sensibilita) * prevalenza\np_non_depresso_positivo <- tasso_falsi_positivi * (1 - prevalenza)\np_non_depresso_negativo <- (1 - tasso_falsi_positivi) * (1 - prevalenza)\n\n# Creazione della tabella\ntabella_congiunta <- matrix(\n  c(p_depresso_positivo, p_depresso_negativo,\n    p_non_depresso_positivo, p_non_depresso_negativo),\n  nrow = 2,\n  byrow = TRUE,\n  dimnames = list(\n    \"Stato reale\" = c(\"Depresso\", \"Non depresso\"),\n    \"Risultato test\" = c(\"Positivo\", \"Negativo\")\n  )\n)\n\ncat(\"TABELLA DI PROBABILITÀ CONGIUNTA\\n\")\n#> TABELLA DI PROBABILITÀ CONGIUNTA\ncat(\"===============================\\n\")\n#> ===============================\nprint(round(tabella_congiunta, 4))\n#>               Risultato test\n#> Stato reale    Positivo Negativo\n#>   Depresso        0.128   0.0225\n#>   Non depresso    0.170   0.6800\n\n# Verifica della coerenza\ncat(\"\\nVERIFICA DELLA COERENZA:\\n\")\n#> \n#> VERIFICA DELLA COERENZA:\ncat(\"Marginali per stato reale:\", round(rowSums(tabella_congiunta), 4), \"\\n\")\n#> Marginali per stato reale: 0.15 0.85\ncat(\"Marginali per risultato test:\", round(colSums(tabella_congiunta), 4), \"\\n\")\n#> Marginali per risultato test: 0.297 0.703\ncat(\"Somma totale (deve essere 1):\", round(sum(tabella_congiunta), 4), \"\\n\")\n#> Somma totale (deve essere 1): 1\n```\n:::\n\n\n**Interpretazione dei risultati:**\n\n- **12.75%**: probabilità che un paziente sia depresso e risulti positivo al test\n- **2.25%**: probabilità che un paziente sia depresso ma risulti negativo (falsi negativi)\n- **17.00%**: probabilità che un paziente non sia depresso ma risulti positivo (falsi positivi)\n- **68.00%**: probabilità che un paziente non sia depresso e risulti negativo\n\nLa tabella è **coerente**: tutte le probabilità sono non negative e la somma totale è 1, come richiesto dagli assiomi della probabilità.\n:::\n\n### Visualizzazione della tabella congiunta\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](02_axioms_coherence_bayesian_files/figure-html/unnamed-chunk-9-1.png){fig-align='center' width=85%}\n:::\n:::\n\n\n### Verifica empirica con simulazione\n\nPossiamo verificare che la tabella congiunta sia coerente simulando dati e confrontando frequenze empiriche con probabilità teoriche.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(123)\nN <- 100000\n\n# Simulare secondo la distribuzione congiunta\n# Esiti possibili: (D,T+), (D,T-), (D^c,T+), (D^c,T-)\nprobs_vector <- c(p_depresso_positivo, p_depresso_negativo, \n                  p_non_depresso_positivo, p_non_depresso_negativo)\n\noutcomes <- sample(1:4, size = N, replace = TRUE, prob = probs_vector)\n\n# Contare frequenze empiriche\nfreq_empiriche <- table(outcomes) / N\n\n# Confronto\ndf_verifica <- data.frame(\n  Configurazione = c(\"D∩T+\", \"D∩T-\", \"D^c∩T+\", \"D^c∩T-\"),\n  Teorica = probs_vector,\n  Empirica = as.numeric(freq_empiriche)\n)\n\ncat(\"Confronto teorico vs empirico:\\n\")\n#> Confronto teorico vs empirico:\n# Correzione: applica round solo alle colonne numeriche\ndf_verifica_numeric <- df_verifica\ndf_verifica_numeric$Teorica <- round(df_verifica_numeric$Teorica, 4)\ndf_verifica_numeric$Empirica <- round(df_verifica_numeric$Empirica, 4)\nprint(df_verifica_numeric)\n#>   Configurazione Teorica Empirica\n#> 1           D∩T+  0.1275   0.1266\n#> 2           D∩T-  0.0225   0.0226\n#> 3         D^c∩T+  0.1700   0.1699\n#> 4         D^c∩T-  0.6800   0.6809\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](02_axioms_coherence_bayesian_files/figure-html/unnamed-chunk-11-1.png){fig-align='center' width=85%}\n:::\n:::\n\n\n**Interpretazione**: le frequenze empiriche convergono verso le probabilità teoriche, confermando che la tabella rappresenta credenze coerenti che producono dati attesi.\n\n## Calcolo di probabilità marginali e condizionate\n\nUna volta costruita una tabella congiunta coerente, possiamo ricavare qualsiasi altra quantità probabilistica di interesse.\n\n### Probabilità marginali\n\nLe probabilità *marginali* si ottengono sommando (marginalizzando) lungo una dimensione:\n\n$$\nP(A) = \\sum_{B} P(A \\cap B) = P(A \\cap B) + P(A \\cap B^c),\n$$\n\n$$\nP(B) = \\sum_{A} P(A \\cap B) = P(A \\cap B) + P(A^c \\cap B).\n$$\n\n\n::: {.cell layout-align=\"center\"}\n\n```\n#> Probabilità marginali derivate:\n#> P(D) = 0.15\n#> P(D^c) = 0.85\n#> P(T+) = 0.297\n#> P(T-) = 0.703\n```\n:::\n\n\n### Probabilità condizionate\n\nLe probabilità *condizionate* si ottengono come rapporti:\n\n$$\nP(A \\mid B) = \\frac{P(A \\cap B)}{P(B)}.\n$$\n\n**Interpretazione epistemica**: dopo aver appreso che $B$ è vero, \"riduciamo\" lo spazio delle possibilità a quelle compatibili con $B$, e rinormalizziamo.\n\n\n::: {.cell layout-align=\"center\"}\n\n```\n#> Probabilità condizionate derivate:\n#> P(D | T+) = 0.429 (Valore predittivo positivo)\n#> P(D | T-) = 0.032 (Probabilità residua dopo test negativo)\n```\n:::\n\n\n::: {.callout-important}\n### Messaggio chiave: la coerenza delle probabilità condizionate\n\nLe probabilità condizionate non sono assegnazioni arbitrarie, ma *relazioni strutturate* che derivano necessariamente dalla distribuzione congiunta. \n\nQuesta dipendenza matematica garantisce che tutte le probabilità siano *coerenti tra loro*: una volta specificata la distribuzione congiunta, le probabilità condizionate sono determinate univocamente attraverso la relazione:\n\n$$\nP(A \\mid B) = \\frac{P(A \\cap B)}{P(B)}\n$$\n\nSe invece assegnassimo le probabilità condizionate in modo indipendente dalla congiunta, rischieremmo di creare **incoerenze logiche**, come ad esempio:\n\n- $P(A \\mid B) \\cdot P(B) \\neq P(A \\cap B)$;\n- Probabilità che violano gli assiomi fondamentali;\n- Assegnazioni che porterebbero al *Dutch book*.\n\nLa struttura congiunta funge quindi da *fondamento coerente* da cui tutte le altre probabilità derivano naturalmente.\n:::\n\n### Visualizzazione: dalla distribuzione congiunta alle probabilità condizionate\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](02_axioms_coherence_bayesian_files/figure-html/unnamed-chunk-14-1.png){fig-align='center' width=85%}\n:::\n:::\n\n\n## Esercizio guidato: costruire e analizzare una tabella 2×2\n\nLavoriamo passo-passo sulla costruzione di una tabella congiunta da informazioni psicologiche.\n\n::: {.callout-tip title=\"Scenario clinico\"}\n### Comorbidità Depressione-Ansia in terapia\n\nUno psicoterapeuta vuole modellare la probabilità di comorbidità nel proprio ambulatorio. Dalla letteratura e dall'esperienza clinica, stabilisce:\n\n- $P(\\text{Depressione}) = 0.50$ (prevalenza nell'ambulatorio);\n- $P(\\text{Ansia}) = 0.40$;\n- $P(\\text{Ansia} \\mid \\text{Depressione}) = 0.60$ (comorbidità).\n\n**Obiettivo**: Costruire la tabella congiunta completa e rispondere a domande cliniche.\n:::\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Parametri\nP_D <- 0.50\nP_A <- 0.40\nP_A_given_D <- 0.60\n\n# Passo 1: Calcolare congiunta P(D ∩ A)\nP_D_and_A <- P_A_given_D * P_D\n\ncat(\"=== COSTRUZIONE TABELLA CONGIUNTA ===\\n\\n\")\n#> === COSTRUZIONE TABELLA CONGIUNTA ===\ncat(\"Passo 1: P(D ∩ A) = P(A|D) × P(D) =\", P_A_given_D, \"×\", P_D, \"=\", P_D_and_A, \"\\n\\n\")\n#> Passo 1: P(D ∩ A) = P(A|D) × P(D) = 0.6 × 0.5 = 0.3\n\n# Passo 2: Altre celle usando additività\nP_D_and_notA <- P_D - P_D_and_A\nP_notD_and_A <- P_A - P_D_and_A\nP_notD_and_notA <- 1 - (P_D_and_A + P_D_and_notA + P_notD_and_A)\n\ncat(\"Passo 2: Altre celle\\n\")\n#> Passo 2: Altre celle\ncat(\"  P(D ∩ A^c) =\", P_D_and_notA, \"\\n\")\n#>   P(D ∩ A^c) = 0.2\ncat(\"  P(D^c ∩ A) =\", P_notD_and_A, \"\\n\")\n#>   P(D^c ∩ A) = 0.1\ncat(\"  P(D^c ∩ A^c) =\", P_notD_and_notA, \"\\n\\n\")\n#>   P(D^c ∩ A^c) = 0.4\n\n# Passo 3: Verificare coerenza\nsomma_celle <- P_D_and_A + P_D_and_notA + P_notD_and_A + P_notD_and_notA\ncat(\"Passo 3: Verifica coerenza\\n\")\n#> Passo 3: Verifica coerenza\ncat(\"  Somma celle =\", somma_celle, \"(deve essere 1) ✓\\n\\n\")\n#>   Somma celle = 1 (deve essere 1) ✓\n\n# Creare tabella\ntab_comorbid <- matrix(\n  c(P_D_and_A, P_D_and_notA,\n    P_notD_and_A, P_notD_and_notA),\n  nrow = 2, byrow = TRUE,\n  dimnames = list(\n    Depressione = c(\"D\", \"D^c\"),\n    Ansia = c(\"A\", \"A^c\")\n  )\n)\n\ncat(\"TABELLA CONGIUNTA FINALE:\\n\")\n#> TABELLA CONGIUNTA FINALE:\nprint(round(tab_comorbid, 3))\n#>            Ansia\n#> Depressione   A A^c\n#>         D   0.3 0.2\n#>         D^c 0.1 0.4\n\ncat(\"\\nMARGINALI:\\n\")\n#> \n#> MARGINALI:\ncat(\"Riga (Depressione):\", round(rowSums(tab_comorbid), 3), \"\\n\")\n#> Riga (Depressione): 0.5 0.5\ncat(\"Colonna (Ansia):\", round(colSums(tab_comorbid), 3), \"\\n\")\n#> Colonna (Ansia): 0.4 0.6\n```\n:::\n\n\n### Rispondere a domande cliniche\n\n\n::: {.cell layout-align=\"center\"}\n\n```\n#> \n#> === DOMANDE CLINICHE ===\n#> Q1: P(D ∪ A) = P(almeno una condizione) = 0.6\n#> Q2: P(D^c ∩ A^c) = P(nessuna condizione) = 0.4\n#> Q3: P(D ∩ A) = P(entrambe le condizioni) = 0.3\n#> Q4: P(D | A) = P(Depressione dato Ansia) = 0.75\n#> \n#> Q5: Test di indipendenza\n#>   P(D) × P(A) = 0.2\n#>   P(D ∩ A) = 0.3\n#>   → Eventi DIPENDENTI (correlati)\n#>   Differenza: 0.1\n```\n:::\n\n\n### Visualizzazione della tabella congiunta\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Heatmap\ndf_comorbid <- as.data.frame(as.table(tab_comorbid))\ncolnames(df_comorbid) <- c(\"Depressione\", \"Ansia\", \"Probabilita\")\n\nggplot(df_comorbid, aes(x = Ansia, y = Depressione, fill = Probabilita)) +\n  geom_tile(color = \"white\", size = 2) +\n  geom_text(aes(label = round(Probabilita, 3)), \n            color = \"white\", size = 8, fontface = \"bold\") +\n  scale_fill_viridis_c(option = \"plasma\") +\n  labs(\n    title = \"Tabella congiunta: Depressione × Ansia\",\n    subtitle = \"Comorbidità P(D ∩ A) = 0.30 (cella in basso a sinistra)\"\n  ) +\n  theme_minimal(base_size = 14) +\n  coord_fixed()\n```\n\n::: {.cell-output-display}\n![](02_axioms_coherence_bayesian_files/figure-html/unnamed-chunk-17-1.png){fig-align='center' width=85%}\n:::\n:::\n\n\n## Estensione a tabelle multidimensionali\n\nIl principio della distribuzione congiunta si generalizza naturalmente a sistemi con più variabili e categorie, permettendo di modellare situazioni cliniche più complesse.\n\n### Esempio: depressione e livelli di ansia\n\nConsideriamo uno scenario clinico con due dimensioni:\n\n- Depressione: presenza/assenza (variabile binaria);\n- Severità dell'ansia: nessuna/lieve/grave (variabile ternaria).\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Scenario: Depressione × Severità Ansia (Nessuna/Lieve/Grave)\ntab_2x3 <- matrix(\n  c(0.15, 0.20, 0.15,  # D: Ansia Nessuna/Lieve/Grave\n    0.35, 0.10, 0.05), # D^c: Ansia Nessuna/Lieve/Grave\n  nrow = 2, byrow = TRUE,\n  dimnames = list(\n    Depressione = c(\"D\", \"D^c\"),\n    Ansia = c(\"Nessuna\", \"Lieve\", \"Grave\")\n  )\n)\n\ncat(\"Tabella 2×3:\\n\")\n#> Tabella 2×3:\nprint(tab_2x3)\n#>            Ansia\n#> Depressione Nessuna Lieve Grave\n#>         D      0.15   0.2  0.15\n#>         D^c    0.35   0.1  0.05\n\ncat(\"\\nMarginali:\\n\")\n#> \n#> Marginali:\ncat(\"Depressione:\", rowSums(tab_2x3), \"\\n\")\n#> Depressione: 0.5 0.5\ncat(\"Ansia:\", colSums(tab_2x3), \"\\n\")\n#> Ansia: 0.5 0.3 0.2\ncat(\"Totale:\", sum(tab_2x3), \"\\n\")\n#> Totale: 1\n```\n:::\n\n\n### Visualizzazione della distribuzione congiunta\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndf_2x3 <- as.data.frame(as.table(tab_2x3))\ncolnames(df_2x3) <- c(\"Depressione\", \"SeveritaAnsia\", \"Probabilita\")\n\nggplot(df_2x3, aes(x = SeveritaAnsia, y = Depressione, fill = Probabilita)) +\n  geom_tile(color = \"white\", size = 1) +\n  geom_text(aes(label = round(Probabilita, 2)), \n            color = \"white\", size = 6, fontface = \"bold\") +\n  scale_fill_viridis_c(option = \"plasma\") +\n  labs(\n    title = \"Tabella congiunta 2×3: Depressione × Severità Ansia\",\n    subtitle = \"Ogni cella = credenza nella configurazione specifica\"\n  ) +\n  theme_minimal(base_size = 12)\n```\n\n::: {.cell-output-display}\n![](02_axioms_coherence_bayesian_files/figure-html/unnamed-chunk-19-1.png){fig-align='center' width=85%}\n:::\n:::\n\n\n**Interpretazione clinica:**\n\n- 15%: pazienti depressi con ansia grave;\n- 20%: pazienti depressi con ansia lieve;  \n- 35%: pazienti non depressi senza ansia;\n- le probabilità marginali mostrano la prevalenza complessiva di ciascuna condizione.\n\n## Riflessioni conclusive {.unnumbered .unlisted}\n\nIn questo capitolo abbiamo gettato le basi matematiche per esprimere e manipolare le nostre credenze in modo rigorosamente coerente.\n\n1. **Spazio campionario epistemico**: abbiamo ridefinito lo spazio campionario non come \"tutto ciò che può fisicamente accadere\", ma come \"tutto ciò che riteniamo possibile\", in base al nostro attuale stato di conoscenza.\n\n2. **Assiomi come garanzia di coerenza**: gli assiomi della probabilità non sono leggi della natura, ma come condizioni necessarie per evitare contraddizioni logiche e situazioni di svantaggio certo (Dutch Book).\n\n3. **Vincoli strutturali**: i vincoli di Fréchet ci mostrano che le probabilità congiunte non possono essere assegnate arbitrariamente, ma devono rispettare relazioni matematiche precise con le probabilità marginali.\n\n4. **La potenza delle tabelle congiunte**: la distribuzione congiunta si rivela come la rappresentazione più completa e operativa del nostro stato di credenza. Da questa matrice fondamentale derivano in modo sistematico:\n\n   - **probabilità marginali** (per somma lungo righe o colonne);\n   - **probabilità condizionate** (come rapporti tra celle);\n   - **verifiche di indipendenza** (confrontando prodotti con congiunte);\n   - **qualsiasi altra quantità probabilistica** di interesse.\n\n5. **Validazione attraverso la simulazione**: le verifiche empiriche confermano che le credenze coerenti generano pattern di dati attesi, ma è fondamentale ricordare che i dati non definiscono le credenze, bensì le credenze esprimono il nostro stato di incertezza prima di osservare i dati.\n\n### Vantaggi per la ricerca e la pratica psicologica\n\nQuesto approccio basato su distribuzioni congiunte offre vantaggi concreti:\n\n- **trasparenza**: tutte le assunzioni probabilistiche sono esplicite e verificabili;\n- **potere diagnostico**: le incoerenze logiche diventano immediatamente visibili e correggibili;\n- **flessibilità operativa**: è semplice incorporare nuove informazioni aggiornando la distribuzione;\n- **chiarezza comunicativa**: le tabelle sono intuitive e accessibili anche per chi non è esperto di statistica.\n\n### Prossime direzioni\n\nNei prossimi capitoli utilizzeremo questo solido framework per:\n\n- esplorare l'*equiprobabilità* come caso speciale di simmetria epistemica;\n- approfondire l'*aggiornamento bayesiano* attraverso il calcolo delle probabilità condizionate;\n- applicare questi strumenti a scenari psicologici sempre più complessi.\n\nQuesto capitolo ha stabilito non solo *come* calcolare probabilità, ma *perché* certe regole sono necessarie per pensare in modo razionale in situazioni di incertezza.\n\n## Esercizi {.unnumbered .unlisted}\n\n::: {.callout-important title=\"Problemi\" collapse=\"true\"}\n\n### Esercizi sulla coerenza\n\n1. Verifica se le seguenti assegnazioni per eventi mutuamente esclusivi sono coerenti:\n\n   a. $P(A) = 0.3, P(B) = 0.4, P(C) = 0.3$\n   b. $P(A) = 0.5, P(B) = 0.4, P(C) = 0.2$\n   c. $P(A) = 0.25, P(B) = 0.25, P(C) = 0.25, P(D) = 0.25$\n\n2. Un ricercatore assegna $P(A) = 0.7$ e $P(A^c) = 0.4$. Identifica l'incoerenza e spiega perché viola gli assiomi.\n\n3. Per eventi disgiunti $A$ e $B$ con $P(A) = 0.6$ e $P(B) = 0.3$, qualcuno afferma $P(A \\cup B) = 0.8$. È coerente? Se no, qual è il valore corretto?\n\n### Esercizi sui vincoli di Fréchet\n\n4. Dati $P(A) = 0.4$ e $P(B) = 0.7$:\n\n   a. Calcola i vincoli di Fréchet per $P(A \\cap B)$\n   b. Quali dei seguenti valori sono coerenti: 0.05, 0.1, 0.3, 0.5?\n   c. Visualizza graficamente la regione ammissibile\n\n5. In uno studio su depressione e insonnia:\n\n   - $P(\\text{Depressione}) = 0.30$\n   - $P(\\text{Insonnia}) = 0.45$\n   \n   Determina l'intervallo di valori plausibili per $P(\\text{Depressione} \\cap \\text{Insonnia})$.\n\n6. Scrivi una funzione R che, dati $P(A)$ e $P(B)$, verifichi se un proposto $P(A \\cap B)$ rispetta i vincoli di Fréchet.\n\n### Esercizi su tabelle congiunte\n\n7. Completa la seguente tabella congiunta (alcune celle sono mancanti):\n\n   |       | $B$  | $B^c$ | Marg. |\n   |-------|------|-------|-------|\n   | $A$   | 0.25 | ?     | 0.40  |\n   | $A^c$ | ?    | 0.45  | ?     |\n   | Marg. | ?    | ?     | 1     |\n\n8. Costruisci una tabella congiunta 2×2 per:\n\n   - Test COVID: $P(+) = 0.08$\n   - Malattia: $P(\\text{COVID}) = 0.05$\n   - Sensibilità: $P(+ \\mid \\text{COVID}) = 0.90$\n   \n   Calcola poi:\n   \n   a. $P(\\text{COVID} \\mid +)$ (valore predittivo positivo)\n   b. $P(\\text{COVID} \\mid -)$ (probabilità dopo test negativo)\n   c. Specificità del test\n\n9. Verifica con simulazione Monte Carlo (N=100,000) che la tabella dell'esercizio 8 è coerente confrontando frequenze empiriche con probabilità teoriche.\n\n### Esercizi applicati (psicologia)\n\n10. **Comorbidità**: In un campione clinico:\n\n    - $P(\\text{Depressione}) = 0.55$\n    - $P(\\text{PTSD}) = 0.30$\n    - $P(\\text{PTSD} \\mid \\text{Depressione}) = 0.45$\n    \n    a. Costruisci la tabella congiunta completa\n    b. Calcola $P(\\text{Depressione} \\mid \\text{PTSD})$\n    c. Le due condizioni sono indipendenti?\n    d. Qual è la probabilità di avere almeno una delle due condizioni?\n\n11. **Test psicometrico**: Un test di ansia ha:\n\n    - Sensibilità: 0.80\n    - Specificità: 0.85\n    - Prevalenza nell'ambulatorio: 0.25\n    \n    a. Costruisci la tabella 2×2 per (Ansia × Test)\n    b. Un paziente ha test positivo. Quanto è probabile che sia ansioso?\n    c. Se il test è negativo, quanto è probabile l'assenza di ansia?\n\n12. **Tre diagnosi**: Un paziente può avere Depressione (D), Ansia (A), o Nessuna condizione (N). Assegnazioni:\n\n    - $P(D) = 0.40$\n    - $P(A) = 0.35$\n    - $P(N) = 0.30$\n    \n    Identifica e correggi l'incoerenza.\n\n### Esercizi di pensiero critico\n\n13. Spiega perché, nell'approccio bayesiano, specificare una tabella congiunta coerente è \"più fondamentale\" che specificare separatamente marginali e condizionate.\n\n14. Un frequentista obietta: \"Le tabelle congiunte funzionano solo per spazi finiti. Come gestite il caso continuo?\" Rispondi dall'ottica bayesiana.\n\n15. Due clinici costruiscono tabelle congiunte diverse per Depressione × Test, partendo da prior diversi ma usando la stessa sensibilità/specificità. È un problema? Cosa succederebbe con molti dati?\n\n### Esercizi computazionali\n\n16. Scrivi una funzione R che:\n\n    - Input: vettore di probabilità per eventi mutuamente esclusivi\n    - Output: TRUE se coerente, FALSE con messaggio di errore se incoerente\n    - Bonus: Se incoerente, proponi correzione per normalizzazione\n\n17. Crea una visualizzazione interattiva (Shiny app o plot animato) che mostri come variano i vincoli di Fréchet al variare di $P(A)$ e $P(B)$.\n\n18. Simula 10,000 pazienti secondo la tabella dell'esercizio 10, poi:\n\n    a. Calcola frequenze empiriche delle 4 configurazioni\n    b. Confronta con probabilità teoriche\n    c. Visualizza convergenza all'aumentare di N\n\n:::\n\n::: {.callout-tip title=\"Soluzioni\" collapse=\"true\"}\n\n### Soluzioni esercizi sulla coerenza\n\n1. a. $0.3 + 0.4 + 0.3 = 1.0$ ✓ Coerente  \n   b. $0.5 + 0.4 + 0.2 = 1.1$ ✗ Incoerente (somma > 1)  \n   c. $4 \\times 0.25 = 1.0$ ✓ Coerente\n\n2. Per l'assioma del complemento: $P(A) + P(A^c) = 1$. Ma $0.7 + 0.4 = 1.1 \\neq 1$. Incoerente. Correzione: deve essere $P(A^c) = 0.3$.\n\n3. Per eventi disgiunti: $P(A \\cup B) = P(A) + P(B) = 0.6 + 0.3 = 0.9$. Il valore 0.8 è incoerente (troppo basso).\n\n### Soluzioni vincoli di Fréchet\n\n4. a. Lower: $\\max(0, 0.4 + 0.7 - 1) = 0.1$; Upper: $\\min(0.4, 0.7) = 0.4$  \n      Intervallo: $[0.1, 0.4]$\n   \n   b. Coerenti: 0.1 (al limite), 0.3 (interno), 0.5 (FUORI, troppo alto)  \n      Non coerente: 0.05 (troppo basso)\n\n5. Lower: $\\max(0, 0.30 + 0.45 - 1) = 0$; Upper: $\\min(0.30, 0.45) = 0.30$  \n   Intervallo plausibile: $[0, 0.30]$\n\n6. ```r\n   check_frechet <- function(P_A, P_B, P_AB) {\n     lower <- max(0, P_A + P_B - 1)\n     upper <- min(P_A, P_B)\n     \n     if (P_AB >= lower && P_AB <= upper) {\n       cat(\"✓ Coerente: P(A∩B) ∈ [\", lower, \",\", upper, \"]\\n\")\n       return(TRUE)\n     } else {\n       cat(\"✗ Incoerente: P(A∩B) =\", P_AB, \n           \"ma deve essere in [\", lower, \",\", upper, \"]\\n\")\n       return(FALSE)\n     }\n   }\n   ```\n\n### Soluzioni tabelle congiunte\n\n7. Tabella completata:\n   - $P(A \\cap B^c) = 0.40 - 0.25 = 0.15$\n   - $P(A^c \\cap B) = P(B) - 0.25$ (serve calcolare $P(B)$ da altre info)\n   - $P(A^c) = 1 - 0.40 = 0.60$\n   - $P(A^c \\cap B) = 0.60 - 0.45 = 0.15$\n   - $P(B) = 0.25 + 0.15 = 0.40$\n   - $P(B^c) = 0.15 + 0.45 = 0.60$\n\n   |       | $B$  | $B^c$ | Marg. |\n   |-------|------|-------|-------|\n   | $A$   | 0.25 | 0.15  | 0.40  |\n   | $A^c$ | 0.15 | 0.45  | 0.60  |\n   | Marg. | 0.40 | 0.60  | 1.00  |\n\n8. ```r\n   P_C <- 0.05\n   P_pos <- 0.08\n   sens <- 0.90\n   \n   # Congiunta\n   P_C_and_pos <- sens * P_C  # = 0.045\n   P_C_and_neg <- P_C - P_C_and_pos  # = 0.005\n   P_notC_and_pos <- P_pos - P_C_and_pos  # = 0.035\n   P_notC_and_neg <- 1 - (P_C_and_pos + P_C_and_neg + P_notC_and_pos)  # = 0.915\n   \n   # a) P(C | +) = 0.045 / 0.08 = 0.5625\n   # b) P(C | -) = 0.005 / 0.92 ≈ 0.0054\n   # c) Specificità = P(- | C^c) = 0.915 / 0.95 ≈ 0.963\n   ```\n\n### Soluzioni esercizi applicati\n\n10. ```r\n    P_D <- 0.55\n    P_P <- 0.30\n    P_P_given_D <- 0.45\n    \n    # a) Tabella\n    P_D_and_P <- P_P_given_D * P_D  # = 0.2475\n    P_D_and_notP <- P_D - P_D_and_P  # = 0.3025\n    P_notD_and_P <- P_P - P_D_and_P  # = 0.0525\n    P_notD_and_notP <- 1 - (P_D_and_P + P_D_and_notP + P_notD_and_P)  # = 0.3975\n    \n    # b) P(D | P) = 0.2475 / 0.30 = 0.825\n    \n    # c) Test indipendenza: P(D) × P(P) = 0.55 × 0.30 = 0.165\n    #    P(D ∩ P) = 0.2475 ≠ 0.165 → DIPENDENTI\n    \n    # d) P(D ∪ P) = 0.55 + 0.30 - 0.2475 = 0.6025\n    ```\n\n11. ```r\n    # Vedi soluzione 8, adattata con prevalenza 0.25\n    # a) Tabella costruita con sens=0.80, spec=0.85, prev=0.25\n    # b) P(A | +) = [0.80 × 0.25] / [0.80 × 0.25 + 0.15 × 0.75] ≈ 0.640\n    # c) P(A^c | -) = [0.85 × 0.75] / [0.20 × 0.25 + 0.85 × 0.75] ≈ 0.927\n    ```\n\n12. Somma = 1.05 > 1. Incoerente. Correzione (normalizzazione):\n    - $P(D) = 0.40 / 1.05 ≈ 0.381$\n    - $P(A) = 0.35 / 1.05 ≈ 0.333$\n    - $P(N) = 0.30 / 1.05 ≈ 0.286$\n\n### Soluzioni pensiero critico\n\n13. La tabella congiunta è più fondamentale perché rappresenta lo stato di credenza **completo** sul sistema. Da essa derivano automaticamente (e coerentemente) tutte le marginali e condizionate. Specificare marginali e condizionate separatamente rischia incoerenze (es. $P(A \\mid B) P(B) \\neq P(B \\mid A) P(A)$).\n\n14. Nel continuo si usano **densità di probabilità congiunta** $f(x, y)$. Il principio è identico: la densità congiunta determina tutto (marginali tramite integrazione, condizionate tramite rapporti di densità). La struttura di coerenza è preservata.\n\n15. Non è un problema—riflette informazioni diverse. Con molti dati, la verosimiglianza dominerà e i posterior convergeranno, riducendo l'influenza dei prior diversi. È una caratteristica, non un bug: la soggettività è nelle assunzioni iniziali esplicite.\n\n:::\n\n## Bibliografia {.unnumbered .unlisted}\n",
    "supporting": [
      "02_axioms_coherence_bayesian_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}