{
  "hash": "c495a631e323df627308105bb2be6483",
  "result": {
    "engine": "knitr",
    "markdown": "# Assiomi e coerenza delle credenze {#sec-prob-axioms-coherence}\n\n## Introduzione {.unnumbered .unlisted}\n\nDopo aver introdotto la probabilità come *grado di credenza razionale* nel @sec-prob-interpretation, il presente capitolo sviluppa il quadro matematico per operare coerentemente con tali credenze.   Verrà esaminato come lo *spazio campionario* e gli *eventi* rappresentino possibilità epistemiche, e come gli *assiomi di Kolmogorov* fungano da vincoli di coerenza logica per le nostre assegnazioni probabilistiche.\n\nUn aspetto centrale della trattazione concerne la costruzione e manipolazione di *tabelle di probabilità congiunta*, che costituiscono lo strumento operativo fondamentale per rappresentare credenze su sistemi complessi. Queste tabelle, in particolare nel caso semplice 2×2, rendono esplicita la relazione tra probabilità *congiunte*, *marginali* e *condizionate*, dimostrando come tutte le probabilità di interesse derivino da un'unica struttura coerente.\n\nAttraverso esempi tratti dalla psicologia e mediante simulazioni in R, verranno illustrate metodologie per diagnosticare e correggere incoerenze nelle assegnazioni probabilistiche, nonché per verificare empiricamente come credenze coerenti generino i comportamenti attesi nei dati osservati.\n\n### Panoramica del capitolo {.unnumbered .unlisted}\n\n- Spazio campionario ed eventi come possibilità epistemiche.\n- Assiomi di Kolmogorov come vincoli di coerenza.\n- Diagnosi di incoerenze: additività e vincoli di Fréchet.\n- Tabelle di probabilità congiunta (2×2 e oltre).\n- Derivazione di marginali e condizionate da congiunte.\n- Verifica empirica della coerenza con simulazioni.\n\n::: {.callout-tip collapse=true}\n## Prerequisiti\n\n- Aver letto il @sec-prob-interpretation.\n- Leggere l'@sec-apx-sets (teoria degli insiemi).\n- Familiarità base con R e ggplot2.\n:::\n\n::: {.callout-caution collapse=true title=\"Preparazione del Notebook\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhere::here(\"code\", \"_common.R\") |> \n  source()\n\n# Load packages\nif (!requireNamespace(\"pacman\")) install.packages(\"pacman\")\npacman::p_load(ggplot2, dplyr, tidyr, viridis)\n```\n:::\n\n:::\n\n## Spazio campionario come possibilità epistemiche\n\nNel linguaggio probabilistico classico, lo spazio campionario $\\Omega$ viene definito come l'insieme di tutti gli esiti possibili di un esperimento casuale. Nell'approccio bayesiano, questa definizione richiede una rilettura in chiave epistemica.\n\n::: {#def-sample-space-bayesian}\n### Spazio campionario (visione bayesiana)\n\nLo *spazio campionario* $\\Omega$ rappresenta l'insieme delle *possibilità epistemiche* compatibili con lo stato attuale delle informazioni disponibili. Esso non descrive necessariamente ciò che può accadere fisicamente, ma piuttosto ciò che, dati i limiti della nostra conoscenza attuale, consideriamo logicamente possibile.\n:::\n\n### Caratteristiche dello spazio campionario epistemico\n\nLo spazio campionario epistemico presenta caratteristiche distintive che riflettono la natura soggettiva e informazionale della probabilità bayesiana. La sua composizione dipende criticamente dall'informazione disponibile e può modificarsi in seguito all'acquisizione di nuove evidenze. Ad esempio, prima di osservare l'esito di un test diagnostico, lo spazio campionario comprende i valori \"positivo\" e \"negativo\"; successivamente all'osservazione di un risultato positivo, lo spazio si riduce di conseguenza.\n\nLa definizione dello spazio campionario non è univoca: ricercatori diversi, con informazioni diverse o con assunzioni diverse, possono legittimamente definire spazi campionari diversi per lo stesso fenomeno. La costruzione di $\\Omega$ richiede infine la specificazione attenta del livello di dettaglio rilevante per la particolare domanda di ricerca, riflettendo un bilanciamento tra completezza descrittiva e pertinenza analitica.\n\n::: {.callout-note collapse=\"true\" title=\"Esempio psicologico\"}\n### Spazio campionario per una valutazione clinica {.unnumbered .unlisted}\n\nConsideriamo la valutazione di un paziente per possibile depressione. Lo spazio campionario può essere definito in modi diversi a seconda delle informazioni e degli obiettivi:\n\n**Livello 1 (binario):**\n$$\\Omega_1 = \\{\\text{Depresso}, \\text{Non depresso}\\}.$$\n\n**Livello 2 (severità):**\n$$\\Omega_2 = \\{\\text{Nessuna}, \\text{Lieve}, \\text{Moderata}, \\text{Severa}\\}.$$\n\n**Livello 3 (combinazioni):**\n$$\\Omega_3 = \\{\\text{Depressione}, \\text{Ansia}, \\text{Comorbidità}, \\text{Nessuna}\\}.$$\n\nLa scelta dipende da:\n\n- informazioni disponibili (screening, test, colloquio);\n- obiettivo clinico (screening vs diagnosi differenziale);\n- decisioni da prendere (trattamento, monitoraggio).\n\nOgni spazio è legittimo nel proprio contesto. La probabilità assegnata riflette la credenza in quello specifico spazio.\n:::\n\n## Eventi come proposizioni sul mondo\n\nNella prospettiva bayesiana, un *evento* rappresenta un sottoinsieme di $\\Omega$ che corrisponde a una *proposizione* sul mondo, suscettibile di essere vera o falsa.\n\n::: {#def-event-bayesian}\n### Evento\n\nUn *evento* $A \\subseteq \\Omega$ costituisce una *proposizione* sul mondo alla quale possiamo assegnare un grado di credenza $P(A)$, condizionato allo stato informativo corrente.\n:::\n\n### Operazioni su eventi\n\nLe operazioni insiemistiche tradizionali possiedono interpretazioni epistemiche naturali nel contesto bayesiano. L'*unione* $A \\cup B$ corrisponde all'affermazione che \"la proposizione $A$ oppure la proposizione $B$ è vera\". L'*intersezione* $A \\cap B$ rappresenta la situazione in cui \"entrambe le proposizioni $A$ e $B$ sono vere\". Il *complemento* $A^c$ esprime la negazione \"la proposizione $A$ non è vera\".\n\nL'*insieme vuoto* $\\varnothing$ identifica una proposizione logicamente contraddittoria, necessariamente falsa per vincoli logici. Lo *spazio campionario* $\\Omega$ rappresenta invece una proposizione logicamente vera, affermando che qualcosa accade all'interno dell'insieme delle possibilità epistemiche definite.\n\n::: {.callout-note collapse=\"true\" title=\"Esempio: Eventi in un test psicometrico\"}\n### Proposizioni nella Satisfaction with Life Scale (SWLS)\n\nLa SWLS ha punteggi che vanno da 5 a 35. Definiamo:\n\n- $\\Omega = \\{5, 6, 7, \\ldots, 35\\}$ (possibili punteggi).\n- $A =$ \"Punteggio ≥ 25\" (alta soddisfazione) $= \\{25, 26, \\ldots, 35\\}$.\n- $B =$ \"Punteggio ≤ 15\" (bassa soddisfazione) $= \\{5, 6, \\ldots, 15\\}$.\n- $C =$ \"Punteggio tra 16 e 24\" (soddisfazione moderata) $= \\{16, 17, \\ldots, 24\\}$.\n\nOperazioni:\n\n- $A \\cup B$: \"Soddisfazione alta *o* bassa\" (non moderata).\n- $A \\cap B = \\varnothing$: proposizioni mutualmente esclusive (impossibile avere entrambi).\n- $A^c = B \\cup C$: \"Non alta soddisfazione\".\n- $A \\cup B \\cup C = \\Omega$: proposizioni esaustive.\n\nLa credenza $P(A)$ quantifica quanto riteniamo plausibile, in base a ciò che sappiamo (popolazione, contesto), che un individuo scelto abbia un'alta soddisfazione.\n:::\n\n## Gli assiomi di Kolmogorov come vincoli di coerenza\n\nNel @sec-prob-interpretation abbiamo visto che gli assiomi di Kolmogorov non sono leggi naturali ma vincoli per evitare incoerenze (il cosiddetto *Dutch Book*). Qui li formalizziamo e approfondiamo le loro implicazioni.\n\n::: {#def-probability-measure}\n### Funzione di probabilità (definizione bayesiana)\n\nUna *funzione di probabilità* $P: \\mathcal{F} \\to [0,1]$ assegna a ogni evento $A$ in una famiglia di eventi $\\mathcal{F}$ un numero $P(A)$ che rappresenta il grado di credenza nell'affermazione $A$. Per essere coerente, $P$ deve soddisfare i seguenti *assiomi di coerenza*:\n\n1. **Non-negatività**: $P(A) \\geq 0$ per ogni evento $A$.\n2. **Normalizzazione**: $P(\\Omega) = 1$.\n3. **Additività finita**: se $A$ e $B$ sono eventi disgiunti ($A \\cap B = \\varnothing$), allora\n   $$P(A \\cup B) = P(A) + P(B).$$\n\n4. **Additività numerabile** (per spazi infiniti): se $A_1, A_2, \\ldots$ è una sequenza di eventi mutuamente disgiunti, allora\n   $$P\\left(\\bigcup_{i=1}^{\\infty} A_i\\right) = \\sum_{i=1}^{\\infty} P(A_i).$$\n:::\n\n### Interpretazione epistemica degli assiomi\n\nLa non negatività riflette l'impossibilità di un grado di credenza negativo, dove lo 0 corrisponde a \"impossibile, dato lo stato informativo attuale\" e l'1 a \"certo, dato lo stato informativo attuale\". La normalizzazione esprime la certezza che almeno una delle possibilità epistemiche nello spazio campionario si realizzi. Un valore $P(\\Omega) < 1$ implicherebbe incoerentemente la possibilità che nessuna delle opzioni considerate si verifichi. L'additività stabilisce che, per affermazioni mutualmente esclusive, la credenza nella loro disgiunzione deve equivalere alla somma delle credenze individuali; la violazione di questo principio rende possibile la costruzione di un *Dutch book*.\n\n### Conseguenze immediate degli assiomi\n\nDagli assiomi fondamentali discendono diverse proprietà derivate di notevole utilità pratica.\n\n::: {#thm-probability-properties}\n### Proprietà derivate della probabilità\n\n1. **Probabilità del complemento**: $P(A^c) = 1 - P(A)$.\n2. **Probabilità dell'insieme vuoto**: $P(\\varnothing) = 0$.\n3. **Monotonia (della probabilità)**: se $A \\subseteq B$, allora $P(A) \\leq P(B)$.\n4. **Regola dell'unione** (eventi non disgiunti):\n   $$P(A \\cup B) = P(A) + P(B) - P(A \\cap B).$$\n5. **Principio di inclusione-esclusione** (generalizzazione):\n   $$P(A_1 \\cup A_2 \\cup A_3) = \\sum P(A_i) - \\sum P(A_i \\cap A_j) + P(A_1 \\cap A_2 \\cap A_3).$$\n:::\n\nQueste proprietà non costituiscono assiomi aggiuntivi, ma emergono come conseguenze logiche necessarie dei tre assiomi di base. Una volta accettati i vincoli di coerenza fondamentali, l'intero edificio della teoria della probabilità si sviluppa in modo deduttivo.\n\n## Diagnosi di incoerenze: casi tipici\n\nEsaminiamo come identificare e correggere le incoerenze più frequenti nelle assegnazioni probabilistiche.\n\n### Incoerenza 1: violazione dell'additività\n\nL'errore più comune consiste nel violare il principio di additività per eventi disgiunti, assegnando una probabilità complessiva superiore a quanto logicamente possibile.\n\n::: {.callout-warning title=\"Esempio di incoerenza clinica\"}\n#### Sovrastima delle probabilità {.unlisted .unnumbered}\n\nUn clinico valuta un paziente con sintomi psicotici e assegna i seguenti gradi di credenza a tre diagnosi mutualmente esclusive:\n\n- $P(\\text{Schizofrenia}) = 0.6$;\n- $P(\\text{Disturbo Bipolare}) = 0.5$;  \n- $P(\\text{Nessun disturbo psicotico}) = 0.2$.\n\nLa somma $0.6 + 0.5 + 0.2 = 1.3$ eccede il valore massimo consentito di 1.\n\nQuesta assegnazione risulta incoerente poiché i tre eventi sono:\n\n- *mutualmente esclusivi*: il paziente può ricevere solo una delle tre diagnosi;\n- *collettivamente esaustivi*: coprono tutti gli esiti diagnostici possibili.\n\nIl clinico ha quindi attribuito più credenza (1.3) di quanta fosse disponibile (1.0), come se possedesse il 130% di certezza invece del 100%.\n:::\n\n### Incoerenza 2: violazione dei vincoli di Fréchet per congiunzioni di eventi\n\nQuando consideriamo due eventi che possono verificarsi congiuntamente, la probabilità della loro intersezione $P(A \\cap B)$ non può essere assegnata liberamente, ma deve rispettare precisi vincoli matematici derivanti dalla struttura logica della probabilità.\n\n::: {#thm-frechet-bounds}\n### Vincoli di Fréchet\n\nPer qualsiasi coppia di eventi $A$ e $B$ vale la disuguaglianza:\n\n$$\n\\max\\{0,\\, P(A) + P(B) - 1\\} \\;\\leq\\; P(A \\cap B) \\;\\leq\\; \\min\\{P(A), P(B)\\}.\n$$\n\n**Interpretazione intuitiva:**\n\nIl limite superiore stabilisce che l'evento congiunto \"$A$ e $B$ insieme\" non può essere più probabile dell'evento singolo meno probabile tra $A$ e $B$. Il limite inferiore indica che quando la somma delle probabilità individuali supera 1, allora $A$ e $B$ devono necessariamente sovrapporsi almeno in parte.\n:::\n\n::: {.callout-note collapse=\"true\" title=\"Esempio clinico: Depressione e Ansia\"}\n#### Applicazione alla comorbidità psicologica {.unnumbered .unlisted}\n\nConsideriamo uno studio su una popolazione clinica in cui la probabilità di depressione è $P(\\text{Depressione}) = 0.6$ e la probabilità di ansia è $P(\\text{Ansia}) = 0.5$. I vincoli di Fréchet determinano l'intervallo di valori logicamente possibili per la comorbidità $P(\\text{Depressione} \\cap \\text{Ansia})$.\n\nIl limite inferiore risulta $\\max(0, 0.6 + 0.5 - 1) = 0.1$, mentre il limite superiore è $\\min(0.6, 0.5) = 0.5$. Pertanto, l'intervallo ammissibile per la probabilità di comorbidità è compreso tra 0.1 e 0.5.\n\nQuesta delimitazione ha implicazioni pratiche immediate: sarebbe logicamente incoerente affermare che solo il 5% della popolazione presenta comorbidità, così come sarebbe incoerente sostenere che il 60% mostra comorbidità. Qualsiasi valore compreso tra il 10% e il 50% risulta invece logicamente possibile.\n:::\n\n### Mappa dei valori ammissibili\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Creare griglia di valori\ngrid <- expand.grid(\n  P_A = seq(0, 1, by = 0.02),\n  P_B = seq(0, 1, by = 0.02)\n)\n\n# Calcolare vincoli per ogni coppia\ngrid$limite_inferiore <- pmax(0, grid$P_A + grid$P_B - 1)\ngrid$limite_superiore <- pmin(grid$P_A, grid$P_B)\ngrid$ampiezza_lecita <- grid$limite_superiore - grid$limite_inferiore\n\n# Visualizzazione\nggplot(grid, aes(x = P_A, y = P_B, fill = ampiezza_lecita)) +\n  geom_tile() +\n  scale_fill_viridis_c(\n    name = \"Ampiezza dell'intervallo\\nammissibile\",\n    option = \"plasma\",\n    limits = c(0, 1)\n  ) +\n  labs(\n    title = \"Vincoli di Fréchet: intervalli ammissibili per P(A ∩ B)\",\n    subtitle = \"Per ogni coppia (P(A), P(B)), l'area colorata mostra quanti valori di P(A ∩ B) \\nsono logicamente possibili\",\n    x = \"P(A)\",\n    y = \"P(B)\",\n    caption = \"Colori più chiari = maggiore libertà nella scelta di P(A ∩ B)\"\n  ) +\n  theme_minimal() +\n  coord_fixed()\n```\n\n::: {.cell-output-display}\n![Regione dei valori ammissibili per P(A ∩ B) in funzione di P(A) e P(B).](02_axioms_coherence_bayesian_files/figure-pdf/unnamed-chunk-2-1.png){fig-align='center' fig-pos='H' width=80%}\n:::\n:::\n\n\nLa mappa visualizza la relazione tra le probabilità marginali e l'ampiezza dell'intervallo ammissibile per la loro intersezione. Le regioni in blu scuro, corrispondenti agli angoli del quadrato unitario, indicano vincoli particolarmente stringenti che limitano fortemente i valori possibili per $P(A \\cap B)$. Al contrario, le regioni in giallo, situate verso il centro della mappa, segnalano la massima libertà nella scelta della probabilità dell'intersezione.\n\nNella regione in alto a destra, dove $P(A) + P(B) > 1$, esiste una sovrapposizione minima obbligatoria tra gli eventi. Nella regione in basso a sinistra, dove $P(A) + P(B) \\leq 1$, la sovrapposizione può teoricamente essere nulla.\n\nQuesti vincoli matematici offrono una protezione formale contro l'assegnazione di probabilità logicamente impossibili a sintomi che si presentano insieme o a condizioni psicologiche che co-occorrono, risultando particolarmente utili nella pratica clinica e nella ricerca psicometrica.\n\n## Tabelle di probabilità congiunta\n\nLe **tabelle di probabilità congiunta** consentono di rappresentare sistematicamente l'intero sistema di credenze relative a un fenomeno caratterizzato da molteplici eventi. Tali tabelle rendono esplicite tutte le possibili combinazioni degli esiti e costituiscono la base da cui emergono coerentemente le probabilità marginali, quelle condizionate e le relazioni di indipendenza statistica.\n\n### Struttura di una tabella 2×2\n\nConsideriamo due eventi dicotomici $A$ e $B$. La loro distribuzione congiunta trova rappresentazione in una tabella 2×2 che organizza le probabilità secondo la seguente struttura:\n\n|               | $B$             | $B^c$             | Marginale |\n| ------------- | --------------- | ----------------- | --------- |\n| $A$           | $P(A \\cap B)$   | $P(A \\cap B^c)$   | $P(A)$    |\n| $A^c$         | $P(A^c \\cap B)$ | $P(A^c \\cap B^c)$ | $P(A^c)$  |\n| **Marginale** | $P(B)$          | $P(B^c)$          | $1$       |\n\nLe celle interne della tabella contengono le quattro probabilità congiunte che specificano il grado di credenza in ciascuna combinazione di eventi. Le probabilità marginali, collocate sui bordi della tabella, si ottengono mediante la somma lungo le righe e le colonne: $P(A)$ è uguale alla somma $P(A\\cap B) + P(A\\cap B^c)$, mentre $P(B)$ deriva da $P(A\\cap B) + P(A^c\\cap B)$.\n\nLa coerenza complessiva della distribuzione è garantita dal vincolo di normalizzazione che impone che la somma di tutte le probabilità congiunte sia pari a 1. Una volta stabilita una tabella congiunta coerente, tutte le ulteriori quantità probabilistiche di interesse diventano accessibili attraverso operazioni algebriche elementari di somma e normalizzazione.\n\n::: {.callout-note collapse=true title=\"Esempio di costruzione di una tabella di probabilità congiunta 2×2\"}\n\n#### Definizione dello scenario {.unnumbered .unlisted}\n\nConsideriamo un test diagnostico per la depressione caratterizzato da due variabili dicotomiche: lo stato reale del paziente ($D$ per depresso, $D^c$ per non depresso) e l'esito del test ($T^+$ per positivo, $T^-$ per negativo). I parametri noti dalla letteratura clinica includono una prevalenza della depressione $P(D) = 0.15$, una sensibilità del test $P(T^+ \\mid D) = 0.85$, e un tasso di falsi positivi $P(T^+ \\mid D^c) = 0.20$.\n\n**Costruzione della tabella di probabilità congiunta:**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Parametri di base\nprevalenza <- 0.15\nsensibilita <- 0.85\ntasso_falsi_positivi <- 0.20\n\n# Calcolo delle probabilità congiunte\np_depresso_positivo <- sensibilita * prevalenza\np_depresso_negativo <- (1 - sensibilita) * prevalenza\np_non_depresso_positivo <- tasso_falsi_positivi * (1 - prevalenza)\np_non_depresso_negativo <- (1 - tasso_falsi_positivi) * (1 - prevalenza)\n\n# Creazione della tabella\ntabella_congiunta <- matrix(\n  c(p_depresso_positivo, p_depresso_negativo,\n    p_non_depresso_positivo, p_non_depresso_negativo),\n  nrow = 2,\n  byrow = TRUE,\n  dimnames = list(\n    \"Stato reale\" = c(\"Depresso\", \"Non depresso\"),\n    \"Risultato test\" = c(\"Positivo\", \"Negativo\")\n  )\n)\n\nprint(round(tabella_congiunta, 4))\n#>               Risultato test\n#> Stato reale    Positivo Negativo\n#>   Depresso        0.128   0.0225\n#>   Non depresso    0.170   0.6800\n```\n:::\n\n\nLa tabella risultante presenta una struttura coerente: la probabilità che un paziente sia depresso e risulti positivo al test ammonta a 0.1275, mentre la probabilità di un falso negativo è 0.0225. Per i non depressi, la probabilità di un falso positivo è 0.1700 e quella di un risultato corretto negativo è 0.6800. La coerenza della tabella è verificata dalla non negatività di tutte le probabilità e dalla somma totale pari a 1, conformemente agli assiomi della probabilità.\n\n#### Visualizzazione della tabella congiunta {.unnumbered .unlisted}\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](02_axioms_coherence_bayesian_files/figure-pdf/unnamed-chunk-4-1.png){fig-align='center' width=85%}\n:::\n:::\n\n\n#### Verifica empirica mediante simulazione {.unnumbered .unlisted}\n\nLa coerenza della distribuzione congiunta può essere verificata empiricamente attraverso simulazione:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(123)\nN <- 100000\n\n# Simulare secondo la distribuzione congiunta\nprobs_vector <- c(p_depresso_positivo, p_depresso_negativo, \n                  p_non_depresso_positivo, p_non_depresso_negativo)\n\noutcomes <- sample(1:4, size = N, replace = TRUE, prob = probs_vector)\n\n# Contare frequenze empiriche\nfreq_empiriche <- table(outcomes) / N\n\n# Confronto tra probabilità teoriche e frequenze empiriche\ndf_verifica <- data.frame(\n  Configurazione = c(\"D∩T+\", \"D∩T-\", \"D^c∩T+\", \"D^c∩T-\"),\n  Teorica = probs_vector,\n  Empirica = as.numeric(freq_empiriche)\n)\n\ndf_verifica$Teorica <- round(df_verifica$Teorica, 4)\ndf_verifica$Empirica <- round(df_verifica$Empirica, 4)\nprint(df_verifica)\n#>   Configurazione Teorica Empirica\n#> 1           D∩T+  0.1275   0.1266\n#> 2           D∩T-  0.0225   0.0226\n#> 3         D^c∩T+  0.1700   0.1699\n#> 4         D^c∩T-  0.6800   0.6809\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](02_axioms_coherence_bayesian_files/figure-pdf/unnamed-chunk-6-1.png){fig-align='center' width=85%}\n:::\n:::\n\n\nLa convergenza delle frequenze empiriche verso le probabilità teoriche conferma che la tabella di probabilità congiunta rappresenta un sistema di credenze coerente in grado di generare i dati attesi.\n:::\n\n### Calcolo di probabilità marginali e condizionate\n\nLa distribuzione congiunta rappresenta la conoscenza completa del sistema analizzato e costituisce il fondamento da cui è possibile dedurre in modo coerente tutte le altre probabilità di interesse.\n\n### Probabilità marginali\n\nLe probabilità *marginali* si ottengono mediante sommazione lungo una dimensione della tabella congiunta. Formalmente:\n\n$$\nP(A) = P(A \\cap B) + P(A \\cap B^c),\n$$\n\n$$\nP(B) = P(A \\cap B) + P(A^c \\cap B).\n$$\n\nQuesto calcolo corrisponde a proiettare la distribuzione congiunta su ciascuna variabile singolarmente, ignorando l'altra dimensione.\n\n\n::: {.cell layout-align=\"center\"}\n\n```\n#> Probabilità marginali derivate:\n#> P(D) = 0.15\n#> P(D^c) = 0.85\n#> P(T+) = 0.297\n#> P(T-) = 0.703\n```\n:::\n\n\n### Probabilità condizionate\n\nLe probabilità *condizionate* emergono come rapporto tra probabilità congiunta e probabilità marginale dell'evento condizionante:\n\n$$\nP(A \\mid B) = \\frac{P(A \\cap B)}{P(B)}.\n$$\n\nEpistemicamente, esse rappresentano l'aggiornamento delle nostre credenze una volta acquisita l'informazione che l'evento $B$ si è verificato: lo spazio delle possibilità si restringe alle configurazioni compatibili con $B$, e le probabilità vengono conseguentemente rinormalizzate.\n\n\n::: {.cell layout-align=\"center\"}\n\n```\n#> Probabilità condizionate derivate:\n#> P(D | T+) = 0.429 (Valore predittivo positivo)\n#> P(D | T-) = 0.032 (Probabilità residua dopo test negativo)\n```\n:::\n\n\n::: {.callout-important}\n\n### Messaggio chiave: la coerenza delle probabilità condizionate\n\nLe probabilità condizionate non rappresentano assegnazioni indipendenti, ma derivano necessariamente dalla distribuzione congiunta attraverso operazioni matematiche ben definite.\n\nQuesta dipendenza strutturale garantisce la coerenza interna dell'intero sistema probabilistico. Qualora si tentasse di specificare probabilità condizionate in modo arbitrario e indipendente dalla distribuzione congiunta, si incorrerebbe in serie incoerenze quali:\n\n* discrepanze tra il prodotto $P(A \\mid B) \\cdot P(B)$ e la probabilità congiunta $P(A \\cap B)$;\n* violazioni degli assiomi fondamentali della probabilità;\n* esposizione al rischio di un *Dutch book*, situazione in cui una combinazione di scommesse condurrebbe a una perdita certa.\n\nLa distribuzione congiunta funge dunque da fondamento coerente da cui tutte le altre quantità probabilistiche discendono logicamente.\n:::\n\n### Visualizzazione: dalla congiunta alle condizionate\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](02_axioms_coherence_bayesian_files/figure-pdf/unnamed-chunk-9-1.png){fig-align='center' width=85%}\n:::\n:::\n\n\n## Esercizio guidato: costruire e analizzare una tabella 2×2\n\nLavoriamo attraverso un approccio sistematico per la costruzione di una tabella di probabilità congiunta a partire da informazioni cliniche.\n\n::: {.callout-tip title=\"Scenario clinico\"}\n### Comorbidità Depressione-Ansia in terapia\n\nUno psicoterapeuta intende modellare probabilisticamente la comorbidità nel proprio contesto clinico. Sulla base della letteratura scientifica e dell'esperienza clinica accumulata, stabilisce i seguenti parametri:\n\n- $P(\\text{Depressione}) = 0.50$ (prevalenza nel setting ambulatoriale);\n- $P(\\text{Ansia}) = 0.40$;\n- $P(\\text{Ansia} \\mid \\text{Depressione}) = 0.60$ (probabilità di comorbidità condizionata).\n\n**Obiettivo**: Costruire la tabella di probabilità congiunta completa e derivare risposte a specifiche domande cliniche.\n:::\n\nParametri:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nP_D <- 0.50\nP_A <- 0.40\nP_A_given_D <- 0.60\n```\n:::\n\n\nPasso 1: Calcolare congiunta $P(D \\cap A)$:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nP_D_and_A <- P_A_given_D * P_D\ncat(\"Passo 1: P(D ∩ A) = P(A|D) × P(D) =\", P_A_given_D, \"×\", P_D, \"=\", P_D_and_A, \"\\n\\n\")\n#> Passo 1: P(D ∩ A) = P(A|D) × P(D) = 0.6 × 0.5 = 0.3\n```\n:::\n\n\nPasso 2: le altre celle si possono calcolare usando l'additività:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nP_D_and_notA <- P_D - P_D_and_A\nP_notD_and_A <- P_A - P_D_and_A\nP_notD_and_notA <- 1 - (P_D_and_A + P_D_and_notA + P_notD_and_A)\n\ncat(\"Passo 2: Altre celle\\n\")\n#> Passo 2: Altre celle\ncat(\"  P(D ∩ A^c) =\", P_D_and_notA, \"\\n\")\n#>   P(D ∩ A^c) = 0.2\ncat(\"  P(D^c ∩ A) =\", P_notD_and_A, \"\\n\")\n#>   P(D^c ∩ A) = 0.1\ncat(\"  P(D^c ∩ A^c) =\", P_notD_and_notA, \"\\n\\n\")\n#>   P(D^c ∩ A^c) = 0.4\n```\n:::\n\n\nPasso 3: Verificare coerenza:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsomma_celle <- P_D_and_A + P_D_and_notA + P_notD_and_A + P_notD_and_notA\ncat(\"Passo 3: Verifica coerenza\\n\")\n#> Passo 3: Verifica coerenza\ncat(\"  Somma celle =\", somma_celle, \"(deve essere 1) ✓\\n\\n\")\n#>   Somma celle = 1 (deve essere 1) ✓\n```\n:::\n\n\nCreare tabella:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ntab_comorbid <- matrix(\n  c(P_D_and_A, P_D_and_notA,\n    P_notD_and_A, P_notD_and_notA),\n  nrow = 2, byrow = TRUE,\n  dimnames = list(\n    Depressione = c(\"D\", \"D^c\"),\n    Ansia = c(\"A\", \"A^c\")\n  )\n)\n\ncat(\"TABELLA CONGIUNTA FINALE:\\n\")\n#> TABELLA CONGIUNTA FINALE:\nprint(round(tab_comorbid, 3))\n#>            Ansia\n#> Depressione   A A^c\n#>         D   0.3 0.2\n#>         D^c 0.1 0.4\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncat(\"\\nMARGINALI:\\n\")\n#> \n#> MARGINALI:\ncat(\"Riga (Depressione):\", round(rowSums(tab_comorbid), 3), \"\\n\")\n#> Riga (Depressione): 0.5 0.5\ncat(\"Colonna (Ansia):\", round(colSums(tab_comorbid), 3), \"\\n\")\n#> Colonna (Ansia): 0.4 0.6\n```\n:::\n\n\n### Risposte a domande cliniche\n\nQ1: Probabilità di almeno una condizione:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nP_D_or_A <- P_D + P_A - P_D_and_A\ncat(\"Q1: P(D ∪ A) = P(almeno una condizione) =\", round(P_D_or_A, 3), \"\\n\")\n#> Q1: P(D ∪ A) = P(almeno una condizione) = 0.6\n```\n:::\n\n\nQ2: Probabilità di nessuna condizione:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nP_neither <- P_notD_and_notA\ncat(\"Q2: P(D^c ∩ A^c) = P(nessuna condizione) =\", round(P_neither, 3), \"\\n\")\n#> Q2: P(D^c ∩ A^c) = P(nessuna condizione) = 0.4\n```\n:::\n\n\nQ3: Probabilità di comorbidità:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncat(\"Q3: P(D ∩ A) = P(entrambe le condizioni) =\", round(P_D_and_A, 3), \"\\n\")\n#> Q3: P(D ∩ A) = P(entrambe le condizioni) = 0.3\n```\n:::\n\n\nQ4: $P(D \\mid A)$ -- Se un paziente manifesta un disturbo d'ansia, qual è la probabilità che sia anche depresso?\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nP_D_given_A <- P_D_and_A / P_A\ncat(\"Q4: P(D | A) = P(Depressione dato Ansia) =\", round(P_D_given_A, 3), \"\\n\")\n#> Q4: P(D | A) = P(Depressione dato Ansia) = 0.75\n```\n:::\n\n\nQ5: Le condizioni sono indipendenti?\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Test: P(D ∩ A) =? P(D) × P(A)\nP_D_times_P_A <- P_D * P_A\ncat(\"\\nQ5: Test di indipendenza\\n\")\n#> \n#> Q5: Test di indipendenza\ncat(\"  P(D) × P(A) =\", round(P_D_times_P_A, 3), \"\\n\")\n#>   P(D) × P(A) = 0.2\ncat(\"  P(D ∩ A) =\", round(P_D_and_A, 3), \"\\n\")\n#>   P(D ∩ A) = 0.3\nif (abs(P_D_and_A - P_D_times_P_A) < 1e-9) {\n  cat(\"  → Eventi INDIPENDENTI\\n\")\n} else {\n  cat(\"  → Eventi DIPENDENTI (correlati)\\n\")\n  cat(\"  Differenza:\", round(P_D_and_A - P_D_times_P_A, 3), \"\\n\")\n}\n#>   → Eventi DIPENDENTI (correlati)\n#>   Differenza: 0.1\n```\n:::\n\n\n### Visualizzazione della tabella congiunta\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Heatmap\ndf_comorbid <- as.data.frame(as.table(tab_comorbid))\ncolnames(df_comorbid) <- c(\"Depressione\", \"Ansia\", \"Probabilita\")\n\nggplot(df_comorbid, aes(x = Ansia, y = Depressione, fill = Probabilita)) +\n  geom_tile(color = \"white\", size = 2) +\n  geom_text(aes(label = round(Probabilita, 3)), \n            color = \"white\", size = 8, fontface = \"bold\") +\n  scale_fill_viridis_c(option = \"plasma\") +\n  labs(\n    title = \"Tabella congiunta: Depressione × Ansia\",\n    subtitle = \"Comorbidità P(D ∩ A) = 0.30 (cella in alto a sinistra)\"\n  ) +\n  theme_minimal() +\n  coord_fixed()\n```\n\n::: {.cell-output-display}\n![](02_axioms_coherence_bayesian_files/figure-pdf/unnamed-chunk-21-1.png){fig-align='center' fig-pos='H' width=85%}\n:::\n:::\n\n\n## Estensione a tabelle multidimensionali\n\nIl principio della distribuzione congiunta si generalizza naturalmente a sistemi caratterizzati da molteplici variabili e categorie, consentendo la modellazione di scenari clinici di maggiore complessità.\n\n### Esempio: depressione e livelli di ansia\n\nConsideriamo uno scenario clinico che coinvolge due dimensioni distinte:\n\n- depressione: presenza/assenza (variabile dicotomica);\n- severità dell'ansia: nessuna/lieve/grave (variabile a tre livelli).\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Scenario: Depressione × Severità Ansia (Nessuna/Lieve/Grave)\ntab_2x3 <- matrix(\n  c(0.15, 0.20, 0.15,  # D: Ansia Nessuna/Lieve/Grave\n    0.35, 0.10, 0.05), # D^c: Ansia Nessuna/Lieve/Grave\n  nrow = 2, byrow = TRUE,\n  dimnames = list(\n    Depressione = c(\"D\", \"D^c\"),\n    Ansia = c(\"Nessuna\", \"Lieve\", \"Grave\")\n  )\n)\n\ncat(\"Tabella 2×3:\\n\")\n#> Tabella 2×3:\nprint(tab_2x3)\n#>            Ansia\n#> Depressione Nessuna Lieve Grave\n#>         D      0.15   0.2  0.15\n#>         D^c    0.35   0.1  0.05\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncat(\"\\nMarginali:\\n\")\n#> \n#> Marginali:\ncat(\"Depressione:\", rowSums(tab_2x3), \"\\n\")\n#> Depressione: 0.5 0.5\ncat(\"Ansia:\", colSums(tab_2x3), \"\\n\")\n#> Ansia: 0.5 0.3 0.2\ncat(\"Totale:\", sum(tab_2x3), \"\\n\")\n#> Totale: 1\n```\n:::\n\n\n### Visualizzazione della distribuzione congiunta\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndf_2x3 <- as.data.frame(as.table(tab_2x3))\ncolnames(df_2x3) <- c(\"Depressione\", \"SeveritaAnsia\", \"Probabilita\")\n\nggplot(df_2x3, aes(x = SeveritaAnsia, y = Depressione, fill = Probabilita)) +\n  geom_tile(color = \"white\", size = 1) +\n  geom_text(aes(label = round(Probabilita, 2)), \n            color = \"white\", size = 6, fontface = \"bold\") +\n  scale_fill_viridis_c(option = \"plasma\") +\n  labs(\n    title = \"Tabella congiunta 2×3: Depressione × Severità Ansia\",\n    x = \"Ansia\",\n    subtitle = \"Ogni cella rappresenta la credenza in una specifica configurazione clinica\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](02_axioms_coherence_bayesian_files/figure-pdf/unnamed-chunk-24-1.png){fig-align='center' fig-pos='H' width=85%}\n:::\n:::\n\n\n**Interpretazione clinica:**\nla distribuzione congiunta rivela i pattern della presentazione clinica: il 15% dei pazienti presenta una comorbilità di depressione con ansia grave, mentre il 20% mostra una depressione associata a un'ansia lieve. Una porzione consistente del 35% comprende pazienti non depressi, senza sintomi d'ansia. Le probabilità marginali, ottenute sommando i valori lungo le rispettive dimensioni, forniscono una stima della prevalenza complessiva di ciascuna condizione nella popolazione clinica di riferimento.\n\n## Riflessioni conclusive {.unnumbered .unlisted}\n\nIn questo capitolo abbiamo gettato le basi matematiche per esprimere e manipolare le nostre credenze in modo coerente. Lo spazio campionario è stato ridefinito in chiave epistemologica: non è l'insieme di tutto ciò che può accadere fisicamente, ma l'insieme di ciò che riteniamo possibile, in base al nostro attuale stato di conoscenza.\n\nGli assiomi della probabilità non emergono come leggi naturali, ma come condizioni necessarie per garantire la coerenza logica e proteggere da situazioni di svantaggio certo, come dimostrato dall'argomento del Dutch Book. I vincoli di Fréchet dimostrano che le probabilità congiunte non possono essere assegnate arbitrariamente, ma devono rispettare precise relazioni matematiche con le probabilità marginali.\n\nLa distribuzione congiunta si rivela la rappresentazione più completa e operativa del nostro stato di credenza. Da questa matrice fondamentale derivano sistematicamente le probabilità marginali mediante la somma lungo righe o colonne, le probabilità condizionate come rapporti tra celle, le verifiche di indipendenza mediante il confronto tra prodotti e probabilità congiunte e qualsiasi altra quantità probabilistica di interesse.\n\nLe verifiche empiriche mediante simulazione confermano che le credenze coerenti generano pattern di dati attesi, ribadendo il principio fondamentale secondo cui i dati non definiscono le credenze, ma piuttosto le credenze esprimono il nostro stato di incertezza prima dell'osservazione dei dati.\n\nQuesto approccio basato sulle distribuzioni congiunte offre vantaggi concreti sia alla ricerca che alla pratica psicologica. La trasparenza garantisce che tutte le assunzioni probabilistiche siano esplicite e verificabili, mentre il potere diagnostico consente di individuare e correggere immediatamente le incoerenze logiche. La flessibilità operativa consente di incorporare agevolmente nuove informazioni aggiornando la distribuzione, mentre la chiarezza comunicativa rende le tabelle intuitive e accessibili anche per chi non possiede competenze statistiche avanzate.\n\nQuesto capitolo non solo ha stabilito le modalità di calcolo delle probabilità, ma ha anche chiarito le ragioni per cui determinate regole sono necessarie per pensare in modo razionale in condizioni di incertezza, fornendo le basi concettuali per sviluppare un approccio bayesiano coerente alla ricerca psicologica.\n\nNei prossimi capitoli, utilizzeremo questo solido framework per esplorare l'equiprobabilità come caso speciale di simmetria epistemica, approfondire l'aggiornamento bayesiano attraverso il calcolo delle probabilità condizionate e applicare questi strumenti a scenari psicologici sempre più complessi.\n\n\n## Esercizi {.unnumbered .unlisted}\n\n::: {.callout-important title=\"Problemi\" collapse=\"true\"}\n\n### Esercizi sulla coerenza\n\n1. Verifica se le seguenti assegnazioni per eventi mutuamente esclusivi sono coerenti:\n\n   a. $P(A) = 0.3, P(B) = 0.4, P(C) = 0.3$\n   b. $P(A) = 0.5, P(B) = 0.4, P(C) = 0.2$\n   c. $P(A) = 0.25, P(B) = 0.25, P(C) = 0.25, P(D) = 0.25$\n\n2. Un ricercatore assegna $P(A) = 0.7$ e $P(A^c) = 0.4$. Identifica l'incoerenza e spiega perché viola gli assiomi.\n\n3. Per eventi disgiunti $A$ e $B$ con $P(A) = 0.6$ e $P(B) = 0.3$, qualcuno afferma $P(A \\cup B) = 0.8$. È coerente? Se no, qual è il valore corretto?\n\n### Esercizi sui vincoli di Fréchet\n\n4. Dati $P(A) = 0.4$ e $P(B) = 0.7$:\n\n   a. Calcola i vincoli di Fréchet per $P(A \\cap B)$\n   b. Quali dei seguenti valori sono coerenti: 0.05, 0.1, 0.3, 0.5?\n   c. Visualizza graficamente la regione ammissibile\n\n5. In uno studio su depressione e insonnia:\n\n   - $P(\\text{Depressione}) = 0.30$\n   - $P(\\text{Insonnia}) = 0.45$\n   \n   Determina l'intervallo di valori plausibili per $P(\\text{Depressione} \\cap \\text{Insonnia})$.\n\n6. Scrivi una funzione R che, dati $P(A)$ e $P(B)$, verifichi se un proposto $P(A \\cap B)$ rispetta i vincoli di Fréchet.\n\n### Esercizi su tabelle congiunte\n\n7. Completa la seguente tabella congiunta (alcune celle sono mancanti):\n\n   |       | $B$  | $B^c$ | Marg. |\n   |-------|------|-------|-------|\n   | $A$   | 0.25 | ?     | 0.40  |\n   | $A^c$ | ?    | 0.45  | ?     |\n   | Marg. | ?    | ?     | 1     |\n\n8. Costruisci una tabella congiunta 2×2 per:\n\n   - Test COVID: $P(+) = 0.08$\n   - Malattia: $P(\\text{COVID}) = 0.05$\n   - Sensibilità: $P(+ \\mid \\text{COVID}) = 0.90$\n   \n   Calcola poi:\n   \n   a. $P(\\text{COVID} \\mid +)$ (valore predittivo positivo)\n   b. $P(\\text{COVID} \\mid -)$ (probabilità dopo test negativo)\n   c. Specificità del test\n\n9. Verifica con simulazione Monte Carlo (N=100,000) che la tabella dell'esercizio 8 è coerente confrontando frequenze empiriche con probabilità teoriche.\n\n### Esercizi applicati (psicologia)\n\n10. **Comorbidità**: In un campione clinico:\n\n    - $P(\\text{Depressione}) = 0.55$\n    - $P(\\text{PTSD}) = 0.30$\n    - $P(\\text{PTSD} \\mid \\text{Depressione}) = 0.45$\n    \n    a. Costruisci la tabella congiunta completa\n    b. Calcola $P(\\text{Depressione} \\mid \\text{PTSD})$\n    c. Le due condizioni sono indipendenti?\n    d. Qual è la probabilità di avere almeno una delle due condizioni?\n\n11. **Test psicometrico**: Un test di ansia ha:\n\n    - Sensibilità: 0.80\n    - Specificità: 0.85\n    - Prevalenza nell'ambulatorio: 0.25\n    \n    a. Costruisci la tabella 2×2 per (Ansia × Test)\n    b. Un paziente ha test positivo. Quanto è probabile che sia ansioso?\n    c. Se il test è negativo, quanto è probabile l'assenza di ansia?\n\n12. **Tre diagnosi**: Un paziente può avere Depressione (D), Ansia (A), o Nessuna condizione (N). Assegnazioni:\n\n    - $P(D) = 0.40$\n    - $P(A) = 0.35$\n    - $P(N) = 0.30$\n    \n    Identifica e correggi l'incoerenza.\n\n### Esercizi di pensiero critico\n\n13. Spiega perché, nell'approccio bayesiano, specificare una tabella congiunta coerente è \"più fondamentale\" che specificare separatamente marginali e condizionate.\n\n14. Un frequentista obietta: \"Le tabelle congiunte funzionano solo per spazi finiti. Come gestite il caso continuo?\" Rispondi dall'ottica bayesiana.\n\n15. Due clinici costruiscono tabelle congiunte diverse per Depressione × Test, partendo da prior diversi ma usando la stessa sensibilità/specificità. È un problema? Cosa succederebbe con molti dati?\n\n### Esercizi computazionali\n\n16. Scrivi una funzione R che:\n\n    - Input: vettore di probabilità per eventi mutuamente esclusivi\n    - Output: TRUE se coerente, FALSE con messaggio di errore se incoerente\n    - Bonus: Se incoerente, proponi correzione per normalizzazione\n\n17. Crea una visualizzazione interattiva (Shiny app o plot animato) che mostri come variano i vincoli di Fréchet al variare di $P(A)$ e $P(B)$.\n\n18. Simula 10,000 pazienti secondo la tabella dell'esercizio 10, poi:\n\n    a. Calcola frequenze empiriche delle 4 configurazioni\n    b. Confronta con probabilità teoriche\n    c. Visualizza convergenza all'aumentare di N\n\n:::\n\n::: {.callout-tip title=\"Soluzioni\" collapse=\"true\"}\n\n### Soluzioni esercizi sulla coerenza\n\n1. a. $0.3 + 0.4 + 0.3 = 1.0$ ✓ Coerente  \n   b. $0.5 + 0.4 + 0.2 = 1.1$ ✗ Incoerente (somma > 1)  \n   c. $4 \\times 0.25 = 1.0$ ✓ Coerente\n\n2. Per l'assioma del complemento: $P(A) + P(A^c) = 1$. Ma $0.7 + 0.4 = 1.1 \\neq 1$. Incoerente. Correzione: deve essere $P(A^c) = 0.3$.\n\n3. Per eventi disgiunti: $P(A \\cup B) = P(A) + P(B) = 0.6 + 0.3 = 0.9$. Il valore 0.8 è incoerente (troppo basso).\n\n### Soluzioni vincoli di Fréchet\n\n4. a. Lower: $\\max(0, 0.4 + 0.7 - 1) = 0.1$; Upper: $\\min(0.4, 0.7) = 0.4$  \n      Intervallo: $[0.1, 0.4]$\n   \n   b. Coerenti: 0.1 (al limite), 0.3 (interno), 0.5 (FUORI, troppo alto)  \n      Non coerente: 0.05 (troppo basso)\n\n5. Lower: $\\max(0, 0.30 + 0.45 - 1) = 0$; Upper: $\\min(0.30, 0.45) = 0.30$  \n   Intervallo plausibile: $[0, 0.30]$\n\n6. ```r\n   check_frechet <- function(P_A, P_B, P_AB) {\n     lower <- max(0, P_A + P_B - 1)\n     upper <- min(P_A, P_B)\n     \n     if (P_AB >= lower && P_AB <= upper) {\n       cat(\"✓ Coerente: P(A∩B) ∈ [\", lower, \",\", upper, \"]\\n\")\n       return(TRUE)\n     } else {\n       cat(\"✗ Incoerente: P(A∩B) =\", P_AB, \n           \"ma deve essere in [\", lower, \",\", upper, \"]\\n\")\n       return(FALSE)\n     }\n   }\n   ```\n\n### Soluzioni tabelle congiunte\n\n7. Tabella completata:\n   - $P(A \\cap B^c) = 0.40 - 0.25 = 0.15$\n   - $P(A^c \\cap B) = P(B) - 0.25$ (serve calcolare $P(B)$ da altre info)\n   - $P(A^c) = 1 - 0.40 = 0.60$\n   - $P(A^c \\cap B) = 0.60 - 0.45 = 0.15$\n   - $P(B) = 0.25 + 0.15 = 0.40$\n   - $P(B^c) = 0.15 + 0.45 = 0.60$\n\n   |       | $B$  | $B^c$ | Marg. |\n   |-------|------|-------|-------|\n   | $A$   | 0.25 | 0.15  | 0.40  |\n   | $A^c$ | 0.15 | 0.45  | 0.60  |\n   | Marg. | 0.40 | 0.60  | 1.00  |\n\n8. ```r\n   P_C <- 0.05\n   P_pos <- 0.08\n   sens <- 0.90\n   \n   # Congiunta\n   P_C_and_pos <- sens * P_C  # = 0.045\n   P_C_and_neg <- P_C - P_C_and_pos  # = 0.005\n   P_notC_and_pos <- P_pos - P_C_and_pos  # = 0.035\n   P_notC_and_neg <- 1 - (P_C_and_pos + P_C_and_neg + P_notC_and_pos)  # = 0.915\n   \n   # a) P(C | +) = 0.045 / 0.08 = 0.5625\n   # b) P(C | -) = 0.005 / 0.92 ≈ 0.0054\n   # c) Specificità = P(- | C^c) = 0.915 / 0.95 ≈ 0.963\n   ```\n\n### Soluzioni esercizi applicati\n\n10. ```r\n    P_D <- 0.55\n    P_P <- 0.30\n    P_P_given_D <- 0.45\n    \n    # a) Tabella\n    P_D_and_P <- P_P_given_D * P_D  # = 0.2475\n    P_D_and_notP <- P_D - P_D_and_P  # = 0.3025\n    P_notD_and_P <- P_P - P_D_and_P  # = 0.0525\n    P_notD_and_notP <- 1 - (P_D_and_P + P_D_and_notP + P_notD_and_P)  # = 0.3975\n    \n    # b) P(D | P) = 0.2475 / 0.30 = 0.825\n    \n    # c) Test indipendenza: P(D) × P(P) = 0.55 × 0.30 = 0.165\n    #    P(D ∩ P) = 0.2475 ≠ 0.165 → DIPENDENTI\n    \n    # d) P(D ∪ P) = 0.55 + 0.30 - 0.2475 = 0.6025\n    ```\n\n11. ```r\n    # Vedi soluzione 8, adattata con prevalenza 0.25\n    # a) Tabella costruita con sens=0.80, spec=0.85, prev=0.25\n    # b) P(A | +) = [0.80 × 0.25] / [0.80 × 0.25 + 0.15 × 0.75] ≈ 0.640\n    # c) P(A^c | -) = [0.85 × 0.75] / [0.20 × 0.25 + 0.85 × 0.75] ≈ 0.927\n    ```\n\n12. Somma = 1.05 > 1. Incoerente. Correzione (normalizzazione):\n    - $P(D) = 0.40 / 1.05 ≈ 0.381$\n    - $P(A) = 0.35 / 1.05 ≈ 0.333$\n    - $P(N) = 0.30 / 1.05 ≈ 0.286$\n\n### Soluzioni pensiero critico\n\n13. La tabella congiunta è più fondamentale perché rappresenta lo stato di credenza **completo** sul sistema. Da essa derivano automaticamente (e coerentemente) tutte le marginali e condizionate. Specificare marginali e condizionate separatamente rischia incoerenze (es. $P(A \\mid B) P(B) \\neq P(B \\mid A) P(A)$).\n\n14. Nel continuo si usano **densità di probabilità congiunta** $f(x, y)$. Il principio è identico: la densità congiunta determina tutto (marginali tramite integrazione, condizionate tramite rapporti di densità). La struttura di coerenza è preservata.\n\n15. Non è un problema—riflette informazioni diverse. Con molti dati, la verosimiglianza dominerà e i posterior convergeranno, riducendo l'influenza dei prior diversi. È una caratteristica, non un bug: la soggettività è nelle assunzioni iniziali esplicite.\n\n:::\n\n## Bibliografia {.unnumbered .unlisted}\n",
    "supporting": [
      "02_axioms_coherence_bayesian_files/figure-pdf"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{},\"value\":[]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}