{
  "hash": "3bbe280059e03656b88d794d125f80a9",
  "result": {
    "engine": "knitr",
    "markdown": "# Variabili casuali {#sec-prob-random-var}\n\n## Introduzione {.unnumbered .unlisted}\n\nImmaginiamo uno scenario ricorrente nella pratica clinica. Una psicologa vuole valutare l'efficacia di un intervento cognitivo-comportamentale per l'ansia sociale. A tal fine, somministra la *Liebowitz Social Anxiety Scale* (LSAS), un questionario i cui punteggi, compresi tra 0 e 144, riflettono la gravità dei sintomi, a 50 pazienti, rilevando le misure prima e dopo un ciclo di 12 sedute.\n\nTuttavia, la domanda clinica non si riduce a un problema dicotomico del tipo \"l'intervento funziona sì o no?\", quesito che gli strumenti probabilistici sin qui introdotti sarebbero già in grado di trattare in termini di test di ipotesi o di probabilità dell'evento. La questione è più complessa e sostanziale: qual è l'entità attesa del miglioramento? Quale distribuzione di probabilità caratterizza gli effetti possibili del trattamento? E, soprattutto, con quale misura di incertezza, in termini di varianza, intervalli di credibilità o densità predittive, dobbiamo accompagnare le nostre stime affinché queste siano interpretabili dal punto di vista clinico?\n\nPer rispondere a queste domande, è necessario compiere un salto concettuale decisivo: non più assegnare probabilità a eventi discreti, ma a quantità numeriche continue e misurabili. È proprio questo il ruolo delle **variabili casuali** che fungono da ponte tra la teoria della probabilità, intesa come sistema formale di credenze coerenti, e i modelli statistici su cui si fonda l'inferenza bayesiana.\n\nSenza questo strumento, domande clinicamente rilevanti resterebbero senza risposta: \"Qual è la probabilità che il miglioramento medio superi i 20 punti?\" o \"In quale intervallo possiamo attendere il punteggio post-trattamento con una probabilità del 95%?\" diventano interrogativi risolvibili solo grazie alla formalizzazione offerta dalle variabili casuali.\n\n::: {.callout-tip collapse=\"true\"}\n## Prerequisiti\n\nPer seguire questo capitolo è necessario aver letto:\n\n- @sec-prob-interpretation\n- @sec-prob-axioms-coherence\n- @sec-equiprobability-combinatorics\n- @sec-prob-conditional-prob \n- @sec-prob-bayes-theorem\n\nConoscenze matematiche richieste:\n\n- @sec-apx-calculus — **fondamentale** per comprendere le PDF e le variabili continue.\n- @sec-apx-sums - per marginalizzazione di variabili discrete.\n\nCompetenze pratiche:\n\n- Familiarità con R e operazioni vettoriali di base per eseguire le simulazioni.\n:::\n\n### Panoramica del capitolo {.unnumbered .unlisted}\n\n- Definizione formale di variabile casuale come funzione dallo spazio campionario ai numeri reali.\n- Distinzione tra variabili casuali discrete e continue.\n- Funzione di massa di probabilità (PMF) per variabili discrete.\n- Funzione di densità di probabilità (PDF) per variabili continue.\n- Funzione di distribuzione cumulativa (CDF) come rappresentazione unificata.\n- Variabili casuali multiple e nozione di indipendenza.\n\n\n::: {.callout-caution collapse=true title=\"Preparazione del Notebook\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhere::here(\"code\", \"_common.R\") |> \n  source()\n# Riapplica il tema per sicurezza\napply_visual_theme()\n```\n:::\n\n:::\n\n## Dalla probabilità degli eventi ai valori numerici\n\nNel framework bayesiano sviluppato nei capitoli precedenti, abbiamo assegnato delle probabilità a degli **eventi**, ovvero a dei sottoinsiemi dello spazio campionario che rappresentano delle proposizioni sul mondo. Quando un clinico afferma $P(\\text{Depressione maggiore}) = 0.3$, sta quantificando la propria credenza in una proposizione binaria: il paziente soddisfa o non soddisfa i criteri diagnostici.\n\nQuesta struttura è potente per molte domande cliniche, come la diagnosi differenziale, la valutazione del rischio e la previsione di esiti categoriali, ma risulta insufficiente quando l'oggetto dell'incertezza non è un evento sì/no, bensì un **valore numerico**. Consideriamo alcune domande tipiche della ricerca psicologica:\n\n- *Quale sarà il punteggio di questo paziente al BDI-II tra sei mesi?*\n- *Quanto tempo impiegherà un partecipante a rispondere in questo compito di decisione lessicale?*\n- *Quanti sintomi depressivi riporterà il paziente nella prossima settimana?*\n- *Quale livello di cortisolo mostrerà lo studente prima dell'esame?*\n\nIn tutti i casi, l'incertezza non riguarda il verificarsi di un evento, ma l'ampiezza, la durata o l'intensità di un fenomeno. Per modellare questo tipo di incertezza, dobbiamo passare dagli eventi alle **variabili casuali**.\n\n### L'idea fondamentale\n\nIl passaggio concettuale consiste nel riconoscere che molti esperimenti producono naturalmente risultati numerici. Un test psicometrico restituisce un punteggio, una misurazione fisiologica produce un valore continuo e un compito cognitivo genera un tempo di reazione. Anche quando gli esiti originari non sono numerici, è sempre possibile **codificarli** come tali, assegnando 1 al successo e 0 al fallimento in un singolo item o utilizzando codifiche ordinali per le categorie diagnostiche.\n\nLa traduzione sistematica degli esiti in numeri è realizzata tramite una **variabile casuale**. La \"casualità\" non risiede nella funzione in sé, che è perfettamente deterministica, ma nell'incertezza relativa all'esito che si verificherà nello spazio campionario. Una volta che l'esito è stato determinato, il valore numerico associato viene automaticamente calcolato.\n\n## Definizione formale di variabile casuale\n\n::: {#def-random-variable}\n### Variabile casuale\n\nSia $\\Omega$ uno spazio campionario. Una *variabile casuale* è una funzione\n\n$$\nX : \\Omega \\longrightarrow \\mathbb{R}\n$$\nche associa a ogni esito $\\omega \\in \\Omega$ un unico numero reale $X(\\omega)$.\n:::\n\nQuesta definizione va interpretata con attenzione. Lo spazio campionario $\\Omega$ rappresenta, nella nostra prospettiva epistemica, l'insieme di tutte le **possibilità** compatibili con le informazioni a nostra disposizione. La variabile casuale $X$ traduce ciascuna di queste possibilità in un numero, rendendo possibile l'applicazione dell'analisi matematica allo studio dell'incertezza.\n\nIl termine \"casuale\" è quindi in parte fuorviante: la funzione $X$ non è affatto aleatoria, ma completamente deterministica. L'incertezza deriva esclusivamente dal fatto che non sappiamo quale elemento di $\\Omega$ si realizzerà.\n\nPer convenzione, le variabili casuali come funzioni sono indicate con lettere maiuscole ($X$, $Y$, $Z$), mentre i valori numerici che possono assumere sono indicati con lettere minuscole ($x$, $y$, $z$). Questa distinzione permette di scrivere espressioni come $P(X = x)$ o $P(X \\leq x)$, separando chiaramente l'oggetto aleatorio dai suoi possibili valori.\n\n::: {.callout-note collapse=\"true\" title=\"Esempio: punteggio in un test a scelta multipla\"}\n\n#### Il punteggio come variabile casuale {.unnumbered .unlisted}\n\nConsideriamo un breve test di memoria di lavoro composto da 5 item. Ogni item può essere risolto correttamente (C) o erroneamente (E). Lo spazio campionario è costituito da tutte le possibili sequenze di risposte:\n\n$$\n\\Omega = \\{CCCCC, CCCCE, CCCEC, \\ldots, EEEEE\\}.\n$$\n\nPoiché ogni item ha due esiti possibili e gli item sono 5, lo spazio campionario contiene $2^5 = 32$ elementi.\n\nDefiniamo la variabile casuale $X$ che associa a ogni sequenza di risposte il numero totale di risposte corrette:\n\n$$\nX(\\omega) = \\text{numero di C in } \\omega.\n$$\n\nPer l'esito $\\omega = CCECE$, ad esempio, il valore della variabile casuale è $X(CCECE) = 3$. La funzione $X$ è perfettamente deterministica: data la sequenza di risposte, il punteggio è univocamente determinato. L'incertezza riguarda solo *quale* sequenza di risposte verrà osservata.\n\nL'evento $\\{X = 3\\}$ rappresenta l'insieme di tutti gli esiti che producono esattamente 3 risposte corrette:\n\n$$\n\\{X = 3\\} = \\{CCCEE, CCECE, CCEEC, CECCE, \\ldots\\}.\n$$\n\nQuesto insieme contiene $\\binom{5}{3} = 10$ elementi. Se assumiamo che ciascuna risposta sia corretta con probabilità $p = 0.6$ indipendentemente dalle altre, la probabilità di ottenere esattamente 3 risposte corrette è:\n\n$$\nP(X = 3) = \\binom{5}{3} (0.6)^3 (0.4)^2 = 10 \\times 0.216 \\times 0.16 = 0.3456.\n$$\n\n:::\n\n### Perché questo passaggio è cruciale per l'inferenza bayesiana\n\nL'introduzione delle variabili casuali non è un mero tecnicismo, ma un  **prerequisito concettuale** per tutto ciò che seguirà. Nell'inferenza bayesiana, i parametri dei modelli, come la probabilità di successo $\\theta$ in un modello binomiale, o la media $\\mu$ di una distribuzione normale, sono trattati essi stessi come variabili casuali. La distribuzione a priori $p(\\theta)$ esprime l'incertezza iniziale sul valore del parametro, mentre la distribuzione a posteriori $p(\\theta \\mid \\text{dati})$ esprime l'incertezza aggiornata dopo l'osservazione dei dati.\n\nSenza il concetto di variabile casuale, non sarebbe nemmeno possibile formulare domande del tipo: \"Qual è la probabilità che l'efficacia del trattamento superi a una certa soglia clinicamente rilevante?\" — domande che sono, al contrario, fondamentali per la pratica bayesiana.\n\n## Variabili casuali discrete\n\nLa distinzione più fondamentale tra le variabili casuali riguarda la natura dell'insieme dei valori che possono assumere. Una variabile casuale è detta **discreta** quando l'insieme dei suoi valori possibili è finito o numerabile, ovvero quando tali valori possono essere elencati in una sequenza (eventualmente infinita).\n\n::: {#def-discrete-rv}\n\n### Variabile casuale discreta\n\nUna variabile casuale $X$ è *discreta* se esiste un insieme finito o numerabile\n\n$$\n\\mathcal{X} = \\{x_1, x_2, \\ldots\\}\n$$\ntale che\n\n$$\nP(X \\in \\mathcal{X}) = 1.\n$$\n\nIn altre parole, $X$ assume con certezza uno dei valori appartenenti all'insieme $\\mathcal{X}$.\n:::\n\n### Esempi in psicologia\n\nLe variabili casuali discrete compaiono in numerosi contesti della ricerca e della pratica psicologica:\n\n- **Punteggi grezzi nei test**: il numero di risposte corrette in un test cognitivo (valori da 0 a $n$, dove $n$ è il numero di item).\n- **Scale Likert**: i punteggi su singoli item o su scale composite con valori discreti (ad esempio, da 1 a 5 o da 1 a 7).\n- **Conteggi di comportamenti**: il numero di episodi di abbuffata in una settimana, il numero di risvegli notturni, il numero di interazioni sociali.\n- **Categorie diagnostiche codificate**: quando si assegnano codici numerici a categorie (0 = assente, 1 = lieve, 2 = moderato, 3 = grave).\n- **Numero di criteri soddisfatti**: in una valutazione diagnostica, quanti criteri del DSM-5 sono soddisfatti per una certa condizione.\n\nLa caratteristica distintiva delle variabili discrete è che tra due valori consecutivi **non esistono valori intermedi**: non è possibile osservare, per esempio, 2.7 risposte corrette su 5, né un punteggio Likert di 3.5 su una scala da 1 a 5.\n\n## Funzione di massa di probabilità\n\nPer descrivere completamente una variabile casuale discreta è sufficiente specificare la probabilità associata a ciascun valore possibile. Questa specificazione prende il nome di **funzione di massa di probabilità**.\n\n::: {#def-pmf}\n\n### Funzione di massa di probabilità (PMF)\n\nLa *funzione di massa di probabilità* di una variabile casuale discreta $X$ è la funzione\n\n$$\np_X : \\mathcal{X} \\to [0,1]\n$$\ndefinita da\n\n$$\np_X(x) = P(X = x)\n$$\nper ogni $x \\in \\mathcal{X}$.\n:::\n\nLa PMF deve soddisfare due condizioni fondamentali, che discendono direttamente dagli assiomi di coerenza della probabilità:\n\n1. **Non-negatività**\n   $$\n   p_X(x) \\geq 0 \\quad \\text{per ogni } x \\in \\mathcal{X}.\n   $$\n\n2. **Normalizzazione**\n   $$\n   \\sum_{x \\in \\mathcal{X}} p_X(x) = 1.\n   $$\n\nUna volta nota la funzione di massa di probabilità, è possibile calcolare la probabilità di qualunque evento relativo alla variabile $X$. Per un sottoinsieme $B \\subseteq \\mathcal{X}$ vale infatti:\n$$\nP(X \\in B) = \\sum_{x \\in B} p_X(x).\n$$\n\n### Ponte applicativo: la PMF nella pratica clinica\n\nQuando uno psicologo riporta che, su una scala di esito del trattamento, \"il 15% dei pazienti mostra remissione completa (4), il 35% miglioramento sostanziale (3), il 30% miglioramento parziale (2), il 15% nessun cambiamento (1) e il 5% peggioramento (0)\", sta implicitamente descrivendo una PMF:\n\n| $x$ (esito)        | 0    | 1    | 2    | 3    | 4    |\n|--------------------|------|------|------|------|------|\n| $p_X(x)$           | 0.05 | 0.15 | 0.30 | 0.35 | 0.15 |\n\nQuesta tabella soddisfa entrambe le proprietà richieste: tutti i valori sono non-negativi e la loro somma è 1. Da questa PMF possiamo calcolare, ad esempio, la probabilità di un esito positivo (miglioramento parziale o superiore):\n\n$$\nP(X \\geq 2) = p_X(2) + p_X(3) + p_X(4) = 0.30 + 0.35 + 0.15 = 0.80.\n$$\n\n::: {.callout-note collapse=\"true\" title=\"Esempio: PMF del punteggio in un test a 5 item\"}\n\n#### Derivazione completa della distribuzione {.unnumbered .unlisted}\n\nRiprendiamo il test di memoria di lavoro a 5 item. Supponiamo che ogni risposta sia corretta con probabilità $p = 0.7$, indipendentemente dalle altre. La variabile casuale $X$ (numero di risposte corrette) può assumere valori compresi tra 0 e 5.\n\nPer ogni valore $x$, il numero di sequenze con esattamente $x$ risposte corrette è $\\binom{5}{x}$, e ciascuna di queste sequenze ha probabilità $(0.7)^x (0.3)^{5-x}$. Pertanto:\n\n$$\np_X(x) = \\binom{5}{x} (0.7)^x (0.3)^{5-x}.\n$$\n\nLa distribuzione completa risulta:\n\n| $x$      | 0      | 1      | 2      | 3      | 4      | 5      |\n|----------|--------|--------|--------|--------|--------|--------|\n| $p_X(x)$ | 0.0024 | 0.0284 | 0.1323 | 0.3087 | 0.3601 | 0.1681 |\n\nSi osservi che la distribuzione è asimmetrica, con la moda (valore più probabile) a $x = 4$. La probabilità di ottenere almeno 3 risposte corrette è:\n\n$$\nP(X \\geq 3) = 0.3087 + 0.3601 + 0.1681 = 0.8369.\n$$\n\nQuesta è esattamente la struttura della **distribuzione binomiale**, che studieremo in dettaglio nel capitolo sulle famiglie di distribuzioni.\n:::\n\n### Connessione con il percorso bayesiano\n\nLa PMF che abbiamo appena costruito, ovvero quella relativa al numero di successi in $n$ prove con probabilità $p$, è una delle **funzione di verosimiglianza** più importanti nei modelli bayesiani. Quando osserviamo $k$ successi su $n$ prove e vogliamo stimare la probabilità di successo $\\theta$, la verosimiglianza è proprio:\n\n$$\nL(\\theta | k) = \\binom{n}{k} \\theta^k (1-\\theta)^{n-k}.\n$$\n\nComprendere la PMF significa quindi comprendere una delle due componenti essenziali dell'inferenza bayesiana (l'altra è la distribuzione a priori).\n\n::: {.callout-note collapse=\"true\" title=\"Esempio: PMF della somma di due dadi\"}\n\n#### Un esempio classico per consolidare l'intuizione {.unnumbered .unlisted}\n\nConsideriamo il lancio di due dadi equilibrati, un esempio classico che, pur essendo distante dalla pratica psicologica, illustra con particolare chiarezza la struttura combinatoria alla base della PMF.\n\nLo spazio campionario è costituito dalle 36 coppie ordinate:\n\n$$\n\\Omega = \\{(1,1), (1,2), \\ldots, (6,5), (6,6)\\}.\n$$\n\nDefiniamo la variabile casuale $X$ che associa a ogni coppia $(i,j)$ la somma dei valori:\n\n$$\nX(i,j) = i + j.\n$$\n\nLa somma può assumere valori da 2 a 12. Per ciascun valore, contiamo quante coppie lo producono:\n\n|    $x$   |        2        |        3        |        4        |        5        |        6        |        7        |        8        |        9        |        10       |        11       |        12       |\n| :------: | :-------------: | :-------------: | :-------------: | :-------------: | :-------------: | :-------------: | :-------------: | :-------------: | :-------------: | :-------------: | :-------------: |\n|   Casi   |        1        |        2        |        3        |        4        |        5        |        6        |        5        |        4        |        3        |        2        |        1        |\n| $p_X(x)$ | $\\tfrac{1}{36}$ | $\\tfrac{2}{36}$ | $\\tfrac{3}{36}$ | $\\tfrac{4}{36}$ | $\\tfrac{5}{36}$ | $\\tfrac{6}{36}$ | $\\tfrac{5}{36}$ | $\\tfrac{4}{36}$ | $\\tfrac{3}{36}$ | $\\tfrac{2}{36}$ | $\\tfrac{1}{36}$ |\n\nLa simmetria della distribuzione attorno al valore 7 riflette la struttura combinatoria del problema. Questa forma \"triangolare\" è un primo esempio di come la struttura del processo generativo (in questo caso, la somma di due quantità uniformi) determini la forma della distribuzione.\n\nUn'analogia psicometrica: se un punteggio composito è la somma di due subscale ciascuna uniformemente distribuita su 1-6, allora la distribuzione del punteggio totale avrà esattamente questa forma triangolare.\n:::\n\n## Verifica computazionale della PMF\n\nLe simulazioni al computer costituiscono uno strumento efficace per **verificare empiricamente** le proprietà teoriche di una funzione di massa di probabilità. Generando un gran numero di realizzazioni della variabile casuale, è possibile osservare come le frequenze relative tendano a convergere verso le probabilità teoriche.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(42)\n\n# Simulazione del test a 5 item con p = 0.7\nn_sim <- 100000\nn_item <- 5\np_corretto <- 0.7\n\n# Generiamo le risposte per tutti i partecipanti simulati\npunteggi <- rbinom(n_sim, size = n_item, prob = p_corretto)\n\n# Frequenze empiriche\nfreq_emp <- table(factor(punteggi, levels = 0:5)) / n_sim\n\n# Probabilità teoriche (distribuzione binomiale)\nvalori <- 0:5\nprob_teor <- dbinom(valori, size = n_item, prob = p_corretto)\n\n# Confronto\ndf_confronto <- data.frame(\n  x = valori,\n  empirica = as.numeric(freq_emp),\n  teorica = prob_teor\n)\n\nggplot(df_confronto, aes(x = x)) +\n  geom_col(aes(y = empirica), alpha = 0.7, width = 0.6) +\n  geom_point(aes(y = teorica), size = 3) +\n  geom_line(aes(y = teorica), linewidth = 1) +\n  scale_x_continuous(breaks = 0:5) +\n  labs(\n    x = \"Numero di risposte corrette\", \n    y = \"Probabilità\",\n    title = \"PMF del punteggio in un test a 5 item (p = 0.7)\"\n  )\n```\n\n::: {.cell-output-display}\n![](06_random_var_files/figure-html/unnamed-chunk-2-1.png){fig-align='center' width=85%}\n:::\n:::\n\n\nLa convergenza delle frequenze empiriche verso le probabilità teoriche **non definisce** la distribuzione di probabilità, ma ne verifica la coerenza interna. La simulazione mostra che un sistema di credenze coerente genera il comportamento atteso quando viene sottoposto a ripetute osservazioni.\n\n## Variabili casuali continue\n\nMolte grandezze psicologiche non possono essere rappresentate adeguatamente da variabili discrete. Il tempo di reazione in un compito cognitivo, il livello di cortisolo in una misurazione fisiologica, la latenza di una risposta comportamentale, o anche i punteggi su scale psicometriche quando vengono trattati come misure continue di un costrutto latente — tutte queste quantità possono assumere, almeno in linea di principio, **qualsiasi valore** all'interno di un intervallo continuo.\n\n::: {#def-continuous-rv}\n\n### Variabile casuale continua\n\nUna variabile casuale $X$ è *continua* se esiste una funzione non negativa\n\n$$\nf_X : \\mathbb{R} \\to [0, +\\infty),\n$$\ndetta *funzione di densità di probabilità* (PDF), tale che per ogni intervallo $[a,b]$ valga:\n\n$$\nP(a \\leq X \\leq b) = \\int_a^b f_X(x)\\,dx.\n$$\n:::\n\nQuesta definizione esprime un cambiamento concettuale importante rispetto al caso discreto: la probabilità non è più assegnata a singoli valori, ma a **intervalli** della retta reale.\n\n### Esempi in psicologia\n\nLe variabili casuali continue sono ampiamente utilizzate nella ricerca psicologica:\n\n- **Tempi di reazione**: la latenza di risposta in compiti cognitivi, tipicamente misurata in millisecondi.\n- **Misure fisiologiche**: livelli di cortisolo, frequenza cardiaca, conduttanza cutanea.\n- **Punteggi standardizzati**: quando i punteggi grezzi vengono trasformati in scale continue (z-score, T-score, percentili).\n- **Variabili latenti**: i costrutti psicologici non osservabili direttamente (come l'intelligenza, l'ansia di tratto e l'apertura mentale) sono solitamente modellati come variabili continue.\n- **Effetti stimati**: le dimensioni dell'effetto, i coefficienti di regressione, le differenze tra le medie.\n\n## Funzione di densità di probabilità\n\nLa funzione di densità di probabilità svolge per le variabili continue un ruolo analogo a quello della PMF per le variabili discrete, ma con una differenza cruciale. Il valore $f_X(x)$ **non rappresenta** la probabilità che la variabile assuma esattamente il valore $x$.\n\nInfatti, per una variabile casuale continua vale sempre:\n\n$$\nP(X = x_0) = \\int_{x_0}^{x_0} f_X(x)\\,dx = 0.\n$$\n\nQuesto risultato, che può apparire controintuitivo, riflette la struttura del continuo: esistono infiniti valori possibili, e non è possibile assegnare a ciascun punto una probabilità positiva mantenendo la normalizzazione. La probabilità non è concentrata nei punti, ma **distribuita sugli intervalli**.\n\n### Come interpretare la densità\n\nLa densità $f_X(x)$  può essere interpretata come una misura della **concentrazione della probabilità**. Valori elevati di $f_X(x)$ indicano le regioni della retta reale in cui la variabile è più probabile che assuma un determinato valore, nel senso che gli intervalli di piccole dimensioni attorno a quei punti hanno una probabilità relativamente maggiore.\n\nUn'analogia utile: se la probabilità fosse acqua e la retta reale fosse un contenitore, la densità $f_X(x)$ indicherebbe l'altezza dell'acqua nel punto $x$. La quantità totale di acqua (ovvero la probabilità totale) è sempre pari a 1, ma può essere distribuita in modo più o meno concentrato in diverse regioni.\n\n::: {#thm-pdf-properties}\n\n### Proprietà delle funzioni di densità di probabilità\n\nUna funzione $f_X(x)$ è una valida funzione di densità di probabilità se e solo se soddisfa le seguenti condizioni:\n\n1. **Non-negatività**\n   $$\n   f_X(x) \\geq 0 \\quad \\text{per ogni } x \\in \\mathbb{R}.\n   $$\n\n2. **Normalizzazione**\n   $$\n   \\int_{-\\infty}^{+\\infty} f_X(x)\\,dx = 1.\n   $$\n:::\n\nÈ importante notare che il valore della densità $f_X(x)$ può superare 1: ciò non viola alcun principio, in quanto $f_X(x)$ non rappresenta una probabilità. Solo l'**integrale** della densità su un intervallo restituisce una probabilità. In termini geometrici, la probabilità $P(a \\leq X \\leq b)$ corrisponde all'**area all'area sottesa dalla curva** di $f_X(x)$ tra $a$ e $b$.\n\n### Ponte applicativo: la PDF nella valutazione clinica\n\nQuando un clinico afferma che \"i punteggi del BDI-II nella popolazione generale seguono approssimativamente una distribuzione normale con media 10 e deviazione standard 8\", sta implicitamente specificando una PDF. Da questa distribuzione è possibile calcolare, ad esempio:\n\n- La probabilità che un individuo estratto casualmente abbia un punteggio superiore a 20 (soglia per depressione lieve).\n- L'intervallo entro cui cade il 95% centrale della popolazione.\n- La probabilità di osservare un punteggio estremo come quello di un particolare paziente.\n\nQuesti calcoli sono fondamentali per interpretare i punteggi individuali nel contesto della variabilità normale.\n\n::: {.callout-note collapse=\"true\" title=\"Esempio: tempo di reazione in un compito cognitivo\"}\n\n#### Probabilità come area sotto la curva {.unnumbered .unlisted}\n\nConsideriamo una variabile casuale continua $T$ che rappresenta il tempo di reazione (in millisecondi) in un compito di decisione lessicale. I tempi di reazione sono solitamente modellati con distribuzioni asimmetriche positive; una scelta comune è la distribuzione **log-normale**.\n\nSupponiamo che la variabile $T$ segua una distribuzione log-normale con parametri $\\mu = 5.7$ e $\\sigma = 0.3$. Ciò significa che il logaritmo naturale del tempo di reazione segue una distribuzione normale: $\\ln(T) \\sim N(5.7, 0.3^2)$.\n\nLa funzione di densità di probabilità è:\n\n$$\nf_T(t) = \\frac{1}{t \\sigma \\sqrt{2\\pi}} \\exp\\left(-\\frac{(\\ln(t) - \\mu)^2}{2\\sigma^2}\\right) \\quad \\text{per } t > 0\n$$\ne $f_T(t) = 0$ per $t \\leq 0$.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Parametri della distribuzione log-normale\nmu <- 5.7   # media del log(T)\nsigma <- 0.3 # deviazione standard del log(T)\n\n# Statistiche descrittive della distribuzione\nmediana_T <- exp(mu)\nmedia_T <- exp(mu + sigma^2 / 2)\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```\n#> Mediana del tempo di reazione: 299 ms\n#> Media del tempo di reazione: 313 ms\n```\n:::\n\n\nLa mediana (298 ms) è inferiore alla media (312 ms) perché la distribuzione è asimmetrica a destra, una caratteristica tipica dei tempi di reazione.\n\nLa probabilità che il tempo di reazione cada in un certo intervallo si ottiene integrando la densità:\n\n$$\nP(300 \\leq T \\leq 400) = \\int_{300}^{400} f_T(t) \\, dt\n$$\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Calcolo tramite la CDF\nprob_300_400 <- plnorm(400, meanlog = mu, sdlog = sigma) - \n                plnorm(300, meanlog = mu, sdlog = sigma)\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```\n#> P(300 ≤ T ≤ 400): 0.329\n```\n:::\n\n\nQuesta probabilità (circa 47%) rappresenta l'area sotto la curva di densità compresa tra 300 e 400 ms.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Visualizzazione\nt_vals <- seq(150, 600, length.out = 500)\ndf_rt <- data.frame(\n  t = t_vals,\n  densita = dlnorm(t_vals, meanlog = mu, sdlog = sigma)\n)\n\n# Area da evidenziare\ndf_area <- df_rt[df_rt$t >= 300 & df_rt$t <= 400, ]\n\nggplot(df_rt, aes(x = t, y = densita)) +\n  geom_area(data = df_area, aes(x = t, y = densita), \n            alpha = 0.4) +\n  geom_line(linewidth = 1) +\n  geom_vline(xintercept = c(300, 400), linetype = \"dashed\", alpha = 0.5) +\n  labs(\n    x = \"Tempo di reazione (ms)\",\n    y = \"Densità di probabilità\",\n    title = \"Distribuzione dei tempi di reazione\"\n  ) +\n  annotate(\"text\", x = 350, y = 0.002, \n           label = paste0(\"P = \", round(prob_300_400, 3)))\n```\n\n::: {.cell-output-display}\n![](06_random_var_files/figure-html/unnamed-chunk-7-1.png){fig-align='center' width=85%}\n:::\n:::\n\n\nL'area ombreggiata rappresenta la probabilità che il tempo di reazione cada tra 300 e 400 ms. \n\nNelle funzioni di densità di probabilità, il valore della funzione può talvolta superare 1. Ciò non rappresenta un problema o un errore, poiché la densità stessa non è una probabilità, ma una misura di concentrazione.\n\n:::\n\n### Connessione con il percorso bayesiano\n\nLa distinzione tra PMF e PDF diventa centrale quando specifichiamo le distribuzioni nel modello bayesiano. Per un parametro come una **proporzione** (che può assumere qualsiasi valore compreso tra 0 e 1), useremo una densità continua — tipicamente la distribuzione Beta. Per il **numero di successi** osservati (assumere solo i valori 0, 1, 2, ..., $n$), useremo invece una distribuzione discreta, ovvero la distribuzione binomiale.\n\nLa distribuzione a priori $p(\\theta)$ su un parametro continuo è sempre una PDF; la verosimiglianza $p(\\text{dati} \\mid \\theta)$ per dati discreti è una PMF rispetto ai dati possibili, ma una funzione continua di $\\theta$.\n\n## Funzione di distribuzione cumulativa\n\nEsiste una descrizione della distribuzione di probabilità che vale **sia per le variabili discrete che per quelle continue** e che specifica direttamente la probabilità che la variabile assuma valori inferiori o uguali a una determinata soglia. Questa descrizione è fornita dalla **funzione di distribuzione cumulativa**.\n\n::: {#def-cdf}\n\n### Funzione di distribuzione cumulativa (CDF)\n\nLa *funzione di distribuzione cumulativa* di una variabile casuale $X$ è la funzione\n\n$$\nF_X : \\mathbb{R} \\to [0,1]\n$$\ndefinita da\n\n$$\nF_X(x) = P(X \\leq x).\n$$\n:::\n\nDal punto di vista epistemico, $F_X(x)$ rappresenta il grado di credenza che il valore della variabile casuale $X$ non superi la soglia $x$. Questa interpretazione rende la CDF particolarmente utile per rispondere a domande come: \"Qual è la probabilità che il punteggio sia inferiore a questa soglia clinica?\".\n\n### Relazione con PMF e PDF\n\nLa funzione di distribuzione cumulativa **caratterizza completamente** la distribuzione di probabilità. Da essa è possibile ricavare:\n\n- la *funzione di massa di probabilità* nel caso discreto;\n- la *funzione di densità di probabilità* nel caso continuo.\n\nPer le variabili casuali continue vale la relazione fondamentale:\n$$\nF_X(x) = \\int_{-\\infty}^{x} f_X(t)\\,dt,\n\\qquad\nf_X(x) = \\frac{d}{dx} F_X(x),\n$$\novvero la CDF è l'integrale cumulativo della densità e, viceversa, la densità è la derivata della CDF.\n\nNel caso discreto, la CDF cresce per *salti*, ciascuno dei quali ha un'ampiezza pari alla probabilità del valore corrispondente:\n$$\nF_X(x) = \\sum_{x_i \\leq x} p_X(x_i).\n$$\n\n::: {#thm-cdf-properties}\n\n### Proprietà della funzione di distribuzione cumulativa\n\nOgni funzione di distribuzione cumulativa soddisfa le seguenti proprietà:\n\n1. **Monotonia non decrescente**: per ogni $a < b$,\n   $$\n   F_X(a) \\leq F_X(b).\n   $$\n\n2. **Comportamento asintotico**:\n   $$\n   \\lim_{x \\to -\\infty} F_X(x) = 0,\n   \\qquad\n   \\lim_{x \\to +\\infty} F_X(x) = 1.\n   $$\n\n3. **Continuità da destra**: per ogni $x \\in \\mathbb{R}$,\n   $$\n   \\lim_{h \\to 0^+} F_X(x + h) = F_X(x).\n   $$\n:::\n\n### Ponte applicativo: uso della CDF per i cut-off clinici\n\nLa CDF è lo strumento naturale per calcolare la proporzione di individui che cadono sotto (o sopra) una certa soglia. Se il punteggio $X$ al PHQ-9 nella popolazione clinica segue una certa distribuzione, allora:\n\n- $F_X(9)$ = probabilità che un paziente abbia un punteggio ≤ 9 (depressione minima)\n- $1 - F_X(19)$ = probabilità di depressione grave (punteggio > 19)\n- $F_X(14) - F_X(9)$ = probabilità di depressione moderata (10-14)\n\nQueste probabilità sono fondamentali per interpretare le proprietà delle scale di screening.\n\n::: {.callout-note collapse=\"true\" title=\"Esempio: CDF del punteggio nel test a 5 item\"}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# CDF per il test a 5 item con p = 0.7\nvalori <- 0:5\nprob <- dbinom(valori, size = 5, prob = 0.7)\ncdf <- pbinom(valori, size = 5, prob = 0.7)\n\n# Dati per il grafico a gradini\ndf_cdf <- data.frame(\n  x_start = c(-0.5, valori),\n  x_end = c(valori, 5.5),\n  y = c(0, cdf)\n)\n\nggplot() +\n  geom_segment(\n    data = df_cdf,\n    aes(x = x_start, xend = x_end, y = y, yend = y),\n    linewidth = 1\n  ) +\n  geom_point(\n    data = data.frame(x = valori, y = cdf),\n    aes(x = x, y = y),\n    size = 3\n  ) +\n  scale_x_continuous(breaks = 0:5, limits = c(-0.5, 5.5)) +\n  scale_y_continuous(breaks = seq(0, 1, 0.2)) +\n  labs(\n    x = \"x (numero di risposte corrette)\",\n    y = expression(F[X](x) == P(X <= x)),\n    title = \"CDF del punteggio nel test a 5 item\"\n  )\n```\n\n::: {.cell-output-display}\n![](06_random_var_files/figure-html/unnamed-chunk-8-1.png){fig-align='center' width=85%}\n:::\n:::\n\n\nNel grafico, ogni **salto** della funzione corrisponde a un possibile valore del punteggio. L'altezza del salto in $x$ è pari alla probabilità $P(X = x)$. Ad esempio, il salto da $F_X(3)$ a $F_X(4)$ ha ampiezza 0.36, che corrisponde  esattamente a $p_X(4)$.\n\nDa questo grafico si può leggere direttamente che:\n\n- $P(X \\leq 2) = F_X(2) \\approx 0.16$;\n- $P(X \\leq 3) = F_X(3) \\approx 0.47$;\n- $P(X \\geq 4) = 1 - F_X(3) \\approx 0.53$.\n\n:::\n\n### Connessione con il percorso bayesiano\n\nLa CDF è lo strumento fondamentale per calcolare gli **intervalli di credibilità** nell'inferenza bayesiana. Se il parametro $\\theta$ ha una distribuzione a posteriori $p(\\theta \\mid \\text{dati})$ e una CDF $F_\\theta(t)$, allora:\n\n- il **quantile** $q_\\alpha$ tale che $F_\\theta(q_\\alpha) = \\alpha$ indica il valore sotto il quale cade una proporzione $\\alpha$ della massa a posteriori;\n- l'**intervallo di credibilità al 95%** è tipicamente $[q_{0.025}, q_{0.975}]$;\n- la **probabilità a posteriori** che il valore di $\\theta$ superi una soglia $\\theta_0$ è data da $1 - F_\\theta(\\theta_0)$.\n\nQueste operazioni sono al centro dell'inferenza bayesiana e richiedono una buona padronanza della CDF.\n\n## Variabili casuali multiple\n\nIn molti contesti sperimentali e clinici è necessario modellare **più fenomeni aleatori simultaneamente**. In uno studio sulla comorbilità tra ansia e depressione, ad esempio, è necessario rappresentare congiuntamente i punteggi su entrambe le scale. Nello studio della memoria, ad esempio, potremmo voler modellare insieme accuratezza e tempo di risposta. Nell'analisi delle misure ripetute, l'incertezza riguarda i valori osservati in momenti diversi.\n\nIl framework probabilistico si estende naturalmente a questi contesti **multivariati**: invece di descrivere l'incertezza relativa a una singola variabile casuale, si descrive l'incertezza relativa alla **combinazione dei valori** assunti da più variabili.\n\n### Distribuzione congiunta\n\n::: {#def-joint-distribution}\n\n### Distribuzione congiunta\n\nSiano $X$ e $Y$ due variabili casuali discrete. La *funzione di massa di probabilità congiunta* è definita come\n$$\np_{X,Y}(x,y) = P(X = x, Y = y).\n$$\n\nEssa assegna una probabilità a ciascuna possibile coppia di valori $(x,y)$ assunta congiuntamente dalle due variabili.\n:::\n\nLa distribuzione congiunta fornisce la **descrizione più completa** dello stato di credenza riguardo alle variabili considerate: tutte le altre quantità probabilistiche possono essere derivate da essa.\n\n### Esempio: ansia e depressione\n\nSupponiamo di classificare i pazienti in base a tre livelli di ansia (bassa, media, alta) e tre livelli di depressione (bassa, media, alta). La distribuzione congiunta potrebbe essere la seguente:\n\n|                | Depr. bassa | Depr. media | Depr. alta |\n|----------------|-------------|-------------|------------|\n| **Ansia bassa**  | 0.25        | 0.10        | 0.05       |\n| **Ansia media**  | 0.08        | 0.15        | 0.07       |\n| **Ansia alta**   | 0.02        | 0.08        | 0.20       |\n\nLa somma di tutte le celle è 1. La probabilità di osservare un paziente con ansia alta e depressione alte è $p_{X,Y}(\\text{alta}, \\text{alta}) = 0.20$.\n\n### Distribuzioni marginali\n\nLe *distribuzioni marginali* si ottengono eliminando una variabile dalla distribuzione congiunta e sommando i valori della variabile da eliminare.\n\n$$\np_X(x) = \\sum_y p_{X,Y}(x,y),\n\\qquad\np_Y(y) = \\sum_x p_{X,Y}(x,y).\n$$\n\nNell'esempio precedente:\n\n- $p_X(\\text{ansia alta}) = 0.02 + 0.08 + 0.20 = 0.30$;\n- $p_Y(\\text{depr. alta}) = 0.05 + 0.07 + 0.20 = 0.32$.\n\nDal punto di vista epistemico, la marginalizzazione corrisponde all'ignorare una delle variabili, concentrandosi esclusivamente sull'incertezza relativa all'altra.\n\n### Indipendenza stocastica\n\nLe variabili casuali $X$ e $Y$ si dicono **stocasticamente indipendenti** se e solo se la loro distribuzione congiunta si scompone nel prodotto delle distribuzioni marginali:\n\n$$\np_{X,Y}(x,y) = p_X(x) \\cdot p_Y(y)\n\\quad \\text{per ogni } (x,y).\n$$\n\nQuesta condizione esprime l'assenza di qualsiasi relazione informativa: conoscere il valore assunto da una variabile **non modifica** la distribuzione dell'altra.\n\nNella tabella di esempio, ansia e depressione **non** sono indipendenti. Se lo fossero, dovremmo avere:\n\n$$\np_{X,Y}(\\text{alta}, \\text{alta}) = p_X(\\text{alta}) \\cdot p_Y(\\text{alta}) = 0.30 \\times 0.32 = 0.096.\n$$\n\nMa il valore osservato è 0.20, molto superiore: le due condizioni tendono a co-occorrere più di quanto ci si aspetterebbe in caso di indipendenza. Questa è la struttura della **comorbidità**.\n\n### Ponte applicativo: perché le variabili multiple sono cruciali\n\nNella pratica clinica, raramente ci interessa una singola variabile presa in isolamento. Le relazioni tra ansia e depressione, tra sintomi e funzionamento, tra processi cognitivi e comportamento manifesto richiedono tutte di modellare distribuzioni congiunte.\n\nNell'inferenza bayesiana, le variabili multiple sono costantemente presenti. Quando abbiamo più parametri nel modello, come la media e la varianza o gli effetti fissi e casuali, la distribuzione a posteriori è una distribuzione congiunta su tutti i parametri. Comprendere come le distribuzioni congiunte si scompongono in marginali e come l'indipendenza semplifica i calcoli è essenziale per poter utilizzare questi modelli.\n\n### Connessione con il percorso bayesiano\n\nLa struttura delle variabili casuali multiple è il fondamento per comprendere concetti avanzati che incontreremo:\n\n- **Gerarchie di parametri**: nei modelli multilivello, i parametri di livello inferiore (ad esempio, gli effetti individuali) hanno una distribuzione condizionata ai parametri di livello superiore (ad esempio, i parametri di gruppo).\n- **Modelli grafici**: le reti bayesiane rappresentano le relazioni di dipendenza condizionata tra variabili attraverso grafi.\n- **Marginalizzazione**: il calcolo della distribuzione a posteriori marginale di un singolo parametro richiede l'integrazione (o marginalizzazione) rispetto agli altri parametri.\n\n## Riflessioni conclusive {.unnumbered .unlisted}\n\nIl concetto di **variabile casuale** costituisce il ponte fondamentale tra la teoria della probabilità, intesa come sistema di credenze coerenti, e l'analisi quantitativa dei fenomeni psicologici. Grazie a questa formalizzazione, qualsiasi risultato, che si tratti di un punteggio, di un tempo o di un conteggio, può essere tradotto in un oggetto matematico sul quale è possibile applicare gli strumenti del calcolo delle probabilità.\n\nLe due principali classi di variabili casuali, **discrete** e **continue**, richiedono formalizzazioni tecniche differenti (somme vs integrali), ma si basano sullo stesso principio: descrivere la distribuzione della credenza nello spazio dei possibili valori. La *funzione di massa di probabilità* (PMF) per variabili discrete e la *funzione di densità di probabilità* (PDF) per le variabili continue svolgono ruoli analoghi, mentre la *funzione di distribuzione cumulativa* (CDF) fornisce una rappresentazione unificante.\n\nPer lo psicologo che si avvicina all'inferenza bayesiana, questi concetti non sono astrazioni matematiche fini a sé stesse, ma il **vocabolario necessario** per:\n\n- specificare le distribuzioni a priori sui parametri di interesse;\n- comprendere la funzione di verosimiglianza che connette parametri e dati;\n- interpretare le distribuzioni a posteriori e gli intervalli di credibilità;\n- formulare domande probabilistiche sui fenomeni psicologici.\n\nNei capitoli successivi studieremo le **famiglie parametriche di distribuzioni**, come la distribuzione Beta, la distribuzione Normale, la distribuzione Binomiale, la distribuzione di Poisson e altre, che costituiscono i mattoni elementari della modellazione bayesiana. Ogni distribuzione codifica specifiche assunzioni sul processo generativo dei dati; comprendere le variabili casuali significa essere pronti a scegliere e interpretare queste distribuzioni in modo consapevole.\n\n## Punti chiave da ricordare {.unnumbered}\n\n::: {.callout-important}\n**Concetti essenziali:**\n\n1. **Variabile casuale come funzione**\n   - $X: \\Omega \\to \\mathbb{R}$ associa a ogni esito un valore numerico;\n   - la funzione è deterministica; l'incertezza riguarda quale esito si realizzerà;\n   - permette di passare da eventi qualitativi a quantità analizzabili.\n\n2. **Discrete vs Continue**\n   - **discrete**: valori numerabili (punteggi, conteggi);\n   - **continue**: valori in intervalli (tempi, misure fisiologiche);\n   - richiedono strumenti diversi: somme vs integrali.\n\n3. **PMF per variabili discrete**\n   - $p_X(x) = P(X = x)$ è una probabilità vera e propria;\n   - $\\sum_x p_X(x) = 1$.\n\n4. **PDF per variabili continue**\n   - $f_X(x)$ è una densità, non una probabilità;\n   - $P(a \\leq X \\leq b) = \\int_a^b f_X(x) \\, dx$;\n   - $P(X = x) = 0$ per ogni $x$ specifico.\n\n5. **CDF come rappresentazione unificata**\n   - $F_X(x) = P(X \\leq x)$ funziona per entrambi i tipi;\n   - fondamentale per quantili e intervalli di credibilità.\n\n6. **Variabili multiple**\n   - la distribuzione congiunta descrive l'incertezza su combinazioni di valori;\n   - marginalizzazione: eliminare una variabile sommando/integrando;\n   - indipendenza: $p_{X,Y}(x,y) = p_X(x) \\cdot p_Y(y)$.\n\n**Formule essenziali:**\n\n$$\n\\text{PMF: } p_X(x) = P(X = x), \\quad \\sum_x p_X(x) = 1\n$$\n\n$$\n\\text{PDF: } P(a \\leq X \\leq b) = \\int_a^b f_X(x) \\, dx, \\quad \\int_{-\\infty}^{+\\infty} f_X(x) \\, dx = 1\n$$\n\n$$\n\\text{CDF: } F_X(x) = P(X \\leq x)\n$$\n\n$$\n\\text{Marginale: } p_X(x) = \\sum_y p_{X,Y}(x,y)\n$$\n\n**Per il prossimi capitoli:**\n\nStudieremo le famiglie di distribuzioni parametriche (Bernoulli, Binomiale, Normale, Beta...) che costituiscono il vocabolario della modellazione bayesiana. Ogni distribuzione codifica assunzioni specifiche sul processo generativo dei dati.\n:::\n\n::: {.callout-note collapse=true title=\"Informazioni sull'ambiente di sviluppo\"}\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsessionInfo()\n#> R version 4.6.1 (2026-06-24)\n#> Platform: aarch64-apple-darwin23\n#> Running under: macOS Tahoe 26.5.2\n#> \n#> Matrix products: default\n#> BLAS:   /Library/Frameworks/R.framework/Versions/4.6/Resources/lib/libRblas.0.dylib \n#> LAPACK: /Library/Frameworks/R.framework/Versions/4.6/Resources/lib/libRlapack.dylib;  LAPACK version 3.12.1\n#> \n#> locale:\n#> [1] C.UTF-8/UTF-8/C.UTF-8/C/C.UTF-8/C.UTF-8\n#> \n#> time zone: Europe/Rome\n#> tzcode source: internal\n#> \n#> attached base packages:\n#> [1] stats     graphics  grDevices utils     datasets  methods   base     \n#> \n#> other attached packages:\n#>  [1] ragg_1.5.2            tinytable_0.17.0      withr_3.0.3          \n#>  [4] systemfonts_1.3.2     patchwork_1.3.2       ggdist_3.3.3         \n#>  [7] tidybayes_3.0.7       bayesplot_1.15.0      ggplot2_4.0.3        \n#> [10] reliabilitydiag_0.2.1 priorsense_1.2.0      posterior_1.7.0      \n#> [13] loo_2.10.0            rstan_2.32.7          StanHeaders_2.32.10  \n#> [16] brms_2.23.0           Rcpp_1.1.1-1.1        sessioninfo_1.2.4    \n#> [19] conflicted_1.2.0      janitor_2.2.1         matrixStats_1.5.0    \n#> [22] modelr_0.1.11         tibble_3.3.1          dplyr_1.2.1          \n#> [25] tidyr_1.3.2           rio_1.3.0             here_1.0.2           \n#> \n#> loaded via a namespace (and not attached):\n#>  [1] svUnit_1.0.8          tidyselect_1.2.1      farver_2.1.2         \n#>  [4] S7_0.2.2              fastmap_1.2.0         tensorA_0.36.2.1     \n#>  [7] digest_0.6.39         timechange_0.4.0      estimability_2.0.0   \n#> [10] lifecycle_1.0.5       magrittr_2.0.5        compiler_4.6.1       \n#> [13] rlang_1.2.0           tools_4.6.1           yaml_2.3.12          \n#> [16] knitr_1.51            labeling_0.4.3        bridgesampling_1.2-1 \n#> [19] htmlwidgets_1.6.4     pkgbuild_1.4.8        curl_7.1.0           \n#> [22] RColorBrewer_1.1-3    abind_1.4-8           purrr_1.2.2          \n#> [25] grid_4.6.1            stats4_4.6.1          xtable_1.8-8         \n#> [28] inline_0.3.21         emmeans_2.0.3         scales_1.4.0         \n#> [31] cli_3.6.6             mvtnorm_1.4-1         rmarkdown_2.31       \n#> [34] generics_0.1.4        otel_0.2.0            RcppParallel_5.1.11-2\n#> [37] cachem_1.1.0          stringr_1.6.0         parallel_4.6.1       \n#> [40] vctrs_0.7.3           V8_8.2.0              Matrix_1.7-5         \n#> [43] jsonlite_2.0.0        arrayhelpers_1.1-1    glue_1.8.1           \n#> [46] codetools_0.2-20      distributional_0.8.1  lubridate_1.9.5      \n#> [49] stringi_1.8.7         gtable_0.3.6          QuickJSR_1.10.0      \n#> [52] pillar_1.11.1         htmltools_0.5.9       Brobdingnag_1.2-9    \n#> [55] R6_2.6.1              textshaping_1.0.5     rprojroot_2.1.1      \n#> [58] evaluate_1.0.5        lattice_0.22-9        backports_1.5.1      \n#> [61] memoise_2.0.1         broom_1.0.13          snakecase_0.11.1     \n#> [64] rstantools_2.6.0      coda_0.19-4.1         gridExtra_2.3.1      \n#> [67] nlme_3.1-169          checkmate_2.3.4       xfun_0.59            \n#> [70] pkgconfig_2.0.3\n```\n:::\n\n:::\n",
    "supporting": [
      "06_random_var_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}