{
  "hash": "7bca639974e133e92e3bbdb2c36157f6",
  "result": {
    "engine": "knitr",
    "markdown": "# Dal dato all'ipotesi: l'evidenza e l'aggiornamento delle credenze {#sec-prob-inference-uncertainty}\n\n## Introduzione {.unnumbered .unlisted}\n\nNei capitoli precedenti abbiamo introdotto gli elementi fondamentali della teoria della probabilità e il linguaggio formale necessario per descrivere l’incertezza. In questo capitolo iniziamo a utilizzare questi strumenti per affrontare le domande centrali dell’inferenza statistica: che cosa possiamo dire, sulla base dei dati osservati, riguardo a quantità di interesse che non osserviamo direttamente?\n\nNella ricerca psicologica siamo spesso interessati a fenomeni complessi, come la prevalenza di un disturbo d’ansia nella popolazione, l’efficacia di un trattamento terapeutico o la relazione tra stress e prestazione cognitiva. Tuttavia, non abbiamo mai accesso all’intera popolazione né a misurazioni perfette. I dati disponibili sono sempre parziali: osserviamo un numero finito di partecipanti, in contesti specifici, utilizzando strumenti affetti da errore. Di conseguenza, ogni conclusione deve necessariamente confrontarsi con l’incertezza.\n\nLa domanda fondamentale diventa quindi: **come possiamo quantificare l’incertezza sulle quantità di interesse a partire da dati limitati?** In che modo possiamo esprimere, in termini probabilistici, il grado di sicurezza che la prevalenza di un disturbo rientri in un certo intervallo, oppure che un trattamento produca un effetto clinicamente rilevante?\n\nL’approccio che adotteremo in questo capitolo tratta i *parametri* del modello statistico — come proporzioni, medie e varianze — come quantità sconosciute rispetto alle quali possediamo un’incertezza di tipo *epistemico*. Questa incertezza viene rappresentata mediante distribuzioni di probabilità. Prima di osservare i dati, formalizziamo le nostre conoscenze preliminari attraverso una distribuzione *a priori*. Dopo aver raccolto i dati, aggiorniamo tali credenze ottenendo una distribuzione *a posteriori*. Questo meccanismo di aggiornamento coerente delle credenze alla luce dell’evidenza osservata costituisce il cuore dell’inferenza bayesiana.\n\n## Un esempio concreto: la stima della prevalenza dei sintomi depressivi\n\nSupponiamo di voler stimare la prevalenza di sintomi depressivi clinicamente rilevanti nella popolazione studentesca universitaria. Poiché non è possibile osservare l’intera popolazione di interesse, ci affidiamo a un campione e utilizziamo l’inferenza statistica per trarre conclusioni più generali.\n\nImmaginiamo di reclutare un campione probabilistico di 200 studenti universitari. In questo campione, 72 partecipanti presentano sintomi depressivi clinicamente rilevanti. Il nostro obiettivo è inferire il valore del parametro $\\theta$, che rappresenta la vera prevalenza di tali sintomi nella popolazione di riferimento, e quantificare l’incertezza associata a questa stima.\n\nNell’approccio bayesiano, il processo inferenziale inizia prima della raccolta dei dati. Le nostre conoscenze preliminari su $\\theta$ vengono formalizzate attraverso una distribuzione *a priori*. Dopo aver osservato i dati, in questo caso, 72 casi su 200, tali conoscenze vengono aggiornate mediante il teorema di Bayes, producendo una distribuzione *a posteriori* per il parametro $\\theta$.\n\nA partire dalla distribuzione a posteriori possiamo ricavare diverse quantità di interesse. Una delle più comuni è l’intervallo di credibilità, che riassume l’incertezza sulla stima del parametro. Ad esempio, un possibile intervallo di credibilità al 95% per $\\theta$ potrebbe essere [0.29; 0.43]. Questo intervallo ammette un’interpretazione diretta: sulla base delle informazioni disponibili, sia pregresse sia derivate dai dati osservati, riteniamo che vi sia una probabilità del 95% che il valore effettivo della prevalenza nella popolazione si collochi tra 0.29 e 0.43.\n\nQuesta interpretazione probabilistica dell’incertezza è coerente con il modo in cui i ricercatori ragionano intuitivamente sui risultati empirici e fornisce una risposta chiara e informativa alla domanda di ricerca che ha motivato lo studio.\n\n### Panoramica del capitolo {.unnumbered .unlisted}\n\n- Comprendere le proprietà statistiche della media campionaria (valore atteso, varianza, SE) e il loro significato inferenziale.\n\n- Comprendere la distribuzione campionaria; come la sua forma determina la verosimiglianza che i dati impongono sui parametri.\n\n- Legge dei Grandi Numeri: perché la media campionaria converge al valore vero e quali implicazioni ha per l’affidabilità delle stime.\n\n- Teorema del Limite Centrale: quando e perché la distribuzione delle medie può essere approssimata con una distribuzione gaussiana e quali sono i limiti pratici di tale approssimazione.\n\n- Come costruire prior, verosimiglianza e posterior; calcolo degli intervalli di credibilità e interpretazione probabilistica.\n\n- Ruolo dell’errore standard come misura di informatività; definizione di precisione e regole di somma delle precisioni per sintetizzare studi indipendenti.\n\n- Analisi di sensibilità per valutare l'effetto dei prior sulla posterior. \n\n- Distinzione tra incertezza campionaria e distorsioni sistematiche e strategie metodologiche per mitigarle.\n\n::: {.callout-tip collapse=true}\n## Prerequisiti\n\n- Leggere il capitolo *Sampling Distributions of Estimators* [@schervish2014probability].\n:::\n\n::: {.callout-caution collapse=true title=\"Preparazione del Notebook\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhere::here(\"code\", \"_common.R\") |> \n  source()\n# Riapplica il tema per sicurezza\napply_visual_theme()\n```\n:::\n\n:::\n\n## Dati, parametri e incertezza\n\n### Dati osservati e parametro di interesse\n\nRiprendiamo l’esempio introdotto in precedenza, relativo alla stima della proporzione $\\theta$ di studenti che presentano sintomi depressivi clinicamente rilevanti nella popolazione studentesca universitaria. Dopo aver selezionato un campione rappresentativo di $n$ studenti, per ciascun partecipante registriamo la presenza o l’assenza del sintomo mediante una codifica binaria.\n\nLe osservazioni del campione possono essere formalizzate come variabili casuali $X_1, X_2, \\ldots, X_n,$ dove ciascuna $X_i$ assume il valore:\n\n$$\nX_i =\n\\begin{cases}\n1 & \\text{se lo studente } i \\text{ presenta il sintomo}, \\\\\n0 & \\text{in caso contrario}.\n\\end{cases}\n$$\n\nQuesta rappresentazione esplicita il legame tra il processo di raccolta dei dati e un modello probabilistico. In particolare, ci consente di descrivere formalmente l’incertezza associata alle osservazioni e di collegarla al parametro di interesse $\\theta$, che rappresenta la prevalenza del fenomeno nella popolazione di riferimento.\n\n### Dalla statistica descrittiva all’inferenza probabilistica\n\nUna prima sintesi dei dati osservati è fornita dalla proporzione campionaria:\n\n$$\n\\bar{X} = \\frac{1}{n}\\sum_{i=1}^n X_i = \\frac{\\text{numero di studenti con sintomo}}{n}.\n$$\n\nQuesta quantità riassume l’informazione contenuta nel campione, ma ha un ruolo puramente descrittivo. Il nostro obiettivo non è semplicemente descrivere i dati osservati, bensì utilizzare tali informazioni per trarre conclusioni sul parametro $\\theta$, che non è direttamente osservabile.\n\nLa questione centrale diventa quindi la seguente: **in che modo il valore osservato di $\\bar{X}$ dovrebbe modificare la nostra incertezza riguardo a $\\theta$?** Rispondere a questa domanda richiede di andare oltre la statistica descrittiva e di adottare un approccio inferenziale fondato su un modello probabilistico.\n\n### Il modello probabilistico di riferimento\n\nPer collegare i dati osservati al parametro di interesse, costruiamo un modello probabilistico che metta in relazione:\n\n1. le osservazioni empiriche $X_1, \\ldots, X_n$;\n2. il parametro $\\theta$, considerato come quantità sconosciuta e soggetta a incertezza epistemica;\n3. le informazioni disponibili prima dell’osservazione dei dati.\n\nAssumiamo che, condizionatamente al parametro $\\theta$, ciascuna osservazione segua una distribuzione di Bernoulli:\n\n$$\nX_i \\mid \\theta \\sim \\text{Bernoulli}(\\theta).\n$$\n\nQuesta assunzione formalizza l’idea che, se il valore di $\\theta$ fosse noto, la probabilità che uno studente qualsiasi presenti il sintomo sarebbe pari a $\\theta$. Il modello specifica quindi come i dati sarebbero generati per ciascun possibile valore del parametro.\n\n::: {.callout-note}\n\n### Notazione condizionale e sua interpretazione\n\nLa notazione $X_i \\mid \\theta$ indica che stiamo descrivendo la distribuzione della variabile casuale $X_i$ assumendo che il parametro $\\theta$ sia fissato a un valore specifico. Questa formulazione non implica che il valore di $\\theta$ sia conosciuto, ma serve a strutturare il ragionamento inferenziale: *se* $\\theta$ avesse un certo valore, *allora* le osservazioni seguirebbero una determinata distribuzione.\n:::\n\n## Proprietà fondamentali della media campionaria\n\nNel @sec-prob-random-var-properties abbiamo già derivato le proprietà algebriche di base della media campionaria come applicazioni dirette della linearità del valore atteso e dell'additività della varianza per variabili indipendenti. Abbiamo visto che $\\mathbb{E}[\\bar{X}] = \\mu$ e che $\\text{Var}(\\bar{X}) = \\sigma^2/n$.\n\nIn questa sezione, **approfondiamo il significato inferenziale** di questi risultati, esaminandoli in relazione all'incertezza sul parametro $\\theta$ e collegandoli esplicitamente alla struttura del processo di campionamento. Mentre nel capitolo precedente l'enfasi era sulle proprietà algebriche generali, qui ci concentriamo su come queste proprietà si traducano nella capacità dei dati osservati di informare le nostre credenze sul parametro di interesse.\n\nRiprendiamo quindi le derivazioni in forma più dettagliata, esplicitando il condizionamento rispetto al parametro e introducendo l'interpretazione in termini di distribuzione campionaria e verosimiglianza.\n\n### Valore atteso della media campionaria\n\nSupponiamo di avere osservazioni $X_1, X_2, \\ldots, X_n$ **indipendenti e identicamente distribuite** (i.i.d.), ciascuna con valore atteso\n$$\n\\mathbb{E}[X_i \\mid \\theta] = \\theta.\n$$\n\n::: {#thm-expval-sample-mean}\nIl valore atteso della media campionaria è:\n$$\n\\mathbb{E}[\\bar{X} \\mid \\theta] = \\theta.\n$$\n:::\n\n::: {.proof}\nPer definizione, la media campionaria è:\n$$\n\\bar{X} = \\frac{1}{n}\\sum_{i=1}^n X_i.\n$$\n\nApplicando l’operatore di valore atteso:\n$$\n\\mathbb{E}[\\bar{X} \\mid \\theta]\n= \\mathbb{E}\\left[\\frac{1}{n}\\sum_{i=1}^n X_i ,\\bigg|, \\theta\\right].\n$$\n\nPer la linearità del valore atteso:\n$$\n= \\frac{1}{n}\\sum_{i=1}^n \\mathbb{E}[X_i \\mid \\theta].\n$$\n\nPoiché tutte le variabili sono identicamente distribuite con valore atteso pari a $\\theta$:\n$$\n= \\frac{1}{n}\\cdot n\\theta = \\theta.\n$$\n:::\n\n**Interpretazione**\nQuesto risultato mostra che la media campionaria è *centrata* sul valore del parametro $\\theta$. In assenza di errori sistematici, $\\bar{X}$ non tende né a sovrastimare né a sottostimare la prevalenza reale nella popolazione. Questa proprietà giustifica l’uso della media campionaria come sintesi informativa dei dati e, nel contesto bayesiano, implica che la distribuzione predittiva della media campionaria è centrata sul valore atteso del parametro.\n\n### Varianza della media campionaria\n\nLa seconda proprietà fondamentale riguarda la *variabilità* della media campionaria.\n\n::: {#thm-var-sample-mean}\nSe le osservazioni sono indipendenti e ciascuna ha varianza\n$$\n\\text{Var}(X_i \\mid \\theta) = \\sigma^2,\n$$\nallora:\n$$\n\\text{Var}(\\bar{X} \\mid \\theta) = \\frac{\\sigma^2}{n}.\n$$\n:::\n\n::: {.proof}\nPer definizione:\n$$\n\\text{Var}(\\bar{X} \\mid \\theta)\n= \\text{Var}\\left(\\frac{1}{n}\\sum_{i=1}^n X_i ,\\bigg|, \\theta\\right).\n$$\n\nUsando la proprietà $\\text{Var}(aY) = a^2 \\text{Var}(Y)$:\n$$\n= \\frac{1}{n^2}\\text{Var}\\left(\\sum_{i=1}^n X_i ,\\bigg|, \\theta\\right).\n$$\n\nPoiché le osservazioni sono indipendenti, la varianza della somma è la somma delle varianze:\n$$\n= \\frac{1}{n^2}\\sum_{i=1}^n \\text{Var}(X_i \\mid \\theta)\n= \\frac{1}{n^2}\\cdot n\\sigma^2\n= \\frac{\\sigma^2}{n}.\n$$\n:::\n\n**Interpretazione**\nQuesto risultato evidenzia che la variabilità della media campionaria diminuisce all’aumentare della dimensione del campione. In particolare:\n\n* la varianza di $\\bar{X}$ decresce proporzionalmente a $1/n$;\n* per ridurre della metà la deviazione standard della media è necessario quadruplicare il numero di osservazioni.\n\nQuesta proprietà fornisce una spiegazione matematica del fatto che, all’aumentare dei dati disponibili, l’inferenza diventa più precisa. In un’ottica bayesiana, ciò si manifesta come una distribuzione a posteriori progressivamente più concentrata attorno ai valori plausibili di $\\theta$.\n\n### Il caso delle variabili Bernoulliane\n\nNel contesto considerato, ciascuna osservazione $X_i$ è una variabile aleatoria binaria che assume valore 1 in caso di “successo” (ad esempio, presenza di un sintomo) e 0 in caso di “insuccesso”. Tali osservazioni sono modellate mediante una distribuzione di **Bernoulli** con parametro $\\theta$, che rappresenta la probabilità di successo.\n\n#### 1. Variabilità di una singola osservazione\n\nLa varianza di una variabile Bernoulliana è:\n$$\n\\text{Var}(X_i \\mid \\theta) = \\theta(1-\\theta).\n$$\n\nQuesta funzione è massima per $\\theta = 0.5$, corrispondente alla massima incertezza, e si annulla per $\\theta = 0$ o $\\theta = 1$, casi in cui l’esito è deterministico.\n\n#### 2. Variabilità della media campionaria\n\nDato un campione di $n$ osservazioni indipendenti, la media campionaria\n$$\n\\bar{X} = \\frac{1}{n}\\sum_{i=1}^n X_i\n$$\ncoincide con la proporzione osservata di successi.\n\nLa sua varianza è:\n$$\n\\text{Var}(\\bar{X} \\mid \\theta)\n= \\frac{\\theta(1-\\theta)}{n}.\n$$\n\nQuesto risultato mostra come l’incertezza associata alla proporzione osservata diminuisca all’aumentare della numerosità campionaria.\n\n#### 3. L’errore standard e la sua interpretazione\n\nLa radice quadrata della varianza della media campionaria è detta **errore standard (SE)**:\n$$\n\\text{SE}(\\bar{X}) = \\sqrt{\\frac{\\theta(1-\\theta)}{n}}.\n$$\n\nL’errore standard quantifica la variabilità attesa della proporzione osservata da un campione all’altro, dovuta esclusivamente alla casualità del processo di campionamento. In altre parole, misura quanto $\\bar{X}$ può discostarsi da $\\theta$ in assenza di errori sistematici.\n\nIn un’ottica bayesiana, l’errore standard fornisce un’indicazione diretta del contenuto informativo dei dati: un errore standard ridotto, tipicamente associato a campioni numerosi, segnala che le osservazioni sono altamente informative e conducono a una distribuzione a posteriori concentrata. Al contrario, un errore standard elevato indica che i dati forniscono un’informazione più debole sul parametro, lasciando spazio a una maggiore incertezza residua. In questo senso, l’errore standard costituisce un ponte concettuale tra la variabilità del fenomeno osservato e l’affidabilità inferenziale delle conclusioni che possiamo trarre.\n\n## Comprendere la variabilità dei dati\n\n### Il concetto di distribuzione campionaria\n\nImmaginiamo di poter osservare molti campioni diversi, tutti della stessa dimensione $n$, estratti dalla medesima popolazione. Per ciascun campione potremmo calcolare la media campionaria $\\bar{X}$, ottenendo ogni volta un valore potenzialmente diverso a causa della variabilità casuale del campionamento.\n\nLa **distribuzione campionaria** della media descrive come questi valori di $\\bar{X}$ si distribuiscono al variare del campione. Essa non riguarda un singolo insieme di dati osservati, ma un esperimento ipotetico ripetuto molte volte nelle stesse condizioni.\n\nQuesto concetto teorico è centrale per comprendere il ruolo dei dati nell’inferenza statistica. In particolare, la distribuzione campionaria costituisce la base della **funzione di verosimiglianza**, che rappresenta il meccanismo formale attraverso cui i dati informano l’inferenza bayesiana: la verosimiglianza quantifica quanto ciascun possibile valore del parametro $\\theta$ sia compatibile con i dati osservati.\n\n### Esempio concreto: una popolazione finita\n\nPer rendere il concetto più concreto, consideriamo un esempio estremamente semplice: una popolazione costituita da soli quattro valori numerici.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nx <- c(2, 4.5, 5, 5.5)\nx\n#> [1] 2.0 4.5 5.0 5.5\n```\n:::\n\n\nCalcoliamo la media e la varianza della popolazione:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmean_x <- mean(x)  # Media\nvar_x <- var(x) * ((length(x) - 1) / length(x))  # Varianza\ncat(\"Media:\", mean_x, \"\\n\")\n#> Media: 4.25\ncat(\"Varianza:\", var_x, \"\\n\")\n#> Varianza: 1.81\n```\n:::\n\n\nSupponiamo ora di estrarre tutti i possibili campioni di dimensione $n = 2$ **con reinserimento**. Poiché la popolazione contiene quattro elementi, questo procedimento genera $4^2 = 16$ campioni distinti.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Generiamo tutte le coppie possibili\nsamples <- expand.grid(x, x)\nhead(samples, 10)\n#>    Var1 Var2\n#> 1   2.0  2.0\n#> 2   4.5  2.0\n#> 3   5.0  2.0\n#> 4   5.5  2.0\n#> 5   2.0  4.5\n#> 6   4.5  4.5\n#> 7   5.0  4.5\n#> 8   5.5  4.5\n#> 9   2.0  5.0\n#> 10  4.5  5.0\n```\n:::\n\n\nPer ciascun campione calcoliamo la media campionaria:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsample_means <- rowMeans(samples)\nsample_means\n#>  [1] 2.00 3.25 3.50 3.75 3.25 4.50 4.75 5.00 3.50 4.75 5.00 5.25 3.75 5.00 5.25\n#> [16] 5.50\n```\n:::\n\n\nPer organizzare i risultati in modo più chiaro, costruiamo un data frame che associa a ciascun campione la sua media:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndf <- data.frame(\n  Campione = apply(samples, 1, paste, collapse = \", \"),\n  Media = sample_means\n)\nhead(df, 10)\n#>    Campione Media\n#> 1      2, 2  2.00\n#> 2    4.5, 2  3.25\n#> 3      5, 2  3.50\n#> 4    5.5, 2  3.75\n#> 5    2, 4.5  3.25\n#> 6  4.5, 4.5  4.50\n#> 7    5, 4.5  4.75\n#> 8  5.5, 4.5  5.00\n#> 9      2, 5  3.50\n#> 10   4.5, 5  4.75\n```\n:::\n\n\nLa distribuzione delle medie campionarie può ora essere visualizzata tramite un istogramma:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot(data.frame(sample_means), aes(x = sample_means)) +\n  geom_histogram(\n    aes(y = after_stat(density))\n  ) +\n  labs(\n    title = \"Distribuzione campionaria della media (n = 2)\",\n    x = \"Media campionaria\",\n    y = \"Densità\"\n  )\n```\n\n::: {.cell-output-display}\n![](10_dal_dato_ipotesi_files/figure-html/unnamed-chunk-7-1.png){fig-align='center' width=85%}\n:::\n:::\n\n\nVerifichiamo empiricamente le proprietà teoriche discusse in precedenza:\n\n\n::: {.cell layout-align=\"center\"}\n\n```\n#> Media delle medie campionarie: 4.25\n#> Media della popolazione: 4.25\n#> Varianza delle medie campionarie: 0.906\n#> Varianza teorica (σ² / n): 0.906\n```\n:::\n\n\nI risultati confermano esattamente le proprietà teoriche della distribuzione campionaria:\n\n* la media delle medie campionarie coincide con la media della popolazione;\n* la varianza delle medie campionarie è pari a $\\sigma^2 / n$.\n\n::: {.callout-note}\n\n### Interpretazione per l'inferenza\n\nQuesta simulazione illustra in modo concreto perché l’osservazione di un valore specifico di $\\bar{X}$ fornisce informazione sul parametro sottostante. I valori della media campionaria tendono a concentrarsi attorno al valore vero del parametro, e tale concentrazione aumenta al crescere della dimensione del campione $n$.\n\nDi conseguenza, osservare $\\bar{X} = 4.75$ rende plausibile che il parametro che governa il processo generativo dei dati sia vicino a tale valore. Questo è il motivo per cui, nell’inferenza bayesiana, la distribuzione a posteriori di $\\theta$ risulta centrata in prossimità del valore osservato di $\\bar{X}$, con una dispersione che riflette la quantità di informazione contenuta nei dati.\n:::\n\n## Legge dei Grandi Numeri {#sec-lln}\n\nLa *Legge dei Grandi Numeri* (LGN) è uno dei risultati fondamentali della teoria della probabilità e fornisce una giustificazione matematica cruciale per l’inferenza statistica basata sui dati.\n\n### Enunciato intuitivo\n\nIn forma intuitiva, la LGN afferma che, all’aumentare del numero di osservazioni $n$, la media campionaria $\\bar{X}_n$ tende ad avvicinarsi al valore atteso della variabile casuale, che nel nostro contesto coincide con il parametro $\\theta$:\n\n$$\n\\bar{X}_n \\xrightarrow{n \\to \\infty} \\theta.\n$$\n\nQuesta convergenza può essere formalizzata in modi diversi. In particolare, si distinguono due versioni principali.\n\n1. **Legge dei Grandi Numeri Debole**\n   La media campionaria converge a $\\theta$ *in probabilità*. Formalmente, per ogni $\\varepsilon > 0$:\n   $$\n   \\Pr\\bigl(|\\bar{X}_n - \\theta| > \\varepsilon \\mid \\theta\\bigr) \\to 0\n   \\quad \\text{quando } n \\to \\infty.\n   $$\n\n2. **Legge dei Grandi Numeri Forte**\n   La media campionaria converge a $\\theta$ *quasi certamente*, ossia:\n   $$\n   \\Pr\\left(\\lim_{n \\to \\infty} \\bar{X}_n = \\theta \\,\\bigg|\\, \\theta\\right) = 1.\n   $$\n\nEntrambe le formulazioni esprimono l’idea che, con un numero sufficientemente elevato di osservazioni, la media campionaria fornisce una rappresentazione sempre più accurata del parametro che governa il processo generativo dei dati.\n\n### Implicazioni per l’inferenza bayesiana\n\nNel contesto bayesiano, la Legge dei Grandi Numeri ha una conseguenza fondamentale: al crescere della dimensione campionaria, l’informazione contenuta nei dati domina progressivamente quella contenuta nella distribuzione *a priori*. Di conseguenza, la distribuzione *a posteriori* di $\\theta$ tende a concentrarsi sempre più attorno al valore vero del parametro.\n\nPiù precisamente, se la distribuzione a priori assegna una probabilità positiva a un intorno del valore vero di $\\theta$, allora l’accumularsi dei dati porta a una concentrazione della distribuzione a posteriori in prossimità di tale valore. In questo senso, **con un numero sufficiente di osservazioni, ricercatori che partono da credenze iniziali diverse giungeranno a conclusioni sostanzialmente coincidenti**.\n\nQuesto risultato evidenzia la robustezza dell’inferenza bayesiana: l’evidenza empirica, se sufficientemente informativa, finisce per prevalere sulle ipotesi iniziali.\n\n### Simulazione della convergenza campionaria\n\nPer osservare empiricamente il comportamento descritto dalla LGN, consideriamo uno scenario in cui il valore vero del parametro è $\\theta = 0.45$. Simuliamo una sequenza di osservazioni bernoulliane e calcoliamo la media campionaria cumulativa al crescere di $n$.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(42)\ntheta_true <- 0.45\nn_max <- 1000\n\n# Generazione delle osservazioni bernoulliane\nobservations <- rbinom(n_max, size = 1, prob = theta_true)\n\n# Calcolo delle medie cumulative\ncumulative_means <- cumsum(observations) / seq_along(observations)\n\n# Preparazione dei dati per la visualizzazione\ndata_plot <- data.frame(\n  n = 1:n_max,\n  mean = cumulative_means\n)\n\nggplot(data_plot, aes(x = n, y = mean)) +\n  geom_line(linewidth = 0.8, alpha = 0.8) +\n  geom_hline(yintercept = theta_true, \n             linetype = \"dashed\", \n             linewidth = 1.2) +\n  geom_ribbon(aes(ymin = mean - 1.96 * sqrt(mean * (1 - mean) / n),\n                  ymax = mean + 1.96 * sqrt(mean * (1 - mean) / n)),\n              alpha = 0.2) +\n  labs(\n    title = \"Convergenza della media campionaria\\nverso il parametro vero\",\n    subtitle = \"Legge dei Grandi Numeri: stabilizzazione con l'aumentare delle osservazioni\",\n    x = \"Dimensione campionaria (n)\",\n    y = \"Media campionaria cumulativa\"\n  ) +\n  ylim(0.2, 0.7) +\n  scale_fill_qualitative() +\n  annotate(\"text\", x = 800, y = theta_true + 0.03, \n           label = paste(\"θ =\", theta_true), \n           size = 4.5)\n```\n\n::: {.cell-output-display}\n![](10_dal_dato_ipotesi_files/figure-html/unnamed-chunk-9-1.png){fig-align='center' width=85%}\n:::\n:::\n\n\n**Osservazioni empiriche**\nNelle fasi iniziali del campionamento, la media campionaria $\\bar{X}_n$ mostra ampie fluttuazioni, riflettendo l’elevata incertezza associata a campioni di piccole dimensioni. Con l’aumentare di $n$, tali oscillazioni si riducono progressivamente e la media campionaria si stabilizza in prossimità del valore vero del parametro.\n\n::: {.callout-important}\n\n### Il carattere autocorrettivo dell’inferenza bayesiana\n\nLa Legge dei Grandi Numeri mette in luce una proprietà essenziale dell’inferenza bayesiana: l’accumularsi dell’evidenza empirica tende a correggere progressivamente eventuali imprecisioni nelle credenze iniziali.\n\nQuando ricercatori diversi partono da distribuzioni a priori differenti, ma nessuna di esse esclude il valore vero del parametro, l’osservazione della stessa sequenza di dati conduce a distribuzioni a posteriori sempre più simili. Questo carattere autocorrettivo conferisce all’approccio bayesiano una forte solidità epistemologica: le conclusioni inferenziali non dipendono in modo arbitrario dalle assunzioni iniziali, ma sono guidate dall’evidenza osservata.\n:::\n\n### Applicazioni in psicologia\n\nLa Legge dei Grandi Numeri ha importanti implicazioni pratiche per la ricerca psicologica.\n\nNegli *studi pilota*, caratterizzati da campioni di piccole dimensioni, le stime sono inevitabilmente soggette a un’elevata variabilità. Questo spiega perché le repliche con campioni più ampi producano risultati più stabili e affidabili.\n\nLe *meta-analisi* sfruttano implicitamente la LGN combinando le informazioni provenienti da molti studi indipendenti, aumentando di fatto la dimensione campionaria complessiva e riducendo l’incertezza sulle stime degli effetti.\n\nNei *disegni longitudinali*, infine, l’osservazione ripetuta degli stessi individui nel tempo consente di accumulare informazione progressiva sui parametri di interesse, migliorando la precisione delle inferenze riguardanti le caratteristiche stabili dei fenomeni psicologici studiati.\n\n## Teorema del Limite Centrale\n\nIl *Teorema del Limite Centrale* (TLC) è uno dei risultati più profondi e generali della teoria della probabilità e riveste un ruolo centrale nella pratica dell’inferenza statistica, inclusa l’inferenza bayesiana.\n\n### Enunciato formale\n\n::: {#thm-clt}\nSiano $X_1, X_2, \\ldots, X_n$ variabili aleatorie indipendenti e identicamente distribuite, con valore atteso $\\mu$ e varianza finita $\\sigma^2$. Allora, al crescere di $n$, la distribuzione della media campionaria $\\bar{X}_n$ converge verso una distribuzione normale:\n\n$$\n\\bar{X}_n \\;\\dot\\sim\\; \\mathcal{N}\\!\\left(\\mu, \\frac{\\sigma^2}{n}\\right),\n$$\n\ndove la notazione $\\dot\\sim$ indica che la distribuzione è *approssimativamente* normale per valori di $n$ sufficientemente grandi.\n:::\n\n### Portata concettuale\n\nLa proprietà più sorprendente del TLC è che la distribuzione della media campionaria tende alla normalità **indipendentemente dalla forma della distribuzione delle variabili originarie**, purché queste abbiano varianza finita e siano indipendenti.\n\nCiò significa che variabili provenienti da distribuzioni uniformi, esponenziali, binarie o fortemente asimmetriche producono, una volta mediate su un numero sufficientemente elevato di osservazioni, una media campionaria la cui distribuzione è ben approssimata da una distribuzione normale. Questa regolarità emergente spiega il ruolo ubiquo della distribuzione normale in statistica applicata.\n\n### Visualizzazione del TLC\n\nConsideriamo una popolazione con distribuzione uniforme, chiaramente non normale:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(42)\npopulation <- runif(5000, min = 0, max = 1)\n\n# Istogramma della popolazione\nggplot(data.frame(population), aes(x = population)) +\n  geom_histogram(\n    aes(y = after_stat(density))\n  ) +\n  labs(\n    title = \"Distribuzione della popolazione (uniforme)\",\n    x = \"Valore\",\n    y = \"Densità\"\n  )\n```\n\n::: {.cell-output-display}\n![](10_dal_dato_ipotesi_files/figure-html/unnamed-chunk-10-1.png){fig-align='center' width=85%}\n:::\n:::\n\n\nEstraiamo ora 300 campioni, ciascuno di dimensione $n = 30$, e calcoliamo le rispettive medie campionarie:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsample_size <- 30\nnum_samples <- 300\n\nsample_means <- replicate(num_samples, {\n  sample_data <- sample(population, size = sample_size, replace = TRUE)\n  mean(sample_data)\n})\n\n# Media e deviazione standard delle medie campionarie\nx_bar <- mean(sample_means)\nstd <- sd(sample_means)\n\ncat(\"Media delle medie campionarie:\", x_bar, \"\\n\")\n#> Media delle medie campionarie: 0.501\ncat(\"Deviazione standard delle medie:\", std, \"\\n\")\n#> Deviazione standard delle medie: 0.0524\n```\n:::\n\n\nConfrontiamo questi risultati con i valori teorici:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmu <- mean(population)\nsigma <- sd(population)\n\ncat(\"\\nValori teorici della popolazione:\\n\")\n#> \n#> Valori teorici della popolazione:\ncat(\"Media:\", mu, \"\\n\")\n#> Media: 0.503\ncat(\"Deviazione standard teorica (σ / √n):\", sigma / sqrt(sample_size), \"\\n\")\n#> Deviazione standard teorica (σ / √n): 0.0531\n```\n:::\n\n\nVisualizziamo ora la distribuzione delle medie campionarie con la curva normale teorica sovrapposta:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot(data.frame(sample_means), aes(x = sample_means)) +\n  geom_histogram(\n    aes(y = after_stat(density)),\n    bins = 30\n  ) +\n  stat_function(\n    fun = dnorm,\n    args = list(mean = x_bar, sd = std),\n    linewidth = 1.2\n  ) +\n  labs(\n    title = \"Distribuzione delle medie campionarie\",\n    subtitle = \"La curva rossa rappresenta la distribuzione normale teorica\",\n    x = \"Media campionaria\",\n    y = \"Densità\"\n  )\n```\n\n::: {.cell-output-display}\n![](10_dal_dato_ipotesi_files/figure-html/unnamed-chunk-13-1.png){fig-align='center' width=85%}\n:::\n:::\n\n\n**Osservazione**\nNonostante la popolazione di partenza segua una distribuzione uniforme, la distribuzione delle medie campionarie risulta approssimativamente normale, in accordo con quanto previsto dal Teorema del Limite Centrale.\n\n### Implicazioni per l’inferenza bayesiana\n\nIl Teorema del Limite Centrale ha conseguenze rilevanti anche nel contesto dell’inferenza bayesiana. In presenza di campioni di grandi dimensioni, la distribuzione a posteriori di un parametro tende ad assumere una forma approssimativamente gaussiana, a condizione che la distribuzione a priori sia sufficientemente regolare e non escluda il valore vero del parametro.\n\nQuesta *normalità asintotica* della distribuzione a posteriori contribuisce alla robustezza dell’approccio bayesiano: al crescere dell’evidenza empirica, l’influenza delle scelte specifiche del prior si attenua, e la forma della posterior è dominata dall’informazione contenuta nei dati.\n\nDal punto di vista pratico, questo risultato giustifica l’uso di **approssimazioni gaussiane** per la distribuzione a posteriori in molti contesti applicativi, semplificando notevolmente i calcoli quando soluzioni analitiche esatte risultano complesse o non disponibili.\n\n### Esempio: approssimazione della distribuzione a posteriori\n\nConsideriamo uno studio in ambito di psicologia clinica volto a stimare la prevalenza di un determinato sintomo. Supponiamo di adottare una distribuzione a priori uniforme per il parametro $\\theta$ e di osservare un campione di $n = 100$ soggetti, di cui $y = 45$ presentano il sintomo.\n\nPer una dimensione campionaria di questo ordine di grandezza, la distribuzione a posteriori può essere approssimata mediante una distribuzione normale:\n\n$$\n\\theta \\mid y \\;\\dot\\sim\\; \\mathcal{N}\\!\\left(\\frac{45}{100}, \\frac{0.45 \\times 0.55}{100}\\right).\n$$\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Parametri osservati\nn <- 100\ny <- 45\np_hat <- y / n\n\n# Approssimazione normale della posteriore\nposterior_mean <- p_hat\nposterior_sd <- sqrt(p_hat * (1 - p_hat) / n)\n\ncat(\"Media a posteriori (approssimata):\", posterior_mean, \"\\n\")\n#> Media a posteriori (approssimata): 0.45\ncat(\"Deviazione standard a posteriori:\", round(posterior_sd, 4), \"\\n\")\n#> Deviazione standard a posteriori: 0.0497\n\n# Intervallo di credibilità al 95%\nlower <- qnorm(0.025, mean = posterior_mean, sd = posterior_sd)\nupper <- qnorm(0.975, mean = posterior_mean, sd = posterior_sd)\n\ncat(\"\\nIntervallo di credibilità 95%: [\",\n    round(lower, 3), \",\", round(upper, 3), \"]\\n\")\n#> \n#> Intervallo di credibilità 95%: [ 0.352 , 0.548 ]\n```\n:::\n\n\nLa distribuzione a posteriori approssimata può essere visualizzata come segue:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ntheta_grid <- seq(0.25, 0.65, length.out = 1000)\nposterior_density <- dnorm(theta_grid,\n                           mean = posterior_mean,\n                           sd = posterior_sd)\n\nggplot(data.frame(theta = theta_grid,\n                  density = posterior_density),\n       aes(x = theta, y = density)) +\n  geom_line(linewidth = 1.2) +\n  geom_area(\n    data = subset(data.frame(theta = theta_grid,\n                             density = posterior_density),\n                  theta >= lower & theta <= upper),\n    aes(x = theta, y = density)\n  ) +\n  geom_vline(xintercept = c(lower, upper),\n             linetype = \"dashed\",\n             linewidth = 0.8) +\n  scale_fill_qualitative() +\n  labs(\n    title = \"Distribuzione a posteriori (approssimazione normale)\",\n    subtitle = \"Intervallo di credibilità al 95% per la proporzione\",\n    x = \"$\\\\theta$ (proporzione nella popolazione)\",\n    y = \"Densità a posteriori\"\n  ) \n```\n\n::: {.cell-output-display}\n![](10_dal_dato_ipotesi_files/figure-html/unnamed-chunk-15-1.png){fig-align='center' width=85%}\n:::\n:::\n\n\n**Interpretazione dell’intervallo di credibilità**\nL’intervallo $[0.352,, 0.548]$ ammette un’interpretazione probabilistica diretta: alla luce dei dati osservati e del modello adottato, vi è una probabilità del 95% che la vera proporzione nella popolazione si collochi tra il 35.2% e il 54.8%. Questa interpretazione è coerente con il modo in cui i ricercatori ragionano sull’incertezza parametrica e costituisce uno dei principali punti di forza dell’approccio bayesiano.\n## Precisione, informazione ed errore standard\n\n### L’errore standard come misura di informatività\n\nL’*errore standard* di una statistica è definito come la deviazione standard della sua distribuzione campionaria. Nel caso della media campionaria, esso è dato da:\n\n$$\n\\text{SE}(\\bar{X}) = \\sqrt{\\frac{\\sigma^2}{n}}.\n$$\n\nQuesta quantità fornisce una misura diretta dell’informazione contenuta nei dati rispetto al parametro di interesse. Un errore standard ridotto indica che la distribuzione campionaria della statistica è fortemente concentrata, segnalando che i dati forniscono un’evidenza precisa su $\\theta$. In un contesto bayesiano, ciò si traduce in una distribuzione a posteriori stretta e ben localizzata. Al contrario, un errore standard elevato indica una maggiore variabilità campionaria e, di conseguenza, una distribuzione a posteriori più dispersa.\n\n### Precisione come inverso della varianza\n\nNell’inferenza bayesiana è spesso utile esprimere l’incertezza non in termini di varianza, ma attraverso la nozione complementare di *precisione*, definita come il reciproco della varianza:\n\n$$\n\\text{Precisione} = \\frac{1}{\\text{Varianza}}.\n$$\n\nApplicando questa definizione alla media campionaria si ottiene:\n\n$$\n\\text{Precisione}(\\bar{X} \\mid \\theta) = \\frac{n}{\\sigma^2}.\n$$\n\nQuesta espressione mette in evidenza una proprietà fondamentale: **la precisione cresce linearmente con la dimensione campionaria $n$**. Tale relazione risulta spesso più intuitiva rispetto alla descrizione in termini di varianza, che decresce come $1/n$.\n\nIn molti modelli bayesiani la precisione viene adottata come parametro primario. Ad esempio, una distribuzione normale può essere parametrizzata come $X \\sim \\mathcal{N}(\\mu, \\tau)$, dove $\\tau = 1/\\sigma^2$ rappresenta la precisione. Questa scelta rende immediatamente trasparenti due principi chiave:\n\n* valori elevati di precisione corrispondono a una minore incertezza;\n* l’informazione proveniente da fonti indipendenti si combina tramite la **somma delle precisioni**.\n\n### Combinazione di informazioni: prior e dati\n\nUno degli aspetti più eleganti dell’approccio bayesiano è la sua capacità di integrare formalmente diverse fonti di informazione. La conoscenza pregressa sul parametro $\\theta$ è codificata nella distribuzione a priori, la cui incertezza può essere espressa mediante una precisione $\\tau_0$. L’informazione fornita dai dati è invece riassunta dalla verosimiglianza, la cui precisione, nel caso di una media campionaria normale con varianza nota, è pari a $n/\\sigma^2$.\n\nNel modello normale–normale, la distribuzione a posteriori ha una precisione data dalla semplice somma delle due componenti:\n\n$$\n\\tau_{\\text{post}} = \\tau_0 + \\frac{n}{\\sigma^2}.\n$$\n\nQuesta relazione fornisce una rappresentazione estremamente chiara del processo di aggiornamento bayesiano: ogni nuova osservazione contribuisce ad aumentare la precisione complessiva dell’inferenza. Il peso relativo attribuito alla conoscenza pregressa e ai nuovi dati è determinato in modo esplicito dalle rispettive precisioni, rendendo il processo di accumulo della conoscenza completamente trasparente.\n\n#### Esempio: sintesi di evidenze da studi multipli\n\nConsideriamo uno scenario tipico nella ricerca psicologica, in cui due studi indipendenti investigano lo stesso costrutto teorico $\\theta$, ma differiscono per dimensione campionaria e precisione delle stime.\n\n* **Studio A**: $n_A = 50$, $\\bar{X}_A = 0.42$, $\\text{SE}_A = 0.07$.\n* **Studio B**: $n_B = 200$, $\\bar{X}_B = 0.38$, $\\text{SE}_B = 0.035$.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Parametri degli studi\nn_A <- 50; x_bar_A <- 0.42; se_A <- 0.07\nn_B <- 200; x_bar_B <- 0.38; se_B <- 0.035\n\n# Calcolo delle precisioni\nprecision_A <- 1 / se_A^2\nprecision_B <- 1 / se_B^2\n\ncat(\"Precisione Studio A:\", round(precision_A, 2), \"\\n\")\n#> Precisione Studio A: 204\ncat(\"Precisione Studio B:\", round(precision_B, 2), \"\\n\")\n#> Precisione Studio B: 816\ncat(\"Rapporto di precisione B/A:\", round(precision_B / precision_A, 2), \"\\n\")\n#> Rapporto di precisione B/A: 4\n```\n:::\n\n\nLe precisioni calcolate mostrano che lo Studio B è circa quattro volte più informativo dello Studio A, in accordo con la sua dimensione campionaria quadruplicata.\n\nProcediamo ora alla sintesi bayesiana delle evidenze:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Combinazione delle informazioni\nprecision_combined <- precision_A + precision_B\nmean_combined <- (precision_A * x_bar_A + precision_B * x_bar_B) / precision_combined\nse_combined <- sqrt(1 / precision_combined)\n\ncat(\"Stima combinata:\", round(mean_combined, 3), \"\\n\")\n#> Stima combinata: 0.388\ncat(\"Errore standard combinato:\", round(se_combined, 4), \"\\n\")\n#> Errore standard combinato: 0.0313\ncat(\"\\nIntervallo di credibilità 95%:\\n\")\n#> \n#> Intervallo di credibilità 95%:\ncat(\"[\", round(mean_combined - 1.96 * se_combined, 3), \",\",\n    round(mean_combined + 1.96 * se_combined, 3), \"]\\n\")\n#> [ 0.327 , 0.449 ]\n```\n:::\n\n\nLa stima combinata risulta più vicina al valore osservato nello Studio B, riflettendo il suo maggiore contributo informativo. In modo del tutto automatico, l’approccio bayesiano assegna un peso maggiore alle evidenze più precise, producendo una sintesi coerente e ottimale di tutte le informazioni disponibili.\n\n## Convergenza bayesiana: da credenze diverse a conclusioni condivise\n\n### Il teorema di convergenza bayesiana\n\nUn risultato teorico centrale dell’inferenza bayesiana riguarda il comportamento asintotico della distribuzione a posteriori al crescere della dimensione campionaria. Questo risultato è noto come *consistenza bayesiana*.\n\n::: {#thm-bayesian-consistency}\n\n### Consistenza bayesiana\n\nSotto opportune condizioni di regolarità sul modello statistico e sulla distribuzione a priori, se la prior assegna una densità positiva al valore vero del parametro $\\theta_0$, allora, al crescere del numero di osservazioni:\n\n1. la distribuzione a posteriori converge verso una distribuzione degenere concentrata in $\\theta_0$:\n   $$\n   p(\\theta \\mid \\mathbf{X}_n) \\xrightarrow{n \\to \\infty} \\delta(\\theta - \\theta_0);\n   $$\n\n2. la media a posteriori converge al valore vero del parametro:\n   $$\n   \\mathbb{E}[\\theta \\mid \\mathbf{X}_n] \\xrightarrow{n \\to \\infty} \\theta_0;\n   $$\n\n3. la varianza a posteriori tende a zero:\n   $$\n   \\text{Var}(\\theta \\mid \\mathbf{X}_n) \\xrightarrow{n \\to \\infty} 0.\n   $$\n:::\n\nQuesti risultati formalizzano matematicamente l’idea che, con dati sufficienti, l’incertezza epistemica sul parametro venga progressivamente eliminata.\n\n### Interpretazione sostantiva\n\nIl teorema di consistenza bayesiana mette in luce alcune proprietà fondamentali dell’inferenza bayesiana.\n\n1. **Robustezza asintotica rispetto alla prior**\n   In presenza di un numero elevato di osservazioni, l’influenza della distribuzione a priori si attenua progressivamente, a condizione che essa non escluda il valore vero del parametro.\n\n2. **Carattere autocorrettivo**\n   Anche se le credenze iniziali sono imprecise o parzialmente errate, l’evidenza empirica opera una correzione graduale, guidando la distribuzione a posteriori verso il valore vero.\n\n3. **Velocità di convergenza**\n   In molti modelli regolari, la varianza a posteriori decresce con ordine $1/n$, in accordo con quanto osservato per la varianza della media campionaria e con le approssimazioni asintotiche discusse in precedenza.\n\nQueste proprietà forniscono una giustificazione teorica forte all’uso dell’inferenza bayesiana come strumento affidabile di apprendimento dai dati.\n\n### Illustrazione: convergenza con prior differenti\n\nConsideriamo tre ricercatori che partono da concezioni iniziali diverse riguardo al parametro $\\theta$:\n\n* **Ricercatore A**: prior $\\text{Beta}(2, 8)$, che privilegia valori bassi di $\\theta$ (circa 0.2);\n* **Ricercatore B**: prior $\\text{Beta}(8, 2)$, orientata verso valori elevati di $\\theta$ (circa 0.8);\n* **Ricercatore C**: prior $\\text{Beta}(1, 1)$, uniforme, che rappresenta una condizione di massima incertezza iniziale.\n\nIl valore vero del parametro è $\\theta_0 = 0.45$. Osserviamo come evolvono le rispettive distribuzioni a posteriori al crescere della dimensione campionaria.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Parametri della simulazione\ntheta_true <- 0.45\nn_observations <- c(10, 50, 200, 1000)\n\n# Specificazioni a priori\nprior_A <- c(2, 8)\nprior_B <- c(8, 2)\nprior_C <- c(1, 1)\n\n# Funzione per il calcolo delle posteriori\ncompute_posterior <- function(prior, n, theta) {\n  y <- rbinom(1, n, theta)\n  c(prior[1] + y, prior[2] + n - y)\n}\n\nset.seed(42)\nposteriors <- list()\n\nfor (n in n_observations) {\n  theta_grid <- seq(0.1, 0.9, length.out = 200)\n  \n  post_A <- compute_posterior(prior_A, n, theta_true)\n  post_B <- compute_posterior(prior_B, n, theta_true)\n  post_C <- compute_posterior(prior_C, n, theta_true)\n  \n  posteriors[[as.character(n)]] <- data.frame(\n    theta = rep(theta_grid, 3),\n    density = c(\n      dbeta(theta_grid, post_A[1], post_A[2]),\n      dbeta(theta_grid, post_B[1], post_B[2]),\n      dbeta(theta_grid, post_C[1], post_C[2])\n    ),\n    researcher = rep(c(\"A (prior conservativo)\",\n                       \"B (prior ottimista)\",\n                       \"C (prior non informativo)\"),\n                     each = length(theta_grid)),\n    n = n\n  )\n}\n\nall_posteriors <- do.call(rbind, posteriors)\nall_posteriors$n <- factor(all_posteriors$n,\n                           levels = n_observations,\n                           labels = paste(\"n =\", n_observations))\n\nggplot(all_posteriors,\n       aes(x = theta, y = density,\n           color = researcher, linetype = researcher)) +\n  geom_line(linewidth = 1.2) +\n  geom_vline(xintercept = theta_true,\n             linetype = \"dashed\",\n             linewidth = 1.2) +\n  facet_wrap(~ n, ncol = 2, scales = \"free_y\") +\n  scale_fill_qualitative() +\n  labs(\n    title = \"Convergenza bayesiana con prior differenti\",\n    subtitle = \"La linea verticale indica il valore vero θ = 0.45\",\n    x = \"Parametro θ\",\n    y = \"Densità a posteriori\",\n    color = \"Ricercatore\",\n    linetype = \"Ricercatore\"\n  ) +\n  theme(legend.position = \"bottom\",\n        plot.title = element_text(face = \"bold\"))\n```\n\n::: {.cell-output-display}\n![](10_dal_dato_ipotesi_files/figure-html/unnamed-chunk-18-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n**Osservazioni empiriche**\n\n1. Con $n = 10$ osservazioni, le distribuzioni a posteriori riflettono fortemente le differenze tra le prior.\n2. Con $n = 50$, emerge un chiaro processo di avvicinamento.\n3. Con $n = 200$, le posteriori risultano ampiamente sovrapposte.\n4. Con $n = 1000$, le differenze diventano praticamente impercettibili.\n\n### Implicazioni per la ricerca scientifica\n\n1. **Soggettività controllata**\n   Sebbene i ricercatori possano partire da credenze iniziali diverse, l’evidenza empirica conduce progressivamente a conclusioni condivise.\n\n2. **Ruolo cruciale della dimensione campionaria**\n   Con campioni piccoli, le specificazioni a priori esercitano un’influenza rilevante; con campioni ampi, l’inferenza è dominata dai dati.\n\n3. **Fondamento teorico della replicabilità**\n   Studi che utilizzano prior ragionevoli e raccolgono dati sufficienti tendono a convergere verso risultati simili, fornendo una base solida per la replicabilità scientifica.\n\n## Incertezza, distorsione sistematica e limiti dell’inferenza\n\n### L’errore standard quantifica solo l’incertezza campionaria\n\nÈ essenziale chiarire che l’errore standard, così come la dispersione della distribuzione a posteriori, misura esclusivamente l’incertezza epistemica dovuta alla variabilità campionaria. In altre parole, esso quantifica quanto le stime potrebbero variare se l’esperimento fosse ripetuto più volte nelle stesse condizioni.\n\nQuesta misura non fornisce alcuna informazione sulla presenza di errori sistematici nel disegno della ricerca, nel processo di campionamento o negli strumenti di misurazione. Di conseguenza, una stima può essere estremamente precisa dal punto di vista statistico e, al tempo stesso, sostanzialmente errata dal punto di vista scientifico.\n\n### Fonti di distorsione che persistono\n\nAlcune fonti di distorsione non vengono attenuate dall’aumento della dimensione campionaria e non sono catturate dall’errore standard.\n\n**Distorsione da selezione**\nSe la prevalenza dei disturbi d’ansia viene stimata attraverso un campione di volontari, gli individui con sintomi più gravi potrebbero essere sovra- o sotto-rappresentati. Anche in presenza di campioni molto ampi, la stima risultante sarebbe sistematicamente distorta rispetto alla popolazione di riferimento.\n\n**Distorsione da risposta**\nNello studio di costrutti auto-riferiti, come la frequenza di pensieri negativi, la desiderabilità sociale può indurre i partecipanti a fornire risposte sistematicamente attenuate. In questo caso si ottiene una stima statisticamente precisa, ma riferita a una rappresentazione distorta del fenomeno.\n\n**Errori di misurazione**\nSe lo strumento utilizzato presenta bassa affidabilità o non coglie adeguatamente il costrutto teorico di interesse, l’inferenza statistica risulta compromessa. L’aumento della dimensione campionaria non corregge problemi di validità o di qualità della misurazione: produce semplicemente stime più precise di una quantità mal definita.\n\n### Rappresentazione visiva: precisione versus accuratezza\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](10_dal_dato_ipotesi_files/figure-html/unnamed-chunk-19-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n**Principio fondamentale**\nLa situazione più critica nell’inferenza statistica si verifica quando un’elevata precisione si accompagna a una scarsa accuratezza. In questo scenario, i metodi statistici producono una falsa sensazione di certezza attorno a conclusioni sistematicamente distorte. Campioni molto grandi, se affetti da bias strutturali, conducono a stime altamente precise ma sostanzialmente errate. Questo paradosso rappresenta uno dei rischi più insidiosi dell’analisi quantitativa, poiché l’apparente solidità statistica può mascherare problemi metodologici profondi.\n\n::: {.callout-warning title=\"Il pericolo della falsa precisione\"}\n\nUn intervallo di credibilità particolarmente ristretto può indurre l’illusione di una conoscenza estremamente accurata. È cruciale ricordare che tale intervallo quantifica esclusivamente l’incertezza dovuta alla variabilità campionaria.\n\nIn presenza di distorsioni sistematiche nel campionamento, nella misurazione o nel disegno sperimentale, il valore vero del parametro potrebbe collocarsi ben al di fuori dei limiti dell’intervallo calcolato. L’inferenza bayesiana, pur essendo uno strumento potente per la quantificazione dell’incertezza campionaria, non è in grado di identificare né correggere automaticamente errori metodologici di fondo.\n\n**La precisione statistica non deve mai essere confusa con la validità scientifica.**\n:::\n\n### Strategie di mitigazione\n\nLa prevenzione della falsa precisione richiede innanzitutto una progettazione della ricerca metodologicamente solida. Campionamento probabilistico, protocolli standardizzati e strumenti con adeguate proprietà psicometriche costituiscono il primo livello di difesa contro le distorsioni sistematiche.\n\nL’approccio bayesiano offre inoltre strumenti analitici specifici, come le analisi di sensibilità, che consentono di valutare la robustezza delle conclusioni rispetto a diverse assunzioni. In contesti più complessi, la modellazione gerarchica permette di rappresentare esplicitamente molteplici fonti di variabilità e potenziali distorsioni, separando le diverse componenti di incertezza.\n\nInfine, la trasparenza epistemica rimane un principio irrinunciabile. Gli intervalli di credibilità e le distribuzioni a posteriori sono validi solo nel contesto delle assunzioni del modello adottato; il riconoscimento esplicito dei limiti metodologici è parte integrante di un’inferenza scientificamente responsabile.\n## Verso la verosimiglianza: come i dati informano le credenze\n\nIn questo capitolo abbiamo esaminato le proprietà matematiche fondamentali che governano il comportamento della media campionaria e, più in generale, il modo in cui i dati si relazionano ai parametri di interesse. Abbiamo visto che la media campionaria è centrata sul parametro, come espresso dalla relazione $\\mathbb{E}[\\bar{X}] = \\theta$, e che la sua variabilità diminuisce con l’aumentare della dimensione campionaria secondo la legge $\\text{Var}(\\bar{X}) = \\sigma^2 / n$. Abbiamo inoltre osservato che, al crescere del numero di osservazioni, la media campionaria converge al valore vero in accordo con la Legge dei Grandi Numeri e che la sua distribuzione tende asintoticamente alla normale per effetto del Teorema del Limite Centrale.\n\nResta ora da chiarire come queste proprietà si traducano operativamente nell’aggiornamento delle credenze bayesiane. La risposta risiede nella **funzione di verosimiglianza**, che costituisce il cuore del meccanismo inferenziale e sarà oggetto di un capitolo successivo. La verosimiglianza formalizza il modo in cui i dati informano le credenze: per ogni possibile valore del parametro $\\theta$, essa quantifica quanto tale valore renda plausibili le osservazioni raccolte.\n\nÈ proprio attraverso la verosimiglianza che le informazioni contenute nei dati vengono combinate con la distribuzione a priori mediante il teorema di Bayes, generando la distribuzione a posteriori. Le proprietà analizzate in questo capitolo — centratura, precisione crescente e convergenza — trovano nella verosimiglianza la loro espressione formale. Comprenderle a fondo è quindi essenziale per interpretare correttamente il funzionamento dell’inferenza bayesiana e il significato delle conclusioni che essa produce.\n\n## Riflessioni conclusive {.unnumbered .unlisted}\n\nIn questo capitolo abbiamo esaminato come sia possibile quantificare in modo sistematico l’incertezza quando si traggono conclusioni a partire da evidenze limitate. Le proprietà matematiche fondamentali della media campionaria mostrano che essa è centrata sul parametro della popolazione, giustificando l’uso dei dati osservati come base per l’inferenza. Abbiamo inoltre visto che la precisione delle stime aumenta con l’aumentare del numero di osservazioni, poiché la variabilità diminuisce proporzionalmente al fattore $1/n$. La Legge dei Grandi Numeri garantisce la convergenza delle inferenze verso i valori veri, mentre il Teorema del Limite Centrale fornisce il fondamento teorico per le approssimazioni distribuzionali ampiamente utilizzate nella pratica statistica.\n\nIn questo contesto, l’inferenza bayesiana emerge come un framework coerente e formalmente rigoroso per rappresentare e aggiornare l’incertezza. Le credenze iniziali, espresse attraverso distribuzioni a priori, vengono sistematicamente aggiornate alla luce dei dati osservati, producendo una distribuzione a posteriori che rappresenta lo stato di conoscenza più informato disponibile. Gli intervalli di credibilità offrono un’interpretazione probabilistica diretta e intuitiva dei risultati inferenziali. Un aspetto particolarmente rilevante è che, in presenza di una quantità sufficiente di dati, credenze iniziali anche molto diverse tendono a convergere verso conclusioni sostanzialmente condivise.\n\nÈ tuttavia essenziale riconoscere i limiti metodologici dell’inferenza statistica. Le procedure inferenziali quantificano l’incertezza campionaria, ma non sono in grado di correggere distorsioni sistematiche derivanti da problemi di campionamento, misurazione o disegno della ricerca. Campioni di grandi dimensioni affetti da bias possono produrre stime estremamente precise ma sostanzialmente errate, alimentando il rischio di false certezze. La qualità del disegno di ricerca rimane quindi un presupposto irrinunciabile che nessuna sofisticazione statistica può sostituire.\n\nNel capitolo successivo vedremo come la funzione di verosimiglianza formalizzi in modo esplicito il ruolo dei dati nel processo inferenziale, completando il quadro concettuale necessario per comprendere il meccanismo di aggiornamento bayesiano e le sue implicazioni per la ricerca empirica.\n\n::: {.callout-important title=\"Problemi\" collapse=\"true\"}\nEsercizi sulla distribuzione campionaria e sull'inferenza sono disponibili sulla seguente [pagina web](https://stats.libretexts.org/Bookshelves/Introductory_Statistics/Introductory_Statistics_(Shafer_and_Zhang)/06%3A_Sampling_Distributions/6.E%3A_Sampling_Distributions_(Exercises)).\n:::\n\n::: {.callout-note collapse=true title=\"Informazioni sull'ambiente di sviluppo\"}\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsessionInfo()\n#> R version 4.5.2 (2025-10-31)\n#> Platform: aarch64-apple-darwin20\n#> Running under: macOS Tahoe 26.2\n#> \n#> Matrix products: default\n#> BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib \n#> LAPACK: /Library/Frameworks/R.framework/Versions/4.5-arm64/Resources/lib/libRlapack.dylib;  LAPACK version 3.12.1\n#> \n#> locale:\n#> [1] C.UTF-8/UTF-8/C.UTF-8/C/C.UTF-8/C.UTF-8\n#> \n#> time zone: Europe/Rome\n#> tzcode source: internal\n#> \n#> attached base packages:\n#> [1] stats     graphics  grDevices utils     datasets  methods   base     \n#> \n#> other attached packages:\n#>  [1] ragg_1.5.0            tinytable_0.15.2      withr_3.0.2          \n#>  [4] systemfonts_1.3.1     patchwork_1.3.2       ggdist_3.3.3         \n#>  [7] tidybayes_3.0.7       bayesplot_1.15.0      ggplot2_4.0.1        \n#> [10] reliabilitydiag_0.2.1 priorsense_1.2.0      posterior_1.6.1      \n#> [13] loo_2.9.0             rstan_2.32.7          StanHeaders_2.32.10  \n#> [16] brms_2.23.0           Rcpp_1.1.0            sessioninfo_1.2.3    \n#> [19] conflicted_1.2.0      janitor_2.2.1         matrixStats_1.5.0    \n#> [22] modelr_0.1.11         tibble_3.3.0          dplyr_1.1.4          \n#> [25] tidyr_1.3.2           rio_1.2.4             here_1.0.2           \n#> \n#> loaded via a namespace (and not attached):\n#>  [1] svUnit_1.0.8          tidyselect_1.2.1      farver_2.1.2         \n#>  [4] S7_0.2.1              fastmap_1.2.0         TH.data_1.1-5        \n#>  [7] tensorA_0.36.2.1      digest_0.6.39         timechange_0.3.0     \n#> [10] estimability_1.5.1    lifecycle_1.0.4       survival_3.8-3       \n#> [13] magrittr_2.0.4        compiler_4.5.2        rlang_1.1.6          \n#> [16] tools_4.5.2           yaml_2.3.12           knitr_1.51           \n#> [19] labeling_0.4.3        bridgesampling_1.2-1  htmlwidgets_1.6.4    \n#> [22] curl_7.0.0            pkgbuild_1.4.8        RColorBrewer_1.1-3   \n#> [25] abind_1.4-8           multcomp_1.4-29       purrr_1.2.0          \n#> [28] grid_4.5.2            stats4_4.5.2          colorspace_2.1-2     \n#> [31] xtable_1.8-4          inline_0.3.21         emmeans_2.0.1        \n#> [34] scales_1.4.0          MASS_7.3-65           cli_3.6.5            \n#> [37] mvtnorm_1.3-3         rmarkdown_2.30        generics_0.1.4       \n#> [40] otel_0.2.0            RcppParallel_5.1.11-1 cachem_1.1.0         \n#> [43] stringr_1.6.0         splines_4.5.2         parallel_4.5.2       \n#> [46] vctrs_0.6.5           V8_8.0.1              Matrix_1.7-4         \n#> [49] sandwich_3.1-1        jsonlite_2.0.0        arrayhelpers_1.1-0   \n#> [52] glue_1.8.0            codetools_0.2-20      distributional_0.5.0 \n#> [55] lubridate_1.9.4       stringi_1.8.7         gtable_0.3.6         \n#> [58] QuickJSR_1.8.1        pillar_1.11.1         htmltools_0.5.9      \n#> [61] Brobdingnag_1.2-9     R6_2.6.1              textshaping_1.0.4    \n#> [64] rprojroot_2.1.1       evaluate_1.0.5        lattice_0.22-7       \n#> [67] backports_1.5.0       memoise_2.0.1         broom_1.0.11         \n#> [70] snakecase_0.11.1      rstantools_2.5.0      gridExtra_2.3        \n#> [73] coda_0.19-4.1         nlme_3.1-168          checkmate_2.3.3      \n#> [76] xfun_0.55             zoo_1.8-15            pkgconfig_2.0.3\n```\n:::\n\n:::\n\n## Bibliografia {.unnumbered .unlisted}\n",
    "supporting": [
      "10_dal_dato_ipotesi_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}