{
  "hash": "bf5feba2f4e77adb0a3b1d106e067972",
  "result": {
    "engine": "knitr",
    "markdown": "# Proprietà delle variabili casuali {#sec-prob-random-var-properties}\n\n## Introduzione {.unnumbered .unlisted}\n\nNel capitolo sulle variabili casuali (@sec-prob-random-var) abbiamo introdotto le variabili casuali come funzioni che associano valori numerici agli esiti di un esperimento aleatorio. Abbiamo visto come la *funzione di massa di probabilità* (PMF) e la *funzione di densità di probabilità* (PDF) forniscano una descrizione completa della distribuzione della probabilità sui possibili valori assunti da una variabile.\n\nQueste descrizioni sono teoricamente esaustive, ma in molti contesti pratici risultano eccessivamente dettagliate. Pensiamo, ad esempio, a uno psicologo clinico che deve comunicare a un paziente l’esito atteso di un trattamento, oppure a un ricercatore che deve confrontare l’efficacia media di due interventi. In situazioni di questo tipo, non è necessario conoscere l’intera distribuzione di probabilità: bastano pochi numeri riassuntivi capaci di catturarne le caratteristiche essenziali. Qual è il valore “tipico” attorno a cui si concentra la distribuzione? Quanto è ampia la variabilità attorno a questo valore?\n\nQuesto capitolo introduce i due indicatori fondamentali che rispondono a queste domande: il **valore atteso**, che individua il “centro di gravità” della distribuzione, e la **varianza**, che ne quantifica la dispersione. Questi concetti non sono semplici convenzioni descrittive, ma possiedono un significato teorico profondo. In particolare, il valore atteso emerge naturalmente come la previsione ottimale quando le decisioni sono valutate tramite una perdita quadratica, mentre la varianza fornisce una misura formale dell’incertezza residua.\n\nPer questo motivo, valore atteso e varianza occupano una posizione centrale non solo nella statistica descrittiva, ma anche nella **teoria delle decisioni** e nell’**inferenza bayesiana**. Comprenderne il significato e le proprietà è essenziale per interpretare correttamente le distribuzioni di probabilità e per utilizzarle come strumenti operativi nel ragionamento scientifico e clinico.\n\n### Panoramica del capitolo {.unnumbered .unlisted}\n\n- Il valore atteso come media ponderata e centro di massa probabilistico.\n- Proprietà algebriche del valore atteso: linearità e additività.\n- La varianza come misura della dispersione attorno al valore atteso.\n- Proprietà della varianza e formula computazionale alternativa.\n- Deviazione standard e standardizzazione.\n- Il teorema di Chebyshev e i momenti di una distribuzione.\n\n::: {.callout-tip collapse=true}\n## Prerequisiti\n\n- Aver letto i capitoli @sec-prob-interpretation, @sec-prob-axioms-coherence e @sec-bayes-theorem.\n- Leggere l'appendice @sec-apx-calculus per i concetti base di calcolo integrale.\n- Familiarità con R e le operazioni vettoriali di base.\n:::\n\n::: {.callout-caution collapse=true title=\"Preparazione del Notebook\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhere::here(\"code\", \"_common.R\") |> \n  source()\n\n# Pacchetti necessari\nif (!requireNamespace(\"pacman\")) install.packages(\"pacman\")\npacman::p_load(ggplot2, dplyr, tidyr)\n```\n:::\n\n:::\n\n## Il valore atteso come centro di gravità\n\nIl **valore atteso** di una variabile casuale rappresenta il suo *baricentro probabilistico*, cioè il punto attorno al quale la probabilità si bilancia. In una prospettiva frequentista, esso corrisponde al valore medio che ci si aspetta di osservare in una lunga serie di ripetizioni dell’esperimento. In una prospettiva bayesiana, invece, il valore atteso formalizza la nostra **aspettativa razionale** alla luce dello stato informativo corrente.\n\n::: {#def-expected-value}\n\n### Valore atteso (speranza matematica)\n\nIl *valore atteso* (o *media* o *speranza matematica*) di una variabile casuale $X$ è definito come segue.\n\nPer variabili **discrete** con funzione di massa di probabilità $p_X$:\n$$\n\\mathbb{E}[X] = \\sum_{x \\in \\mathcal{X}} x \\cdot p_X(x).\n$$\n\nPer variabili **continue** con funzione di densità di probabilità $f_X$:\n$$\n\\mathbb{E}[X] = \\int_{-\\infty}^{+\\infty} x \\cdot f_X(x),dx.\n$$\n:::\n\nIn entrambi i casi, il valore atteso è una **media ponderata** dei valori possibili della variabile, in cui i pesi sono dati dalle probabilità (nel caso discreto) o dalla densità di probabilità (nel caso continuo).\n\nÈ importante sottolineare che il valore atteso **non deve necessariamente coincidere con un valore osservabile** della variabile. Per la somma di due dadi, $\\mathbb{E}[X] = 7$ è un valore possibile; per il lancio di un singolo dado, invece, $\\mathbb{E}[X] = 3.5$ non può mai essere osservato direttamente. Ciò nonostante, 3.5 rappresenta correttamente il punto di equilibrio della distribuzione.\n\n::: {.callout-note collapse=\"true\" title=\"Esempio: moneta equilibrata\"}\n\n#### Il valore atteso non è un esito {.unnumbered .unlisted}\n\nConsideriamo una moneta equilibrata e definiamo la variabile casuale $X$ tale che:\n\n* $X = 1$ se esce *testa*,\n* $X = 0$ se esce *croce*.\n\nIl valore atteso è:\n$$\n\\mathbb{E}[X] = 0 \\cdot \\frac{1}{2} + 1 \\cdot \\frac{1}{2} = 0.5.\n$$\n\nIl valore 0.5 non è un esito possibile del lancio della moneta, che produce sempre 0 o 1. Tuttavia, 0.5 rappresenta il **centro di gravità** della distribuzione e il valore verso cui tende la media empirica in una lunga sequenza di lanci.\n:::\n\n## Il valore atteso come limite di frequenze\n\nUn’interpretazione operativa del valore atteso è fornita dalla **legge dei grandi numeri**. Se ripetiamo un esperimento molte volte e calcoliamo la media aritmetica dei risultati, questa media tende al valore atteso teorico.\n\nFormalmente, se $X_1, X_2, \\ldots, X_n$ sono realizzazioni indipendenti della stessa variabile casuale $X$, allora:\n\n$$\n\\bar{X}_n = \\frac{X_1 + X_2 + \\cdots + X_n}{n}\n\\;\\xrightarrow{n \\to \\infty}\\;\n\\mathbb{E}[X].\n$$\n\nQuesta convergenza **non definisce** il valore atteso — che resta una media ponderata secondo la definizione formale — ma ne fornisce una giustificazione empirica. Il valore atteso è quindi il valore verso cui tende la media osservata quando il processo viene campionato ripetutamente.\n\n::: {.callout-note collapse=\"true\" title=\"Esempio: valore atteso della somma di due dadi\"}\n\n#### Verifica della convergenza {.unnumbered .unlisted}\n\nSia $X$ la variabile casuale che rappresenta la somma di due dadi equilibrati. La sua distribuzione di probabilità è:\n\n$$\nP(X = x) = \\left\\{\n\\begin{array}{ll}\n\\frac{x-1}{36} & \\text{per } x = 2, 3, \\ldots, 7 \\\\\n\\frac{13-x}{36} & \\text{per } x = 8, 9, \\ldots, 12\n\\end{array}\n\\right.\n$$\n\nIn forma esplicita:\n$$\nP(X = 2) = \\frac{1}{36}, \\quad\nP(X = 3) = \\frac{2}{36}, \\quad\nP(X = 4) = \\frac{3}{36}, \\quad\nP(X = 5) = \\frac{4}{36}, \\quad\nP(X = 6) = \\frac{5}{36},\n$$\n$$\nP(X = 7) = \\frac{6}{36}, \\quad\nP(X = 8) = \\frac{5}{36}, \\quad\nP(X = 9) = \\frac{4}{36}, \\quad\nP(X = 10) = \\frac{3}{36}, \\quad\nP(X = 11) = \\frac{2}{36}, \n$$\n$$\nP(X = 12) = \\frac{1}{36}.\n$$\n\nIl valore atteso è:\n$$\n\\mathbb{E}[X] = 7.\n$$\n\nUna simulazione mostra che la media empirica converge a questo valore:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(123)\n\nvalori <- 2:12\nprob <- c(1, 2, 3, 4, 5, 6, 5, 4, 3, 2, 1) / 36\nE_teorico <- sum(valori * prob)\n\nn_sim <- 1000000\nsomme <- sample(1:6, n_sim, replace = TRUE) +\n         sample(1:6, n_sim, replace = TRUE)\nE_empirico <- mean(somme)\n\ncat(\"Valore atteso teorico:\", E_teorico, \"\\n\")\n#> Valore atteso teorico: 7\ncat(\"Media empirica:\", E_empirico, \"\\n\")\n#> Media empirica: 7\n```\n:::\n\n\nLa convergenza della media empirica al valore 7 illustra concretamente la legge dei grandi numeri.\n:::\n\n## Un calcolo più efficiente: la linearità del valore atteso\n\nIl valore atteso possiede una proprietà algebrica di importanza cruciale: la **linearità**. Per qualunque coppia di variabili casuali $X$ e $Y$ e per qualunque costante $a$ vale:\n$$\n\\mathbb{E}[X + Y] = \\mathbb{E}[X] + \\mathbb{E}[Y],\n\\qquad\n\\mathbb{E}[aX] = a,\\mathbb{E}[X].\n$$\n\nQuesta proprietà non richiede alcuna assunzione di indipendenza.\n\nNel caso della somma di due dadi, se $D_1$ e $D_2$ rappresentano i risultati dei singoli dadi e $X = D_1 + D_2$, otteniamo:\n\n$$\n\\mathbb{E}[X] = \\mathbb{E}[D_1] + \\mathbb{E}[D_2].\n$$\n\nPoiché per ciascun dado $\\mathbb{E}[D_i] = 3.5$, segue immediatamente:\n\n$$\n\\mathbb{E}[X] = 3.5 + 3.5 = 7.\n$$\n\nQuesto approccio è non solo più efficiente dal punto di vista computazionale, ma mette in luce il ruolo del valore atteso come **operatore lineare**, una proprietà che lo rende centrale nella teoria delle decisioni, nell’inferenza bayesiana e nella modellazione statistica avanzata.\n\n## Proprietà del valore atteso\n\nIl valore atteso possiede proprietà algebriche di notevole importanza che ne rendono il calcolo spesso sorprendentemente semplice. Queste proprietà non sono assunzioni aggiuntive, ma **conseguenze dirette della definizione** di valore atteso come media ponderata, e valgono per qualsiasi variabile casuale per cui il valore atteso sia ben definito.\n\n## Linearità del valore atteso\n\n::: {#thm-expected-value-linearity}\n\n### Linearità\n\nPer qualsiasi variabile casuale $X$ e per qualunque costanti $a,b \\in \\mathbb{R}$ vale:\n$$\n\\mathbb{E}[aX + b] = a,\\mathbb{E}[X] + b.\n$$\n:::\n\nLa linearità afferma che **traslazioni** e **riscalamenti** dei valori di una variabile si riflettono in modo diretto sul valore atteso. Se moltiplichiamo tutti i valori per una costante $a$, la media viene moltiplicata per $a$; se aggiungiamo una costante $b$ a tutti i valori, la media aumenta di $b$.\n\nQuesta proprietà rende il valore atteso uno strumento estremamente stabile e prevedibile, qualità essenziali nella modellazione statistica e nella teoria delle decisioni.\n\n## Additività del valore atteso\n\n::: {#thm-expected-value-additivity}\n\n### Additività\n\nPer qualsiasi coppia di variabili casuali $X$ e $Y$ vale:\n\n$$\n\\mathbb{E}[X + Y] = \\mathbb{E}[X] + \\mathbb{E}[Y].\n$$\nQuesta proprietà è valida **sempre**, indipendentemente dal fatto che $X$ e $Y$ siano indipendenti o dipendenti.\n:::\n\nL’additività è una conseguenza immediata della linearità ed è particolarmente notevole perché **non richiede l’indipendenza** tra le variabili. Anche in presenza di correlazione, il valore atteso della somma coincide con la somma dei valori attesi.\n\nPer una somma di $n$ variabili casuali $X_1, \\ldots, X_n$ si ottiene:\n\n$$\n\\mathbb{E}\\left[\\sum_{i=1}^{n} X_i\\right] = \\sum_{i=1}^{n} \\mathbb{E}[X_i].\n$$\nQuesta proprietà semplifica in modo drastico molti calcoli teorici e applicativi.\n\n\n### Prodotto di variabili casuali\n\n::: {#thm-expected-value-product}\n\n### Prodotto di variabili indipendenti\n\nSe $X$ e $Y$ sono variabili casuali **indipendenti**, allora vale:\n\n$$\n\\mathbb{E}[XY] = \\mathbb{E}[X]\\cdot \\mathbb{E}[Y].\n$$\n:::\n\nA differenza dell’additività, questa proprietà **richiede** l’indipendenza. In generale, per variabili dipendenti il valore atteso del prodotto non è uguale al prodotto dei valori attesi. Questa distinzione sarà cruciale quando introdurremo concetti come covarianza e correlazione.\n\n::: {.callout-note collapse=\"true\" title=\"Esempio: Dado e moneta\"}\n\n**Applicazione della linearità**\n\nConsideriamo l’esperimento di lanciare una moneta e un dado. Sia:\n\n* $X$ la variabile casuale associata alla moneta, con valori $0$ (croce) e $1$ (testa);\n* $Y$ la variabile casuale associata al dado, con valori da 1 a 6.\n\nVogliamo calcolare il valore atteso di $X + Y$.\n\nUn approccio diretto richiederebbe di elencare tutti i 12 esiti possibili e calcolare la media ponderata. Utilizzando invece l’additività:\n$$\n\\mathbb{E}[X + Y] = \\mathbb{E}[X] + \\mathbb{E}[Y] = 0.5 + 3.5 = 4.0.\n$$\n\nLa verifica diretta conferma il risultato:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncoin <- c(0, 1)\ndie <- 1:6\nsample_space <- expand.grid(X = coin, Y = die)\nsample_space$sum <- sample_space$X + sample_space$Y\n\nE_diretto <- mean(sample_space$sum)\nE_lineare <- 0.5 + 3.5\n\ncat(\"Calcolo diretto:\", E_diretto, \"\\n\")\n#> Calcolo diretto: 4\ncat(\"Calcolo via linearità:\", E_lineare, \"\\n\")\n#> Calcolo via linearità: 4\n```\n:::\n\n:::\n\n### Valore atteso della media campionaria\n\nUna conseguenza fondamentale della linearità riguarda la **media aritmetica** di più osservazioni. Se $X_1, \\ldots, X_n$ sono variabili casuali indipendenti e identicamente distribuite (i.i.d.) con valore atteso $\\mathbb{E}[X_i] = \\mu$, la media campionaria:\n\n$$\n\\bar{X} = \\frac{1}{n}\\sum_{i=1}^{n} X_i\n$$\n\nha valore atteso:\n\n$$\n\\mathbb{E}[\\bar{X}] = \\frac{1}{n}\\sum_{i=1}^{n} \\mathbb{E}[X_i] = \\frac{1}{n} \\cdot n \\cdot \\mu = \\mu.\n$$\n\nQuesto risultato mostra che la media campionaria è uno **stimatore non distorto** del valore atteso della popolazione: in media, la media campionaria coincide con il parametro che intende stimare.\n\n### Punto chiave da ricordare\n\n* La linearità è la proprietà centrale del valore atteso.\n* L'additività vale sempre, anche senza indipendenza.\n* Il prodotto richiede indipendenza.\n* La media campionaria conserva il valore atteso della popolazione.\n\n---\n\n## La varianza come misura di dispersione\n\nIl valore atteso individua il centro di una distribuzione, ma da solo non fornisce informazioni su **quanto** i valori della variabile si discostino da questo centro. Due variabili casuali possono avere lo stesso valore atteso e tuttavia comportamenti molto diversi: una può essere fortemente concentrata attorno alla media, l'altra estremamente dispersa.\n\nPer quantificare la dispersione, introduciamo gli **scarti dalla media**, cioè la variabile casuale $X - \\mathbb{E}[X]$. Gli scarti possono assumere valori positivi o negativi e, per definizione del valore atteso, la loro media è sempre zero. Di conseguenza, una semplice media degli scarti non può fornire una misura utile della variabilità.\n\nPer ottenere una misura non nulla e sempre positiva della dispersione, si considera il **quadrato degli scarti**, che elimina i segni e penalizza maggiormente le deviazioni più ampie.\n\n## Definizione di varianza\n\n::: {#def-variance}\n\n### Varianza\n\nLa *varianza* di una variabile casuale $X$ è definita come il valore atteso degli scarti quadratici dalla media:\n$$\n\\text{Var}(X) = \\mathbb{E}\\left[(X - \\mathbb{E}[X])^2\\right].\n$$\n:::\n\nIndicando con $\\mu = \\mathbb{E}[X]$, la varianza può essere scritta in forma esplicita come:\n\n* **caso discreto**\n  $$\n  \\text{Var}(X) = \\sum_i (x_i - \\mu)^2 \\cdot p_X(x_i),\n  $$\n\n* **caso continuo**\n  $$\n  \\text{Var}(X) = \\int_{-\\infty}^{+\\infty} (x - \\mu)^2 \\cdot f_X(x) \\, dx.\n  $$\n\nLa varianza è sempre **non negativa**, cioè $\\text{Var}(X) \\geq 0$ per ogni variabile casuale $X$. L'uguaglianza vale se e solo se $X$ è una costante, ossia se non esiste alcuna incertezza sul valore assunto dalla variabile.\n\nValori elevati di varianza indicano una forte dispersione dei valori attorno alla media e quindi una maggiore incertezza nella previsione degli esiti. Al contrario, una varianza piccola segnala che la distribuzione è fortemente concentrata attorno al valore atteso.\n\n## Formula alternativa della varianza\n\nEsiste una forma equivalente della varianza che risulta spesso più conveniente dal punto di vista computazionale.\n\n::: {#thm-variance-formula}\n\n### Formula alternativa\n\n$$\n\\text{Var}(X) = \\mathbb{E}[X^2] - \\bigl(\\mathbb{E}[X]\\bigr)^2.\n$$\n:::\n\n### Dimostrazione\n\n::: {.proof}\nSia $\\mu = \\mathbb{E}[X]$. Partendo dalla definizione:\n\\begin{align*}\n\\text{Var}(X)\n&= \\mathbb{E}[(X - \\mu)^2] \\\\\n&= \\mathbb{E}[X^2 - 2\\mu X + \\mu^2] \\\\\n&= \\mathbb{E}[X^2] - 2\\mu\\,\\mathbb{E}[X] + \\mu^2 \\\\\n&= \\mathbb{E}[X^2] - 2\\mu^2 + \\mu^2 \\\\\n&= \\mathbb{E}[X^2] - \\mu^2.\n\\end{align*}\n:::\n\nQuesta formulazione mostra che la varianza dipende esclusivamente da due **momenti** della distribuzione: il valore atteso $\\mathbb{E}[X]$ e il valore atteso del quadrato $\\mathbb{E}[X^2]$. In molti casi, questo rende il calcolo più semplice ed efficiente rispetto all'uso diretto degli scarti.\n\n::: {.callout-note collapse=\"true\" title=\"Esempio: varianza della somma di due dadi\"}\n\n**Calcolo con entrambe le formule**\n\nCalcoliamo la varianza della variabile casuale $X$ che rappresenta la somma di due dadi equilibrati.\n\n**Formula diretta**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nvalori <- 2:12\nprob <- c(1, 2, 3, 4, 5, 6, 5, 4, 3, 2, 1) / 36\nE_X <- sum(valori * prob)\nVar_diretta <- sum((valori - E_X)^2 * prob)\ncat(\"Varianza (formula diretta):\", Var_diretta, \"\\n\")\n#> Varianza (formula diretta): 5.83\n```\n:::\n\n\n**Formula alternativa**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nE_X2 <- sum(valori^2 * prob)\nVar_alternativa <- E_X2 - E_X^2\ncat(\"Varianza (formula alternativa):\", Var_alternativa, \"\\n\")\n#> Varianza (formula alternativa): 5.83\n```\n:::\n\n\nLe due formule producono lo stesso risultato, come atteso, ma la formula alternativa richiede solo il calcolo di due medie ponderate, senza dover calcolare esplicitamente tutti gli scarti dalla media.\n:::\n\n## Proprietà algebriche della varianza\n\nLa varianza possiede proprietà algebriche che, pur essendo simili a quelle del valore atteso, presentano differenze cruciali.\n\n### Trasformazioni lineari\n\nPer qualsiasi variabile casuale $X$ e per costanti $a$ e $b$:\n\n$$\n\\text{Var}(aX + b) = a^2 \\text{Var}(X).\n$$\n\n::: {.proof}\nSia $\\mu = \\mathbb{E}[X]$. Allora $\\mathbb{E}[aX + b] = a\\mu + b$ e quindi:\n\\begin{align*}\n\\text{Var}(aX + b)\n&= \\mathbb{E}[(aX + b - a\\mu - b)^2] \\\\\n&= \\mathbb{E}[a^2(X - \\mu)^2] \\\\\n&= a^2 \\mathbb{E}[(X - \\mu)^2] \\\\\n&= a^2 \\text{Var}(X).\n\\end{align*}\n:::\n\n**Osservazione cruciale**: una traslazione (addizione di una costante $b$) **non modifica** la varianza, poiché non altera la dispersione dei valori attorno alla media. La moltiplicazione per una costante $a$ amplifica o riduce la varianza proporzionalmente a $a^2$.\n\n### Additività della varianza per variabili indipendenti\n\nSe $X$ e $Y$ sono variabili casuali **indipendenti**, allora:\n\n$$\n\\text{Var}(X + Y) = \\text{Var}(X) + \\text{Var}(Y).\n$$\n\nA differenza dell'additività del valore atteso, che vale sempre, l'additività della varianza **richiede l'assenza di dipendenza**. In presenza di correlazione, la varianza della somma può essere maggiore o minore della somma delle varianze, a seconda del segno della covarianza.\n\n::: {.callout-note collapse=\"true\" title=\"Esempio: Varianza della somma vs varianza dei componenti\"}\n\n**Due dadi indipendenti**\n\nConsideriamo un singolo dado equilibrato. Il suo valore atteso e la sua varianza sono:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nvalori_dado <- 1:6\nprob_dado <- rep(1/6, 6)\n\nE_dado <- sum(valori_dado * prob_dado)\nE_dado2 <- sum(valori_dado^2 * prob_dado)\nVar_dado <- E_dado2 - E_dado^2\n\ncat(\"Singolo dado:\\n\")\n#> Singolo dado:\ncat(\"  E[D] =\", E_dado, \"\\n\")\n#>   E[D] = 3.5\ncat(\"  Var(D) =\", round(Var_dado, 4), \"\\n\")\n#>   Var(D) = 2.92\n```\n:::\n\n\nPer la somma $X = D_1 + D_2$ di due dadi indipendenti vale:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncat(\"\\nSomma di due dadi indipendenti:\\n\")\n#> \n#> Somma di due dadi indipendenti:\ncat(\"  E[X] = E[D₁] + E[D₂] =\", 2 * E_dado, \"\\n\")\n#>   E[X] = E[D₁] + E[D₂] = 7\ncat(\"  Var(X) = Var(D₁) + Var(D₂) =\", round(2 * Var_dado, 4), \"\\n\")\n#>   Var(X) = Var(D₁) + Var(D₂) = 5.83\n```\n:::\n\n\nLa varianza della somma è quindi circa $5.83$, esattamente il doppio della varianza di un singolo dado (circa $2.92$), come previsto dalla proprietà di additività per variabili indipendenti.\n:::\n\n### Varianza della media campionaria\n\nUn risultato di rilevanza diretta per l'inferenza statistica riguarda la **varianza della media campionaria**. Siano $X_1, X_2, \\ldots, X_n$ variabili casuali **indipendenti e identicamente distribuite** (i.i.d.) con\n\n$$\n\\mathbb{E}[X_i] = \\mu,\n\\qquad\n\\text{Var}(X_i) = \\sigma^2.\n$$\n\nLa media campionaria è definita come\n\n$$\n\\bar{X} = \\frac{1}{n}\\sum_{i=1}^{n} X_i.\n$$\n\nApplicando le proprietà della varianza, otteniamo:\n\n$$\n\\text{Var}(\\bar{X})\n= \\text{Var}\\left(\\frac{1}{n}\\sum_{i=1}^{n} X_i\\right)\n= \\frac{1}{n^2}\\,\\text{Var}\\left(\\sum_{i=1}^{n} X_i\\right).\n$$\n\nPoiché le variabili sono indipendenti, la varianza della somma è la somma delle varianze:\n\n$$\n\\text{Var}\\left(\\sum_{i=1}^{n} X_i\\right)\n= \\sum_{i=1}^{n} \\text{Var}(X_i)\n= n \\sigma^2.\n$$\n\nSostituendo, otteniamo:\n\n$$\n\\text{Var}(\\bar{X}) = \\frac{\\sigma^2}{n}.\n$$\n\n**Interpretazione**: La varianza della media campionaria decresce linearmente con $1/n$. Questo significa che raddoppiare la dimensione campionaria dimezza la varianza della media, rendendo le stime progressivamente più precise all'aumentare dei dati. Questo risultato costituisce il fondamento matematico dell'idea che \"più dati implicano maggiore precisione\".\n\n::: {.callout-note}\n### Approfondimento inferenziale\n\nLe proprietà della media campionaria qui derivate hanno implicazioni profonde per l'inferenza statistica e bayesiana. Nel @sec-prob-inference-uncertainty esamineremo in dettaglio come questi risultati si traducano operativamente nell'aggiornamento delle credenze e nella quantificazione dell'incertezza, introducendo concetti quali distribuzione campionaria, verosimiglianza ed errore standard.\n:::\n\n### Punto chiave da ricordare\n\n* La media campionaria conserva il valore atteso della popolazione: $\\mathbb{E}[\\bar{X}] = \\mu$.\n* La sua varianza decresce come $1/n$: $\\text{Var}(\\bar{X}) = \\sigma^2/n$.\n* Questi risultati sono alla base della precisione statistica e dell'apprendimento dall'esperienza.\n\n## Deviazione standard e standardizzazione\n\nLa varianza è definita come valore atteso degli scarti quadratici dalla media e, di conseguenza, ha come unità di misura il **quadrato** dell’unità della variabile originaria. Questa caratteristica, pur essendo matematicamente conveniente, rende la varianza meno immediata da interpretare sul piano pratico. Per riportare la dispersione sulla **stessa scala dei dati**, si introduce la *deviazione standard*.\n\n::: {#def-standard-deviation}\n\n### Deviazione standard\n\nLa *deviazione standard* di una variabile casuale $X$ è definita come\n$$\n\\sigma_X = \\text{SD}(X) = \\sqrt{\\text{Var}(X)}.\n$$\n:::\n\nLa deviazione standard misura la dispersione in unità direttamente confrontabili con i valori osservati. In termini intuitivi, essa rappresenta una “distanza tipica” dei valori dalla media. Per molte distribuzioni simmetriche e unimodali, una larga parte delle osservazioni si concentra entro una o due deviazioni standard dal valore atteso, rendendo questa misura particolarmente informativa.\n\n## Standardizzazione\n\nUn ulteriore passo concettualmente importante consiste nel trasformare una variabile casuale in una forma *standardizzata*, eliminando l’effetto della scala e della posizione.\n\n::: {#def-standardization}\n\n### Variabile standardizzata\n\nData una variabile casuale $X$ con valore atteso $\\mathbb{E}[X] = \\mu$ e deviazione standard $\\text{SD}(X) = \\sigma$, la *variabile standardizzata* è definita come\n\n$$\nZ = \\frac{X - \\mu}{\\sigma}.\n$$\n:::\n\nLa variabile standardizzata $Z$ ha sempre:\n\n$$\n\\mathbb{E}[Z] = 0,\n\\qquad\n\\text{Var}(Z) = 1,\n$$\nindipendentemente dalla distribuzione originaria di $X$. La standardizzazione esprime ogni osservazione in termini di **quante deviazioni standard** essa si discosta dalla media, fornendo una misura adimensionale della posizione relativa.\n\nQuesto procedimento è fondamentale per confrontare variabili misurate su scale diverse e per interpretare i valori in modo comparabile, sia in ambito descrittivo sia inferenziale.\n\n::: {.callout-note collapse=\"true\" title=\"Esempio: standardizzazione dei punteggi di QI\"}\n\n**Confronto tra scale diverse**\n\nI punteggi di quoziente intellettivo (QI) sono tradizionalmente costruiti con media $\\mu = 100$ e deviazione standard $\\sigma = 15$. Un punteggio di 130 corrisponde a:\n\n$$\nz = \\frac{130 - 100}{15} = 2.0,\n$$\novvero a 2 deviazioni standard sopra la media.\n\nSupponiamo ora un altro test cognitivo con media $\\mu = 50$ e deviazione standard $\\sigma = 10$. Il punteggio che occupa la **stessa posizione relativa** nella distribuzione è:\n\n$$\nx = \\mu + z \\cdot \\sigma = 50 + 2.0 \\times 10 = 70.\n$$\n\nLa standardizzazione consente quindi di tradurre i punteggi tra scale diverse preservandone il significato relativo, rendendo possibile un confronto diretto tra misure apparentemente eterogenee.\n:::\n\n### Significato concettuale\n\nDeviazione standard e standardizzazione completano il quadro iniziato con valore atteso e varianza. Se il valore atteso individua il centro della distribuzione e la varianza quantifica la dispersione complessiva, la deviazione standard rende tale dispersione interpretabile nella scala dei dati, mentre la standardizzazione permette di confrontare distribuzioni diverse su una base comune.\n\n::: {.callout-note collapse=\"true\" title=\"Approfondimento: il teorema di Chebyshev\"}\n\nUna domanda naturale è: **quanto della distribuzione cade entro un certo numero di deviazioni standard dalla media?**  \nIl *teorema di Chebyshev* fornisce una risposta estremamente generale, valida per **qualsiasi distribuzione**, indipendentemente dalla sua forma.\n\n::: {#thm-chebyshev}\n**Teorema di Chebyshev**\n\nPer qualsiasi variabile casuale $X$ con media $\\mu$ e deviazione standard $\\sigma$, e per ogni $k > 0$ vale:\n\n$$\nP(|X - \\mu| \\geq k\\sigma) \\leq \\frac{1}{k^2}.\n$$\n\nEquivalentemente:\n\n$$\nP(|X - \\mu| < k\\sigma) \\geq 1 - \\frac{1}{k^2}.\n$$\n:::\n\nIl teorema fornisce quindi un **limite inferiore garantito** alla probabilità che una variabile cada entro $k$ deviazioni standard dalla media:\n\n| $k$ | $P(|X - \\mu| < k\\sigma) \\geq$ |\n|:---:|:------------------------------:|\n| 1   | 0% (limite triviale)           |\n| 2   | 75%                            |\n| 3   | 89%                            |\n| 4   | 94%                            |\n\nQuesti limiti sono **molto conservativi**. Per molte distribuzioni di interesse pratico (in particolare la distribuzione normale), le probabilità effettive sono significativamente più alte. Tuttavia, il teorema di Chebyshev ha un valore concettuale importante: **fornisce garanzie minime senza assumere nulla sulla forma della distribuzione**.\n\n**Esempio applicativo**\n\nUn test psicometrico ha media 100 e deviazione standard 15. Anche senza conoscere la distribuzione esatta dei punteggi, possiamo affermare che **almeno il 75%** delle osservazioni cade nell’intervallo:\n\n$$\n[100 - 2 \\times 15,\\; 100 + 2 \\times 15] = [70,\\;130].\n$$\n\nSe la distribuzione fosse normale, la proporzione reale sarebbe circa il 95%, ma il teorema di Chebyshev ci fornisce una **garanzia universale** che vale anche nei casi peggiori.\n:::\n\n::: {.callout-note collapse=\"true\" title=\"Approfondimento: i momenti di una distribuzione\"}\n\n**Momenti di una distribuzione**\n\nIl valore atteso e la varianza possono essere visti come i primi due **momenti** di una distribuzione, ovvero una famiglia di quantità che descrivono in modo sistematico la forma della distribuzione.\n\n::: {#def-moments}\n**Momenti**\n\nIl *momento di ordine* $r$ di una variabile casuale $X$ è definito come:\n$$\n\\mathbb{E}[X^r] =\n\\begin{cases}\n\\sum_i x_i^r \\cdot p_X(x_i) & \\text{(caso discreto)} \\\\\n\\int_{-\\infty}^{+\\infty} x^r \\cdot f_X(x)\\,dx & \\text{(caso continuo)}\n\\end{cases}\n$$\n\nIl *momento centrale di ordine* $r$ è invece:\n$$\n\\mathbb{E}[(X - \\mu)^r],\n$$\ndove $\\mu = \\mathbb{E}[X]$.\n:::\n\n- Il **momento di ordine 1** è il valore atteso.\n- Il **momento centrale di ordine 2** è la varianza.\n- I momenti centrali di ordine superiore descrivono aspetti più fini della distribuzione.\n\nIn particolare:\n\n- il **terzo momento centrale**, opportunamente normalizzato, misura l’**asimmetria** (*skewness*);\n- il **quarto momento centrale** misura la **curtosi**, cioè quanto la distribuzione è più o meno “concentrata” e con code più o meno pesanti rispetto alla distribuzione normale.\n\nQuesti concetti diventano rilevanti nello studio delle famiglie parametriche di distribuzioni (in particolare la normale) e nell’analisi della forma dei dati, ma per molti scopi applicativi il valore atteso e la varianza costituiscono già una descrizione estremamente informativa.\n:::\n\n## Riflessioni conclusive {.unnumbered .unlisted}\n\nIl **valore atteso** e la **varianza** costituiscono gli strumenti fondamentali per sintetizzare una distribuzione di probabilità. Il valore atteso individua il centro della distribuzione, ovvero il suo *baricentro probabilistico*, mentre la varianza misura la dispersione dei valori attorno a tale centro, quantificando il grado di incertezza associato alla variabile casuale.\n\nLe proprietà algebriche di queste quantità ne spiegano la centralità operativa. La **linearità del valore atteso** consente di calcolare in modo semplice le medie di trasformazioni e somme di variabili casuali, mentre il comportamento della **varianza** mette in evidenza il ruolo cruciale dell’indipendenza: solo in assenza di dipendenza la dispersione di una somma è la somma delle dispersioni. In particolare, il risultato secondo cui la varianza della media campionaria decresce come $1/n$ fornisce il fondamento matematico della precisione statistica e chiarisce perché l’accumulo di osservazioni rende le stime progressivamente più affidabili.\n\nQuesti concetti non sono soltanto strumenti descrittivi, ma assumono un significato pienamente **inferenziale** nel quadro bayesiano. Nei capitoli successivi, dedicati allo studio di famiglie parametriche di distribuzioni (Beta, Normale, Poisson e Binomiale) e alla costruzione dell’apparato formale dell’inferenza bayesiana, il valore atteso della distribuzione *a posteriori* fungerà da **stima puntuale razionale** del parametro di interesse, mentre la varianza *a posteriori* fornirà una misura quantitativa dell’incertezza residua dopo l’osservazione dei dati.\n\nIn questo senso, valore atteso e varianza rappresentano il punto di incontro tra probabilità, decisione e apprendimento: sintetizzano ciò che sappiamo, guidano le previsioni ottimali e rendono misurabile quanto resta ancora incerto.\n\n::: {.callout-note collapse=true title=\"Informazioni sull'ambiente di sviluppo\"}\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsessionInfo()\n#> R version 4.5.2 (2025-10-31)\n#> Platform: aarch64-apple-darwin20\n#> Running under: macOS Tahoe 26.2\n#> \n#> Matrix products: default\n#> BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib \n#> LAPACK: /Library/Frameworks/R.framework/Versions/4.5-arm64/Resources/lib/libRlapack.dylib;  LAPACK version 3.12.1\n#> \n#> locale:\n#> [1] C.UTF-8/UTF-8/C.UTF-8/C/C.UTF-8/C.UTF-8\n#> \n#> time zone: Europe/Rome\n#> tzcode source: internal\n#> \n#> attached base packages:\n#> [1] stats     graphics  grDevices utils     datasets  methods   base     \n#> \n#> other attached packages:\n#>  [1] pillar_1.11.1         tinytable_0.15.2      patchwork_1.3.2      \n#>  [4] ggdist_3.3.3          tidybayes_3.0.7       bayesplot_1.15.0     \n#>  [7] ggplot2_4.0.1         reliabilitydiag_0.2.1 priorsense_1.2.0     \n#> [10] posterior_1.6.1       loo_2.9.0             rstan_2.32.7         \n#> [13] StanHeaders_2.32.10   brms_2.23.0           Rcpp_1.1.0           \n#> [16] sessioninfo_1.2.3     conflicted_1.2.0      janitor_2.2.1        \n#> [19] matrixStats_1.5.0     modelr_0.1.11         tibble_3.3.0         \n#> [22] dplyr_1.1.4           tidyr_1.3.2           rio_1.2.4            \n#> [25] here_1.0.2           \n#> \n#> loaded via a namespace (and not attached):\n#>  [1] svUnit_1.0.8          tidyselect_1.2.1      farver_2.1.2         \n#>  [4] S7_0.2.1              fastmap_1.2.0         TH.data_1.1-5        \n#>  [7] tensorA_0.36.2.1      pacman_0.5.1          digest_0.6.39        \n#> [10] timechange_0.3.0      estimability_1.5.1    lifecycle_1.0.4      \n#> [13] survival_3.8-3        magrittr_2.0.4        compiler_4.5.2       \n#> [16] rlang_1.1.6           tools_4.5.2           yaml_2.3.12          \n#> [19] knitr_1.51            bridgesampling_1.2-1  htmlwidgets_1.6.4    \n#> [22] curl_7.0.0            pkgbuild_1.4.8        RColorBrewer_1.1-3   \n#> [25] abind_1.4-8           multcomp_1.4-29       withr_3.0.2          \n#> [28] purrr_1.2.0           grid_4.5.2            stats4_4.5.2         \n#> [31] colorspace_2.1-2      xtable_1.8-4          inline_0.3.21        \n#> [34] emmeans_2.0.1         scales_1.4.0          MASS_7.3-65          \n#> [37] cli_3.6.5             mvtnorm_1.3-3         rmarkdown_2.30       \n#> [40] ragg_1.5.0            generics_0.1.4        otel_0.2.0           \n#> [43] RcppParallel_5.1.11-1 cachem_1.1.0          stringr_1.6.0        \n#> [46] splines_4.5.2         parallel_4.5.2        vctrs_0.6.5          \n#> [49] V8_8.0.1              Matrix_1.7-4          sandwich_3.1-1       \n#> [52] jsonlite_2.0.0        arrayhelpers_1.1-0    systemfonts_1.3.1    \n#> [55] glue_1.8.0            codetools_0.2-20      distributional_0.5.0 \n#> [58] lubridate_1.9.4       stringi_1.8.7         gtable_0.3.6         \n#> [61] QuickJSR_1.8.1        htmltools_0.5.9       Brobdingnag_1.2-9    \n#> [64] R6_2.6.1              textshaping_1.0.4     rprojroot_2.1.1      \n#> [67] evaluate_1.0.5        lattice_0.22-7        backports_1.5.0      \n#> [70] memoise_2.0.1         broom_1.0.11          snakecase_0.11.1     \n#> [73] rstantools_2.5.0      gridExtra_2.3         coda_0.19-4.1        \n#> [76] nlme_3.1-168          checkmate_2.3.3       xfun_0.55            \n#> [79] zoo_1.8-15            pkgconfig_2.0.3\n```\n:::\n\n:::\n\n\n## Bibliografia {.unnumbered .unlisted}\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}