{
  "hash": "8c0e65e77dfec32f212ccf4699d746d4",
  "result": {
    "engine": "knitr",
    "markdown": "# Proprietà delle variabili casuali {#sec-prob-random-var-properties}\n\n## Introduzione {.unnumbered .unlisted}\n\nNel @sec-prob-random-var abbiamo introdotto le variabili casuali come funzioni che traducono gli esiti di un esperimento aleatorio in valori numerici. Abbiamo visto come la funzione di massa di probabilità (PMF) e la funzione di densità di probabilità (PDF) descrivano la distribuzione della probabilità sui possibili valori. Queste descrizioni sono complete, ma per molti scopi pratici sono eccessivamente dettagliate.\n\nPensiamo a uno psicologo che deve comunicare a un paziente l'esito atteso di un trattamento o a un ricercatore che deve confrontare l'efficacia di due interventi. In questi contesti, non è necessario conoscere l'intera distribuzione, ma bastano pochi numeri riassuntivi che ne catturino le caratteristiche essenziali. Quali sono i valori \"tipici\"? Quanto è ampia la variabilità attorno a questi valori?\n\nQuesto capitolo introduce i due indicatori fondamentali che rispondono a queste domande: il *valore atteso*, che localizza il \"centro di gravità\" della distribuzione, e la *varianza*, che ne misura la dispersione. Questi concetti non sono mere convenzioni descrittive, ma hanno profonde connessioni con la teoria delle decisioni e con l'inferenza bayesiana. Il valore atteso, in particolare, emerge naturalmente come la previsione ottimale sotto una perdita quadratica, un risultato che rende questi strumenti centrali per l'intera statistica.\n\n### Panoramica del capitolo {.unnumbered .unlisted}\n\n- Il valore atteso come media ponderata e centro di massa probabilistico.\n- Proprietà algebriche del valore atteso: linearità e additività.\n- La varianza come misura della dispersione attorno al valore atteso.\n- Proprietà della varianza e formula computazionale alternativa.\n- Deviazione standard e standardizzazione.\n- Il teorema di Chebyshev e i momenti di una distribuzione.\n\n::: {.callout-tip collapse=true}\n## Prerequisiti\n\n- Aver letto i capitoli @sec-prob-interpretation, @sec-prob-axioms-coherence e @sec-bayes-theorem.\n- Leggere l'appendice @sec-apx-calculus per i concetti base di calcolo integrale.\n- Familiarità con R e le operazioni vettoriali di base.\n:::\n\n::: {.callout-caution collapse=true title=\"Preparazione del Notebook\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhere::here(\"code\", \"_common.R\") |> \n  source()\n\n# Pacchetti necessari\nif (!requireNamespace(\"pacman\")) install.packages(\"pacman\")\npacman::p_load(ggplot2, dplyr, tidyr)\n```\n:::\n\n:::\n\n## Il valore atteso come centro di gravità\n\nIl *valore atteso* di una variabile casuale rappresenta il suo baricentro  probabilistico, ovvero il valore medio che ci si aspetta di osservare in una lunga serie di replicazioni dell'esperimento.  Nell'interpretazione bayesiana, il valore atteso formalizza matematicamente la nostra *aspettativa razionale* alla luce dell'attuale stato di informazione.\n\n::: {#def-expected-value}\n### Valore atteso (Speranza Matematica)\n\nIl *valore atteso* (o *media* o *speranza matematica*) di una variabile casuale $X$ è definito come:\n\nPer variabili **discrete** con funzione di massa di probabilità $p_X$:\n$$\n\\mathbb{E}[X] = \\sum_{x \\in \\mathcal{X}} x \\cdot p_X(x).\n$$\n\nPer variabili **continue** con funzione di densità di probabilità $f_X$:\n$$\n\\mathbb{E}[X] = \\int_{-\\infty}^{+\\infty} x \\cdot f_X(x)  dx.\n$$\n:::\n\nConcettualmente, il valore atteso costituisce una *media ponderata* dei possibili valori della variabile, dove i pesi sono rappresentati dalle rispettive probabilità (nel caso discreto) o densità di probabilità (nel caso continuo). Si noti che il valore atteso non coincide necessariamente con un valore che la variabile può assumere: per la somma di due dadi, $\\mathbb{E}[X] = 7$ è un valore possibile; per un dado singolo, $\\mathbb{E}[X] = 3.5$ non lo è.\n\n::: {.callout-note collapse=\"true\" title=\"Esercizio\"}\n\nCalcoliamo il valore atteso della variabile casuale $X$ corrispondente al lancio di una moneta equilibrata, dove *testa* corrisponde a $X = 1$ e *croce* corrisponde a $X = 0$:\n\n$$\n\\mathbb{E}(X) = \\sum_{i=1}^{2} x_i \\cdot P(x_i) = 0 \\cdot \\frac{1}{2} + 1 \\cdot \\frac{1}{2} = 0.5.\n$$\nSi noti che 0.5 non è un valore che $X$ può effettivamente assumere, la moneta mostra sempre 0 o 1, mai 0.5. Eppure, 0.5 rappresenta correttamente il \"centro\" della distribuzione: è il punto di equilibrio tra i due esiti possibili.\n:::\n\n### Il valore atteso come limite di frequenze\n\nL'interpretazione operativa più intuitiva del valore atteso emerge dalla *legge dei grandi numeri*: se ripetiamo un esperimento molte volte e calcoliamo la media aritmetica dei risultati, questa media tende al valore atteso teorico.\n\nFormalmente, se $X_1, X_2, \\ldots, X_n$ sono realizzazioni indipendenti della stessa variabile casuale $X$, allora:\n$$\n\\bar{X}_n = \\frac{X_1 + X_2 + \\cdots + X_n}{n} \\xrightarrow{n \\to \\infty} \\mathbb{E}[X].\n$$\n\nQuesta proprietà di convergenza non definisce il valore atteso, la cui definizione assiomatica rimane quella di media ponderata, ma ne fornisce una giustificazione empirica e un'interpretazione operativa. Il valore atteso rappresenta quindi il limite a cui tende la media empirica in un processo di campionamento ripetuto e costituisce il valore che \"ci aspettiamo\" di osservare come media a lungo termine.\n\n::: {.callout-note collapse=\"true\" title=\"Esercizio: valore atteso del lancio di due dadi\"}\n#### Verifica della convergenza {.unnumbered .unlisted}\n\nPer la variabile $X$ che rappresenta la somma di due dadi equilibrati, abbiamo già calcolato la PMF nel @sec-prob-random-var:\n\n$$\nP(X) = \\left\\{\\frac{1}{36}, \\frac{2}{36}, \\frac{3}{36}, \\frac{4}{36}, \\frac{5}{36}, \\frac{6}{36}, \\frac{5}{36}, \\frac{4}{36}, \\frac{3}{36}, \\frac{2}{36}, \\frac{1}{36}\\right\\}.\n$$\n\nIl valore atteso $\\mathbb{E}[X]$ è:\n\n$$\n\\mathbb{E}[X] = 2 \\cdot \\frac{1}{36} + 3 \\cdot \\frac{2}{36} + 4 \\cdot \\frac{3}{36} + \\cdots + 12 \\cdot \\frac{1}{36} = 7.\n$$\n\nVerifichiamo con una simulazione:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(123)\n\n# Calcolo teorico\nvalori <- 2:12\nprob <- c(1, 2, 3, 4, 5, 6, 5, 4, 3, 2, 1) / 36\nE_teorico <- sum(valori * prob)\ncat(\"Valore atteso teorico:\", E_teorico, \"\\n\")\n#> Valore atteso teorico: 7\n\n# Verifica empirica con simulazione\nn_sim <- 1000000\nsomme <- sample(1:6, n_sim, replace = TRUE) + sample(1:6, n_sim, replace = TRUE)\nE_empirico <- mean(somme)\ncat(\"Media empirica (n =\", format(n_sim, big.mark = \",\"), \"):\", E_empirico, \"\\n\")\n#> Media empirica (n = 1,000,000 ): 7\n```\n:::\n\n\nLa convergenza della media empirica al valore teorico 7 illustra la legge dei grandi numeri in azione.\n:::\n\n### Un calcolo più efficiente: il principio di linearità\n\nPer determinare il valore atteso della somma di due dadi, esiste un approccio più efficiente ed elegante rispetto al calcolo diretto. Siano $D_1$ e $D_2$ le variabili casuali che rappresentano i risultati dei due dadi. Poiché $X = D_1 + D_2$, possiamo applicare la proprietà di *linearità del valore atteso*:\n$$\n\\mathbb{E}[X] = \\mathbb{E}[D_1 + D_2] = \\mathbb{E}[D_1] + \\mathbb{E}[D_2].\n$$\n\nSapendo che il valore atteso del lancio di un singolo dado è $\\mathbb{E}[D_i] = 3.5$, otteniamo immediatamente:\n$$\n\\mathbb{E}[X] = 3.5 + 3.5 = 7.\n$$\n\nQuesto metodo di calcolo non solo è considerevolmente più semplice della somma ponderata diretta, ma mette anche in luce una proprietà algebrica fondamentale del valore atteso, la sua linearità, che esploreremo nelle sezioni successive.\n\n## Proprietà del valore atteso\n\nIl valore atteso gode di proprietà algebriche che ne rendono il calcolo spesso sorprendentemente semplice. Queste proprietà sono conseguenze dirette della definizione e valgono per qualsiasi variabile casuale.\n\n::: {#thm-expected-value-linearity}\n### Linearità del valore atteso\n\nPer qualsiasi variabile casuale $X$ e costanti $a, b \\in \\mathbb{R}$:\n$$\n\\mathbb{E}[aX + b] = a\\mathbb{E}[X] + b.\n$$\n:::\n\nLa linearità afferma che traslazioni e riscalamenti operano in modo prevedibile sulla media. Se moltiplichiamo tutti i valori per una costante $a$, la media viene moltiplicata per $a$; se aggiungiamo una costante $b$ a tutti i valori, la media aumenta di $b$.\n\n::: {#thm-expected-value-additivity}\n### Additività del valore atteso\n\nPer qualsiasi coppia di variabili casuali $X$ e $Y$:\n$$\n\\mathbb{E}[X + Y] = \\mathbb{E}[X] + \\mathbb{E}[Y].\n$$\nQuesta proprietà è valida sempre, a prescindere dal fatto che $X$ e $Y$ siano dipendenti o indipendenti.\n:::\n\nL'additività è particolarmente notevole: il valore atteso di una somma è *sempre* la somma dei valori attesi, anche quando le variabili sono correlate. Questa proprietà semplifica notevolmente i calcoli. Per $n$ variabili casuali:\n$$\n\\mathbb{E}\\left[\\sum_{i=1}^{n} X_i\\right] = \\sum_{i=1}^{n} \\mathbb{E}[X_i].\n$$\n\n::: {#thm-expected-value-product}\n### Prodotto di variabili indipendenti\n\nSe $X$ e $Y$ sono variabili casuali **indipendenti**, allora:\n$$\n\\mathbb{E}[XY] = \\mathbb{E}[X] \\cdot \\mathbb{E}[Y].\n$$\nQuesta proprietà **non** vale in generale per le variabili dipendenti.\n:::\n\n::: {.callout-note collapse=\"true\" title=\"Esempio: Dado e moneta\"}\n### Applicazione della linearità\n\nConsideriamo l'esperimento di lanciare un dado ($Y$, valori 1-6) e una moneta ($X$, valori 0-1). Vogliamo calcolare $\\mathbb{E}[X + Y]$.\n\nIl modo diretto richiede di costruire lo spazio campionario completo (12 esiti) e calcolare la media ponderata. Ma usando l'additività:\n$$\n\\mathbb{E}[X + Y] = \\mathbb{E}[X] + \\mathbb{E}[Y] = 0.5 + 3.5 = 4.0.\n$$\n\nVerifichiamo:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Costruzione dello spazio campionario\ncoin <- c(0, 1)\ndie <- 1:6\nsample_space <- expand.grid(X = coin, Y = die)\nsample_space$sum <- sample_space$X + sample_space$Y\n\n# Calcolo diretto (ogni esito ha prob. 1/12)\nE_diretto <- mean(sample_space$sum)\n\n# Calcolo via linearità\nE_lineare <- 0.5 + 3.5\n\ncat(\"Calcolo diretto:\", E_diretto, \"\\n\")\n#> Calcolo diretto: 4\ncat(\"Calcolo via linearità:\", E_lineare, \"\\n\")\n#> Calcolo via linearità: 4\n```\n:::\n\n:::\n\n### Valore atteso della media campionaria\n\nUna conseguenza importante della linearità riguarda la media aritmetica di $n$ osservazioni indipendenti dalla stessa distribuzione. Se $X_1, \\ldots, X_n$ sono variabili casuali indipendenti e identicamente distribuite (i.i.d.) con $\\mathbb{E}[X_i] = \\mu$, allora la media campionaria:\n\n$$\n\\bar{X} = \\frac{1}{n}\\sum_{i=1}^{n} X_i\n$$\nha valore atteso:\n$$\n\\mathbb{E}[\\bar{X}] = \\frac{1}{n}\\sum_{i=1}^{n} \\mathbb{E}[X_i] = \\frac{1}{n} \\cdot n \\cdot \\mu = \\mu.\n$$\n\nQuesto risultato afferma che la media campionaria è uno stimatore *non distorto* del valore atteso della popolazione, una proprietà fondamentale per l'inferenza statistica.\n\n## La varianza come misura di dispersione\n\nIl valore atteso localizza il centro della distribuzione, ma non fornisce informazioni sulla dispersione dei valori attorno a questo centro. Due distribuzioni possono avere lo stesso valore atteso, ma comportamenti molto diversi: una può essere concentrata, l'altra molto sparsa.\n\nPer quantificare la dispersione, consideriamo la variabile casuale $X - \\mathbb{E}[X]$, detta *scarto* o *deviazione* dalla media. Gli scarti possono essere positivi o negativi, e il loro valore atteso è sempre zero (per definizione di $\\mathbb{E}[X]$). Per ottenere una misura di dispersione non nulla, si elevano gli scarti al quadrato.\n\n::: {#def-}\n### Varianza\n\nLa *varianza* di una variabile casuale $X$ è il valore atteso degli scarti quadratici dalla media:\n$$\n\\text{Var}(X) = \\mathbb{E}\\left[(X - \\mathbb{E}[X])^2\\right].\n$$\n\nEquivalentemente, per $\\mu = \\mathbb{E}[X]$:\n\n- **Caso discreto**: $\\text{Var}(X) = \\sum_i (x_i - \\mu)^2 \\cdot p_X(x_i)$\n- **Caso continuo**: $\\text{Var}(X) = \\int_{-\\infty}^{+\\infty} (x - \\mu)^2 \\cdot f_X(x) \\, dx$\n:::\n\nLa varianza gode della proprietà di non-negatività, ossia $\\text{Var}(X) \\geq 0$ per ogni variabile casuale $X$, con uguaglianza che si verifica se e solo se $X$ è una costante. Valori elevati di varianza indicano una rilevante dispersione dei valori attorno alla media e riflettono un'elevata incertezza nella previsione dei risultati. Al contrario, valori piccoli di varianza indicano che la distribuzione è fortemente concentrata intorno al valore atteso, a indicare una minore variabilità del fenomeno aleatorio.\n\nEsiste una formula equivalente per la varianza che spesso semplifica i calcoli:\n\n::: {#thm-variance-formula}\n### Formula alternativa della varianza\n\n$$\n\\text{Var}(X) = \\mathbb{E}[X^2] - (\\mathbb{E}[X])^2.\n$$\n:::\n\n::: {.proof}\nEspandiamo la definizione:\n\\begin{align}\n\\text{Var}(X) &= \\mathbb{E}[(X - \\mu)^2] \\\\\n&= \\mathbb{E}[X^2 - 2\\mu X + \\mu^2] \\\\\n&= \\mathbb{E}[X^2] - 2\\mu\\mathbb{E}[X] + \\mu^2 \\\\\n&= \\mathbb{E}[X^2] - 2\\mu^2 + \\mu^2 \\\\\n&= \\mathbb{E}[X^2] - \\mu^2.\n\\end{align}\n:::\n\nQuesta formulazione richiede esclusivamente la determinazione di due momenti: il valore atteso della variabile $\\mathbb{E}[X]$ e il valore atteso del suo quadrato $\\mathbb{E}[X^2]$, escludendo così la necessità di calcolare gli scostamenti $(X - \\mathbb{E}[X])^2$ per ogni possibile valore della variabile.\n\n::: {.callout-note collapse=\"true\" title=\"Esempio: Varianza della somma di due dadi\"}\n### Calcolo con entrambe le formule\n\nCalcoliamo la varianza della somma $X$ di due dadi usando entrambe le formule.\n\n**Formula diretta** (definizione):\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nvalori <- 2:12\nprob <- c(1, 2, 3, 4, 5, 6, 5, 4, 3, 2, 1) / 36\n\nE_X <- sum(valori * prob)\nvar_diretta <- sum((valori - E_X)^2 * prob)\n\ncat(\"Valore atteso:\", E_X, \"\\n\")\n#> Valore atteso: 7\ncat(\"Varianza (formula diretta):\", round(var_diretta, 4), \"\\n\")\n#> Varianza (formula diretta): 5.83\n```\n:::\n\n\n**Formula alternativa** ($\\mathbb{E}[X^2] - (\\mathbb{E}[X])^2$):\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nE_X2 <- sum(valori^2 * prob)\nvar_alternativa <- E_X2 - E_X^2\n\ncat(\"E[X²]:\", E_X2, \"\\n\")\n#> E[X²]: 54.8\ncat(\"Varianza (formula alternativa):\", round(var_alternativa, 4), \"\\n\")\n#> Varianza (formula alternativa): 5.83\n```\n:::\n\n\nEntrambe le formule producono lo stesso risultato: $\\text{Var}(X) \\approx 5.83$.\n:::\n\n## Proprietà della varianza\n\nLe proprietà della varianza differiscono significativamente da quelle del valore atteso, riflettendo la natura non lineare dell'elevamento al quadrato.\n\n::: {#thm-variance-properties}\n### Proprietà della varianza\n\n1. **Non negatività**: $\\text{Var}(X) \\geq 0$, con uguaglianza se e solo se $X$ è costante.\n\n2. **Invarianza per traslazioni**: $\\text{Var}(X + b) = \\text{Var}(X)$ per qualsiasi costante $b$.\n\n3. **Scaling quadratico**: $\\text{Var}(aX) = a^2 \\text{Var}(X)$ per qualsiasi costante $a$.\n\n4. **Combinando**: $\\text{Var}(aX + b) = a^2 \\text{Var}(X)$.\n:::\n\nL'invarianza per traslazioni ha senso intuitivo: aggiungere una costante a tutti i valori sposta il centro della distribuzione ma non ne modifica la dispersione. Lo scaling quadratico riflette il fatto che la varianza è definita in termini di scarti *quadratici*.\n\n### Varianza di somme di variabili\n\nLa proprietà più importante, in cui la varianza si comporta in modo diverso dal valore atteso, riguarda le somme.\n\n::: {#thm-variance-sum}\n### Varianza di una somma\n\nPer due variabili casuali $X$ e $Y$:\n$$\n\\text{Var}(X + Y) = \\text{Var}(X) + \\text{Var}(Y) + 2\\text{Cov}(X, Y),\n$$\ndove $\\text{Cov}(X, Y) = \\mathbb{E}[XY] - \\mathbb{E}[X]\\mathbb{E}[Y]$ è la *covarianza*.\n\nSe $X$ e $Y$ sono **indipendenti** (o anche solo incorrelate), allora $\\text{Cov}(X, Y) = 0$ e:\n$$\n\\text{Var}(X + Y) = \\text{Var}(X) + \\text{Var}(Y).\n$$\n:::\n\nA differenza dell'additività del valore atteso, che vale sempre, l'additività della varianza richiede l'indipendenza. Per variabili dipendenti, la varianza della somma può essere maggiore o minore della somma delle varianze, a seconda del segno della covarianza.\n\n::: {.callout-note collapse=\"true\" title=\"Esempio: Varianza della somma vs varianza dei componenti\"}\n### Due dadi indipendenti\n\nPer un singolo dado equilibrato, calcoliamo valore atteso e varianza:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nvalori_dado <- 1:6\nprob_dado <- rep(1/6, 6)\n\nE_dado <- sum(valori_dado * prob_dado)\nE_dado2 <- sum(valori_dado^2 * prob_dado)\nVar_dado <- E_dado2 - E_dado^2\n\ncat(\"Singolo dado:\\n\")\n#> Singolo dado:\ncat(\"  E[D] =\", E_dado, \"\\n\")\n#>   E[D] = 3.5\ncat(\"  Var(D) =\", round(Var_dado, 4), \"\\n\")\n#>   Var(D) = 2.92\n```\n:::\n\n\nPer la somma $X = D_1 + D_2$ di due dadi indipendenti:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncat(\"\\nSomma di due dadi indipendenti:\\n\")\n#> \n#> Somma di due dadi indipendenti:\ncat(\"  E[X] = E[D₁] + E[D₂] =\", 2 * E_dado, \"\\n\")\n#>   E[X] = E[D₁] + E[D₂] = 7\ncat(\"  Var(X) = Var(D₁) + Var(D₂) =\", round(2 * Var_dado, 4), \"\\n\")\n#>   Var(X) = Var(D₁) + Var(D₂) = 5.83\n```\n:::\n\n\nNotiamo che la varianza della somma (≈ 5.83) è esattamente il doppio della varianza di un singolo dado (≈ 2.92), come previsto dalla proprietà di additività per variabili indipendenti.\n:::\n\n### Varianza della media campionaria\n\nUn risultato cruciale per l'inferenza statistica riguarda la varianza della media campionaria. Se $X_1, \\ldots, X_n$ sono i.i.d. con varianza $\\sigma^2$, allora:\n$$\n\\text{Var}(\\bar{X}) = \\text{Var}\\left(\\frac{1}{n}\\sum_{i=1}^{n} X_i\\right) = \\frac{1}{n^2} \\cdot n \\cdot \\sigma^2 = \\frac{\\sigma^2}{n}.\n$$\n\nQuesto risultato fondamentale afferma che la varianza della media campionaria *decresce* con il numero di osservazioni, al tasso $1/n$. Questo è il fondamento matematico del fatto che i campioni più grandi producono stime più precise.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(456)\n\n# Popolazione: normale con media 50 e sd 10\npop_var <- 100\n\n# Calcola varianza empirica delle medie per diversi n\nsample_sizes <- c(5, 10, 20, 50, 100, 200)\nn_rep <- 10000\n\nvar_empiriche <- sapply(sample_sizes, function(n) {\n  medie <- replicate(n_rep, mean(rnorm(n, mean = 50, sd = 10)))\n  var(medie)\n})\n\nvar_teoriche <- pop_var / sample_sizes\n\ndf <- data.frame(\n  n = sample_sizes,\n  empirica = var_empiriche,\n  teorica = var_teoriche\n)\n\nggplot(df, aes(x = n)) +\n  geom_line(aes(y = teorica), color = \"darkred\", linewidth = 1) +\n  geom_point(aes(y = empirica), color = \"steelblue\", size = 3) +\n  scale_x_continuous(breaks = sample_sizes) +\n  labs(x = \"Dimensione campionaria (n)\", \n       y = expression(Var(bar(X)))) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![La varianza della media campionaria decresce come 1/n. La simulazione (punti) conferma la previsione teorica (linea).](08_expval_var_files/figure-pdf/fig-variance-sample-mean-1.png){#fig-variance-sample-mean fig-align='center' fig-pos='H' width=85%}\n:::\n:::\n\n\n## Deviazione standard e standardizzazione\n\nLa varianza, essendo definita in termini di scarti quadratici, ha come unità di misura il quadrato dell'unità della variabile originaria. Per ottenere una misura di dispersione nella stessa scala dei dati, si usa la *deviazione standard*.\n\n::: {#def-standard-deviation}\n### Deviazione standard\n\nLa *deviazione standard* di una variabile casuale $X$ è:\n$$\n\\sigma_X = \\text{SD}(X) = \\sqrt{\\text{Var}(X)}.\n$$\n:::\n\nLa deviazione standard rappresenta, approssimativamente, la \"distanza tipica\" di un valore dalla media. Per molte distribuzioni simmetriche e unimodali, la maggior parte dei valori si colloca entro una o due deviazioni standard dalla media.\n\n### Standardizzazione\n\nQualsiasi variabile casuale può essere standardizzata sottraendo la media e dividendo il risultato per la deviazione standard.\n\n::: {#def-standardization}\n### Variabile standardizzata\n\nData una variabile casuale $X$ con $\\mathbb{E}[X] = \\mu$ e $\\text{SD}(X) = \\sigma$, la *variabile standardizzata* è:\n$$\nZ = \\frac{X - \\mu}{\\sigma}.\n$$\n:::\n\nLa variabile standardizzata $Z$ ha sempre $\\mathbb{E}[Z] = 0$ e $\\text{Var}(Z) = 1$, indipendentemente dalla distribuzione originaria di $X$. Questo processo permette di confrontare variabili misurate su scale diverse e di esprimere ogni valore in termini di \"quante deviazioni standard\" esso disti dalla media.\n\n::: {.callout-note collapse=\"true\" title=\"Esempio: Standardizzazione dei punteggi QI\"}\n### Confronto tra scale diverse\n\nIl QI ha tradizionalmente $\\mu = 100$ e $\\sigma = 15$. Un punteggio di 130 corrisponde a:\n$$\nz = \\frac{130 - 100}{15} = 2.0\n$$\n\novvero 2 deviazioni standard sopra la media.\n\nSe un altro test cognitivo ha $\\mu = 50$ e $\\sigma = 10$, quale punteggio corrisponde allo stesso livello relativo?\n$$\nx = \\mu + z \\cdot \\sigma = 50 + 2.0 \\times 10 = 70.\n$$\n\nLa standardizzazione permette di tradurre punteggi tra scale diverse mantenendo il significato relativo.\n:::\n\n## Il teorema di Chebyshev\n\nUna domanda naturale è: quanto della distribuzione cade entro un certo numero di deviazioni standard dalla media? Il *teorema di Chebyshev* fornisce una risposta universale, valida per qualsiasi distribuzione.\n\n::: {#thm-chebyshev}\n### Teorema di Chebyshev\n\nPer qualsiasi variabile casuale $X$ con media $\\mu$ e deviazione standard $\\sigma$, e per qualsiasi $k > 0$:\n$$\nP(|X - \\mu| \\geq k\\sigma) \\leq \\frac{1}{k^2}.\n$$\n\nEquivalentemente:\n$$\nP(|X - \\mu| < k\\sigma) \\geq 1 - \\frac{1}{k^2}.\n$$\n:::\n\nIl teorema fornisce un limite inferiore alla probabilità che una variabile cada entro $k$ deviazioni standard dalla media:\n\n| $k$ | $P(\\|X - \\mu\\| < k\\sigma) \\geq$ |\n|:---:|:------------------------------:|\n| 1   | 0% (limite triviale)           |\n| 2   | 75%                            |\n| 3   | 89%                            |\n| 4   | 94%                            |\n\nQuesti limiti sono conservativi: per molte distribuzioni comuni (come la normale), le probabilità effettive sono molto più alte. Tuttavia, il teorema è valido universalmente, senza assumere nulla sulla forma della distribuzione.\n\n::: {.callout-note collapse=\"true\" title=\"Esempio: Applicazione del teorema di Chebyshev\"}\n### Stima di probabilità\n\nUn test psicometrico ha media 100 e deviazione standard 15. Senza conoscere la distribuzione esatta, possiamo affermare che almeno il 75% dei punteggi cade nell'intervallo:\n$$\n[100 - 2 \\times 15, 100 + 2 \\times 15] = [70, 130].\n$$\n\nPer la distribuzione normale, la proporzione effettiva è circa 95%—molto superiore al limite di Chebyshev, ma il teorema ci dà una garanzia minima senza dover assumere la normalità.\n:::\n\n## Momenti di una distribuzione\n\nIl valore atteso e la varianza sono i primi due **momenti** di una distribuzione, ovvero una famiglia di quantità che caratterizzano completamente la forma della distribuzione sotto certe condizioni.\n\n::: {#def-moments}\n### Momenti\n\nIl *momento di ordine $r$* di una variabile casuale $X$ è:\n$$\n\\mathbb{E}[X^r] = \\begin{cases}\n\\sum_i x_i^r \\cdot p_X(x_i) & \\text{(caso discreto)} \\\\\n\\int_{-\\infty}^{+\\infty} x^r \\cdot f_X(x) \\, dx & \\text{(caso continuo)}\n\\end{cases}\n$$\n\nIl *momento centrale di ordine $r$* è:\n$$\n\\mathbb{E}[(X - \\mu)^r],\n$$\ndove $\\mu = \\mathbb{E}[X]$.\n:::\n\nIl momento di ordine 1 è il valore atteso. Il momento centrale di ordine 2 è la varianza. I momenti di ordine superiore catturano altre caratteristiche della distribuzione: il terzo momento centrale (opportunamente normalizzato) misura l'asimmetria, mentre il quarto misura l'eccesso di curtosi, ovvero quanto le code sono pesanti rispetto a una distribuzione normale.\n\n## Riflessioni conclusive {.unnumbered .unlisted}\n\nIl valore atteso e la varianza sono gli strumenti fondamentali per sintetizzare una distribuzione di probabilità. Il valore atteso localizza il centro, ovvero il \"baricentro probabilistico\", mentre la varianza quantifica la dispersione attorno a esso.\n\nLe proprietà algebriche di queste quantità, ovvero la linearità del valore atteso e l'additività della varianza per variabili indipendenti, semplificano notevolmente i calcoli pratici e rivelano le strutture profonde delle relazioni tra le variabili casuali. La proprietà per cui la varianza della media campionaria decresce come $1/n$ è alla base dell'inferenza statistica e spiega perché i campioni più grandi forniscono stime più affidabili.\n\nQuesti concetti troveranno immediata applicazione nei capitoli successivi, in cui verranno studiate specifiche famiglie di distribuzioni (Beta, Normale, Poisson e Binomiale) e verrà costruito l'apparato formale dell'inferenza bayesiana. Il valore atteso del parametro sotto la distribuzione a posteriori sarà la nostra stima puntuale bayesiana, mentre la varianza a posteriori quantificherà l'incertezza residua dopo l'osservazione dei dati.\n\n::: {.callout-note collapse=true title=\"Informazioni sull'ambiente di sviluppo\"}\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsessionInfo()\n#> R version 4.5.2 (2025-10-31)\n#> Platform: aarch64-apple-darwin20\n#> Running under: macOS Tahoe 26.1\n#> \n#> Matrix products: default\n#> BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib \n#> LAPACK: /Library/Frameworks/R.framework/Versions/4.5-arm64/Resources/lib/libRlapack.dylib;  LAPACK version 3.12.1\n#> \n#> locale:\n#> [1] C.UTF-8/UTF-8/C.UTF-8/C/C.UTF-8/C.UTF-8\n#> \n#> time zone: Europe/Rome\n#> tzcode source: internal\n#> \n#> attached base packages:\n#> [1] stats     graphics  grDevices utils     datasets  methods   base     \n#> \n#> other attached packages:\n#>  [1] pillar_1.11.1         tinytable_0.15.1      patchwork_1.3.2      \n#>  [4] ggdist_3.3.3          tidybayes_3.0.7       bayesplot_1.14.0     \n#>  [7] ggplot2_4.0.1         reliabilitydiag_0.2.1 priorsense_1.2.0     \n#> [10] posterior_1.6.1       loo_2.8.0             rstan_2.32.7         \n#> [13] StanHeaders_2.32.10   brms_2.23.0           Rcpp_1.1.0           \n#> [16] sessioninfo_1.2.3     conflicted_1.2.0      janitor_2.2.1        \n#> [19] matrixStats_1.5.0     modelr_0.1.11         tibble_3.3.0         \n#> [22] dplyr_1.1.4           tidyr_1.3.1           rio_1.2.4            \n#> [25] here_1.0.2           \n#> \n#> loaded via a namespace (and not attached):\n#>  [1] svUnit_1.0.8          tidyselect_1.2.1      farver_2.1.2         \n#>  [4] S7_0.2.1              fastmap_1.2.0         TH.data_1.1-5        \n#>  [7] tensorA_0.36.2.1      pacman_0.5.1          digest_0.6.39        \n#> [10] timechange_0.3.0      estimability_1.5.1    lifecycle_1.0.4      \n#> [13] survival_3.8-3        magrittr_2.0.4        compiler_4.5.2       \n#> [16] rlang_1.1.6           tools_4.5.2           yaml_2.3.10          \n#> [19] knitr_1.50            labeling_0.4.3        bridgesampling_1.2-1 \n#> [22] curl_7.0.0            pkgbuild_1.4.8        RColorBrewer_1.1-3   \n#> [25] abind_1.4-8           multcomp_1.4-29       withr_3.0.2          \n#> [28] purrr_1.2.0           grid_4.5.2            stats4_4.5.2         \n#> [31] colorspace_2.1-2      xtable_1.8-4          inline_0.3.21        \n#> [34] emmeans_2.0.0         scales_1.4.0          MASS_7.3-65          \n#> [37] cli_3.6.5             mvtnorm_1.3-3         rmarkdown_2.30       \n#> [40] ragg_1.5.0            generics_0.1.4        RcppParallel_5.1.11-1\n#> [43] cachem_1.1.0          stringr_1.6.0         splines_4.5.2        \n#> [46] parallel_4.5.2        vctrs_0.6.5           V8_8.0.1             \n#> [49] Matrix_1.7-4          sandwich_3.1-1        jsonlite_2.0.0       \n#> [52] arrayhelpers_1.1-0    systemfonts_1.3.1     glue_1.8.0           \n#> [55] codetools_0.2-20      distributional_0.5.0  lubridate_1.9.4      \n#> [58] stringi_1.8.7         gtable_0.3.6          QuickJSR_1.8.1       \n#> [61] htmltools_0.5.8.1     Brobdingnag_1.2-9     R6_2.6.1             \n#> [64] textshaping_1.0.4     rprojroot_2.1.1       evaluate_1.0.5       \n#> [67] lattice_0.22-7        backports_1.5.0       memoise_2.0.1        \n#> [70] broom_1.0.10          snakecase_0.11.1      rstantools_2.5.0     \n#> [73] coda_0.19-4.1         gridExtra_2.3         nlme_3.1-168         \n#> [76] checkmate_2.3.3       xfun_0.54             zoo_1.8-14           \n#> [79] pkgconfig_2.0.3\n```\n:::\n\n:::\n\n\n## Bibliografia {.unnumbered .unlisted}\n\n",
    "supporting": [
      "08_expval_var_files/figure-pdf"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{},\"value\":[]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}