{
  "hash": "6584ca2a64ce90e9ecde03817d729bca",
  "result": {
    "engine": "knitr",
    "markdown": "# Equiprobabilità e calcolo combinatorio come caso limite {#sec-equiprobability-combinatorics}\n\n## Introduzione {.unnumbered .unlisted}\n\nNei capitoli precedenti abbiamo sviluppato una concezione della probabilità come grado di credenza razionale, in cui gli assiomi rappresentano vincoli di coerenza logica. In questo capitolo, ci poniamo una domanda cruciale: *quando è possibile applicare legittimamente la formula classica \"casi favorevoli / casi possibili\"?*\n\nLa risposta risiede nel riconoscere che *questa formula presuppone implicitamente l'equiprobabilità di tutti i casi possibili*. Solo quando ogni esito è ugualmente plausibile, il rapporto tra i casi favorevoli e il totale corrisponde effettivamente alla probabilità dell'evento.\n\nLa prospettiva bayesiana fornisce una fondazione precisa per questo approccio: l'equiprobabilità non è una proprietà intrinseca del mondo fisico, ma deriva da uno stato di *simmetria epistemica*, ovvero dalla nostra mancanza di ragioni per considerare un esito più plausibile di un altro. Questo approccio formalizza il *principio di indifferenza* (o principio di ragione insufficiente): quando non disponiamo di informazioni che ci permettano di discriminare tra diverse possibilità, assegniamo loro credenze uguali.\n\nIn questa luce, il calcolo combinatorio assume un nuovo significato: non costituisce una definizione di probabilità, ma diventa uno *strumento di modellazione* per elencare le configurazioni in contesti che riteniamo simmetrici.\n\nTuttavia, quando emergono informazioni asimmetriche, come palline con pesi differenti in un'urna o item di test con diversa difficoltà, l'ipotesi di equiprobabilità viene meno. In questi casi, dobbiamo abbandonare il modello uniforme semplice e passare a modelli parametrici più sofisticati, in grado di catturare le differenze sistematiche tra le alternative.\n\n### Panoramica del capitolo {.unnumbered .unlisted}\n\n- Il principio di indifferenza e la simmetria epistemica.\n- Formula classica come caso speciale bayesiano.\n- Calcolo combinatorio come modellazione delle credenze equiprobabili.\n- Esempi con urne, carte, dadi interpretati in chiave bayesiana.\n- Quando l'equiprobabilità NON si applica.\n- Dal discreto al continuo: parametri ignoti e Beta-Binomiale.\n- La distribuzione Beta: un'intuizione profonda.\n- Applicazioni psicologiche: test, item difficulty, response patterns.\n\n::: {.callout-tip collapse=true}\n## Prerequisiti\n\n- Aver letto il @sec-prob-interpretation e il @sec-prob-models.\n- Leggere l'@sec-apx-combinatorics (calcolo combinatorio).\n- Familiarità con R e simulazioni Monte Carlo.\n:::\n\n::: {.callout-caution collapse=true title=\"Preparazione del Notebook\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhere::here(\"code\", \"_common.R\") |> \n  source()\n\n# Load packages\nif (!requireNamespace(\"pacman\")) install.packages(\"pacman\")\npacman::p_load(ggplot2, dplyr, tidyr, gtools, combinat)\n```\n:::\n\n:::\n\n## Il principio di indifferenza (simmetria epistemica)\n\n::: {#def-principle-indifference}\n### Principio di indifferenza\n\nSe, in base alle informazioni di cui disponiamo attualmente, non abbiamo *ragioni per distinguere* tra $n$ possibilità mutualmente esclusive ed esaustive, allora è coerente assegnare a ciascuna la stessa credenza $1/n$.\n:::\n\n### Fondamento epistemico\n\nIl principio di indifferenza non afferma che gli esiti sono \"fisicamente equiprobabili\", ma che la *nostra ignoranza è simmetrica*. In assenza di informazioni discriminanti, la distribuzione uniforme rappresenta il massimo livello di incertezza (massima entropia).\n\n::: {.callout-important title=\"Distinzione cruciale\"}\n**Non bayesiano**: \"Il dado è equo, quindi ogni faccia ha una probabilità pari a 1/6\" (l'equiprobabilità è una proprietà fisica).\n\n**Bayesiano**: \"Non ho informazioni che favoriscano una faccia rispetto alle altre, quindi assegno a ciascuna una credenza pari a 1/6, in base alla simmetria epistemica\" (l'equiprobabilità è uno stato di ignoranza simmetrica).\n:::\n\n### Quando si applica il principio\n\nIl principio di indifferenza trova giustificazione epistemica in tre condizioni specifiche. La prima condizione riguarda la presenza di simmetria fisica nel sistema oggetto di studio, come nel caso di dadi regolari, monete bilanciate o urne omogenee, in cui le proprietà fisiche garantiscono un'effettiva equivalenza tra gli esiti possibili.\n\nLa seconda condizione si verifica in situazioni di ignoranza totale, quando non disponiamo di alcuna informazione rilevante che ci permetterebbe di operare distinzioni tra i diversi esiti considerati. In tali circostanze, l'assegnazione di probabilità uniformi rappresenta l'unica scelta coerente con il nostro stato di conoscenza.\n\nLa terza condizione necessaria è l'assenza di una struttura sottostante, ovvero la mancanza di dipendenze note, di pattern sistematici o di relazioni che potrebbero favorire determinati esiti rispetto ad altri. Quando non emergono elementi che suggeriscono l'esistenza di tali strutture latenti, il principio di indifferenza rappresenta un approccio ragionevole per l'assegnazione delle probabilità iniziali.\n\n::: {.callout-warning title=\"Attenzione: i paradossi del principio di indifferenza\"}\n### Quando l'equiprobabilità genera contraddizioni\n\nL'applicazione automatica del principio di indifferenza, svincolata da un'analisi critica, può condurre a conclusioni paradossali e contraddittorie. Un esempio particolarmente illuminante è rappresentato dal celebre paradosso di Bertrand sulla produzione di cubi.\n\n**Il paradosso di Bertrand dei cubi**: si consideri una fabbrica che produce cubi con una lunghezza del lato compresa tra 0 e 1 metro. La questione investigata riguarda la probabilità che un cubo selezionato casualmente presenti un lato superiore a 0.5 metri.\n\nAdottando un primo approccio basato sull'indifferenza rispetto alla lunghezza del lato, assumendo cioè che tutte le lunghezze siano ugualmente probabili, si giunge alla conclusione che $P(\\text{lato} > 0.5) = 0.5$.\n\nUn secondo approccio, basato invece sull'indifferenza rispetto al volume e sull'equiprobabilità di tutti i volumi possibili, conduce a un risultato differente. Considerando che il volume è dato da $L^3$, si ottiene $P(\\text{volume} > 0.125) = P(L > 0.5) \\neq 0.5$.\n\nL'origine della contraddizione risiede nell'ambiguità fondamentale riguardante la scelta della variabile considerata \"naturale\" per l'applicazione del principio di indifferenza. Il conflitto emerge dalla mancanza di criteri oggettivi per stabilire se sia più rilevante la lunghezza del lato o il volume del cubo.\n\nLa prospettiva bayesiana risolve questo paradosso riconoscendo che non esiste una scelta \"corretta\" a priori tra le diverse parametrizzazioni. La soluzione richiede invece una specificazione esplicita della parametrizzazione ritenuta rilevante per il problema specifico, basata sulle informazioni concrete disponibili riguardo al processo di produzione. L'equiprobabilità non è una proprietà oggettiva del sistema in esame, ma piuttosto una scelta di modellazione che deve essere giustificata in base al contesto conoscitivo e agli obiettivi inferenziali.\n:::\n\n## La formula classica come caso particolare dell'equiprobabilità\n\nQuando accettiamo il principio di indifferenza per uno spazio campionario finito, la formula classica della probabilità emerge come conseguenza logica e matematica.\n\n::: {#thm-classical-formula}\n### La formula classica nella prospettiva bayesiana\n\nConsideriamo uno spazio campionario finito $\\Omega = \\{\\omega_1, \\omega_2, \\ldots, \\omega_n\\}$ in cui, per *simmetria epistemica*, assegniamo a ogni esito elementare la stessa probabilità: $P(\\omega_i) = \\frac{1}{n}$ per ogni $i = 1, \\ldots, n$.\n\nAllora, per qualsiasi evento $A \\subseteq \\Omega$, la probabilità è data da:\n\n$$\nP(A) = \\frac{|A|}{|\\Omega|} = \\frac{\\text{numero di esiti favorevoli}}{\\text{numero totale di esiti possibili}}.\n$$\n\n**Dimostrazione**: Per l'assioma di additività degli eventi disgiunti:\n$$\nP(A) = \\sum_{\\omega_i \\in A} P(\\omega_i) = \\sum_{\\omega_i \\in A} \\frac{1}{n} = |A| \\cdot \\frac{1}{n} = \\frac{|A|}{n} = \\frac{|A|}{|\\Omega|}.\n$$\n\n**Nota fondamentale**: La validità di questa formula dipende criticamente dall'ipotesi di equiprobabilità degli esiti elementari.\n:::\n\n### Una conseguenza, non una definizione\n\nÈ fondamentale riconoscere che la formula classica \"casi favorevoli diviso casi possibili\" non costituisce una *definizione* del concetto di probabilità, bensì rappresenta una *conseguenza matematica* della teoria probabilistica che risulta valida esclusivamente sotto condizioni specifiche e circoscritte.\n\nQuesta formula emerge naturalmente dall'interazione sinergica di tre componenti fondamentali. In primo luogo, gli *assiomi di coerenza* garantiscono la consistenza logica formale delle nostre assegnazioni probabilistiche. In secondo luogo, il *principio di indifferenza* introduce un'assunzione epistemica concernente la simmetria delle nostre credenze preliminari rispetto ai diversi esiti possibili. Infine, il *calcolo combinatorio* fornisce lo strumento operativo per enumerare sistematicamente le configurazioni che vengono considerate equiprobabili.\n\nLa validità della formula classica risulta quindi *condizionata criticamente* all'appropriatezza dell'assunzione di equiprobabilità. Quando questa assunzione non risulta giustificata dal nostro stato informativo—ovvero quando disponiamo di evidenza che contraddice la simmetria epistemica—la formula classica perde il suo fondamento logico e deve essere necessariamente sostituita da modelli probabilistici più sofisticati in grado di incorporare le asimmetrie informative disponibili.\n\n## Calcolo combinatorio come modellazione bayesiana\n\n### Un cambio di prospettiva\n\nNella trattazione classica della probabilità, il calcolo combinatorio viene solitamente presentato come una \"tecnica di conteggio\" neutrale e puramente operativa. La prospettiva bayesiana introduce invece un cambiamento epistemologico fondamentale: ogni formula combinatoria rappresenta l'implementazione di un modello specifico di credenze equiprobabili su un particolare tipo di configurazione.\n\nQuando applichiamo il calcolo combinatorio a contesti probabilistici, operiamo implicitamente una serie di assunzioni epistemologiche precise. In primo luogo, identifichiamo uno spazio di configurazioni che riteniamo rilevante per il problema in esame, definendo così l'insieme delle possibilità ammissibili. In secondo luogo, si assume l'esistenza di una simmetria epistemica su tale spazio, postulando che tutte le configurazioni identificate siano ugualmente credibili, date le informazioni attuali. Infine, procediamo all'enumerazione sistematica delle configurazioni per calcolare probabilità coerenti con questa assunzione di simmetria.\n\nQuesta riconcettualizzazione trasforma il calcolo combinatorio da mero strumento computazionale a componente integrante di un più ampio framework epistemico, in cui le scelte combinatorie riflettono precise posizioni riguardo alla struttura delle credenze preliminari.\n\n::: {.callout-note title=\"Esempio psicologico: formazione di gruppi terapeutici\"}\nImmaginiamo di dover costituire dei gruppi per una terapia di gruppo. Abbiamo a disposizione 10 pazienti e dobbiamo sceglierne 4 per formare il primo gruppo.\n\n**Domanda operativa**: quante composizioni gruppali distinte possiamo formare?\n\n**Risposta meccanica**:  \n\"Si tratta di una combinazione di 10 elementi presi 4 alla volta, pertanto $\\binom{10}{4} = 210$.\"\n\n**Interpretazione bayesiana**:  \nQuesta risposta numerica cela un'assunzione epistemica di fondamentale importanza:\n\nStiamo implicitamente presupponendo che ogni possibile gruppo di quattro pazienti sia, a priori, equivalente rispetto alle nostre credenze preliminari. Questo assunto si basa sull'assenza di informazioni che ci porterebbero a considerare alcune composizioni più plausibili di altre. La simmetria epistemica tra tutti i possibili sottoinsiemi giustifica dunque l'applicazione del calcolo combinatorio nella sua forma standard.\n\nTuttavia, se disponessimo di informazioni aggiuntive, come la conoscenza di dinamiche conflittuali pregresse tra specifici pazienti o l'evidenza di profili clinici particolarmente complementari, l'ipotesi di equiprobabilità risulterebbe ingiustificata. In tali circostanze, l'applicazione acritica del modello combinatorio uniforme condurrebbe a rappresentazioni inadeguate delle nostre credenze effettive.\n\nImplicazione pratica: il numero 210 rappresenta il conteggio delle configurazioni che consideriamo ugualmente plausibili, ma solo in assenza di informazioni specifiche sulla compatibilità interpersonale tra i pazienti.\n:::\n\n### Principio della somma (prospettiva bayesiana)\n\nIl *principio della somma* corrisponde alla *regola di additività* per eventi disgiunti nel calcolo delle probabilità. Quando uno spazio può essere partizionato in categorie mutualmente esclusive, le nostre credenze si distribuiscono additivamente tra queste categorie.\n\n$$\nn_{\\text{totale}} = n_1 + n_2 + \\dots + n_k.\n$$\n\n**Interpretazione bayesiana**: Se dobbiamo scegliere tra alternative che appartengono a categorie disgiunte, e assegniamo equiprobabilità all'interno di ciascuna categoria, allora il numero totale di configurazioni che consideriamo ugualmente plausibili è la somma delle configurazioni in ciascuna categoria.\n\n**Esempio psicologico: scelta di trattamenti**\n\nImmaginiamo che un paziente debba scegliere un protocollo terapeutico tra tre categorie mutualmente esclusive:\n\n- **Categoria A** (terapie cognitive): 8 protocolli diversi;\n- **Categoria B** (terapie comportamentali): 6 protocolli diversi; \n- **Categoria C** (terapie integrate): 10 protocolli diversi.\n\nSe non disponiamo di informazioni che favoriscano un protocollo rispetto agli altri (principio di indifferenza), il numero totale di opzioni equiprobabili è:\n\n$$\nn_{\\text{totale}} = 8 + 6 + 10 = 24.\n$$\n\nLa probabilità di scegliere un protocollo specifico, sotto l'ipotesi di equiprobabilità, è quindi $1/24$.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Calcolo delle probabilità per la scelta di trattamenti\nA <- 8   # Terapie cognitive\nB <- 6   # Terapie comportamentali\nC <- 10  # Terapie integrate\n\nn_totale <- A + B + C\n\ncat(\"ANALISI DELLE OPZIONI TERAPEUTICHE\\n\")\n#> ANALISI DELLE OPZIONI TERAPEUTICHE\ncat(\"===================================\\n\")\n#> ===================================\ncat(\"Numero totale di protocolli disponibili:\", n_totale, \"\\n\")\n#> Numero totale di protocolli disponibili: 24\ncat(\"Probabilità di ciascun protocollo (equiprobabilità):\", round(1/n_totale, 4), \"\\n\")\n#> Probabilità di ciascun protocollo (equiprobabilità): 0.0417\ncat(\"\\nPROBABILITÀ PER CATEGORIA:\\n\")\n#> \n#> PROBABILITÀ PER CATEGORIA:\ncat(\"Terapie cognitive (A):\", round(A/n_totale, 3), \"\\n\")\n#> Terapie cognitive (A): 0.333\ncat(\"Terapie comportamentali (B):\", round(B/n_totale, 3), \"\\n\")\n#> Terapie comportamentali (B): 0.25\ncat(\"Terapie integrate (C):\", round(C/n_totale, 3), \"\\n\")\n#> Terapie integrate (C): 0.417\ncat(\"\\nVerifica coerenza (somma = 1):\", round((A + B + C)/n_totale, 3))\n#> \n#> Verifica coerenza (somma = 1): 1\n```\n:::\n\n\n**Interpretazione clinica**: \n\n- ogni protocollo ha la stessa plausibilità a priori (4.17%);\n- le terapie integrate sono collettivamente più probabili (41.7%) perché offrono più opzioni;\n- questo modello è appropriato solo se non abbiamo informazioni sulla compatibilità tra paziente e approccio terapeutico.\n\n### Principio del prodotto (prospettiva bayesiana)\n\nIl *principio del prodotto* si applica quando dobbiamo fare *scelte sequenziali indipendenti*. Dal punto di vista bayesiano, questo principio corrisponde alla moltiplicazione delle probabilità per eventi considerati indipendenti nel nostro stato di conoscenza:\n\n$$\nn_{\\text{totale}} = n_1 \\times n_2 \\times \\dots \\times n_k.\n$$\n\n**Interpretazione bayesiana**: Se dobbiamo effettuare $k$ scelte successive e indipendenti, e per ciascuna scelta abbiamo $n_i$ opzioni che consideriamo ugualmente plausibili, allora il numero totale di sequenze equiprobabili è dato dal prodotto delle opzioni disponibili a ogni passo.\n\n**Esempio psicologico: progettazione di uno studio longitudinale**\n\nImmaginiamo di progettare uno studio longitudinale che richiede tre decisioni sequenziali.\n\n- **Fase 1**: Selezione del metodo di assessment  \n  (3 opzioni: intervista clinica, questionario standardizzato, osservazione diretta).\n- **Fase 2**: Scelta della frequenza di misurazione  \n  (4 opzioni: settimanale, bisettimanale, mensile, bimestrale).\n- **Fase 3**: Decisione sulla durata del follow-up  \n  (2 opzioni: breve termine [6 mesi], lungo termine [12 mesi]).\n\nSe non abbiamo informazioni che favoriscano opzioni specifiche (simmetria epistemica), il numero totale di design considerati ugualmente plausibili è:\n\n$$\nn_{\\text{totale}} = 3 \\times 4 \\times 2 = 24.\n$$\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Calcolo delle combinazioni per il design dello studio\nmetodi_assessment <- 3\nfrequenze <- 4\nfollow_up <- 2\n\nn_design <- metodi_assessment * frequenze * follow_up\n\ncat(\"ANALISI DEI DESIGN DI STUDIO POSSIBILI\\n\")\n#> ANALISI DEI DESIGN DI STUDIO POSSIBILI\ncat(\"======================================\\n\")\n#> ======================================\ncat(\"Metodi di assessment disponibili:\", metodi_assessment, \"\\n\")\n#> Metodi di assessment disponibili: 3\ncat(\"Frequenze di misurazione:\", frequenze, \"\\n\")\n#> Frequenze di misurazione: 4\ncat(\"Opzioni di follow-up:\", follow_up, \"\\n\")\n#> Opzioni di follow-up: 2\ncat(\"\\nNumero totale di design possibili:\", n_design, \"\\n\")\n#> \n#> Numero totale di design possibili: 24\ncat(\"Probabilità di ciascun design specifico:\", round(1/n_design, 4), \"\\n\")\n#> Probabilità di ciascun design specifico: 0.0417\ncat(\"\\nEsempio: probabilità di 'intervista + settimanale + lungo termine':\", \n    round(1/n_design, 4))\n#> \n#> Esempio: probabilità di 'intervista + settimanale + lungo termine': 0.0417\n```\n:::\n\n\n**Condizione cruciale per l'applicabilità**: l'equiprobabilità di tutte le 24 combinazioni vale *solo se* consideriamo le tre scelte come indipendenti e non abbiamo informazioni che suggeriscano preferenze tra le opzioni.\n\n**Situazione realistica**: se la letteratura ci indica che le misurazioni settimanali sono più accurate per certi fenomeni psicologici, o che certi metodi di assessment sono più appropriati per specifiche popolazioni, dovremmo *revisionare le nostre credenze* e abbandonare il modello equiprobabile a favore di una distribuzione più informata.\n\n### Permutazioni: ordinamenti equiprobabili\n\nLe **permutazioni** rappresentano l'insieme completo dei possibili ordinamenti di $n$ oggetti distinti. Dal punto di vista bayesiano, questa nozione implica l'assunzione che *ogni possibile sequenza ordinata sia a priori ugualmente credibile*:\n\n$$\nP_n = n! = n \\times (n-1) \\times (n-2) \\times \\dots \\times 2 \\times 1.\n$$ {#eq-permutations-def}\n\n**Intuizione della formula**. Consideriamo $n$ elementi distinti da disporre in sequenza. La scelta del primo elemento può avvenire in $n$ modi differenti. Una volta selezionato il primo elemento, rimangono $n-1$ possibilità per il secondo. Il terzo elemento avrà a disposizione $n-2$ opzioni, e così via fino all'ultimo elemento che avrà una sola collocazione possibile. Applicando il principio del prodotto, si ottiene l'equazione @eq-permutations-def.\n\n**Interpretazione bayesiana**: quando dobbiamo ordinare $n$ elementi in assenza di informazioni che favoriscano sequenze specifiche, ciascuna delle $n!$ permutazioni possiede la medesima credibilità iniziale, pari a $1/n!$.\n\n::: {.callout-note title=\"Esempio psicologico: ordine di presentazione degli stimoli\"}\nIn un esperimento sulla memoria, vengono presentate 5 parole distinte ai partecipanti. Per evitare che i risultati siano influenzati dagli effetti di posizione (primacy e recency), l'ordine di presentazione viene randomizzato.\n\n**Domanda metodologica**: Quanti ordinamenti distinti è possibile generare?\n\n**Analisi bayesiana**: \n$$\nP_5 = 5! = 5 \\times 4 \\times 3 \\times 2 \\times 1 = 120.\n$$\n\nNell'ipotesi di simmetria epistemica, che presuppone l'assenza di ragioni per privilegiare un ordine particolare, ciascuna sequenza specifica presenta una probabilità di $1/120 \\approx 0.0083$.\n\n**Implicazione metodologica**: l'implementazione sistematica della randomizzazione dell'ordine tra i partecipanti garantisce una rappresentazione equa di tutte le possibili sequenze. Questo procedimento neutralizza i potenziali fattori confondenti associati alla posizione degli stimoli, consentendo di attribuire gli effetti osservati alle variabili sperimentali di effettivo interesse.\n:::\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Esempio: parole in esperimento di memoria\nparole <- c(\"Tavolo\", \"Fiore\", \"Automobile\", \"Stella\", \"Libro\")\n\n# Numero di permutazioni\nn_perm <- factorial(length(parole))\n\ncat(\"ANALISI DELLE PERMUTAZIONI PER ESPERIMENTO DI MEMORIA\\n\")\n#> ANALISI DELLE PERMUTAZIONI PER ESPERIMENTO DI MEMORIA\ncat(\"=====================================================\\n\")\n#> =====================================================\ncat(\"Parole utilizzate:\", paste(parole, collapse = \", \"), \"\\n\")\n#> Parole utilizzate: Tavolo, Fiore, Automobile, Stella, Libro\ncat(\"Numero totale di ordini possibili:\", n_perm, \"\\n\")\n#> Numero totale di ordini possibili: 120\ncat(\"Probabilità di ciascun ordine specifico:\", round(1/n_perm, 5), \"\\n\\n\")\n#> Probabilità di ciascun ordine specifico: 0.00833\n\n# Generiamo alcune permutazioni casuali\nset.seed(123)\ncat(\"ESEMPI DI SEQUENZE EQUIPROBABILI:\\n\")\n#> ESEMPI DI SEQUENZE EQUIPROBABILI:\nfor(i in 1:3) {\n  cat(\"Sequenza\", i, \": \", paste(sample(parole), collapse = \" → \"), \"\\n\")\n}\n#> Sequenza 1 :  Automobile → Fiore → Libro → Stella → Tavolo \n#> Sequenza 2 :  Automobile → Tavolo → Fiore → Libro → Stella \n#> Sequenza 3 :  Fiore → Automobile → Tavolo → Stella → Libro\n```\n:::\n\n\n**Significato metodologico**: nella ricerca psicologica, la procedura di randomizzazione degli ordini di presentazione implementa operativamente il principio bayesiano di indifferenza. Questo approccio metodologico garantisce che il disegno sperimentale non introduca distorsioni sistematiche e favorisce l'elaborazione di interpretazioni causali più robuste.\n\n### Disposizioni: selezioni ordinate equiprobabili\n\nLe **disposizioni** (denominate anche *permutazioni parziali*) rappresentano il numero di modi per scegliere e ordinare $k$ oggetti da un insieme di $n$ oggetti. Dal punto di vista bayesiano, questa nozione implica l'assunzione di equiprobabilità su tutte le possibili sequenze ordinate di lunghezza $k$.\n\n$$\nD_{n,k} = \\frac{n!}{(n-k)!} = n \\times (n-1) \\times \\cdots \\times (n-k+1).\n$$ {#eq-dispositions-def}\n\n**Intuizione della formula**. Si consideri il processo di formazione di una sequenza ordinata composta da $k$ elementi selezionati da un insieme di $n$ oggetti distinti. Questo processo si sviluppa attraverso $k$ passi sequenziali. Nel primo passo, la scelta del primo elemento presenta $n$ possibilità distinte. Nel secondo passo, la scelta del secondo elemento offre $n-1$ opzioni residue. Il terzo passo prevede $n-2$ opzioni, e questa progressione decrescente continua fino al $k$-esimo passo, in cui rimangono $n-k+1$ possibilità.\n\nIl prodotto delle scelte disponibili a ogni passo conduce alla formula:\n$$\nD_{n,k} = n \\times (n-1) \\times (n-2) \\times \\dots \\times (n-k+1).\n$$\n\nQuesta espressione equivale concettualmente a interrompere il fattoriale di $n$ dopo $k$ fattori. Formalmente, essa corrisponde alla divisione di $n!$ per il fattoriale degli elementi non selezionati $(n-k)!$, come illustrato nell'equazione @eq-dispositions-def.\n\n**Interpretazione bayesiana**: quando dobbiamo selezionare $k$ elementi da $n$ in sequenza senza reinserimento, e l'ordine di selezione risulta rilevante, ciascuna possibile sequenza possiede una credibilità iniziale pari a $1/D_{n,k}$.\n\n::: {.callout-note title=\"Esempio psicologico: assegnazione di ruoli in terapia di gruppo\"}\nIn un contesto di terapia di gruppo che coinvolge 8 partecipanti, è necessario assegnare tre ruoli specifici e distinti:\n\n- il **facilitatore**, responsabile della guida delle discussioni;\n- l'**osservatore**, incaricato di annotare le dinamiche interpersonali;\n- il **timekeeper**, deputato alla gestione dei tempi.\n\n**Domanda metodologica**: Quante assegnazioni distinte di questi ruoli è possibile realizzare?\n\n**Analisi bayesiana**: \n$$\nD_{8,3} = \\frac{8!}{(8-3)!} = 8 \\times 7 \\times 6 = 336.\n$$\n\nNell'ipotesi di simmetria epistemica—che presuppone l'assenza di informazioni sulle preferenze individuali o sulle competenze specifiche—ciascuna assegnazione possiede una probabilità di $1/336 \\approx 0.003$.\n\n**Scenario realistico**: qualora si disponga di informazioni aggiuntive, come la conoscenza di esperienze pregresse di alcuni partecipanti nel ruolo di facilitatore, l'assunzione di equiprobabilità risulterebbe inappropriata. In tali circostanze, diverrebbe necessario adottare un modello probabilistico più sofisticato in grado di riflettere questa informazione aggiuntiva, ad esempio assegnando probabilità più elevate alle configurazioni che includono facilitatori esperti.\n:::\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Partecipanti\npartecipanti <- paste0(\"P\", 1:8)\n\n# Numero di disposizioni (3 ruoli da 8 persone, ordine conta)\nn <- length(partecipanti)\nk <- 3\nn_disp <- factorial(n) / factorial(n - k)\n\ncat(\"ANALISI DELLE DISPOSIZIONI PER ASSEGNAZIONE DI RUOLI\\n\")\n#> ANALISI DELLE DISPOSIZIONI PER ASSEGNAZIONE DI RUOLI\ncat(\"===================================================\\n\")\n#> ===================================================\ncat(\"Numero di partecipanti:\", n, \"\\n\")\n#> Numero di partecipanti: 8\ncat(\"Numero di ruoli da assegnare:\", k, \"\\n\")\n#> Numero di ruoli da assegnare: 3\ncat(\"Numero di assegnazioni possibili:\", n_disp, \"\\n\")\n#> Numero di assegnazioni possibili: 336\ncat(\"Probabilità di ciascuna assegnazione specifica:\", round(1/n_disp, 5), \"\\n\\n\")\n#> Probabilità di ciascuna assegnazione specifica: 0.00298\n\n# Generiamo alcune assegnazioni casuali\nset.seed(456)\nruoli <- c(\"Facilitatore\", \"Osservatore\", \"Timekeeper\")\n\ncat(\"ESEMPI DI ASSEGNAZIONI EQUIPROBABILI:\\n\")\n#> ESEMPI DI ASSEGNAZIONI EQUIPROBABILI:\nfor(i in 1:3) {\n  selezione <- sample(partecipanti, k, replace = FALSE)\n  assegnazione <- paste(ruoli, \"=\", selezione, collapse = \", \")\n  cat(\"Assegnazione\", i, \": \", assegnazione, \"\\n\")\n}\n#> Assegnazione 1 :  Facilitatore = P5, Osservatore = P8, Timekeeper = P3 \n#> Assegnazione 2 :  Facilitatore = P6, Osservatore = P5, Timekeeper = P4 \n#> Assegnazione 3 :  Facilitatore = P3, Osservatore = P1, Timekeeper = P6\n```\n:::\n\n\n**Insight bayesiano**: l'applicazione del modello delle disposizioni presuppone il soddisfacimento di due condizioni fondamentali: la rilevanza dell'ordine o della specificità dei ruoli, e l'equivalenza a priori di tutte le possibili assegnazioni. Quando una di queste condizioni non risulta verificata, a causa di informazioni aggiuntive o di caratteristiche contestuali, diventa necessario modificare il modello probabilistico per incorporare adeguatamente queste complessità.\n\n\n### Combinazioni: selezioni non ordinate equiprobabili\n\nLe *combinazioni* rappresentano il numero di modi per selezionare $k$ oggetti da un insieme di $n$ elementi quando l'ordine non conta. Dal punto di vista bayesiano, questa nozione implica l'assunzione che ogni possibile sottoinsieme di dimensione $k$ abbia la stessa credibilità iniziale:\n\n$$\nC_{n,k} = \\binom{n}{k} = \\frac{n!}{k!(n-k)!}.\n$$ {#eq-combinations-def}\n\n**Intuizione della formula**. Si consideri il processo di formazione di gruppi composti da $k$ elementi selezionati da un insieme di $n$, in cui l'ordine di selezione non è rilevante.\n\nSe contassimo le sequenze ordinate (disposizioni), noteremmo che il primo elemento offre $n$ opzioni, il secondo $n-1$, e così via fino al $k$-esimo elemento, che offre $n-k+1$ possibilità. Il numero totale di sequenze ordinate risulterebbe dunque:\n\n$$\nD_{n,k} = n \\times (n-1) \\times \\dots \\times (n-k+1).\n$$\n\nTuttavia, nella prospettiva delle combinazioni, l'ordine non è rilevante: il gruppo {A, B} è equivalente al gruppo {B, A}. \n\nOgni gruppo di $k$ elementi appare replicato in tutte le sue possibili permutazioni, che ammontano esattamente a $k!$. Per ottenere il numero di gruppi distinti, ovvero eliminando le ripetizioni dovute alle differenti ordinazioni, è necessario dividere per $k!$:\n\n$$\nC_{n,k} = \\frac{D_{n,k}}{k!} = \\frac{n \\times (n-1) \\times \\dots \\times (n-k+1)}{k!}.\n$$\n\nQuesta espressione coincide esattamente con la formula delle combinazioni presentata nell'equazione @eq-combinations-def.\n\n**Interpretazione bayesiana**: quando dobbiamo costituire gruppi di $k$ elementi selezionati da $n$, e non disponiamo di informazioni che favoriscano composizioni specifiche, ciascun gruppo possiede una credibilità iniziale pari a $1/\\binom{n}{k}$.\n\n::: {.callout-note title=\"Esempio psicologico: formazione di coppie terapeutiche\"}\nUn programma di peer counseling richiede la formazione di coppie di supporto reciproco tra 12 volontari.\n\n**Domanda operativa**: quante coppie distinte è possibile costituire?\n\n**Analisi bayesiana**: \n$$\nC_{12,2} = \\binom{12}{2} = \\frac{12!}{2!(12-2)!} = \\frac{12 \\times 11}{2} = 66.\n$$\n\nNell'ipotesi del principio di indifferenza, ciascuna coppia possiede una probabilità di $1/66 \\approx 0.015$.\n\n**Considerazione psicologica**: nella pratica clinica, alcune coppie potrebbero rivelarsi più compatibili di altre in virtù di fattori quali l'affinità di personalità, la condivisione di esperienze pregresse o la similarità anagrafica. Se si dispone di tali informazioni, l'assunzione di equiprobabilità risulterebbe inappropriata e sarebbe necessario adottare un modello alternativo in grado di incorporare i fattori di compatibilità, ad esempio assegnando probabilità più elevate alle coppie caratterizzate da complementarità ottimale.\n:::\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Volontari per peer counseling\nvolontari <- paste0(\"V\", 1:12)\n\n# Numero di coppie possibili\nn_volontari <- length(volontari)\nn_coppie <- choose(n_volontari, 2)\n\ncat(\"ANALISI DELLE COMBINAZIONI PER FORMAZIONE DI COPPIE\\n\")\n#> ANALISI DELLE COMBINAZIONI PER FORMAZIONE DI COPPIE\ncat(\"===================================================\\n\")\n#> ===================================================\ncat(\"Numero di volontari:\", n_volontari, \"\\n\")\n#> Numero di volontari: 12\ncat(\"Numero di coppie possibili:\", n_coppie, \"\\n\")\n#> Numero di coppie possibili: 66\ncat(\"Probabilità di ciascuna coppia specifica:\", round(1/n_coppie, 4), \"\\n\\n\")\n#> Probabilità di ciascuna coppia specifica: 0.0152\n\n# Generiamo alcune coppie casuali usando combinazioni\nlibrary(gtools)\nset.seed(789)\ntutte_coppie <- combinations(n = n_volontari, r = 2, v = volontari)\n\ncat(\"ESEMPI DI COPPIE EQUIPROBABILI:\\n\")\n#> ESEMPI DI COPPIE EQUIPROBABILI:\nfor(i in 1:5) {\n  cat(\"Coppia\", i, \": (\", tutte_coppie[i,1], \",\", tutte_coppie[i,2], \")\\n\")\n}\n#> Coppia 1 : ( V1 , V10 )\n#> Coppia 2 : ( V1 , V11 )\n#> Coppia 3 : ( V1 , V12 )\n#> Coppia 4 : ( V1 , V2 )\n#> Coppia 5 : ( V1 , V3 )\n\n# Verifica\ncat(\"\\nVerifica - Totale coppie uniche generate:\", nrow(tutte_coppie))\n#> \n#> Verifica - Totale coppie uniche generate: 66\n```\n:::\n\n\n**Lezione bayesiana fondamentale**: il modello delle combinazioni rappresenta una formalizzazione dell'ignoranza simmetrica riguardo alla composizione dei gruppi. Quando questa condizione di ignoranza viene meno, in seguito all'acquisizione di informazioni sulle relazioni interpersonali, sulle competenze complementari o su altri fattori rilevanti, diventa necessario abbandonare il modello uniforme a favore di un approccio parametrico, in grado di riflettere adeguatamente la struttura delle conoscenze disponibili.\n\n### Sintesi: quando usare ciascun metodo\n\nDal punto di vista bayesiano, la scelta tra permutazioni, disposizioni e combinazioni riflette *quali aspetti del problema consideriamo rilevanti* e su quali *assumiamo simmetria epistemica*.\n\n| Metodo | Ordine rilevante? | Modello bayesiano | Formula | Esempio psicologico |\n|--------|-------------------|-------------------|---------|---------------------|\n| **Permutazioni** | **Importante** | Tutti gli ordinamenti completi di $n$ elementi sono ugualmente plausibili | $n!$ | Ordine di presentazione di $n$ stimoli in un esperimento |\n| **Disposizioni** | **Importante** | Tutte le sequenze ordinate di $k$ elementi (scelti da $n$) sono ugualmente plausibili | $\\frac{n!}{(n-k)!}$ | Assegnazione di $k$ compiti specifici a $n$ partecipanti |\n| **Combinazioni** | **Irrilevante** | Tutti i sottoinsiemi di $k$ elementi (scelti da $n$) sono ugualmente plausibili | $\\binom{n}{k}$ | Selezione di $k$ partecipanti per un gruppo terapeutico |\n\n::: {.callout-important title=\"Principio bayesiano fondamentale\"}\n**Il calcolo combinatorio non è \"oggettivo\"**: ogni formula incorpora specifiche assunzioni epistemiche. Quando applichiamo una formula combinatoria, stiamo implicitamente:\n\n1. *definendo* uno spazio di configurazioni che consideriamo possibili;\n2. *assumendo* simmetria epistemica su quello spazio (nessuna configurazione è a priori più credibile di altre);\n3. *calcolando* le credenze coerenti date quelle assunzioni.\n\nSe si acquisiscono nuove informazioni che rompono la simmetria (per esempio, si scopre che determinati ordini di presentazione influenzano la memoria o che alcune composizioni di gruppo sono più efficaci), è necessario abbandonare il modello uniforme e sviluppare un modello probabilistico più sofisticato che rifletta la conoscenza aggiornata.\n:::\n\n## Quando l'equiprobabilità NON si applica\n\nIl principio di indifferenza decade quando si dispone di *informazioni asimmetriche* che ci permettono di distinguere tra le diverse possibilità. In psicologia e nelle scienze del comportamento, questa situazione è la *regola* piuttosto che l'eccezione.\n\n### Esempio 1: palline con pesi diversi\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Urna con 3 palline: A (leggera), B (media), C (pesante)\n# Le probabilità di estrazione sono proporzionali ai pesi\n\npesi <- c(A = 1, B = 2, C = 3)\nprob_corrette <- pesi / sum(pesi)  # Normalizziamo per ottenere probabilità\n\ncat(\"DISTRIBUZIONE CORRETTA (considerando i pesi)\\n\")\n#> DISTRIBUZIONE CORRETTA (considerando i pesi)\ncat(\"===========================================\\n\")\n#> ===========================================\nfor(i in 1:3) {\n  cat(names(pesi)[i], \": peso =\", pesi[i], \"→ prob =\", round(prob_corrette[i], 3), \"\\n\")\n}\n#> A : peso = 1 → prob = 0.167 \n#> B : peso = 2 → prob = 0.333 \n#> C : peso = 3 → prob = 0.5\n\ncat(\"\\nDISTRIBUZIONE ERRATA (ignorando i pesi)\\n\")\n#> \n#> DISTRIBUZIONE ERRATA (ignorando i pesi)\ncat(\"=======================================\\n\")\n#> =======================================\nprob_equiprobabili <- rep(1/3, 3)\nnames(prob_equiprobabili) <- names(pesi)\nprint(round(prob_equiprobabili, 3))\n#>     A     B     C \n#> 0.333 0.333 0.333\n\n# Simulazione per verificare il modello corretto\nset.seed(123)\nn_sim <- 10000\nestrazioni <- sample(names(pesi), size = n_sim, replace = TRUE, prob = prob_corrette)\nfreq_sim <- table(estrazioni) / n_sim\n\ncat(\"\\nVERIFICA EMPIRICA (\", n_sim, \"estrazioni simulate)\\n\")\n#> \n#> VERIFICA EMPIRICA ( 10000 estrazioni simulate)\ncat(\"================================================\\n\")\n#> ================================================\nprint(round(freq_sim, 3))\n#> estrazioni\n#>     A     B     C \n#> 0.162 0.333 0.506\n```\n:::\n\n\n**Interpretazione bayesiana**: se *sappiamo* che i pesi sono diversi, applicare l'equiprobabilità sarebbe *incoerente* con il nostro stato di informazione. Le nostre credenze devono necessariamente riflettere le asimmetrie che conosciamo.\n\n**Conseguenza pratica**: in questo caso, la pallina $C$ ha una probabilità di estrazione *tripla* rispetto alla pallina $A$ (0.5 vs 0.167), nonostante tutte e tre siano ugualmente \"possibili\" in senso fisico.\n\n### Esempio 2: item di un test con difficoltà variabile\n\nIn psicometria, gli item di un test presentano tipicamente *diversi livelli di difficoltà*. Assumere che tutte le domande siano ugualmente facili sarebbe un grave errore di modellazione.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# 5 item con probabilità di risposta corretta realisticamente variabili\nitem_difficolta <- c(\n  Item1 = 0.9,  # Molto facile\n  Item2 = 0.7,  # Facile\n  Item3 = 0.5,  # Difficoltà media\n  Item4 = 0.3,  # Difficile\n  Item5 = 0.1   # Molto difficile\n)\n\ncat(\"PROFILO DI DIFFICOLTÀ DEGLI ITEM\\n\")\n#> PROFILO DI DIFFICOLTÀ DEGLI ITEM\ncat(\"================================\\n\")\n#> ================================\nfor(i in 1:5) {\n  cat(names(item_difficolta)[i], \": P(corretta) =\", item_difficolta[i], \"\\n\")\n}\n#> Item1 : P(corretta) = 0.9 \n#> Item2 : P(corretta) = 0.7 \n#> Item3 : P(corretta) = 0.5 \n#> Item4 : P(corretta) = 0.3 \n#> Item5 : P(corretta) = 0.1\n\n# Simulare le risposte di studenti con abilità media\nset.seed(123)\nn_studenti <- 1000\nrisposte <- matrix(nrow = n_studenti, ncol = 5)\n\nfor (studente in 1:n_studenti) {\n  risposte[studente, ] <- rbinom(5, size = 1, prob = item_difficolta)\n}\n\n# Calcolare la frequenza empirica di risposte corrette\nfreq_empiriche <- colMeans(risposte)\n\ncat(\"\\nRISULTATI DELLA SIMULAZIONE (\", n_studenti, \"studenti)\\n\")\n#> \n#> RISULTATI DELLA SIMULAZIONE ( 1000 studenti)\ncat(\"==================================================\\n\")\n#> ==================================================\nprint(round(freq_empiriche, 3))\n#> [1] 0.890 0.711 0.479 0.287 0.098\n\n# Confronto con l'assunzione ingenua di equiprobabilità\ncat(\"\\nCONFRONTO CON MODELLO INGENUO\\n\")\n#> \n#> CONFRONTO CON MODELLO INGENUO\ncat(\"=============================\\n\")\n#> =============================\ncat(\"Equiprobabilità (modello errato): P(corretta) = 0.5 per ogni item\\n\")\n#> Equiprobabilità (modello errato): P(corretta) = 0.5 per ogni item\ncat(\"Differenza media:\", round(mean(abs(freq_empiriche - 0.5)), 3), \"\\n\")\n#> Differenza media: 0.247\n```\n:::\n\n\n**Interpretazione bayesiana:** in ambito psicometrico, l'assunzione di equiprobabilità risulta quasi sistematicamente inappropriata. Il modello ingenuo che attribuisce una probabilità di risposta corretta P(corretta) = 0.5 a tutti gli item comporta distorsioni metodologicamente rilevanti. Questo approccio porta a una sottostima sostanziale della performance relativa agli item facili, come evidenziato dal confronto tra il valore empirico di 0.9 per l'Item1 e l'assunzione uniforme di 0.5, e a una sovrastima drammatica della performance sugli item difficili, come dimostrato dal caso dell'Item5, dove il valore osservato di 0.1 contrasta nettamente con l'assunzione di equiprobabilità. Inoltre, questo modello trascura completamente la complessa struttura psicometrica sottostante al test, ignorando le differenze sistematiche di difficoltà tra gli item.\n\n**Conseguenza metodologica:** questa evidenza rende necessario l'utilizzo di modelli parametrici sofisticati, come quelli sviluppati nell'ambito della teoria della risposta all'item. Questi modelli permettono di stimare la difficoltà specifica di ciascun item, di modellare l'abilità degli studenti in modo differenziato e di incorporare sistematicamente le asimmetrie informative che emergono dall'osservazione empirica, superando i limiti fondamentali dell'approccio equiprobabilistico.\n\n### Esempio 3: estrazioni dipendenti senza reinserimento\n\nQuando le estrazioni avvengono senza reinserimento, i risultati successivi *dipendono* da quelli precedenti, creando vincoli strutturali che violano l'equiprobabilità delle sequenze.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Confronto tra estrazioni con e senza reinserimento\nset.seed(123)\nn_sim <- 5000\n\n# Scenario A: CON reinserimento (eventi indipendenti)\nrisultati_indip <- replicate(n_sim, {\n  sample(c(\"R\", \"B\"), size = 2, replace = TRUE, prob = c(0.5, 0.5))\n})\n\n# Scenario B: SENZA reinserimento (eventi dipendenti)\nrisultati_dip <- replicate(n_sim, {\n  sample(c(\"R\", \"B\"), size = 2, replace = FALSE)\n})\n\n# Analisi delle coppie possibili\nconta_indip <- table(paste0(risultati_indip[1, ], risultati_indip[2, ]))\nconta_dip <- table(paste0(risultati_dip[1, ], risultati_dip[2, ]))\n\ncat(\"DISTRIBUZIONE DELLE COPPIE - CONFRONTO\\n\")\n#> DISTRIBUZIONE DELLE COPPIE - CONFRONTO\ncat(\"=====================================\\n\")\n#> =====================================\ncat(\"CON REINSERIMENTO (eventi indipendenti):\\n\")\n#> CON REINSERIMENTO (eventi indipendenti):\ncat(\"----------------------------------------\\n\")\n#> ----------------------------------------\ndistrib_indip <- round(conta_indip / n_sim, 3)\nfor(coppia in c(\"RR\", \"RB\", \"BR\", \"BB\")) {\n  if(coppia %in% names(distrib_indip)) {\n    cat(coppia, \":\", distrib_indip[coppia], \"\\n\")\n  } else {\n    cat(coppia, \": 0.000\\n\")\n  }\n}\n#> RR : 0.239 \n#> RB : 0.259 \n#> BR : 0.252 \n#> BB : 0.25\n\ncat(\"\\nSENZA REINSERIMENTO (eventi dipendenti):\\n\")\n#> \n#> SENZA REINSERIMENTO (eventi dipendenti):\ncat(\"----------------------------------------\\n\")\n#> ----------------------------------------\ndistrib_dip <- round(conta_dip / n_sim, 3)\nfor(coppia in c(\"RR\", \"RB\", \"BR\", \"BB\")) {\n  if(coppia %in% names(distrib_dip)) {\n    cat(coppia, \":\", distrib_dip[coppia], \"\\n\")\n  } else {\n    cat(coppia, \": 0.000\\n\")\n  }\n}\n#> RR : 0.000\n#> RB : 0.501 \n#> BR : 0.499 \n#> BB : 0.000\n\n# Verifica teorica\ncat(\"\\nVERIFICA TEORICA\\n\")\n#> \n#> VERIFICA TEORICA\ncat(\"---------------\\n\")\n#> ---------------\ncat(\"Con reinserimento: tutte le coppie equiprobabili = 0.25\\n\")\n#> Con reinserimento: tutte le coppie equiprobabili = 0.25\ncat(\"Senza reinserimento: RR e BB impossibili, RB e BR equiprobabili = 0.5\\n\")\n#> Senza reinserimento: RR e BB impossibili, RB e BR equiprobabili = 0.5\n```\n:::\n\n\n**Interpretazione bayesiana:** nel contesto di estrazioni senza reinserimento da un'urna contenente una pallina rossa e una blu, si osserva una trasformazione radicale della distribuzione probabilistica. Le coppie RR e BB diventano logicamente impossibili, acquisendo quindi una probabilità nulla. Al contrario, le coppie RB e BR diventano necessarie, con una probabilità di 0.5 per ciascuna. Questa configurazione viola completamente il principio di equiprobabilità, che presupporrebbe una probabilità uniforme di 0.25 per ciascuna delle quattro coppie possibili.\n\n**Implicazione epistemica:** le nostre credenze riguardo alle possibili sequenze devono necessariamente incorporare i vincoli strutturali intrinseci al processo di generazione dei dati. Quando si conosce il fatto che il campionamento avviene senza reinserimento, risulterebbe incoerente dal punto di vista epistemologico assegnare probabilità positive a sequenze che, date le condizioni del processo, diventano logicamente impossibili.\n\n## Dal discreto al continuo: parametri ignoti\n\nNella ricerca psicologica, il passaggio dal conteggio di casi equiprobabili alla stima di parametri ignoti rappresenta una transizione fondamentale. Questa evoluzione concettuale trova una trattazione naturale all'interno del framework bayesiano.\n\n### Motivazione: oltre il conteggio\n\nConsideriamo la situazione in cui si osservano k successi in n prove, come tipicamente avviene nella valutazione delle risposte corrette in un test psicometrico.\n\nL'approccio frequentista classico tende a interpretare la proporzione osservata, $\\hat{p} = k/n$, come una stima puntuale definitiva della probabilità di successo, trattandola come un valore fisso e deterministico.\n\nL'approccio bayesiano, al contrario, introduce una prospettiva epistemologicamente più sofisticata, riconoscendo tre dimensioni fondamentali dell'inferenza probabilistica. In primo luogo, esso afferma che il vero parametro $\\theta$, che rappresenta la probabilità di successo, rimane intrinsecamente sconosciuto e soggetto a un'incertezza che non può essere eliminata. In secondo luogo, tale incertezza deve essere formalmente rappresentata mediante una distribuzione di probabilità completa su $\\theta$, che quantifichi la plausibilità relativa di tutti i suoi valori possibili. In terzo luogo, il framework bayesiano supporta un processo di apprendimento sequenziale che permette di aggiornare le credenze in modo coerente e incrementale, man mano che nuovi dati empirici diventano disponibili.\n\n### La transizione epistemologica: dalle frequenze ai parametri\n\n::: {.callout-important title=\"Transizione concettuale\"}\nL'*equiprobabilità discreta* corrisponde a una credenza uniforme distribuita su un numero finito di casi possibili, mentre la situazione di *parametro continuo ignoto* richiede la specificazione di una distribuzione di probabilità completa su $\\theta \\in [0,1]$.\n\nNel campo della psicologia, questa seconda condizione è la norma piuttosto che l'eccezione, poiché i costrutti fondamentali della disciplina presentano caratteristiche intrinseche di latenza e incertezza. L'abilità latente di un esaminando non è direttamente osservabile, ma deve essere inferita da indicatori comportamentali. L'efficacia genuina di un trattamento psicologico rimane soggetta a un'elevata incertezza e richiede processi inferenziali sofisticati. La proporzione di risposte affermative a un item di un questionario è un parametro che deve essere stimato piuttosto che osservato direttamente.\n\nL'approccio bayesiano fornisce gli strumenti formali necessari per rappresentare in modo appropriato, quantificare con precisione e aggiornare coerentemente questa incertezza epistemica, attraverso processi inferenziali rigorosi.\n:::\n\n## La distribuzione Beta: un'intuizione concettuale\n\nLa distribuzione Beta costituisce lo strumento fondamentale per rappresentare le credenze bayesiane riguardo a probabilità ignote $\\theta \\in [0, 1]$. Prima di affrontarne la formalizzazione matematica, è essenziale svilupparne una comprensione intuitiva.\n\n### Metafora: la Beta come \"memoria di esperienze virtuali\"\n\nSi consideri il compito di stimare la probabilità che uno studente risponda correttamente a domande di una determinata tipologia. Anche in assenza di osservazioni dirette del soggetto in esame, è possibile formulare una valutazione preliminare basata su diversi elementi conoscitivi. Questi includono le esperienze virtuali pregresse con studenti analoghi, le credenze consolidate riguardo alla distribuzione delle abilità nella popolazione di riferimento e le conoscenze contestuali relative alla difficoltà intrinseca del compito.\n\nLa distribuzione Beta (Beta($\\alpha, \\beta$)) formalizza queste informazioni preliminari attraverso una rappresentazione parametrica che equivale, concettualmente, a possedere una \"memoria\" di esperienze virtuali. In particolare, essa codifica l'informazione pregressa come se avessimo già osservato $\\alpha - 1$ successi virtuali, corrispondenti a risposte corrette immaginarie, e $\\beta - 1$ insuccessi virtuali, corrispondenti a risposte errate immaginarie.\n\n::: {.callout-note title=\"Esempio concreto: valutazione di un nuovo studente\"}\n**Scenario**: un nuovo studente si presenta per sostenere un test di matematica. Non disponiamo di osservazioni empiriche dirette sulle sue prestazioni.\n\n**Domanda**: quale distribuzione Beta dovremmo adottare per rappresentare le nostre credenze iniziali sulla probabilità $\\theta$ di risposta corretta?\n\n**Opzione 1** - $\\text{Beta}(1, 1)$ (stato di ignoranza epistemica):\nquesta configurazione è appropriata in assenza di esperienze con studenti simili. Ogni valore di $\\theta$ nell'intervallo $[0, 1]$ è ugualmente plausibile, riflettendo una distribuzione uniforme. L'interpretazione corrispondente è: \"La probabilità di risposta corretta potrebbe assumere qualsiasi valore compreso tra 0% e 100%\".\n\n**Opzione 2** - $\\text{Beta}(5, 5)$ (preferenza moderata per i valori centrali): questa parametrizzazione si basa sull'evidenza che gli studenti con caratteristiche simili tendono a mostrare abilità prevalentemente intermedie. I valori estremi di $\\theta$ sono meno probabili, concentrando la massa probabilistica attorno alla regione centrale. L'interpretazione conseguente è: \"La probabilità di risposta corretta si colloca verosimilmente intorno al 50%\".\n\n**Opzione 3** - $\\text{Beta}(20, 10)$ (aspettativa di abilità elevate): questa scelta è giustificata quando lo studente proviene da un contesto scolastico caratterizzato da eccellenza accademica. Le esperienze pregresse con popolazioni analoghe suggeriscono probabilità di successo costantemente elevate. L'interpretazione appropriata è: \"Mi aspetto una probabilità di risposta corretta compresa approssimativamente tra il 60% e il 70%\".\n\n**Opzione 4** - $\\text{Beta}(2, 8)$ (aspettativa di difficoltà):\nQuesta parametrizzazione è pertinente in presenza di difficoltà di apprendimento documentate. L'evidenza derivante da esperienze con studenti con profili analoghi indica prestazioni tipicamente modeste. L'interpretazione corrispondente è: \"Prevedo una probabilità di risposta corretta situata attorno al 20%\".\n:::\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Visualizzazione delle quattro distribuzioni Beta\ntheta <- seq(0, 1, length.out = 500)\n\n# Parametri delle quattro distribuzioni\nbeta_params <- list(\n  \"Beta(1,1)\\nIgnoranza totale\" = c(1, 1),\n  \"Beta(5,5)\\nPreferenza centrale\" = c(5, 5),\n  \"Beta(20,10)\\nAspettativa alta\" = c(20, 10),\n  \"Beta(2,8)\\nAspettativa bassa\" = c(2, 8)\n)\n\ndf_beta_examples <- data.frame()\nfor(nome in names(beta_params)) {\n  params <- beta_params[[nome]]\n  df_temp <- data.frame(\n    theta = theta,\n    Densita = dbeta(theta, params[1], params[2]),\n    Distribuzione = nome\n  )\n  df_beta_examples <- rbind(df_beta_examples, df_temp)\n}\n\nggplot(df_beta_examples, aes(x = theta, y = Densita, color = Distribuzione)) +\n  geom_line(linewidth = 1.2) +\n  facet_wrap(~ Distribuzione, scales = \"free_y\", ncol = 2) +\n  labs(\n    title = \"Distribuzioni Beta come rappresentazioni di stati di conoscenza iniziale\",\n    subtitle = \"Diverse configurazioni parametriche corrispondono a differenti credenze preliminari\",\n    x = expression(theta ~ \" (probabilità di risposta corretta)\"),\n    y = \"Densità di probabilità\"\n  ) +\n  theme_minimal() +\n  theme(legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![Rappresentazione grafica di diverse distribuzioni Beta come stati di conoscenza iniziale](03_equiprobability_combinatorics_bayesian_files/figure-html/fig-beta-distributions-1.png){#fig-beta-distributions fig-align='center' width=85%}\n:::\n:::\n\n\n### Proprietà intuitive della distribuzione Beta\n\n::: {.callout-tip title=\"Interpretazione intuitiva dei parametri α e β\"}\n**Forza delle credenze: $\\alpha + \\beta$**\n\nLa somma $\\alpha + \\beta$ determina il grado di concentrazione della distribuzione Beta e riflette la solidità delle nostre credenze preliminari. Valori elevati di questa somma producono distribuzioni marcatamente concentrate, indicando credenze ben definite e caratterizzate da bassa incertezza. Al contrario, valori ridotti generano distribuzioni ampie e diffuse, indicando credenze deboli e associate a un'elevata incertezza.\n\nDal punto di vista psicologico, la somma $\\alpha + \\beta$ quantifica l'entità dell'\"esperienza virtuale\" accumulata riguardo alla situazione in esame. La configurazione Beta(1, 1) corrisponde a una condizione di assenza di esperienza e di incertezza totale. Beta(10, 10) riflette un'esperienza moderata, con incertezza significativa persistente, mentre Beta(100, 100) indica un'esperienza sostanziale, accompagnata da una relativa certezza.\n\n**Posizione delle credenze: $\\alpha / (\\alpha + \\beta)$**\n\nLa media della distribuzione Beta, $\\mathbb{E}[\\theta] = \\frac{\\alpha}{\\alpha + \\beta}$, rappresenta il valore atteso per il parametro $\\theta$ in base al nostro stato di conoscenza. La configurazione Beta(6, 4), con media 0.6, esprime l'aspettativa che il valore $\\theta$ si collochi intorno al 60%. La configurazione Beta(3, 7), con media 0.3, suggerisce che il valore di $\\theta$ si aggiri intorno al 30%. Beta(5, 5), con media 0.5, indica che la credenza è che il valore di $\\theta$ sia prossimo al 50%.\n\n**Equilibrio delle credenze: simmetria e asimmetria**\n\nLa relazione tra $\\alpha$ e $\\beta$ determina la simmetria della distribuzione, riflettendo eventuali preferenze direzionali nelle nostre aspettative. Le distribuzioni simmetriche, con  $\\alpha = \\beta$, esprimono credenze bilanciate, senza preferenze per valori particolari di $\\theta$. Le distribuzioni asimmetriche con $\\alpha > \\beta$ manifestano una preferenza per valori elevati di $\\theta$, mentre quelle con $\\alpha < \\beta$ rivelano una preferenza per valori ridotti di $\\theta$.\n:::\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Visualizzazione dell'effetto di α + β sulla forma della distribuzione\ntheta <- seq(0, 1, length.out = 500)\n\n# Quattro distribuzioni con media identica (0.5) ma diversa concentrazione\nforza_credenze <- list(\n  \"Beta(1,1)\\nDebole (α+β=2)\" = c(1, 1),\n  \"Beta(5,5)\\nModerata (α+β=10)\" = c(5, 5),\n  \"Beta(20,20)\\nForte (α+β=40)\" = c(20, 20),\n  \"Beta(100,100)\\nMolto forte (α+β=200)\" = c(100, 100)\n)\n\ndf_forza <- data.frame()\nfor(nome in names(forza_credenze)) {\n  params <- forza_credenze[[nome]]\n  df_temp <- data.frame(\n    theta = theta,\n    Densita = dbeta(theta, params[1], params[2]),\n    Forza = nome\n  )\n  df_forza <- rbind(df_forza, df_temp)\n}\n\nggplot(df_forza, aes(x = theta, y = Densita, color = Forza)) +\n  geom_line(linewidth = 1.2) +\n  labs(\n    title = \"Effetto della forza delle credenze sulla distribuzione Beta\",\n    subtitle = \"Distribuzioni con media identica (0.5) ma diverso grado di certezza\",\n    x = expression(theta),\n    y = \"Densità di probabilità\"\n  ) +\n  theme_minimal() +\n  theme(legend.position = \"bottom\")\n```\n\n::: {.cell-output-display}\n![Effetto della forza delle credenze (α + β) sulla concentrazione della distribuzione Beta](03_equiprobability_combinatorics_bayesian_files/figure-html/fig-beta-strength-1.png){#fig-beta-strength fig-align='center' width=85%}\n:::\n:::\n\n\n### Definizione formale della distribuzione Beta\n\nDopo aver sviluppato un'intuizione concettuale, procediamo ora con la definizione matematica formale.\n\n::: {#def-beta-distribution}\n### Distribuzione Beta\n\nUna variabile casuale $\\theta$ segue una distribuzione **Beta** con parametri $\\alpha > 0$ e $\\beta > 0$, denotata come $\\theta \\sim \\text{Beta}(\\alpha, \\beta)$, se la sua funzione di densità di probabilità è data da:\n\n$$\nf(\\theta; \\alpha, \\beta) = \\frac{\\Gamma(\\alpha + \\beta)}{\\Gamma(\\alpha)\\Gamma(\\beta)} \\theta^{\\alpha-1} (1-\\theta)^{\\beta-1}, \\quad \\theta \\in [0, 1],\n$$\n\ndove $\\Gamma(\\cdot)$ rappresenta la funzione gamma, che generalizza il concetto di fattoriale ai numeri reali.\n\n**Proprietà fondamentali**:\n\n- **valore atteso**: $\\mathbb{E}[\\theta] = \\frac{\\alpha}{\\alpha + \\beta}$;\n- **moda**: $\\text{Mode}[\\theta] = \\frac{\\alpha - 1}{\\alpha + \\beta - 2}$ (definita per $\\alpha, \\beta > 1$);\n- **varianza**: $\\text{Var}(\\theta) = \\frac{\\alpha\\beta}{(\\alpha+\\beta)^2(\\alpha+\\beta+1)}$.\n\n**Interpretazione bayesiana**:\nI parametri $\\alpha$ e $\\beta$ ammettono un'interpretazione naturale in termini di evidenza pseudo-osservata:\n\n- $\\alpha - 1$: numero di successi virtuali nelle credenze preliminari;\n- $\\beta - 1$: numero di insuccessi virtuali nelle credenze preliminari;\n- $\\alpha + \\beta$: dimensione campionaria equivalente che quantifica la forza delle credenze iniziali.\n\n**Configurazioni parametriche notevoli**:\n\n- $\\text{Beta}(1, 1)$: Distribuzione *uniforme* sull'intervallo $[0, 1]$, corrispondente a uno stato di massima ignoranza;\n- $\\text{Beta}(0.5, 0.5)$: *Prior di Jeffreys*, caratterizzata da invarianza per riparametrizzazione;\n- $\\text{Beta}(\\alpha, \\beta)$ con $\\alpha = \\beta$: Distribuzioni *simmetriche* attorno al valore 0.5;\n- $\\text{Beta}(\\alpha, \\beta)$ con $\\alpha > \\beta$: Distribuzioni *asimmetriche* con preferenza per valori elevati di $\\theta$;\n- $\\text{Beta}(\\alpha, \\beta)$ con $\\alpha < \\beta$: Distribuzioni *asimmetriche* con preferenza per valori ridotti di $\\theta$.\n:::\n\n### Dalla Beta(1,1) all'aggiornamento bayesiano\n\nLa distribuzione $\\text{Beta}(1, 1)$ riveste particolare importanza poiché stabilisce un *collegamento fondamentale* tra il concetto di equiprobabilità discreta e il framework bayesiano continuo.\n\n::: {.callout-important title=\"Beta(1,1) come generalizzazione continua dell'equiprobabilità\"}\nLa distribuzione Beta(1, 1) coincide esattamente con la distribuzione uniforme sull'intervallo $[0, 1]$, caratterizzata dalla funzione di densità costante:\n\n$$\nf(\\theta) = 1 \\quad \\text{per ogni } \\theta \\in [0, 1].\n$$\n\n**Interpretazione epistemica**: questa configurazione implica che ogni possibile valore del parametro $\\theta$ sia credibile a priori con la stessa probabilità. Tale distribuzione rappresenta l'analogo continuo del principio di indifferenza tradizionalmente applicato ai contesti discreti.\n\n**Parallelismo concettuale tra i due dominii**:\n\n- nel caso discreto, l'equiprobabilità si esprime attraverso l'assegnazione $P(\\omega_i) = \\frac{1}{n}$ per ogni esito elementare $\\omega_i$ dello spazio campionario;\n- nel caso continuo, l'equiprobabilità si manifesta attraverso la funzione di densità costante $f(\\theta) = 1$ per ogni valore di $\\theta$ compreso tra 0 e 1.\n\nIn entrambi i contesti, queste rappresentazioni formalizzano uno stato di massima ignoranza epistemica o simmetria perfetta tra tutte le possibilità considerate, costituendo il punto di partenza neutrale per i processi inferenziali successivi.\n:::\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Visualizzazione della distribuzione Beta(1,1) come uniforme\ntheta <- seq(0, 1, length.out = 500)\nuniforme <- dbeta(theta, 1, 1)\n\ndf_uniforme <- data.frame(\n  theta = theta,\n  Densita = uniforme\n)\n\nggplot(df_uniforme, aes(x = theta, y = Densita)) +\n  geom_line(linewidth = 1.5, color = \"darkblue\") +\n  geom_hline(yintercept = 1, linetype = \"dashed\", color = \"red\", alpha = 0.6) +\n  annotate(\"text\", x = 0.5, y = 1.2, \n           label = \"Beta(1,1) ≡ Uniforme\\n(massima ignoranza epistemica)\", \n           size = 5, color = \"red\") +\n  ylim(0, 1.5) +\n  labs(\n    title = \"Beta(1,1): generalizzazione continua del principio di equiprobabilità\",\n    subtitle = \"Rappresentazione formale dello stato di massima ignoranza sul parametro θ\",\n    x = expression(theta ~ \" (probabilità ignota)\"),\n    y = \"Densità di probabilità\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![La distribuzione Beta(1,1) come caso particolare di distribuzione uniforme sull'intervallo [0,1]](03_equiprobability_combinatorics_bayesian_files/figure-html/fig-beta-uniform-1.png){#fig-beta-uniform fig-align='center' width=85%}\n:::\n:::\n\n\n### Dall'equiprobabilità discreta all'inferenza bayesiana: un esempio psicologico\n\n::: {.callout-note collapse=\"false\" title=\"Esempio completo: valutazione delle abilità in un test a scelta multipla\"}\n\n**Scenario sperimentale**: uno studente completa un test composto da 20 domande a scelta multipla con 4 opzioni ciascuna. L'obiettivo inferenziale consiste nello stimare la sua abilità latente $\\theta$, definita operativamente come la probabilità di fornire una risposta corretta.\n\n**Fase 1: Specificazione della distribuzione a priori**\n\nIn condizioni di risposte completamente casuali, il valore atteso di $\\theta$ sarebbe 0.25, corrispondente a una probabilità su quattro. Tuttavia, poiché il reale livello di preparazione dello studente rimane ignoto, adottiamo una distribuzione a priori che incorpori questa aspettativa conservando un'adeguata quantificazione dell'incertezza:\n\n$$\n\\theta \\sim \\text{Beta}(1, 3).\n$$\n\n**La giustificazione della scelta Beta(1,3)** si fonda su tre considerazioni fondamentali. Il valore atteso di $\\frac{1}{1+3} = 0.25$ risulta coerente con l'ipotesi di equiprobabilità delle opzioni di risposta. Inoltre, la varianza associata a questa parametrizzazione è sufficientemente elevata da riflettere adeguatamente l'incertezza relativa alla preparazione effettiva dello studente. Dal punto di vista epistemico, questa configurazione corrisponde a un'evidenza virtuale equivalente all'osservazione di 0 successi e 2 insuccessi.\n\n**Fase 2: Raccolta dei dati empirici**\n\nDalla somministrazione del test emergono i seguenti risultati empirici: 7 risposte corrette su 20 tentativi ($k = 7$, $n = 20$).\n\n**Fase 3: Aggiornamento bayesiano**\n\nIl modello Beta-Binomiale, che appartiene alla classe delle famiglie coniugate, permette un aggiornamento particolarmente elegante delle credenze attraverso la seguente regola:\n\n$$\n\\text{Prior: } \\theta \\sim \\text{Beta}(\\alpha, \\beta);\n$$\n$$\n\\text{Dati osservati: } k \\text{ successi su } n \\text{ prove};\n$$\n$$\n\\text{Posterior: } \\theta \\mid \\text{dati} \\sim \\text{Beta}(\\alpha + k, \\beta + n - k).\n$$\n\nApplicando questa regola al caso in esame, si ottiene:\n\n$$\n\\text{Posterior: } \\theta \\mid \\text{dati} \\sim \\text{Beta}(1 + 7, 3 + 13) = \\text{Beta}(8, 16).\n$$\n\n**Interpretazione della distribuzione a posteriori**:\n\nIl valore atteso della distribuzione a posteriori è pari a $\\frac{8}{8+16} = \\frac{8}{24} \\approx 0.33$. Questo valore indica un significativo aggiornamento delle credenze, che si spostano dalla stima a priori di 0.25 verso il dato empirico di 0.35 ($7/20$). Questo risultato esemplifica efficacemente il metodo bayesiano, in cui la distribuzione a posteriori rappresenta un compromesso ponderato tra le credenze iniziali e l'evidenza empirica osservata.\n:::\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Visualizzazione completa del processo inferenziale\ntheta <- seq(0, 1, length.out = 500)\n\n# Distribuzione a priori: Beta(1, 3)\nprior <- dbeta(theta, 1, 3)\n\n# Distribuzione a posteriori: Beta(8, 16) dopo 7 successi su 20 prove\nposterior <- dbeta(theta, 8, 16)\n\n# Funzione di verosimiglianza (scalata per visualizzazione)\nn <- 20; k <- 7\nlikelihood_prop <- dbeta(theta, k + 1, n - k + 1)\nlikelihood_prop <- likelihood_prop / max(likelihood_prop) * max(posterior) * 0.8\n\ndf_inferenza <- data.frame(\n  theta = theta,\n  Prior = prior,\n  Likelihood = likelihood_prop,\n  Posterior = posterior\n)\n\ndf_inferenza_long <- df_inferenza %>%\n  pivot_longer(cols = c(Prior, Likelihood, Posterior),\n               names_to = \"Distribuzione\", values_to = \"Densita\")\n\n# Calcolo dei parametri di riferimento\nmedia_prior <- 1/(1+3)\nmedia_posterior <- 8/(8+16)\nmedia_mle <- 7/20\n\nggplot(df_inferenza_long, aes(x = theta, y = Densita, color = Distribuzione)) +\n  geom_line(linewidth = 1.3) +\n  geom_vline(xintercept = 0.25, linetype = \"dashed\", alpha = 0.5, color = \"red\") +\n  geom_vline(xintercept = media_posterior, linetype = \"dashed\", alpha = 0.5, color = \"blue\") +\n  geom_vline(xintercept = media_mle, linetype = \"dotted\", alpha = 0.5, color = \"green\") +\n  annotate(\"text\", x = 0.25, y = max(posterior) * 0.95, \n           label = \"Prior\\n(0.25)\", hjust = 1.1, size = 3.5, color = \"red\") +\n  annotate(\"text\", x = media_posterior, y = max(posterior) * 0.95, \n           label = \"Posterior\\n(0.33)\", hjust = -0.1, size = 3.5, color = \"blue\") +\n  annotate(\"text\", x = media_mle, y = max(posterior) * 0.8, \n           label = \"MLE\\n(0.35)\", hjust = -0.1, size = 3.5, color = \"darkgreen\") +\n  labs(\n    title = \"Processo di aggiornamento bayesiano: dall'equiprobabilità alla stima parametrica\",\n    subtitle = \"Integrazione di credenze a priori e dati osservati (7 risposte corrette su 20)\",\n    x = expression(theta ~ \" (probabilità di risposta corretta)\"),\n    y = \"Densità di probabilità\",\n    color = \"Componente inferenziale\"\n  ) +\n  theme_minimal() +\n  theme(legend.position = \"top\")\n```\n\n::: {.cell-output-display}\n![Processo di aggiornamento bayesiano dalle credenze a priori basate sull'equiprobabilità alla stima a posteriori](03_equiprobability_combinatorics_bayesian_files/figure-html/fig-bayesian-update-1.png){#fig-bayesian-update fig-align='center' width=85%}\n:::\n:::\n\n\n**Analisi del processo inferenziale**:\n\nLa *distribuzione a priori* (in rosso) rappresenta le credenze iniziali basate sul principio di equiprobabilità delle opzioni di risposta, con un valore atteso di 0.25. La *funzione di verosimiglianza* (in verde) illustra la compatibilità dei dati osservati con i diversi valori possibili del parametro $\\theta$. La *distribuzione a posteriori* (in blu) sintetizza le credenze aggiornate che integrano coerentemente le informazioni a priori con l'evidenza empirica.\n\nDal punto di vista quantitativo, la media a posteriori di 0.33 costituisce un tipico compromesso bayesiano tra la stima a priori di 0.25 e la stima di massima verosimiglianza di 0.35. Un ulteriore aspetto significativo è la *riduzione dell'incertezza*: la distribuzione a posteriori presenta infatti una minore dispersione rispetto a quella a priori, riflettendo l'informazione aggiuntiva acquisita attraverso i dati osservati.\n\n### Intervallo di credibilità: quantificare l'incertezza\n\nUn vantaggio cruciale dell'approccio bayesiano è che possiamo quantificare direttamente l'incertezza attraverso gli *intervalli di credibilità*.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Intervallo di credibilità al 95%\nalpha_post <- 8\nbeta_post <- 16\nci_lower <- qbeta(0.025, alpha_post, beta_post)\nci_upper <- qbeta(0.975, alpha_post, beta_post)\n\ncat(\"=== RISULTATI DELL'INFERENZA BAYESIANA ===\\n\\n\")\n#> === RISULTATI DELL'INFERENZA BAYESIANA ===\ncat(\"Media posterior:\", round(alpha_post / (alpha_post + beta_post), 3), \"\\n\")\n#> Media posterior: 0.333\ncat(\"Intervallo di credibilità 95%: [\", \n    round(ci_lower, 3), \",\", round(ci_upper, 3), \"]\\n\\n\")\n#> Intervallo di credibilità 95%: [ 0.164 , 0.529 ]\ncat(\"Interpretazione bayesiana:\\n\")\n#> Interpretazione bayesiana:\ncat(\"Dopo aver osservato 7 risposte corrette su 20, siamo 95% certi\\n\")\n#> Dopo aver osservato 7 risposte corrette su 20, siamo 95% certi\ncat(\"(date le nostre assunzioni) che la vera abilità θ dello studente\\n\")\n#> (date le nostre assunzioni) che la vera abilità θ dello studente\ncat(\"sia compresa tra\", round(ci_lower, 3), \"e\", round(ci_upper, 3), \"\\n\\n\")\n#> sia compresa tra 0.164 e 0.529\ncat(\"Confronto con approccio frequentista:\\n\")\n#> Confronto con approccio frequentista:\ncat(\"Stima puntuale MLE:\", round(7/20, 3), \"(no quantificazione incertezza)\\n\")\n#> Stima puntuale MLE: 0.35 (no quantificazione incertezza)\ncat(\"Intervallo di confidenza (approssimato):\", \n    sprintf(\"[%.3f, %.3f]\", 7/20 - 1.96*sqrt((7/20)*(13/20)/20), \n                             7/20 + 1.96*sqrt((7/20)*(13/20)/20)))\n#> Intervallo di confidenza (approssimato): [0.141, 0.559]\n```\n:::\n\n\n::: {.callout-tip title=\"Differenza fondamentale: credibilità vs confidenza\"}\nL'*intervallo di credibilità bayesiano* al 95% consente l'affermazione diretta: \"Esiste una probabilità del 95% che $\\theta$ sia compreso nell'intervallo [0.18, 0.52]\". Questa formulazione esprime esplicitamente le nostre credenze aggiornate riguardo al parametro ignoto.\n\nAl contrario, l'*intervallo di confidenza frequentista* al 95% richiede l'interpretazione: \"Se l'esperimento fosse ripetuto infinite volte, il 95% degli intervalli così costruiti conterrebbe il vero valore di $\\theta$\". Questa affermazione caratterizza le proprietà a lungo termine della procedura di stima, senza quantificare direttamente le credenze riguardo al parametro specifico oggetto di studio.\n:::\n\n### Accumulazione di evidenza: aggiornamento sequenziale\n\nUn vantaggio particolarmente significativo dell'approccio bayesiano risiede nella capacità di **aggiornare le credenze in modo incrementale** man mano che nuovi dati diventano disponibili.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Simulazione di aggiornamento sequenziale\nset.seed(42)\n\n# \"Vera\" abilità dello studente (sconosciuta a noi)\ntheta_vero <- 0.4\n\n# Partiamo dalla prior Beta(1, 3)\nalpha <- 1\nbeta <- 3\n\n# Simuliamo 20 domande, una alla volta\nn_domande <- 20\nrisposte <- rbinom(n_domande, 1, theta_vero)\n\n# Tracciamo l'evoluzione della distribuzione posterior\ndf_evoluzione <- data.frame()\ntheta_grid <- seq(0, 1, length.out = 200)\n\nfor(i in 0:n_domande) {\n  if(i == 0) {\n    # Prior iniziale\n    dens <- dbeta(theta_grid, alpha, beta)\n    label <- \"Prior iniziale\"\n  } else {\n    # Aggiorna con la i-esima risposta\n    alpha <- alpha + risposte[i]\n    beta <- beta + (1 - risposte[i])\n    dens <- dbeta(theta_grid, alpha, beta)\n    label <- paste0(\"Dopo \", i, \" domande\")\n  }\n  \n  df_temp <- data.frame(\n    theta = theta_grid,\n    Densita = dens,\n    Momento = label,\n    n_osservazioni = i\n  )\n  df_evoluzione <- rbind(df_evoluzione, df_temp)\n}\n\n# Visualizza alcuni momenti chiave\nmomenti_chiave <- c(0, 5, 10, 15, 20)\ndf_chiave <- df_evoluzione %>% \n  filter(n_osservazioni %in% momenti_chiave)\n\nggplot(df_chiave, aes(x = theta, y = Densita, color = factor(n_osservazioni))) +\n  geom_line(linewidth = 1.2) +\n  geom_vline(xintercept = theta_vero, linetype = \"dashed\", color = \"black\", linewidth = 0.8) +\n  annotate(\"text\", x = theta_vero, y = max(df_chiave$Densita) * 0.9,\n           label = \"θ vero (0.4)\", hjust = -0.1, size = 4) +\n  labs(\n    title = \"Aggiornamento bayesiano sequenziale delle credenze\",\n    subtitle = \"Concentrazione progressiva delle distribuzioni a posteriori attorno al valore vero\",\n    x = expression(theta ~ \" (abilità)\"),\n    y = \"Densità di probabilità\",\n    color = \"Numero di domande\\nosservate\"\n  ) +\n  scale_color_brewer(palette = \"Set1\") +\n  theme_minimal() +\n  theme(legend.position = \"right\")\n```\n\n::: {.cell-output-display}\n![Evoluzione delle distribuzioni a posteriori durante l'accumulo sequenziale di dati](03_equiprobability_combinatorics_bayesian_files/figure-html/fig-sequential-update-1.png){#fig-sequential-update fig-align='center' width=85%}\n:::\n:::\n\n\n**Analisi del processo di aggiornamento sequenziale**:\n\nNella fase *iniziale*, le credenze sono caratterizzate da un'ampia dispersione e centrate sul valore di 0.25, riflettendo l'incertezza della distribuzione a priori. *Progressivamente*, con l'accumularsi dei dati osservati, la distribuzione a posteriori manifesta una duplice evoluzione: da un lato si osserva una marcata concentrazione della densità di probabilità, dall'altro uno spostamento progressivo verso il valore vero del parametro. Al *termine* del processo, dopo l'osservazione di 20 domande, le credenze risultano notevolmente concentrate attorno al valore $\\theta = 0.4$, dimostrando l'efficacia dell'aggiornamento bayesiano. Un aspetto fondamentale di questo processo è l'*indipendenza dall'ordine*: la distribuzione a posteriori finale dipende esclusivamente dal numero complessivo di successi e insuccessi osservati, non dalla sequenza temporale in cui questi si sono manifestati.\n\n## Applicazioni psicologiche\n\n### Test psicometrici: dalla conta alla modellazione IRT\n\nNella *Item Response Theory* (IRT), la probabilità di risposta corretta non costituisce una quantità fissa ma dipende da variabili latenti specifiche:\n\n- il livello di *abilità* dello studente ($\\theta$);\n- il grado di *difficoltà* dell'item ($b$);\n- ulteriori parametri psicometrici (capacità discriminativa, probabilità di guessing).\n\n**Modello 1PL (Rasch)**:\n$$\nP(\\text{corretto} \\mid \\theta, b) = \\frac{1}{1 + e^{-(θ - b)}}\n$$\n\nQuesto approccio rappresenta un *superamento concettuale* dell'equiprobabilità, poiché modella esplicitamente l'eterogeneità sistematica presente nei dati psicometrici.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Simulare risposte secondo modello Rasch\nset.seed(123)\n\nabilita_studenti <- rnorm(100, mean = 0, sd = 1)  # Studenti con abilità varie\ndifficolta_item <- c(-1, -0.5, 0, 0.5, 1)         # 5 item con difficoltà crescente\n\n# Funzione logistica (modello Rasch)\nprob_corretta <- function(theta, b) {\n  1 / (1 + exp(-(theta - b)))\n}\n\n# Simulare matrice risposte (100 studenti × 5 item)\nrisposte_IRT <- matrix(nrow = 100, ncol = 5)\nfor (i in 1:100) {\n  for (j in 1:5) {\n    p <- prob_corretta(abilita_studenti[i], difficolta_item[j])\n    risposte_IRT[i, j] <- rbinom(1, size = 1, prob = p)\n  }\n}\n\n# Analizzare proporzioni di successo per item\nprop_successo <- colMeans(risposte_IRT)\n\ndf_IRT <- data.frame(\n  Item = paste0(\"Item\", 1:5),\n  Difficolta = difficolta_item,\n  Proporzione_Successo = prop_successo\n)\n\ncat(\"Analisi IRT simulata:\\n\")\n#> Analisi IRT simulata:\nprint(df_IRT)\n#>    Item Difficolta Proporzione_Successo\n#> 1 Item1       -1.0                 0.63\n#> 2 Item2       -0.5                 0.56\n#> 3 Item3        0.0                 0.48\n#> 4 Item4        0.5                 0.43\n#> 5 Item5        1.0                 0.26\n\nggplot(df_IRT, aes(x = Difficolta, y = Proporzione_Successo)) +\n  geom_point(size = 4, color = \"darkblue\") +\n  geom_line(linewidth = 1, color = \"darkblue\") +\n  geom_hline(yintercept = 0.5, linetype = \"dashed\", alpha = 0.5) +\n  labs(\n    title = \"Item Response Theory: Relazione tra difficoltà e proporzione di successo\",\n    subtitle = \"Simulazione del modello Rasch (100 studenti, 5 item)\",\n    x = \"Difficoltà dell'item (b)\",\n    y = \"Proporzione di risposte corrette\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![Simulazione di un modello Rasch: relazione tra difficoltà degli item e proporzione di risposte corrette](03_equiprobability_combinatorics_bayesian_files/figure-html/fig-irt-simulation-1.png){#fig-irt-simulation fig-align='center' width=85%}\n:::\n:::\n\n\n**Implicazione bayesiana**: la probabilità di successo non rappresenta una quantità fissa (né equiprobabile né deterministica), ma assume un carattere *parametrico* che dipende da fattori latenti come l'abilità individuale e la difficoltà degli item. Il framework bayesiano consente di stimare questi parametri mantenendo una quantificazione esplicita dell'incertezza associata.\n\n### Pattern di risposta in questionari: oltre l'equiprobabilità\n\nNei questionari psicologici, come il Big Five Inventory o il Minnesota Multiphasic Personality Inventory, le distribuzioni delle risposte raramente seguono un pattern equiprobabile a causa della presenza di molteplici fattori distorsivi sistematici. Tra questi, emergono in particolare il bias di acquiescenza, che si manifesta con una tendenza sistematica a concordare con gli item indipendentemente dal loro contenuto, la desiderabilità sociale, che orienta le risposte verso opzioni percepite come socialmente accettabili o approvabili, e gli stili di risposta individuali, che danno origine a pattern di risposta personali e consistenti attraverso item e contesti differenti.\n\nL'adozione di un modello bayesiano fornisce un solido framework metodologico per stimare quantitativamente questi pattern sistematici e applicare correzioni appropriate che migliorino la validità delle misurazioni psicologiche.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Simulare bias di acquiescenza\nset.seed(42)\nn_risposte <- 100\n\n# Scenario 1: Senza bias (equiprobabile tra Agree/Disagree)\nrisposte_neutre <- sample(c(\"Agree\", \"Disagree\"), n_risposte, replace = TRUE)\n\n# Scenario 2: Con bias di acquiescenza (70% Agree)\nrisposte_biased <- sample(c(\"Agree\", \"Disagree\"), n_risposte, \n                          replace = TRUE, prob = c(0.7, 0.3))\n\n# Confronto\ncat(\"CONFRONTO TRA SCENARI: EQUIPROBABILITÀ VS BIAS DI ACQUIESCENZA\\n\\n\")\n#> CONFRONTO TRA SCENARI: EQUIPROBABILITÀ VS BIAS DI ACQUIESCENZA\ncat(\"Scenario 1 - Distribuzione neutra (equiprobabile):\\n\")\n#> Scenario 1 - Distribuzione neutra (equiprobabile):\nprint(table(risposte_neutre) / n_risposte)\n#> risposte_neutre\n#>    Agree Disagree \n#>     0.44     0.56\n\ncat(\"\\nScenario 2 - Distribuzione con bias di acquiescenza:\\n\")\n#> \n#> Scenario 2 - Distribuzione con bias di acquiescenza:\nprint(table(risposte_biased) / n_risposte)\n#> risposte_biased\n#>    Agree Disagree \n#>     0.63     0.37\n\ncat(\"\\nINFERENZA BAYESIANA SUL BIAS\\n\\n\")\n#> \n#> INFERENZA BAYESIANA SUL BIAS\n\n# Stima bayesiana della probabilità di \"Agree\" per Scenario 2\nn_agree <- sum(risposte_biased == \"Agree\")\nn_total <- length(risposte_biased)\n\n# Prior: Beta(1, 1) - equiprobabilità come punto di partenza\n# Posterior: Beta(1 + n_agree, 1 + n_total - n_agree)\nalpha_post <- 1 + n_agree\nbeta_post <- 1 + (n_total - n_agree)\n\ncat(\"Distribuzione a priori: Beta(1, 1) - assunzione iniziale di equiprobabilità\\n\")\n#> Distribuzione a priori: Beta(1, 1) - assunzione iniziale di equiprobabilità\ncat(\"Dati osservati:\", n_agree, \"risposte 'Agree' su\", n_total, \"osservazioni\\n\")\n#> Dati osservati: 63 risposte 'Agree' su 100 osservazioni\ncat(\"Distribuzione a posteriori: Beta(\", alpha_post, \",\", beta_post, \")\\n\\n\")\n#> Distribuzione a posteriori: Beta( 64 , 38 )\n\nmedia_post <- alpha_post / (alpha_post + beta_post)\nic_post <- qbeta(c(0.025, 0.975), alpha_post, beta_post)\n\ncat(\"Stima bayesiana della probabilità di 'Agree':\", round(media_post, 3), \"\\n\")\n#> Stima bayesiana della probabilità di 'Agree': 0.627\ncat(\"Intervallo di credibilità 95%: [\", round(ic_post[1], 3), \",\", round(ic_post[2], 3), \"]\\n\\n\")\n#> Intervallo di credibilità 95%: [ 0.532 , 0.718 ]\ncat(\"Conclusione inferenziale: L'ipotesi di equiprobabilità (p = 0.5) risulta incompatibile con i dati osservati.\\n\")\n#> Conclusione inferenziale: L'ipotesi di equiprobabilità (p = 0.5) risulta incompatibile con i dati osservati.\ncat(\"Esiste evidenza robusta della presenza di bias di acquiescenza nel campione.\\n\")\n#> Esiste evidenza robusta della presenza di bias di acquiescenza nel campione.\n```\n:::\n\n\n**Implicazioni metodologiche**: l'assunzione di equiprobabilità nelle risposte ai questionari psicologici conduce tipicamente a inferenze distorte e conclusioni erronee, compromettendo la validità delle misurazioni psicologiche. Il framework bayesiano offre invece un approccio alternativo e più sofisticato che permette di verificare empiricamente l'adeguatezza dell'ipotesi di equiprobabilità attraverso l'analisi di adattamento del modello. Questo framework consente inoltre di quantificare precisamente l'entità della deviazione dall'equiprobabilità, fornendo stime parametriche della magnitudine dei bias di risposta. Infine, esso supporta l'applicazione di correzioni sistematiche mediante l'incorporazione di modelli espliciti che rappresentano formalmente i meccanismi sottostanti ai bias di risposta.\n\n### Esempio avanzato: stima dell'efficacia di un intervento psicologico\n\n::: {.callout-note title=\"Caso di studio: valutazione dell'efficacia della CBT per il disturbo d'ansia\"}\n**Contesto clinico**: si desidera valutare l'efficacia di un intervento di terapia cognitivo-comportamentale (CBT) per il trattamento del disturbo d'ansia. La variabile outcome è definita come il raggiungimento di un miglioramento clinicamente significativo in un campione di pazienti trattati.\n\n**Domanda di ricerca**: qual è la vera probabilità di successo $\\theta$ associata all'intervento CBT?\n\n**Approccio bayesiano.**\n\nLa specificazione di una *distribuzione a priori informativa* si basa sull'evidenza consolidata in letteratura, che indica come gli interventi CBT mostrino tipicamente tassi di successo compresi tra il 60% e l'80%. Questa conoscenza pregressa viene incorporata attraverso una distribuzione Beta(60, 30), caratterizzata da un valore atteso di 60/90 ≈ 0.67 e in grado di catturare appropriatamente l'incertezza associata ai risultati degli studi precedenti.\n\nI *dati osservati* nel presente studio consistono in 45 successi registrati su un totale di 60 pazienti trattati.\n\nLa distribuzione *a posteriori* risulta quindi Beta(60 + 45, 30 + 15) = Beta(105, 45), sintetizzando coerentemente l'evidenza pregressa con i nuovi dati empirici.\n:::\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Prior informativa basata su letteratura\nalpha_prior <- 60\nbeta_prior <- 30\n\n# Dati osservati\nn_successi <- 45\nn_pazienti <- 60\n\n# Posterior\nalpha_posterior <- alpha_prior + n_successi\nbeta_posterior <- beta_prior + (n_pazienti - n_successi)\n\n# Visualizzazione\ntheta <- seq(0, 1, length.out = 500)\n\nprior_cbt <- dbeta(theta, alpha_prior, beta_prior)\nposterior_cbt <- dbeta(theta, alpha_posterior, beta_posterior)\n\ndf_cbt <- data.frame(\n  theta = theta,\n  Prior = prior_cbt,\n  Posterior = posterior_cbt\n)\n\ndf_cbt_long <- df_cbt %>%\n  pivot_longer(cols = c(Prior, Posterior),\n               names_to = \"Distribuzione\", values_to = \"Densita\")\n\nmedia_prior_cbt <- alpha_prior / (alpha_prior + beta_prior)\nmedia_post_cbt <- alpha_posterior / (alpha_posterior + beta_posterior)\n\nggplot(df_cbt_long, aes(x = theta, y = Densita, color = Distribuzione)) +\n  geom_line(linewidth = 1.3) +\n  geom_vline(xintercept = media_prior_cbt, linetype = \"dashed\", color = \"red\", alpha = 0.6) +\n  geom_vline(xintercept = media_post_cbt, linetype = \"dashed\", color = \"blue\", alpha = 0.6) +\n  geom_vline(xintercept = n_successi/n_pazienti, linetype = \"dotted\", color = \"green\", alpha = 0.6) +\n  annotate(\"text\", x = media_prior_cbt, y = max(posterior_cbt) * 0.9,\n           label = sprintf(\"Prior\\n(%.2f)\", media_prior_cbt), hjust = 1.1, size = 3.5) +\n  annotate(\"text\", x = media_post_cbt, y = max(posterior_cbt) * 0.9,\n           label = sprintf(\"Posterior\\n(%.2f)\", media_post_cbt), hjust = -0.1, size = 3.5) +\n  labs(\n    title = \"Stima bayesiana dell'efficacia della terapia cognitivo-comportamentale\",\n    subtitle = sprintf(\"Integrazione di evidenza pregressa (prior) con dati osservati (%d successi su %d pazienti)\", \n                       n_successi, n_pazienti),\n    x = expression(theta ~ \" (probabilità di successo del trattamento)\"),\n    y = \"Densità di probabilità\",\n    color = \"Distribuzione\"\n  ) +\n  theme_minimal() +\n  theme(legend.position = \"top\")\n```\n\n::: {.cell-output-display}\n![Stima bayesiana dell'efficacia della terapia cognitivo-comportamentale per il disturbo d'ansia](03_equiprobability_combinatorics_bayesian_files/figure-html/fig-cbt-efficacy-1.png){#fig-cbt-efficacy fig-align='center' width=85%}\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```\n#> RISULTATI DELL'INFERENZA BAYESIANA\n#> ===================================\n#> DISTRIBUZIONE A PRIORI (basata su letteratura):\n#>   Valore atteso:  0.667\n#>   Intervallo di credibilità 95%: [ 0.567 ,  0.76 ]\n#> EVIDENZA EMPIRICA OSSERVATA:\n#>   Successi osservati:  45 / 60  =  0.75\n#> DISTRIBUZIONE A POSTERIORI (sintesi bayesiana):\n#>   Valore atteso:  0.7\n#>   Intervallo di credibilità 95%: [ 0.625 ,  0.77 ]\n#> INTERPRETAZIONE CLINICA:\n#> L'integrazione dell'evidenza pregressa con i dati del presente studio consente di stimare\n#> una probabilità di successo della CBT pari a  0.7  con un intervallo\n#> di credibilità 95% compreso tra  0.625  e  0.77 .\n#> Questa stima rappresenta una sintesi bayesiana che bilancia consapevolmente la conoscenza\n#> accumulata dalla letteratura con l'evidenza specifica del campione in esame.\n```\n:::\n\n\n## Esercizi guidati\n\n### Esercizio 1: Urna con composizione ignota\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Urna con composizione ignota: R rosse, B bianche (R + B = 10)\n# Osserviamo 3 estrazioni con reinserimento: R, R, B\n\n# Prior uniforme su R: R ~ Uniform(0, 10)\n# Likelihood: dato R, prob di osservare RRB\n\nset.seed(123)\nR_values <- 0:10\nn_estrazioni <- 3\ndati <- c(\"R\", \"R\", \"B\")\n\n# Calcolare likelihood per ogni valore di R\nlikelihoods <- numeric(11)\nfor (r in R_values) {\n  p_r <- r / 10\n  # P(RRB | R) = p_r * p_r * (1 - p_r)\n  likelihoods[r + 1] <- p_r^2 * (1 - p_r)\n}\n\n# Prior uniforme\nprior <- rep(1/11, 11)\n\n# Posterior (proporzionale a prior × likelihood, poi normalizzare)\nposterior <- prior * likelihoods\nposterior <- posterior / sum(posterior)\n\ndf_esercizio1 <- data.frame(\n  R_rosse = R_values,\n  Prior = prior,\n  Likelihood = likelihoods / max(likelihoods),  # scala per vis.\n  Posterior = posterior\n)\n\ncat(\"Distribuzione posterior per numero di palline rosse:\\n\")\n#> Distribuzione posterior per numero di palline rosse:\nprint(round(df_esercizio1[, c(\"R_rosse\", \"Posterior\")], 4))\n#>    R_rosse Posterior\n#> 1        0    0.0000\n#> 2        1    0.0109\n#> 3        2    0.0388\n#> 4        3    0.0764\n#> 5        4    0.1164\n#> 6        5    0.1515\n#> 7        6    0.1745\n#> 8        7    0.1782\n#> 9        8    0.1552\n#> 10       9    0.0982\n#> 11      10    0.0000\n\n# Valore più probabile (moda posterior)\nmoda_post <- R_values[which.max(posterior)]\ncat(\"\\nStima MAP (massimo a posteriori): R =\", moda_post, \"\\n\")\n#> \n#> Stima MAP (massimo a posteriori): R = 7\ncat(\"Media posterior:\", round(sum(R_values * posterior), 2), \"\\n\")\n#> Media posterior: 5.96\n\n# Visualizzazione\ndf_ex1_long <- df_esercizio1 %>%\n  pivot_longer(cols = c(Prior, Posterior),\n               names_to = \"Tipo\", values_to = \"Probabilita\")\n\nggplot(df_ex1_long, aes(x = R_rosse, y = Probabilita, fill = Tipo)) +\n  geom_col(position = \"dodge\", alpha = 0.7) +\n  labs(\n    title = \"Inferenza bayesiana: composizione urna ignota\",\n    subtitle = \"Dati: 3 estrazioni con reinserimento (R, R, B)\",\n    x = \"Numero di palline rosse (R)\",\n    y = \"Probabilità\"\n  ) +\n  scale_fill_brewer(palette = \"Set1\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](03_equiprobability_combinatorics_bayesian_files/figure-html/unnamed-chunk-9-1.png){fig-align='center' width=85%}\n:::\n:::\n\n\n## Riflessioni conclusive {.unnumbered .unlisted}\n\nIn questo capitolo abbiamo analizzato il ruolo dell'equiprobabilità all'interno del framework bayesiano, mostrando come il calcolo combinatorio e la distribuzione Beta si integrino in un'unica visione coerente e unificata dell'inferenza probabilistica.\n\nL'equiprobabilità non è una proprietà intrinseca del mondo fisico, ma emerge da uno stato di simmetria epistemica formalizzato attraverso il principio di indifferenza. La formula classica dei \"casi favorevoli sui casi possibili\" rappresenta dunque un caso speciale valido esclusivamente quando l'ignoranza si distribuisce in modo simmetrico e sussistono ragioni fondate per presupporre una corrispondente simmetria fisica.\n\nIl calcolo combinatorio svolge il ruolo di strumento di modellazione bayesiana, in cui ciascuna formula incorpora specifiche assunzioni di equiprobabilità su spazi di configurazione definiti. Le permutazioni presuppongono l'equiprobabilità di tutti i possibili ordinamenti, le disposizioni assumono l'equiprobabilità delle sequenze ordinate e le combinazioni postulano l'equiprobabilità dei sottoinsiemi non ordinati.\n\nTuttavia, l'equiprobabilità decade inevitabilmente in presenza di informazioni asimmetriche, come differenze di peso, variabilità di difficoltà o relazioni di dipendenza. In tali circostanze, è necessario adottare modelli parametrici più sofisticati in grado di catturare queste complessità.\n\nLa transizione dal discreto al continuo trova nella distribuzione Beta la sua naturale generalizzazione. La distribuzione Beta(1,1) corrisponde alla distribuzione uniforme, che rappresenta lo stato di massima ignoranza, mentre le distribuzioni Beta(α, β) parametrizzano credenze caratterizzate da una \"forza\" data da α + β. L'aggiornamento bayesiano consente il passaggio dalle credenze a priori a quelle a posteriori mediante l'applicazione coerente del teorema di Bayes.\n\nNelle applicazioni psicologiche, dalla teoria della risposta agli item allo studio dei bias di risposta, dalla valutazione degli interventi clinici all'analisi dei questionari, la condizione di equiprobabilità risulta raramente soddisfatta. Il framework bayesiano fornisce tuttavia gli strumenti concettuali e computazionali per modellare queste situazioni complesse e stimare i parametri rilevanti, mantenendo una quantificazione esplicita dell'incertezza.\n\nL'approccio bayesiano consente una transizione concettuale naturale dall'equiprobabilità, implementata attraverso prior uniformi che rappresentano lo stato di massima ignoranza, all'aggiornamento delle credenze basato sull'osservazione di dati empirici. Questo processo genera distribuzioni a posteriori che quantificano formalmente l'incertezza residua sui parametri di interesse e supporta un accumulo sequenziale di evidenza attraverso aggiornamenti iterativi.\n\nQuesto approccio supera i limiti intrinseci dell'approccio frequentista classico, che risulta inadeguato a trattare eventi singolari non ripetibili, a quantificare l'incertezza parametrica, a supportare aggiornamenti sequenziali delle credenze e a integrare sistematicamente le conoscenze pregresse nell'inferenza statistica.\n\nNei prossimi capitoli, questo framework teorico verrà applicato allo studio della probabilità condizionata, che funge da meccanismo fondamentale per l'aggiornamento delle credenze, e al teorema di Bayes, che emerge come principio unificante dell'inferenza probabilistica in condizioni di incertezza.\n\n## Esercizi {.unnumbered}\n\n::: {.callout-important title=\"Problemi\" collapse=\"true\"}\n\n### Esercizi concettuali\n\n1. Spiega perché la formula \"casi favorevoli / casi totali\" è un caso speciale dell'approccio bayesiano, non una definizione indipendente.\n\n2. Un dado ha 6 facce. Quando è legittimo assegnare $P(\\text{faccia} = i) = 1/6$ per ogni $i$? Quando non lo è?\n\n3. Il principio di indifferenza sembra paradossale: due persone con le stesse informazioni dovrebbero avere le stesse credenze? Discuti.\n\n4. In che modo l'approccio bayesiano risolve (o evita) il paradosso di Bertrand?\n\n5. Perché nella pratica psicologica passiamo rapidamente dalla \"conta equiprobabile\" alla stima parametrica?\n\n### Esercizi su calcolo combinatorio (prospettiva bayesiana)\n\n6. In un esperimento di percezione, 8 stimoli devono essere presentati in ordine casuale. \n   a) Quanti ordini diversi sono possibili? \n   b) Qual è la probabilità di un ordine specifico sotto equiprobabilità?\n   c) Se sappiamo che alcuni ordini causano effetti di interferenza, è ancora appropriato assumere equiprobabilità?\n\n7. Da un gruppo di 15 pazienti in terapia di gruppo:\n   a) Quanti sottogruppi di 5 persone possiamo formare?\n   b) Sotto quali condizioni è ragionevole assumere che ogni sottogruppo sia equiprobabile?\n   c) Quali fattori psicologici potrebbero violare l'equiprobabilità?\n\n8. Un test ha 10 domande Vero/Falso. \n   a) Assumendo che uno studente risponda a caso (equiprobabilità), quante configurazioni di risposte sono possibili?\n   b) Qual è la probabilità di ottenere esattamente 7 risposte corrette?\n   c) Se lo studente ha studiato un po', come cambierebbe il nostro modello probabilistico?\n\n### Esercizi sulla distribuzione Beta\n\n9. Interpreta intuitivamente (senza formule) cosa rappresentano le seguenti distribuzioni Beta:\n   a) Beta(1, 1)\n   b) Beta(10, 10)\n   c) Beta(80, 20)\n   d) Beta(2, 8)\n\n10. Confronta Beta(5, 5) con Beta(50, 50):\n    a) Quale ha media più alta?\n    b) Quale rappresenta credenze più forti?\n    c) Visualizza entrambe e discuti le differenze\n\n11. Un ricercatore vuole stimare la proporzione di successo di un nuovo trattamento. Ha letto che trattamenti simili hanno successo nel 30-40% dei casi. Proponi una prior Beta appropriata e giustifica la scelta dei parametri.\n\n12. **Urna ignota**: Estraggo 10 volte con reinserimento, ottengo 7R e 3B. Usando prior $\\text{Beta}(1,1)$ su $\\theta = P(\\text{rossa})$:\n    a) Calcola il posterior\n    b) Qual è l'intervallo di credibilità al 95%?\n    c) Confronta con un approccio che usa prior Beta(5, 5)\n\n### Esercizi applicati (psicologia)\n\n13. **Questionario Big Five**: Item con 5 opzioni (Strongly Disagree ... Strongly Agree). Sotto equiprobabilità, ogni opzione dovrebbe essere scelta nel 20% dei casi. Una simulazione (N=200 rispondenti) mostra:\n    - Opzione 1: 10%\n    - Opzione 2: 15%\n    - Opzione 3: 30%\n    - Opzione 4: 25%\n    - Opzione 5: 20%\n    \n    a) L'equiprobabilità è supportata dai dati?\n    b) Proponi un modello bayesiano alternativo che catturi il bias verso l'opzione centrale\n    c) Come potresti usare la distribuzione Dirichlet per modellare questo scenario?\n\n14. **Test a scelta multipla**: 30 domande, 4 opzioni. Studente che \"non ha studiato\".\n    a) Proponi una prior Beta appropriata per la probabilità di rispondere correttamente\n    b) Lo studente ottiene 12 risposte corrette. Calcola il posterior\n    c) Calcola l'intervallo di credibilità al 95%\n    d) Confronta con la stima puntuale frequentista $\\hat{p} = 12/30$\n\n15. **Pattern di risposta con bias**: In un questionario di personalità (20 item binari), un partecipante risponde \"Sì\" a 18 item.\n    a) Sotto equiprobabilità, qual è la probabilità di osservare 18+ \"Sì\"?\n    b) Usa un modello Beta-Binomiale per stimare la probabilità individuale di rispondere \"Sì\"\n    c) L'equiprobabilità è compatibile con i dati?\n\n16. **Efficacia di intervento con prior informativa**: Stai valutando un nuovo protocollo di mindfulness. La letteratura suggerisce che interventi simili hanno tassi di successo tra 50-70%.\n    a) Proponi una prior Beta che rifletta questa conoscenza\n    b) Osservi 28 successi su 40 pazienti. Calcola il posterior\n    c) Confronta il risultato con quello che otterresti usando una prior non informativa Beta(1,1)\n    d) Discuti quando è appropriato usare prior informative vs non informative\n\n### Esercizi computazionali\n\n17. Scrivi una funzione R che:\n    - Input: prior Beta(α, β), n successi osservati, n prove totali\n    - Output: posterior, media, IC 95%, grafico prior/posterior\n    - Testa con vari esempi psicologici\n\n18. **Simulazione di aggiornamento sequenziale**: \n    - Simula un esperimento dove osservi 100 risposte binarie (θ vero = 0.6)\n    - Parti da Beta(1,1)\n    - Aggiorna la distribuzione dopo ogni osservazione\n    - Visualizza come la posterior si concentra intorno a θ = 0.6\n\n19. **Confronto prior informative vs non informative**:\n    - Genera dati da Binomial(n=20, θ=0.7)\n    - Stima θ usando: (a) Beta(1,1), (b) Beta(10,5), (c) Beta(100,50)\n    - Confronta i posteriori e discuti l'effetto della prior\n\n20. **Paradosso del compleanno bayesiano**:\n    - Simula n persone con compleanni casuali (365 giorni)\n    - Stima la probabilità di almeno 2 compleanni coincidenti\n    - Usa approccio bayesiano per quantificare l'incertezza\n    - Confronta con calcolo analitico $1 - \\frac{365!}{365^n(365-n)!}$\n\n:::\n\n::: {.callout-tip title=\"Soluzioni selezionate\" collapse=\"true\"}\n\n### Soluzioni esercizi concettuali\n\n1. La formula deriva dall'applicazione del principio di indifferenza (credenza 1/n per ogni esito) combinato con l'assioma di additività. Non è una definizione, ma una **conseguenza** di assiomi + assunzione epistemica di simmetria.\n\n2. **Legittimo** quando: dado regolare, lanciato equamente, nessuna informazione sullo stato. **Non legittimo** quando: dado truccato, conosciamo pesi, o abbiamo osservato pattern (es. 100 lanci, mai uscito 6).\n\n3. Non è paradossale: il bayesianesimo è soggettivo ma razionale. Con identiche informazioni, agenti razionali *dovrebbero* convergere. Divergenze riflettono differenze informative nascoste o irrazionalità.\n\n4. Il paradosso nasce dall'ambiguità su quale parametrizzazione usare. La soluzione bayesiana: specificare esplicitamente la prior appropriata al contesto (es. se produciamo lati uniformemente, prior uniforme sul lato; se produciamo volumi uniformemente, prior adeguata al volume).\n\n5. Perché: (a) equiprobabilità è rara in psicologia, (b) vogliamo quantificare incertezza sui parametri, (c) aggiornamento sequenziale richiede approccio parametrico, (d) framework bayesiano permette integrazione di conoscenze pregresse.\n\n### Soluzioni calcolo combinatorio\n\n6. a) $8! = 40,320$ ordini\n   b) $P(\\text{ordine specifico}) = 1/40,320 \\approx 0.000025$\n   c) No, se alcuni ordini causano interferenza, dobbiamo modellare probabilità diverse per ordini diversi\n\n7. a) $\\binom{15}{5} = 3,003$ sottogruppi\n   b) Equiprobabilità ragionevole se: nessuna informazione su compatibilità, caratteristiche simili, assegnazione casuale\n   c) Fattori che violano equiprobabilità: personalità incompatibili, relazioni pregresse, livelli diversi di gravità dei sintomi\n\n8. a) $2^{10} = 1,024$ configurazioni\n   b) $P(7 \\text{ corrette}) = \\binom{10}{7} (0.5)^{10} = 120/1024 \\approx 0.117$\n   c) Modello con $\\theta > 0.5$, es. Beta-Binomiale con prior centrata su valore più alto\n\n### Soluzioni sulla Beta\n\n9. a) Beta(1,1): massima ignoranza, tutti i valori equiprobabili\n   b) Beta(10,10): credenza moderata, media 0.5, qualche certezza\n   c) Beta(80,20): forte credenza verso valori alti (media 0.8)\n   d) Beta(2,8): preferenza verso valori bassi (media 0.2)\n\n10. a) Stessa media (0.5)\n    b) Beta(50,50) rappresenta credenze molto più forti (meno incertezza)\n\n12. ```r\n    # a) Posterior: Beta(1+7, 1+3) = Beta(8, 4)\n    alpha_post <- 8; beta_post <- 4\n    \n    # b) IC 95%\n    qbeta(c(0.025, 0.975), alpha_post, beta_post)  # [0.36, 0.86]\n    \n    # c) Con prior Beta(5, 5):\n    # Posterior: Beta(5+7, 5+3) = Beta(12, 8)\n    # IC 95%: [0.38, 0.78] (più stretto, perché prior più informativa)\n    ```\n\n### Soluzioni applicazioni psicologiche\n\n14. ```r\n    # a) Prior: Beta(1, 3) - media 0.25 (equiprobabilità con 4 opzioni)\n    # b) Posterior: Beta(1+12, 3+18) = Beta(13, 21)\n    #    Media: 13/34 ≈ 0.382\n    # c) IC 95%: [0.24, 0.54]\n    # d) Stima puntuale: 12/30 = 0.4 (no quantificazione incertezza)\n    ```\n\n15. ```r\n    # a) Sotto equiprobabilità (p=0.5):\n    pbinom(17, 20, 0.5, lower.tail = FALSE)  # ≈ 0.0002 (molto bassa!)\n    \n    # b) Prior Beta(1,1), dati: 18 successi su 20\n    #    Posterior: Beta(19, 3)\n    #    Media: 19/22 ≈ 0.86\n    #    IC 95%: [0.68, 0.96]\n    \n    # c) No, equiprobabilità non compatibile. Forte evidenza di bias.\n    ```\n\n:::\n\n## Bibliografia {.unnumbered .unlisted}\n",
    "supporting": [
      "03_equiprobability_combinatorics_bayesian_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}