{
  "hash": "7e04d3af916d863095c9ba87ef5b4288",
  "result": {
    "engine": "knitr",
    "markdown": "# Proprietà della verosimiglianza e aggiornamento bayesiano {#sec-likelihood-properties}\n\n## Introduzione {.unnumbered .unlisted}\n\nNel capitolo precedente abbiamo introdotto la funzione di verosimiglianza come lo strumento che quantifica la compatibilità relativa tra i dati osservati e i possibili valori dei parametri di un modello. Attraverso esempi concreti, abbiamo osservato alcune sue caratteristiche ricorrenti: la verosimiglianza tende a concentrarsi attorno a un valore ben definito, diventa progressivamente più stretta con l’aumentare della dimensione del campione e, per campioni sufficientemente ampi, assume una forma approssimativamente gaussiana.\n\nQueste osservazioni sollevano naturalmente alcune domande di fondo: *perché la verosimiglianza si comporta in questo modo?* E, soprattutto, *in che modo queste proprietà influenzano la costruzione e l’evoluzione della distribuzione a posteriori nell’inferenza bayesiana?*\n\nIl presente capitolo affronta queste domande fornendo una lettura teorica unificante dei fenomeni osservati. Mostreremo che il comportamento della verosimiglianza non è accidentale, ma riflette regolarità matematiche profonde che governano il comportamento delle statistiche campionarie e il flusso di informazione dai dati ai parametri. In particolare, vedremo perché la verosimiglianza tende a concentrarsi attorno al valore corretto del parametro e perché la sua informatività cresce al crescere del numero di osservazioni disponibili.\n\nIn questa prospettiva, l’aggiornamento bayesiano potrà essere reinterpretato come un processo di integrazione dell’informazione, in cui la verosimiglianza e la distribuzione a priori contribuiscono in modo complementare alla forma finale della distribuzione a posteriori. Questa lettura mette in evidenza come l’evidenza empirica e la conoscenza pregressa non siano in competizione, ma cooperino nella costruzione dell’inferenza.\n\nInfine, discuteremo il ruolo di due risultati fondamentali della teoria della probabilità, ovvero la **Legge dei Grandi Numeri** e il **Teorema del Limite Centrale**, che aiutano a comprendere il comportamento asintotico dell’inferenza bayesiana. Senza entrare in dimostrazioni formali, useremo questi teoremi per spiegare perché, al crescere dei dati, la distribuzione a posteriori tende a concentrarsi attorno al valore vero del parametro e perché, in molti contesti, essa può essere ben approssimata da una distribuzione gaussiana, indipendentemente dalla forma iniziale del prior.\n\n::: {.callout-tip collapse=\"true\"}\n## Prerequisiti\n\nPer seguire questo capitolo è necessario aver letto:\n\n- @sec-prob-bayes-theorem\n- @sec-prob-inference-uncertainty\n- @sec-prob-discr-distr\n- @sec-prob-cont-distr\n- @sec-prob-likelihood — **fondamentale**\n\nQuesto capitolo completa lo studio della verosimiglianza, introducendo score function, informazione di Fisher, coniugazione e fornendo gli strumenti operativi per l'inferenza bayesiana parametrica.\n\nConoscenze matematiche richieste:\n\n- @sec-apx-calculus - per derivate e integrali della verosimiglianza\n:::\n\n### Panoramica del capitolo {.unnumbered .unlisted}\n\n- Collegamento tra proprietà della media campionaria e forma della verosimiglianza.\n- Precisione come misura di informatività e regola di combinazione delle precisioni.\n- Aggiornamento bayesiano nel caso gaussiano: formula esplicita per la distribuzione a posteriori.\n- Legge dei Grandi Numeri e convergenza della distribuzione a posteriori.\n- Teorema del Limite Centrale e approssimazione normale della distribuzione a posteriori.\n- Combinazione di evidenze da studi multipli.\n- Limiti dell'inferenza: distinzione tra incertezza campionaria e distorsioni sistematiche.\n\n::: {.callout-caution collapse=true title=\"Preparazione del Notebook\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhere::here(\"code\", \"_common.R\") |> \n  source()\nlibrary(patchwork)\n\n# Riapplica il tema per sicurezza\napply_visual_theme()\n```\n:::\n\n:::\n\n## Dalla media campionaria alla verosimiglianza\n\n### Il problema inferenziale\n\nConsideriamo un problema concreto: stimare la prevalenza $\\theta$ di sintomi depressivi clinicamente rilevanti nella popolazione studentesca universitaria. Poiché non è possibile osservare l’intera popolazione, raccogliamo un campione di $n$ studenti e registriamo, per ciascuno, la presenza (1) o assenza (0) del sintomo.\n\nDal punto di vista probabilistico, le osservazioni\n$X_1, X_2, \\ldots, X_n$ possono essere modellate come variabili casuali indipendenti e identicamente distribuite (i.i.d.) con distribuzione di Bernoulli:\n\n$$\nX_i \\mid \\theta \\sim \\text{Bernoulli}(\\theta).\n$$\n\nL’informazione contenuta nel campione viene tipicamente riassunta dalla **proporzione campionaria**\n\n$$\n\\bar{X} = \\frac{1}{n}\\sum_{i=1}^n X_i,\n$$\nche rappresenta la frazione di studenti nel campione che presentano il sintomo.\n\nPrima di osservare i dati, le nostre conoscenze su $\\theta$ possono essere rappresentate da una distribuzione a priori. Dopo l’osservazione, l’aggiornamento bayesiano avviene tramite la **verosimiglianza**.\nPer capire *perché* la verosimiglianza ha la forma che osserviamo nei grafici, dobbiamo quindi capire *come si comporta* la media campionaria $\\bar{X}$.\n\n### Perché la verosimiglianza è centrata nel punto giusto\n\nUn primo fatto fondamentale è che, in media, la proporzione campionaria coincide con il parametro che vogliamo stimare.\n\n::: {#thm-expval-mean}\nPer osservazioni i.i.d. con $\\mathbb{E}[X_i \\mid \\theta] = \\theta$:\n\n$$\n\\mathbb{E}[\\bar{X} \\mid \\theta] = \\theta.\n$$\n:::\n\n**Interpretazione.**\nSe potessimo ripetere l’esperimento molte volte, la media delle proporzioni osservate coinciderebbe con il valore vero di $\\theta$. In altre parole, $\\bar{X}$ non tende sistematicamente a sovrastimare o sottostimare il parametro.\n\n**Conseguenza per la verosimiglianza.**\nPoiché la funzione di verosimiglianza riflette quanto i dati sono compatibili con ciascun valore di $\\theta$, questa proprietà spiega perché il **picco della verosimiglianza** si trovi in corrispondenza della proporzione osservata $\\bar{X}$. La verosimiglianza è quindi *centrata correttamente*.\n\n::: {.callout-note collapse=\"true\" title=\"Dimostrazione\"}\n$$\n\\mathbb{E}[\\bar{X} \\mid \\theta]\n= \\mathbb{E}\\!\\left[\\frac{1}{n}\\sum_{i=1}^n X_i\\right]\n= \\frac{1}{n}\\sum_{i=1}^n \\mathbb{E}[X_i \\mid \\theta]\n= \\theta.\n$$\n:::\n\n### Perché la verosimiglianza diventa più stretta con più dati\n\nUn secondo fatto cruciale riguarda **quanto** la proporzione campionaria può fluttuare attorno al suo valore medio.\n\n::: {#thm-var-mean}\nPer osservazioni i.i.d. con varianza $\\text{Var}(X_i \\mid \\theta) = \\sigma^2$:\n\n$$\n\\text{Var}(\\bar{X} \\mid \\theta) = \\frac{\\sigma^2}{n}.\n$$\n:::\n\n**Interpretazione.**\nAll’aumentare del numero di osservazioni, la variabilità della media campionaria diminuisce. Ogni nuovo dato contribuisce a “stabilizzare” la stima.\n\n**Conseguenza per la verosimiglianza.**\nPoiché la verosimiglianza riflette l’incertezza sulla posizione del parametro, questa proprietà spiega perché la funzione di verosimiglianza diventa sempre più **concentrata** al crescere di $n$. In termini intuitivi, più dati osserviamo, meno valori di $\\theta$ restano compatibili con l’evidenza.\n\n::: {.callout-note collapse=\"true\" title=\"Dimostrazione\"}\n$$\n\\text{Var}(\\bar{X} \\mid \\theta)\n= \\frac{1}{n^2}\\sum_{i=1}^n \\text{Var}(X_i \\mid \\theta)\n= \\frac{\\sigma^2}{n}.\n$$\n:::\n\n### Il caso Bernoulliano: quanta incertezza rimane?\n\nNel caso delle variabili di Bernoulli, la variabilità di ciascuna osservazione dipende dal valore stesso di $\\theta$:\n\n$$\n\\text{Var}(X_i \\mid \\theta) = \\theta(1-\\theta).\n$$\n\nDi conseguenza, la variabilità della proporzione campionaria è:\n\n$$\n\\text{Var}(\\bar{X} \\mid \\theta) = \\frac{\\theta(1-\\theta)}{n}.\n$$\n\nLa quantità\n\n$$\n\\text{SE}(\\bar{X}) = \\sqrt{\\frac{\\theta(1-\\theta)}{n}}\n$$\nè detta **errore standard** e rappresenta l’ordine di grandezza delle fluttuazioni attese di $\\bar{X}$ attorno al valore vero di $\\theta$.\n\nQuesta espressione ha una forma particolarmente informativa:\n\n* l’incertezza è massima quando $\\theta = 0.5$;\n* diminuisce rapidamente al crescere di $n$;\n* tende a zero quando $\\theta$ è vicino a 0 o a 1.\n\n\n### Visualizzazione: come la verosimiglianza cambia con $n$\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Proporzione osservata fissa\np_obs <- 0.6\n\n# Diverse dimensioni campionarie\nn_values <- c(10, 50, 200)\n\n# Griglia di valori per theta\ntheta_grid <- seq(0.01, 0.99, length.out = 500)\n\n# Calcolo delle verosimiglianze\nlikelihood_data <- do.call(rbind, lapply(n_values, function(n) {\n  y <- round(p_obs * n)  # numero di successi\n  lik <- dbinom(y, size = n, prob = theta_grid)\n  # Normalizziamo per confronto visivo\n  lik_norm <- lik / max(lik)\n  data.frame(\n    theta = theta_grid,\n    likelihood = lik_norm,\n    n = factor(paste0(\"n = \", n), levels = paste0(\"n = \", n_values))\n  )\n}))\n\nggplot(likelihood_data, aes(x = theta, y = likelihood, color = n)) +\n  geom_line(linewidth = 1.2) +\n  geom_vline(xintercept = p_obs, linetype = \"dashed\") +\n  scale_fill_qualitative()\n  labs(\n    x = expression(theta),\n    y = \"Verosimiglianza (normalizzata)\",\n    color = \"Dimensione\\ncampionaria\"\n  ) \n#> <ggplot2::labels> List of 3\n#>  $ x     :  expression(theta)\n#>  $ y     : chr \"Verosimiglianza (normalizzata)\"\n#>  $ colour: chr \"Dimensione\\ncampionaria\"\n```\n\n::: {.cell-output-display}\n![La verosimiglianza diventa più concentrata all'aumentare della dimensione campionaria. Tutti i campioni hanno la stessa proporzione osservata (0.6), ma la precisione aumenta con n.](15_properties_likelihood_files/figure-html/fig-likelihood-n-1.png){#fig-likelihood-n fig-align='center' width=85%}\n:::\n:::\n\n\n**Lettura del grafico.**\nA parità di proporzione osservata ($\\bar{X} = 0.6$), campioni più grandi producono funzioni di verosimiglianza sempre più strette. Questo illustra visivamente il principio chiave di questa sezione:\n\n> **la forma della verosimiglianza riflette direttamente la variabilità della media campionaria.**\n\n## Precisione e informatività\n\n### Perché parlare di precisione?\n\nNell’inferenza bayesiana è spesso più utile ragionare in termini di **precisione** piuttosto che di varianza.\nLa precisione è definita come l’inverso della varianza:\n\n$$\n\\tau = \\frac{1}{\\sigma^2}.\n$$\n\nQuesta scelta non è puramente convenzionale. La precisione fornisce infatti una misura diretta di **quanta informazione** è contenuta in una distribuzione:\n\n* una varianza grande indica molta incertezza e quindi **bassa precisione**;\n* una varianza piccola indica poca incertezza e quindi **alta precisione**.\n\nIn altre parole, la precisione quantifica quanto “strettamente” una distribuzione è concentrata attorno ai valori più plausibili del parametro.\n\n### La precisione della media campionaria\n\nNel capitolo precedente abbiamo visto che la varianza della media campionaria decresce con il numero di osservazioni:\n\n$$\n\\text{Var}(\\bar{X} \\mid \\theta) = \\frac{\\sigma^2}{n}.\n$$\n\nPassando alla precisione otteniamo:\n\n$$\n\\text{Precisione}(\\bar{X} \\mid \\theta)\n= \\frac{1}{\\text{Var}(\\bar{X} \\mid \\theta)}\n= \\frac{n}{\\sigma^2}.\n$$\n\n**Osservazione chiave.**\nLa precisione cresce in modo **lineare** con la dimensione campionaria $n$. Questo significa che:\n\n* ogni nuova osservazione aggiunge la *stessa quantità di informazione*;\n* l’informazione totale fornita dai dati è la **somma** delle informazioni contenute nelle singole osservazioni.\n\nQuesta proprietà è fondamentale, perché anticipa uno dei meccanismi centrali dell’aggiornamento bayesiano:\n\n> **le informazioni si combinano in modo additivo quando sono espresse in termini di precisione.**\n\n### Errore standard e informatività dei dati\n\nL’**errore standard**\n\n$$\n\\text{SE} = \\frac{\\sigma}{\\sqrt{n}}\n$$\nfornisce una misura immediata dell’incertezza associata alla media campionaria come stima del parametro.\n\nDal punto di vista bayesiano:\n\n* un errore standard **piccolo** indica che i dati sono molto informativi: la verosimiglianza è stretta e concentrata;\n* un errore standard **grande** indica che i dati sono poco informativi: la verosimiglianza è ampia e diffusa.\n\nLa precisione e l’errore standard descrivono quindi lo stesso fenomeno da due prospettive complementari:\n\n* l’errore standard misura l’**incertezza residua**;\n* la precisione misura l’**informazione accumulata**.\n\n### Visualizzazione: come informazione e incertezza cambiano con $n$\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nn_seq <- 1:200\nsigma <- 1  # varianza unitaria per semplicità\n\nprecision_data <- data.frame(\n  n = n_seq,\n  se = sigma / sqrt(n_seq),\n  precision = n_seq / sigma^2\n)\n\np1 <- ggplot(precision_data, aes(x = n, y = se)) +\n  geom_line(linewidth = 1.2) +\n  scale_fill_qualitative() +\n  labs(\n    x = \"Dimensione campionaria (n)\",\n    y = \"Errore standard\",\n    title = \"Errore standard\\ndecresce come 1/√n\"\n  ) \n\np2 <- ggplot(precision_data, aes(x = n, y = precision)) +\n  geom_line(linewidth = 1.2) +\n  scale_fill_qualitative() +\n  labs(\n    x = \"Dimensione campionaria (n)\",\n    y = \"Precisione\",\n    title = \"Precisione cresce\\nlinearmente con n\"\n  ) \n\np1 + p2\n```\n\n::: {.cell-output-display}\n![Relazione tra dimensione campionaria, errore standard e precisione. Mentre l'errore standard decresce come 1/√n, la precisione cresce linearmente con n.](15_properties_likelihood_files/figure-html/fig-precision-vs-n-1.png){#fig-precision-vs-n fig-align='center' width=100%}\n:::\n:::\n\n\n**Lettura dei grafici.**\nIl primo grafico mostra che l’errore standard decresce lentamente, come $1/\\sqrt{n}$: raddoppiare il campione non dimezza l’incertezza. Il secondo grafico mostra invece che la precisione cresce linearmente con $n$: ogni osservazione aggiunge la stessa quantità di informazione.\n\nQuesta differenza di comportamento spiega perché, nell’inferenza bayesiana, la precisione sia spesso il linguaggio più naturale per descrivere il contributo dei dati.\n\n## L'aggiornamento bayesiano come combinazione di precisioni\n\n### L’idea chiave\n\nNel caso gaussiano, l’aggiornamento bayesiano può essere compreso in modo sorprendentemente semplice:\n**la stima a posteriori è una media ponderata tra ciò che credevamo prima e ciò che ci dicono i dati**, dove i pesi sono dati dalle rispettive **precisioni**.\n\nQuesta sezione rende esplicita questa idea nel contesto più semplice possibile, ma anche uno dei più istruttivi.\n\n### Il caso gaussiano: prior e dati\n\nSupponiamo di avere una credenza iniziale sul parametro $\\theta$, rappresentata da una distribuzione a priori gaussiana:\n\n$$\n\\theta \\sim \\mathcal{N}(\\mu_0, \\sigma_0^2).\n$$\n\nQuesta distribuzione riassume ciò che sappiamo (o crediamo di sapere) *prima* di osservare nuovi dati:\n\n* $\\mu_0$ è il valore più plausibile secondo le nostre conoscenze pregresse;\n* $\\sigma_0^2$ quantifica l’incertezza associata a tale credenza.\n\nOra raccogliamo un campione di $n$ osservazioni indipendenti:\n\n$$\nX_1, \\ldots, X_n \\sim \\mathcal{N}(\\theta, \\sigma^2),\n$$\ndove la varianza $\\sigma^2$ è nota. Come visto nelle sezioni precedenti, tutta l’informazione rilevante contenuta nel campione è riassunta dalla **media campionaria** $\\bar{X}$.\n\n### La verosimiglianza come distribuzione informativa\n\nConsiderata come funzione del parametro $\\theta$, la verosimiglianza associata ai dati è proporzionale a una distribuzione normale:\n\n$$\nL(\\theta; \\bar{x}) \\propto\n\\exp \\!\\left(-\\frac{n(\\bar{x}-\\theta)^2}{2\\sigma^2}\\right).\n$$\n\nQuesta funzione:\n\n* è centrata sulla media osservata $\\bar{x}$;\n* ha varianza $\\sigma^2/n$;\n* diventa più stretta al crescere del numero di osservazioni.\n\nIn termini di **precisione**, l’informazione fornita dai dati è pari a:\n\n$$\n\\tau_{\\text{dati}} = \\frac{n}{\\sigma^2}.\n$$\n\n### La distribuzione a posteriori\n\nIl teorema di Bayes stabilisce che la distribuzione a posteriori è proporzionale al prodotto tra prior e verosimiglianza:\n\n$$\np(\\theta \\mid \\bar{x}) \\propto p(\\theta)\\, L(\\theta; \\bar{x}).\n$$\n\nNel caso gaussiano, questo prodotto genera ancora una distribuzione normale:\n\n$$\n\\theta \\mid \\bar{x} \\sim \\mathcal{N}(\\mu_{\\text{post}}, \\sigma_{\\text{post}}^2).\n$$\n\n::: {#thm-posterior-gaussian}\n\n### Aggiornamento bayesiano gaussiano (forma esplicita)\n\nLa **media a posteriori** è una media ponderata tra prior e dati:\n\n$$\n\\mu_{\\text{post}}\n= \\frac{\\tau_0 \\mu_0 + \\tau_{\\text{dati}} \\bar{x}}\n{\\tau_0 + \\tau_{\\text{dati}}},\n$$\ndove:\n\n* $\\tau_0 = 1/\\sigma_0^2$ è la precisione del prior;\n* $\\tau_{\\text{dati}} = n/\\sigma^2$ è la precisione dei dati.\n\nLa **precisione a posteriori** è la somma delle precisioni:\n\n$$\n\\tau_{\\text{post}} = \\tau_0 + \\tau_{\\text{dati}}.\n$$\n:::\n\n\n### Come leggere queste formule\n\nQueste espressioni matematiche traducono in modo preciso la logica dell’aggiornamento bayesiano:\n\n1. **Media ponderata**\n   La stima a posteriori si colloca tra $\\mu_0$ e $\\bar{x}$, più vicina alla fonte di informazione più precisa.\n\n2. **Somma delle informazioni**\n   Le precisioni si sommano: l’incertezza diminuisce ogni volta che incorporiamo nuova informazione.\n\n3. **Dominanza dei dati**\n   Quando il campione è grande, $\\tau_{\\text{dati}}$ domina e la posterior è centrata vicino a $\\bar{x}$.\n\n4. **Dominanza del prior**\n   Quando i dati sono pochi o molto rumorosi, il prior ha un peso maggiore.\n\nIn breve:\n\n> **Bayes aggiorna credenze facendo una media, ma una media “intelligente”, pesata dall’informazione disponibile.**\n\n### Esempio numerico\n\nL’esempio seguente mostra visivamente come prior e dati contribuiscano alla distribuzione a posteriori in proporzione alle loro precisioni.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Parametri del prior\nmu_0 <- 100\nsigma_0 <- 15\ntau_0 <- 1 / sigma_0^2\n\n# Parametri dei dati\nn <- 25\nx_bar <- 115\nsigma <- 20  # deviazione standard nota\ntau_data <- n / sigma^2\n\n# Calcolo della posterior\ntau_post <- tau_0 + tau_data\nsigma_post <- sqrt(1 / tau_post)\nmu_post <- (tau_0 * mu_0 + tau_data * x_bar) / tau_post\n\n# Griglia di valori\ntheta_grid <- seq(60, 150, length.out = 500)\n\n# Calcolo delle distribuzioni\nprior_density <- dnorm(theta_grid, mu_0, sigma_0)\nlikelihood <- dnorm(theta_grid, x_bar, sigma / sqrt(n))\nposterior_density <- dnorm(theta_grid, mu_post, sigma_post)\n\n# Normalizzazione per visualizzazione\nlikelihood_norm <- likelihood * max(prior_density) / max(likelihood)\n\nplot_data <- data.frame(\n  theta = rep(theta_grid, 3),\n  density = c(prior_density, likelihood_norm, posterior_density),\n  type = factor(rep(c(\"Prior\", \"Verosimiglianza\", \"Posterior\"), each = length(theta_grid)),\n                levels = c(\"Prior\", \"Verosimiglianza\", \"Posterior\"))\n)\n\nggplot(plot_data, aes(x = theta, y = density, color = type, linetype = type)) +\n  geom_line(linewidth = 1.2) +\n  scale_fill_qualitative() +\n  scale_linetype_manual(values = c(\"solid\", \"dashed\", \"solid\")) +\n  labs(\n    x = expression(theta),\n    y = \"Densità\",\n    color = \"\",\n    linetype = \"\"\n  ) \n```\n\n::: {.cell-output-display}\n![Aggiornamento bayesiano: il prior (blu), la verosimiglianza (arancione) e la distribuzione a posteriori (verde). La posterior è un compromesso tra prior e dati, pesato dalle rispettive precisioni.](15_properties_likelihood_files/figure-html/fig-bayesian-update-1.png){#fig-bayesian-update fig-align='center' width=85%}\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Stampa dei risultati\ncat(\"Prior: N(\", mu_0, \", \", sigma_0, \"²)\\n\", sep = \"\")\n#> Prior: N(100, 15²)\ncat(\"Dati: n =\", n, \", media campionaria =\", x_bar, \"\\n\")\n#> Dati: n = 25 , media campionaria = 115\ncat(\"Precisione prior:\", round(tau_0, 6), \"\\n\")\n#> Precisione prior: 0.00444\ncat(\"Precisione dati:\", round(tau_data, 6), \"\\n\")\n#> Precisione dati: 0.0625\ncat(\"Precisione posterior:\", round(tau_post, 6), \"\\n\")\n#> Precisione posterior: 0.0669\ncat(\"\\nMedia posterior:\", round(mu_post, 2), \"\\n\")\n#> \n#> Media posterior: 114\ncat(\"Deviazione standard posterior:\", round(sigma_post, 2), \"\\n\")\n#> Deviazione standard posterior: 3.86\n```\n:::\n\n\n::: {.callout-note}\n### Il peso relativo di prior e dati\n\nIn questo esempio, la precisione dei dati ($\\tau_{\\text{dati}} = 0.062$) è circa 14.1 volte maggiore della precisione del prior ($\\tau_0 = 0.004$). Di conseguenza, la media a posteriori (114) è molto più vicina alla media campionaria (115) che alla media a priori (100).\n:::\n\n## La Legge dei Grandi Numeri e la convergenza bayesiana\n\nTra i risultati fondamentali della teoria della probabilità, la **Legge dei Grandi Numeri (LGN)** descrive come l’informazione fornita dai dati si stabilizzi progressivamente all’aumentare del numero di osservazioni. Nella sua interpretazione più intuitiva, essa afferma che, ripetendo molte volte lo stesso esperimento nelle medesime condizioni, la frequenza relativa di un evento tende ad avvicinarsi alla sua probabilità teorica.\n\nIn termini più formali, se $X_1, \\dots, X_n$ sono variabili casuali indipendenti e identicamente distribuite con valore atteso $\\mu$, la media campionaria\n\n$$\n\\bar X_n = \\frac{1}{n}\\sum_{i=1}^{n} X_i\n$$\ntende, al crescere di $n$, a concentrarsi attorno al valore costante $\\mu$.\n\nQuesto non significa che la media campionaria smetta di fluttuare, ma che **deviazioni ampie dal valore vero diventano sempre meno probabili**: le oscillazioni persistono, ma si fanno progressivamente più piccole e trascurabili rispetto a $\\mu$.\n\n### Conseguenze per la verosimiglianza\n\nLa Legge dei Grandi Numeri ha un impatto diretto sul comportamento della funzione di verosimiglianza. Nei modelli in cui il massimo della verosimiglianza coincide con una statistica campionaria — come la media nel caso gaussiano — tale massimo converge al valore vero del parametro.\n\nDi conseguenza, all’aumentare della quantità di dati, la funzione di verosimiglianza:\n\n* si concentra sempre più attorno al valore corretto del parametro;\n* assegna un supporto sempre minore ai valori alternativi;\n* restringe progressivamente l’insieme dei parametri plausibili.\n\nL’incertezza non viene eliminata, ma **localizzata**: le ipotesi sbagliate non scompaiono, diventano semplicemente sempre meno credibili alla luce dell’evidenza accumulata.\n\n### Conseguenze per l’inferenza bayesiana: la consistenza\n\nQuesto comportamento della verosimiglianza si riflette direttamente nell’aggiornamento bayesiano delle credenze e conduce al principio di **consistenza bayesiana**.\n\n::: {#thm-bayesian-consistency}\n\n### Consistenza bayesiana\n\nSe la distribuzione a priori assegna probabilità positiva a ogni intorno del valore vero $\\theta_0$, allora, al crescere della dimensione campionaria ($n \\to \\infty$), la distribuzione a posteriori si concentra sempre più attorno a $\\theta_0$.\n:::\n\nIn termini intuitivi, questo risultato afferma che l’inferenza bayesiana è un procedimento **auto-correttivo**. Le credenze iniziali possono essere imprecise, deboli o persino fortemente divergenti tra loro; tuttavia, purché non escludano a priori il valore vero del parametro, l’accumulo dell’evidenza empirica le costringe progressivamente a convergere verso la stessa conclusione.\n\nCon l’aumentare dei dati:\n\n* l’influenza del prior si attenua;\n* l’informazione fornita dai dati diventa dominante;\n* la distribuzione a posteriori diventa una rappresentazione sempre più concentrata e accurata del parametro che governa il fenomeno osservato.\n\n### Simulazione: convergenza con prior diversi\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(42)\ntheta_true <- 0.45\nn_values <- c(10, 50, 200, 1000)\n\n# Prior diversi\npriors <- list(\n  A = c(2, 8),   # Prior pessimista (media = 0.2)\n  B = c(8, 2),   # Prior ottimista (media = 0.8)\n  C = c(1, 1)    # Prior uniforme (media = 0.5)\n)\n\n# Funzione per calcolare la posterior Beta\ncompute_posterior <- function(prior_params, n, theta_true) {\n  y <- rbinom(1, n, theta_true)\n  c(prior_params[1] + y, prior_params[2] + n - y)\n}\n\n# Generazione dei dati per il plot\nset.seed(42)\ntheta_grid <- seq(0.01, 0.99, length.out = 300)\n\nall_data <- do.call(rbind, lapply(n_values, function(n) {\n  do.call(rbind, lapply(names(priors), function(name) {\n    post <- compute_posterior(priors[[name]], n, theta_true)\n    data.frame(\n      theta = theta_grid,\n      density = dbeta(theta_grid, post[1], post[2]),\n      researcher = name,\n      n = n\n    )\n  }))\n}))\n\nall_data$n_label <- factor(paste(\"n =\", all_data$n), \n                           levels = paste(\"n =\", n_values))\nall_data$researcher <- factor(all_data$researcher,\n                              labels = c(\"Prior pessimista (β = 0.2)\",\n                                        \"Prior ottimista (β = 0.8)\", \n                                        \"Prior uniforme\"))\n\nggplot(all_data, aes(x = theta, y = density, color = researcher)) +\n  geom_line(linewidth = 1) +\n  geom_vline(xintercept = theta_true, linetype = \"dashed\", \n             linewidth = 0.8) +\n  facet_wrap(~ n_label, scales = \"free_y\", ncol = 2) +\n  scale_fill_qualitative() +\n  labs(\n    x = expression(theta),\n    y = \"Densità a posteriori\",\n    color = \"Ricercatore\"\n  ) +\n  theme(legend.position = \"bottom\")\n```\n\n::: {.cell-output-display}\n![Convergenza bayesiana: tre ricercatori con prior molto diversi convergono alla stessa conclusione all'aumentare dei dati. La linea verticale indica il valore vero θ₀ = 0.45.](15_properties_likelihood_files/figure-html/fig-convergence-1.png){#fig-convergence fig-align='center' width=100%}\n:::\n:::\n\n\n**Lettura del grafico.**\nQuando il campione è molto piccolo ($n = 10$), le distribuzioni a posteriori riflettono ancora fortemente le diverse credenze iniziali dei ricercatori. Con $n = 50$, inizia a emergere un avvicinamento sistematico. A partire da $n = 200$, le posteriori risultano sostanzialmente sovrapposte, e con $n = 1000$ sono praticamente indistinguibili, tutte fortemente concentrate attorno al valore vero $\\theta_0$.\n\nQuesta simulazione fornisce un’illustrazione concreta del principio di consistenza bayesiana: **a sufficienza di dati, ricercatori con prior molto diversi arrivano alle stesse conclusioni**.\n\n## Il Teorema del Limite Centrale e l’approssimazione normale\n\n### Perché la normalità emerge\n\nNel capitolo precedente abbiamo visto che, all’aumentare del numero di osservazioni, la verosimiglianza tende a concentrarsi attorno a un valore ben definito del parametro. Un ulteriore passo consiste nel capire **perché questa concentrazione assume spesso una forma gaussiana**, anche quando i dati non provengono da una popolazione normale.\n\nLa risposta a questa domanda è fornita dal **Teorema del Limite Centrale (TLC)**, uno dei risultati più importanti della teoria della probabilità.\n\n### L’idea del Teorema del Limite Centrale\n\nIn forma intuitiva, il TLC afferma che, quando si calcola la media di molte osservazioni indipendenti, il risultato tende a comportarsi come una variabile normale. Questo accade **indipendentemente dalla forma della distribuzione originale**, purché la varianza sia finita.\n\nIn altri termini:\n\n* i singoli dati possono essere asimmetrici, discreti o irregolari;\n* ma le **medie campionarie** tendono a seguire una distribuzione gaussiana.\n\n::: {#thm-clt}\n\n### Teorema del Limite Centrale (forma intuitiva)\n\nPer osservazioni i.i.d. con media $\\mu$ e varianza $\\sigma^2 < \\infty$, la distribuzione della media campionaria $\\bar X_n$ può essere approssimata, per $n$ sufficientemente grande, da una distribuzione normale:\n\n$$\n\\bar{X}_n \\;\\dot\\sim\\; \\mathcal{N}\\!\\left(\\mu, \\frac{\\sigma^2}{n}\\right).\n$$\n:::\n\nQuesta proprietà spiega perché le distribuzioni gaussiane compaiano così frequentemente in statistica: **non perché la natura sia normale, ma perché facciamo medie**.\n\n### Conseguenze per la verosimiglianza\n\nPoiché in molti modelli la verosimiglianza dipende dalla media campionaria (o da statistiche che si comportano in modo analogo), il TLC implica che, per campioni sufficientemente grandi, la verosimiglianza assuma una forma **approssimativamente normale** rispetto al parametro:\n\n$$\nL(\\theta \\mid \\bar{x}) \\;\\approx\\;\n\\mathcal{N}\\!\\left(\\bar{x}, \\frac{\\sigma^2}{n}\\right),\n$$\ninterpretata come funzione di $\\theta$.\n\nÈ importante sottolineare che questa normalità **non deriva** dalla distribuzione delle singole osservazioni, ma dal loro comportamento aggregato. Anche partendo da popolazioni fortemente non gaussiane, la verosimiglianza tende ad assumere una struttura a campana man mano che il numero di dati cresce.\n\n### Conseguenze per l’inferenza bayesiana\n\nSe la verosimiglianza è approssimativamente normale e il prior non è patologico, anche la distribuzione a posteriori eredita questa forma. Questo fatto è formalizzato da un risultato noto come **teorema di Bernstein–von Mises**.\n\n::: {#thm-bvm}\n\n### Teorema di Bernstein–von Mises (interpretazione)\n\nSotto condizioni di regolarità e per campioni sufficientemente grandi, la distribuzione a posteriori può essere approssimata da una distribuzione normale centrata sul valore stimato del parametro, con una dispersione che riflette la quantità di informazione contenuta nei dati.\n:::\n\n**Interpretazione intuitiva.**\nQuando i dati sono numerosi:\n\n* il ruolo del prior diventa marginale;\n* la posterior è dominata dalla verosimiglianza;\n* la forma della posterior è ben approssimata da una gaussiana, anche se il prior e il modello iniziale non lo erano.\n\nQuesto risultato spiega perché, in molti contesti applicativi, l’inferenza bayesiana produca risultati simili a quelli frequentisti per grandi campioni, pur mantenendo un’interpretazione probabilistica distinta.\n\n### Visualizzazione: il TLC in una popolazione non normale\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(42)\n\n# Popolazione: distribuzione uniforme (non gaussiana)\npopulation <- runif(1e6, min = 0, max = 1)\n\n# Funzione per simulare distribuzioni campionarie\nsimulate_sampling_dist <- function(pop, sample_size, n_samples = 1e5) {\n  replicate(n_samples, mean(sample(pop, sample_size, replace = TRUE)))\n}\n\n# Diverse dimensioni campionarie\nsample_sizes <- c(1, 5, 30)\n\nsampling_data <- do.call(rbind, lapply(sample_sizes, function(n) {\n  means <- simulate_sampling_dist(population, n)\n  data.frame(\n    mean = means,\n    n = factor(paste(\"n =\", n), levels = paste(\"n =\", sample_sizes))\n  )\n}))\n\nggplot(sampling_data, aes(x = mean)) +\n  geom_histogram(aes(y = after_stat(density)), bins = 40, \n                 alpha = 0.7) +\n  stat_function(fun = dnorm, \n                args = list(mean = 0.5, sd = sqrt(1/12) / sqrt(30)),\n                data = subset(sampling_data, n == \"n = 30\"),\n                linewidth = 1.2) +\n  facet_wrap(~ n, scales = \"free_y\") +\n  scale_fill_qualitative() +\n  labs(\n    x = \"Media campionaria\",\n    y = \"Densità\"\n  ) \n```\n\n::: {.cell-output-display}\n![Il Teorema del Limite Centrale in azione: anche partendo da una distribuzione uniforme, la distribuzione delle medie campionarie converge rapidamente a una forma gaussiana.](15_properties_likelihood_files/figure-html/fig-clt-1.png){#fig-clt fig-align='center' width=85%}\n:::\n:::\n\n\n**Lettura del grafico.**\nCon $n = 1$, la distribuzione delle medie coincide con la distribuzione originale. Già con $n = 5$, inizia a emergere una forma a campana. Con $n = 30$, la distribuzione delle medie è praticamente indistinguibile da una normale.\n\nQuesto esempio mostra in modo visivo il messaggio centrale del TLC:\n\n> **la normalità non è una proprietà dei dati, ma delle medie dei dati.**\n\n## Combinazione di evidenze da studi multipli\n\n### L’idea di base\n\nUno dei punti di forza dell'approccio bayesiano è la possibilità di **integrare \nin modo coerente evidenze provenienti da fonti diverse**. Questo principio è alla base della **meta-analisi bayesiana**, che combina i risultati di studi \nindipendenti per ottenere stime più precise e robuste. Quando più studi indipendenti indagano lo stesso parametro $\\theta$, ciascuno di essi può essere visto come una fonte di informazione parziale, caratterizzata da una stima centrale e da un certo grado di incertezza.\n\nIl principio fondamentale è semplice:\n\n> **le informazioni si combinano sommando le loro precisioni.**\n\n### Il principio della somma delle precisioni\n\nSupponiamo che ciascuno studio $i$ fornisca:\n\n* una stima $\\bar{x}_i$ del parametro $\\theta$;\n* una misura della sua incertezza, espressa tramite la **precisione** $\\tau_i$ (l’inverso della varianza).\n\nLa stima combinata risulta essere una **media ponderata**:\n\n$$\n\\bar{x}_{\\text{comb}} = \\frac{\\sum_i \\tau_i \\bar{x}_i}{\\sum_i \\tau_i},\n$$\ndove i pesi riflettono l’affidabilità relativa degli studi.\n\nAllo stesso tempo, la precisione complessiva è semplicemente:\n\n$$\n\\tau_{\\text{comb}} = \\sum_i \\tau_i.\n$$\n\nQueste formule riflettono esattamente la logica dell’aggiornamento bayesiano: ogni nuova fonte di informazione contribuisce in proporzione alla propria precisione, riducendo l’incertezza complessiva.\n\n### Esempio: sintesi di due studi\n\nConsideriamo due studi indipendenti che stimano la prevalenza di un sintomo:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Parametri degli studi\nstudi <- data.frame(\n  studio = c(\"A\", \"B\"),\n  n = c(50, 200),\n  proporzione = c(0.42, 0.38),\n  se = c(0.07, 0.035)\n)\n\nstudi$precisione <- 1 / studi$se^2\n\nprecisione_totale <- sum(studi$precisione)\nmedia_combinata <- sum(studi$precisione * studi$proporzione) / precisione_totale\nse_combinato <- sqrt(1 / precisione_totale)\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```\n#> Stima combinata: 0.388\n#> Errore standard combinato: 0.0313\n#> Precisioni:\n#> - Studio A: 204\n#> - Studio B: 816\n#> - Totale: 1020\n```\n:::\n\n\n**Risultato chiave.**\nLa stima combinata ha un errore standard (0.031) inferiore a quello di entrambi gli studi presi singolarmente. Questo accade perché la **precisione totale** (1020.4) è la somma delle precisioni individuali: l’incertezza si riduce man mano che integriamo più evidenza affidabile.[^cue-combination]\n\n[^cue-combination]: Questo principio, che formalizza il modo *ottimale* di combinare informazioni incerte, ha ispirato e motivato una vasta quantità di ricerche empiriche nel campo delle Scienze della Visione. In particolare, ci si è chiesti se il sistema visivo umano si comporti come un \"osservatore ideale\", ovvero se integri le informazioni in modo statisticamente ottimale e coerente con l'integrazione bayesiana. Questa domanda ha motivato molti studi condotti per comprendere come un individuo integri segnali visivi che possono essere parzialmente discordanti, come ad esempio quelli provenienti dalla stereopsi e dalla parallasse di movimento [@domini2011combining].\n\n### Visualizzazione: perché uno studio pesa più dell’altro\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ntheta_grid <- seq(0.2, 0.6, length.out = 500)\n\nmeta_data <- data.frame(\n  theta = rep(theta_grid, 3),\n  density = c(\n    dnorm(theta_grid, studi$proporzione[1], studi$se[1]),\n    dnorm(theta_grid, studi$proporzione[2], studi$se[2]),\n    dnorm(theta_grid, media_combinata, se_combinato)\n  ),\n  studio = factor(rep(c(\"Studio A (n=50)\", \"Studio B (n=200)\", \"Combinato\"), \n                      each = length(theta_grid)),\n                  levels = c(\"Studio A (n=50)\", \"Studio B (n=200)\", \"Combinato\"))\n)\n\nggplot(meta_data, aes(x = theta, y = density, color = studio, linetype = studio)) +\n  geom_line(linewidth = 1.2) +\n  scale_fill_qualitative() +\n  scale_linetype_manual(values = c(\"dashed\", \"dashed\", \"solid\")) +\n  labs(\n    x = expression(theta),\n    y = \"Densità\",\n    color = \"\",\n    linetype = \"\"\n  )  \n```\n\n::: {.cell-output-display}\n![Combinazione di evidenze. Lo studio B (n=200), avendo una precisione notevolmente maggiore, contribuisce di più alla stima combinata (linea verde). L'intervallo di credibilità risultante è più stretto di quello di ciascuno studio preso singolarmente.](15_properties_likelihood_files/figure-html/fig-meta-analysis-1.png){#fig-meta-analysis fig-align='center' width=85%}\n:::\n:::\n\n\n**Lettura del grafico.**\nLo studio B, avendo una dimensione campionaria maggiore, presenta una distribuzione più stretta e quindi una precisione più elevata. Di conseguenza, la stima combinata (linea verde) risulta più vicina allo studio B che allo studio A. L’intervallo risultante è inoltre più stretto di entrambi, riflettendo la maggiore informazione complessiva.\n\n::: {.callout-note}\n\n### Il peso dell’evidenza\n\nLa stima combinata (0.388) è più vicina al valore riportato dallo studio B (0.38) perché questo studio fornisce un’informazione più precisa. In un’ottica bayesiana, **le evidenze non si contano, si pesano**: fonti più affidabili contribuiscono di più alla conclusione finale.\n\nQuesto principio — che formalizza il modo ottimale di integrare informazioni incerte — ha ispirato numerose ricerche nelle scienze cognitive e percettive, dove ci si è chiesti se il sistema umano integri i segnali sensoriali in modo coerente con l’inferenza bayesiana [@domini2011combining].\n:::\n\n## Limiti dell'inferenza: precisione vs. accuratezza\n\n### Cosa misura davvero l’errore standard\n\nLe quantità studiate in questo capitolo, come la concentrazione della verosimiglianza, il restringimento della distribuzione a posteriori e la riduzione dell’errore standard, descrivono **una sola dimensione dell’inferenza statistica**: la **precisione**, cioè quanto una stima è influenzata dalla variabilità campionaria.\n\nUn errore standard piccolo indica che, se ripetessimo lo studio molte volte nelle stesse condizioni, otterremmo risultati molto simili. Tuttavia, questa stabilità **non garantisce** che la stima sia vicina al valore vero del parametro.\n\nIn altre parole:\n\n> una stima può essere molto precisa, ma comunque sbagliata.\n\nL’inferenza bayesiana, come qualunque procedura statistica, **non può correggere distorsioni sistematiche** introdotte prima dell’analisi, durante la progettazione dello studio, la raccolta dei dati o la misurazione dei costrutti.\n\n### Fonti comuni di distorsione sistematica\n\nNella ricerca applicata, in particolare in ambito psicologico e sociale, sono frequenti meccanismi che producono errori sistematici (*bias*). Anche un’analisi statisticamente impeccabile può portare a conclusioni fuorvianti se questi problemi non vengono affrontati a monte.\n\n**Distorsione da selezione**\nSi verifica quando il campione osservato non è rappresentativo della popolazione di interesse. Reclutamento opportunistico, autoselezione o bassi tassi di risposta possono produrre stime che descrivono bene *il campione*, ma non *la popolazione*.\n\n**Distorsione da desiderabilità sociale**\nIn presenza di temi sensibili, i partecipanti possono fornire risposte socialmente accettabili piuttosto che veritiere. In questi casi, le osservazioni non riflettono il costrutto psicologico di interesse, compromettendo la validità delle inferenze.\n\n**Errori di misurazione**\nStrumenti poco affidabili o non validati possono introdurre rumore o distorsioni sistematiche. Anche grandi campioni non compensano misure che catturano il fenomeno sbagliato o in modo instabile.\n\n### Il paradosso della falsa precisione\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Precisione e accuratezza nell'inferenza. La situazione più pericolosa è l'alta precisione con bassa accuratezza (in alto a destra): stime molto sicure ma sistematicamente sbagliate.](15_properties_likelihood_files/figure-html/fig-precision-accuracy-1.png){#fig-precision-accuracy fig-align='center' width=95%}\n:::\n:::\n\n\n::: {.callout-warning title=\"Il pericolo della falsa precisione\"}\nLa situazione più insidiosa si verifica quando un’elevata precisione si accompagna a una bassa accuratezza. In questo caso, l’analisi produce intervalli di credibilità molto stretti — che suggeriscono grande certezza — attorno a valori che sono invece sistematicamente distorti.\n\nUn campione numericamente grande ma affetto da bias può essere **più pericoloso** di un campione piccolo ma corretto: consolida conclusioni errate con un’apparenza di rigore e affidabilità scientifica.\n:::\n\n### Come mitigare questi limiti\n\nLa consapevolezza dei limiti dell’inferenza statistica suggerisce alcune buone pratiche fondamentali.\n\n**Progettazione metodologica rigorosa**\nLa prevenzione dei bias avviene principalmente *prima* dell’analisi dei dati: campionamento appropriato, randomizzazione, protocolli standardizzati e strumenti validati sono insostituibili.\n\n**Analisi di sensibilità**\nL’approccio bayesiano permette di esplorare esplicitamente l’impatto di ipotesi alternative e di valutare quanto le conclusioni dipendano da assunzioni potenzialmente discutibili.\n\n**Trasparenza epistemica**\nÈ essenziale comunicare chiaramente che gli intervalli di credibilità quantificano solo l’incertezza campionaria. La valutazione critica della qualità dei dati e del disegno di ricerca resta una responsabilità centrale del ricercatore.\n\n## Riflessioni conclusive {.unnumbered .unlisted}\n\nQuesto capitolo ha messo in luce il legame profondo tra il comportamento delle statistiche campionarie e il meccanismo dell’aggiornamento bayesiano. Le proprietà matematiche della media campionaria non sono semplici risultati tecnici, ma costituiscono il fondamento che spiega *perché* la verosimiglianza e la distribuzione a posteriori assumono le forme osservate.\n\nIn particolare, il fatto che la media campionaria sia centrata sul valore del parametro di interesse e che la sua variabilità diminuisca con l’aumentare del numero di osservazioni determina la forma della funzione di verosimiglianza: essa è centrata sul valore osservato e diventa progressivamente più concentrata man mano che l’evidenza empirica cresce. Queste stesse proprietà governano il modo in cui la distribuzione a posteriori risponde ai dati.\n\nNel caso gaussiano, l’aggiornamento bayesiano assume una forma particolarmente trasparente: la **precisione a posteriori** è la somma delle precisioni del prior e dei dati, mentre la **media a posteriori** è una media ponderata delle due fonti di informazione. Grazie al Teorema del Limite Centrale, questo schema si estende in modo approssimato a una vasta classe di modelli, giustificando l’uso dell’approssimazione normale per campioni sufficientemente ampi.\n\nLa Legge dei Grandi Numeri garantisce la **consistenza dell’inferenza bayesiana**: quando l’evidenza empirica diventa abbondante, la distribuzione a posteriori si concentra attorno al valore vero del parametro, indipendentemente dalla distribuzione a priori adottata, purché essa non lo escluda a priori. Questo risultato conferisce una solida robustezza epistemica al metodo bayesiano: nel lungo periodo, i dati prevalgono sulle convinzioni iniziali.\n\nIl Teorema del Limite Centrale spiega inoltre perché la forma normale emerga così frequentemente nella distribuzione a posteriori per grandi campioni, fornendo il fondamento teorico di molte approssimazioni pratiche utilizzate nell’inferenza statistica.\n\nÈ tuttavia essenziale riconoscere i **limiti** intrinseci di questi risultati. Tutte le proprietà discusse riguardano esclusivamente l’incertezza dovuta al campionamento casuale. Esse non possono correggere né compensare distorsioni sistematiche legate al disegno di ricerca, alla selezione del campione o agli strumenti di misura. La precisione statistica, quindi, non deve mai essere confusa con la validità scientifica delle conclusioni.\n\nNei capitoli successivi del manuale principale, questi principi teorici verranno utilizzati in modo operativo nella costruzione, stima e interpretazione di modelli bayesiani applicati alla ricerca psicologica. Il ruolo di questo companion è fornire le basi concettuali necessarie per comprendere *perché* tali modelli funzionano e *in quali condizioni* le loro inferenze possono essere considerate affidabili.\n\n## Punti chiave da ricordare {.unnumbered}\n\n::: {.callout-important}\n**Concetti essenziali di questo capitolo:**\n\n1. **Score function (funzione punteggio)**\n   - $S(\\theta) = \\frac{\\partial}{\\partial\\theta}\\ell(\\theta) = \\frac{\\partial}{\\partial\\theta}\\log L(\\theta)$\n   - Pendenza della log-verosimiglianza\n   - $S(\\hat{\\theta}_{\\text{MLE}}) = 0$ (condizione del primo ordine per massimo)\n   - Intuitivamente: \"direzione di maggiore crescita della verosimiglianza\"\n\n2. **Informazione di Fisher**\n   - $I(\\theta) = -\\mathbb{E}\\left[\\frac{\\partial^2}{\\partial\\theta^2}\\ell(\\theta)\\right] = \\mathbb{E}[S(\\theta)^2]$\n   - Quantifica \"quanta informazione sul parametro fornisce un'osservazione\"\n   - Curvatura della log-verosimiglianza al punto vero\n   - $I_n(\\theta) = n \\cdot I(\\theta)$ per $n$ osservazioni i.i.d. (informazione si accumula!)\n\n3. **Normalità asintotica della MLE**\n   - Per $n$ grande: $\\hat{\\theta}_{\\text{MLE}} \\approx \\mathcal{N}\\left(\\theta_{\\text{vero}}, \\frac{1}{I_n(\\theta)}\\right)$\n   - La verosimiglianza diventa approssimativamente normale attorno alla MLE\n   - Permette approssimazioni gaussiane della posterior (approssimazione di Laplace)\n\n4. **Prior coniugati**\n   - Prior e verosimiglianza \"coniugati\" → posterior della stessa famiglia del prior\n   - **Beta-Binomiale**: $\\text{Beta}(\\alpha,\\beta) + \\text{Bin}(n,\\theta) \\to \\text{Beta}(\\alpha+k, \\beta+n-k)$\n   - **Normale-Normale**: prior Normale + dati Normali → posterior Normale\n   - **Gamma-Poisson**: prior Gamma + dati Poisson → posterior Gamma\n   - Enormemente semplifica i calcoli (forma chiusa!)\n\n5. **Interpretazione parametri coniugati**\n   - **Beta($\\alpha, \\beta$)**: $\\alpha-1$ successi pregressi, $\\beta-1$ fallimenti pregressi\n   - **Gamma($\\alpha, \\beta$)**: $\\alpha$ eventi osservati in tempo $\\beta$\n   - Parametri prior = \"dimensione campionaria equivalente\" delle credenze iniziali\n\n6. **Aggiornamento sequenziale**\n   - Posterior(oggi) diventa prior(domani)\n   - Con coniugazione: aggiornare parametri sequenzialmente = aggiornare con tutti i dati insieme\n   - Proprietà di **coerenza temporale**: l'ordine dei dati non conta\n\n7. **Regola della precisione**\n   - Precisione posteriore = Precisione prior + Precisione likelihood\n   - $\\tau_{\\text{post}} = \\tau_{\\text{prior}} + \\tau_{\\text{data}}$\n   - Per prior deboli: $\\tau_{\\text{post}} \\approx \\tau_{\\text{data}}$ (posterior dominata dai dati)\n\n8. **Quando la coniugazione non è disponibile**\n   - Approssimazioni: normale asintotica, approssimazione di Laplace\n   - Metodi computazionali: MCMC, variational inference\n   - Prior non coniugati permettono maggiore flessibilità ma richiedono calcolo numerico\n\n**Formule da ricordare:**\n\n**Score function:**\n$$\nS(\\theta) = \\frac{\\partial}{\\partial\\theta}\\log L(\\theta), \\quad S(\\hat{\\theta}_{\\text{MLE}}) = 0\n$$\n\n**Informazione di Fisher:**\n$$\nI(\\theta) = -\\mathbb{E}\\left[\\frac{\\partial^2}{\\partial\\theta^2}\\log L(\\theta)\\right] = \\mathbb{E}[S(\\theta)^2]\n$$\n\n**Informazione per $n$ osservazioni i.i.d.:**\n$$\nI_n(\\theta) = n \\cdot I(\\theta)\n$$\n\n**Normalità asintotica MLE:**\n$$\n\\hat{\\theta}_{\\text{MLE}} \\xrightarrow{d} \\mathcal{N}\\left(\\theta, \\frac{1}{I_n(\\theta)}\\right)\n$$\n\n**Aggiornamento Beta-Binomiale:**\n$$\n\\text{Beta}(\\alpha, \\beta) \\xrightarrow{k/n} \\text{Beta}(\\alpha+k, \\beta+n-k)\n$$\n\n**Aggiornamento Normale-Normale (media):**\n$$\n\\mathcal{N}(\\mu_0, \\sigma_0^2) \\xrightarrow{\\bar{x}, n} \\mathcal{N}\\left(\\frac{\\tau_0\\mu_0 + n\\tau\\bar{x}}{\\tau_0 + n\\tau}, \\frac{1}{\\tau_0 + n\\tau}\\right)\n$$\ndove $\\tau = 1/\\sigma^2$ è la precisione.\n\n**Aggiornamento Gamma-Poisson:**\n$$\n\\text{Gamma}(\\alpha, \\beta) \\xrightarrow{\\sum x_i, n} \\text{Gamma}(\\alpha + \\sum x_i, \\beta + n)\n$$\n\n**Coppie coniugate principali:**\n\n| Verosimiglianza | Prior coniugato | Posterior | Parametro |\n|:---|:---|:---|:---|\n| Binomiale | Beta | Beta | Proporzione $\\theta$ |\n| Normale (var nota) | Normale | Normale | Media $\\mu$ |\n| Normale (media nota) | Gamma | Gamma | Precisione $\\tau$ |\n| Poisson | Gamma | Gamma | Rate $\\lambda$ |\n| Esponenziale | Gamma | Gamma | Rate $\\lambda$ |\n\n**Proprietà critiche:**\n\n- Informazione di Fisher cresce linearmente con $n$\n- Coniugazione preserva la famiglia parametrica\n- Prior deboli → posterior dominata dai dati\n- Prior informativi → sintesi ponderata\n- Aggiornamento sequenziale = aggiornamento batch (con coniugazione)\n\n**Conclusione del modulo:**\n\nQuesto capitolo conclude il **modulo di richiamo della teoria della probabilità**. Abbiamo costruito un percorso completo: dall'interpretazione bayesiana della probabilità agli assiomi di coerenza, dalle variabili casuali alle distribuzioni parametriche, dalla verosimiglianza all'aggiornamento bayesiano. Questi fondamenti costituiscono la base concettuale e operativa per l'**inferenza bayesiana** presentata nel manuale principale *Inferenza bayesiana in psicologia: Ragionare con l'incertezza*.\n\n**Per il manuale principale:**\n\nIl manuale UTET approfondisce: modelli gerarchici, confronto di modelli, inferenza decisionale, metodi computazionali (MCMC, HMC, Stan), regressione bayesiana, modelli di mistura, analisi di mediazione e moderazione, e applicazioni psicologiche avanzate.\n:::\n\n::: {.callout-note collapse=true title=\"Informazioni sull'ambiente di sviluppo\"}\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsessionInfo()\n#> R version 4.6.0 (2026-04-24)\n#> Platform: aarch64-apple-darwin23\n#> Running under: macOS Tahoe 26.5.1\n#> \n#> Matrix products: default\n#> BLAS:   /Library/Frameworks/R.framework/Versions/4.6/Resources/lib/libRblas.0.dylib \n#> LAPACK: /Library/Frameworks/R.framework/Versions/4.6/Resources/lib/libRlapack.dylib;  LAPACK version 3.12.1\n#> \n#> locale:\n#> [1] C.UTF-8/UTF-8/C.UTF-8/C/C.UTF-8/C.UTF-8\n#> \n#> time zone: Europe/Rome\n#> tzcode source: internal\n#> \n#> attached base packages:\n#> [1] stats     graphics  grDevices utils     datasets  methods   base     \n#> \n#> other attached packages:\n#>  [1] ragg_1.5.2            tinytable_0.17.0      withr_3.0.3          \n#>  [4] systemfonts_1.3.2     patchwork_1.3.2       ggdist_3.3.3         \n#>  [7] tidybayes_3.0.7       bayesplot_1.15.0      ggplot2_4.0.3        \n#> [10] reliabilitydiag_0.2.1 priorsense_1.2.0      posterior_1.7.0      \n#> [13] loo_2.10.0            rstan_2.32.7          StanHeaders_2.32.10  \n#> [16] brms_2.23.0           Rcpp_1.1.1-1.1        sessioninfo_1.2.4    \n#> [19] conflicted_1.2.0      janitor_2.2.1         matrixStats_1.5.0    \n#> [22] modelr_0.1.11         tibble_3.3.1          dplyr_1.2.1          \n#> [25] tidyr_1.3.2           rio_1.3.0             here_1.0.2           \n#> \n#> loaded via a namespace (and not attached):\n#>  [1] svUnit_1.0.8          tidyselect_1.2.1      farver_2.1.2         \n#>  [4] S7_0.2.2              fastmap_1.2.0         tensorA_0.36.2.1     \n#>  [7] digest_0.6.39         timechange_0.4.0      estimability_2.0.0   \n#> [10] lifecycle_1.0.5       magrittr_2.0.5        compiler_4.6.0       \n#> [13] rlang_1.2.0           tools_4.6.0           yaml_2.3.12          \n#> [16] knitr_1.51            labeling_0.4.3        bridgesampling_1.2-1 \n#> [19] htmlwidgets_1.6.4     pkgbuild_1.4.8        curl_7.1.0           \n#> [22] RColorBrewer_1.1-3    abind_1.4-8           purrr_1.2.2          \n#> [25] grid_4.6.0            stats4_4.6.0          xtable_1.8-8         \n#> [28] inline_0.3.21         emmeans_2.0.3         scales_1.4.0         \n#> [31] cli_3.6.6             mvtnorm_1.4-1         rmarkdown_2.31       \n#> [34] generics_0.1.4        otel_0.2.0            RcppParallel_5.1.11-2\n#> [37] cachem_1.1.0          stringr_1.6.0         parallel_4.6.0       \n#> [40] vctrs_0.7.3           V8_8.2.0              Matrix_1.7-5         \n#> [43] jsonlite_2.0.0        arrayhelpers_1.1-1    glue_1.8.1           \n#> [46] codetools_0.2-20      distributional_0.8.1  lubridate_1.9.5      \n#> [49] stringi_1.8.7         gtable_0.3.6          QuickJSR_1.10.0      \n#> [52] pillar_1.11.1         htmltools_0.5.9       Brobdingnag_1.2-9    \n#> [55] R6_2.6.1              textshaping_1.0.5     rprojroot_2.1.1      \n#> [58] evaluate_1.0.5        lattice_0.22-9        backports_1.5.1      \n#> [61] memoise_2.0.1         broom_1.0.13          snakecase_0.11.1     \n#> [64] rstantools_2.6.0      coda_0.19-4.1         gridExtra_2.3.1      \n#> [67] nlme_3.1-169          checkmate_2.3.4       xfun_0.59            \n#> [70] pkgconfig_2.0.3\n```\n:::\n\n:::\n\n## Bibliografia {.unnumbered .unlisted}\n",
    "supporting": [
      "15_properties_likelihood_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}