{
  "hash": "e1adfd7139ff258fbf0f361529d33241",
  "result": {
    "engine": "knitr",
    "markdown": "# Proprietà della verosimiglianza e aggiornamento bayesiano {#sec-likelihood-properties}\n\n## Introduzione {.unnumbered .unlisted}\n\nNel capitolo precedente abbiamo introdotto la verosimiglianza come lo strumento che quantifica la compatibilità relativa tra i dati osservati e i possibili valori dei parametri del modello. Abbiamo descritto alcune sue caratteristiche empiriche: tende a concentrarsi attorno a un valore ben definito, si restringe progressivamente con l’aumentare della dimensione del campione e, per campioni sufficientemente ampi, assume una forma approssimativamente gaussiana.\n\nQueste osservazioni sollevano un interrogativo teorico: *quali principi matematici spiegano tali proprietà?* E, soprattutto, *in che modo esse determinano la forma e l’evoluzione della distribuzione a posteriori nell’inferenza bayesiana?*\n\nIl presente capitolo risponde a queste domande, mostrando che la struttura della verosimiglianza non è un fenomeno contingente, ma riflette regolarità matematiche che governano sia il comportamento delle statistiche campionarie sia il meccanismo di aggiornamento bayesiano. In particolare, dimostreremo che la verosimiglianza è centrata sul valore corretto del parametro, in quanto la media campionaria è uno stimatore non distorto, e che diventa progressivamente più informativa con l'aumentare del numero di osservazioni, grazie al fatto che la sua varianza decresce proporzionalmente a $1/n$.\n\nL’aggiornamento bayesiano sarà reinterpretato come una combinazione lineare di informazioni, nella quale la verosimiglianza e la distribuzione a priori contribuiscono con un peso proporzionale alla rispettiva precisione, definita come l’inverso della varianza. Tale prospettiva evidenzia il ruolo complementare dell'evidenza empirica e della conoscenza pregressa nella costruzione della distribuzione a posteriori.\n\nInfine, discuteremo il ruolo di due teoremi fondamentali che descrivono il comportamento asintotico dell’inferenza: la **Legge dei Grandi Numeri**, che garantisce la convergenza della distribuzione a posteriori verso il valore vero del parametro, e il **Teorema del Limite Centrale**, che spiega perché, per ampi campioni, la distribuzione a posteriori possa essere approssimata da una distribuzione gaussiana, a prescindere dalla forma iniziale del prior. Questi risultati forniranno le basi teoriche per comprendere l’affidabilità, la robustezza e la convergenza dell’approccio bayesiano.\n\n### Panoramica del capitolo {.unnumbered .unlisted}\n\n- Collegamento tra proprietà della media campionaria e forma della verosimiglianza.\n- Precisione come misura di informatività e regola di combinazione delle precisioni.\n- Aggiornamento bayesiano nel caso gaussiano: formula esplicita per la distribuzione a posteriori.\n- Legge dei Grandi Numeri e convergenza della distribuzione a posteriori.\n- Teorema del Limite Centrale e approssimazione normale della distribuzione a posteriori.\n- Combinazione di evidenze da studi multipli.\n- Limiti dell'inferenza: distinzione tra incertezza campionaria e distorsioni sistematiche.\n\n::: {.callout-caution collapse=true title=\"Preparazione del Notebook\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhere::here(\"code\", \"_common.R\") |> \n  source()\nlibrary(patchwork)\n```\n:::\n\n:::\n\n\n## Dalla media campionaria alla verosimiglianza\n\n### Il problema inferenziale\n\nConsideriamo un problema concreto: stimare la prevalenza $\\theta$ di sintomi depressivi clinicamente rilevanti nella popolazione studentesca universitaria. Non potendo valutare l’intera popolazione, raccogliamo un campione di $n$ studenti, registrando per ciascuno la presenza (1) o assenza (0) del sintomo.\n\nFormalmente, le osservazioni $X_1, X_2, \\ldots, X_n$ sono variabili casuali indipendenti e identicamente distribuite (i.i.d.) che seguono una distribuzione di Bernoulli:\n$$\nX_i \\mid \\theta \\sim \\text{Bernoulli}(\\theta).\n$$\n\nLa **proporzione campionaria** $\\bar{X} = \\frac{1}{n}\\sum_{i=1}^n X_i$ sintetizza l’evidenza osservata. Prima di raccogliere i dati, le nostre conoscenze preliminari su $\\theta$ possono essere formalizzate in una distribuzione a priori su $\\theta$. Ma come si fa a usare $\\bar{X}$ per aggiornare le nostre credenze su $\\theta$?\n\nLa risposta risiede nel concetto di **verosimiglianza**: le proprietà matematiche di $\\bar{X}$ determinano la forma della funzione di verosimiglianza, che a sua volta governa il modo in cui i dati trasformano la distribuzione a priori in quella a posteriori.\n\n### Il valore atteso della media campionaria\n\nEsaminiamo dunque la prima proprietà fondamentale di $\\bar{X}$: la sua media coincide esattamente con il parametro di interesse.\n\n::: {#thm-expval-mean}\nPer osservazioni i.i.d. con $\\mathbb{E}[X_i \\mid \\theta] = \\theta$:\n$$\n\\mathbb{E}[\\bar{X} \\mid \\theta] = \\theta.\n$$\n:::\n\n::: {.proof}\n$$\n\\mathbb{E}[\\bar{X} \\mid \\theta] = \\mathbb{E}\\left[\\frac{1}{n}\\sum_{i=1}^n X_i \\; \\bigg| \\; \\theta\\right] = \\frac{1}{n}\\sum_{i=1}^n \\mathbb{E}[X_i \\mid \\theta] = \\frac{1}{n} \\cdot n\\theta = \\theta.\n$$\n:::\n\n**Conseguenza per la verosimiglianza**: questa proprietà garantisce che, in media, il picco della funzione di verosimiglianza — ovvero lo stimatore di massima verosimiglianza $\\hat{\\theta} = \\bar{X}$ — corrisponde al valore vero del parametro $\\theta$. Uno stimatore con questa caratteristica si dice **non distorto**: non presenta una tendenza sistematica a sovrastimare o sottostimare il parametro.\n\n### La varianza della media campionaria\n\nLa seconda proprietà fondamentale riguarda la **dispersione** di $\\bar{X}$, che quantifica quanto le stime campionarie fluttuano attorno al valore atteso.\n\n::: {#thm-var-mean}\nPer osservazioni i.i.d. con $\\text{Var}(X_i \\mid \\theta) = \\sigma^2$:\n$$\n\\text{Var}(\\bar{X} \\mid \\theta) = \\frac{\\sigma^2}{n}.\n$$\n:::\n\n::: {.proof}\n$$\n\\text{Var}(\\bar{X} \\mid \\theta) = \\text{Var}\\left(\\frac{1}{n}\\sum_{i=1}^n X_i \\; \\bigg| \\; \\theta\\right) = \\frac{1}{n^2}\\sum_{i=1}^n \\text{Var}(X_i \\mid \\theta) = \\frac{1}{n^2} \\cdot n\\sigma^2 = \\frac{\\sigma^2}{n}.\n$$\n:::\n\n**Conseguenza per la verosimiglianza**: questa proprietà spiega il motivo per cui la verosimiglianza diventa più **concentrata** (cioè più \"stretta\") al crescere della dimensione campionaria $n$. Poiché la varianza della media campionaria diminuisce proporzionalmente a $1/n$, l'incertezza sulla localizzazione del parametro si riduce di conseguenza. In particolare, la larghezza tipica del profilo di verosimiglianza — ad esempio, la sua deviazione standard — è proporzionale a $1/\\sqrt{n}$. Di conseguenza, raddoppiare il numero di osservazioni riduce tale ampiezza di un fattore $\\sqrt{2}$, incrementando in modo sostanziale la precisione dell’inferenza.\n\n### Il caso Bernoulliano\n\nNel caso specifico di variabili di Bernoulli, la varianza non è costante, ma dipende dal parametro $\\theta$ stesso:\n\n$$\n\\text{Var}(X_i \\mid \\theta) = \\theta(1-\\theta).\n$$\n\nDi conseguenza, la varianza della media campionaria (cioè della proporzione osservata) assume la forma:\n\n$$\n\\text{Var}(\\bar{X} \\mid \\theta) = \\frac{\\theta(1-\\theta)}{n}.\n$$\n\nL'**errore standard** della proporzione campionaria, che rappresenta la tipica deviazione di $\\bar{X}$ rispetto al vero $\\theta$, è quindi:\n\n$$\n\\text{SE}(\\bar{X}) = \\sqrt{\\frac{\\theta(1-\\theta)}{n}}.\n$$\n\nQuesta espressione ha un andamento caratteristico: l'incertezza è massima quando $\\theta = 0.5$, ovvero nella situazione di massima variabilità intrinseca di una prova Bernoulliana. Al contrario, l'errore standard si annulla quando $\\theta$ tende a 0 o a 1, situazioni in cui l'esito è praticamente deterministico e quindi l'osservazione di ulteriori dati non aggiunge incertezza sostanziale.\n\n### Visualizzazione: come la verosimiglianza cambia con $n$\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Proporzione osservata fissa\np_obs <- 0.6\n\n# Diverse dimensioni campionarie\nn_values <- c(10, 50, 200)\n\n# Griglia di valori per theta\ntheta_grid <- seq(0.01, 0.99, length.out = 500)\n\n# Calcolo delle verosimiglianze\nlikelihood_data <- do.call(rbind, lapply(n_values, function(n) {\n  y <- round(p_obs * n)  # numero di successi\n  lik <- dbinom(y, size = n, prob = theta_grid)\n  # Normalizziamo per confronto visivo\n  lik_norm <- lik / max(lik)\n  data.frame(\n    theta = theta_grid,\n    likelihood = lik_norm,\n    n = factor(paste0(\"n = \", n), levels = paste0(\"n = \", n_values))\n  )\n}))\n\nggplot(likelihood_data, aes(x = theta, y = likelihood, color = n)) +\n  geom_line(linewidth = 1.2) +\n  geom_vline(xintercept = p_obs, linetype = \"dashed\", color = \"gray40\") +\n  labs(\n    x = expression(theta),\n    y = \"Verosimiglianza (normalizzata)\",\n    color = \"Dimensione\\ncampionaria\"\n  ) +\n  scale_color_manual(values = c(\"#E69F00\", \"#56B4E9\", \"#009E73\")) +\n  theme_minimal() \n```\n\n::: {.cell-output-display}\n![La verosimiglianza diventa più concentrata all'aumentare della dimensione campionaria. Tutti i campioni hanno la stessa proporzione osservata (0.6), ma la precisione aumenta con n.](15_properties_likelihood_files/figure-pdf/fig-likelihood-n-1.png){#fig-likelihood-n fig-align='center' fig-pos='H' width=85%}\n:::\n:::\n\n\nIl grafico mostra chiaramente come la verosimiglianza si restringa attorno al valore osservato $\\bar{X} = 0.6$ all'aumentare di $n$. Con $n = 10$, molti valori di $\\theta$ sono ancora plausibili, mentre con $n = 200$, solo i valori molto vicini a 0.6 hanno una verosimiglianza apprezzabile.\n\n## Precisione e informatività\n\n### La precisione come inverso della varianza\n\nNell'inferenza bayesiana risulta particolarmente efficace ragionare in termini di **precisione**, definita come l'inverso della varianza:\n$$\n\\tau = \\frac{1}{\\sigma^2}.\n$$\n\nQuesta definizione non è meramente formale: la precisione possiede proprietà algebriche che rendono il meccanismo di aggiornamento bayesiano particolarmente chiaro e lineare.\n\nApplicando questo concetto alla media campionaria, otteniamo:\n$$\n\\text{Precisione}(\\bar{X} \\mid \\theta) = \\frac{1}{\\text{Var}(\\bar{X} \\mid \\theta)} = \\frac{n}{\\sigma^2}.\n$$\n\n**Osservazione fondamentale**: la precisione cresce in modo **lineare** con il numero di osservazioni $n$. Ciò significa che ogni nuova osservazione aggiunge una quantità fissa di informazione, indipendentemente dalla dimensione campionaria già raggiunta.\n\n### L'errore standard come misura di informatività\n\nL'errore standard $\\text{SE} = \\sigma/\\sqrt{n}$ quantifica l'incertezza della media campionaria come stimatore del parametro $\\mu$, ovvero la media della popolazione. In termini bayesiani:\n\n- un errore standard piccolo indica che i dati sono molto informativi, ovvero che la verosimiglianza è stretta e concentrata;\n- un errore standard grande indica che i dati sono poco informativi, ovvero che la verosimiglianza è ampia e dispersa.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nn_seq <- 1:200\nsigma <- 1  # varianza unitaria per semplicità\n\nprecision_data <- data.frame(\n  n = n_seq,\n  se = sigma / sqrt(n_seq),\n  precision = n_seq / sigma^2\n)\n\np1 <- ggplot(precision_data, aes(x = n, y = se)) +\n  geom_line(linewidth = 1.2, color = \"#4E79A7\") +\n  labs(\n    x = \"Dimensione campionaria (n)\",\n    y = \"Errore standard\",\n    title = \"Errore standard decresce come 1/√n\"\n  ) +\n  theme_minimal()\n\np2 <- ggplot(precision_data, aes(x = n, y = precision)) +\n  geom_line(linewidth = 1.2, color = \"#E15759\") +\n  labs(\n    x = \"Dimensione campionaria (n)\",\n    y = \"Precisione\",\n    title = \"Precisione cresce linearmente con n\"\n  ) +\n  theme_minimal()\n\np1 + p2\n```\n\n::: {.cell-output-display}\n![Relazione tra dimensione campionaria, errore standard e precisione. Mentre l'errore standard decresce come 1/√n, la precisione cresce linearmente con n.](15_properties_likelihood_files/figure-pdf/fig-precision-vs-n-1.png){#fig-precision-vs-n fig-align='center' fig-pos='H' width=85%}\n:::\n:::\n\n\n## L'aggiornamento bayesiano come combinazione di precisioni\n\n### Il caso gaussiano: una derivazione esplicita\n\nConsideriamo il modello più semplice e rivelatore: osservazioni distribuite normalmente con varianza nota. Supponiamo di avere una credenza iniziale sul parametro $\\theta$, formalizzata da una distribuzione a priori gaussiana, $\\theta \\sim \\mathcal{N}(\\mu_0, \\sigma_0^2)$. Questo esprime la nostra aspettativa che il valore $\\theta$ si trovi intorno a $\\mu_0$, con un'incertezza quantificata da $\\sigma_0^2$.\n\nA questo punto, si raccolgono i dati: $n$ osservazioni indipendenti $X_1, ..., X_n$, ciascuna distribuita come $\\mathcal{N}(\\theta, \\sigma^2)$, dove la varianza $\\sigma^2$ è nota. L'informazione rilevante contenuta in questo campione è sintetizzata dalla media campionaria $\\bar{X}$.\n\nLa verosimiglianza, ovvero la plausibilità dei diversi valori di $\\theta$ alla luce dei dati osservati, assume una forma familiare. Considerata come funzione di $\\theta$, essa è proporzionale a una gaussiana:\n$$\nL(\\theta \\mid \\bar{x}) \\propto \\exp\\left(-\\frac{n(\\bar{x} - \\theta)^2}{2\\sigma^2}\\right).\n$$\nQuesta curva è centrata esattamente sulla media osservata $\\bar{x}$ e ha una varianza pari a $\\sigma^2/n$, il che riflette il fatto che l'incertezza sul valore effettivo di $\\theta$ diminuisce con l'aumentare del numero di osservazioni.\n\n### La distribuzione a posteriori\n\nIl teorema di Bayes ci dice come combinare la nostra conoscenza iniziale con la nuova evidenza:\n$$\np(\\theta \\mid \\bar{x}) \\propto p(\\theta) \\times L(\\theta \\mid \\bar{x}).\n$$\n\nNello specifico, il prodotto di due distribuzioni normali (il prior e la verosimiglianza) genera una nuova distribuzione normale. Pertanto, la nostra credenza aggiornata, o distribuzione a posteriori, sarà ancora una gaussiana:\n$$\n\\theta \\mid \\bar{x} \\sim \\mathcal{N}(\\mu_{\\text{post}}, \\sigma_{\\text{post}}^2),\n$$\ncon una nuova media $\\mu_{\\text{post}}$ e una nuova varianza $\\sigma_{\\text{post}}^2$.\n\n::: {#thm-posterior-gaussian}\n### Aggiornamento bayesiano gaussiano\n\nI parametri di questa nuova distribuzione si calcolano nel modo seguente. La **media a posteriori** $\\mu_{\\text{post}}$ non è altro che una media ponderata tra la nostra convinzione iniziale $\\mu_0$ e l'evidenza dei dati $\\bar{x}$:\n$$\n\\mu_{\\text{post}} = \\frac{\\tau_0 \\mu_0 + \\tau_{\\text{dati}} \\bar{x}}{\\tau_0 + \\tau_{\\text{dati}}},\n$$\ndove i pesi sono le rispettive **precisioni** (gli inversi delle varianze): $\\tau_0 = 1/\\sigma_0^2$ per il prior e $\\tau_{\\text{dati}} = n/\\sigma^2$ per i dati.\n\nAllo stesso modo, la **precisione a posteriori** — che misura quantitativamente la certezza della nostra stima aggiornata — è semplicemente la somma delle precisioni che abbiamo combinato:\n$$\n\\tau_{\\text{post}} = \\tau_0 + \\tau_{\\text{dati}}.\n$$\n:::\n\n### Interpretazione\n\nQueste formule esprimono la logica profonda dell'aggiornamento bayesiano:\n\n1.  **Combinazione ponderata:** la media a posteriori è un compromesso tra la credenza iniziale ($\\mu_0$) e l'evidenza empirica ($\\bar{x}$), ponderato dalle rispettive precisioni. Un'informazione più precisa (maggiore $\\tau$) riceve un peso maggiore nella stima finale.\n\n2.  **Accumulo di informazione:** la precisione a posteriori è sempre superiore sia alla precisione a priori che a quella dei dati presi separatamente. L'informazione si somma, riducendo l'incertezza complessiva.\n\n3.  **Dominanza dei dati:** quando $n$ è grande, $\\tau_{\\text{dati}}$ diventa molto elevata. In tal caso $\\mu_{\\text{post}} \\approx \\bar{x}$ e la distribuzione a posteriori è determinata quasi esclusivamente dall'evidenza empirica.\n\n4.  **Dominanza del prior:** quando $n$ è piccolo o i dati sono molto rumorosi ($\\sigma^2$ grande), $\\tau_{\\text{dati}}$ è modesta. In questa situazione $\\mu_{\\text{post}} \\approx \\mu_0$, e le credenze iniziali rimangono dominanti.\n\n### Esempio numerico\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Parametri del prior\nmu_0 <- 100\nsigma_0 <- 15\ntau_0 <- 1 / sigma_0^2\n\n# Parametri dei dati\nn <- 25\nx_bar <- 115\nsigma <- 20  # deviazione standard nota\ntau_data <- n / sigma^2\n\n# Calcolo della posterior\ntau_post <- tau_0 + tau_data\nsigma_post <- sqrt(1 / tau_post)\nmu_post <- (tau_0 * mu_0 + tau_data * x_bar) / tau_post\n\n# Griglia di valori\ntheta_grid <- seq(60, 150, length.out = 500)\n\n# Calcolo delle distribuzioni\nprior_density <- dnorm(theta_grid, mu_0, sigma_0)\nlikelihood <- dnorm(theta_grid, x_bar, sigma / sqrt(n))\nposterior_density <- dnorm(theta_grid, mu_post, sigma_post)\n\n# Normalizzazione per visualizzazione\nlikelihood_norm <- likelihood * max(prior_density) / max(likelihood)\n\nplot_data <- data.frame(\n  theta = rep(theta_grid, 3),\n  density = c(prior_density, likelihood_norm, posterior_density),\n  type = factor(rep(c(\"Prior\", \"Verosimiglianza\", \"Posterior\"), each = length(theta_grid)),\n                levels = c(\"Prior\", \"Verosimiglianza\", \"Posterior\"))\n)\n\nggplot(plot_data, aes(x = theta, y = density, color = type, linetype = type)) +\n  geom_line(linewidth = 1.2) +\n  scale_color_manual(values = c(\"#4E79A7\", \"#E69F00\", \"#59A14F\")) +\n  scale_linetype_manual(values = c(\"solid\", \"dashed\", \"solid\")) +\n  labs(\n    x = expression(theta),\n    y = \"Densità\",\n    color = \"\",\n    linetype = \"\"\n  ) +\n  theme_minimal() \n```\n\n::: {.cell-output-display}\n![Aggiornamento bayesiano: il prior (blu), la verosimiglianza (arancione) e la distribuzione a posteriori (verde). La posterior è un compromesso tra prior e dati, pesato dalle rispettive precisioni.](15_properties_likelihood_files/figure-pdf/fig-bayesian-update-1.png){#fig-bayesian-update fig-align='center' fig-pos='H' width=85%}\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Stampa dei risultati\ncat(\"Prior: N(\", mu_0, \", \", sigma_0, \"²)\\n\", sep = \"\")\n#> Prior: N(100, 15²)\ncat(\"Dati: n =\", n, \", media campionaria =\", x_bar, \"\\n\")\n#> Dati: n = 25 , media campionaria = 115\ncat(\"Precisione prior:\", round(tau_0, 6), \"\\n\")\n#> Precisione prior: 0.00444\ncat(\"Precisione dati:\", round(tau_data, 6), \"\\n\")\n#> Precisione dati: 0.0625\ncat(\"Precisione posterior:\", round(tau_post, 6), \"\\n\")\n#> Precisione posterior: 0.0669\ncat(\"\\nMedia posterior:\", round(mu_post, 2), \"\\n\")\n#> \n#> Media posterior: 114\ncat(\"Deviazione standard posterior:\", round(sigma_post, 2), \"\\n\")\n#> Deviazione standard posterior: 3.86\n```\n:::\n\n\n::: {.callout-note}\n### Il peso relativo di prior e dati\n\nIn questo esempio, la precisione dei dati ($\\tau_{\\text{dati}} = 0.062$) è circa 14.1 volte maggiore della precisione del prior ($\\tau_0 = 0.004$). Di conseguenza, la media a posteriori (114) è molto più vicina alla media campionaria (115) che alla media a priori (100).\n:::\n\n## La Legge dei Grandi Numeri e la convergenza bayesiana\n\nTra i risultati fondamentali della teoria della probabilità, la **Legge dei Grandi Numeri (LGN)** descrive come l’informazione fornita dai dati tenda a stabilizzarsi con l’aumentare delle osservazioni. Nella sua interpretazione più intuitiva, essa afferma che, ripetendo molte volte un esperimento nelle stesse condizioni, la frequenza relativa di un evento si avvicina sempre di più alla sua probabilità teorica.\n\nFormalmente, se $X_1, \\dots, X_n$ sono variabili aleatorie indipendenti e identicamente distribuite con valore atteso $\\mu$, la media campionaria\n\n$$\n\\bar X_n = \\frac{1}{n}\\sum_{i=1}^{n} X_i\n$$\ntende, al crescere di $n$, a concentrarsi attorno alla quantità costante $\\mu$. Questa convergenza non significa che gli scarti dal valore vero scompaiono, ma che diventano **sempre meno probabili**: la media può ancora fluttuare, ma tali oscillazioni risulteranno via via più contenute e statisticamente trascurabili rispetto a $\\mu$.\n\n### Conseguenze per la verosimiglianza\n\nLa LGN esercita un’influenza diretta sulla funzione di verosimiglianza, poiché ne determina il comportamento asintotico. Quando lo stimatore di massima verosimiglianza coincide con una statistica campionaria — come accade per la media nei modelli gaussiani — esso converge al valore vero del parametro. Di conseguenza, la verosimiglianza concentra progressivamente tutta la propria massa attorno a tale valore, restringendo lo spazio dei parametri plausibili. L’accumularsi dei dati non elimina l’incertezza, ma la rende sempre più localizzata: le alternative al valore corretto non scompaiono, ma diventano via via meno credibili fino a risultare statisticamente trascurabili.\n\n### Conseguenze per l’inferenza bayesiana: consistenza\n\nQuesto comportamento si riflette in modo naturale sull’aggiornamento delle credenze nell’ambito bayesiano, dando luogo al principio della **consistenza bayesiana**.\n\n::: {#thm-bayesian-consistency}\n\n### Consistenza bayesiana\n\nSe la distribuzione a priori assegna probabilità positiva a ogni intorno del valore vero $\\theta_0$, allora, quando $n \\to \\infty$, la distribuzione a posteriori converge a una distribuzione degenerata concentrata interamente in $\\theta_0$.\n:::\n\nLa rilevanza di questo risultato è concettuale oltre che operativa. L’inferenza bayesiana si presenta come un procedimento **auto-correttivo**: qualsiasi prior a supporto positivo — cioè che non escluda a priori il valore vero — conduce alle stesse conclusioni quando l’evidenza empirica diventa sufficientemente ricca. Le credenze iniziali possono essere imprecise o addirittura fuorvianti, ma l’accumulo dei dati le spinge gradualmente verso la realtà, rendendo l’analisi sempre più dominata dall’informazione proveniente dai dati stessi. Al crescere della dimensione del campione, la distribuzione a posteriori diventa quindi una rappresentazione sempre più accurata e concentrata del parametro che governa il fenomeno in esame.\n\n### Simulazione: convergenza con prior diversi\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(42)\ntheta_true <- 0.45\nn_values <- c(10, 50, 200, 1000)\n\n# Prior diversi\npriors <- list(\n  A = c(2, 8),   # Prior pessimista (media = 0.2)\n  B = c(8, 2),   # Prior ottimista (media = 0.8)\n  C = c(1, 1)    # Prior uniforme (media = 0.5)\n)\n\n# Funzione per calcolare la posterior Beta\ncompute_posterior <- function(prior_params, n, theta_true) {\n  y <- rbinom(1, n, theta_true)\n  c(prior_params[1] + y, prior_params[2] + n - y)\n}\n\n# Generazione dei dati per il plot\nset.seed(42)\ntheta_grid <- seq(0.01, 0.99, length.out = 300)\n\nall_data <- do.call(rbind, lapply(n_values, function(n) {\n  do.call(rbind, lapply(names(priors), function(name) {\n    post <- compute_posterior(priors[[name]], n, theta_true)\n    data.frame(\n      theta = theta_grid,\n      density = dbeta(theta_grid, post[1], post[2]),\n      researcher = name,\n      n = n\n    )\n  }))\n}))\n\nall_data$n_label <- factor(paste(\"n =\", all_data$n), \n                           levels = paste(\"n =\", n_values))\nall_data$researcher <- factor(all_data$researcher,\n                              labels = c(\"Prior pessimista (β = 0.2)\",\n                                        \"Prior ottimista (β = 0.8)\", \n                                        \"Prior uniforme\"))\n\nggplot(all_data, aes(x = theta, y = density, color = researcher)) +\n  geom_line(linewidth = 1) +\n  geom_vline(xintercept = theta_true, linetype = \"dashed\", \n             color = \"gray40\", linewidth = 0.8) +\n  facet_wrap(~ n_label, scales = \"free_y\", ncol = 2) +\n  scale_color_manual(values = c(\"#4E79A7\", \"#E15759\", \"#59A14F\")) +\n  labs(\n    x = expression(theta),\n    y = \"Densità a posteriori\",\n    color = \"Ricercatore\"\n  ) +\n  theme_minimal() +\n  theme(legend.position = \"bottom\")\n```\n\n::: {.cell-output-display}\n![Convergenza bayesiana: tre ricercatori con prior molto diversi convergono alla stessa conclusione all'aumentare dei dati. La linea verticale indica il valore vero θ₀ = 0.45.](15_properties_likelihood_files/figure-pdf/fig-convergence-1.png){#fig-convergence fig-align='center' fig-pos='H' width=85%}\n:::\n:::\n\n\n**Osservazioni.**\nCon un campione ridotto di $n = 10$ unità, le distribuzioni a posteriori rimangono nettamente diverse tra loro, riflettendo ancora fortemente l'influenza delle diverse credenze iniziali. Con l'aumentare della dimensione del campione, con $n = 50$ si inizia a osservare un chiaro avvicinamento. Quando si raggiungono $n = 200$ osservazioni, le distribuzioni sono sostanzialmente sovrapposte, il che indica che l'evidenza empirica sta prevalendo. Infine, con $n = 1000$ le distribuzioni a posteriori sono praticamente indistinguibili e tutte fortemente concentrate attorno al valore vero del parametro, a dimostrazione della proprietà di consistenza dell'inferenza bayesiana.\n\n## Il Teorema del Limite Centrale e l’approssimazione normale\n\n### Enunciato del Teorema del Limite Centrale\n\nIl **Teorema del Limite Centrale (TLC)** è un raffinamento della legge dei grandi numeri che rende più precisa la convergenza delle medie empiriche.  Esso afferma che, indipendentemente dalla forma della distribuzione delle singole osservazioni, la media campionaria tende a una distribuzione normale.\n\n::: {#thm-clt}\n\n### Teorema del Limite Centrale\n\nPer osservazioni i.i.d. con $\\mathbb{E}[X_i] = \\mu$ e $\\mathrm{Var}(X_i) = \\sigma^2 < \\infty$,\n$$\n\\bar{X}_n \\;\\dot\\sim\\; \\mathcal{N}\\!\\left(\\mu, \\frac{\\sigma^2}{n}\\right) \\qquad \\text{per } n \\text{ sufficientemente grande}.\n$$\n:::\n\nQuesto risultato di “universalità” delle densità gaussiane fornisce quindi una giustificazione della loro applicazione così diffusa in molteplici ambiti.\n\n### Conseguenza per la verosimiglianza\n\nPoiché la verosimiglianza spesso dipende dalla media campionaria, il TLC implica che, per campioni sufficientemente ampi, essa assuma una forma **approssimativamente normale** rispetto al parametro:\n$$\nL(\\theta \\mid \\bar{x}) \\;\\approx\\; \\mathcal{N}\\!\\left(\\bar{x}, \\frac{\\sigma^2}{n}\\right)\n\\qquad \\text{interpretata come funzione di } \\theta.\n$$\n\nQuesta gaussianità non deriva dalla distribuzione delle singole osservazioni, ma dal comportamento aggregato delle loro medie. Anche quando i dati provengono da popolazioni con forme molto diverse dalla normale, la verosimiglianza tende a seguire una struttura gaussiana: la normalità emerge *dal campionamento*, non dalla popolazione di origine.\n\n### Conseguenza per l’inferenza bayesiana: il teorema di Bernstein–von Mises\n\nL'approssimazione normale della verosimiglianza si propaga in modo diretto alla distribuzione a posteriori, dando luogo a un risultato centrale della teoria bayesiana.\n\n::: {#thm-bvm}\n\n### Teorema di Bernstein–von Mises \n\nSotto condizioni di regolarità, per campioni sufficientemente grandi, la distribuzione a posteriori può essere approssimata accuratamente da una distribuzione normale:\n$$\np(\\theta \\mid X_1, \\ldots, X_n) \\approx \\mathcal{N}(\\hat{\\theta}_n,\\, I_n^{-1}),\n$$\ndove $\\hat{\\theta}_n$ è lo stimatore di massima verosimiglianza e $I_n$ rappresenta l’*informazione di Fisher* osservata, che misura la quantità di informazione sul parametro contenuta nel campione.\n:::\n\n**Interpretazione pratica.** La conseguenza principale è di natura computazionale. Grazie all'approssimazione normale, il calcolo della distribuzione a posteriori, che spesso è complesso o addirittura intrattabile, può essere sostituito da formule approssimate più semplici, anche in modelli non gaussiani. Questa semplificazione consente di applicare l'inferenza bayesiana a una vasta gamma di problemi, anche quando i modelli sottostanti non sono trattabili analiticamente.\n\n### Visualizzazione: il TLC in una popolazione non normale\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(42)\n\n# Popolazione: distribuzione uniforme (non gaussiana)\npopulation <- runif(1e6, min = 0, max = 1)\n\n# Funzione per simulare distribuzioni campionarie\nsimulate_sampling_dist <- function(pop, sample_size, n_samples = 1e5) {\n  replicate(n_samples, mean(sample(pop, sample_size, replace = TRUE)))\n}\n\n# Diverse dimensioni campionarie\nsample_sizes <- c(1, 5, 30)\n\nsampling_data <- do.call(rbind, lapply(sample_sizes, function(n) {\n  means <- simulate_sampling_dist(population, n)\n  data.frame(\n    mean = means,\n    n = factor(paste(\"n =\", n), levels = paste(\"n =\", sample_sizes))\n  )\n}))\n\nggplot(sampling_data, aes(x = mean)) +\n  geom_histogram(aes(y = after_stat(density)), bins = 40, \n                 fill = \"#4E79A7\", alpha = 0.7) +\n  stat_function(fun = dnorm, \n                args = list(mean = 0.5, sd = sqrt(1/12) / sqrt(30)),\n                data = subset(sampling_data, n == \"n = 30\"),\n                color = \"#E15759\", linewidth = 1.2) +\n  facet_wrap(~ n, scales = \"free_y\") +\n  labs(\n    x = \"Media campionaria\",\n    y = \"Densità\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![Il Teorema del Limite Centrale in azione: anche partendo da una distribuzione uniforme, la distribuzione delle medie campionarie converge rapidamente a una forma gaussiana.](15_properties_likelihood_files/figure-pdf/fig-clt-1.png){#fig-clt fig-align='center' fig-pos='H' width=85%}\n:::\n:::\n\n\nCon un solo dato ($n = 1$), la distribuzione delle \"medie campionarie\" è semplicemente la distribuzione uniforme originale da cui i dati sono tratti. Già con $n = 5$ osservazioni, inizia a delinearsi una forma a campana. Quando si arriva a $n = 30$, la distribuzione diventa praticamente indistinguibile da una curva normale, offrendo una dimostrazione visiva immediata dell'universalità del TLC.\n\n## Combinazione di evidenze da studi multipli\n\n### Il principio della somma delle precisioni\n\nUna delle applicazioni più eleganti dell'approccio bayesiano è la **sintesi di evidenze** provenienti da studi indipendenti. Quando più ricerche indagano lo stesso parametro $\\theta$, le loro informazioni possono essere combinate in modo naturale e coerente.\n\nSe ciascuno studio $i$ fornisce una stima $\\bar{x}_i$ con una corrispondente precisione $\\tau_i$ (l'inverso della sua varianza), la stima combinata risulta essere una **media ponderata**:\n$$\n\\bar{x}_{\\text{comb}} = \\frac{\\sum_i \\tau_i \\bar{x}_i}{\\sum_i \\tau_i},\n$$\ndove i pesi sono proprio le precisioni individuali. La precisione totale della stima sintetica è semplicemente la somma delle precisioni degli studi:\n$$\n\\tau_{\\text{comb}} = \\sum_i \\tau_i.\n$$\n\n### Esempio: sintesi di due studi\n\nConsideriamo due studi indipendenti che stimano la prevalenza di un sintomo:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Parametri degli studi\nstudi <- data.frame(\n  studio = c(\"A\", \"B\"),\n  n = c(50, 200),\n  proporzione = c(0.42, 0.38),\n  se = c(0.07, 0.035)  # Errore standard\n)\n\n# Calcolo delle precisioni (inverso della varianza)\nstudi$precisione <- 1 / studi$se^2\n\n# Sintesi bayesiana (combinazione delle normali)\nprecisione_totale <- sum(studi$precisione)\nmedia_combinata <- sum(studi$precisione * studi$proporzione) / precisione_totale\nse_combinato <- sqrt(1 / precisione_totale)\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```\n#> Stima combinata: 0.388\n#> Errore standard combinato: 0.0313\n#> Confronto precisioni:\n#> - Studio A (n=50): SE = 0.07 → Precisione = 204\n#> - Studio B (n=200): SE = 0.035 → Precisione = 816\n#> - Stima combinata: SE = 0.0313 → Precisione = 1020\n```\n:::\n\n\n**Risultato principale:** la sintesi produce una stima con un errore standard minore (0.031) rispetto a quello di entrambi gli studi presi singolarmente Ciò significa che la **precisione della stima combinata** (pari a 1020.4) è superiore alla precisione di ciascuno studio preso separatamente. Ciò dimostra concretamente come la combinazione di più fonti di evidenza, ponderate in base alla loro affidabilità, porti a una conclusione più robusta e meno incerta.[^cue-combination]\n\n[^cue-combination]: Questo principio, che formalizza il modo *ottimale* di combinare informazioni incerte, ha ispirato e motivato una vasta quantità di ricerche empiriche nel campo delle Scienze della Visione. In particolare, ci si è chiesti se il sistema visivo umano si comporti come un \"osservatore ideale\", ovvero se integri le informazioni in modo statisticamente ottimale e coerente con l'integrazione bayesiana. Questa domanda ha motivato molti studi condotti per comprendere come un individuo integri segnali visivi che possono essere parzialmente discordanti, come ad esempio quelli provenienti dalla stereopsi e dalla parallasse di movimento [@domini2011combining].\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ntheta_grid <- seq(0.2, 0.6, length.out = 500)\n\nmeta_data <- data.frame(\n  theta = rep(theta_grid, 3),\n  density = c(\n    dnorm(theta_grid, studi$proporzione[1], studi$se[1]),\n    dnorm(theta_grid, studi$proporzione[2], studi$se[2]),\n    dnorm(theta_grid, media_combinata, se_combinato)\n  ),\n  studio = factor(rep(c(\"Studio A (n=50)\", \"Studio B (n=200)\", \"Combinato\"), \n                      each = length(theta_grid)),\n                  levels = c(\"Studio A (n=50)\", \"Studio B (n=200)\", \"Combinato\"))\n)\n\nggplot(meta_data, aes(x = theta, y = density, color = studio, linetype = studio)) +\n  geom_line(linewidth = 1.2) +\n  scale_color_manual(values = c(\"#4E79A7\", \"#E69F00\", \"#59A14F\")) +\n  scale_linetype_manual(values = c(\"dashed\", \"dashed\", \"solid\")) +\n  labs(\n    x = expression(theta),\n    y = \"Densità\",\n    color = \"\",\n    linetype = \"\"\n  ) +\n  theme_minimal() \n```\n\n::: {.cell-output-display}\n![Combinazione di evidenze. Lo studio B (n=200), avendo una precisione notevolmente maggiore, contribuisce di più alla stima combinata (linea verde). L'intervallo di credibilità risultante è più stretto di quello di ciascuno studio preso singolarmente.](15_properties_likelihood_files/figure-pdf/fig-meta-analysis-1.png){#fig-meta-analysis fig-align='center' fig-pos='H' width=85%}\n:::\n:::\n\n\n::: {.callout-note}\n### Il peso dell'evidenza\n\nLa stima combinata (0.388) risulta più vicina al valore riportato dallo studio B (0.38) rispetto a quello dello studio A (0.42). Ciò è dovuto al fatto che lo studio B, grazie alla sua maggiore dimensione campionaria, presenta una maggiore precisione e quindi riceve un peso maggiore nella media ponderata. Il principio che emerge è intuitivo: nella sintesi delle evidenze scientifiche, le stime basate su campioni più ampi e quelle meno incerte esercitano un'influenza proporzionalmente maggiore sul risultato finale, garantendo che la conclusione complessiva rifletta in modo ottimale l'affidabilità delle fonti disponibili.\n:::\n\n## Limiti dell'inferenza: precisione vs. accuratezza\n\n### L'errore standard quantifica solo l'incertezza campionaria\n\nÈ cruciale distinguere due dimensioni distinte dell'inferenza statistica. Tutte le proprietà matematiche discusse in questo capitolo, quali la convergenza della verosimiglianza, il restringimento della distribuzione a posteriori e la riduzione dell'errore standard, riguardano esclusivamente la **precisione** della stima, ovvero la riduzione dell'incertezza dovuta alla variabilità campionaria.\n\nQuesti risultati non mitigano né possono correggere eventuali **distorsioni sistematiche** (*bias*) introdotte nelle fasi di progettazione, misurazione o raccolta dei dati. Una stima può essere estremamente precisa (con un intervallo di credibilità molto stretto), ma può comunque essere profondamente inaccurata (lontana dal valore vero del parametro) se è affetta da *bias* non considerati.\n\n### Fonti di distorsione sistematica\n\nNella ricerca applicata, soprattutto in ambito psicologico e sociale, sono frequenti distorsioni che alterano i risultati in modo prevedibile. Anche un’analisi statistica formalmente corretta può condurre a conclusioni fuorvianti se tali distorsioni non vengono prevenute o controllate.\n\n**Distorsione da selezione.**\nSi verifica quando il campione studiato non rappresenta la popolazione a cui si desidera estendere le inferenze. In questi casi, la generalizzabilità dei risultati è compromessa. Tra le cause tipiche vi sono il basso tasso di partecipazione, il reclutamento opportunistico (*convenience sampling*) o l'autoselezione, in cui partecipano preferenzialmente individui con caratteristiche particolari (per esempio, maggiore motivazione o familiarità con il tema).\n\n**Distorsione da desiderabilità sociale.**\nConsiste nella tendenza a fornire risposte ritenute più accettabili o approvate socialmente, invece di riportare ciò che si pensa o si fa realmente. Questa distorsione riguarda in particolare costrutti “sensibili” (come pregiudizi, l'uso di sostanze e i problemi alimentari) e minaccia soprattutto la validità di costrutto, poiché le risposte raccolte non rappresentano più il fenomeno psicologico che si intende misurare.\n\n**Errori di misurazione.**\nSi verificano quando gli strumenti utilizzati non riescono a catturare correttamente il costrutto teorico o producono misurazioni instabili. L’assenza di validità porta a misurare qualcosa di diverso da ciò che si intende studiare, mentre l’assenza di affidabilità introduce fluttuazioni casuali che aumentano il rumore e nascondono il segnale reale. In entrambi i casi, le stime ottenute risultano distorte o indebolite rispetto al fenomeno reale.\n\n### Il paradosso della falsa precisione\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Precisione e accuratezza nell'inferenza. La situazione più pericolosa è l'alta precisione con bassa accuratezza (in alto a destra): stime molto sicure ma sistematicamente sbagliate.](15_properties_likelihood_files/figure-pdf/fig-precision-accuracy-1.png){#fig-precision-accuracy fig-align='center' width=85%}\n:::\n:::\n\n\n::: {.callout-warning title=\"Il pericolo della falsa precisione\"}\nLa combinazione più insidiosa si verifica quando un'elevata precisione si accompagna a una scarsa accuratezza (quadrante in alto a destra). In questo scenario, il procedimento inferenziale produce intervalli di credibilità molto stretti, che suggeriscono una grande certezza, attorno a valori che sono invece sistematicamente distorti.\n\nUn campione numericamente grande ma affetto da un bias sistematico può essere **più fuorviante** di un campione piccolo ma non distorto: genera stime apparentemente robuste che, però, consolidano una conclusione errata, creando un'illusione di conoscenza scientificamente fondata.\n:::\n\n### Strategie di mitigazione\n\nLa consapevolezza di questi limiti suggerisce alcune linee d'azione per condurre una ricerca più solida.\n\n**Progettazione metodologica rigorosa**: il controllo delle distorsioni avviene principalmente nella fase di progettazione dello studio, attraverso il campionamento probabilistico, la randomizzazione, la definizione di protocolli standardizzati e la validazione degli strumenti di misurazione.\n\n**Analisi di sensibilità**: l'approccio bayesiano consente di modellare esplicitamente le fonti di incertezza non campionaria e di esplorare come le conclusioni cambino in base a diverse ipotesi sull'entità dei possibili bias.\n\n**Trasparenza epistemica**: è essenziale comunicare chiaramente che gli intervalli di credibilità quantificano solo l'incertezza campionaria e non l'affidabilità complessiva del disegno di ricerca. La valutazione critica delle potenziali distorsioni rimane comunque un compito fondamentale per il ricercatore.\n\n## Riflessioni conclusive {.unnumbered .unlisted}\n\nQuesto capitolo ha stabilito il collegamento fondamentale tra le proprietà matematiche della distribuzione campionaria e il meccanismo dell'aggiornamento bayesiano.\n\nLe proprietà della media campionaria — $\\mathbb{E}[\\bar{X}] = \\theta$ e $\\text{Var}(\\bar{X}) = \\sigma^2/n$ — determinano la forma della funzione di verosimiglianza: centrata sul valore osservato e sempre più concentrata all'aumentare dei dati. Queste proprietà, a loro volta, determinano come la distribuzione a posteriori risponde all'evidenza empirica.\n\nNel caso gaussiano l'aggiornamento assume una forma particolarmente trasparente: la precisione a posteriori è la somma delle precisioni del prior e dei dati, mentre la media a posteriori ne è la media ponderata. Questo schema si generalizza, in modo approssimato, a una vasta classe di modelli grazie al TLC, che giustifica l'approssimazione normale per campioni sufficientemente ampi.\n\nLa LGN garantisce la **consistenza** dell'inferenza bayesiana: con un numero sufficiente di osservazioni, la distribuzione a posteriori converge al valore vero del parametro, indipendentemente dalla distribuzione a priori adottata. Questo risultato conferisce robustezza epistemica al procedimento: l'evidenza empirica, quando abbondante, prevale sulle convinzioni iniziali.\n\nIl TLC spiega l'ubiquità della forma normale nella distribuzione a posteriori per campioni di grandi dimensioni, fornendo il fondamento teorico per molte delle approssimazioni pratiche utilizzate nell'inferenza.\n\nÈ tuttavia cruciale riconoscere i **limiti** intrinseci di questi risultati. Tutte le proprietà discusse si riferiscono esclusivamente all'incertezza campionaria — la variabilità introdotta dalla natura casuale del campionamento. Esse non possono né correggere né mitigare distorsioni sistematiche (bias) legate al disegno di ricerca o alla misurazione. La precisione statistica, quindi, non deve mai essere confusa con la validità scientifica.\n\nNei capitoli successivi del manuale principale, questi principi teorici troveranno applicazione concreta nella costruzione, stima e interpretazione di modelli bayesiani per la ricerca psicologica.\n\n::: {.callout-note collapse=true title=\"Informazioni sull'ambiente di sviluppo\"}\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsessionInfo()\n#> R version 4.5.2 (2025-10-31)\n#> Platform: aarch64-apple-darwin20\n#> Running under: macOS Tahoe 26.1\n#> \n#> Matrix products: default\n#> BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib \n#> LAPACK: /Library/Frameworks/R.framework/Versions/4.5-arm64/Resources/lib/libRlapack.dylib;  LAPACK version 3.12.1\n#> \n#> locale:\n#> [1] C.UTF-8/UTF-8/C.UTF-8/C/C.UTF-8/C.UTF-8\n#> \n#> time zone: Europe/Rome\n#> tzcode source: internal\n#> \n#> attached base packages:\n#> [1] stats     graphics  grDevices utils     datasets  methods   base     \n#> \n#> other attached packages:\n#>  [1] pillar_1.11.1         tinytable_0.15.1      patchwork_1.3.2      \n#>  [4] ggdist_3.3.3          tidybayes_3.0.7       bayesplot_1.14.0     \n#>  [7] ggplot2_4.0.1         reliabilitydiag_0.2.1 priorsense_1.2.0     \n#> [10] posterior_1.6.1       loo_2.8.0             rstan_2.32.7         \n#> [13] StanHeaders_2.32.10   brms_2.23.0           Rcpp_1.1.0           \n#> [16] sessioninfo_1.2.3     conflicted_1.2.0      janitor_2.2.1        \n#> [19] matrixStats_1.5.0     modelr_0.1.11         tibble_3.3.0         \n#> [22] dplyr_1.1.4           tidyr_1.3.1           rio_1.2.4            \n#> [25] here_1.0.2           \n#> \n#> loaded via a namespace (and not attached):\n#>  [1] svUnit_1.0.8          tidyselect_1.2.1      farver_2.1.2         \n#>  [4] S7_0.2.1              fastmap_1.2.0         TH.data_1.1-5        \n#>  [7] tensorA_0.36.2.1      digest_0.6.39         timechange_0.3.0     \n#> [10] estimability_1.5.1    lifecycle_1.0.4       survival_3.8-3       \n#> [13] magrittr_2.0.4        compiler_4.5.2        rlang_1.1.6          \n#> [16] tools_4.5.2           yaml_2.3.10           knitr_1.50           \n#> [19] labeling_0.4.3        bridgesampling_1.2-1  curl_7.0.0           \n#> [22] pkgbuild_1.4.8        RColorBrewer_1.1-3    abind_1.4-8          \n#> [25] multcomp_1.4-29       withr_3.0.2           purrr_1.2.0          \n#> [28] grid_4.5.2            stats4_4.5.2          colorspace_2.1-2     \n#> [31] xtable_1.8-4          inline_0.3.21         emmeans_2.0.0        \n#> [34] scales_1.4.0          MASS_7.3-65           cli_3.6.5            \n#> [37] mvtnorm_1.3-3         rmarkdown_2.30        ragg_1.5.0           \n#> [40] generics_0.1.4        RcppParallel_5.1.11-1 cachem_1.1.0         \n#> [43] stringr_1.6.0         splines_4.5.2         parallel_4.5.2       \n#> [46] vctrs_0.6.5           V8_8.0.1              Matrix_1.7-4         \n#> [49] sandwich_3.1-1        jsonlite_2.0.0        arrayhelpers_1.1-0   \n#> [52] systemfonts_1.3.1     glue_1.8.0            codetools_0.2-20     \n#> [55] distributional_0.5.0  lubridate_1.9.4       stringi_1.8.7        \n#> [58] gtable_0.3.6          QuickJSR_1.8.1        htmltools_0.5.8.1    \n#> [61] Brobdingnag_1.2-9     R6_2.6.1              textshaping_1.0.4    \n#> [64] rprojroot_2.1.1       evaluate_1.0.5        lattice_0.22-7       \n#> [67] backports_1.5.0       memoise_2.0.1         broom_1.0.10         \n#> [70] snakecase_0.11.1      rstantools_2.5.0      coda_0.19-4.1        \n#> [73] gridExtra_2.3         nlme_3.1-168          checkmate_2.3.3      \n#> [76] xfun_0.54             zoo_1.8-14            pkgconfig_2.0.3\n```\n:::\n\n:::\n\n## Bibliografia {.unnumbered .unlisted}\n",
    "supporting": [
      "15_properties_likelihood_files/figure-pdf"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{},\"value\":[]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}